// Schnellkochtopf-Anleitungen – Teil 3
(typeof window !== 'undefined' ? window : globalThis).DK = Object.assign((typeof window !== 'undefined' ? window : globalThis).DK || {}, {
  'bbq-pulled-chicken-coleslaw': {
    t: 40,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf mit Dämpfeinsatz und Dreifuß. Mindestens 250 ml Flüssigkeit, max. 2/3 füllen. Ersetzt das 40-minütige Backen der Süßkartoffeln.',
    steps: [
      ['Ketchup, Essig, Senf, Honig, geräuchertes Paprikapulver und fein gewürfelte Zwiebel im Topf mit 250 ml Wasser verrühren.', '', '', ''],
      ['Hähnchenschenkel in die Sauce legen. Für Baby/Kleinkind einen Schenkel in einer kleinen hitzefesten Schale mit etwas Wasser (ohne Sauce) bereitstellen.', '', '', ''],
      ['Dreifuß einsetzen, Einsatz mit den längs halbierten, ungeschälten Süßkartoffeln und der Baby-Schale darauf, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 2. Ring erscheint, dann Hitze reduzieren und garen.', '2', '12 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen. Inzwischen Kohl und Karotte hobeln und mit Joghurt, Mayo, Essig und Salz zum Coleslaw mischen.', '', '', 'natürlich'],
      ['Süßkartoffeln und Baby-Schale herausnehmen. Hähnchen im Topf mit zwei Gabeln zerzupfen und offen 5 Min. sämig einkochen.', '', '', ''],
      ['Süßkartoffeln aufschneiden, mit Pulled Chicken füllen und mit Coleslaw servieren.', '', '', ''],
    ],
  },
  'haehnchenkeulen-blech-rosmarinkartoffeln': {
    t: 45,
    fit: 2,
    note: 'Für ca. 4 Portionen, 6-l-Topf. Mindestens 250 ml Flüssigkeit, max. 2/3 füllen. Geschmort statt geröstet – wer Kruste mag, die Keulen danach 5 Min. unter den Backofengrill legen.',
    steps: [
      ['Hähnchenkeulen ohne Haut mit Paprikapulver und Thymian einreiben und im offenen Topf in der Hälfte des Öls portionsweise rundum anbraten, herausnehmen.', '', '', ''],
      ['Zwiebelspalten im restlichen Öl kurz anbraten, mit 250 ml Wasser ablöschen und den Bratsatz vom Topfboden lösen.', '', '', ''],
      ['Geviertelte Kartoffeln, Karotten in 4 cm großen Stücken und Rosmarin hineingeben, Keulen obenauf legen, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 2. Ring erscheint, dann Hitze reduzieren und garen.', '2', '12 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest salzen und mit Kräuterjoghurt servieren.', '', '', ''],
    ],
  },
  'haehnchen-erbsen-risotto': {
    t: 28,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5-l-Topf. Im Schnellkochtopf genügt weniger Brühe: ca. 750 ml auf 300 g Reis. Max. halb füllen. Kein Rühren nötig.',
    steps: [
      ['Hähnchenwürfel im offenen Topf in der Hälfte des Öls 3 Min. anbraten und herausnehmen.', '', '', ''],
      ['Zwiebel im restlichen Öl glasig dünsten, Reis 1 Min. mitrösten.', '', '', ''],
      ['Mit ca. 750 ml heißer Brühe ablöschen, Bodensatz lösen, Hähnchen zurück in den Topf geben, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 1. Ring erscheint, dann Hitze reduzieren und garen.', '1', '6 Min.', ''],
      ['Druck sofort über das Ventil ablassen.', '', '', 'schnell'],
      ['Erbsen einrühren und offen 2–3 Min. mitziehen lassen. Baby-Portion vor Parmesan und Salz entnehmen.', '', '', ''],
      ['Butter, Parmesan und Zitronenabrieb unterrühren, 2 Min. ruhen lassen und mit Petersilie servieren.', '', '', ''],
    ],
  },
  'ratatouille-haehnchen': {
    t: 32,
    fit: 2,
    note: 'Für ca. 4 Portionen, 6-l-Topf. Mindestens 250 ml Flüssigkeit (Tomaten + 100 ml Wasser), max. 2/3 füllen. Reis parallel im offenen Topf garen.',
    steps: [
      ['Aubergine im offenen Topf in 2/3 des Öls 5 Min. anbraten, Zwiebel und Paprika 3 Min. mitbraten.', '', '', ''],
      ['Tomaten, 100 ml Wasser, Knoblauch und Kräuter der Provence zugeben und den Bodensatz lösen.', '', '', ''],
      ['Hähnchenwürfel und Zucchini in groben Stücken obenauf geben, nicht umrühren, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 1. Ring erscheint, dann Hitze reduzieren und garen.', '1', '5 Min.', ''],
      ['Druck sofort über das Ventil ablassen.', '', '', 'schnell'],
      ['Baby-Portion entnehmen, Rest offen kurz einkochen, mit Salz und Pfeffer abschmecken und mit Basilikum und Reis servieren.', '', '', ''],
    ],
  },
  'paella-haehnchen-garnelen': {
    t: 32,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Ca. 700 ml Brühe auf 300 g Reis, max. halb füllen. Ohne Kruste (Socarrat), dafür ohne Aufpassen.',
    steps: [
      ['Hähnchenwürfel im offenen Topf im Öl 4 Min. anbraten, Zwiebel, Paprika und Knoblauch 3 Min. mitbraten.', '', '', ''],
      ['Tomate, Paprikapulver und Safran zugeben, Reis einstreuen und 1 Min. mitrösten.', '', '', ''],
      ['Mit ca. 700 ml heißer Brühe ablöschen, Bodensatz lösen, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 1. Ring erscheint, dann Hitze reduzieren und garen.', '1', '6 Min.', ''],
      ['Druck sofort über das Ventil ablassen.', '', '', 'schnell'],
      ['Garnelen und Erbsen in den Reis drücken und bei aufgelegtem (nicht verriegeltem) Deckel 4 Min. gar ziehen lassen.', '', '', ''],
      ['Baby-Portion entnehmen, Rest leicht salzen, 3 Min. ruhen lassen und mit Zitronenspalten servieren.', '', '', ''],
    ],
  },
  'kuerbisrisotto-feta-edamame': {
    t: 25,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5-l-Topf. Ca. 550 ml Brühe auf 220 g Reis, max. halb füllen. Kein Rühren nötig.',
    steps: [
      ['Zwiebel im offenen Topf im Öl 3 Min. glasig dünsten, Reis 1 Min. mitrösten.', '', '', ''],
      ['Kürbiswürfel zugeben, mit ca. 550 ml heißer Brühe ablöschen, Bodensatz lösen, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 1. Ring erscheint, dann Hitze reduzieren und garen.', '1', '6 Min.', ''],
      ['Druck sofort über das Ventil ablassen.', '', '', 'schnell'],
      ['Edamame einrühren und offen 3 Min. mitziehen lassen, bis das Risotto cremig ist.', '', '', ''],
      ['Baby-/Kleinkind-Portion ohne Feta und Parmesan entnehmen.', '', '', ''],
      ['Parmesan einrühren, mit Feta, gerösteten Kürbiskernen und Salbei servieren.', '', '', ''],
    ],
  },
  'rahmspinat-spiegelei-kartoffeln': {
    t: 22,
    fit: 1,
    note: 'Für ca. 4 Portionen, 4,5-l-Topf mit Dämpfeinsatz. Nur die Kartoffeln im Schnellkochtopf, mind. 250 ml Wasser. Rahmspinat und Eier parallel auf dem Herd.',
    steps: [
      ['Kartoffeln schälen, vierteln und in den Einsatz legen. 250 ml Wasser in den Topf, Einsatz einhängen, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 1. Ring erscheint, dann Hitze reduzieren und garen.', '1', '8 Min.', ''],
      ['Inzwischen Zwiebel und Knoblauch in der Hälfte der Butter andünsten, Spinat und Milch zugeben und 8 Min. garen, Frischkäse einrühren und grob pürieren.', '', '', ''],
      ['Druck über das Ventil ablassen.', '', '', 'schnell'],
      ['Baby-/Kleinkind-Portion entnehmen, Rest mit Muskat, Pfeffer und Salz abschmecken. Eier in der restlichen Butter braten (für Kinder beidseitig durch).', '', '', ''],
      ['Kartoffeln mit Rahmspinat, Spiegelei und Hüttenkäse servieren.', '', '', ''],
    ],
  },
  'gemuese-tajine-kichererbsen': {
    t: 25,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Mindestens 250 ml Flüssigkeit (Tomaten + 150 ml Wasser), max. 2/3 füllen. Couscous separat.',
    steps: [
      ['Zwiebel im offenen Topf im Öl 4 Min. dünsten, Knoblauch und Ras el Hanout 1 Min. mitrösten.', '', '', ''],
      ['Tomaten und 150 ml Wasser zugeben, Bodensatz lösen. Karotten in 1 cm dicken Scheiben, abgespülte Kichererbsen und Zucchini in groben Stücken zugeben, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 1. Ring erscheint, dann Hitze reduzieren und garen.', '1', '4 Min.', ''],
      ['Druck über das Ventil ablassen.', '', '', 'schnell'],
      ['Baby-/Kleinkind-Portion vor dem Salzen entnehmen, Rest abschmecken. Couscous mit gleicher Menge kochendem Wasser 5 Min. quellen lassen.', '', '', ''],
      ['Tajine mit Couscous, Joghurt, gerösteten Mandelblättchen und Koriander servieren.', '', '', ''],
    ],
  },
});
