// Schnellkochtopf-Anleitungen – Teil 1
(typeof window !== 'undefined' ? window : globalThis).DK = Object.assign((typeof window !== 'undefined' ? window : globalThis).DK || {}, {
  'chicken-tikka-masala': {
    t: 32,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Tomatensauce mit Wasser strecken (mind. 250 ml Flüssigkeit), damit nichts ansetzt. Reis separat garen.',
    steps: [
      ['Hähnchenwürfel mit Joghurt, der Hälfte von Knoblauch, Ingwer und Garam Masala 15 Min. marinieren. Parallel den Reis im normalen Topf aufsetzen.', '', '', ''],
      ['Zwiebel im offenen Schnellkochtopf im Öl 4 Min. glasig dünsten, restlichen Knoblauch, Ingwer und Gewürze 1 Min. mitrösten.', '', '', ''],
      ['Mit 150 ml Wasser ablöschen und den Boden loskratzen. Mariniertes Hähnchen einlegen, passierte Tomaten obenauf geben (nicht umrühren), Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 1. Ring erscheint, Hitze reduzieren und garen.', '1', '4 Min.', ''],
      ['Topf unter kaltes Wasser stellen, bis der Druck abgebaut ist, dann öffnen.', '', '', 'kaltes Wasser'],
      ['Sahne einrühren und offen 2 Min. sämig köcheln. Baby-/Kleinkind-Portion jetzt entnehmen.', '', '', ''],
      ['Rest mit Salz und nach Wunsch Chili abschmecken, mit Koriander und Reis servieren.', '', '', ''],
    ],
  },
  'leichtes-butter-chicken': {
    t: 33,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Mind. 250 ml Flüssigkeit, Tomaten obenauf schichten, damit nichts anbrennt. Reis separat garen.',
    steps: [
      ['Hähnchenwürfel mit Joghurt, der Hälfte des Garam Masala, Knoblauch und Ingwer 15 Min. marinieren. Parallel den Reis aufsetzen.', '', '', ''],
      ['Butter im offenen Schnellkochtopf schmelzen, Zwiebel 4 Min. andünsten, Tomatenmark und restliche Gewürze 1 Min. anrösten.', '', '', ''],
      ['Mit 150 ml Wasser ablöschen und den Boden loskratzen. Hähnchen einlegen, passierte Tomaten obenauf geben, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '4 Min.', ''],
      ['Topf unter kaltes Wasser stellen, bis der Druck abgebaut ist.', '', '', 'kaltes Wasser'],
      ['Hähnchen kurz herausheben, Sauce fein pürieren, Sahne einrühren und Hähnchen zurückgeben. Baby-/Kleinkind-Portion jetzt ungesalzen entnehmen.', '', '', ''],
      ['Rest mit Salz abschmecken und mit Reis und Koriander servieren.', '', '', ''],
    ],
  },
  'pho-rindfleisch': {
    t: 35,
    fit: 1,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Nur die Gewürzbrühe gart unter Druck, max. bis zur Hälfte füllen.',
    steps: [
      ['Zwiebel und Ingwer halbieren und im offenen Schnellkochtopf ohne Fett 5 Min. dunkel anrösten. Rindfleisch inzwischen 20 Min. anfrieren.', '', '', ''],
      ['Brühe, Sternanis, Zimt und Nelke zugeben, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 2. Ring erhitzen, Hitze reduzieren und die Aromen auskochen.', '2', '10 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen. Inzwischen Fleisch hauchdünn schneiden und Reisnudeln garen.', '', '', 'natürlich'],
      ['Brühe abseihen. Baby-/Kleinkind-Portion vor der Fischsauce abnehmen, Rest mit Fischsauce abschmecken.', '', '', ''],
      ['Rindfleisch auf die Nudeln legen, mit kochend heißer Brühe übergießen (für Kinder 2 Min. in der Brühe durchgaren) und mit Kräutern, Frühlingszwiebeln, Limette und Chili servieren.', '', '', ''],
    ],
  },
  'chili-sin-carne': {
    t: 32,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Mit Hülsenfrüchten höchstens bis zur Hälfte füllen, mind. 250 ml Flüssigkeit. Dosenbohnen erst nach dem Druckgaren zugeben.',
    steps: [
      ['Zwiebel und Knoblauch im offenen Topf im Öl 3 Min. glasig dünsten, Tomatenmark 1 Min. anrösten.', '', '', ''],
      ['Mit 300 ml Wasser ablöschen und Boden loskratzen. Gewaschene rote Linsen und Paprika zugeben, gehackte Tomaten obenauf geben, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen. Reis parallel im normalen Topf kochen.', '1', '4 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen (Linsen schäumen).', '', '', 'natürlich'],
      ['Abgespülte Kidneybohnen, schwarze Bohnen und Mais unterrühren und offen 3 Min. erhitzen. Baby-/Kleinkind-Portion vor dem Würzen entnehmen.', '', '', ''],
      ['Rest mit Paprikapulver, Kreuzkümmel, Chili und Salz abschmecken, mit Reis, Skyr und Koriander servieren.', '', '', ''],
    ],
  },
  'fischstaebchen-kartoffelpueree': {
    t: 30,
    fit: 1,
    note: 'Für ca. 4 Portionen. Nur Kartoffeln und Karotten im Schnellkochtopf (mit Einsatz), mind. 250 ml Wasser. Fischstäbchen in der Pfanne.',
    steps: [
      ['Kartoffeln schälen und vierteln, Karotten in Stifte schneiden. 300 ml Wasser in den Topf, Kartoffeln und Karotten in den gelochten Einsatz, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '7 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Währenddessen Kabeljau in Stäbchen schneiden, panieren und in der Pfanne pro Seite 3 Min. goldbraun braten.', '', '', ''],
      ['Kartoffeln mit warmer Milch und Butter zu Püree stampfen, mit Muskat würzen. Baby-/Kleinkind-Portion ungesalzen abnehmen, Rest salzen.', '', '', ''],
      ['Fischstäbchen mit Püree, Karotten und Zitronenspalten servieren.', '', '', ''],
    ],
  },
  'frikadellen-kartoffel-moehren-stampf': {
    t: 30,
    fit: 1,
    note: 'Für ca. 4 Portionen. Nur Kartoffeln und Möhren im Schnellkochtopf (Einsatz), mind. 250 ml Wasser. Frikadellen in der Pfanne.',
    steps: [
      ['Kartoffeln und Möhren schälen und in gleich große Stücke schneiden. 300 ml Wasser in den Topf, Gemüse in den Einsatz geben, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '7 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Parallel Hackmasse anmachen (Kinder-Frikadellen ohne Salz formen) und Frikadellen im Öl pro Seite 5–6 Min. durchbraten (Kern 72 °C).', '', '', ''],
      ['Kartoffeln und Möhren mit warmer Milch und Butter grob stampfen, mit Muskat würzen. Kinderportion abnehmen, Rest salzen.', '', '', ''],
      ['Frikadellen mit Stampf und Petersilie servieren.', '', '', ''],
    ],
  },
  'pellkartoffeln-kraeuterquark-leinsamen': {
    t: 22,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf mit Einsatz. Möglichst gleich große Kartoffeln, mind. 250 ml Wasser.',
    steps: [
      ['Kartoffeln gründlich waschen. 300 ml Wasser in den Topf, Kartoffeln in den gelochten Einsatz, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 2. Ring erhitzen, Hitze reduzieren und garen (große Kartoffeln eher 12 Min.).', '2', '10 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Währenddessen Quark mit Milch glatt rühren, Kräuter und Gurkenwürfel unterheben. Baby-/Kleinkind-Portion abnehmen, Rest salzen und pfeffern.', '', '', ''],
      ['Kartoffeln kurz ausdampfen lassen, pellen, mit Kräuterquark, Leinsamen und Rapsöl servieren.', '', '', ''],
    ],
  },
  'paprika-rindergulasch-kartoffeln': {
    t: 70,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Mind. 300 ml Flüssigkeit, max. 2/3 füllen. Kartoffeln parallel im normalen Topf kochen.',
    steps: [
      ['Fleisch trocken tupfen und im offenen Schnellkochtopf im Öl portionsweise 4–5 Min. rundum scharf anbraten.', '', '', ''],
      ['Zwiebeln 5 Min. goldbraun mitrösten, Knoblauch und Tomatenmark 1 Min. mitrösten, mit edelsüßem Paprika und Kümmel bestäuben.', '', '', ''],
      ['Mit der Brühe ablöschen, Bratansatz vom Boden lösen, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 2. Ring erhitzen, Hitze reduzieren und schmoren.', '2', '22 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen. Inzwischen Kartoffeln 20 Min. in Wasser kochen.', '', '', 'natürlich'],
      ['Paprikastücke zugeben und offen 8 Min. bissfest mitköcheln. Baby-/Kleinkind-Portion vor Salz und Rosenpaprika/Chili entnehmen.', '', '', ''],
      ['Rest abschmecken und mit Kartoffeln und einem Klecks Schmand servieren.', '', '', ''],
    ],
  },
  'gefuellte-suesskartoffel-huettenkaese-bohnen': {
    t: 30,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf mit Einsatz. Statt 45 Min. Ofen: ganze Süßkartoffeln gedämpft. Mind. 250 ml Wasser.',
    steps: [
      ['Süßkartoffeln waschen, mehrmals einstechen. 300 ml Wasser in den Topf, Süßkartoffeln in den Einsatz legen, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 2. Ring erhitzen, Hitze reduzieren und garen (dicke Knollen eher 18 Min.).', '2', '15 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Währenddessen Bohnen und Mais abspülen und in einem kleinen Topf 3 Min. erwärmen. Kinderportion abnehmen, Rest mit Kreuzkümmel und Paprika würzen.', '', '', ''],
      ['Süßkartoffeln längs aufschneiden, Fruchtfleisch auflockern, mit Bohnen-Mais-Mischung und Hüttenkäse füllen.', '', '', ''],
      ['Mit Salsa, Frühlingszwiebel, Koriander und Limettensaft toppen.', '', '', ''],
    ],
  },
  'kabeljau-senfsauce-kartoffeln': {
    t: 22,
    fit: 1,
    note: 'Für ca. 4 Portionen. Nur die Kartoffeln im Schnellkochtopf (Einsatz), mind. 250 ml Wasser. Fisch in der Pfanne.',
    steps: [
      ['Kartoffeln schälen und vierteln. 300 ml Wasser in den Topf, Kartoffeln in den Einsatz, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '7 Min.', ''],
      ['Druck über das Ventil abdampfen lassen. Erbsen ins heiße Wasser geben und 3 Min. zugedeckt ziehen lassen.', '', '', 'schnell'],
      ['Parallel Milch und Brühe in der Pfanne aufkochen, mit angerührter Stärke binden, Kabeljau einlegen und 7–8 Min. gar ziehen lassen.', '', '', ''],
      ['Baby-/Kleinkind-Portion Fisch und Kartoffeln vor dem Senf entnehmen.', '', '', ''],
      ['Senf und Butter in die Sauce rühren, salzen und mit Dill, Kartoffeln und Erbsen servieren.', '', '', ''],
    ],
  },
  'kabeljau-curry-blumenkohl': {
    t: 27,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Mind. 250 ml Flüssigkeit. Fisch nicht unter Druck garen, sondern danach offen ziehen lassen. Reis separat.',
    steps: [
      ['Zwiebel im offenen Topf im Öl 4 Min. goldgelb braten, Knoblauch, Ingwer und Currypulver 1 Min. mitrösten.', '', '', ''],
      ['Mit 150 ml Wasser ablöschen, Boden loskratzen. Blumenkohlröschen zugeben, Tomaten obenauf, Deckel schließen. Reis parallel aufsetzen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '2 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Kabeljau in Stücken einlegen und offen bei kleiner Hitze 6 Min. gar ziehen lassen.', '', '', ''],
      ['Vom Herd nehmen, Joghurt unterrühren. Baby-/Kleinkind-Portion vor dem Salzen entnehmen.', '', '', ''],
      ['Rest salzen und mit Koriander und Reis servieren.', '', '', ''],
    ],
  },
  'norddeutsche-fischsuppe-seelachs': {
    t: 28,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Suppe: höchstens halb füllen. Fisch und Sahne erst nach dem Druckgaren zugeben.',
    steps: [
      ['Kartoffeln und Karotten würfeln, Lauch in Ringe, Sellerie in Scheiben schneiden und in der Butter im offenen Topf 3 Min. andünsten.', '', '', ''],
      ['Brühe angießen (für die Baby-Portion ideal: ungesalzenes Wasser), Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '5 Min.', ''],
      ['Topf unter kaltes Wasser stellen, bis der Druck abgebaut ist (nicht über das Ventil abdampfen).', '', '', 'kaltes Wasser'],
      ['Seelachswürfel einlegen und offen 6 Min. gar ziehen lassen, nicht mehr kochen. Baby-/Kleinkind-Portion entnehmen.', '', '', ''],
      ['Sahne einrühren, mit Zitronensaft und Salz abschmecken und mit Dill bestreuen.', '', '', ''],
    ],
  },
  'fischfrikadellen-kartoffel-gurkensalat': {
    t: 30,
    fit: 1,
    note: 'Für ca. 4 Portionen. Nur die Pellkartoffeln im Schnellkochtopf (Einsatz), mind. 250 ml Wasser.',
    steps: [
      ['Kartoffeln waschen. 300 ml Wasser in den Topf, Kartoffeln mit Schale in den Einsatz, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 2. Ring erhitzen, Hitze reduzieren und garen.', '2', '9 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Kartoffeln pellen, in Scheiben schneiden und mit Essig, Joghurt und Gurkenscheiben mischen.', '', '', ''],
      ['Parallel Fischmasse anmachen, 2 kleine Baby-Frikadellen ohne Senf und Salz abnehmen, Rest würzen, formen und im Öl pro Seite 4 Min. braten.', '', '', ''],
      ['Salat salzen und mit den Frikadellen servieren.', '', '', ''],
    ],
  },
  'forelle-muellerin-glutenfrei': {
    t: 20,
    fit: 1,
    note: 'Für ca. 4 Portionen. Nur die Kartoffeln im Schnellkochtopf (Einsatz), mind. 250 ml Wasser. Baby-Kartoffeln ungesalzen.',
    steps: [
      ['Kartoffeln schälen und halbieren. 300 ml Wasser in den Topf, Kartoffeln in den Einsatz, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '7 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Währenddessen Forelle in glutenfreiem Mehl wenden und in der Hälfte der Butter auf der Hautseite 3 Min., dann 1–2 Min. auf der Fleischseite braten. Baby-Stück entnehmen, Rest salzen.', '', '', ''],
      ['Restliche Butter leicht bräunen, Zitronensaft und Petersilie zugeben und über Forelle und Kartoffeln löffeln. Mit Blattsalat servieren.', '', '', ''],
    ],
  },
  'forelle-mandeln-gruene-bohnen': {
    t: 22,
    fit: 1,
    note: 'Für ca. 4 Portionen. Kartoffeln und Bohnen im Schnellkochtopf (Einsatz), mind. 250 ml Wasser. Bohnen erst im zweiten, kurzen Durchgang.',
    steps: [
      ['Kartoffeln schälen und halbieren. 300 ml Wasser in den Topf, Kartoffeln in den Einsatz, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '6 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Geputzte grüne Bohnen auf die Kartoffeln legen, Deckel wieder schließen und erneut bis zum 1. Ring bringen.', '1', '2 Min.', 'schnell'],
      ['Parallel Mandeln trocken rösten, Forelle in Butter auf der Hautseite 3 Min. und auf der Fleischseite 1–2 Min. braten. Baby-Stück entnehmen.', '', '', ''],
      ['Mandeln, Zitronensaft und Petersilie in die Pfanne geben, salzen und mit Bohnen und Kartoffeln servieren.', '', '', ''],
    ],
  },
  'forelle-lauwarmer-kartoffelsalat-radieschen': {
    t: 25,
    fit: 1,
    note: 'Für ca. 4 Portionen. Nur die Pellkartoffeln im Schnellkochtopf (Einsatz), mind. 250 ml Wasser.',
    steps: [
      ['Kartoffeln waschen. 300 ml Wasser in den Topf, Kartoffeln mit Schale in den Einsatz, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 2. Ring erhitzen, Hitze reduzieren und garen.', '2', '9 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Kartoffeln pellen und warm in Scheiben schneiden. Baby-Kartoffeln ohne Dressing beiseitelegen.', '', '', ''],
      ['Skyr, Senf, Essig und Schnittlauch verrühren, mit Radieschen, Gurke und Kartoffeln mischen und salzen.', '', '', ''],
      ['Forelle im Öl auf der Hautseite 3 Min. knusprig braten, wenden, 1 Min. fertig garen und auf dem Salat anrichten.', '', '', ''],
    ],
  },
  'zander-kuerbisrisotto': {
    t: 25,
    fit: 1,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Risotto ohne Rühren im Schnellkochtopf: nur ca. 150 ml Brühe pro Portion nötig. Zander in der Pfanne.',
    steps: [
      ['Zwiebel im offenen Topf in der Hälfte des Öls glasig dünsten, Reis 1 Min. mitrösten.', '', '', ''],
      ['Kürbiswürfel zugeben, mit ca. 600 ml heißer Brühe ablöschen, einmal umrühren und Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '6 Min.', ''],
      ['Druck sofort über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Risotto offen 1 Min. cremig rühren. Baby-/Kleinkind-Portion vor dem Parmesan entnehmen, dann Parmesan unterrühren.', '', '', ''],
      ['Zander im restlichen Öl auf der Hautseite 4 Min. braten, wenden, 1 Min. fertig garen, salzen und mit Salbei oder Petersilie auf dem Risotto anrichten.', '', '', ''],
    ],
  },
  'zander-blumenkohlpueree-spinat': {
    t: 20,
    fit: 1,
    note: 'Für ca. 4 Portionen. Nur der Blumenkohl im Schnellkochtopf (Einsatz), mind. 250 ml Wasser.',
    steps: [
      ['Blumenkohl in Röschen teilen. 300 ml Wasser in den Topf, Röschen in den Einsatz, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '4 Min.', ''],
      ['Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Blumenkohl mit Milch, der Hälfte der Butter und Parmesan fein pürieren. Baby-Portion entnehmen, Rest mit Salz und Muskat abschmecken.', '', '', ''],
      ['Parallel Knoblauch in restlicher Butter andünsten, Spinat zusammenfallen lassen. Zander auf der Hautseite 4 Min. braten, wenden, 1 Min. fertig garen.', '', '', ''],
      ['Zander auf Püree und Spinat anrichten.', '', '', ''],
    ],
  },
  'bouillabaisse-light': {
    t: 32,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Suppe: höchstens halb füllen. Fisch und Garnelen erst nach dem Druckgaren offen garziehen lassen.',
    steps: [
      ['Zwiebel, Knoblauch und Fenchel im offenen Topf im Öl 5 Min. andünsten, Safran und Fenchelsamen zugeben.', '', '', ''],
      ['Kartoffelwürfel, Brühe und Tomaten zugeben, Boden loskratzen, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe bis zum 1. Ring erhitzen, Hitze reduzieren und garen.', '1', '5 Min.', ''],
      ['Topf unter kaltes Wasser stellen, bis der Druck abgebaut ist (nicht über das Ventil abdampfen).', '', '', 'kaltes Wasser'],
      ['Dorade und Kabeljau in großen Stücken sowie Garnelen einlegen und offen 5–6 Min. gar ziehen lassen. Brot währenddessen rösten.', '', '', ''],
      ['Baby-/Kleinkind-Portion entnehmen, Rest salzen, mit Petersilie bestreuen und mit dem Brot servieren.', '', '', ''],
    ],
  },
});
