// Schnellkochtopf-Anleitungen – Teil 2
(typeof window !== 'undefined' ? window : globalThis).DK = Object.assign((typeof window !== 'undefined' ? window : globalThis).DK || {}, {
  'garnelen-spargel-risotto': {
    t: 22,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Ca. 1 l Brühe für 240 g Risottoreis, max. halb füllen.',
    steps: [
      ['Zwiebel im offenen Topf in Öl glasig dünsten, Reis 1 Min. mitrösten, Spargelstücke kurz mitschwenken.', '', '', ''],
      ['Mit heißer Brühe ablöschen, Bodensatz lösen und den Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 1. Ring erscheint, Hitze reduzieren und garen.', '1', '6 Min.', ''],
      ['Topf vom Herd nehmen und den Druck über das Ventil abdampfen lassen.', '', '', 'schnell'],
      ['Garnelen unterheben und offen bei kleiner Hitze 3–4 Min. unter Rühren gar ziehen lassen. Baby-Portion vor dem Parmesan entnehmen.', '', '', ''],
      ['Parmesan, Zitronensaft und Petersilie unterrühren und salzen.', '', '', ''],
    ],
  },
  'tafelspitz-rinderhuefte-wurzelgemuese': {
    t: 70,
    fit: 2,
    note: 'Für ca. 4 Portionen, 6-l-Topf mit Dämpfeinsatz. Ca. 1,2 l Brühe, max. halb füllen. Das Fleisch wird wie klassischer Tafelspitz durchgegart statt rosa.',
    steps: [
      ['Halbierte Zwiebel mit Schale in der Pfanne dunkel anrösten. Mit Brühe, Lorbeer und Pfefferkörnern im offenen Topf aufkochen.', '', '', ''],
      ['Rinderhüfte am Stück einlegen, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '35 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Karotten, Sellerie und Lauch in die Brühe geben, geschälte Kartoffeln in Stücken im Einsatz darüber setzen. Deckel schließen.', '', '', ''],
      ['Erneut erhitzen, bis der 1. Ring erscheint, und garen.', '1', '6 Min.', ''],
      ['Druck über das Ventil abdampfen lassen. Skyr mit Senf, Schnittlauch und 2 EL Brühe verrühren.', '', '', 'schnell'],
      ['Baby-/Kleinkind-Portion vor dem Salzen entnehmen. Fleisch quer zur Faser aufschneiden und mit Gemüse, Kartoffeln, Brühe und Sauce servieren.', '', '', ''],
    ],
  },
  'schnitzel-glutenfrei-kartoffelsalat': {
    t: 30,
    fit: 1,
    note: 'Nur die Pellkartoffeln im Schnellkochtopf. Ca. 300 ml Wasser, Kartoffeln im Dämpfeinsatz.',
    steps: [
      ['Etwa gleich große Kartoffeln mit Schale in den Einsatz legen, 300 ml Wasser in den Topf geben, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '10 Min.', ''],
      ['Druck über das Ventil abdampfen lassen, Kartoffeln pellen und etwas abkühlen lassen.', '', '', 'schnell'],
      ['Währenddessen Schnitzel klopfen und in Stärke, Ei und glutenfreiem Paniermehl wenden.', '', '', ''],
      ['Kartoffeln in Scheiben schneiden und mit Gurke und Joghurt-Senf-Dressing mischen. Schnitzel pro Seite 3 Min. braten.', '', '', ''],
      ['Baby-/Kleinkind-Portion ungesalzen beiseitelegen, Rest leicht salzen und mit Zitronenspalten servieren.', '', '', ''],
    ],
  },
  'schweinefilet-medaillons-pfeffersauce': {
    t: 28,
    fit: 1,
    note: 'Nur die Kartoffeln im Schnellkochtopf (Dämpfeinsatz, ca. 300 ml Wasser).',
    steps: [
      ['Geschälte, halbierte Kartoffeln in den Einsatz legen, 300 ml Wasser in den Topf geben, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 1. Ring erscheint, Hitze reduzieren und garen.', '1', '7 Min.', ''],
      ['Druck über das Ventil abdampfen lassen. Bohnen parallel 6–8 Min. dämpfen.', '', '', 'schnell'],
      ['Medaillons pro Seite 3 Min. braten und im Ofen bei 80 °C ruhen lassen.', '', '', ''],
      ['Zwiebel im Bratensatz dünsten, mit Brühe ablöschen, Sahne und Senf zugeben und mit Stärke binden.', '', '', ''],
      ['Baby-/Kleinkind-Portion vor dem Pfeffern abnehmen, Rest mit Pfeffer und Salz würzen und servieren.', '', '', ''],
    ],
  },
  'koettbullar-kartoffelpueree': {
    t: 35,
    fit: 1,
    note: 'Nur die Kartoffeln fürs Püree im Schnellkochtopf (Dämpfeinsatz, ca. 300 ml Wasser).',
    steps: [
      ['Kartoffeln schälen, vierteln, in den Einsatz legen, 300 ml Wasser in den Topf geben, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 1. Ring erscheint, Hitze reduzieren und garen.', '1', '8 Min.', ''],
      ['Druck über das Ventil abdampfen lassen und Kartoffeln mit warmer Milch zu Püree stampfen.', '', '', 'schnell'],
      ['Währenddessen Köttbullar formen und in der Pfanne 8–10 Min. rundum braten.', '', '', ''],
      ['Bratensatz mit Brühe ablöschen, Sahne und Sojasauce zugeben, mit Stärke binden, Bällchen darin ziehen lassen. Heidelbeeren kurz einkochen.', '', '', ''],
      ['Baby-/Kleinkind-Portion vor dem Salzen entnehmen, mit Püree, Kompott und Gurke servieren.', '', '', ''],
    ],
  },
  'picadillo-reis': {
    t: 27,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5-l-Topf. Mit Tomaten und 250 ml Wasser, max. 2/3 füllen. Reis separat garen.',
    steps: [
      ['Reis separat nach Packungsangabe aufsetzen.', '', '', ''],
      ['Hack im offenen Topf in Öl 5 Min. krümelig anbraten, Zwiebel, Knoblauch und Paprika 3 Min. mitbraten.', '', '', ''],
      ['Kartoffelwürfel, Tomaten, 250 ml Wasser, Kreuzkümmel und Oregano zugeben, Bodensatz lösen, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 1. Ring erscheint, Hitze reduzieren und garen.', '1', '5 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Baby-/Kleinkind-Portion vor Oliven und Salz entnehmen.', '', '', ''],
      ['Oliven und Rosinen unterrühren, offen 3 Min. ziehen lassen, salzen und mit Reis und Petersilie servieren.', '', '', ''],
    ],
  },
  'kohlrouladen-hack-reis': {
    t: 55,
    fit: 2,
    note: 'Für ca. 4 Portionen (8 Rouladen), 6-l-Topf. Mind. 400 ml Tomaten-Brühe-Flüssigkeit, max. 2/3 füllen.',
    steps: [
      ['Kohlblätter wie beschrieben blanchieren und ablösen, Reis 10 Min. vorgaren. Füllung mischen und Rouladen wickeln.', '', '', ''],
      ['Rouladen im offenen Topf in Öl rundum 5 Min. anbraten. Restliche Zwiebel und Tomatenmark kurz mitrösten.', '', '', ''],
      ['Mit passierten Tomaten und Brühe ablöschen, Bodensatz lösen, Rouladen mit der Naht nach unten einlegen, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '15 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Baby-/Kleinkind-Portion ungesalzen entnehmen. Sauce mit Schmand verfeinern, salzen und mit Petersilie servieren.', '', '', ''],
    ],
  },
  'gulaschsuppe-rind': {
    t: 75,
    fit: 2,
    note: 'Für ca. 4 Portionen, 6-l-Topf. Ca. 1,4 l Brühe, als Suppe höchstens halb füllen.',
    steps: [
      ['Fleisch im offenen Topf in Öl portionsweise kräftig anbraten. Zwiebeln 5 Min. bräunen, Tomatenmark und Paprikapulver 1 Min. anrösten.', '', '', ''],
      ['Mit Brühe und Tomaten ablöschen, Bodensatz lösen, Kümmel und Majoran zugeben, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '20 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Kartoffel- und Paprikawürfel zugeben, Deckel schließen.', '', '', ''],
      ['Erneut erhitzen, bis der 1. Ring erscheint, und garen.', '1', '5 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Baby-/Kleinkind-Portion ungesalzen entnehmen. Rest mit Salz, Pfeffer und Rosenpaprika abschmecken, mit Schmand und Brot servieren.', '', '', ''],
    ],
  },
  'rinder-madras-curry': {
    t: 55,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Tomaten plus 300 ml Wasser, max. 2/3 füllen. Kokosmilch erst nach dem Druckgaren.',
    steps: [
      ['Reis separat aufsetzen. Fleisch im offenen Topf in Öl portionsweise anbraten, Zwiebel 4 Min. mitbraten, Knoblauch, Ingwer und Currypulver 1 Min. anrösten.', '', '', ''],
      ['Tomaten und 300 ml Wasser zugeben, Bodensatz lösen, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '25 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Kokosmilch einrühren und offen 3–5 Min. sämig einköcheln, Spinat die letzten 2 Min. unterheben.', '', '', ''],
      ['Baby-/Kleinkind-Portion vor Chili und Salz entnehmen. Rest abschmecken und mit Koriander und Reis servieren.', '', '', ''],
    ],
  },
  'lamm-rogan-josh': {
    t: 50,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Tomaten plus 250 ml Wasser, max. 2/3 füllen. Joghurt aus der Marinade erst nach dem Druckgaren einrühren.',
    steps: [
      ['Lamm mit der Hälfte des Currypulvers einreiben (ohne Joghurt). Reis separat aufsetzen.', '', '', ''],
      ['Zwiebel im offenen Topf in Öl 6 Min. bräunen, Fleisch 5 Min. mitbraten, Knoblauch, Ingwer, Tomatenmark und restliche Gewürze 1 Min. anrösten.', '', '', ''],
      ['Tomaten und 250 ml Wasser zugeben, Bodensatz lösen, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '20 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['30 g Joghurt pro Portion mit etwas Sauce glatt rühren und unterziehen, nicht mehr kochen. Raita aus restlichem Joghurt, Gurke und Minze anrühren.', '', '', ''],
      ['Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest salzen und mit Reis und Raita servieren.', '', '', ''],
    ],
  },
  'lamm-tajine-kichererbsen': {
    t: 50,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Tomaten plus 300 ml Wasser, max. 2/3 füllen. Kichererbsen aus der Dose.',
    steps: [
      ['Lamm im offenen Topf in Öl rundum 5 Min. anbraten, Zwiebel 4 Min. mitdünsten, Knoblauch, Ingwer und Gewürze 1 Min. anrösten.', '', '', ''],
      ['Tomaten, dicke Karottenscheiben und 300 ml Wasser zugeben, Bodensatz lösen, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '20 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Zucchini, abgespülte Kichererbsen und Datteln zugeben und offen 5–6 Min. köcheln. Couscous mit kochendem Wasser übergießen und quellen lassen.', '', '', ''],
      ['Baby-/Kleinkind-Portion ungesalzen entnehmen. Rest salzen und mit Couscous und Kräutern servieren.', '', '', ''],
    ],
  },
  'koenigsberger-klopse': {
    t: 38,
    fit: 2,
    note: 'Für ca. 4 Portionen, 6-l-Topf mit Dämpfeinsatz. Ca. 1,2 l Brühe, max. halb füllen.',
    steps: [
      ['Klopse wie beschrieben formen. Brühe mit Lorbeer im offenen Topf aufkochen, Klopse einlegen.', '', '', ''],
      ['Geschälte Kartoffeln in großen Stücken im Einsatz darüber setzen, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 1. Ring erscheint, Hitze reduzieren und garen.', '1', '6 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Kartoffeln und Klopse herausnehmen. Rote Bete mit Essig und Petersilie mischen.', '', '', ''],
      ['300 ml Brühe mit Milch aufkochen, mit Stärke binden, Senf einrühren. Baby-Portion Sauce und Klopse entnehmen.', '', '', ''],
      ['Rest mit Zitronensaft und Salz abschmecken, Klopse darin erwärmen und mit Kartoffeln und Rote-Bete-Salat servieren.', '', '', ''],
    ],
  },
  'rinderhuefte-rosenkohl-stampf': {
    t: 35,
    fit: 1,
    note: 'Nur Kartoffeln und Sellerie für den Stampf im Schnellkochtopf (Dämpfeinsatz, ca. 300 ml Wasser).',
    steps: [
      ['Kartoffeln und Sellerie würfeln, in den Einsatz legen, 300 ml Wasser in den Topf geben, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 1. Ring erscheint, Hitze reduzieren und garen.', '1', '7 Min.', ''],
      ['Druck über das Ventil abdampfen lassen, mit warmer Milch, Butter und Muskat stampfen.', '', '', 'schnell'],
      ['Währenddessen Rinderhüfte scharf anbraten und im Ofen bei 140 °C auf 56 °C Kerntemperatur garen. Rosenkohl 6 Min. dämpfen.', '', '', ''],
      ['Rosenkohl im Bratensatz anrösten, mit Brühe und Senf ablöschen.', '', '', ''],
      ['Baby-/Kleinkind-Portion ungesalzen entnehmen. Fleisch aufschneiden, würzen und servieren.', '', '', ''],
    ],
  },
  'rindergulasch-ossobuco-art-polenta': {
    t: 55,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Mindestens 250 ml Flüssigkeit, max. 2/3 füllen.',
    steps: [
      ['Fleisch im offenen Topf in Öl rundum kräftig anbraten, Gemüse 4 Min. mitrösten, Tomatenmark 1 Min. anrösten.', '', '', ''],
      ['Mit Tomaten und Brühe ablöschen (mind. 300 ml Flüssigkeit), Bodensatz lösen, Deckel schließen.', '', '', ''],
      ['Auf hoher Stufe erhitzen, bis der 2. Ring erscheint, dann Hitze reduzieren und garen.', '2', '25 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Polenta separat im offenen Topf zubereiten, Parmesan unterziehen. Gremolata hacken.', '', '', ''],
      ['Baby-Portion ungesalzen entnehmen, Rest salzen und mit Polenta und Gremolata servieren.', '', '', ''],
    ],
  },
  'beef-rendang-light': {
    t: 75,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. 300 ml Wasser, max. 2/3 füllen. Kokosmilch erst nach dem Druckgaren, dann offen einkochen.',
    steps: [
      ['Gewürzpaste pürieren (Baby-Anteil ohne Chili beachten). Paste und Currypulver im offenen Topf in Öl 4 Min. anbraten.', '', '', ''],
      ['Fleisch zugeben und 5 Min. rundum anbraten. 300 ml Wasser und Limettenschale zugeben, Bodensatz lösen, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '25 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Kokosmilch einrühren und offen bei mittlerer Hitze 15–20 Min. unter Rühren einkochen, bis die Sauce fast trocken ist. Reis separat garen.', '', '', ''],
      ['Geröstete Kokosraspeln unterrühren. Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest salzen und mit Reis, Gurke und Limette servieren.', '', '', ''],
    ],
  },
  'congee-haehnchen-ei': {
    t: 42,
    fit: 2,
    note: 'Für ca. 4 Portionen, 6-l-Topf. Reis mit ca. 2,2 l Flüssigkeit, höchstens halb füllen (schäumt).',
    steps: [
      ['Reis waschen, mit Brühe, Wasser und Ingwerscheiben in den Topf geben, umrühren, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '12 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Congee kräftig durchrühren, Hähnchenstreifen zugeben und offen bei kleiner Hitze 6–8 Min. gar ziehen lassen. Eier parallel 7 Min. kochen.', '', '', ''],
      ['Baby-/Kleinkind-Portion ohne Sojasauce entnehmen.', '', '', ''],
      ['Rest mit Sojasauce, Sesamöl und Frühlingszwiebeln würzen und mit dem halbierten Ei servieren.', '', '', ''],
    ],
  },
  'quarkkeulchen-apfelmus': {
    t: 32,
    fit: 1,
    note: 'Nur die Pellkartoffeln im Schnellkochtopf (Dämpfeinsatz, ca. 300 ml Wasser).',
    steps: [
      ['Etwa gleich große Kartoffeln mit Schale in den Einsatz legen, 300 ml Wasser in den Topf geben, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '10 Min.', ''],
      ['Druck über das Ventil abdampfen lassen, Kartoffeln pellen und fein zerdrücken.', '', '', 'schnell'],
      ['Quark, Ei, Mehl, Erythrit, Zimt und Rosinen unterkneten und flache Keulchen formen.', '', '', ''],
      ['Keulchen je Seite 3–4 Min. goldbraun braten und mit Apfelmus servieren.', '', '', ''],
    ],
  },
  'putenschnitzel-gurken-kartoffelsalat': {
    t: 35,
    fit: 1,
    note: 'Nur die Pellkartoffeln im Schnellkochtopf (Dämpfeinsatz, ca. 300 ml Wasser).',
    steps: [
      ['Etwa gleich große Kartoffeln mit Schale in den Einsatz legen, 300 ml Wasser in den Topf geben, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '10 Min.', ''],
      ['Druck über das Ventil abdampfen lassen, Kartoffeln pellen, in Scheiben schneiden und mit Gurke und Joghurt-Dressing 15 Min. ziehen lassen.', '', '', 'schnell'],
      ['Währenddessen Putenschnitzel klopfen, panieren und je Seite 3–4 Min. durchbraten.', '', '', ''],
      ['Baby-/Kleinkind-Portion von Schnitzel und Salat vor dem Salzen abnehmen.', '', '', ''],
      ['Schnitzel leicht salzen und mit Zitronenspalten und Kartoffelsalat servieren.', '', '', ''],
    ],
  },
  'arroz-con-pollo': {
    t: 38,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. 240 g Reis mit ca. 300 ml Brühe plus Tomaten, max. halb füllen.',
    steps: [
      ['Hähnchenstücke im offenen Topf in Öl 5 Min. anbraten, Zwiebel, Knoblauch und Paprika 3 Min. mitbraten.', '', '', ''],
      ['Mit Brühe ablöschen und Bodensatz lösen. Reis einstreuen, Tomaten obenauf geben, nicht umrühren. Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 1. Ring erscheint, Hitze reduzieren und garen.', '1', '6 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen.', '', '', 'natürlich'],
      ['Erbsen unterheben und offen 2–3 Min. ziehen lassen.', '', '', ''],
      ['Baby-/Kleinkind-Portion ungesalzen entnehmen. Rest salzen, mit Petersilie und Limettenspalten servieren.', '', '', ''],
    ],
  },
  'haehnchen-tajine-zitrone-oliven': {
    t: 35,
    fit: 2,
    note: 'Für ca. 4 Portionen, 4,5–6-l-Topf. Mind. 500 ml Brühe, max. 2/3 füllen. Kichererbsen aus der Dose.',
    steps: [
      ['Hähnchen im offenen Topf in Öl 5 Min. anbraten, Zwiebel, Knoblauch und Ingwer 3 Min. mitdünsten.', '', '', ''],
      ['Karotten, Kichererbsen und Brühe zugeben, Bodensatz lösen, Deckel schließen.', '', '', ''],
      ['Erhitzen, bis der 2. Ring erscheint, Hitze reduzieren und garen.', '2', '10 Min.', ''],
      ['Herd ausschalten und den Druck von selbst abbauen lassen. Couscous mit kochendem Wasser übergießen und quellen lassen.', '', '', 'natürlich'],
      ['Baby-/Kleinkind-Portion ohne Oliven und ungesalzen entnehmen.', '', '', ''],
      ['Oliven und Zitronensaft zugeben, offen 3 Min. ziehen lassen, mit Koriander bestreuen und mit Couscous servieren.', '', '', ''],
    ],
  },
});
