/* SuPER Küche – Zutaten-Datenbank
 * Nährwerte pro 100 g (roh / wie gekauft, Trockenprodukte trocken), Richtwerte nach BLS / USDA.
 *  k  kcal | p Protein g | c Kohlenhydrate g | f Fett g | fi Ballaststoffe g | su Zucker g | sa Salz g
 *  pr Preis € pro kg (Richtwert Discounter/Vollsortimenter DE)
 *  cat Einkaufs-Kategorie (siehe SHOP_CATS)
 *  u  [Gramm pro Einheit, 'Einheit'] für schönere Mengenangaben (optional)
 *  fl Flags: G Gluten · L Laktose · M Milcheiweiß · E Ei · N Schalenfrüchte · P Erdnuss · F Fisch
 *            K Krebstiere · Y Soja · Z Sesam · X Fleisch/Fisch (nicht vegetarisch) · A tierisch (nicht vegan)
 *  fm FODMAP: max. Gramm pro Portion, die als FODMAP-arm gelten (0 = schon in kleinen Mengen reich an FODMAPs).
 *     Fehlt fm, gilt die Zutat als FODMAP-arm.
 *  sw Austausch-Zutat je Ernährungsform: {gf, lf, fm}
 *  b  Baby-/Kleinkind-Hinweis: h Honig (<12 Mon. verboten) · s salzig · c Verschluckungsgefahr
 *     r roh/Keimrisiko · p scharf · m quecksilberreicher Fisch (selten) · n Nitrat/gepökelt
 */
const SHOP_CATS = {
  obst: { n: 'Obst & Gemüse', e: '🥦' },
  fleisch: { n: 'Fleisch & Fisch', e: '🥩' },
  milch: { n: 'Milch, Käse & Eier', e: '🧀' },
  trocken: { n: 'Nudeln, Reis & Getreide', e: '🍚' },
  konserve: { n: 'Konserven & Hülsenfrüchte', e: '🥫' },
  backen: { n: 'Brot & Backwaren', e: '🍞' },
  tk: { n: 'Tiefkühl', e: '🧊' },
  vorrat: { n: 'Öl, Gewürze & Saucen', e: '🫙' },
  nuss: { n: 'Nüsse, Samen & Süßes', e: '🥜' },
  spezial: { n: 'Spezial & Free-From', e: '✨' },
  sport: { n: 'Proteinprodukte (Drogerie / online)', e: '💪' },
};

const ING = {
  /* ---------- Fleisch & Geflügel ---------- */
  haehnchenbrust: { n: 'Hähnchenbrustfilet', k: 110, p: 23.5, c: 0, f: 1.5, fi: 0, su: 0, sa: 0.15, pr: 11, cat: 'fleisch', fl: 'XA' },
  haehnchenschenkel: { n: 'Hähnchenschenkel (ohne Haut, entbeint)', k: 125, p: 19.5, c: 0, f: 5, fi: 0, su: 0, sa: 0.2, pr: 9, cat: 'fleisch', fl: 'XA' },
  haehnchenkeule: { n: 'Hähnchenkeulen (mit Knochen)', k: 175, p: 17, c: 0, f: 11.5, fi: 0, su: 0, sa: 0.2, pr: 5.5, cat: 'fleisch', fl: 'XA', u: [250, 'Keule'] },
  putenbrust: { n: 'Putenbrust', k: 105, p: 24, c: 0, f: 1, fi: 0, su: 0, sa: 0.15, pr: 12, cat: 'fleisch', fl: 'XA' },
  putenhack: { n: 'Putenhackfleisch', k: 140, p: 20, c: 0, f: 6.5, fi: 0, su: 0, sa: 0.2, pr: 10, cat: 'fleisch', fl: 'XA' },
  rinderhack: { n: 'Rinderhackfleisch (mager, 5 %)', k: 135, p: 21, c: 0, f: 5, fi: 0, su: 0, sa: 0.2, pr: 12, cat: 'fleisch', fl: 'XA' },
  gemischtes_hack: { n: 'Hackfleisch gemischt', k: 230, p: 19, c: 0, f: 17, fi: 0, su: 0, sa: 0.2, pr: 8, cat: 'fleisch', fl: 'XA' },
  rindersteak: { n: 'Rinderhüftsteak', k: 125, p: 22, c: 0, f: 4, fi: 0, su: 0, sa: 0.15, pr: 25, cat: 'fleisch', fl: 'XA' },
  rindergulasch: { n: 'Rindergulasch', k: 140, p: 21, c: 0, f: 6, fi: 0, su: 0, sa: 0.15, pr: 14, cat: 'fleisch', fl: 'XA' },
  schweinefilet: { n: 'Schweinefilet', k: 110, p: 21.5, c: 0, f: 2.5, fi: 0, su: 0, sa: 0.15, pr: 13, cat: 'fleisch', fl: 'XA' },
  schinken_gekocht: { n: 'Kochschinken (mager)', k: 110, p: 19, c: 1, f: 3.5, fi: 0, su: 1, sa: 2.2, pr: 14, cat: 'fleisch', fl: 'XA', b: 'sn' },
  lammhack: { n: 'Lammhackfleisch', k: 240, p: 17, c: 0, f: 19, fi: 0, su: 0, sa: 0.2, pr: 16, cat: 'fleisch', fl: 'XA' },

  /* ---------- Fisch & Meeresfrüchte ---------- */
  lachs: { n: 'Lachsfilet', k: 200, p: 20, c: 0, f: 13, fi: 0, su: 0, sa: 0.15, pr: 24, cat: 'fleisch', fl: 'XAF' },
  lachs_sushi: { n: 'Lachs in Sushi-Qualität', k: 200, p: 20, c: 0, f: 13, fi: 0, su: 0, sa: 0.15, pr: 35, cat: 'fleisch', fl: 'XAF', b: 'r' },
  raeucherlachs: { n: 'Räucherlachs', k: 180, p: 22, c: 0, f: 10, fi: 0, su: 0, sa: 3, pr: 30, cat: 'fleisch', fl: 'XAF', b: 'sr' },
  kabeljau: { n: 'Kabeljaufilet', k: 80, p: 18, c: 0, f: 0.7, fi: 0, su: 0, sa: 0.2, pr: 22, cat: 'fleisch', fl: 'XAF' },
  seelachs: { n: 'Seelachsfilet (TK)', k: 80, p: 18.5, c: 0, f: 0.8, fi: 0, su: 0, sa: 0.2, pr: 12, cat: 'tk', fl: 'XAF' },
  thunfisch_dose: { n: 'Thunfisch im eigenen Saft (Dose)', k: 105, p: 24, c: 0, f: 1, fi: 0, su: 0, sa: 0.9, pr: 14, cat: 'konserve', fl: 'XAF', u: [140, 'Dose'], b: 'm' },
  garnelen: { n: 'Garnelen (TK, roh, geschält)', k: 75, p: 17, c: 0, f: 0.8, fi: 0, su: 0, sa: 0.8, pr: 22, cat: 'tk', fl: 'XAK' },
  forelle: { n: 'Forellenfilet', k: 120, p: 20, c: 0, f: 4, fi: 0, su: 0, sa: 0.15, pr: 20, cat: 'fleisch', fl: 'XAF' },

  /* ---------- Eier & Milchprodukte ---------- */
  ei: { n: 'Eier (Größe M)', k: 145, p: 12.5, c: 0.7, f: 10, fi: 0, su: 0.7, sa: 0.35, pr: 5, cat: 'milch', fl: 'EA', u: [60, 'Ei'] },
  eiklar: { n: 'Eiklar', k: 50, p: 11, c: 0.7, f: 0.2, fi: 0, su: 0.7, sa: 0.4, pr: 7, cat: 'milch', fl: 'EA' },
  milch: { n: 'Milch 1,5 %', k: 47, p: 3.4, c: 4.9, f: 1.5, fi: 0, su: 4.9, sa: 0.1, pr: 1.1, cat: 'milch', fl: 'LMA', fm: 0, sw: { lf: 'milch_lf', fm: 'milch_lf' } },
  milch_lf: { n: 'Laktosefreie Milch 1,5 %', k: 47, p: 3.4, c: 4.9, f: 1.5, fi: 0, su: 4.9, sa: 0.1, pr: 1.4, cat: 'milch', fl: 'MA' },
  hafermilch: { n: 'Haferdrink', k: 45, p: 0.5, c: 6.5, f: 1.5, fi: 0.8, su: 3.5, sa: 0.1, pr: 1.6, cat: 'milch', fl: 'G', fm: 125 },
  mandelmilch: { n: 'Mandeldrink ungesüßt', k: 15, p: 0.5, c: 0.3, f: 1.2, fi: 0.3, su: 0.1, sa: 0.1, pr: 2.2, cat: 'milch', fl: 'N' },
  magerquark: { n: 'Magerquark', k: 67, p: 12, c: 4, f: 0.3, fi: 0, su: 4, sa: 0.1, pr: 4, cat: 'milch', fl: 'LMA', fm: 0, sw: { lf: 'quark_lf', fm: 'quark_lf' }, u: [250, 'Becher'] },
  quark_lf: { n: 'Laktosefreier Magerquark', k: 67, p: 12, c: 4, f: 0.3, fi: 0, su: 4, sa: 0.1, pr: 5.5, cat: 'milch', fl: 'MA', u: [250, 'Becher'] },
  skyr: { n: 'Skyr natur', k: 63, p: 11, c: 4, f: 0.2, fi: 0, su: 4, sa: 0.1, pr: 4, cat: 'milch', fl: 'LMA', fm: 0, sw: { lf: 'skyr_lf', fm: 'skyr_lf' } },
  skyr_lf: { n: 'Laktosefreier Skyr', k: 63, p: 11, c: 4, f: 0.2, fi: 0, su: 4, sa: 0.1, pr: 5.5, cat: 'milch', fl: 'MA' },
  griech_joghurt: { n: 'Griechischer Joghurt 2 %', k: 75, p: 9, c: 4, f: 2, fi: 0, su: 4, sa: 0.1, pr: 4.5, cat: 'milch', fl: 'LMA', fm: 0, sw: { lf: 'joghurt_lf', fm: 'joghurt_lf' } },
  joghurt: { n: 'Naturjoghurt 1,5 %', k: 50, p: 4, c: 5, f: 1.5, fi: 0, su: 5, sa: 0.1, pr: 1.8, cat: 'milch', fl: 'LMA', fm: 0, sw: { lf: 'joghurt_lf', fm: 'joghurt_lf' } },
  joghurt_lf: { n: 'Laktosefreier Joghurt 1,5 %', k: 50, p: 4, c: 5, f: 1.5, fi: 0, su: 5, sa: 0.1, pr: 2.6, cat: 'milch', fl: 'MA' },
  huettenkaese: { n: 'Hüttenkäse', k: 90, p: 12.5, c: 2.5, f: 3.5, fi: 0, su: 2.5, sa: 0.9, pr: 6, cat: 'milch', fl: 'LMA', fm: 0, sw: { lf: 'huettenkaese_lf', fm: 'huettenkaese_lf' } },
  huettenkaese_lf: { n: 'Laktosefreier Hüttenkäse', k: 90, p: 12.5, c: 2.5, f: 3.5, fi: 0, su: 2.5, sa: 0.9, pr: 8, cat: 'milch', fl: 'MA' },
  frischkaese_light: { n: 'Frischkäse light', k: 150, p: 8, c: 4, f: 11, fi: 0, su: 4, sa: 0.8, pr: 7, cat: 'milch', fl: 'LMA', fm: 0, sw: { lf: 'frischkaese_lf', fm: 'frischkaese_lf' } },
  frischkaese_lf: { n: 'Laktosefreier Frischkäse', k: 160, p: 7, c: 3.5, f: 13, fi: 0, su: 3.5, sa: 0.8, pr: 9, cat: 'milch', fl: 'MA' },
  koerniger_frischkaese: { n: 'Körniger Frischkäse', k: 90, p: 12.5, c: 2.5, f: 3.5, fi: 0, su: 2.5, sa: 0.9, pr: 6, cat: 'milch', fl: 'LMA', fm: 0, sw: { lf: 'huettenkaese_lf', fm: 'huettenkaese_lf' } },
  ricotta: { n: 'Ricotta', k: 150, p: 9, c: 3.5, f: 11, fi: 0, su: 3.5, sa: 0.3, pr: 9, cat: 'milch', fl: 'LMA', fm: 40, sw: { lf: 'quark_lf' } },
  mozzarella: { n: 'Mozzarella light', k: 165, p: 19, c: 1, f: 9.5, fi: 0, su: 1, sa: 0.6, pr: 9, cat: 'milch', fl: 'MA', u: [125, 'Kugel'] },
  feta: { n: 'Feta', k: 260, p: 17, c: 0.5, f: 21, fi: 0, su: 0.5, sa: 2.8, pr: 11, cat: 'milch', fl: 'MA', b: 's' },
  halloumi: { n: 'Halloumi', k: 320, p: 22, c: 2, f: 25, fi: 0, su: 2, sa: 2.7, pr: 16, cat: 'milch', fl: 'MA', b: 's' },
  parmesan: { n: 'Parmesan (gerieben)', k: 400, p: 33, c: 0, f: 29, fi: 0, su: 0, sa: 1.6, pr: 22, cat: 'milch', fl: 'MA' },
  gouda_light: { n: 'Gouda light (gerieben)', k: 270, p: 30, c: 0, f: 16, fi: 0, su: 0, sa: 1.8, pr: 10, cat: 'milch', fl: 'MA' },
  cheddar: { n: 'Cheddar (gerieben)', k: 400, p: 25, c: 1, f: 33, fi: 0, su: 0.5, sa: 1.8, pr: 13, cat: 'milch', fl: 'MA' },
  butter: { n: 'Butter', k: 740, p: 0.7, c: 0.6, f: 83, fi: 0, su: 0.6, sa: 0, pr: 9, cat: 'milch', fl: 'MA' },
  sahne: { n: 'Kochsahne 15 %', k: 165, p: 3, c: 4, f: 15, fi: 0, su: 4, sa: 0.1, pr: 4, cat: 'milch', fl: 'LMA', fm: 40, sw: { lf: 'sahne_lf' } },
  sahne_lf: { n: 'Laktosefreie Kochsahne 15 %', k: 165, p: 3, c: 4, f: 15, fi: 0, su: 4, sa: 0.1, pr: 5, cat: 'milch', fl: 'MA' },
  schmand_light: { n: 'Saure Sahne / Schmand light', k: 115, p: 3, c: 4, f: 10, fi: 0, su: 4, sa: 0.1, pr: 4, cat: 'milch', fl: 'LMA', fm: 40, sw: { lf: 'joghurt_lf' } },
  kokosjoghurt: { n: 'Kokosjoghurt (pflanzlich)', k: 110, p: 1, c: 5, f: 9, fi: 0.5, su: 3, sa: 0.05, pr: 9, cat: 'milch', fl: '' },

  /* ---------- Pflanzliche Proteine ---------- */
  tofu: { n: 'Tofu natur (fest)', k: 125, p: 13, c: 1.5, f: 7.5, fi: 1, su: 0.5, sa: 0.05, pr: 8, cat: 'milch', fl: 'Y' },
  raeuchertofu: { n: 'Räuchertofu', k: 160, p: 16, c: 2, f: 9.5, fi: 1, su: 0.5, sa: 1.2, pr: 10, cat: 'milch', fl: 'Y' },
  tempeh: { n: 'Tempeh', k: 195, p: 19, c: 8, f: 11, fi: 5, su: 0, sa: 0.02, pr: 16, cat: 'milch', fl: 'Y', fm: 100 },
  edamame: { n: 'Edamame (TK, geschält)', k: 120, p: 11.5, c: 6, f: 5, fi: 5, su: 2, sa: 0.02, pr: 8, cat: 'tk', fl: 'Y', fm: 90 },
  kichererbsen: { n: 'Kichererbsen (Dose, abgetropft)', k: 120, p: 7, c: 15, f: 2.5, fi: 6, su: 0.5, sa: 0.5, pr: 3.5, cat: 'konserve', fl: '', fm: 42 },
  rote_linsen: { n: 'Rote Linsen (trocken)', k: 340, p: 24, c: 50, f: 1.5, fi: 11, su: 2, sa: 0.02, pr: 4, cat: 'trocken', fl: '', fm: 23 },
  linsen_dose: { n: 'Linsen (Dose, abgetropft)', k: 100, p: 8, c: 13, f: 0.5, fi: 4.5, su: 0.5, sa: 0.5, pr: 3.5, cat: 'konserve', fl: '', fm: 46 },
  kidneybohnen: { n: 'Kidneybohnen (Dose, abgetropft)', k: 105, p: 7.5, c: 14, f: 0.5, fi: 6, su: 0.5, sa: 0.5, pr: 3, cat: 'konserve', fl: '', fm: 0 },
  schwarze_bohnen: { n: 'Schwarze Bohnen (Dose, abgetropft)', k: 110, p: 7.5, c: 15, f: 0.5, fi: 7, su: 0.3, sa: 0.5, pr: 3.5, cat: 'konserve', fl: '', fm: 0 },
  weisse_bohnen: { n: 'Weiße Bohnen (Dose, abgetropft)', k: 100, p: 7, c: 13, f: 0.5, fi: 6, su: 0.5, sa: 0.5, pr: 3, cat: 'konserve', fl: '', fm: 0 },
  erbsenprotein: { n: 'Veganes Proteinpulver', k: 380, p: 78, c: 4, f: 6, fi: 2, su: 1, sa: 1.5, pr: 28, cat: 'sport', fl: '', b: 'w' },
  /* Markenprodukte (Nährwerte laut Hersteller-Angaben / Open Food Facts, je 100 g Pulver) */
  more_total_sahne: { n: 'More Nutrition Total Protein „Sahne“', k: 397, p: 74, c: 6, f: 6.9, fi: 1, su: 3, sa: 0.6, pr: 50, cat: 'sport', fl: 'LMA', fm: 0, sw: { lf: 'whey_iso', fm: 'whey_iso' }, u: [30, 'Messlöffel'], b: 'w' },
  more_pudding: { n: 'More Nutrition Protein Pudding (Pulver, neutral)', k: 343, p: 56.7, c: 22.7, f: 1.7, fi: 3, su: 5, sa: 1, pr: 70, cat: 'sport', fl: 'LMA', fm: 0, u: [30, 'Portion'], b: 'w' },
  more_chunky: { n: 'More Nutrition Chunky Flavour (Geschmackspulver)', k: 270, p: 2, c: 32, f: 3, fi: 15, su: 3, sa: 0.5, pr: 50, cat: 'sport', fl: '', u: [5, 'Teelöffel'], b: 'w' },
  esn_designer_whey: { n: 'ESN Designer Whey', k: 380, p: 73, c: 7.5, f: 5.3, fi: 0.5, su: 6, sa: 0.5, pr: 33, cat: 'sport', fl: 'LMA', fm: 0, sw: { lf: 'esn_isoclear', fm: 'esn_isoclear' }, u: [30, 'Messlöffel'], b: 'w' },
  esn_isoclear: { n: 'ESN Isoclear Whey Isolate', k: 347, p: 81, c: 3.5, f: 0, fi: 0, su: 1, sa: 0.5, pr: 45, cat: 'sport', fl: 'MA', u: [30, 'Messlöffel'], b: 'w' },
  esn_flexpresso: { n: 'ESN Flexpresso Protein Coffee', k: 360, p: 70, c: 11, f: 3.3, fi: 1, su: 5, sa: 0.6, pr: 40, cat: 'sport', fl: 'LMA', fm: 0, sw: { lf: 'whey_iso', fm: 'whey_iso' }, u: [30, 'Messlöffel'], b: 'w' },
  whey: { n: 'Whey Protein (Vanille)', k: 380, p: 78, c: 7, f: 5, fi: 0, su: 5, sa: 0.5, pr: 30, cat: 'sport', fl: 'MA', u: [30, 'Messlöffel'], b: 'w' },
  whey_iso: { n: 'Whey Isolat (laktosefrei)', k: 370, p: 88, c: 2, f: 1, fi: 0, su: 1, sa: 0.5, pr: 40, cat: 'sport', fl: 'MA', u: [30, 'Messlöffel'], b: 'w' },

  /* ---------- Getreide, Nudeln, Reis ---------- */
  reis: { n: 'Basmatireis (trocken)', k: 350, p: 7.5, c: 78, f: 0.6, fi: 1, su: 0.2, sa: 0, pr: 3, cat: 'trocken', fl: '' },
  vollkornreis: { n: 'Vollkornreis (trocken)', k: 355, p: 7.5, c: 74, f: 2.5, fi: 3.5, su: 0.7, sa: 0, pr: 3.5, cat: 'trocken', fl: '' },
  risottoreis: { n: 'Risottoreis (trocken)', k: 350, p: 7, c: 78, f: 0.6, fi: 1, su: 0.2, sa: 0, pr: 4, cat: 'trocken', fl: '' },
  sushireis: { n: 'Sushi-/Milchreis (trocken)', k: 355, p: 6.5, c: 79, f: 0.5, fi: 1, su: 0.1, sa: 0, pr: 4, cat: 'trocken', fl: '' },
  quinoa: { n: 'Quinoa (trocken)', k: 365, p: 14, c: 64, f: 6, fi: 7, su: 0, sa: 0, pr: 8, cat: 'trocken', fl: '' },
  hirse: { n: 'Hirse (trocken)', k: 355, p: 10.5, c: 69, f: 4, fi: 4, su: 0, sa: 0, pr: 5, cat: 'trocken', fl: '' },
  buchweizen: { n: 'Buchweizen (trocken)', k: 345, p: 13, c: 71, f: 3.4, fi: 10, su: 0, sa: 0, pr: 5, cat: 'trocken', fl: '' },
  couscous: { n: 'Couscous (trocken)', k: 355, p: 12, c: 72, f: 0.6, fi: 5, su: 0, sa: 0, pr: 3, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'quinoa', fm: 'quinoa' } },
  bulgur: { n: 'Bulgur (trocken)', k: 340, p: 12, c: 69, f: 1.3, fi: 12, su: 0.4, sa: 0, pr: 3, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'quinoa', fm: 'quinoa' } },
  haferflocken: { n: 'Haferflocken (zart)', k: 370, p: 13.5, c: 59, f: 7, fi: 10, su: 1, sa: 0, pr: 1.5, cat: 'trocken', fl: 'G', fm: 52, sw: { gf: 'haferflocken_gf' } },
  haferflocken_gf: { n: 'Glutenfreie Haferflocken', k: 370, p: 13.5, c: 59, f: 7, fi: 10, su: 1, sa: 0, pr: 6, cat: 'spezial', fl: '', fm: 52 },
  vollkornnudeln: { n: 'Vollkornnudeln (trocken)', k: 350, p: 13.5, c: 64, f: 2.5, fi: 9, su: 3, sa: 0, pr: 2.5, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'nudeln_gf', fm: 'nudeln_gf' } },
  nudeln: { n: 'Hartweizennudeln (trocken)', k: 355, p: 12.5, c: 71, f: 1.5, fi: 3, su: 3, sa: 0, pr: 2, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'nudeln_gf', fm: 'nudeln_gf' } },
  linsennudeln: { n: 'Rote-Linsen-Nudeln (trocken)', k: 340, p: 25, c: 50, f: 2, fi: 9, su: 2, sa: 0, pr: 9, cat: 'spezial', fl: '', fm: 30, sw: { fm: 'nudeln_gf' } },
  nudeln_gf: { n: 'Glutenfreie Nudeln (Reis/Mais)', k: 355, p: 7, c: 78, f: 1.5, fi: 2, su: 0.5, sa: 0, pr: 5, cat: 'spezial', fl: '' },
  lasagneplatten: { n: 'Lasagneplatten (trocken)', k: 355, p: 12.5, c: 71, f: 1.5, fi: 3, su: 3, sa: 0, pr: 3, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'lasagne_gf', fm: 'lasagne_gf' } },
  lasagne_gf: { n: 'Glutenfreie Lasagneplatten', k: 355, p: 7, c: 78, f: 1.5, fi: 2, su: 0.5, sa: 0, pr: 8, cat: 'spezial', fl: '' },
  reisnudeln: { n: 'Reisnudeln (trocken)', k: 360, p: 6, c: 82, f: 0.6, fi: 1.5, su: 0, sa: 0, pr: 5, cat: 'trocken', fl: '' },
  udon: { n: 'Udon-/Ramen-Nudeln (frisch)', k: 140, p: 4, c: 28, f: 0.5, fi: 1.5, su: 0.5, sa: 0.8, pr: 6, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'reisnudeln', fm: 'reisnudeln' }, swf: 0.4 },
  gnocchi: { n: 'Gnocchi (Kühlregal)', k: 150, p: 3.5, c: 32, f: 0.5, fi: 2, su: 0.5, sa: 1.2, pr: 4, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'gnocchi_gf', fm: 'gnocchi_gf' }, swf: 1 },
  gnocchi_gf: { n: 'Glutenfreie Gnocchi', k: 160, p: 2, c: 35, f: 1, fi: 2, su: 0.5, sa: 1, pr: 7, cat: 'spezial', fl: '' },
  polenta: { n: 'Polenta / Maisgrieß (trocken)', k: 355, p: 8, c: 75, f: 1.5, fi: 4, su: 0.5, sa: 0, pr: 3, cat: 'trocken', fl: '' },
  mehl: { n: 'Weizenmehl Type 405', k: 345, p: 10, c: 72, f: 1, fi: 4, su: 0.5, sa: 0, pr: 0.9, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'mehl_gf', fm: 'mehl_gf' } },
  vollkornmehl: { n: 'Dinkelvollkornmehl', k: 335, p: 13, c: 62, f: 2.5, fi: 9, su: 1, sa: 0, pr: 2, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'mehl_gf', fm: 'mehl_gf' } },
  mehl_gf: { n: 'Glutenfreie Mehlmischung', k: 350, p: 4, c: 80, f: 1.5, fi: 3, su: 1, sa: 0, pr: 5, cat: 'spezial', fl: '' },
  speisestaerke: { n: 'Speisestärke', k: 350, p: 0.4, c: 86, f: 0.1, fi: 0, su: 0, sa: 0, pr: 3, cat: 'trocken', fl: '' },
  paniermehl: { n: 'Paniermehl', k: 360, p: 12, c: 72, f: 2, fi: 4, su: 4, sa: 1.2, pr: 2.5, cat: 'trocken', fl: 'G', fm: 0, sw: { gf: 'paniermehl_gf', fm: 'paniermehl_gf' } },
  paniermehl_gf: { n: 'Glutenfreies Paniermehl', k: 370, p: 5, c: 82, f: 2, fi: 2, su: 2, sa: 1, pr: 8, cat: 'spezial', fl: '' },
  backpulver: { n: 'Backpulver', k: 100, p: 0, c: 25, f: 0, fi: 0, su: 0, sa: 25, pr: 8, cat: 'trocken', fl: '' },
  chiasamen: { n: 'Chiasamen', k: 490, p: 17, c: 8, f: 31, fi: 34, su: 0, sa: 0, pr: 10, cat: 'nuss', fl: '', fm: 24 },
  leinsamen: { n: 'Leinsamen (geschrotet)', k: 500, p: 18, c: 2, f: 42, fi: 27, su: 1.5, sa: 0.1, pr: 4, cat: 'nuss', fl: '', fm: 15 },
  granola: { n: 'Knuspermüsli / Granola', k: 450, p: 10, c: 60, f: 17, fi: 7, su: 18, sa: 0.3, pr: 7, cat: 'trocken', fl: 'GN', fm: 0, sw: { gf: 'granola_gf', fm: 'granola_gf' } },
  granola_gf: { n: 'Glutenfreies Granola', k: 450, p: 9, c: 60, f: 18, fi: 6, su: 16, sa: 0.3, pr: 12, cat: 'spezial', fl: 'N' },
  reiswaffeln: { n: 'Reiswaffeln', k: 385, p: 8, c: 81, f: 3, fi: 4, su: 0.5, sa: 0.1, pr: 8, cat: 'backen', fl: '', u: [8, 'Waffel'] },

  /* ---------- Brot & Backwaren ---------- */
  vollkornbrot: { n: 'Vollkornbrot', k: 215, p: 7.5, c: 38, f: 1.5, fi: 7.5, su: 3, sa: 1.1, pr: 4, cat: 'backen', fl: 'G', fm: 0, sw: { gf: 'brot_gf', fm: 'brot_gf' }, u: [50, 'Scheibe'] },
  sauerteigbrot: { n: 'Dinkel-Sauerteigbrot', k: 240, p: 9, c: 45, f: 1.5, fi: 5, su: 1.5, sa: 1.2, pr: 5, cat: 'backen', fl: 'G', sw: { gf: 'brot_gf' }, u: [50, 'Scheibe'] },
  brot_gf: { n: 'Glutenfreies Brot', k: 240, p: 4, c: 42, f: 6, fi: 6, su: 3, sa: 1.1, pr: 9, cat: 'spezial', fl: '', u: [45, 'Scheibe'] },
  toast_vollkorn: { n: 'Vollkorntoast', k: 245, p: 9, c: 41, f: 3.5, fi: 6, su: 4, sa: 1.1, pr: 3, cat: 'backen', fl: 'G', fm: 0, sw: { gf: 'brot_gf', fm: 'brot_gf' }, u: [28, 'Scheibe'] },
  tortilla: { n: 'Weizentortilla (Vollkorn)', k: 300, p: 9, c: 48, f: 7, fi: 6, su: 2.5, sa: 1.2, pr: 6, cat: 'backen', fl: 'G', fm: 0, sw: { gf: 'tortilla_mais', fm: 'tortilla_mais' }, u: [60, 'Tortilla'] },
  tortilla_mais: { n: 'Maistortillas', k: 220, p: 5.5, c: 44, f: 3, fi: 6, su: 1, sa: 0.8, pr: 9, cat: 'spezial', fl: '', u: [30, 'Tortilla'] },
  burgerbroetchen: { n: 'Vollkorn-Burgerbrötchen', k: 250, p: 9.5, c: 43, f: 4, fi: 6, su: 5, sa: 1.1, pr: 5, cat: 'backen', fl: 'G', fm: 0, sw: { gf: 'broetchen_gf', fm: 'broetchen_gf' }, u: [70, 'Brötchen'] },
  broetchen_gf: { n: 'Glutenfreie Brötchen', k: 250, p: 4, c: 44, f: 6, fi: 5, su: 3, sa: 1.1, pr: 12, cat: 'spezial', fl: '', u: [70, 'Brötchen'] },
  pitabrot: { n: 'Pita-/Fladenbrot', k: 265, p: 9, c: 54, f: 1.5, fi: 2.5, su: 2, sa: 1.2, pr: 4, cat: 'backen', fl: 'G', fm: 0, sw: { gf: 'brot_gf', fm: 'brot_gf' }, u: [70, 'Pita'] },
  naan: { n: 'Naan-Brot', k: 290, p: 8.5, c: 50, f: 6, fi: 2, su: 3, sa: 1.2, pr: 6, cat: 'backen', fl: 'GLMA', fm: 0, sw: { gf: 'brot_gf', fm: 'brot_gf', lf: 'pitabrot' }, u: [90, 'Naan'] },
  bagel: { n: 'Vollkornbagel', k: 255, p: 10, c: 47, f: 2, fi: 5, su: 5, sa: 1.1, pr: 6, cat: 'backen', fl: 'G', fm: 0, sw: { gf: 'broetchen_gf', fm: 'broetchen_gf' }, u: [85, 'Bagel'] },
  pizzateig: { n: 'Pizzateig (Kühlregal)', k: 260, p: 7.5, c: 48, f: 4, fi: 2, su: 2, sa: 1.4, pr: 5, cat: 'backen', fl: 'G', fm: 0, sw: { gf: 'pizzateig_gf', fm: 'pizzateig_gf' } },
  pizzateig_gf: { n: 'Glutenfreier Pizzateig', k: 250, p: 3, c: 48, f: 5, fi: 3, su: 2, sa: 1.2, pr: 10, cat: 'spezial', fl: '' },

  /* ---------- Gemüse ---------- */
  zwiebel: { n: 'Zwiebeln', k: 40, p: 1.2, c: 8, f: 0.1, fi: 1.8, su: 4, sa: 0, pr: 1.5, cat: 'obst', fl: '', fm: 0, sw: { fm: 'lauchgruen' }, u: [100, 'Zwiebel'] },
  rote_zwiebel: { n: 'Rote Zwiebeln', k: 40, p: 1.2, c: 8, f: 0.1, fi: 1.8, su: 4, sa: 0, pr: 2.5, cat: 'obst', fl: '', fm: 0, sw: { fm: 'lauchgruen' }, u: [90, 'Zwiebel'] },
  fruehlingszwiebel: { n: 'Frühlingszwiebeln', k: 30, p: 1.8, c: 5, f: 0.2, fi: 2.5, su: 2, sa: 0, pr: 6, cat: 'obst', fl: '', fm: 0, sw: { fm: 'lauchgruen' }, u: [15, 'Stange'] },
  lauchgruen: { n: 'Lauch-/Frühlingszwiebelgrün', k: 30, p: 1.8, c: 5, f: 0.2, fi: 2.5, su: 2, sa: 0, pr: 6, cat: 'obst', fl: '' },
  lauch: { n: 'Lauch', k: 30, p: 2, c: 4, f: 0.3, fi: 2.3, su: 2.5, sa: 0, pr: 3, cat: 'obst', fl: '', fm: 0, sw: { fm: 'lauchgruen' } },
  knoblauch: { n: 'Knoblauch', k: 140, p: 6, c: 28, f: 0.5, fi: 2, su: 1, sa: 0, pr: 8, cat: 'obst', fl: '', fm: 0, sw: { fm: 'knoblauchoel' }, u: [4, 'Zehe'] },
  knoblauchoel: { n: 'Knoblauch-Öl (FODMAP-arm)', k: 880, p: 0, c: 0, f: 99, fi: 0, su: 0, sa: 0, pr: 20, cat: 'vorrat', fl: '' },
  ingwer: { n: 'Ingwer (frisch)', k: 80, p: 1.8, c: 18, f: 0.8, fi: 2, su: 1.7, sa: 0, pr: 8, cat: 'obst', fl: '' },
  tomate: { n: 'Tomaten', k: 18, p: 0.9, c: 3, f: 0.2, fi: 1.2, su: 2.6, sa: 0, pr: 3, cat: 'obst', fl: '', u: [100, 'Tomate'] },
  kirschtomaten: { n: 'Kirschtomaten', k: 20, p: 1, c: 3.5, f: 0.3, fi: 1.3, su: 3, sa: 0, pr: 6, cat: 'obst', fl: '', b: 'c' },
  paprika: { n: 'Paprika (rot/gelb)', k: 30, p: 1, c: 6, f: 0.3, fi: 2, su: 4.5, sa: 0, pr: 4, cat: 'obst', fl: '', u: [160, 'Paprika'] },
  gurke: { n: 'Salatgurke', k: 15, p: 0.6, c: 2.5, f: 0.1, fi: 0.5, su: 1.7, sa: 0, pr: 2, cat: 'obst', fl: '', u: [400, 'Gurke'] },
  zucchini: { n: 'Zucchini', k: 20, p: 1.5, c: 2.5, f: 0.4, fi: 1, su: 2, sa: 0, pr: 2.5, cat: 'obst', fl: '', fm: 65, u: [250, 'Zucchini'] },
  aubergine: { n: 'Aubergine', k: 25, p: 1, c: 3, f: 0.2, fi: 3, su: 3, sa: 0, pr: 3, cat: 'obst', fl: '', fm: 180, u: [300, 'Aubergine'] },
  brokkoli: { n: 'Brokkoli', k: 35, p: 3, c: 4, f: 0.4, fi: 3, su: 1.7, sa: 0, pr: 3.5, cat: 'obst', fl: '', fm: 75 },
  blumenkohl: { n: 'Blumenkohl', k: 25, p: 2, c: 3, f: 0.3, fi: 2, su: 2, sa: 0, pr: 2.5, cat: 'obst', fl: '', fm: 0 },
  spinat: { n: 'Babyspinat', k: 23, p: 2.9, c: 1.5, f: 0.4, fi: 2.2, su: 0.4, sa: 0.2, pr: 8, cat: 'obst', fl: '' },
  spinat_tk: { n: 'Blattspinat (TK)', k: 23, p: 2.9, c: 1.5, f: 0.4, fi: 2.2, su: 0.4, sa: 0.2, pr: 2.5, cat: 'tk', fl: '' },
  gruenkohl: { n: 'Grünkohl', k: 45, p: 4.3, c: 3, f: 0.9, fi: 4, su: 1.5, sa: 0, pr: 5, cat: 'obst', fl: '' },
  rucola: { n: 'Rucola', k: 25, p: 2.6, c: 2, f: 0.7, fi: 1.6, su: 2, sa: 0, pr: 12, cat: 'obst', fl: '' },
  salat: { n: 'Blattsalat (Romana/Eisberg)', k: 15, p: 1.2, c: 2, f: 0.3, fi: 1.8, su: 1.2, sa: 0, pr: 4, cat: 'obst', fl: '' },
  karotte: { n: 'Karotten', k: 36, p: 0.9, c: 7, f: 0.2, fi: 3, su: 4.7, sa: 0.1, pr: 1.5, cat: 'obst', fl: '', u: [80, 'Karotte'] },
  sellerie: { n: 'Staudensellerie', k: 15, p: 0.7, c: 2, f: 0.2, fi: 1.6, su: 1.3, sa: 0.2, pr: 4, cat: 'obst', fl: '', fm: 10, sw: { fm: 'karotte' }, u: [40, 'Stange'] },
  champignons: { n: 'Champignons', k: 22, p: 3, c: 0.5, f: 0.3, fi: 2, su: 0.5, sa: 0, pr: 5, cat: 'obst', fl: '', fm: 0, sw: { fm: 'austernpilze' } },
  austernpilze: { n: 'Austernpilze', k: 33, p: 3.3, c: 3, f: 0.4, fi: 2.3, su: 1, sa: 0, pr: 12, cat: 'obst', fl: '' },
  kartoffel: { n: 'Kartoffeln (festkochend)', k: 72, p: 2, c: 15, f: 0.1, fi: 1.6, su: 0.8, sa: 0, pr: 1.3, cat: 'obst', fl: '' },
  suesskartoffel: { n: 'Süßkartoffeln', k: 85, p: 1.6, c: 18, f: 0.1, fi: 3, su: 4.2, sa: 0.1, pr: 3, cat: 'obst', fl: '', fm: 75 },
  kuerbis: { n: 'Hokkaido-Kürbis', k: 40, p: 1.7, c: 8, f: 0.2, fi: 2.5, su: 3, sa: 0, pr: 2.5, cat: 'obst', fl: '' },
  erbsen: { n: 'Erbsen (TK)', k: 80, p: 5.5, c: 12, f: 0.4, fi: 5, su: 4.5, sa: 0, pr: 3, cat: 'tk', fl: '', fm: 0 },
  mais: { n: 'Mais (Dose, abgetropft)', k: 85, p: 3, c: 16, f: 1.2, fi: 2.5, su: 4, sa: 0.5, pr: 4, cat: 'konserve', fl: '', fm: 38 },
  gruene_bohnen: { n: 'Grüne Bohnen (TK)', k: 30, p: 2, c: 5, f: 0.2, fi: 3, su: 2.5, sa: 0, pr: 3, cat: 'tk', fl: '', fm: 75 },
  zuckerschoten: { n: 'Zuckerschoten', k: 40, p: 3, c: 5.5, f: 0.2, fi: 2.5, su: 4, sa: 0, pr: 10, cat: 'obst', fl: '', fm: 0, sw: { fm: 'gruene_bohnen' } },
  spargel: { n: 'Grüner Spargel', k: 20, p: 2.2, c: 2, f: 0.1, fi: 2, su: 1.9, sa: 0, pr: 12, cat: 'obst', fl: '', fm: 0, sw: { fm: 'gruene_bohnen' } },
  pak_choi: { n: 'Pak Choi', k: 13, p: 1.5, c: 1.2, f: 0.2, fi: 1, su: 1.2, sa: 0.2, pr: 6, cat: 'obst', fl: '' },
  weisskohl: { n: 'Weiß-/Spitzkohl', k: 25, p: 1.3, c: 4, f: 0.1, fi: 2.5, su: 3.2, sa: 0, pr: 1.5, cat: 'obst', fl: '', fm: 75 },
  rotkohl: { n: 'Rotkohl (frisch)', k: 30, p: 1.4, c: 5, f: 0.2, fi: 2.1, su: 3.8, sa: 0, pr: 2, cat: 'obst', fl: '', fm: 75 },
  rote_bete: { n: 'Rote Bete (vorgegart)', k: 45, p: 1.6, c: 8, f: 0.2, fi: 2.5, su: 7, sa: 0.2, pr: 4, cat: 'obst', fl: '', fm: 20 },
  wokgemuese: { n: 'Wok-Gemüse (TK)', k: 35, p: 2, c: 5, f: 0.3, fi: 2.5, su: 3, sa: 0, pr: 3.5, cat: 'tk', fl: '', fm: 0, sw: { fm: 'pak_choi' } },
  avocado: { n: 'Avocado', k: 160, p: 2, c: 2, f: 15, fi: 6.5, su: 0.7, sa: 0, pr: 8, cat: 'obst', fl: '', fm: 30, u: [150, 'Avocado (Fruchtfleisch)'] },
  oliven: { n: 'Schwarze Oliven (entsteint)', k: 145, p: 1, c: 4, f: 15, fi: 3, su: 0, sa: 2.5, pr: 9, cat: 'konserve', fl: '', b: 'sc' },
  getr_tomaten: { n: 'Getrocknete Tomaten (in Öl, abgetropft)', k: 210, p: 5, c: 14, f: 14, fi: 6, su: 12, sa: 1.5, pr: 18, cat: 'konserve', fl: '', fm: 8 },
  passierte_tomaten: { n: 'Passierte Tomaten', k: 30, p: 1.4, c: 5, f: 0.2, fi: 1.3, su: 4, sa: 0.1, pr: 1.6, cat: 'konserve', fl: '' },
  tomaten_dose: { n: 'Gehackte Tomaten (Dose)', k: 25, p: 1.2, c: 4, f: 0.2, fi: 1.5, su: 3.5, sa: 0.1, pr: 2, cat: 'konserve', fl: '', u: [400, 'Dose'] },
  tomatenmark: { n: 'Tomatenmark', k: 90, p: 4.5, c: 15, f: 0.5, fi: 4, su: 12, sa: 0.3, pr: 5, cat: 'konserve', fl: '' },
  kraeuter: { n: 'Frische Kräuter (Petersilie, Koriander, Basilikum…)', k: 40, p: 3, c: 4, f: 0.7, fi: 3.5, su: 0.8, sa: 0.1, pr: 25, cat: 'obst', fl: '' },
  limette: { n: 'Limetten', k: 30, p: 0.7, c: 8, f: 0.2, fi: 2.8, su: 1.7, sa: 0, pr: 6, cat: 'obst', fl: '', u: [65, 'Limette'] },
  zitrone: { n: 'Zitronen', k: 35, p: 0.9, c: 7, f: 0.3, fi: 2.8, su: 2.5, sa: 0, pr: 4, cat: 'obst', fl: '', u: [100, 'Zitrone'] },
  chili_frisch: { n: 'Chilischote', k: 40, p: 1.9, c: 7, f: 0.4, fi: 1.5, su: 5, sa: 0, pr: 15, cat: 'obst', fl: '', b: 'p', u: [10, 'Schote'] },

  /* ---------- Obst ---------- */
  banane: { n: 'Bananen', k: 93, p: 1.1, c: 21, f: 0.2, fi: 2, su: 17, sa: 0, pr: 1.7, cat: 'obst', fl: '', fm: 100, u: [120, 'Banane (geschält)'] },
  apfel: { n: 'Äpfel', k: 55, p: 0.3, c: 12, f: 0.2, fi: 2.3, su: 10, sa: 0, pr: 2.5, cat: 'obst', fl: '', fm: 0, sw: { fm: 'orange' }, u: [150, 'Apfel'] },
  birne: { n: 'Birnen', k: 55, p: 0.4, c: 12, f: 0.1, fi: 3, su: 10, sa: 0, pr: 3, cat: 'obst', fl: '', fm: 0, sw: { fm: 'kiwi' }, u: [160, 'Birne'] },
  orange: { n: 'Orangen', k: 47, p: 0.9, c: 9, f: 0.1, fi: 2.4, su: 9, sa: 0, pr: 2.5, cat: 'obst', fl: '', u: [150, 'Orange'] },
  kiwi: { n: 'Kiwis', k: 60, p: 1, c: 11, f: 0.5, fi: 3, su: 9, sa: 0, pr: 5, cat: 'obst', fl: '', u: [75, 'Kiwi'] },
  beeren_tk: { n: 'Beerenmix (TK)', k: 45, p: 1, c: 8, f: 0.4, fi: 4, su: 6, sa: 0, pr: 6, cat: 'tk', fl: '', fm: 0, sw: { fm: 'heidelbeeren' } },
  heidelbeeren: { n: 'Heidelbeeren', k: 57, p: 0.7, c: 12, f: 0.3, fi: 2.4, su: 10, sa: 0, pr: 12, cat: 'obst', fl: '' },
  himbeeren: { n: 'Himbeeren', k: 50, p: 1.2, c: 6, f: 0.7, fi: 6.5, su: 4.4, sa: 0, pr: 15, cat: 'obst', fl: '', fm: 60 },
  erdbeeren: { n: 'Erdbeeren', k: 32, p: 0.7, c: 6, f: 0.3, fi: 2, su: 5, sa: 0, pr: 6, cat: 'obst', fl: '' },
  mango: { n: 'Mango', k: 60, p: 0.8, c: 13, f: 0.4, fi: 1.6, su: 13, sa: 0, pr: 6, cat: 'obst', fl: '', fm: 40, sw: { fm: 'ananas' } },
  ananas: { n: 'Ananas', k: 50, p: 0.5, c: 12, f: 0.1, fi: 1.4, su: 10, sa: 0, pr: 3.5, cat: 'obst', fl: '' },
  datteln: { n: 'Datteln (entsteint)', k: 280, p: 2.5, c: 66, f: 0.4, fi: 8, su: 63, sa: 0, pr: 8, cat: 'nuss', fl: '', fm: 0, b: 'c' },
  rosinen: { n: 'Rosinen', k: 300, p: 3, c: 70, f: 0.5, fi: 4, su: 59, sa: 0, pr: 6, cat: 'nuss', fl: '', fm: 0, b: 'c' },

  /* ---------- Nüsse, Saaten, Aufstriche ---------- */
  mandeln: { n: 'Mandeln', k: 600, p: 21, c: 6, f: 52, fi: 12, su: 4.4, sa: 0, pr: 14, cat: 'nuss', fl: 'N', fm: 20, b: 'c' },
  walnuesse: { n: 'Walnüsse', k: 670, p: 15, c: 7, f: 65, fi: 7, su: 2.6, sa: 0, pr: 16, cat: 'nuss', fl: 'N', b: 'c' },
  cashews: { n: 'Cashewkerne', k: 580, p: 18, c: 27, f: 44, fi: 3, su: 6, sa: 0, pr: 16, cat: 'nuss', fl: 'N', fm: 0, sw: { fm: 'erdnuesse' }, b: 'c' },
  erdnuesse: { n: 'Erdnüsse (ungesalzen)', k: 590, p: 26, c: 8, f: 49, fi: 8.5, su: 4, sa: 0, pr: 7, cat: 'nuss', fl: 'P', b: 'c' },
  erdnussbutter: { n: 'Erdnussmus 100 %', k: 620, p: 26, c: 12, f: 50, fi: 7, su: 5, sa: 0, pr: 10, cat: 'nuss', fl: 'P' },
  mandelmus: { n: 'Mandelmus', k: 630, p: 24, c: 6, f: 54, fi: 11, su: 4, sa: 0, pr: 22, cat: 'nuss', fl: 'N', fm: 20 },
  tahini: { n: 'Tahini (Sesammus)', k: 640, p: 20, c: 10, f: 56, fi: 9, su: 0.5, sa: 0.1, pr: 14, cat: 'nuss', fl: 'Z' },
  sesam: { n: 'Sesam', k: 580, p: 18, c: 12, f: 50, fi: 12, su: 0.3, sa: 0, pr: 8, cat: 'nuss', fl: 'Z' },
  kuerbiskerne: { n: 'Kürbiskerne', k: 580, p: 30, c: 5, f: 49, fi: 6, su: 1.4, sa: 0, pr: 14, cat: 'nuss', fl: '', b: 'c' },
  kokosraspeln: { n: 'Kokosraspeln', k: 660, p: 7, c: 7, f: 63, fi: 16, su: 7, sa: 0, pr: 8, cat: 'nuss', fl: '', fm: 30 },
  kakao: { n: 'Backkakao (entölt)', k: 360, p: 20, c: 11, f: 21, fi: 30, su: 1, sa: 0.05, pr: 12, cat: 'nuss', fl: '' },
  zartbitter: { n: 'Zartbitterschokolade 70 %', k: 580, p: 8, c: 33, f: 43, fi: 11, su: 28, sa: 0, pr: 12, cat: 'nuss', fl: 'M', fm: 30 },
  honig: { n: 'Honig', k: 305, p: 0.4, c: 76, f: 0, fi: 0, su: 76, sa: 0, pr: 10, cat: 'vorrat', fl: 'A', fm: 0, sw: { fm: 'ahornsirup' }, b: 'h' },
  ahornsirup: { n: 'Ahornsirup', k: 260, p: 0, c: 67, f: 0, fi: 0, su: 60, sa: 0, pr: 18, cat: 'vorrat', fl: '' },
  zucker: { n: 'Zucker', k: 400, p: 0, c: 100, f: 0, fi: 0, su: 100, sa: 0, pr: 1, cat: 'vorrat', fl: '' },

  /* ---------- Öle, Saucen, Gewürze ---------- */
  olivenoel: { n: 'Olivenöl', k: 880, p: 0, c: 0, f: 99.8, fi: 0, su: 0, sa: 0, pr: 10, cat: 'vorrat', fl: '' },
  rapsoel: { n: 'Rapsöl', k: 880, p: 0, c: 0, f: 99.8, fi: 0, su: 0, sa: 0, pr: 3, cat: 'vorrat', fl: '' },
  sesamoel: { n: 'Geröstetes Sesamöl', k: 880, p: 0, c: 0, f: 99.8, fi: 0, su: 0, sa: 0, pr: 20, cat: 'vorrat', fl: 'Z' },
  kokosoel: { n: 'Kokosöl', k: 880, p: 0, c: 0, f: 99.8, fi: 0, su: 0, sa: 0, pr: 12, cat: 'vorrat', fl: '' },
  kokosmilch_light: { n: 'Kokosmilch light', k: 75, p: 0.7, c: 2, f: 7, fi: 0, su: 1.5, sa: 0.05, pr: 5, cat: 'konserve', fl: '', fm: 125 },
  sojasauce: { n: 'Sojasauce', k: 60, p: 8, c: 6, f: 0.1, fi: 0.8, su: 1, sa: 14, pr: 6, cat: 'vorrat', fl: 'GY', sw: { gf: 'tamari' }, b: 's' },
  tamari: { n: 'Tamari (glutenfreie Sojasauce)', k: 60, p: 10, c: 5, f: 0.1, fi: 0.8, su: 1, sa: 14, pr: 14, cat: 'vorrat', fl: 'Y', b: 's' },
  fischsauce: { n: 'Fischsauce', k: 35, p: 5, c: 3.5, f: 0, fi: 0, su: 3.5, sa: 23, pr: 10, cat: 'vorrat', fl: 'XAF', b: 's' },
  austernsauce: { n: 'Austernsauce', k: 50, p: 1.3, c: 11, f: 0.2, fi: 0.3, su: 8, sa: 9, pr: 8, cat: 'vorrat', fl: 'GXAK', sw: { gf: 'tamari' }, b: 's', swf: 0.7 },
  teriyakisauce: { n: 'Teriyaki-Sauce', k: 130, p: 4, c: 26, f: 0, fi: 0.2, su: 22, sa: 8, pr: 8, cat: 'vorrat', fl: 'GY', fm: 0, sw: { gf: 'tamari', fm: 'tamari' }, b: 's', swf: 0.4 },
  currypaste: { n: 'Thai-Currypaste (grün/rot)', k: 110, p: 2.5, c: 10, f: 6, fi: 4, su: 4, sa: 9, pr: 18, cat: 'vorrat', fl: '', fm: 0, sw: { fm: 'currypulver' }, b: 'ps', swf: 0.3 },
  currypulver: { n: 'Currypulver / Garam Masala', k: 330, p: 13, c: 33, f: 14, fi: 33, su: 3, sa: 0.1, pr: 25, cat: 'vorrat', fl: '' },
  gewuerze: { n: 'Gewürze (Paprika, Kreuzkümmel, Oregano…)', k: 300, p: 13, c: 35, f: 10, fi: 30, su: 5, sa: 0.2, pr: 30, cat: 'vorrat', fl: '' },
  cajun: { n: 'Cajun-/Taco-Gewürz', k: 280, p: 10, c: 45, f: 7, fi: 20, su: 5, sa: 15, pr: 30, cat: 'vorrat', fl: '', fm: 0, sw: { fm: 'gewuerze' }, b: 'ps' },
  salz: { n: 'Salz', k: 0, p: 0, c: 0, f: 0, fi: 0, su: 0, sa: 100, pr: 0.8, cat: 'vorrat', fl: '', b: 's' },
  gemuesebruehe: { n: 'Gemüsebrühe (zubereitet)', k: 5, p: 0.2, c: 0.6, f: 0.2, fi: 0, su: 0.3, sa: 0.9, pr: 0.6, cat: 'vorrat', fl: '', fm: 0, sw: { fm: 'bruehe_fm' }, b: 's' },
  huehnerbruehe: { n: 'Hühnerbrühe (zubereitet)', k: 8, p: 0.6, c: 0.4, f: 0.4, fi: 0, su: 0.2, sa: 0.9, pr: 0.8, cat: 'vorrat', fl: 'XA', fm: 0, sw: { fm: 'bruehe_fm' }, b: 's' },
  bruehe_fm: { n: 'FODMAP-arme Brühe (ohne Zwiebel/Knoblauch)', k: 6, p: 0.3, c: 0.6, f: 0.2, fi: 0, su: 0.3, sa: 0.8, pr: 2, cat: 'spezial', fl: '', b: 's' },
  senf: { n: 'Senf (mittelscharf)', k: 90, p: 6, c: 5, f: 5, fi: 3, su: 3, sa: 3, pr: 4, cat: 'vorrat', fl: '' },
  essig: { n: 'Essig (Balsamico/Apfel)', k: 90, p: 0.5, c: 17, f: 0, fi: 0, su: 15, sa: 0, pr: 4, cat: 'vorrat', fl: '' },
  pesto: { n: 'Pesto Genovese', k: 450, p: 5, c: 5, f: 45, fi: 2, su: 2, sa: 2.5, pr: 18, cat: 'vorrat', fl: 'MN', fm: 0, sw: { fm: 'pesto_fm' }, b: 's' },
  pesto_fm: { n: 'Basilikum-Pesto ohne Knoblauch', k: 450, p: 5, c: 5, f: 45, fi: 2, su: 2, sa: 2, pr: 22, cat: 'spezial', fl: 'MN' },
  mayo_light: { n: 'Salatcreme / Mayo light', k: 280, p: 1, c: 8, f: 27, fi: 0, su: 5, sa: 1.8, pr: 5, cat: 'vorrat', fl: 'EA', b: 's' },
  ketchup: { n: 'Ketchup (zuckerreduziert)', k: 60, p: 1.5, c: 12, f: 0.2, fi: 1, su: 9, sa: 2, pr: 4, cat: 'vorrat', fl: '', fm: 0, sw: { fm: 'tomatenmark' }, swf: 0.5 },
  salsa: { n: 'Tomaten-Salsa', k: 35, p: 1.5, c: 7, f: 0.2, fi: 1.5, su: 5, sa: 1.4, pr: 6, cat: 'vorrat', fl: '', fm: 0, sw: { fm: 'passierte_tomaten' } },
  hummus: { n: 'Hummus (fertig)', k: 270, p: 7, c: 13, f: 21, fi: 6, su: 1, sa: 1.1, pr: 10, cat: 'milch', fl: 'Z', fm: 0 },
  sriracha: { n: 'Sriracha / Chilisauce', k: 95, p: 2, c: 19, f: 1, fi: 2, su: 15, sa: 5.5, pr: 10, cat: 'vorrat', fl: '', fm: 0, sw: { fm: 'chili_frisch' }, b: 'ps' },
  vanille: { n: 'Vanille / Zimt', k: 250, p: 4, c: 80, f: 1, fi: 50, su: 2, sa: 0, pr: 40, cat: 'vorrat', fl: '' },
  hefe: { n: 'Trockenhefe', k: 330, p: 40, c: 40, f: 7, fi: 27, su: 0, sa: 0.1, pr: 20, cat: 'trocken', fl: '' },
};

/* Portionsfaktoren für Haushaltsmitglieder (1 = Erwachsenenportion) */
const MEMBER_TYPES = {
  erwachsen: { n: 'Erwachsene/r', e: '🧑', f: 1.0, age: '18+' },
  teen: { n: 'Teenager', e: '🧒', f: 0.9, age: '11–17 J.' },
  kind: { n: 'Kind', e: '👧', f: 0.6, age: '4–10 J.' },
  kleinkind: { n: 'Kleinkind', e: '🧸', f: 0.35, age: '1–3 J.' },
  baby: { n: 'Baby (Beikost)', e: '👶', f: 0.2, age: '6–12 Mon.' },
};

/* Hinweise für Baby & Kleinkind, abgeleitet aus Zutaten-Flags */
const BABY_WARN = {
  h: { t: 'Honig', d: 'Kein Honig unter 12 Monaten (Botulismus-Risiko). Für das Baby weglassen oder durch Banane ersetzen.', baby: true, kk: false },
  s: { t: 'Salz/Salziges', d: 'Babys bis 12 Monate kein zusätzliches Salz. Baby-Portion vor dem Salzen bzw. vor salzigen Saucen (Soja, Brühe, Feta) entnehmen.', baby: true, kk: true },
  c: { t: 'Verschluckungsgefahr', d: 'Ganze Nüsse, Kirschtomaten, Oliven, Trockenobst: bis 4 J. nur gemahlen, als Mus oder längs geviertelt anbieten.', baby: true, kk: true },
  r: { t: 'Roher Fisch', d: 'Roher/geräucherter Fisch ist für Babys, Kleinkinder (und Schwangere) ungeeignet – Fisch für die Kleinen durchgaren.', baby: true, kk: true },
  p: { t: 'Scharf', d: 'Schärfe (Chili, Currypaste, Cajun) erst nach dem Portionieren für die Erwachsenen zugeben.', baby: true, kk: true },
  m: { t: 'Thunfisch', d: 'Thunfisch kann Quecksilber enthalten – für Kleinkinder höchstens 1× pro Woche in kleiner Menge.', baby: true, kk: true },
  w: { t: 'Proteinpulver & Süßstoffe', d: 'Proteinpulver (z. B. More, ESN) ist für Babys und Kleinkinder nicht geeignet (zu viel Eiweiß, Süßstoffe, Koffein bei Kaffee-Sorten). Kinderportion ohne Pulver zubereiten – z. B. mit Naturjoghurt/Quark und Obst.', baby: true, kk: true },
  n: { t: 'Gepökeltes', d: 'Schinken & Gepökeltes enthalten viel Salz/Nitrit – für Babys weglassen.', baby: true, kk: false },
};

const ALLERGENS = { G: 'Gluten', L: 'Laktose', M: 'Milch', E: 'Ei', N: 'Nüsse', P: 'Erdnuss', F: 'Fisch', K: 'Krebstiere', Y: 'Soja', Z: 'Sesam' };

if (typeof module !== 'undefined') module.exports = { ING, SHOP_CATS, MEMBER_TYPES, BABY_WARN, ALLERGENS };
