// Asiatische & indische Hauptgerichte
Object.assign(ING, {
  asia_reispapier: { n: 'Reispapier', k: 335, p: 6, c: 76, f: 0.5, fi: 1, su: 0, sa: 0.6, pr: 12, cat: 'spezial', fl: '', u: [9, 'Blatt'] },
  asia_rinderbruehe: { n: 'Rinderbrühe (zubereitet)', k: 7, p: 1, c: 0.2, f: 0.3, fi: 0, su: 0, sa: 0.9, pr: 1, cat: 'vorrat', fl: 'XA', fm: 0, sw: { fm: 'bruehe_fm' }, b: 's' },
  asia_gochujang: { n: 'Gochujang (koreanische Chilipaste)', k: 220, p: 4, c: 45, f: 1.5, fi: 2, su: 20, sa: 7, pr: 15, cat: 'vorrat', fl: 'GY', fm: 0, sw: { gf: 'sriracha', fm: 'chili_frisch' }, b: 'ps', swf: 0.4 },
});

(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  {
    id: 'chicken-tikka-masala',
    n: 'Chicken Tikka Masala',
    img: { wiki: 'Chicken tikka masala', q: 'chicken tikka masala rice' },
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort', 'mealprep'],
    i: [['haehnchenbrust', 170], ['griech_joghurt', 50], ['reis', 60], ['passierte_tomaten', 150], ['sahne', 30], ['zwiebel', 60], ['knoblauch', 8], ['ingwer', 8], ['currypulver', 6], ['gewuerze', 2], ['rapsoel', 8], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Hähnchen in 3 cm große Würfel schneiden, mit Joghurt, der Hälfte von Knoblauch, Ingwer und Garam Masala mischen und mindestens 15 Min. marinieren.',
      'Reis in der doppelten Menge Wasser aufkochen und zugedeckt bei kleiner Hitze 12–15 Min. garen.',
      'Hähnchen in einer heißen Pfanne mit der Hälfte des Öls 5–6 Min. rundum scharf anbraten, herausnehmen.',
      'Zwiebel im restlichen Öl 5 Min. glasig dünsten, restlichen Knoblauch, Ingwer und Gewürze 1 Min. mitrösten, passierte Tomaten zugeben und 10 Min. köcheln.',
      'Sahne einrühren, Hähnchen zurück in die Sauce geben und 5 Min. ziehen lassen. Jetzt die Baby-/Kleinkind-Portion entnehmen.',
      'Erwachsenen-Portion mit Salz und nach Wunsch Chili abschmecken, mit Koriander und Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Hähnchen vorher mind. 15 Min. in Joghurt, Knoblauch, Ingwer und Garam Masala marinieren.',
      steps: [
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Currypulver und Gewürze zugeben und mitrösten.', '1 Min.', '120°C', 'Stufe 1', ''],
        ['Passierte Tomaten zugeben und köcheln, Garkörbchen statt Messbecher als Spritzschutz aufsetzen.', '8 Min.', '100°C', 'Stufe 1', ''],
        ['Marinierte Hähnchenwürfel und Sahne zugeben und garen.', '12 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion jetzt entnehmen.', '', '', '', ''],
        ['Rest mit Salz und nach Wunsch Chili abschmecken, mit Koriander und Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes Hähnchen in daumendicke Streifen schneiden oder mit etwas Sauce und Reis zu einem groben Brei pürieren. Kleinkind: mild lassen, Fleisch klein schneiden und mit Reis vermischen, einen Klecks Joghurt dazu.',
    baby: 2,
  },
  {
    id: 'leichtes-butter-chicken',
    n: 'Leichtes Butter Chicken',
    img: { file: 'Chicken makhani.jpg', wiki: 'Butter chicken', q: 'butter chicken murgh makhani' },
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort', 'kinderliebling'],
    i: [['haehnchenbrust', 170], ['griech_joghurt', 50], ['butter', 8], ['passierte_tomaten', 150], ['tomatenmark', 15], ['sahne', 30], ['reis', 60], ['zwiebel', 50], ['knoblauch', 8], ['ingwer', 8], ['currypulver', 6], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Hähnchen würfeln und mit Joghurt, der Hälfte des Garam Masala, Knoblauch und Ingwer 15 Min. marinieren.',
      'Reis in doppelter Menge Wasser 12–15 Min. bei kleiner Hitze garen.',
      'Butter in einer Pfanne schmelzen, Hähnchen bei mittlerer bis hoher Hitze 5 Min. anbraten und herausnehmen.',
      'Zwiebel 4 Min. andünsten, Tomatenmark und restliche Gewürze 1 Min. anrösten, passierte Tomaten zugeben und 10 Min. sämig köcheln.',
      'Sauce fein pürieren, Sahne einrühren, Hähnchen zugeben und 5 Min. gar ziehen lassen. Baby-/Kleinkind-Portion jetzt ungesalzen entnehmen.',
      'Rest mit Salz abschmecken und mit Reis und Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Hähnchen vorher 15 Min. in Joghurt, Garam Masala, Knoblauch und Ingwer marinieren.',
      steps: [
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Butter zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Tomatenmark und restliche Gewürze zugeben und anrösten.', '1 Min.', '120°C', 'Stufe 1', ''],
        ['Passierte Tomaten zugeben und sämig köcheln, Garkörbchen als Spritzschutz aufsetzen.', '8 Min.', '100°C', 'Stufe 1', ''],
        ['Sauce fein pürieren, dabei die Stufe langsam auf 8 erhöhen.', '20 Sek.', '', 'Stufe 8', ''],
        ['Sahne und marinierte Hähnchenwürfel zugeben und gar ziehen lassen.', '12 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion jetzt ungesalzen entnehmen.', '', '', '', ''],
        ['Rest mit Salz abschmecken und mit Reis und Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen in weichen Streifen als Fingerfood oder mit Sauce und Reis fein püriert, ohne Salz. Kleinkind: die milde, cremige Sauce über den Reis geben, Fleisch in mundgerechte Stücke schneiden.',
    baby: 2,
  },
  {
    id: 'rote-linsen-dal',
    n: 'Rote-Linsen-Dal',
    img: { wiki: 'Dal', q: 'red lentil dal masoor' },
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['comfort', 'mealprep', 'kinderliebling'],
    i: [['rote_linsen', 85], ['reis', 35], ['griech_joghurt', 120], ['tomaten_dose', 100], ['spinat', 60], ['zwiebel', 50], ['knoblauch', 8], ['ingwer', 8], ['currypulver', 5], ['gewuerze', 2], ['rapsoel', 7], ['gemuesebruehe', 300], ['zitrone', 10], ['salz', 0.5]],
    s: [
      'Linsen in einem Sieb gründlich waschen, bis das Wasser klar ist.',
      'Zwiebel im Öl 4 Min. glasig dünsten, Knoblauch, Ingwer, Kurkuma, Kreuzkümmel und Garam Masala 1 Min. mitrösten.',
      'Linsen, Tomaten und Brühe zugeben, aufkochen und 15–18 Min. bei kleiner Hitze weich köcheln, dabei gelegentlich umrühren.',
      'Parallel Reis in doppelter Menge Wasser 12–15 Min. garen.',
      'Spinat unterrühren und 1 Min. zusammenfallen lassen. Baby-Portion jetzt entnehmen (mit salzfreier Brühe gekocht).',
      'Rest mit Zitronensaft und Salz abschmecken und mit Reis und einem Klecks Joghurt servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Wegen der Mixtopfgröße nur ca. 900 g Brühe verwenden; salzfreie Brühe für die Baby-Portion.',
      steps: [
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl, Kurkuma, Kreuzkümmel und Garam Masala zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Gewaschene Linsen, Tomaten und 900 g Brühe zugeben und weich garen.', '18 Min.', '100°C', 'Stufe 1', ''],
        ['Spinat zugeben und zusammenfallen lassen.', '2 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion jetzt entnehmen.', '', '', '', ''],
        ['Rest mit Zitronensaft und Salz abschmecken und mit Reis und einem Klecks Joghurt servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Dal ist der perfekte Brei – mit Reis glatt pürieren oder dick als Löffel-Dip anbieten; für BLW auf Reisbällchen streichen. Brühe salzfrei verwenden. Kleinkind: mit Joghurt verrührt und Reis gemischt, dazu Fladenbrot-Streifen zum Dippen.',
    baby: 2,
  },
  {
    id: 'chana-masala',
    n: 'Chana Masala',
    img: { wiki: 'Chana masala', q: 'chana masala chickpea curry' },
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['mealprep'],
    i: [['kichererbsen', 160], ['tomaten_dose', 150], ['zwiebel', 60], ['knoblauch', 8], ['ingwer', 8], ['currypulver', 5], ['gewuerze', 2], ['rapsoel', 7], ['reis', 50], ['griech_joghurt', 170], ['gurke', 50], ['kraeuter', 4], ['zitrone', 10], ['salz', 1]],
    s: [
      'Reis in doppelter Menge Wasser aufkochen und zugedeckt 12–15 Min. garen.',
      'Zwiebel im Öl bei mittlerer Hitze 6 Min. goldbraun braten, Knoblauch, Ingwer, Garam Masala, Kreuzkümmel und Kurkuma 1 Min. mitrösten.',
      'Tomaten zugeben und 5 Min. einköcheln, dann abgetropfte Kichererbsen unterrühren und 10 Min. bei kleiner Hitze schmoren, einige Kichererbsen am Topfrand andrücken.',
      'Für die Raita Gurke fein reiben und mit Joghurt und etwas Minze/Koriander verrühren.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen, den Rest mit Salz, Zitronensaft und nach Wunsch Chili abschmecken.',
      'Mit Reis, Raita und frischem Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Zuerst die Raita, dann Reis und Curry nacheinander im Mixtopf.',
      steps: [
        ['Für die Raita Gurke in Stücken und Minze/Koriander in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Joghurt zugeben, verrühren, in eine Schüssel umfüllen und kalt stellen. Mixtopf spülen.', '10 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Garam Masala, Kreuzkümmel und Kurkuma zugeben und mitrösten.', '1 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten und abgetropfte Kichererbsen zugeben und schmoren.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ungesalzen entnehmen.', '', '', '', ''],
        ['Rest mit Salz, Zitronensaft und nach Wunsch Chili abschmecken, mit Reis, Raita und Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Kichererbsen gut zerdrücken oder mit Joghurt pürieren (ganze Kichererbsen sind rund – nur flach gequetscht anbieten). Kleinkind: Kichererbsen leicht andrücken, mit Reis und Raita mischen.',
    baby: 2,
  },
  {
    id: 'gruenes-thai-curry-haehnchen',
    n: 'Grünes Thai-Curry mit Hähnchen',
    img: { wiki: 'Green curry', q: 'thai green curry chicken' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['comfort'],
    i: [['haehnchenbrust', 170], ['currypaste', 15], ['kokosmilch_light', 125], ['reis', 65], ['zucchini', 60], ['paprika', 80], ['zuckerschoten', 50], ['fischsauce', 5], ['limette', 10], ['kraeuter', 4], ['rapsoel', 6]],
    s: [
      'Reis (am besten Jasminreis) in doppelter Menge Wasser 12–15 Min. garen.',
      'Hähnchen in dünne Streifen, Zucchini und Paprika in mundgerechte Stücke schneiden.',
      'Hähnchen im Öl im Wok 4 Min. anbraten. Für Baby/Kleinkind jetzt ein paar Streifen mit etwas Kokosmilch und Gemüse in einem kleinen Topf separat ohne Paste garen.',
      'Currypaste zum restlichen Hähnchen geben und 1 Min. anrösten, Kokosmilch angießen und aufkochen.',
      'Gemüse und Zuckerschoten zugeben und 5–6 Min. köcheln, bis das Gemüse bissfest ist.',
      'Mit Fischsauce und Limettensaft abschmecken, mit Thai-Basilikum oder Koriander und Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Die Baby-Portion gart ohne Currypaste im Varoma über dem Reis.',
      steps: [
        ['Für Baby/Kleinkind ein paar Hähnchenstreifen und Zucchinistücke mit 2 EL Kokosmilch in eine kleine Schale in den Varoma-Behälter stellen.', '', '', '', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen, Varoma aufsetzen und alles garen. Reis in den Thermoserver umfüllen, Mixtopf leeren.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Currypaste und Öl in den Mixtopf geben und anschwitzen.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Kokosmilch und 100 g Wasser zugeben und aufkochen.', '5 Min.', '100°C', 'Stufe 1', ''],
        ['Hähnchenstreifen, Paprika und Zucchini zugeben und garen.', '8 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Zuckerschoten zugeben und bissfest garen.', '3 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Mit Fischsauce und Limettensaft abschmecken, mit Thai-Basilikum oder Koriander und Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): separat in Kokosmilch gegartes Hähnchen und Zucchini als weiche Sticks oder mit Reis püriert – ohne Currypaste und Fischsauce. Kleinkind: mildes Kokos-Hähnchen mit Reis, ein Löffel Erwachsenen-Sauce nur zum Probieren.',
    baby: 1,
  },
  {
    id: 'rotes-curry-garnelen',
    n: 'Rotes Curry mit Garnelen',
    img: { wiki: 'Red curry', q: 'thai red curry prawns' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['garnelen', 200], ['currypaste', 15], ['kokosmilch_light', 125], ['reis', 70], ['paprika', 80], ['brokkoli', 70], ['fischsauce', 5], ['limette', 10], ['kraeuter', 4], ['rapsoel', 6]],
    s: [
      'Garnelen auftauen und trocken tupfen. Reis in doppelter Menge Wasser 12–15 Min. garen.',
      'Paprika in Streifen schneiden, Brokkoli in kleine Röschen teilen.',
      'Currypaste im Öl im Wok 1 Min. anrösten (Baby-/Kleinkind-Portion vorher separat in Kokosmilch ohne Paste garen).',
      'Kokosmilch angießen, aufkochen, Gemüse zugeben und 4 Min. köcheln.',
      'Garnelen zugeben und 3–4 Min. ziehen lassen, bis sie rosa und vollständig durchgegart sind.',
      'Mit Fischsauce und Limettensaft abschmecken, mit Koriander und Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Brokkoli und die Baby-Garnelen garen im Varoma über dem Reis.',
      steps: [
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen. Brokkoliröschen in den Varoma legen, aufsetzen und garen. Reis und Brokkoli warm stellen, Mixtopf leeren.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Für Baby/Kleinkind nach 12 Min. einige Garnelen auf den Einlegeboden legen und ohne Paste vollständig durchgaren.', '', '', '', ''],
        ['Currypaste und Öl in den Mixtopf geben und anrösten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Kokosmilch, 100 g Wasser und Paprikastreifen zugeben und garen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Garnelen und Brokkoli zugeben und durchziehen lassen, bis die Garnelen rosa und gar sind.', '4 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Mit Fischsauce und Limettensaft abschmecken, mit Koriander und Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Garnelen ohne Paste in Kokosmilch durchgaren, fein hacken und mit Reis und weichem Brokkoli mischen oder pürieren. Kleinkind: Garnelen klein schneiden, Brokkoli-Bäumchen als Fingerfood, Sauce mild.',
    baby: 1,
  },
  {
    id: 'pad-thai-haehnchen',
    n: 'Pad Thai mit Hähnchen',
    img: { wiki: 'Pad thai', q: 'pad thai chicken noodles' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 2,
    st: ['kinderliebling'],
    i: [['reisnudeln', 65], ['haehnchenbrust', 140], ['ei', 60], ['erdnuesse', 15], ['karotte', 40], ['fruehlingszwiebel', 20], ['fischsauce', 8], ['sojasauce', 8], ['zucker', 5], ['limette', 15], ['knoblauch', 4], ['rapsoel', 8], ['kraeuter', 3]],
    s: [
      'Reisnudeln 8–10 Min. in heißem Wasser einweichen, abgießen und kalt abspülen.',
      'Sauce aus Fischsauce, Sojasauce, Zucker und Limettensaft verrühren.',
      'Hähnchen in dünne Streifen schneiden und im heißen Öl im Wok 4 Min. braten, Knoblauch und Karottenstreifen 1 Min. mitbraten.',
      'Alles an den Rand schieben, Ei in die Mitte schlagen, 1 Min. stocken lassen und zerteilen.',
      'Nudeln zugeben und 2 Min. mitbraten. Baby-/Kleinkind-Portion jetzt ohne Sauce entnehmen.',
      'Sauce und Frühlingszwiebeln zum Rest geben, 1 Min. schwenken und mit gehackten Erdnüssen, Koriander und Limette servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Thermomix für Erdnüsse und Sauce, gebraten wird im Wok.',
      steps: [
        ['Erdnüsse in den Mixtopf geben, grob hacken und umfüllen (für das Baby einen Teil fein mahlen).', '3 Sek.', '', 'Stufe 5', ''],
        ['Fischsauce, Sojasauce, Zucker und Limettensaft in den Mixtopf geben und erwärmen, bis der Zucker gelöst ist. Umfüllen.', '2 Min.', '60°C', 'Stufe 2', ''],
        ['Reisnudeln 8–10 Min. in heißem Wasser einweichen, abgießen und kalt abspülen.', '', '', '', ''],
        ['Hähnchenstreifen im heißen Öl im Wok 4 Min. braten, Knoblauch und Karottenstreifen 1 Min. mitbraten.', '', '', '', ''],
        ['Alles an den Rand schieben, Eier in die Mitte schlagen, stocken lassen und zerteilen. Nudeln zugeben und 2 Min. mitbraten.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion jetzt ohne Sauce entnehmen.', '', '', '', ''],
        ['Sauce und Frühlingszwiebeln zugeben, 1 Min. schwenken und mit Erdnüssen, Koriander und Limette servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Nudeln kurz schneiden, Hähnchenstreifen und Rührei als Fingerfood, ohne Sauce; Erdnüsse nur fein gemahlen untermischen (frühe Allergen-Einführung). Kleinkind: wenig Sauce, Erdnüsse gemahlen statt gehackt.',
    baby: 1,
  },
  {
    id: 'haehnchen-teriyaki-reis',
    n: 'Hähnchen-Teriyaki mit Reis',
    img: { wiki: 'Teriyaki', q: 'chicken teriyaki rice bowl' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling', 'mealprep'],
    i: [['haehnchenschenkel', 170], ['teriyakisauce', 30], ['reis', 65], ['brokkoli', 75], ['sesam', 4], ['fruehlingszwiebel', 15], ['ingwer', 5], ['knoblauch', 4], ['rapsoel', 6]],
    s: [
      'Reis in doppelter Menge Wasser 12–15 Min. garen, Brokkoli die letzten 5 Min. darüber dämpfen.',
      'Hähnchenschenkel in breite Streifen schneiden und im Öl in einer Pfanne bei mittlerer bis hoher Hitze 6–7 Min. goldbraun braten.',
      'Baby-/Kleinkind-Portion jetzt ohne Sauce herausnehmen.',
      'Ingwer und Knoblauch kurz mitbraten, Teriyaki-Sauce zugeben und 2 Min. einkochen, bis das Hähnchen glänzt.',
      'Mit Reis und Brokkoli anrichten, mit Sesam und Frühlingszwiebelringen bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Reis und Brokkoli im Thermomix, das Hähnchen wird in der Pfanne gebraten.',
      steps: [
        ['Knoblauch und Ingwer in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 8', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen. Brokkoliröschen in den Varoma legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Währenddessen Hähnchenstreifen im Öl in der Pfanne 6–7 Min. goldbraun braten.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion jetzt ohne Sauce herausnehmen.', '', '', '', ''],
        ['Ingwer und Knoblauch kurz mitbraten, Teriyaki-Sauce zugeben und 2 Min. einkochen, bis das Hähnchen glänzt.', '', '', '', ''],
        ['Mit Reis und Brokkoli anrichten, mit Sesam und Frühlingszwiebelringen bestreuen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): saftige Schenkelstreifen ohne Sauce, weiche Brokkoliröschen und Reisbällchen als Fingerfood. Kleinkind: nur einen Hauch Sauce (salzig/süß), Sesam gemahlen.',
    baby: 2,
  },
  {
    id: 'gebratener-reis-ei-haehnchen',
    n: 'Gebratener Reis mit Ei & Hähnchen',
    img: { wiki: 'Fried rice', q: 'chicken egg fried rice' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling', 'mealprep'],
    i: [['reis', 65], ['haehnchenbrust', 130], ['ei', 90], ['erbsen', 50], ['karotte', 50], ['fruehlingszwiebel', 20], ['sojasauce', 12], ['sesamoel', 4], ['rapsoel', 8], ['knoblauch', 4]],
    s: [
      'Reis am besten am Vortag kochen und kalt stellen (oder frisch gegart auf einem Blech 15 Min. abkühlen lassen).',
      'Hähnchen klein würfeln und in der Hälfte des Öls im Wok 4–5 Min. braten, herausnehmen.',
      'Karottenwürfel, Erbsen und Knoblauch im restlichen Öl 3 Min. braten, Eier zugeben und unter Rühren stocken lassen.',
      'Reis und Hähnchen zugeben und 3–4 Min. bei hoher Hitze braten, bis der Reis leicht knusprig ist.',
      'Baby-/Kleinkind-Portion jetzt entnehmen, Rest mit Sojasauce, Sesamöl und Frühlingszwiebeln abschmecken.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Reis am besten am Vortag im Thermomix garen, gebraten wird im Wok.',
      steps: [
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und garen. Auf einem Blech ausbreiten und auskühlen lassen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Karotte in Stücken und Knoblauch in den Mixtopf geben, zerkleinern und umfüllen.', '4 Sek.', '', 'Stufe 5', ''],
        ['Hähnchenwürfel in der Hälfte des Öls im Wok 4–5 Min. braten, herausnehmen.', '', '', '', ''],
        ['Karotten, Erbsen und Knoblauch im restlichen Öl 3 Min. braten, Eier zugeben und unter Rühren stocken lassen.', '', '', '', ''],
        ['Reis und Hähnchen zugeben und 3–4 Min. bei hoher Hitze knusprig braten.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion entnehmen, Rest mit Sojasauce, Sesamöl und Frühlingszwiebeln abschmecken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ohne Sojasauce; Reis mit Ei zu kleinen Bällchen formen, Hähnchen fein würfeln, Erbsen zerdrücken. Kleinkind: wenig Sojasauce, Erbsen leicht anquetschen.',
    baby: 2,
  },
  {
    id: 'rindfleisch-brokkoli',
    n: 'Rindfleisch mit Brokkoli',
    img: { wiki: 'Beef and broccoli', q: 'beef and broccoli stir fry' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 2,
    i: [['rindersteak', 170], ['brokkoli', 180], ['reis', 65], ['austernsauce', 15], ['sojasauce', 10], ['speisestaerke', 6], ['zucker', 3], ['knoblauch', 8], ['ingwer', 5], ['rapsoel', 8]],
    s: [
      'Reis in doppelter Menge Wasser 12–15 Min. garen.',
      'Rindfleisch quer zur Faser in dünne Streifen schneiden und mit der Hälfte der Speisestärke mischen.',
      'Brokkoli in Röschen teilen und 2 Min. in kochendem Wasser blanchieren, abgießen.',
      'Fleisch im heißen Öl im Wok portionsweise 1–2 Min. scharf anbraten, herausnehmen. Baby-/Kleinkind-Portion jetzt mit etwas Brokkoli beiseitestellen.',
      'Knoblauch und Ingwer 30 Sek. anbraten, Austernsauce, Sojasauce, Zucker, restliche Stärke und 80 ml Wasser zugeben und aufkochen.',
      'Fleisch und Brokkoli in der Sauce 1 Min. schwenken und mit Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Reis, Brokkoli und Sauce im Thermomix, das Fleisch wird im Wok scharf angebraten.',
      steps: [
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen. Brokkoliröschen in den Varoma legen, aufsetzen und garen. Warm stellen, Mixtopf leeren.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Knoblauch und Ingwer in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Austernsauce, Sojasauce, Zucker, restliche Stärke und 200 g Wasser zugeben und andicken.', '4 Min.', '100°C', 'Stufe 3', ''],
        ['Währenddessen die mit Stärke gemischten Fleischstreifen im heißen Öl im Wok portionsweise 1–2 Min. scharf anbraten.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion Fleisch mit etwas Brokkoli beiseitestellen.', '', '', '', ''],
        ['Fleisch, Brokkoli und Sauce im Wok 1 Min. schwenken und mit Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Rindfleisch fein hacken oder mit Reis und Brokkoli pürieren (gute Eisenquelle), Brokkoliröschen weich als Fingerfood. Kleinkind: Fleisch sehr klein schneiden, nur wenig Sauce.',
    baby: 1,
  },
  {
    id: 'teriyaki-lachs-pak-choi',
    n: 'Teriyaki-Lachs mit Pak Choi',
    img: { file: 'Salmon Teriyaki.jpg', wiki: 'Teriyaki', q: 'teriyaki salmon bok choy' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling'],
    i: [['lachs', 150], ['teriyakisauce', 25], ['reis', 60], ['pak_choi', 150], ['sesam', 3], ['ingwer', 5], ['knoblauch', 4], ['rapsoel', 4], ['fruehlingszwiebel', 10]],
    s: [
      'Reis in doppelter Menge Wasser 12–15 Min. garen. Backofen auf 200 °C Ober-/Unterhitze vorheizen.',
      'Lachs auf ein Blech mit Backpapier legen. Baby-/Kleinkind-Stück ohne Sauce danebenlegen, den Rest mit der Hälfte der Teriyaki-Sauce bestreichen.',
      'Lachs 12–14 Min. backen, nach 8 Min. mit restlicher Sauce bestreichen.',
      'Pak Choi längs halbieren und mit Knoblauch und Ingwer im Öl 3–4 Min. braten, mit 2 EL Wasser kurz dämpfen.',
      'Lachs mit Reis und Pak Choi anrichten, mit Sesam und Frühlingszwiebeln bestreuen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Lachs und Pak Choi garen im Varoma statt im Ofen.',
      steps: [
        ['Knoblauch und Ingwer in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 8', ''],
        ['Pak Choi längs halbieren und mit Knoblauch und Ingwer in den Varoma-Behälter legen.', '', '', '', ''],
        ['Lachs auf den gefetteten Einlegeboden legen. Baby-/Kleinkind-Stück ohne Sauce lassen, den Rest mit der Hälfte der Teriyaki-Sauce bestreichen.', '', '', '', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen, Varoma aufsetzen und alles garen, bis der Lachs gar ist.', '22 Min.', 'Varoma', 'Stufe 4', ''],
        ['Mixtopf leeren, restliche Teriyaki-Sauce hineingeben und erwärmen.', '2 Min.', '100°C', 'Stufe 1', ''],
        ['Lachs mit Reis und Pak Choi anrichten, mit warmer Sauce beträufeln und mit Sesam und Frühlingszwiebeln bestreuen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesaucten Lachs grätenfrei zerpflücken, in großen Flocken als Fingerfood oder mit Reis zerdrückt; Pak-Choi-Stiele weich gedämpft. Kleinkind: Lachs mit wenig Sauce, Pak Choi klein geschnitten.',
    baby: 2,
  },
  {
    id: 'poke-bowl-lachs',
    n: 'Poke Bowl mit Lachs',
    img: { wiki: 'Poke (dish)', q: 'salmon poke bowl' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['lachs_sushi', 140], ['sushireis', 60], ['edamame', 50], ['gurke', 60], ['avocado', 30], ['mango', 40], ['sojasauce', 12], ['essig', 10], ['sesam', 4], ['sesamoel', 2], ['fruehlingszwiebel', 10]],
    s: [
      'Sushireis gründlich waschen, mit 1,2-facher Menge Wasser aufkochen und 12 Min. bei kleinster Hitze garen, 10 Min. ruhen lassen und mit Reisessig würzen.',
      'Edamame 3 Min. in kochendem Wasser garen und kalt abschrecken.',
      'Lachs in 1,5 cm große Würfel schneiden und mit Sojasauce und Sesamöl 10 Min. marinieren.',
      'Gurke, Avocado und Mango in Würfel schneiden.',
      'Reis in Schalen füllen, Lachs, Edamame, Gurke, Avocado und Mango darauf anrichten und mit Sesam und Frühlingszwiebeln bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Thermomix für Reis, Edamame und Marinade, der Rest wird frisch angerichtet.',
      steps: [
        ['Edamame in den Varoma-Behälter geben. Für Baby/Kleinkind ein Stück normalen Lachs auf den Einlegeboden legen.', '', '', '', ''],
        ['Gewaschenen Sushireis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen, Varoma aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Reis in eine Schüssel umfüllen, mit Reisessig würzen und 10 Min. ruhen lassen. Edamame kalt abschrecken. Mixtopf leeren.', '', '', '', ''],
        ['Frühlingszwiebel in den Mixtopf geben und zerkleinern, mit Sojasauce und Sesamöl kurz verrühren.', '3 Sek.', '', 'Stufe 5', ''],
        ['Lachswürfel mit der Marinade mischen und 10 Min. ziehen lassen. Gurke, Avocado und Mango würfeln.', '', '', '', ''],
        ['Reis in Schalen füllen, Lachs, Edamame, Gurke, Avocado und Mango darauf anrichten und mit Sesam bestreuen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): kein roher Fisch! Ein Stück normalen Lachs 12 Min. bei 200 °C durchgaren, zerpflücken; dazu Reisbällchen, Avocado- und Mangosticks als Fingerfood. Kleinkind: ebenfalls gegarter Lachs, Edamame zerdrückt.',
    baby: 0,
  },
  {
    id: 'bibimbap',
    n: 'Bibimbap',
    img: { wiki: 'Bibimbap', q: 'bibimbap beef egg rice bowl' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    i: [['rinderhack', 130], ['reis', 60], ['ei', 60], ['spinat', 60], ['karotte', 50], ['zucchini', 60], ['champignons', 50], ['asia_gochujang', 15], ['sojasauce', 10], ['sesamoel', 5], ['rapsoel', 4], ['sesam', 3], ['knoblauch', 4]],
    s: [
      'Reis (Rundkorn oder Basmati) in doppelter Menge Wasser 12–15 Min. garen.',
      'Karotte und Zucchini in Streifen, Champignons in Scheiben schneiden und nacheinander mit wenig Öl je 2–3 Min. anbraten. Spinat 1 Min. zusammenfallen lassen und mit Sesamöl beträufeln.',
      'Hackfleisch mit Knoblauch 5–6 Min. krümelig braten. Baby-/Kleinkind-Portion jetzt entnehmen, Rest mit Sojasauce würzen.',
      'Ei als Spiegelei braten (für Kinder durchgaren).',
      'Reis in Schalen füllen, Gemüse und Hack kranzförmig darauf anrichten, Spiegelei in die Mitte setzen.',
      'Mit Gochujang und Sesam servieren und am Tisch alles gut vermischen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Reis und Gemüse im Thermomix, Hack und Spiegelei in der Pfanne.',
      steps: [
        ['Knoblauch in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 8', ''],
        ['Karotten- und Zucchinistreifen sowie Champignonscheiben in den Varoma-Behälter legen.', '', '', '', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen, Varoma aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Spinat für die letzten 3 Min. auf den Einlegeboden legen, danach mit Sesamöl beträufeln.', '', '', '', ''],
        ['Hackfleisch mit Knoblauch in der Pfanne 5–6 Min. krümelig braten. Baby-/Kleinkind-Portion entnehmen, Rest mit Sojasauce würzen.', '', '', '', ''],
        ['Eier als Spiegeleier braten (für Kinder durchgaren).', '', '', '', ''],
        ['Reis in Schalen füllen, Gemüse und Hack darauf anrichten, Spiegelei in die Mitte setzen und mit Gochujang und Sesam servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürztes Hack mit Reis zu Bällchen formen, Gemüsestreifen weich als Fingerfood, Ei vollständig durchgegart. Kleinkind: alles mild vermischt, ohne Gochujang.',
    baby: 1,
  },
  {
    id: 'ramen-haehnchen-ei',
    n: 'Ramen mit Hähnchen & Ei',
    img: { wiki: 'Ramen', q: 'chicken ramen soft boiled egg' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    st: ['comfort'],
    i: [['udon', 200], ['haehnchenbrust', 140], ['ei', 60], ['huehnerbruehe', 450], ['sojasauce', 15], ['pak_choi', 80], ['champignons', 40], ['fruehlingszwiebel', 15], ['ingwer', 5], ['knoblauch', 4], ['sesamoel', 4], ['rapsoel', 4]],
    s: [
      'Ei 6,5 Min. kochen (für Kinder 9 Min.), kalt abschrecken und pellen.',
      'Hähnchenbrust im Öl 3 Min. pro Seite anbraten, dann zugedeckt bei kleiner Hitze 6–8 Min. gar ziehen lassen und in Scheiben schneiden.',
      'Ingwer und Knoblauch in Sesamöl kurz anschwitzen, Brühe angießen und 10 Min. leise köcheln. Baby-Portion vorher mit salzfreier Brühe abzweigen.',
      'Champignons und Pak Choi in der Brühe 3 Min. garen, mit Sojasauce abschmecken.',
      'Nudeln nach Packungsangabe 2–3 Min. garen, in Schalen verteilen, heiße Brühe darübergießen.',
      'Mit Hähnchen, halbiertem Ei und Frühlingszwiebeln servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Mixtopf max. 2,2 l: ca. 1400 g Brühe verwenden. Udon separat in heißem Wasser erwärmen.',
      steps: [
        ['Ingwer und Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Sesamöl zugeben und andünsten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['1400 g Brühe zugeben, Hähnchenbrust auf den Einlegeboden legen, Varoma aufsetzen und garen. Eier für die letzten 13 Min. (für Kinder 17 Min.) in den Varoma-Behälter legen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
        ['Eier abschrecken und pellen, Hähnchen in Scheiben schneiden. Baby-Portion Brühe jetzt abnehmen (salzfreie Brühe).', '', '', '', ''],
        ['Champignons und Pak Choi in die Brühe geben und garen.', '4 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Brühe mit Sojasauce abschmecken. Udon in Schalen verteilen und mit heißer Brühe übergießen.', '', '', '', ''],
        ['Mit Hähnchen, halbiertem Ei und Frühlingszwiebeln servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Nudeln in kurze Stücke schneiden, Hähnchen fein zupfen, Ei hart gekocht in Spalten; nur wenig salzfreie Brühe. Kleinkind: Nudeln kürzen, Brühe lauwarm und wenig Sojasauce.',
    baby: 1,
  },
  {
    id: 'haehnchen-satay-erdnusssauce',
    n: 'Hähnchen-Satay mit Erdnusssauce',
    img: { wiki: 'Satay', q: 'chicken satay peanut sauce' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    st: ['kinderliebling'],
    i: [['haehnchenbrust', 170], ['erdnussbutter', 25], ['kokosmilch_light', 60], ['sojasauce', 10], ['limette', 10], ['currypulver', 3], ['ahornsirup', 5], ['reis', 60], ['gurke', 80], ['rapsoel', 5], ['knoblauch', 4]],
    s: [
      'Hähnchen in lange, dünne Streifen schneiden, mit Currypulver, der Hälfte der Kokosmilch und Knoblauch 15 Min. marinieren und auf Holzspieße stecken.',
      'Reis in doppelter Menge Wasser 12–15 Min. garen.',
      'Spieße mit Öl bestreichen und in der Grillpfanne oder unter dem Backofengrill (250 °C) 8–10 Min. rundum grillen, bis sie durchgegart sind.',
      'Erdnussmus mit restlicher Kokosmilch, Limettensaft und Ahornsirup glatt rühren. Baby-Portion abnehmen, dann den Rest mit Sojasauce würzen.',
      'Spieße mit Reis, Gurkenscheiben und Erdnusssauce servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Marinade, Reis und Erdnusssauce im Thermomix, die Spieße kommen in die Grillpfanne oder unter den Grill.',
      steps: [
        ['Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Currypulver und die Hälfte der Kokosmilch zugeben und verrühren. Hähnchenstreifen damit 15 Min. marinieren und aufspießen.', '10 Sek.', '', 'Stufe 3', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Spieße mit Öl bestreichen und in der Grillpfanne oder unter dem Backofengrill 8–10 Min. rundum durchgaren.', '', '', '', ''],
        ['Erdnussmus, restliche Kokosmilch, Limettensaft und Ahornsirup in den Mixtopf geben und glatt rühren.', '3 Min.', '60°C', 'Stufe 3', ''],
        ['Baby-Portion Sauce abnehmen.', '', '', '', ''],
        ['Sojasauce zugeben und verrühren. Spieße mit Reis, Gurkenscheiben und Sauce servieren.', '5 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchenstreifen vom Spieß ziehen und als Fingerfood geben, ungesalzene Erdnusssauce dünn als Dip (gute Erdnuss-Einführung). Kleinkind: Spieße vorher entfernen, Gurkensticks dazu.',
    baby: 2,
  },
  {
    id: 'pho-rindfleisch',
    n: 'Pho mit Rindfleisch',
    img: { wiki: 'Pho', q: 'pho bo beef noodle soup' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['comfort'],
    i: [['reisnudeln', 70], ['rindersteak', 150], ['asia_rinderbruehe', 500], ['fischsauce', 8], ['zwiebel', 40], ['ingwer', 10], ['gewuerze', 3], ['kraeuter', 8], ['limette', 15], ['fruehlingszwiebel', 15], ['chili_frisch', 5]],
    s: [
      'Zwiebel und Ingwer halbieren und in einer trockenen Pfanne 5 Min. dunkel anrösten.',
      'Brühe mit Zwiebel, Ingwer, Sternanis, Zimt und Nelke aufkochen und 25 Min. leise köcheln, dann abseihen. Baby-Portion vor der Fischsauce abnehmen.',
      'Rindfleisch 20 Min. anfrieren und hauchdünn aufschneiden.',
      'Reisnudeln nach Packungsangabe einweichen bzw. 3 Min. garen und in Schalen verteilen.',
      'Brühe mit Fischsauce abschmecken. Rindfleisch auf die Nudeln legen und mit kochend heißer Brühe übergießen (für Kinder das Fleisch 2 Min. in der Brühe durchgaren).',
      'Mit Kräutern, Frühlingszwiebeln, Limette und Chili servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Mixtopf max. 2,2 l: ca. 1600 g Brühe verwenden. Zwiebel und Ingwer werden in der Pfanne geröstet.',
      steps: [
        ['Zwiebel und Ingwer halbieren und in einer trockenen Pfanne 5 Min. dunkel anrösten.', '', '', '', ''],
        ['Zwiebel, Ingwer, Sternanis, Zimt und Nelken ins Garkörbchen geben, 1600 g Brühe in den Mixtopf geben, Garkörbchen einsetzen und köcheln.', '25 Min.', '100°C', 'Stufe 1', ''],
        ['Währenddessen Rindfleisch 20 Min. anfrieren und hauchdünn aufschneiden. Reisnudeln nach Packungsangabe einweichen und in Schalen verteilen.', '', '', '', ''],
        ['Garkörbchen herausnehmen. Baby-Portion Brühe jetzt abnehmen.', '', '', '', ''],
        ['Fischsauce zugeben und Brühe aufkochen.', '3 Min.', '100°C', 'Stufe 1', ''],
        ['Rindfleisch auf die Nudeln legen und mit kochend heißer Brühe übergießen (für Kinder das Fleisch 2 Min. in der Brühe durchgaren).', '', '', '', ''],
        ['Mit Kräutern, Frühlingszwiebeln, Limette und Chili servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Rindfleisch vollständig durchgaren und fein hacken, Nudeln kurz schneiden, mit wenig ungesalzener Brühe. Kleinkind: Fleisch klein schneiden, kein Chili, Brühe lauwarm.',
    baby: 1,
  },
  {
    id: 'knuspriger-tofu-stir-fry',
    n: 'Knuspriger Tofu-Stir-Fry',
    img: { q: 'crispy tofu stir fry vegetables' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['mealprep'],
    i: [['tofu', 200], ['speisestaerke', 10], ['reis', 45], ['brokkoli', 75], ['paprika', 100], ['edamame', 40], ['sojasauce', 15], ['ahornsirup', 5], ['ingwer', 5], ['knoblauch', 4], ['sesamoel', 4], ['rapsoel', 6], ['sesam', 3]],
    s: [
      'Tofu 10 Min. zwischen Küchenpapier pressen, in 2 cm Würfel schneiden und in Speisestärke wenden.',
      'Reis in doppelter Menge Wasser 12–15 Min. garen.',
      'Tofu im heißen Öl in einer Pfanne 8–10 Min. rundum goldbraun und knusprig braten, herausnehmen. Baby-Portion entnehmen.',
      'Brokkoli, Paprika und Edamame mit Ingwer und Knoblauch im Wok 4–5 Min. bissfest braten.',
      'Sojasauce, Ahornsirup und Sesamöl verrühren, mit Tofu zum Gemüse geben und 1 Min. schwenken.',
      'Mit Reis servieren und mit Sesam bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Thermomix für Reis und Sauce, Tofu und Gemüse werden in Pfanne/Wok gebraten.',
      steps: [
        ['Knoblauch und Ingwer in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 8', ''],
        ['Sojasauce, Ahornsirup und Sesamöl in den Mixtopf geben, verrühren und umfüllen.', '5 Sek.', '', 'Stufe 3', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Gepressten, in Stärke gewendeten Tofu im heißen Öl 8–10 Min. knusprig braten, herausnehmen. Baby-Portion entnehmen.', '', '', '', ''],
        ['Brokkoli, Paprika und Edamame mit Ingwer und Knoblauch im Wok 4–5 Min. bissfest braten.', '', '', '', ''],
        ['Sauce und Tofu zugeben, 1 Min. schwenken und mit Reis und Sesam servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Tofu in fingerlange Sticks schneiden (ohne Sauce), weichen Brokkoli und Paprikastreifen dazu; Edamame zerdrücken. Kleinkind: wenig Sauce, Edamame halbiert.',
    baby: 2,
  },
  {
    id: 'kung-pao-haehnchen',
    n: 'Kung Pao Hähnchen',
    img: { wiki: 'Kung Pao chicken', q: 'kung pao chicken peanuts' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 2,
    i: [['haehnchenbrust', 170], ['erdnuesse', 20], ['reis', 60], ['paprika', 100], ['fruehlingszwiebel', 20], ['sojasauce', 15], ['essig', 8], ['zucker', 4], ['speisestaerke', 6], ['chili_frisch', 5], ['knoblauch', 8], ['ingwer', 5], ['rapsoel', 6]],
    s: [
      'Hähnchen in 2 cm Würfel schneiden und mit der Hälfte der Speisestärke und 1 TL Sojasauce mischen.',
      'Reis in doppelter Menge Wasser 12–15 Min. garen. Sauce aus restlicher Sojasauce, Essig, Zucker, Stärke und 50 ml Wasser verrühren.',
      'Erdnüsse in einer trockenen Pfanne 3 Min. rösten und beiseitestellen.',
      'Hähnchen im heißen Öl im Wok 4–5 Min. braten, Paprika zugeben und 2 Min. mitbraten. Baby-/Kleinkind-Portion jetzt entnehmen.',
      'Knoblauch, Ingwer und Chili 30 Sek. mitbraten, Sauce angießen und 1 Min. eindicken lassen.',
      'Erdnüsse und Frühlingszwiebeln unterheben und mit Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Thermomix für Reis und Sauce, gebraten wird im Wok.',
      steps: [
        ['Knoblauch und Ingwer und Chili in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 8', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Restliche Sojasauce, Essig, Zucker, Stärke und 200 g Wasser in den Mixtopf geben und andicken.', '4 Min.', '100°C', 'Stufe 3', ''],
        ['Erdnüsse in einer trockenen Pfanne 3 Min. rösten und beiseitestellen.', '', '', '', ''],
        ['Hähnchenwürfel im heißen Öl im Wok 4–5 Min. braten, Paprika 2 Min. mitbraten. Baby-/Kleinkind-Portion jetzt entnehmen.', '', '', '', ''],
        ['Knoblauch, Ingwer und Chili 30 Sek. mitbraten, Sauce zugeben und kurz schwenken.', '', '', '', ''],
        ['Erdnüsse und Frühlingszwiebeln unterheben und mit Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen und Paprika ohne Sauce und Chili, Erdnüsse nur fein gemahlen. Kleinkind: ohne Chili, Erdnüsse gemahlen oder weglassen (Verschluckungsgefahr), wenig Sauce.',
    baby: 1,
  },
  {
    id: 'katsu-curry-haehnchen',
    n: 'Japanisches Katsu-Curry mit Hähnchen',
    img: { wiki: 'Japanese curry', q: 'chicken katsu curry' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['comfort', 'kinderliebling'],
    i: [['haehnchenbrust', 160], ['paniermehl', 20], ['ei', 20], ['mehl', 12], ['rapsoel', 8], ['reis', 50], ['karotte', 60], ['kartoffel', 50], ['zwiebel', 50], ['currypulver', 6], ['huehnerbruehe', 200], ['ahornsirup', 4], ['sojasauce', 5]],
    s: [
      'Backofen auf 220 °C Umluft vorheizen. Hähnchenbrust waagerecht halbieren und flach klopfen.',
      'Fleisch erst in der Hälfte des Mehls, dann in verquirltem Ei und zuletzt in Paniermehl wenden, mit der Hälfte des Öls beträufeln und 15–18 Min. knusprig backen.',
      'Reis in doppelter Menge Wasser 12–15 Min. garen.',
      'Zwiebel, Karotte und Kartoffel würfeln und im restlichen Öl 5 Min. anschwitzen, restliches Mehl und Currypulver 1 Min. mitrösten.',
      'Brühe nach und nach einrühren und 15 Min. köcheln, bis das Gemüse weich ist; fein pürieren. Baby-Portion entnehmen, Rest mit Sojasauce und Ahornsirup abschmecken.',
      'Schnitzel in Streifen schneiden und mit Reis und Currysauce servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Reis und Currysauce im Thermomix, die Schnitzel werden im Ofen gebacken.',
      steps: [
        ['Backofen auf 220 °C Umluft vorheizen. Hähnchen flach klopfen, panieren, mit Öl beträufeln und 15–18 Min. knusprig backen.', '', '', '', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel, Karotte und Kartoffel in Stücken in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Restliches Öl zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Restliches Mehl und Currypulver zugeben und mitrösten.', '1 Min.', '120°C', 'Stufe 1', ''],
        ['800 g Brühe zugeben und garen, bis das Gemüse weich ist.', '15 Min.', '100°C', 'Stufe 1', ''],
        ['Sauce fein pürieren, dabei die Stufe langsam auf 8 erhöhen.', '30 Sek.', '', 'Stufe 8', ''],
        ['Baby-Portion entnehmen.', '', '', '', ''],
        ['Rest mit Sojasauce und Ahornsirup abschmecken, Schnitzel in Streifen schneiden und mit Reis und Sauce servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): panierte Hähnchenstreifen (salzfreie Brühe) als Fingerfood, weiche Karotten- und Kartoffelstücke dazu, Sauce als Dip. Kleinkind: die milde, sämige Sauce ist ideal – Schnitzel klein schneiden.',
    baby: 2,
  },
  {
    id: 'suesskartoffel-kichererbsen-curry',
    n: 'Süßkartoffel-Kichererbsen-Curry',
    img: { q: 'sweet potato chickpea curry spinach' },
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['mealprep', 'kinderliebling'],
    i: [['suesskartoffel', 150], ['kichererbsen', 100], ['rote_linsen', 40], ['kokosmilch_light', 100], ['tomaten_dose', 80], ['spinat', 50], ['zwiebel', 40], ['knoblauch', 4], ['ingwer', 5], ['currypulver', 5], ['rapsoel', 7], ['griech_joghurt', 100], ['salz', 0.5], ['kraeuter', 3]],
    s: [
      'Süßkartoffel schälen und in 2 cm Würfel schneiden, Linsen waschen.',
      'Zwiebel im Öl 4 Min. andünsten, Knoblauch, Ingwer und Currypulver 1 Min. mitrösten.',
      'Süßkartoffel, Linsen, Tomaten, Kokosmilch und 150 ml Wasser zugeben, aufkochen und 15 Min. zugedeckt köcheln.',
      'Kichererbsen zugeben und 5 Min. mitgaren, dann Spinat unterrühren.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest mit Salz und nach Wunsch Chili abschmecken.',
      'Mit einem Klecks Joghurt und Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Der Mixtopf ist gut gefüllt – bei größeren Mengen in zwei Durchgängen kochen.',
      steps: [
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Currypulver zugeben und mitrösten.', '1 Min.', '120°C', 'Stufe 1', ''],
        ['Süßkartoffelwürfel, gewaschene Linsen, Tomaten, Kokosmilch und 300 g Wasser zugeben und garen.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Kichererbsen und Spinat zugeben und mitgaren.', '5 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ungesalzen entnehmen.', '', '', '', ''],
        ['Rest mit Salz und nach Wunsch Chili abschmecken, mit Joghurt und Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): alles zu einem cremigen Brei pürieren oder Süßkartoffelwürfel als weiches Fingerfood; Kichererbsen zerdrücken. Kleinkind: grob zerstampft mit Joghurt, dazu Brotstreifen zum Dippen.',
    baby: 2,
  },
  {
    id: 'saag-haehnchen',
    n: 'Saag-Hähnchen (Spinat-Curry)',
    img: { wiki: 'Saag', q: 'saag chicken spinach curry' },
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['mealprep'],
    i: [['haehnchenbrust', 170], ['spinat_tk', 200], ['griech_joghurt', 60], ['sahne', 20], ['zwiebel', 60], ['tomate', 80], ['knoblauch', 8], ['ingwer', 8], ['currypulver', 6], ['rapsoel', 8], ['reis', 60], ['salz', 1]],
    s: [
      'Spinat auftauen und gut ausdrücken. Reis in doppelter Menge Wasser 12–15 Min. garen.',
      'Hähnchen würfeln und in der Hälfte des Öls 5 Min. anbraten, herausnehmen.',
      'Zwiebel im restlichen Öl 5 Min. goldgelb braten, Knoblauch, Ingwer und Garam Masala 1 Min. mitrösten, gewürfelte Tomate zugeben und 3 Min. einkochen.',
      'Spinat und 100 ml Wasser zugeben, 5 Min. köcheln und grob pürieren.',
      'Hähnchen, Joghurt und Sahne einrühren und 6–8 Min. bei kleiner Hitze gar ziehen lassen (nicht kochen). Baby-Portion jetzt entnehmen.',
      'Rest mit Salz abschmecken und mit Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Spinat vorher auftauen und gut ausdrücken.',
      steps: [
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Garam Masala zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Tomate in Stücken zugeben und einkochen.', '3 Min.', '100°C', 'Stufe 1', ''],
        ['Spinat und 100 g Wasser zugeben und köcheln.', '5 Min.', '100°C', 'Stufe 1', ''],
        ['Grob pürieren.', '10 Sek.', '', 'Stufe 6', ''],
        ['Hähnchenwürfel, Joghurt und Sahne zugeben und gar ziehen lassen (nicht kochen).', '12 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion jetzt entnehmen.', '', '', '', ''],
        ['Rest mit Salz abschmecken und mit Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen und Spinatsauce mit Reis fein pürieren – eisenreicher Brei; oder Hähnchenstreifen zum Eintunken. Kleinkind: grün, mild und cremig – Hähnchen klein schneiden und mit Reis mischen.',
    baby: 2,
  },
  {
    id: 'tandoori-haehnchen-raita',
    n: 'Tandoori-Hähnchen mit Raita',
    img: { file: 'Tandoori chicken Indian.jpg', wiki: 'Tandoori chicken', q: 'tandoori chicken raita' },
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['mealprep'],
    i: [['haehnchenbrust', 180], ['griech_joghurt', 160], ['gurke', 80], ['zitrone', 10], ['currypulver', 6], ['gewuerze', 3], ['knoblauch', 8], ['ingwer', 8], ['reis', 60], ['rapsoel', 6], ['rote_zwiebel', 30], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Hähnchen mehrfach einschneiden. 60 g Joghurt mit Zitronensaft, Knoblauch, Ingwer, Garam Masala, Paprika und Kurkuma verrühren, Hähnchen darin mindestens 30 Min. (besser über Nacht) marinieren.',
      'Backofen auf 230 °C Ober-/Unterhitze vorheizen. Hähnchen auf ein Gitter legen, mit Öl beträufeln und 18–22 Min. backen, bis es durchgegart und an den Rändern leicht gebräunt ist.',
      'Reis in doppelter Menge Wasser 12–15 Min. garen.',
      'Für die Raita Gurke reiben, mit restlichem Joghurt, Minze/Koriander verrühren. Baby-Portion abnehmen, Rest mit wenig Salz würzen.',
      'Hähnchen aufschneiden und mit Reis, Raita und roten Zwiebelringen servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Marinade, Raita und Reis im Thermomix, das Hähnchen wird im Ofen gebacken.',
      steps: [
        ['Knoblauch und Ingwer in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['240 g Joghurt, Zitronensaft und Gewürze zugeben und verrühren. Eingeschnittenes Hähnchen darin mind. 30 Min. marinieren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Hähnchen auf einem Gitter im vorgeheizten Ofen bei 230 °C 18–22 Min. backen, bis es durchgegart ist.', '', '', '', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Für die Raita Gurke in Stücken und Minze/Koriander in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Restlichen Joghurt zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Baby-Portion Raita abnehmen, Rest mit wenig Salz würzen.', '', '', '', ''],
        ['Hähnchen aufschneiden und mit Reis, Raita und roten Zwiebelringen servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ein Stück ohne Salz und Chili marinieren, in weiche Streifen schneiden; Raita als Dip. Kleinkind: mild gewürzt, Fleisch klein schneiden, Gurkensticks dazu.',
    baby: 2,
  },
  {
    id: 'mildes-haehnchen-korma',
    n: 'Mildes Hähnchen-Korma',
    img: { wiki: 'Korma', q: 'chicken korma creamy curry' },
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort', 'kinderliebling'],
    i: [['haehnchenbrust', 170], ['cashews', 15], ['griech_joghurt', 80], ['kokosmilch_light', 80], ['zwiebel', 60], ['knoblauch', 4], ['ingwer', 6], ['currypulver', 5], ['rapsoel', 6], ['reis', 50], ['salz', 0.5], ['kraeuter', 3]],
    s: [
      'Cashews 10 Min. in heißem Wasser einweichen und mit 50 ml Wasser fein pürieren. Reis in doppelter Menge Wasser 12–15 Min. garen.',
      'Zwiebel im Öl 6 Min. sanft weich dünsten, ohne zu bräunen. Knoblauch, Ingwer und milde Gewürze (Garam Masala, Kurkuma, Kardamom) 1 Min. mitrösten.',
      'Hähnchenwürfel zugeben und 3 Min. rundum anbraten.',
      'Cashewcreme und Kokosmilch einrühren und 12 Min. bei kleiner Hitze köcheln.',
      'Vom Herd nehmen, Joghurt unterrühren. Baby-Portion jetzt entnehmen, Rest mit Salz abschmecken.',
      'Mit Reis und Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Cashews müssen nicht eingeweicht werden – der Thermomix püriert sie fein.',
      steps: [
        ['Cashews und 200 g heißes Wasser in den Mixtopf geben, fein pürieren und umfüllen.', '1 Min.', '', 'Stufe 10', ''],
        ['Reis im Garkörbchen einwiegen, 1000 g Wasser in den Mixtopf geben, Garkörbchen einsetzen und Reis garen. Danach in den Thermoserver umfüllen und den Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und sanft dünsten, ohne zu bräunen. Nach 5 Min. Garam Masala, Kurkuma und Kardamom zugeben.', '6 Min.', '100°C', 'Stufe 1', ''],
        ['Hähnchenwürfel, Cashewcreme und Kokosmilch zugeben und garen.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Joghurt zugeben und unterrühren.', '20 Sek.', '', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion jetzt entnehmen.', '', '', '', ''],
        ['Rest mit Salz abschmecken und mit Reis und Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): mild-cremig und nussig (Cashews fein püriert = sichere Nuss-Einführung) – Hähnchen mit Sauce und Reis pürieren oder als Streifen zum Eintunken. Kleinkind: so wie es ist, Fleisch klein geschnitten.',
    baby: 2,
  },
  {
    id: 'chow-mein-haehnchen',
    n: 'Chow Mein mit Hähnchen',
    img: { wiki: 'Chow mein', q: 'chicken chow mein noodles' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling'],
    i: [['nudeln', 70], ['haehnchenbrust', 150], ['weisskohl', 70], ['karotte', 50], ['paprika', 60], ['fruehlingszwiebel', 20], ['sojasauce', 15], ['austernsauce', 10], ['sesamoel', 4], ['rapsoel', 8], ['knoblauch', 4], ['ingwer', 5]],
    s: [
      'Mie-Nudeln nach Packungsangabe 3–4 Min. garen, abgießen und mit 1 TL Öl vermengen.',
      'Hähnchen in dünne Streifen schneiden und im heißen Öl im Wok 4 Min. braten, herausnehmen.',
      'Kohl, Karotte und Paprika in feine Streifen schneiden und mit Knoblauch und Ingwer 3 Min. pfannenrühren.',
      'Nudeln und Hähnchen zugeben und 2 Min. braten. Baby-/Kleinkind-Portion jetzt entnehmen.',
      'Rest mit Sojasauce, Austernsauce und Sesamöl schwenken und mit Frühlingszwiebeln servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Nudeln im Thermomix, gebraten wird im Wok.',
      steps: [
        ['Knoblauch und Ingwer in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 8', ''],
        ['1200 g Wasser in den Mixtopf geben und aufkochen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Mie-Nudeln zugeben und nach Packungsangabe garen, abgießen und mit 1 TL Öl vermengen.', '4 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Hähnchenstreifen im heißen Öl im Wok 4 Min. braten, herausnehmen.', '', '', '', ''],
        ['Kohl, Karotte und Paprika in feinen Streifen mit Knoblauch und Ingwer 3 Min. pfannenrühren, Nudeln und Hähnchen 2 Min. mitbraten.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion jetzt entnehmen.', '', '', '', ''],
        ['Rest mit Sojasauce, Austernsauce und Sesamöl schwenken und mit Frühlingszwiebeln servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Nudeln in kurze Stücke schneiden, Hähnchen- und weiche Gemüsestreifen als Fingerfood, ohne Saucen. Kleinkind: wenig Sojasauce, Nudeln etwas kürzen.',
    baby: 2,
  },
  {
    id: 'sommerrollen-garnelen-erdnussdip',
    n: 'Sommerrollen mit Garnelen & Erdnussdip',
    img: { wiki: 'Gỏi cuốn', q: 'vietnamese summer rolls shrimp peanut sauce' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    i: [['asia_reispapier', 36], ['garnelen', 160], ['reisnudeln', 40], ['salat', 30], ['gurke', 50], ['karotte', 40], ['kraeuter', 8], ['erdnussbutter', 20], ['sojasauce', 8], ['limette', 10], ['ahornsirup', 4]],
    s: [
      'Garnelen 3–4 Min. in siedendem Wasser garen, bis sie rosa und durchgegart sind, abschrecken und längs halbieren.',
      'Reisnudeln nach Packungsangabe einweichen, abgießen und kurz schneiden. Gurke und Karotte in feine Stifte schneiden.',
      'Ein Reispapierblatt 10 Sek. in lauwarmes Wasser tauchen und auf ein feuchtes Brett legen.',
      'Salat, Nudeln, Gemüse und Kräuter auf das untere Drittel legen, Garnelen mit der Schnittfläche nach oben darüber, Seiten einschlagen und straff aufrollen. Mit allen Blättern wiederholen.',
      'Erdnussmus mit Limettensaft, Ahornsirup und 2–3 EL warmem Wasser glatt rühren, für Erwachsene mit Sojasauce würzen.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen. Der Thermomix macht nur den Erdnussdip, die Rollen werden von Hand gerollt.',
      steps: [
        ['Garnelen 3–4 Min. in siedendem Wasser durchgaren, abschrecken und längs halbieren. Reisnudeln einweichen, Gurke und Karotte in Stifte schneiden.', '', '', '', ''],
        ['Reispapier kurz in lauwarmes Wasser tauchen, füllen und straff aufrollen.', '', '', '', ''],
        ['Erdnussmus, Limettensaft, Ahornsirup und 60 g warmes Wasser in den Mixtopf geben und glatt rühren.', '20 Sek.', '', 'Stufe 4', ''],
        ['Baby-Portion Dip abnehmen.', '', '', '', ''],
        ['Sojasauce zugeben und verrühren.', '5 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Reispapier ist klebrig und zäh – lieber die Füllung als Fingerfood: Garnelen fein gehackt, Nudeln, weiche Karottenstifte und ungesalzener Erdnussdip. Kleinkind: Rolle in kleine Stücke schneiden.',
    baby: 1,
  },
]);
