// Kalorienarme, proteinreiche Desserts ohne Backofen: Quarkspeisen, Skyr- und Joghurtcremes, Mousse,
// Tiramisu- und Cheesecake-Cremes im Glas, Trifle, Bowls und Schichtdesserts – alle glutenfrei umsetzbar.
// Geschmackspulver, Zero-Sirup und Proteinpulver sind nicht für Babys und Kleinkinder: Kinderportion immer ohne.
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  /* ---------- Fruchtquark & Quarkspeisen ---------- */
  {
    id: 'erdbeerquark-klassisch',
    n: 'Erdbeerquark wie bei Oma',
    img: { wiki: 'Quark (dairy product)', q: 'strawberry quark dessert' },
    ck: 'Erdbeerquark',
    cu: 'deutsch', m: ['snack'], t: 10, d: 1, st: ['dessert', 'kinderliebling'],
    i: [['magerquark', 200], ['erdbeeren', 150], ['milch', 30], ['more_chunky', 4], ['vanille', 1]],
    s: [
      'Erdbeeren waschen, entkelchen. Ein Drittel in kleine Würfel schneiden, den Rest mit einer Gabel fein zerdrücken.',
      'Magerquark mit Milch und Vanille glatt rühren, bis er cremig ist.',
      'Kinderportion jetzt abnehmen (ohne Geschmackspulver).',
      'Chunky Flavour (z. B. Strawberry Cream) und das Erdbeerpüree unterrühren, mit den Erdbeerwürfeln toppen und 10 Min. kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Zwei Drittel der Erdbeeren in den Mixtopf geben und pürieren.', '5 Sek.', '', 'Stufe 6', ''],
      ['Quark, Milch und Vanille zugeben und cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Kinderportion entnehmen.', '', '', '', ''],
      ['Chunky Flavour zugeben und unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['In Schalen füllen und mit Erdbeerwürfeln toppen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): 1–2 EL Quark mit zerdrückten Erdbeeren, ohne Pulver – Quark wegen des hohen Eiweißgehalts nur in kleinen Mengen. Kleinkind: Erdbeerquark ohne Chunky, mit etwas reifer Banane gesüßt.',
    baby: 1,
  },
  {
    id: 'pfirsich-melba-quark',
    n: 'Pfirsich-Melba-Quark',
    img: { wiki: 'Peach Melba', q: 'peach melba raspberries dessert' },
    ck: 'Pfirsich Melba',
    cu: 'international', m: ['snack'], t: 10, d: 1, st: ['dessert'],
    i: [['magerquark', 180], ['skyr', 50], ['pfirsiche_dose', 100], ['himbeeren', 50], ['more_chunky', 4], ['vanille', 1]],
    s: [
      'Pfirsiche abtropfen lassen und in Spalten schneiden.',
      'Himbeeren mit einer Gabel zu einer stückigen Sauce zerdrücken.',
      'Quark, Skyr, Vanille und Chunky Flavour (z. B. Vanilla) cremig rühren.',
      'Creme in Gläser füllen, Pfirsichspalten darauflegen und mit der Himbeersauce beträufeln.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Himbeeren in den Mixtopf geben und zu Sauce pürieren, umfüllen.', '5 Sek.', '', 'Stufe 5', ''],
      ['Quark, Skyr und Vanille zugeben und cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Kinderportion entnehmen, dann Chunky Flavour unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Mit Pfirsichspalten und Himbeersauce anrichten.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): weiche Pfirsichspalten als Fingerfood, dazu 1–2 EL Quark mit Himbeermus. Kleinkind: Creme ohne Chunky Flavour, Pfirsich in Würfeln.',
    baby: 1,
  },
  {
    id: 'banoffee-quark',
    n: 'Banoffee-Quark im Glas',
    img: { wiki: 'Banoffee pie', q: 'banoffee dessert glass' },
    ck: 'Banoffee im Glas',
    cu: 'international', m: ['snack'], t: 10, d: 1, st: ['dessert', 'kinderliebling'],
    i: [['magerquark', 200], ['banane', 70], ['more_chunky', 5], ['milch', 30], ['reiswaffeln', 8], ['kakao', 2]],
    s: [
      'Banane in Scheiben schneiden. Reiswaffel grob zerbröseln.',
      'Quark mit Milch und Chunky Flavour (z. B. Salted Caramel oder Banana Toffee) cremig rühren.',
      'Reiswaffelbrösel als Boden ins Glas geben, Hälfte der Creme und Bananenscheiben darauf schichten.',
      'Restliche Creme und Bananen darauf geben, mit Kakao bestäuben.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Reiswaffeln in den Mixtopf geben und grob zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 4', ''],
      ['Quark und Milch cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Kinderportion entnehmen, dann Chunky Flavour unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Mit Bröseln und Bananenscheiben in Gläser schichten, mit Kakao bestäuben.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 6 Mon.): Bananenstick als Fingerfood, ab 8 Mon. dazu 1–2 EL Quark mit zerdrückter Banane. Kleinkind: Bananen-Quark ohne Chunky und ohne Kakao, Reiswaffelbrösel obendrauf.',
    baby: 1,
  },
  {
    id: 'bratapfel-quark',
    n: 'Bratapfel-Quark',
    img: { wiki: 'Baked apple', q: 'baked apple quark cinnamon' },
    ck: 'Bratapfel Creme',
    cu: 'deutsch', m: ['snack'], t: 20, d: 1, st: ['dessert', 'comfort'],
    i: [['magerquark', 180], ['apfel', 150], ['walnuesse', 6], ['zimt', 1], ['vanille', 1], ['more_chunky', 3]],
    s: [
      'Apfel entkernen, in Würfel schneiden und mit Zimt und 3 EL Wasser in einer Pfanne 6–8 Min. weich schmoren.',
      'Quark mit Vanille cremig rühren, Kinderportion abnehmen, dann Chunky Flavour (z. B. Bratapfel oder Cinnamon Cereal) unterrühren.',
      'Warme Apfelwürfel in eine Schale geben und den kalten Quark darauf setzen.',
      'Mit gehackten Walnüssen bestreuen und sofort servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Walnüsse grob hacken, umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
      ['Apfelwürfel, Zimt und 50 g Wasser in den Mixtopf geben und garen.', '8 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
      ['Äpfel umfüllen. Quark und Vanille cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Kinderportion entnehmen, Chunky Flavour unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Warme Äpfel mit Quark und Walnüssen anrichten.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 6 Mon.): weich geschmorte Apfelstücke als Fingerfood oder püriert, ab 8 Mon. mit wenig Quark. Kleinkind: ohne Chunky, Walnüsse fein gemahlen.',
    baby: 1,
  },
  {
    id: 'carrot-cake-quark',
    n: 'Carrot-Cake-Quark',
    img: { wiki: 'Carrot cake', q: 'carrot cake quark bowl' },
    ck: 'Karottenkuchen Quark',
    cu: 'amerikanisch', m: ['snack'], t: 10, d: 1, st: ['dessert'],
    i: [['magerquark', 200], ['karotte', 60], ['frischkaese_light', 20], ['zimt', 1], ['walnuesse', 6], ['rosinen', 8], ['erythrit', 8]],
    s: [
      'Karotte sehr fein raspeln.',
      'Quark mit Frischkäse, Zimt und Erythrit zu einer Frosting-Creme rühren.',
      'Karottenraspel und Rosinen unterheben.',
      'In eine Schale füllen und mit gehackten Walnüssen bestreuen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Walnüsse grob hacken, umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
      ['Karotten in Stücken in den Mixtopf geben und fein raspeln.', '5 Sek.', '', 'Stufe 5', ''],
      ['Quark, Frischkäse, Zimt, Erythrit und Rosinen zugeben und verrühren.', '20 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ['Mit Walnüssen bestreuen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): gedünstete, pürierte Karotte mit wenig Quark und Zimt, ohne Rosinen und Nüsse. Kleinkind: ohne Erythrit, Rosinen gehackt, Walnüsse gemahlen.',
    baby: 1,
  },
  {
    id: 'kuerbis-pie-creme',
    n: 'Pumpkin-Pie-Creme im Glas',
    img: { wiki: 'Pumpkin pie', q: 'pumpkin pie cream parfait' },
    ck: 'Kürbis Creme Dessert',
    cu: 'amerikanisch', m: ['snack'], t: 25, d: 1, st: ['dessert', 'mealprep'],
    i: [['kuerbis', 120], ['magerquark', 150], ['skyr', 50], ['zimt', 2], ['ahornsirup', 6], ['vanille', 1], ['granola', 10]],
    s: [
      'Kürbis würfeln und in wenig Wasser 12–15 Min. weich kochen, abgießen und fein pürieren. Abkühlen lassen.',
      'Kürbispüree mit Quark, Skyr, Zimt, Vanille und Ahornsirup cremig rühren.',
      'In Gläser füllen und mind. 30 Min. kühlen.',
      'Vor dem Servieren mit Granola (glutenfrei: glutenfreies Granola) bestreuen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Kürbiswürfel in den Varoma-Behälter legen, 500 g Wasser in den Mixtopf geben, Varoma aufsetzen und garen.', '15 Min.', 'Varoma', 'Stufe 1', ''],
      ['Wasser weggießen, Kürbis in den Mixtopf geben und pürieren.', '15 Sek.', '', 'Stufe 7', ''],
      ['Abkühlen lassen. Kinderportion Kürbispüree entnehmen.', '', '', '', ''],
      ['Quark, Skyr, Zimt, Vanille und Ahornsirup zugeben und cremig rühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['In Gläser füllen, kühlen und mit Granola bestreuen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 6 Mon.): pures Kürbispüree mit einer Prise Zimt, ab 8 Mon. mit 1–2 EL Quark. Kleinkind: Creme ohne Sirup, statt Granola weiche Haferflocken.',
    baby: 2,
  },
  {
    id: 'spaghettieis-quark',
    n: 'Spaghettieis-Dessert aus Quark',
    img: { wiki: 'Spaghettieis', q: 'spaghettieis dessert' },
    ck: 'Spaghettieis Dessert',
    cu: 'deutsch', m: ['snack'], t: 15, d: 2, st: ['dessert', 'kinderliebling'],
    i: [['magerquark', 200], ['frischkaese_light', 20], ['erdbeeren', 120], ['vanille', 1], ['erythrit', 10], ['kokosraspeln', 3]],
    s: [
      'Quark, Frischkäse, Vanille und Erythrit glatt rühren und 15 Min. ins Gefrierfach stellen, damit die Masse fester wird.',
      'Erdbeeren fein pürieren.',
      'Die Quarkmasse portionsweise durch eine Spätzlepresse auf Teller drücken – sie sieht aus wie Spaghetti.',
      'Erdbeersauce darübergeben und mit Kokosraspeln als „Parmesan“ bestreuen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen. Spätzlepresse nötig.', steps: [
      ['Erdbeeren in den Mixtopf geben und pürieren, umfüllen.', '10 Sek.', '', 'Stufe 8', ''],
      ['Quark, Frischkäse, Vanille und Erythrit zugeben und cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Masse 15 Min. im Gefrierfach anziehen lassen.', '', '', '', ''],
      ['Durch die Spätzlepresse drücken, mit Erdbeersauce und Kokosraspeln anrichten.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): 1–2 EL Quark mit Erdbeerpüree, ohne Erythrit und Kokos. Kleinkind: das Spaghetti-Spiel lieben Kinder – Quark ohne Erythrit, mit Banane gesüßt.',
    baby: 1,
  },
  /* ---------- Skyr- & Joghurtcremes ---------- */
  {
    id: 'lemon-curd-skyr',
    n: 'Lemon-Curd-Skyr',
    img: { wiki: 'Fruit curd', q: 'lemon curd yogurt' },
    ck: 'Zitronencreme',
    cu: 'international', m: ['snack'], t: 15, d: 2, st: ['dessert'],
    i: [['skyr', 220], ['zitronensaft', 15], ['zitrone', 10], ['eiklar', 30], ['erythrit', 12], ['heidelbeeren', 40]],
    s: [
      'Für den leichten Curd Zitronensaft, Eiklar, abgeriebene Zitronenschale und Erythrit in einem kleinen Topf unter ständigem Rühren bei mittlerer Hitze 3–4 Min. eindicken (nicht kochen).',
      'Curd durch ein Sieb streichen und vollständig abkühlen lassen.',
      'Skyr cremig rühren und den Curd als Streifen unterziehen.',
      'In Gläser füllen und mit Heidelbeeren toppen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Zitronenschale und Erythrit pulverisieren.', '10 Sek.', '', 'Stufe 10', ''],
      ['Zitronensaft und Eiklar zugeben und zu Curd andicken.', '6 Min.', '80°C', 'Stufe 3', ''],
      ['Umfüllen und abkühlen lassen.', '', '', '', ''],
      ['Skyr im sauberen Mixtopf cremig rühren und den Curd unterziehen.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['In Gläser füllen und mit Heidelbeeren toppen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): wenig Naturjoghurt mit zerdrückten Heidelbeeren (Curd ist zu sauer). Kleinkind: Skyr mit wenig Curd, Erythrit durch Apfelmus ersetzen, Ei vollständig gegart.',
    baby: 1,
  },
  {
    id: 'key-lime-pie-glas',
    n: 'Key-Lime-Pie im Glas',
    img: { wiki: 'Key lime pie', q: 'key lime pie jar' },
    ck: 'Limettencreme im Glas',
    cu: 'amerikanisch', m: ['snack'], t: 10, d: 1, st: ['dessert'],
    i: [['skyr', 180], ['frischkaese_light', 25], ['limette', 30], ['erythrit', 10], ['haferflocken', 15], ['kokosraspeln', 3]],
    s: [
      'Haferflocken (glutenfrei: zertifizierte Haferflocken) mit Kokosraspeln in einer Pfanne ohne Fett 2–3 Min. rösten – das ist der Keksboden.',
      'Limettenschale fein abreiben, Saft auspressen.',
      'Skyr, Frischkäse, Limettensaft, Abrieb und Erythrit cremig rühren.',
      'Bröselboden ins Glas geben, Creme darauf füllen und 30 Min. kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Haferflocken und Kokosraspel rösten, umfüllen.', '4 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
      ['Limettenschale und Erythrit pulverisieren.', '10 Sek.', '', 'Stufe 10', ''],
      ['Skyr, Frischkäse und Limettensaft zugeben und cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Boden und Creme in Gläser schichten und kühlen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Haferbrösel in Joghurt eingeweicht, ohne Limette und Erythrit. Kleinkind: Creme mit wenig Limette und Banane statt Erythrit.',
    baby: 1,
  },
  {
    id: 'erdbeer-chia-schichtdessert',
    n: 'Erdbeer-Chia-Schichtdessert',
    img: { wiki: 'Chia seed', q: 'strawberry chia pudding parfait' },
    ck: 'Chia Pudding Erdbeere',
    cu: 'international', m: ['snack'], t: 15, d: 1, st: ['dessert', 'mealprep'],
    i: [['skyr', 180], ['erdbeeren', 120], ['chiasamen', 10], ['milch', 50], ['vanille', 1], ['erythrit', 6]],
    s: [
      'Erdbeeren pürieren, Chiasamen einrühren und 15 Min. (oder über Nacht) quellen lassen.',
      'Skyr mit Milch, Vanille und Erythrit cremig rühren.',
      'Abwechselnd Erdbeer-Chia und Skyrcreme in ein Glas schichten.',
      'Mit Erdbeerscheiben garnieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Erdbeeren pürieren.', '10 Sek.', '', 'Stufe 8', ''],
      ['Chiasamen zugeben, unterrühren und umfüllen, 15 Min. quellen lassen.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Skyr, Milch, Vanille und Erythrit cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['In Gläser schichten und garnieren.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Erdbeer-Chia-Püree mit gemahlenen Chiasamen und wenig Joghurt. Kleinkind: wie gezeigt ohne Erythrit, gut gequollen.',
    baby: 2,
  },

  /* ---------- Mousse ---------- */
  {
    id: 'mousse-au-chocolat-quark',
    n: 'Protein-Mousse au Chocolat',
    img: { wiki: 'Chocolate mousse', q: 'chocolate mousse glass' },
    ck: 'Mousse au Chocolat',
    cu: 'international', m: ['snack'], t: 15, d: 2, st: ['dessert'],
    i: [['magerquark', 150], ['eiklar', 60], ['kakao', 8], ['zartbitter', 10], ['erythrit', 12], ['vanille', 1]],
    s: [
      'Zartbitterschokolade über dem Wasserbad schmelzen und leicht abkühlen lassen.',
      'Quark mit Kakao, Erythrit, Vanille und der Schokolade glatt rühren.',
      'Eiklar (pasteurisiert) sehr steif schlagen und in zwei Portionen vorsichtig unterheben.',
      'In Gläser füllen und mind. 1 Std. kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser. Pasteurisiertes Eiklar verwenden.', steps: [
      ['Schokolade zerkleinern.', '5 Sek.', '', 'Stufe 8', ''],
      ['Schmelzen.', '2 Min.', '50°C', 'Stufe 2', ''],
      ['Quark, Kakao, Erythrit und Vanille zugeben und glatt rühren, umfüllen.', '20 Sek.', '', 'Stufe 4', ''],
      ['Mixtopf spülen, Rühraufsatz einsetzen, Eiklar steif schlagen.', '4 Min.', '', 'Stufe 3,5', ''],
      ['Eischnee mit dem Spatel unter die Schokocreme heben, in Gläser füllen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Nicht fürs Baby (Kakao, Schokolade, rohes Eiklar). Kleinkind: Schokoquark aus Quark, Banane und 1 TL Kakao, ohne Eischnee.',
    baby: 0,
  },
  {
    id: 'erdbeer-mousse-skyr',
    n: 'Erdbeer-Mousse',
    img: { wiki: 'Mousse', q: 'strawberry mousse glass' },
    ck: 'Erdbeermousse',
    cu: 'international', m: ['snack'], t: 20, d: 2, st: ['dessert', 'mealprep'],
    i: [['erdbeeren', 150], ['skyr', 150], ['magerquark', 50], ['gelatine', 3], ['erythrit', 10], ['sahne_spray_light', 6]],
    s: [
      'Erdbeeren fein pürieren. Gelatine in 3 EL kaltem Wasser 5 Min. quellen lassen.',
      'Gelatine bei kleiner Hitze auflösen (nicht kochen), 2 EL Püree einrühren, dann ins übrige Püree geben.',
      'Skyr, Quark und Erythrit cremig rühren, Erdbeerpüree zügig unterrühren.',
      'In Gläser füllen und mind. 2 Std. fest werden lassen. Mit einem Tupfer Sprühsahne servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser. Vegetarisch mit 1 g Agar-Agar statt Gelatine.', steps: [
      ['Erdbeeren pürieren.', '15 Sek.', '', 'Stufe 8', ''],
      ['Gequollene Gelatine zugeben und auflösen.', '2 Min.', '50°C', 'Stufe 2', ''],
      ['Skyr, Quark und Erythrit zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['In Gläser füllen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Erdbeerpüree mit wenig Joghurt – Mousse ohne Erythrit geht auch als Löffelspeise. Kleinkind: ohne Erythrit und Sahne, mit Banane gesüßt.',
    baby: 1,
  },
  {
    id: 'himbeer-mousse-gelatine',
    n: 'Himbeer-Joghurt-Mousse',
    img: { wiki: 'Mousse', q: 'raspberry mousse' },
    ck: 'Himbeermousse',
    cu: 'international', m: ['snack'], t: 20, d: 2, st: ['dessert', 'mealprep'],
    i: [['himbeeren', 120], ['skyr', 120], ['griech_joghurt', 60], ['gelatine', 3], ['eiklar', 40], ['erythrit', 12]],
    s: [
      'Himbeeren pürieren und durch ein Sieb streichen. Gelatine in kaltem Wasser quellen lassen.',
      'Gelatine leicht erwärmt auflösen und mit dem Himbeermark verrühren.',
      'Skyr, Joghurt und Erythrit unterrühren. Eiklar (pasteurisiert) steif schlagen und unterheben.',
      'In Gläser füllen und 2 Std. kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser. Pasteurisiertes Eiklar verwenden.', steps: [
      ['Rühraufsatz einsetzen, Eiklar steif schlagen, umfüllen.', '4 Min.', '', 'Stufe 3,5', ''],
      ['Himbeeren pürieren und durch ein Sieb streichen, zurück in den Mixtopf.', '15 Sek.', '', 'Stufe 8', ''],
      ['Gelatine zugeben und auflösen.', '2 Min.', '50°C', 'Stufe 2', ''],
      ['Skyr, Joghurt und Erythrit zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Eischnee mit dem Spatel unterheben, abfüllen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Baby: kein rohes Eiklar – stattdessen Himbeermark mit wenig Joghurt. Kleinkind: Himbeer-Joghurt ohne Eischnee und Erythrit.',
    baby: 1,
  },
  {
    id: 'zitronen-mousse',
    n: 'Zitronen-Mousse',
    img: { wiki: 'Mousse', q: 'lemon mousse dessert' },
    ck: 'Zitronenmousse',
    cu: 'international', m: ['snack'], t: 20, d: 2, st: ['dessert', 'mealprep'],
    i: [['magerquark', 150], ['skyr', 80], ['zitronensaft', 20], ['zitrone', 10], ['gelatine', 3], ['erythrit', 15], ['eiklar', 40]],
    s: [
      'Gelatine in kaltem Wasser quellen lassen. Zitronenschale abreiben.',
      'Gelatine mit dem Zitronensaft bei kleiner Hitze auflösen.',
      'Quark, Skyr, Abrieb und Erythrit cremig rühren, Zitronen-Gelatine zügig einrühren.',
      'Eiklar (pasteurisiert) steif schlagen und unterheben. 2 Std. kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser. Pasteurisiertes Eiklar verwenden.', steps: [
      ['Rühraufsatz einsetzen, Eiklar steif schlagen, umfüllen.', '4 Min.', '', 'Stufe 3,5', ''],
      ['Zitronenschale und Erythrit pulverisieren.', '10 Sek.', '', 'Stufe 10', ''],
      ['Zitronensaft und Gelatine zugeben und auflösen.', '2 Min.', '50°C', 'Stufe 2', ''],
      ['Quark und Skyr zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Eischnee unterheben, abfüllen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Baby: nicht geeignet (sauer, rohes Eiklar). Kleinkind: Quark mit etwas Zitronenabrieb und Apfelmus, ohne Eischnee.',
    baby: 0,
  },
  {
    id: 'mango-mousse',
    n: 'Mango-Mousse',
    img: { wiki: 'Mousse', q: 'mango mousse cup' },
    ck: 'Mangomousse',
    cu: 'international', m: ['snack'], t: 20, d: 2, st: ['dessert', 'mealprep'],
    i: [['mango', 120], ['skyr', 150], ['magerquark', 50], ['gelatine', 3], ['limette', 10], ['kokosraspeln', 3]],
    s: [
      'Mango pürieren. Gelatine in kaltem Wasser quellen lassen.',
      'Gelatine bei kleiner Hitze auflösen und mit dem Mangopüree verrühren.',
      'Skyr, Quark und Limettensaft unterrühren.',
      'In Gläser füllen, 2 Std. kühlen und mit gerösteten Kokosraspeln bestreuen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser. Vegetarisch mit 1 g Agar-Agar (kurz aufkochen).', steps: [
      ['Mango pürieren.', '15 Sek.', '', 'Stufe 8', ''],
      ['Gelatine zugeben und auflösen.', '2 Min.', '50°C', 'Stufe 2', ''],
      ['Skyr, Quark und Limettensaft zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Abfüllen, kühlen und mit Kokos bestreuen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 6 Mon.): pures Mangopüree, ab 8 Mon. mit wenig Skyr. Kleinkind: Mousse wie gezeigt, Kokos weglassen.',
    baby: 2,
  },

  {
    id: 'erdnussbutter-mousse',
    n: 'Erdnussbutter-Mousse',
    img: { q: 'peanut butter mousse cup' },
    ck: 'Erdnussbutter Creme',
    cu: 'amerikanisch', m: ['snack'], t: 10, d: 1, st: ['dessert'],
    i: [['magerquark', 180], ['erdnussbutter', 12], ['milch', 30], ['more_chunky', 4], ['banane', 40], ['erdnuesse', 4]],
    s: [
      'Erdnussmus mit Milch glatt rühren.',
      'Quark zugeben und mit dem Schneebesen 1 Min. luftig aufschlagen.',
      'Kinderportion abnehmen, Chunky Flavour (z. B. Peanut Butter) unterrühren.',
      'Mit Bananenscheiben und gehackten Erdnüssen servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Erdnüsse grob hacken, umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
      ['Rühraufsatz einsetzen. Quark, Erdnussmus und Milch luftig aufschlagen.', '1 Min.', '', 'Stufe 3,5', ''],
      ['Kinderportion entnehmen, Chunky Flavour unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Mit Banane und Erdnüssen anrichten.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 6 Mon.): dünn verrührtes Erdnussmus mit Banane (frühe Allergen-Einführung, keine ganzen Nüsse). Kleinkind: Creme ohne Chunky, Erdnüsse fein gemahlen.',
    baby: 1,
  },
  /* ---------- Tiramisu-Varianten ---------- */
  {
    id: 'kirsch-tiramisu',
    n: 'Kirsch-Tiramisu mit Schoko',
    img: { wiki: 'Tiramisu', q: 'cherry tiramisu' },
    ck: 'Kirsch Tiramisu',
    cu: 'italienisch', m: ['snack'], t: 15, d: 1, st: ['dessert', 'mealprep'],
    i: [['magerquark', 160], ['skyr', 60], ['sauerkirschen', 80], ['reiswaffeln', 8], ['kakao', 4], ['more_chunky', 4]],
    s: [
      'Sauerkirschen abtropfen lassen, 3 EL Saft auffangen.',
      'Quark, Skyr und Chunky Flavour (z. B. Choco Cherry oder Vanilla) cremig rühren.',
      'Reiswaffel zerbröseln und mit Kirschsaft tränken.',
      'Brösel, Kirschen und Creme schichten, dick mit Kakao bestäuben und 1 Std. kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Quark und Skyr cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Kinderportion entnehmen, Chunky Flavour unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Reiswaffelbrösel mit Kirschsaft tränken.', '', '', '', ''],
      ['Mit Kirschen schichten, mit Kakao bestäuben und kühlen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): pürierte Kirschen mit wenig Quark, ohne Kakao. Kleinkind: ohne Chunky und Kakao, Kirschen halbiert.',
    baby: 1,
  },
  /* ---------- Cheesecake-Cremes im Glas ---------- */
  {
    id: 'lemon-cheesecake-creme',
    n: 'Lemon-Cheesecake-Creme im Glas',
    img: { wiki: 'Cheesecake', q: 'lemon cheesecake jar' },
    ck: 'Zitronen Käsekuchen im Glas',
    cu: 'amerikanisch', m: ['snack'], t: 10, d: 1, st: ['dessert', 'mealprep'],
    i: [['magerquark', 180], ['frischkaese_light', 30], ['zitrone', 10], ['zitronensaft', 10], ['erythrit', 12], ['haferflocken', 15], ['heidelbeeren', 40]],
    s: [
      'Haferflocken (glutenfrei: zertifizierte) in einer Pfanne ohne Fett 2 Min. rösten.',
      'Quark, Frischkäse, Zitronenabrieb, -saft und Erythrit cremig rühren.',
      'Geröstete Flocken als Boden ins Glas geben, Creme darauf füllen.',
      'Mit Heidelbeeren toppen und 30 Min. kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Haferflocken rösten, umfüllen.', '4 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
      ['Zitronenschale und Erythrit pulverisieren.', '10 Sek.', '', 'Stufe 10', ''],
      ['Quark, Frischkäse und Zitronensaft zugeben und cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Schichten, mit Heidelbeeren toppen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Haferflocken in wenig Quark und Heidelbeerpüree eingeweicht. Kleinkind: Creme ohne Erythrit und mit wenig Zitrone.',
    baby: 1,
  },
  {
    id: 'strawberry-cheesecake-jar',
    n: 'Strawberry Cheesecake Jar',
    img: { wiki: 'Cheesecake', q: 'strawberry cheesecake jar' },
    ck: 'Erdbeer Käsekuchen im Glas',
    cu: 'amerikanisch', m: ['snack'], t: 10, d: 1, st: ['dessert', 'mealprep'],
    i: [['magerquark', 170], ['frischkaese_light', 30], ['erdbeeren', 120], ['more_chunky', 4], ['reiswaffeln', 10]],
    s: [
      'Reiswaffeln fein zerbröseln.',
      'Quark und Frischkäse cremig rühren, Kinderportion abnehmen, Chunky Flavour (z. B. Strawberry Cheesecake) unterrühren.',
      'Die Hälfte der Erdbeeren pürieren, den Rest würfeln.',
      'Brösel, Creme und Erdbeerpüree schichten, mit Erdbeerwürfeln toppen und kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Reiswaffeln zerbröseln, umfüllen.', '4 Sek.', '', 'Stufe 5', ''],
      ['Hälfte der Erdbeeren pürieren, umfüllen.', '10 Sek.', '', 'Stufe 8', ''],
      ['Quark und Frischkäse cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Kinderportion entnehmen, Chunky Flavour unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Schichten und kühlen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Erdbeerpüree mit wenig Quark, Reiswaffel als Fingerfood. Kleinkind: Creme ohne Chunky.',
    baby: 1,
  },
  {
    id: 'blaubeer-cheesecake-creme',
    n: 'Blaubeer-Cheesecake-Creme',
    img: { wiki: 'Cheesecake', q: 'blueberry cheesecake glass' },
    ck: 'Heidelbeer Käsekuchen im Glas',
    cu: 'amerikanisch', m: ['snack'], t: 15, d: 1, st: ['dessert', 'mealprep'],
    i: [['magerquark', 130], ['skyr', 50], ['frischkaese_light', 20], ['heidelbeeren', 100], ['esn_designer_whey', 12], ['granola', 10]],
    s: [
      'Die Hälfte der Heidelbeeren in einem Topf 3–4 Min. zu Kompott einkochen und abkühlen lassen.',
      'Quark, Skyr, Frischkäse und Whey (z. B. Blueberry Cheesecake) cremig rühren.',
      'Granola (glutenfrei: glutenfreies Granola) als Boden ins Glas geben, Creme und Kompott darauf schichten.',
      'Mit frischen Heidelbeeren toppen und kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Hälfte der Heidelbeeren einkochen, umfüllen.', '5 Min.', '100°C', 'Stufe 1', ''],
      ['Quark, Skyr und Frischkäse cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Kinderportion entnehmen, Whey unterrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['Mit Granola und Kompott schichten.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Heidelbeerkompott mit wenig Quark. Kleinkind: Creme ohne Whey, Granola durch weiche Haferflocken ersetzen.',
    baby: 0,
  },
  {
    id: 'pfirsich-kaesekuchen-creme',
    n: 'Pfirsich-Käsekuchencreme',
    img: { wiki: 'Cheesecake', q: 'peach cheesecake jar' },
    ck: 'Käsekuchen im Glas Pfirsich',
    cu: 'deutsch', m: ['snack'], t: 10, d: 1, st: ['dessert', 'mealprep'],
    i: [['magerquark', 180], ['frischkaese_light', 25], ['pfirsiche_dose', 100], ['vanille', 1], ['erythrit', 10], ['haferflocken', 15], ['zimt', 1]],
    s: [
      'Haferflocken (glutenfrei: zertifizierte) mit Zimt in der Pfanne ohne Fett 2 Min. rösten.',
      'Quark, Frischkäse, Vanille und Erythrit cremig rühren.',
      'Pfirsiche würfeln.',
      'Zimtflocken, Creme und Pfirsiche ins Glas schichten und 30 Min. kühlen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Haferflocken und Zimt rösten, umfüllen.', '4 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
      ['Quark, Frischkäse, Vanille und Erythrit cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Pfirsiche würfeln.', '', '', '', ''],
      ['Schichten und kühlen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 6 Mon.): weiche Pfirsichspalten als Fingerfood, ab 8 Mon. mit wenig Quark. Kleinkind: Creme ohne Erythrit.',
    baby: 2,
  },
  {
    id: 'huettenkaese-cheesecake-whip',
    n: 'Hüttenkäse-Cheesecake-Whip mit Beeren',
    img: { wiki: 'Cottage cheese', q: 'whipped cottage cheese berries' },
    ck: 'Hüttenkäse Creme',
    cu: 'amerikanisch', m: ['snack'], t: 5, d: 1, st: ['dessert'],
    i: [['huettenkaese', 200], ['zitronensaft', 5], ['vanille', 1], ['ahornsirup', 6], ['himbeeren', 60], ['heidelbeeren', 40]],
    s: [
      'Hüttenkäse mit Zitronensaft, Vanille und Ahornsirup in einen hohen Becher geben.',
      'Mit dem Stabmixer 1 Min. ganz glatt und luftig pürieren – schmeckt wie Cheesecake-Füllung.',
      'In eine Schale streichen.',
      'Mit Himbeeren und Heidelbeeren toppen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Hüttenkäse, Zitronensaft, Vanille und Ahornsirup fein pürieren.', '1 Min.', '', 'Stufe 8', ''],
      ['Mit dem Spatel nach unten schieben und nochmals pürieren.', '20 Sek.', '', 'Stufe 8', ''],
      ['In Schalen streichen.', '', '', '', ''],
      ['Mit Beeren toppen.', '', '', '', ''],
    ] },
    kid: 'Baby: Hüttenkäse ist recht salzig – höchstens 1 TL ab 10 Mon., dazu zerdrückte Beeren. Kleinkind: kleine Portion ohne Sirup.',
    baby: 1,
  },
  /* ---------- Trifle & Schichtdesserts ---------- */
  {
    id: 'beeren-trifle',
    n: 'Englisches Beeren-Trifle',
    img: { wiki: 'Trifle', q: 'berry trifle glass' },
    ck: 'Trifle',
    cu: 'international', m: ['snack'], t: 15, d: 1, st: ['dessert', 'mealprep'],
    i: [['ehrmann_pudding', 120], ['skyr', 100], ['beeren_tk', 100], ['reiswaffeln', 8], ['sahne_spray_light', 8]],
    s: [
      'Beeren in einem Topf 3 Min. erwärmen, bis sie Saft ziehen, abkühlen lassen.',
      'Reiswaffel zerbröseln und als Biskuit-Ersatz ins Glas geben, mit etwas Beerensaft tränken.',
      'Beeren, Vanille-Proteinpudding und Skyr schichten.',
      'Mit einem Tupfer Sprühsahne krönen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Beeren erwärmen, umfüllen und abkühlen lassen.', '4 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
      ['Skyr cremig rühren.', '15 Sek.', '', 'Stufe 3', ''],
      ['Reiswaffelbrösel, Beeren, Pudding und Skyr schichten.', '', '', '', ''],
      ['Mit Sprühsahne garnieren.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Beerenkompott mit wenig Joghurt, ohne Fertigpudding (Süßstoff). Kleinkind: Trifle mit Naturjoghurt statt Proteinpudding.',
    baby: 1,
  },
  {
    id: 'schwarzwaelder-kirsch-trifle',
    n: 'Schwarzwälder-Kirsch-Trifle',
    img: { wiki: 'Black Forest gateau', q: 'black forest trifle glass' },
    ck: 'Schwarzwälder Kirsch Dessert',
    cu: 'deutsch', m: ['snack'], t: 15, d: 1, st: ['dessert'],
    i: [['ehrmann_pudding', 150], ['magerquark', 100], ['sauerkirschen', 80], ['kakao', 4], ['zartbitter', 5], ['sahne_spray_light', 8]],
    s: [
      'Quark mit Kakao glatt rühren.',
      'Sauerkirschen abtropfen lassen.',
      'Schokopudding, Kakaoquark und Kirschen abwechselnd ins Glas schichten.',
      'Mit Sprühsahne und Schokoraspeln garnieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Schokolade raspeln, umfüllen.', '5 Sek.', '', 'Stufe 7', ''],
      ['Quark und Kakao cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Mit Schokopudding und Kirschen schichten.', '', '', '', ''],
      ['Mit Sprühsahne und Schokoraspeln garnieren.', '', '', '', ''],
    ] },
    kid: 'Nicht fürs Baby (Kakao, Fertigpudding). Kleinkind: Kirsch-Quark-Schichtdessert ohne Kakao und Proteinpudding.',
    baby: 0,
  },
  {
    id: 'apfel-crumble-trifle',
    n: 'Apple-Crumble-Trifle',
    img: { wiki: 'Apple crumble', q: 'apple crumble trifle glass' },
    ck: 'Apfel Crumble im Glas',
    cu: 'international', m: ['snack'], t: 15, d: 1, st: ['dessert', 'comfort'],
    i: [['magerquark', 180], ['apfelmus', 80], ['haferflocken', 15], ['mandeln', 5], ['zimt', 1], ['ahornsirup', 5], ['vanille', 1]],
    s: [
      'Haferflocken (glutenfrei: zertifizierte), gehackte Mandeln, Zimt und Ahornsirup in einer Pfanne 3 Min. knusprig rösten.',
      'Quark mit Vanille cremig rühren.',
      'Apfelmus, Vanillequark und Crumble abwechselnd ins Glas schichten.',
      'Mit Crumble abschließen und sofort servieren.',
    ],
    tm: { fit: 1, note: 'Crumble in der Pfanne rösten, damit er knusprig wird.', steps: [
      ['Mandeln grob hacken, umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
      ['Mit Haferflocken, Zimt und Sirup in der Pfanne knusprig rösten.', '', '', '', ''],
      ['Quark und Vanille cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Mit Apfelmus und Crumble schichten.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 6 Mon.): Apfelmus mit eingeweichten Haferflocken, ab 8 Mon. mit wenig Quark, ohne Mandelstücke und Sirup. Kleinkind: Crumble ohne Sirup, Mandeln gemahlen.',
    baby: 2,
  },
  {
    id: 'eton-mess-skyr',
    n: 'Eton Mess mit Skyr',
    img: { wiki: 'Eton mess', q: 'eton mess strawberries' },
    ck: 'Eton Mess',
    cu: 'international', m: ['snack'], t: 10, d: 1, st: ['dessert'],
    i: [['skyr', 200], ['erdbeeren', 150], ['sahne_spray_light', 10], ['puffreis', 8], ['vanille', 1], ['erythrit', 8]],
    s: [
      'Erdbeeren vierteln, ein Drittel mit Erythrit zerdrücken.',
      'Skyr mit Vanille cremig rühren und die Sprühsahne locker unterziehen.',
      'Erdbeeren, Erdbeermus und Puffreis (statt Baiser) grob unterheben – es darf „messy“ aussehen.',
      'Sofort in Gläsern servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen. Sahne erst zum Schluss unterziehen.', steps: [
      ['Ein Drittel der Erdbeeren mit Erythrit zerkleinern, umfüllen.', '4 Sek.', '', 'Stufe 5', ''],
      ['Skyr und Vanille cremig rühren.', '15 Sek.', '', 'Stufe 3', ''],
      ['Sprühsahne, Erdbeeren und Puffreis von Hand unterheben.', '', '', '', ''],
      ['Sofort servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): zerdrückte Erdbeeren mit wenig Joghurt. Kleinkind: ohne Erythrit und Sahne, Erdbeeren klein geschnitten.',
    baby: 1,
  },
  {
    id: 'rote-gruetze-vanillequark',
    n: 'Rote Grütze mit Vanillequark',
    img: { wiki: 'Rote Grütze', q: 'rote gruetze vanilla sauce' },
    ck: 'Rote Grütze',
    cu: 'deutsch', m: ['snack'], t: 20, d: 1, st: ['dessert', 'mealprep'],
    i: [['beeren_tk', 150], ['sauerkirschen', 50], ['agar', 1], ['erythrit', 10], ['magerquark', 180], ['milch', 40], ['vanille', 1]],
    s: [
      'Beeren und Sauerkirschen mit 50 ml Wasser und Erythrit aufkochen.',
      'Agar-Agar einrühren und 2 Min. sprudelnd kochen lassen, dann abkühlen und fest werden lassen.',
      'Quark mit Milch und Vanille zu einem cremigen Vanillequark rühren.',
      'Grütze in Schalen füllen und mit Vanillequark servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Beeren, Kirschen, 200 g Wasser und Erythrit aufkochen.', '7 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Agar-Agar zugeben und kochen.', '2 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Umfüllen und fest werden lassen. Mixtopf spülen.', '', '', '', ''],
      ['Quark, Milch und Vanille cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Grütze mit Vanillequark anrichten.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Grütze ohne Erythrit kochen, pürieren und mit wenig Quark mischen. Kleinkind: Grütze ohne Erythrit, mit etwas Apfelmus gesüßt.',
    baby: 2,
  },
  /* ---------- Pudding & Panna cotta ---------- */
  {
    id: 'herrencreme-protein',
    n: 'Herrencreme (leicht, alkoholfrei)',
    img: { q: 'vanilla pudding chocolate shavings glass' },
    ck: 'Herrencreme',
    cu: 'deutsch', m: ['snack'], t: 10, d: 1, st: ['dessert'],
    i: [['ehrmann_pudding', 200], ['skyr', 60], ['zartbitter', 8], ['sahne_spray_light', 8], ['vanille', 1]],
    s: [
      'Zartbitterschokolade fein raspeln.',
      'Vanille-Proteinpudding mit Skyr und Vanille glatt rühren.',
      'Die Sprühsahne und zwei Drittel der Schokoraspel locker unterheben.',
      'In Gläser füllen und mit den restlichen Raspeln bestreuen. (Klassisch mit einem Schuss Rum, hier ohne.)',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Schokolade raspeln, umfüllen.', '5 Sek.', '', 'Stufe 7', ''],
      ['Pudding, Skyr und Vanille verrühren.', '15 Sek.', '', 'Stufe 3', ''],
      ['Sprühsahne und Schokoraspel unterheben.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Abfüllen und bestreuen.', '', '', '', ''],
    ] },
    kid: 'Nicht fürs Baby (Fertigpudding mit Süßstoff, Schokolade). Kleinkind: Vanillejoghurt mit Banane und ein paar Schokoraspeln.',
    baby: 0,
  },
  {
    id: 'pudding-heisse-himbeeren',
    n: 'Vanillepudding mit heißen Himbeeren',
    img: { q: 'vanilla pudding hot raspberries' },
    ck: 'Vanillepudding mit heißen Himbeeren',
    cu: 'deutsch', m: ['snack'], t: 10, d: 1, st: ['dessert', 'comfort'],
    i: [['ehrmann_pudding', 200], ['magerquark', 60], ['himbeeren', 100], ['erythrit', 6], ['mandeln', 5]],
    s: [
      'Proteinpudding mit Quark glatt rühren und kalt stellen.',
      'Himbeeren mit Erythrit und 1 EL Wasser in einem Topf 2–3 Min. heiß werden lassen.',
      'Mandelblättchen in einer Pfanne ohne Fett goldbraun rösten.',
      'Kalten Pudding in Schalen füllen, heiße Himbeeren darübergeben und mit Mandeln bestreuen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Mandeln rösten, umfüllen.', '4 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
      ['Pudding und Quark verrühren, umfüllen und kühlen.', '15 Sek.', '', 'Stufe 3', ''],
      ['Himbeeren, Erythrit und 20 g Wasser erhitzen.', '4 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
      ['Heiße Himbeeren über den kalten Pudding geben.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): warme, zerdrückte Himbeeren mit wenig Joghurt, ohne Fertigpudding. Kleinkind: Quark-Joghurt-Creme statt Proteinpudding, Himbeeren ohne Erythrit.',
    baby: 1,
  },

  {
    id: 'protein-panna-cotta',
    n: 'Protein-Panna-Cotta mit Erdbeersauce',
    img: { wiki: 'Panna cotta', q: 'panna cotta strawberry sauce' },
    ck: 'Panna Cotta',
    cu: 'italienisch', m: ['snack'], t: 20, d: 2, st: ['dessert', 'mealprep'],
    i: [['milch', 150], ['skyr', 100], ['more_total_sahne', 15], ['gelatine', 4], ['vanille', 1], ['erdbeeren', 80], ['erythrit', 6]],
    s: [
      'Gelatine in 3 EL kaltem Wasser quellen lassen. Milch mit Vanille und Erythrit erwärmen (nicht kochen).',
      'Topf vom Herd nehmen, Gelatine darin auflösen und auf ca. 40 °C abkühlen lassen.',
      'More „Sahne“ und Skyr glatt einrühren, in Förmchen oder Gläser füllen und mind. 4 Std. kühlen.',
      'Erdbeeren pürieren und vor dem Servieren über die Panna cotta geben.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Erdbeeren pürieren, umfüllen.', '10 Sek.', '', 'Stufe 8', ''],
      ['Milch, Vanille und Erythrit erwärmen.', '4 Min.', '80°C', 'Stufe 2', ''],
      ['Gequollene Gelatine zugeben und auflösen.', '1 Min.', '60°C', 'Stufe 2', ''],
      ['Auf 40°C abkühlen lassen, Proteinpulver und Skyr zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Abfüllen, kühlen und mit Erdbeersauce servieren.', '', '', '', ''],
    ] },
    kid: 'Kinderportion vor dem Proteinpulver abnehmen: Milch-Gelatine-Creme mit Joghurt und Erdbeerpüree, ohne Erythrit. Für Babys unter 12 Mon. nur wenig Kuhmilch.',
    baby: 1,
  },
  {
    id: 'kokos-panna-cotta-mango',
    n: 'Kokos-Panna-Cotta mit Mango',
    img: { wiki: 'Panna cotta', q: 'coconut panna cotta mango' },
    ck: 'Kokos Panna Cotta',
    cu: 'international', m: ['snack'], t: 20, d: 2, st: ['dessert', 'mealprep'],
    i: [['kokosmilch_light', 80], ['skyr', 150], ['gelatine', 4], ['erythrit', 8], ['mango', 80], ['limette', 5]],
    s: [
      'Gelatine in kaltem Wasser quellen lassen. Kokosmilch mit Erythrit erwärmen.',
      'Vom Herd nehmen, Gelatine darin auflösen und leicht abkühlen lassen.',
      'Skyr glatt einrühren, in Gläser füllen und 4 Std. kühlen.',
      'Mango mit Limettensaft pürieren und als Spiegel auf die Panna cotta geben.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser. Vegan/vegetarisch mit 1 g Agar-Agar (2 Min. kochen) und Kokosjoghurt.', steps: [
      ['Mango und Limettensaft pürieren, umfüllen.', '10 Sek.', '', 'Stufe 8', ''],
      ['Kokosmilch und Erythrit erwärmen.', '3 Min.', '80°C', 'Stufe 2', ''],
      ['Gelatine zugeben und auflösen.', '1 Min.', '60°C', 'Stufe 2', ''],
      ['Leicht abkühlen lassen, Skyr zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Abfüllen, kühlen und mit Mangopüree servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 6 Mon.): Mangopüree pur, ab 8 Mon. mit wenig Skyr. Kleinkind: Panna cotta ohne Erythrit, mit Mango gesüßt.',
    baby: 1,
  },
  /* ---------- Bowls ---------- */

  {
    id: 'himbeer-kokos-quark-bowl',
    n: 'Himbeer-Kokos-Quark-Bowl',
    img: { q: 'raspberry coconut yogurt bowl' },
    ck: 'Himbeer Quark',
    cu: 'international', m: ['snack'], t: 5, d: 1, st: ['dessert'],
    i: [['magerquark', 200], ['kokosmilch_light', 30], ['himbeeren', 100], ['kokosraspeln', 5], ['more_chunky', 4]],
    s: [
      'Quark mit Kokosmilch cremig rühren.',
      'Kinderportion abnehmen, Chunky Flavour (z. B. Coconut oder White Chocolate) unterrühren.',
      'Die Hälfte der Himbeeren zerdrücken und marmorierend unterziehen.',
      'Mit restlichen Himbeeren und gerösteten Kokosraspeln toppen.',
    ],
    tm: { fit: 0, note: 'Thermomix nur zum Rösten und Cremigrühren.', steps: [
      ['Kokosraspel rösten, umfüllen.', '3 Min.', '120°C', 'Stufe 1', ''],
      ['Quark und Kokosmilch cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Kinderportion entnehmen, Chunky Flavour unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Mit Himbeeren und Kokos anrichten.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): zerdrückte Himbeeren mit wenig Quark. Kleinkind: ohne Chunky, Kokos sparsam.',
    baby: 1,
  },
]);
