// Gebackene und gekühlte Protein-Desserts & süße Snacks – kalorienarm, proteinreich, alle glutenfrei umsetzbar.
// Proteinpulver, Chunky Flavour und Zerup sind nicht für Babys/Kleinkinder: Kinderportion immer ohne Pulver und ohne Süßstoff.
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  /* ---------- Käsekuchen ---------- */
  {
    id: 'kaesekuchen-ohne-boden-vanille',
    n: 'Käsekuchen ohne Boden (Protein, Vanille)',
    ck: 'Käsekuchen ohne Boden',
    img: { wiki: 'Cheesecake', q: 'german quark cheesecake crustless' },
    cu: 'deutsch', m: ['snack'], t: 75, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['magerquark', 125], ['ei', 30], ['more_pudding', 10], ['speisestaerke', 4], ['milch', 20], ['erythrit', 15], ['zitronensaft', 5], ['vanille', 1]],
    s: [
      'Backofen auf 170 °C Ober-/Unterhitze vorheizen, eine Springform (24 cm) mit Backpapier auslegen. Die Mengen ergeben 8 Stücke.',
      'Quark, Eier, Milch, Erythrit, Zitronensaft und Vanille glatt rühren.',
      'Proteinpudding-Pulver und Speisestärke darübersieben und kurz unterrühren, bis keine Klümpchen mehr da sind.',
      'Masse in die Form füllen und 50–55 Min. backen, bis die Mitte nur noch leicht wackelt.',
      'Im ausgeschalteten Ofen bei leicht geöffneter Tür 15 Min. ruhen lassen (reißt so weniger), dann mind. 3 Std. kühlen.',
    ],
    tm: { fit: 1, note: 'Teig für 8 Stücke im Thermomix, Backen im Ofen.', steps: [
      ['Quark, Eier, Milch, Erythrit, Zitronensaft und Vanille in den Mixtopf geben und verrühren.', '30 Sek.', '', 'Stufe 4', ''],
      ['Proteinpudding-Pulver und Speisestärke zugeben und glatt rühren, mit dem Spatel nachschieben.', '20 Sek.', '', 'Stufe 4', ''],
      ['In die Springform füllen und bei 170 °C 50–55 Min. im Ofen backen.', '', '', '', ''],
      ['Im Ofen auskühlen lassen und mind. 3 Std. kühlen.', '', '', '', ''],
    ] },
    kid: 'Kinderkuchen: eine kleine Form ohne Proteinpulver (stattdessen 1 EL mehr Speisestärke) und ohne Erythrit, mit reifer zerdrückter Banane süßen. Baby (ab 8 Mon.): kleine, weiche Stücke als Fingerfood, Ei vollständig durchgebacken; Quark nur in kleinen Mengen.',
    baby: 1,
  },
  {
    id: 'schoko-kaesekuchen-ohne-boden',
    n: 'Schoko-Käsekuchen ohne Boden',
    ck: 'Schoko Käsekuchen',
    img: { wiki: 'Cheesecake', q: 'chocolate cheesecake slice' },
    cu: 'deutsch', m: ['snack'], t: 75, d: 1, st: ['dessert', 'mealprep'],
    i: [['magerquark', 120], ['ei', 30], ['esn_designer_whey', 10], ['kakao', 6], ['speisestaerke', 4], ['milch', 20], ['erythrit', 15], ['zartbitter', 5]],
    s: [
      'Ofen auf 170 °C Ober-/Unterhitze vorheizen, Springform (24 cm) mit Backpapier auslegen. Ergibt 8 Stücke.',
      'Quark, Eier, Milch und Erythrit cremig rühren.',
      'Whey (Schoko), Kakao und Speisestärke einsieben und glatt rühren.',
      'Schokolade fein hacken, die Hälfte unterheben, Masse in die Form füllen und den Rest darüberstreuen.',
      '50 Min. backen, im Ofen bei offener Tür 15 Min. ruhen lassen und mind. 3 Std. kühlen.',
    ],
    tm: { fit: 1, note: 'Für 8 Stücke. Backen im Ofen.', steps: [
      ['Schokolade in den Mixtopf geben und hacken, umfüllen.', '4 Sek.', '', 'Stufe 7', ''],
      ['Quark, Eier, Milch und Erythrit verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Whey, Kakao und Speisestärke zugeben und glatt rühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Die Hälfte der Schokolade unterheben.', '5 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['In die Form füllen, Rest Schokolade aufstreuen und bei 170 °C 50 Min. backen, dann kühlen.', '', '', '', ''],
    ] },
    kid: 'Kleinkind: kleine Portion aus Quark, Ei, Kakao und Banane ohne Whey und ohne Erythrit im Muffinförmchen mitbacken (ca. 25 Min.). Für Babys wegen Kakao/Schokolade eher nicht – lieber den Vanille-Käsekuchen ohne Pulver.',
    baby: 0,
  },
  {
    id: 'kirsch-kaesekuchen-ohne-boden',
    n: 'Kirsch-Käsekuchen ohne Boden',
    ck: 'Kirschkäsekuchen',
    img: { wiki: 'Cheesecake', q: 'cherry cheesecake slice' },
    cu: 'deutsch', m: ['snack'], t: 80, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['magerquark', 120], ['ei', 30], ['more_pudding', 8], ['speisestaerke', 5], ['sauerkirschen', 50], ['erythrit', 15], ['zitronensaft', 5], ['vanille', 1]],
    s: [
      'Ofen auf 170 °C vorheizen, Springform (24 cm) auslegen. Ergibt 8 Stücke.',
      'Sauerkirschen gut abtropfen lassen und mit 1 TL der Speisestärke mischen (so sinken sie nicht ab).',
      'Quark, Eier, Erythrit, Zitronensaft, Vanille, Pudding-Pulver und restliche Stärke glatt rühren.',
      'Masse in die Form füllen, Kirschen gleichmäßig darauf verteilen und leicht eindrücken.',
      '55 Min. backen, im Ofen auskühlen lassen und mind. 3 Std. kühlen.',
    ],
    tm: { fit: 1, note: 'Für 8 Stücke. Backen im Ofen.', steps: [
      ['Kirschen abtropfen und mit etwas Stärke mischen.', '', '', '', ''],
      ['Quark, Eier, Erythrit, Zitronensaft, Vanille, Pudding-Pulver und restliche Stärke in den Mixtopf geben und glatt rühren.', '40 Sek.', '', 'Stufe 4', ''],
      ['In die Form füllen und Kirschen darauf verteilen.', '', '', '', ''],
      ['Bei 170 °C 55 Min. backen, auskühlen lassen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Kleinkind-Portion in einer kleinen Form ohne Proteinpudding-Pulver und ohne Erythrit (dafür mehr Kirschen und etwas Banane). Baby (ab 8 Mon.): weiche Stücke ohne Kirschhaut-Stücke, Kirschen vorher zerdrücken; Ei durchgebacken.',
    baby: 1,
  },
  {
    id: 'pfirsich-schmand-kaesekuchen-ohne-boden',
    n: 'Pfirsich-Schmand-Käsekuchen ohne Boden',
    ck: 'Schmandkuchen Pfirsich',
    img: { wiki: 'Cheesecake', q: 'peach cheesecake' },
    cu: 'deutsch', m: ['snack'], t: 75, d: 1, st: ['dessert', 'mealprep'],
    i: [['skyr', 100], ['magerquark', 50], ['ei', 25], ['schmand_light', 20], ['pfirsiche_dose', 50], ['speisestaerke', 6], ['erythrit', 15], ['vanille', 1]],
    s: [
      'Ofen auf 170 °C vorheizen, Springform (24 cm) auslegen. Ergibt 8 Stücke.',
      'Pfirsiche gut abtropfen lassen und in Spalten schneiden.',
      'Skyr, Quark, Eier, Schmand, Erythrit, Vanille und Speisestärke glatt rühren.',
      'Masse in die Form füllen, Pfirsichspalten fächerartig darauflegen.',
      '50–55 Min. backen, im Ofen auskühlen lassen und mind. 3 Std. kalt stellen.',
    ],
    tm: { fit: 1, note: 'Für 8 Stücke. Backen im Ofen.', steps: [
      ['Skyr, Quark, Eier, Schmand, Erythrit, Vanille und Stärke in den Mixtopf geben und glatt rühren.', '40 Sek.', '', 'Stufe 4', ''],
      ['Masse in die Springform füllen.', '', '', '', ''],
      ['Pfirsichspalten auflegen.', '', '', '', ''],
      ['Bei 170 °C 50–55 Min. backen, dann auskühlen lassen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Für Kinder ohne Erythrit backen und mit etwas pürierten Pfirsichen süßen. Baby (ab 8 Mon.): weiche Pfirsichstücke und kleine Kuchenstücke als Fingerfood, Ei durchgebacken, Milchprodukte in kleinen Mengen.',
    baby: 2,
  },
  {
    id: 'cheesecake-mandelboden-light',
    n: 'New York Cheesecake light mit Mandelboden',
    ck: 'New York Cheesecake',
    img: { wiki: 'Cheesecake', q: 'new york cheesecake slice' },
    cu: 'amerikanisch', m: ['snack'], t: 90, d: 2, st: ['dessert', 'mealprep'],
    i: [['mandelmehl', 12], ['butter', 4], ['erythrit', 12], ['frischkaese_light', 30], ['magerquark', 100], ['ei', 25], ['esn_designer_whey', 8], ['speisestaerke', 3], ['zitronensaft', 5], ['vanille', 1]],
    s: [
      'Ofen auf 160 °C Ober-/Unterhitze vorheizen. Ergibt 8 Stücke aus einer 20-cm-Springform.',
      'Mandelmehl, geschmolzene Butter und ein Drittel des Erythrits verkneten, als Boden in die Form drücken und 10 Min. vorbacken.',
      'Frischkäse, Quark, Eier, restliches Erythrit, Whey (Vanille), Stärke, Zitronensaft und Vanille nur kurz glatt rühren (nicht schaumig schlagen).',
      'Creme auf den Boden geben, Form auf ein Blech mit etwas heißem Wasser stellen und 55 Min. backen.',
      'Im ausgeschalteten Ofen 30 Min. ruhen lassen, dann über Nacht kühlen.',
    ],
    tm: { fit: 1, note: 'Für 8 Stücke. Boden und Creme im Thermomix, Backen im Ofen.', steps: [
      ['Mandelmehl, Butter und ein Drittel Erythrit verkneten.', '20 Sek.', '', 'Stufe 4', ''],
      ['Als Boden in die Form drücken und bei 160 °C 10 Min. vorbacken.', '', '', '', ''],
      ['Frischkäse, Quark, Eier, restliches Erythrit, Whey, Stärke, Zitronensaft und Vanille glatt rühren.', '30 Sek.', '', 'Stufe 3', ''],
      ['Auf den Boden geben und im Wasserbad 55 Min. backen, über Nacht kühlen.', '', '', '', ''],
    ] },
    kid: 'Kinderportion als Mini-Cheesecake im Muffinförmchen ohne Whey und ohne Erythrit (mit Banane süßen). Mandelboden ist fein gemahlen – für Babys (ab 8 Mon.) eine gute frühe Nuss-Einführung in kleinen Mengen.',
    baby: 1,
  },
  {
    id: 'kaesekuchen-muffins-himbeere',
    n: 'Käsekuchen-Muffins mit Himbeeren',
    ck: 'Käsekuchen Muffins',
    img: { q: 'cheesecake muffins raspberries' },
    cu: 'deutsch', m: ['snack'], t: 35, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['magerquark', 100], ['ei', 25], ['more_pudding', 10], ['speisestaerke', 4], ['himbeeren', 40], ['erythrit', 10], ['zitronensaft', 5]],
    s: [
      'Ofen auf 170 °C vorheizen, ein Muffinblech mit Silikonförmchen bestücken. Eine Portion = 2 Muffins.',
      'Quark, Eier, Erythrit, Zitronensaft, Pudding-Pulver und Stärke glatt rühren.',
      'Masse zu zwei Dritteln in die Förmchen füllen, je 2–3 Himbeeren hineindrücken.',
      '22–25 Min. backen, bis die Oberfläche fest ist.',
      'In den Förmchen abkühlen lassen (sie fallen etwas zusammen) und gekühlt servieren.',
    ],
    tm: { fit: 1, note: 'Für 8 Muffins (4 Portionen).', steps: [
      ['Quark, Eier, Erythrit, Zitronensaft, Pudding-Pulver und Stärke in den Mixtopf geben und glatt rühren.', '30 Sek.', '', 'Stufe 4', ''],
      ['In Förmchen füllen und Himbeeren hineindrücken.', '', '', '', ''],
      ['Bei 170 °C 22–25 Min. backen.', '', '', '', ''],
      ['Abkühlen lassen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Kinder-Muffins ohne Pudding-Pulver und ohne Erythrit (1 EL Stärke mehr, ½ zerdrückte Banane). Baby (ab 8 Mon.): halbierter Muffin als Fingerfood, Himbeeren sind weich genug.',
    baby: 1,
  },
  /* ---------- Muffins ---------- */
  {
    id: 'schoko-protein-muffins',
    n: 'Saftige Schoko-Protein-Muffins',
    ck: 'Schokomuffins',
    img: { wiki: 'Muffin', q: 'chocolate muffins' },
    cu: 'amerikanisch', m: ['snack'], t: 35, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['banane', 40], ['haferflocken', 20], ['esn_designer_whey', 15], ['kakao', 6], ['ei', 30], ['skyr', 50], ['erythrit', 8], ['backpulver', 3], ['zartbitter', 4]],
    s: [
      'Ofen auf 180 °C vorheizen. Eine Portion = 2 Muffins.',
      'Haferflocken (glutenfrei: zertifizierte) fein mahlen, Banane zerdrücken.',
      'Banane, Eier und Skyr verrühren, Hafermehl, Whey (Schoko), Kakao, Erythrit und Backpulver unterrühren.',
      'Schokolade hacken, unterheben und den Teig in Förmchen füllen.',
      '18–20 Min. backen – die Mitte darf noch leicht saftig sein.',
    ],
    tm: { fit: 1, note: 'Für 8 Muffins (4 Portionen).', steps: [
      ['Haferflocken und Schokolade in den Mixtopf geben und zerkleinern.', '8 Sek.', '', 'Stufe 8', ''],
      ['Banane, Eier, Skyr, Whey, Kakao, Erythrit und Backpulver zugeben und verrühren.', '25 Sek.', '', 'Stufe 4', ''],
      ['Teig in Förmchen füllen.', '', '', '', ''],
      ['Bei 180 °C 18–20 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Kleinkind: Teig-Portion vorher abnehmen und ohne Whey/Erythrit backen (mehr Banane). Kakao in Maßen. Baby: lieber Bananen-Hafer-Muffin ohne Kakao und ohne Schokolade.',
    baby: 0,
  },
  {
    id: 'apfel-zimt-protein-muffins',
    n: 'Apfel-Zimt-Protein-Muffins',
    ck: 'Apfelmuffins',
    img: { wiki: 'Muffin', q: 'apple cinnamon muffins' },
    cu: 'deutsch', m: ['snack'], t: 40, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['apfel', 50], ['haferflocken', 20], ['esn_designer_whey', 15], ['ei', 30], ['magerquark', 50], ['mandeln', 5], ['zimt', 1.5], ['erythrit', 8], ['backpulver', 3]],
    s: [
      'Ofen auf 180 °C vorheizen. Eine Portion = 2 Muffins.',
      'Apfel fein raspeln, Mandeln grob hacken, Haferflocken (glutenfrei: zertifizierte) mahlen.',
      'Eier, Quark, Erythrit und Zimt verrühren, Hafermehl, Whey (Vanille) und Backpulver unterrühren.',
      'Apfelraspel unterheben, in Förmchen füllen und mit gehackten Mandeln bestreuen.',
      '22–25 Min. backen und abkühlen lassen.',
    ],
    tm: { fit: 1, note: 'Für 8 Muffins (4 Portionen).', steps: [
      ['Mandeln hacken, umfüllen.', '3 Sek.', '', 'Stufe 6', ''],
      ['Haferflocken mahlen, Apfel in Stücken zugeben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
      ['Eier, Quark, Whey, Erythrit, Zimt und Backpulver zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['In Förmchen füllen, mit Mandeln bestreuen und bei 180 °C 22–25 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Kinder-Muffins ohne Whey und Erythrit (dafür 1 EL Apfelmus mehr), Mandeln für die Kleinen nur gemahlen untermischen statt obendrauf. Baby (ab 8 Mon.): weiches Fingerfood.',
    baby: 1,
  },
  {
    id: 'rueblikuchen-protein-muffins',
    n: 'Rüblikuchen-Protein-Muffins',
    ck: 'Rüblitorte Muffins',
    img: { wiki: 'Carrot cake', q: 'carrot cake muffins' },
    cu: 'deutsch', m: ['snack'], t: 40, d: 1, st: ['dessert', 'mealprep'],
    i: [['karotte', 40], ['mandelmehl', 20], ['haferflocken', 15], ['esn_designer_whey', 10], ['ei', 30], ['skyr', 50], ['walnuesse', 5], ['zimt', 1], ['erythrit', 10], ['backpulver', 3]],
    s: [
      'Ofen auf 180 °C vorheizen. Eine Portion = 2 Muffins.',
      'Karotten fein raspeln, Walnüsse hacken, Haferflocken (glutenfrei: zertifizierte) mahlen.',
      'Eier, die Hälfte des Skyrs und Erythrit verrühren, Mandelmehl, Hafermehl, Whey, Zimt und Backpulver unterrühren, dann Karotten und Nüsse unterheben.',
      'In Förmchen füllen und 22–25 Min. backen.',
      'Abgekühlt mit dem restlichen Skyr (mit etwas Erythrit verrührt) als Frosting toppen.',
    ],
    tm: { fit: 1, note: 'Für 8 Muffins (4 Portionen).', steps: [
      ['Walnüsse hacken, umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
      ['Haferflocken mahlen, Karotten in Stücken zugeben und zerkleinern.', '6 Sek.', '', 'Stufe 5', ''],
      ['Eier, halben Skyr, Mandelmehl, Whey, Zimt, Erythrit und Backpulver zugeben und verrühren, Nüsse unterheben.', '20 Sek.', '', 'Stufe 4', 'Linkslauf'],
      ['In Förmchen bei 180 °C 22–25 Min. backen, mit Skyr-Frosting toppen.', '', '', '', ''],
    ] },
    kid: 'Kinderportion ohne Whey und Erythrit backen, Walnüsse nur gemahlen. Baby (ab 8 Mon.): Muffin ohne Frosting als weiches Fingerfood – Karotte und Mandel sind ideal.',
    baby: 1,
  },
  /* ---------- Brownies & Blondies ---------- */
  {
    id: 'black-bean-protein-brownies',
    n: 'Black Bean Brownies (Protein)',
    ck: 'Bohnen Brownies',
    img: { wiki: 'Chocolate brownie', q: 'black bean brownies' },
    cu: 'amerikanisch', m: ['snack'], t: 35, d: 1, st: ['dessert', 'mealprep'],
    i: [['schwarze_bohnen', 60], ['ei', 20], ['kakao', 8], ['esn_designer_whey', 12], ['erdnussbutter', 6], ['erythrit', 12], ['zartbitter', 5], ['backpulver', 2]],
    s: [
      'Ofen auf 180 °C vorheizen, eine 20×20-cm-Form mit Backpapier auslegen. Ergibt 9 Stücke (Mengen pro Stück).',
      'Bohnen gründlich abspülen und abtropfen lassen.',
      'Bohnen, Eier, Erdnussmus und Erythrit sehr fein pürieren, Kakao, Whey (Schoko) und Backpulver unterrühren.',
      'Gehackte Schokolade unterheben, Teig in die Form streichen.',
      '20–22 Min. backen – die Mitte bleibt fudgy. Vollständig auskühlen lassen und in Stücke schneiden.',
    ],
    tm: { fit: 1, note: 'Für 9 Stücke.', steps: [
      ['Schokolade hacken, umfüllen.', '4 Sek.', '', 'Stufe 7', ''],
      ['Bohnen, Eier, Erdnussmus und Erythrit pürieren, mit dem Spatel nachschieben.', '30 Sek.', '', 'Stufe 8', ''],
      ['Kakao, Whey und Backpulver zugeben und verrühren, Schokolade unterheben.', '15 Sek.', '', 'Stufe 4', 'Linkslauf'],
      ['In die Form streichen und bei 180 °C 20–22 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Kleinkind: Teig-Portion vor dem Whey abnehmen und mit Banane statt Erythrit süßen, ohne Schokostücke. Erdnussmus ist ein gutes frühes Allergen. Für Babys wegen Kakao und Bohnen-Menge eher nicht.',
    baby: 0,
  },
  {
    id: 'quark-protein-brownies',
    n: 'Quark-Protein-Brownies',
    ck: 'Protein Brownies',
    img: { wiki: 'Chocolate brownie', q: 'chocolate brownies squares' },
    cu: 'amerikanisch', m: ['snack'], t: 35, d: 1, st: ['dessert', 'mealprep'],
    i: [['magerquark', 80], ['ei', 25], ['mandelmehl', 12], ['kakao', 8], ['esn_designer_whey', 10], ['erythrit', 12], ['zartbitter', 6], ['backpulver', 2]],
    s: [
      'Ofen auf 175 °C vorheizen, 20×20-cm-Form auslegen. Ergibt 9 Stücke.',
      'Schokolade hacken, die Hälfte über dem Wasserbad schmelzen.',
      'Quark, Eier und Erythrit verrühren, geschmolzene Schokolade einrühren.',
      'Mandelmehl, Kakao, Whey (Schoko) und Backpulver unterrühren, restliche Schokostücke unterheben.',
      'In die Form streichen und 20 Min. backen, auskühlen lassen und schneiden.',
    ],
    tm: { fit: 1, note: 'Für 9 Stücke.', steps: [
      ['Schokolade hacken, die Hälfte umfüllen.', '4 Sek.', '', 'Stufe 7', ''],
      ['Restliche Schokolade schmelzen.', '2 Min.', '50°C', 'Stufe 2', ''],
      ['Quark, Eier, Erythrit, Mandelmehl, Kakao, Whey und Backpulver zugeben und verrühren.', '30 Sek.', '', 'Stufe 4', ''],
      ['Schokostücke unterheben, in die Form streichen und bei 175 °C 20 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Kleinkind: Mini-Brownie aus Quark, Ei, Mandelmehl, Banane und wenig Kakao ohne Whey und Erythrit backen. Für Babys wegen Schokolade nicht geeignet.',
    baby: 0,
  },
  {
    id: 'suesskartoffel-brownies',
    n: 'Süßkartoffel-Brownies',
    ck: 'Süßkartoffel Brownies',
    img: { wiki: 'Chocolate brownie', q: 'sweet potato brownies' },
    cu: 'amerikanisch', m: ['snack'], t: 50, d: 1, st: ['dessert', 'mealprep'],
    i: [['suesskartoffel', 70], ['ei', 25], ['mandelmehl', 10], ['kakao', 8], ['esn_designer_whey', 12], ['mandelmus', 5], ['erythrit', 10], ['backpulver', 2]],
    s: [
      'Süßkartoffel schälen, würfeln und 15 Min. dämpfen, bis sie weich ist; fein zerdrücken. Ergibt 9 Stücke.',
      'Ofen auf 180 °C vorheizen, 20×20-cm-Form auslegen.',
      'Süßkartoffelpüree mit Eiern, Mandelmus und Erythrit glatt rühren.',
      'Mandelmehl, Kakao, Whey (Schoko) und Backpulver unterrühren, Teig in die Form streichen.',
      '22–25 Min. backen, vollständig auskühlen lassen (dann werden sie fudgy) und schneiden.',
    ],
    tm: { fit: 1, note: 'Für 9 Stücke. Süßkartoffel im Varoma garen.', steps: [
      ['500 g Wasser einfüllen, Süßkartoffelwürfel in den Varoma geben und garen.', '18 Min.', 'Varoma', 'Stufe 1', ''],
      ['Wasser abgießen, Süßkartoffel in den Mixtopf geben und pürieren.', '15 Sek.', '', 'Stufe 6', ''],
      ['Eier, Mandelmus, Erythrit, Mandelmehl, Kakao, Whey und Backpulver zugeben und verrühren.', '25 Sek.', '', 'Stufe 4', ''],
      ['In die Form streichen und bei 180 °C 22–25 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 6 Mon.): gedämpfte Süßkartoffel vorher abnehmen und als Brei oder Sticks geben. Kleinkind: Brownie-Teig ohne Whey/Erythrit mit Banane – Kakao in kleinen Mengen.',
    baby: 1,
  },
  {
    id: 'kichererbsen-protein-blondies',
    n: 'Kichererbsen-Blondies mit Schokostücken',
    ck: 'Kichererbsen Blondies',
    img: { wiki: 'Blondie (confection)', q: 'chickpea blondies' },
    cu: 'amerikanisch', m: ['snack'], t: 35, d: 1, st: ['dessert', 'mealprep'],
    i: [['kichererbsen', 50], ['erdnussbutter', 10], ['esn_designer_whey', 15], ['ei', 15], ['erythrit', 10], ['backpulver', 2], ['zartbitter', 6], ['vanille', 1]],
    s: [
      'Ofen auf 180 °C vorheizen, 20×20-cm-Form auslegen. Ergibt 9 Stücke.',
      'Kichererbsen abspülen und gut trockentupfen.',
      'Kichererbsen, Erdnussmus, Ei, Erythrit und Vanille sehr fein pürieren.',
      'Whey (Vanille/Cookie) und Backpulver unterrühren, die Hälfte der gehackten Schokolade unterheben.',
      'In die Form streichen, restliche Schokolade aufstreuen und 20 Min. backen. Auskühlen lassen.',
    ],
    tm: { fit: 1, note: 'Für 9 Stücke.', steps: [
      ['Schokolade hacken, umfüllen.', '4 Sek.', '', 'Stufe 7', ''],
      ['Kichererbsen, Erdnussmus, Ei, Erythrit und Vanille pürieren, nach unten schieben.', '40 Sek.', '', 'Stufe 8', ''],
      ['Whey und Backpulver zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['Halbe Schokolade unterheben, in die Form streichen, Rest aufstreuen und bei 180 °C 20 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Kleinkind: Teil ohne Whey, Erythrit und Schokostücke backen, dafür ½ Banane – Erdnuss und Kichererbse sind gute frühe Lebensmittel. Baby (ab 8 Mon.): weiche Streifen ohne Schokolade.',
    baby: 1,
  },
  {
    id: 'erdnuss-protein-blondies',
    n: 'Erdnuss-Protein-Blondies',
    ck: 'Erdnussbutter Blondies',
    img: { wiki: 'Blondie (confection)', q: 'peanut butter blondies' },
    cu: 'amerikanisch', m: ['snack'], t: 35, d: 1, st: ['dessert', 'mealprep'],
    i: [['mandelmehl', 15], ['erdnussbutter', 12], ['eiklar', 30], ['skyr', 50], ['whey', 10], ['erythrit', 12], ['backpulver', 2], ['erdnuesse', 5], ['vanille', 1]],
    s: [
      'Ofen auf 175 °C vorheizen, 20×20-cm-Form auslegen. Ergibt 9 Stücke.',
      'Erdnussmus, Eiklar, Skyr, Erythrit und Vanille glatt rühren.',
      'Mandelmehl, Whey (Vanille) und Backpulver unterrühren.',
      'Teig in die Form streichen und mit gehackten Erdnüssen bestreuen.',
      '18–20 Min. backen, auskühlen lassen und in Quadrate schneiden.',
    ],
    tm: { fit: 1, note: 'Für 9 Stücke.', steps: [
      ['Erdnüsse hacken, umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
      ['Erdnussmus, Eiklar, Skyr, Erythrit und Vanille verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Mandelmehl, Whey und Backpulver zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['In die Form streichen, Erdnüsse aufstreuen und bei 175 °C 18–20 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Kinder-Variante ohne Whey und Erythrit, mit zerdrückter Banane; Erdnüsse für unter 4-Jährige NICHT ganz/gehackt obendrauf, nur als Mus im Teig. Baby (ab 8 Mon.): weiche Streifen – frühe Erdnuss-Einführung.',
    baby: 1,
  },
  /* ---------- Bananenbrot ---------- */
  {
    id: 'schoko-bananenbrot-protein',
    n: 'Schoko-Bananenbrot mit Protein',
    ck: 'Schoko Bananenbrot',
    img: { wiki: 'Banana bread', q: 'chocolate banana bread' },
    cu: 'amerikanisch', m: ['snack'], t: 65, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['banane', 50], ['haferflocken', 20], ['esn_designer_whey', 12], ['ei', 20], ['skyr', 40], ['kakao', 5], ['zartbitter', 5], ['backpulver', 2]],
    s: [
      'Ofen auf 175 °C vorheizen, Kastenform (25 cm) auslegen. Ergibt 10 Scheiben.',
      'Haferflocken (glutenfrei: zertifizierte) fein mahlen, sehr reife Bananen zerdrücken (1 Banane für die Deko längs halbieren).',
      'Bananen, Eier und Skyr verrühren, Hafermehl, Whey (Schoko), Kakao und Backpulver unterrühren.',
      'Gehackte Schokolade unterheben, Teig in die Form füllen und die Bananenhälften auflegen.',
      '45–50 Min. backen (Stäbchenprobe), in der Form 10 Min. abkühlen lassen.',
    ],
    tm: { fit: 1, note: 'Für 10 Scheiben.', steps: [
      ['Haferflocken und Schokolade in den Mixtopf geben und zerkleinern.', '8 Sek.', '', 'Stufe 8', ''],
      ['Bananen in Stücken zugeben und zerdrücken.', '5 Sek.', '', 'Stufe 4', ''],
      ['Eier, Skyr, Whey, Kakao und Backpulver zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['In die Kastenform füllen und bei 175 °C 45–50 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Kleinkind: halbe Menge Teig ohne Whey und ohne Schokostücke in einer kleinen Form backen (Banane süßt genug). Baby: lieber reines Bananen-Hafer-Brot ohne Kakao als Fingerfood.',
    baby: 0,
  },
  /* ---------- Crêpes & Pfannkuchen-Desserts ---------- */
  {
    id: 'schoko-protein-crepes-banane',
    n: 'Schoko-Protein-Crêpes mit Banane',
    ck: 'Schoko Crêpes',
    img: { wiki: 'Crêpe', q: 'chocolate crepes banana' },
    cu: 'international', m: ['snack'], t: 25, d: 2, st: ['dessert', 'kinderliebling'],
    i: [['ei', 50], ['milch', 60], ['mehl', 15], ['kakao', 4], ['esn_designer_whey', 10], ['rapsoel', 2], ['banane', 40], ['skyr', 50], ['erythrit', 5]],
    s: [
      'Ei, Milch, Mehl (glutenfrei: glutenfreie Mehlmischung), Kakao und Whey (Schoko) glatt verquirlen, 10 Min. ruhen lassen.',
      'Skyr mit Erythrit cremig rühren, Banane in Scheiben schneiden.',
      'Pfanne mit wenig Öl auspinseln, dünne Crêpes je 1 Min. pro Seite backen (Kakao-Teig verbrennt schnell – mittlere Hitze).',
      'Crêpes mit Skyr bestreichen, Bananenscheiben darauflegen und falten.',
    ],
    tm: { fit: 1, note: 'Teig im Thermomix, Backen in der Pfanne.', steps: [
      ['Ei, Milch, Mehl, Kakao und Whey in den Mixtopf geben und verrühren.', '20 Sek.', '', 'Stufe 5', ''],
      ['Teig 10 Min. ruhen lassen.', '', '', '', ''],
      ['Crêpes in der Pfanne bei mittlerer Hitze ausbacken.', '', '', '', ''],
      ['Mit Skyr und Bananenscheiben füllen.', '', '', '', ''],
    ] },
    kid: 'Kinder-Crêpes: Teig ohne Whey und Kakao vorher abnehmen, mit Banane und Skyr füllen. Baby (ab 8 Mon.): Crêpe-Streifen mit zerdrückter Banane, ohne Erythrit.',
    baby: 1,
  },
  {
    id: 'buchweizen-crepes-apfelkompott',
    n: 'Süße Buchweizen-Crêpes mit Apfelkompott & Skyr',
    ck: 'Buchweizen Crêpes',
    img: { wiki: 'Galette', q: 'buckwheat crepes apple' },
    cu: 'international', m: ['snack'], t: 30, d: 2, st: ['dessert'],
    i: [['buchweizen', 20], ['ei', 40], ['milch', 80], ['rapsoel', 2], ['apfel', 80], ['zimt', 1], ['skyr', 100], ['erythrit', 5]],
    s: [
      'Buchweizen fein mahlen (oder Buchweizenmehl verwenden) und mit Ei und Milch zu einem dünnen Teig verrühren, 15 Min. quellen lassen.',
      'Apfel würfeln und mit Zimt und 2 EL Wasser 5–6 Min. weich dünsten.',
      'Skyr mit Erythrit verrühren.',
      'Pfanne mit wenig Öl auspinseln, dünne Crêpes je 1–2 Min. pro Seite backen.',
      'Crêpes mit Skyr und Apfelkompott füllen und falten.',
    ],
    tm: { fit: 1, note: 'Für 4 Portionen. Backen in der Pfanne.', steps: [
      ['Buchweizen in den Mixtopf geben und mahlen.', '1 Min.', '', 'Stufe 10', ''],
      ['Ei und Milch zugeben und verrühren, umfüllen und quellen lassen.', '20 Sek.', '', 'Stufe 5', ''],
      ['Apfelwürfel, Zimt und 30 g Wasser in den Mixtopf geben und dünsten.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Crêpes in der Pfanne backen und mit Skyr und Kompott füllen.', '', '', '', ''],
    ] },
    kid: 'Buchweizen ist von Natur aus glutenfrei und babyfreundlich. Baby (ab 8 Mon.): Crêpe-Streifen mit püriertem Apfelkompott, ohne Erythrit. Kleinkind: eingerollt mit Skyr und Kompott.',
    baby: 2,
  },
  {
    id: 'dutch-baby-aepfel-protein',
    n: 'Dutch Baby (Ofenpfannkuchen) mit Äpfeln',
    ck: 'Ofenpfannkuchen',
    img: { wiki: 'Dutch baby pancake', q: 'dutch baby pancake apples' },
    cu: 'amerikanisch', m: ['snack'], t: 30, d: 2, st: ['dessert', 'kinderliebling'],
    i: [['ei', 60], ['milch', 60], ['mehl', 15], ['esn_designer_whey', 8], ['butter', 3], ['apfel', 70], ['zimt', 1], ['erythrit', 5], ['skyr', 50]],
    s: [
      'Ofen mit einer gusseisernen Pfanne (24 cm) auf 220 °C Ober-/Unterhitze vorheizen.',
      'Eier, Milch, Mehl (glutenfrei: glutenfreie Mehlmischung) und Whey (Vanille) 1 Min. glatt mixen.',
      'Äpfel in dünne Spalten schneiden und mit Zimt und Erythrit mischen.',
      'Butter in der heißen Pfanne schmelzen, Äpfel kurz darin verteilen, Teig darübergießen.',
      '15–18 Min. backen, bis der Rand hoch aufgegangen und goldbraun ist (Ofen nicht öffnen). Sofort mit Skyr servieren.',
    ],
    tm: { fit: 1, note: 'Teig im Thermomix, Backen im Ofen. Für 4 Portionen.', steps: [
      ['Eier, Milch, Mehl und Whey in den Mixtopf geben und verrühren.', '30 Sek.', '', 'Stufe 5', ''],
      ['Apfelspalten mit Zimt und Erythrit mischen.', '', '', '', ''],
      ['Butter in der heißen Ofenpfanne schmelzen, Äpfel verteilen, Teig darübergießen.', '', '', '', ''],
      ['Bei 220 °C 15–18 Min. backen und mit Skyr servieren.', '', '', '', ''],
    ] },
    kid: 'Teig für Kinder ohne Whey vorbereiten (1 EL Mehl mehr) und ohne Erythrit. Baby (ab 8 Mon.): weiche Pfannkuchenstreifen mit den gebackenen Apfelspalten als Fingerfood. Kleinkind: mit Skyr-Dip.',
    baby: 1,
  },
  {
    id: 'topfenpalatschinken-ofen',
    n: 'Überbackene Topfenpalatschinken',
    ck: 'Topfenpalatschinken',
    img: { wiki: 'Crêpe', q: 'topfenpalatschinken' },
    cu: 'deutsch', m: ['snack'], t: 45, d: 2, st: ['dessert', 'comfort', 'kinderliebling'],
    i: [['ei', 40], ['milch', 80], ['mehl', 12], ['rapsoel', 2], ['magerquark', 100], ['eiklar', 20], ['erythrit', 10], ['rosinen', 5], ['zitronensaft', 5], ['vanille', 1]],
    s: [
      'Ei, 50 g der Milch und Mehl (glutenfrei: glutenfreie Mehlmischung) zu einem dünnen Teig verrühren und in wenig Öl dünne Palatschinken backen.',
      'Ofen auf 180 °C vorheizen. Quark, Erythrit, Zitronensaft, Vanille und Rosinen verrühren.',
      'Palatschinken mit Quarkfüllung bestreichen, einrollen, halbieren und in eine Auflaufform schichten.',
      'Restliche Milch mit dem Eiklar verquirlen und darübergießen.',
      '20 Min. goldbraun überbacken und warm servieren.',
    ],
    tm: { fit: 1, note: 'Für 4 Portionen. Palatschinken in der Pfanne, Überbacken im Ofen.', steps: [
      ['Ei, Milch (Teiganteil) und Mehl in den Mixtopf geben und verrühren, umfüllen.', '20 Sek.', '', 'Stufe 5', ''],
      ['Quark, Erythrit, Zitronensaft und Vanille verrühren, Rosinen unterheben.', '15 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ['Palatschinken in der Pfanne backen, füllen, einrollen und in die Form legen.', '', '', '', ''],
      ['Restliche Milch mit Eiklar verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
      ['Darübergießen und bei 180 °C 20 Min. überbacken.', '', '', '', ''],
    ] },
    kid: 'Kinderportion ohne Erythrit und ohne Rosinen (Verschluckungsgefahr) – dafür Apfelmus in die Füllung. Baby (ab 8 Mon.): weiche Röllchen-Scheiben, Ei durchgegart. Kleinkind: lauwarm als Röllchen.',
    baby: 1,
  },
  /* ---------- Eis & Frozen Yogurt ---------- */
  {
    id: 'protein-vanilleeis-chunky',
    n: 'Protein-Vanilleeis mit Chunky Flavour',
    ck: 'Vanilleeis',
    img: { wiki: 'Ice cream', q: 'vanilla ice cream scoop' },
    cu: 'international', m: ['snack'], t: 15, d: 1, st: ['dessert', 'mealprep'],
    i: [['skyr', 150], ['milch', 50], ['esn_designer_whey', 10], ['more_chunky', 5], ['erythrit', 10], ['vanille', 1], ['sahne_spray_light', 10]],
    s: [
      'Skyr, Milch, Whey (Vanille), Chunky Flavour, Erythrit und Vanille glatt rühren.',
      'Masse in eine flache Dose füllen und 3–4 Std. einfrieren, dabei in der ersten Stunde alle 30 Min. kräftig durchrühren.',
      'Alternativ in Eiswürfelformen frieren und vor dem Servieren kurz cremig mixen.',
      'Vor dem Portionieren 10 Min. antauen lassen und mit einem Tupfer Sprühsahne servieren.',
    ],
    tm: { fit: 2, note: 'Für 4 Portionen. Masse in Eiswürfelformen vorfrieren.', steps: [
      ['Skyr, Milch, Whey, Chunky, Erythrit und Vanille in den Mixtopf geben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['In Eiswürfelformen mind. 4 Std. einfrieren.', '', '', '', ''],
      ['Gefrorene Würfel in den Mixtopf geben und zerkleinern.', '20 Sek.', '', 'Stufe 9', ''],
      ['Mit dem Spatel nach unten schieben und cremig rühren, mit Sprühsahne servieren.', '20 Sek.', '', 'Stufe 4', ''],
    ] },
    kid: 'Kinder-Eis: Skyr mit gefrorener Banane pürieren – ohne Whey, Chunky und Erythrit. Für Babys unter 12 Mon. kein Eis aus dem Gefrierfach direkt; leicht angetaut in kleinen Mengen ok.',
    baby: 0,
  },
  {
    id: 'erdbeer-frozen-yogurt-protein',
    n: 'Erdbeer-Frozen-Yogurt mit Protein',
    ck: 'Frozen Joghurt Erdbeer',
    img: { wiki: 'Frozen yogurt', q: 'strawberry frozen yogurt' },
    cu: 'international', m: ['snack'], t: 10, d: 1, st: ['dessert'],
    i: [['griech_joghurt', 150], ['erdbeeren', 100], ['esn_isoclear', 10], ['erythrit', 10], ['zitronensaft', 5]],
    s: [
      'Erdbeeren waschen, putzen, halbieren und mind. 4 Std. einfrieren (oder TK-Erdbeeren nehmen).',
      'Gefrorene Erdbeeren mit Joghurt, Isoclear-Pulver, Erythrit und Zitronensaft cremig mixen.',
      'Sofort als Soft-Frozen-Yogurt servieren oder 30 Min. nachfrieren, damit er sich portionieren lässt.',
      'Mit ein paar frischen Erdbeerscheiben garnieren.',
    ],
    tm: { fit: 2, note: 'Für 4 Portionen.', steps: [
      ['Gefrorene Erdbeeren, Erythrit und Isoclear in den Mixtopf geben und zerkleinern.', '15 Sek.', '', 'Stufe 9', ''],
      ['Mit dem Spatel nach unten schieben.', '', '', '', ''],
      ['Joghurt und Zitronensaft zugeben und cremig rühren.', '30 Sek.', '', 'Stufe 4', ''],
      ['Sofort servieren oder kurz nachfrieren.', '', '', '', ''],
    ] },
    kid: 'Kinder-Frozen-Yogurt: Erdbeeren und Joghurt pur pürieren, ohne Pulver und Erythrit, ggf. mit Banane süßen. Baby (ab 8 Mon.): leicht angetaut vom Löffel in kleinen Mengen.',
    baby: 1,
  },
  /* ---------- Panna Cotta & Pudding ---------- */
  {
    id: 'espresso-panna-cotta-flexpresso',
    n: 'Espresso-Panna-Cotta mit ESN Flexpresso',
    ck: 'Kaffee Panna Cotta',
    img: { wiki: 'Panna cotta', q: 'coffee panna cotta' },
    cu: 'italienisch', m: ['snack'], t: 20, d: 1, st: ['dessert', 'mealprep'],
    i: [['milch', 150], ['esn_flexpresso', 15], ['gelatine', 4], ['skyr', 80], ['erythrit', 8], ['kakao', 2]],
    s: [
      'Gelatine in 3 EL kaltem Wasser 5 Min. quellen lassen.',
      'Milch mit Erythrit erwärmen (ca. 70 °C), vom Herd nehmen und Gelatine darin auflösen.',
      'Auf ca. 40 °C abkühlen lassen, Flexpresso und Skyr glatt einrühren.',
      'In Gläser füllen und mind. 4 Std. kühlen.',
      'Vor dem Servieren mit Kakao bestäuben.',
    ],
    tm: { fit: 2, note: 'Für 4 Portionen. Proteinpulver erst nach dem Abkühlen zugeben.', steps: [
      ['Milch und Erythrit in den Mixtopf geben und erwärmen.', '4 Min.', '70°C', 'Stufe 2', ''],
      ['Gequollene Gelatine zugeben und auflösen.', '1 Min.', '', 'Stufe 3', ''],
      ['Auf 40 °C abkühlen lassen, Flexpresso und Skyr zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['In Gläser füllen, kühlen und mit Kakao bestäuben.', '', '', '', ''],
    ] },
    kid: 'Enthält Koffein und Proteinpulver – nicht für Kinder. Kinder-Variante: Vanille-Panna-Cotta aus Milch, Skyr und Gelatine mit Beerenpüree.',
    baby: 0,
  },
  {
    id: 'protein-schokopudding-selbstgemacht',
    n: 'Selbstgemachter Protein-Schokopudding',
    ck: 'Schokoladenpudding',
    img: { wiki: 'Chocolate pudding', q: 'chocolate pudding bowl' },
    cu: 'deutsch', m: ['snack'], t: 15, d: 1, st: ['dessert', 'comfort', 'kinderliebling'],
    i: [['milch', 250], ['speisestaerke', 12], ['kakao', 8], ['erythrit', 15], ['esn_designer_whey', 15], ['sahne_spray_light', 5]],
    s: [
      'Speisestärke, Kakao und Erythrit mit 5 EL der kalten Milch glatt rühren.',
      'Restliche Milch aufkochen, die Mischung unter Rühren einrühren und 1 Min. unter Rühren köcheln lassen.',
      'Vom Herd nehmen, 5 Min. abkühlen lassen (unter 60 °C) und Whey (Schoko) glatt einrühren.',
      'In Schälchen füllen, Oberfläche mit Frischhaltefolie abdecken (keine Haut) und kühlen.',
      'Mit einem Tupfer Sprühsahne servieren.',
    ],
    tm: { fit: 2, note: 'Für 4 Portionen.', steps: [
      ['Milch, Speisestärke, Kakao und Erythrit in den Mixtopf geben und aufkochen.', '8 Min.', '90°C', 'Stufe 3', ''],
      ['Kinderportion entnehmen (ohne Pulver).', '', '', '', ''],
      ['5 Min. abkühlen lassen, Whey zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['In Schälchen füllen, abdecken und kühlen.', '', '', '', ''],
    ] },
    kid: 'Kinderportion vor dem Whey entnehmen und statt Erythrit mit ½ zerdrückter Banane süßen. Für Babys wegen Kakao eher nicht – alternativ Vanillepudding mit Banane.',
    baby: 0,
  },
  /* ---------- Grießbrei-Alternativen ---------- */
  {
    id: 'polenta-griessbrei-sauerkirschen',
    n: 'Polenta-Grießbrei mit Sauerkirschen',
    ck: 'Grießbrei',
    img: { wiki: 'Semolina pudding', q: 'semolina pudding cherries' },
    cu: 'deutsch', m: ['snack'], t: 15, d: 1, st: ['dessert', 'comfort', 'kinderliebling'],
    i: [['milch', 200], ['polenta', 25], ['erythrit', 8], ['vanille', 1], ['more_total_sahne', 15], ['sauerkirschen', 50], ['zimt', 0.5]],
    s: [
      'Milch mit Vanille aufkochen, feine Polenta (Maisgrieß) unter Rühren einrieseln lassen.',
      'Bei kleiner Hitze 5–7 Min. unter Rühren quellen lassen, bis ein cremiger Brei entsteht.',
      'Kinderportion abnehmen. Restlichen Brei leicht abkühlen lassen (unter 60 °C), Erythrit und More „Sahne“ glatt einrühren.',
      'Kirschen kurz erwärmen und mit Zimt auf den Brei geben.',
    ],
    tm: { fit: 2, note: 'Für 4 Portionen.', steps: [
      ['Milch, Polenta und Vanille in den Mixtopf geben und garen.', '10 Min.', '90°C', 'Stufe 3', ''],
      ['Kinderportion entnehmen (ohne Pulver und Erythrit).', '', '', '', ''],
      ['5 Min. abkühlen lassen, Erythrit und Proteinpulver zugeben und verrühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['In Schalen füllen und mit Kirschen und Zimt servieren.', '', '', '', ''],
    ] },
    kid: 'Polenta-Brei ist ein idealer glutenfreier Babybrei: Kinderportion vor Pulver und Erythrit entnehmen, mit zerdrückten Kirschen oder Apfelmus süßen. Babys unter 12 Mon. mit wenig Kuhmilch (oder halb Wasser) kochen.',
    baby: 1,
  },
  {
    id: 'hirse-flammeri-erdbeeren',
    n: 'Hirse-Flammeri mit Erdbeeren',
    ck: 'Grießflammeri',
    img: { wiki: 'Flummery', q: 'semolina flummery strawberries' },
    cu: 'deutsch', m: ['snack'], t: 30, d: 2, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['milch', 180], ['hirse', 25], ['gelatine', 3], ['skyr', 80], ['erythrit', 10], ['vanille', 1], ['erdbeeren', 80]],
    s: [
      'Hirse fein mahlen (Hirsegrieß). Gelatine in 2 EL kaltem Wasser quellen lassen.',
      'Milch mit Vanille und Erythrit aufkochen, Hirsegrieß einrühren und bei kleiner Hitze 8–10 Min. quellen lassen.',
      'Vom Herd nehmen, Gelatine darin auflösen, 10 Min. abkühlen lassen und den Skyr unterrühren.',
      'In kalt ausgespülte Förmchen füllen und mind. 4 Std. kühlen.',
      'Erdbeeren pürieren bzw. würfeln, Flammeri stürzen und mit Erdbeeren servieren.',
    ],
    tm: { fit: 2, note: 'Für 4 Portionen.', steps: [
      ['Hirse in den Mixtopf geben und zu Grieß mahlen.', '20 Sek.', '', 'Stufe 8', ''],
      ['Milch, Vanille und Erythrit zugeben und garen.', '12 Min.', '90°C', 'Stufe 3', ''],
      ['Gequollene Gelatine zugeben und auflösen.', '1 Min.', '', 'Stufe 3', ''],
      ['10 Min. abkühlen lassen, Skyr zugeben und verrühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['In Förmchen füllen, kühlen, stürzen und mit Erdbeeren servieren.', '', '', '', ''],
    ] },
    kid: 'Ohne Erythrit zubereiten – Erdbeerpüree süßt. Baby (ab 8 Mon.): Flammeri in kleine Würfel geschnitten oder vom Löffel, Hirse ist glutenfrei und eisenreich.',
    baby: 1,
  },
  /* ---------- Wackelpudding ---------- */
  {
    id: 'orangen-goetterspeise-vanilleschaum',
    n: 'Orangen-Götterspeise mit Vanilleschaum',
    ck: 'Götterspeise',
    img: { wiki: 'Gelatin dessert', q: 'orange jelly dessert' },
    cu: 'deutsch', m: ['snack'], t: 20, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['orange', 100], ['esn_isoclear', 15], ['gelatine', 4], ['erythrit', 8], ['skyr', 80], ['vanille', 1]],
    s: [
      'Gelatine in 3 EL kaltem Wasser 5 Min. quellen lassen.',
      'Orangen auspressen, Saft mit Wasser auf ca. 200 ml pro Portion auffüllen und Isoclear (Orange/Pfirsich) darin auflösen.',
      'Gelatine bei kleiner Hitze auflösen (nicht kochen), 3 EL Saft einrühren, dann zügig unter den restlichen Saft rühren.',
      'In Gläser füllen und mind. 3 Std. fest werden lassen.',
      'Skyr mit Erythrit und Vanille luftig aufschlagen und als Haube auf die Götterspeise geben.',
    ],
    tm: { fit: 1, note: 'Für 4 Gläser. Gelatine im Topf auflösen.', steps: [
      ['Gequollene Gelatine mit 50 g Wasser in den Mixtopf geben und auflösen.', '2 Min.', '60°C', 'Stufe 2', ''],
      ['Orangensaft, Wasser und Isoclear zugeben und verrühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['In Gläser füllen und fest werden lassen. Mixtopf spülen.', '', '', '', ''],
      ['Skyr, Erythrit und Vanille aufschlagen und als Haube aufsetzen.', '30 Sek.', '', 'Stufe 4', ''],
    ] },
    kid: 'Kinder-Götterspeise: frischer Orangensaft mit Gelatine (ohne Isoclear, ohne Erythrit), Haube aus Naturjoghurt. Baby (ab 8 Mon.): kleine Würfel vom Löffel, Saft dafür mit Wasser verdünnen.',
    baby: 1,
  },
  {
    id: 'kirsch-wackelpudding-quarkhaube',
    n: 'Kirsch-Wackelpudding mit Vanillequark-Haube',
    ck: 'Wackelpudding Kirsch',
    img: { wiki: 'Gelatin dessert', q: 'cherry jelly dessert cream' },
    cu: 'deutsch', m: ['snack'], t: 20, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['sauerkirschen', 80], ['gelatine', 5], ['erythrit', 10], ['zitronensaft', 5], ['magerquark', 100], ['milch', 30], ['vanille', 1]],
    s: [
      'Gelatine in 3 EL kaltem Wasser 5 Min. quellen lassen. Kirschen abtropfen, den Saft auffangen.',
      'Kirschsaft mit Wasser auf ca. 150 ml pro Portion auffüllen, mit Zitronensaft und der Hälfte des Erythrits erwärmen (nicht kochen) und Gelatine darin auflösen.',
      'Kirschen in Gläser verteilen, Flüssigkeit darübergießen und mind. 3 Std. kühlen.',
      'Quark mit Milch, restlichem Erythrit und Vanille cremig rühren.',
      'Als Haube auf den Wackelpudding geben.',
    ],
    tm: { fit: 2, note: 'Für 4 Gläser.', steps: [
      ['Kirschsaft, Wasser, Zitronensaft und halbes Erythrit in den Mixtopf geben und erwärmen.', '3 Min.', '70°C', 'Stufe 2', ''],
      ['Gequollene Gelatine zugeben und auflösen.', '1 Min.', '', 'Stufe 2', ''],
      ['Über die Kirschen in die Gläser gießen und fest werden lassen. Mixtopf spülen.', '', '', '', ''],
      ['Quark, Milch, restliches Erythrit und Vanille verrühren und als Haube aufsetzen.', '20 Sek.', '', 'Stufe 4', ''],
    ] },
    kid: 'Für Kinder ohne Erythrit (Kirschsaft mit etwas Apfelsaft süßen). Baby (ab 8 Mon.): Wackelpudding in kleine Würfel schneiden, Kirschen zerdrücken, Quark nur ein Klecks.',
    baby: 1,
  },
  /* ---------- Riegel & Bites ---------- */
  {
    id: 'schoko-erdnuss-proteinriegel',
    n: 'Schoko-Erdnuss-Proteinriegel (no bake)',
    ck: 'Proteinriegel',
    img: { wiki: 'Protein bar', q: 'homemade protein bars chocolate peanut' },
    cu: 'amerikanisch', m: ['snack'], t: 20, d: 1, st: ['dessert', 'mealprep'],
    i: [['haferflocken', 15], ['erdnussbutter', 12], ['esn_designer_whey', 15], ['kakao', 3], ['datteln', 8], ['milch', 15], ['zartbitter', 6]],
    s: [
      'Datteln sehr fein hacken, Haferflocken (glutenfrei: zertifizierte) grob mahlen. Mengen pro Riegel, ergibt 8 Riegel.',
      'Haferflocken, Whey (Schoko), Kakao, Datteln, Erdnussmus und Milch zu einer formbaren Masse verkneten.',
      'In eine mit Backpapier ausgelegte Kastenform drücken und glatt streichen.',
      'Schokolade schmelzen, darüberstreichen und 1 Std. kühlen.',
      'In 8 Riegel schneiden und im Kühlschrank aufbewahren (hält 1 Woche).',
    ],
    tm: { fit: 2, note: 'Für 8 Riegel.', steps: [
      ['Haferflocken und Datteln in den Mixtopf geben und zerkleinern.', '10 Sek.', '', 'Stufe 8', ''],
      ['Whey, Kakao, Erdnussmus und Milch zugeben und verkneten.', '1 Min.', '', '', 'Teigkneten'],
      ['Masse in eine Form drücken. Mixtopf säubern.', '', '', '', ''],
      ['Schokolade zerkleinern und schmelzen.', '3 Min.', '50°C', 'Stufe 2', ''],
      ['Darüberstreichen, kühlen und in Riegel schneiden.', '', '', '', ''],
    ] },
    kid: 'Kinder-Riegel ohne Whey: Haferflocken, Datteln und Erdnussmus mit etwas Banane verkneten. Datteln sehr fein hacken (Verschluckungsgefahr). Für Babys nicht als Riegel geeignet.',
    baby: 0,
  },
  {
    id: 'apfel-hafer-proteinriegel-gebacken',
    n: 'Gebackene Apfel-Hafer-Proteinriegel',
    ck: 'Haferriegel',
    img: { q: 'baked oat bars apple' },
    cu: 'international', m: ['snack'], t: 35, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['haferflocken', 25], ['apfelmus', 40], ['esn_designer_whey', 15], ['eiklar', 20], ['magerquark', 40], ['mandeln', 5], ['zimt', 1]],
    s: [
      'Ofen auf 180 °C vorheizen, eine 20×20-cm-Form auslegen. Mengen pro Riegel, ergibt 8 Riegel.',
      'Haferflocken (glutenfrei: zertifizierte), Whey (Vanille), Zimt und gehackte Mandeln mischen.',
      'Apfelmus, Eiklar und Quark unterrühren.',
      'Masse in die Form streichen und 20–22 Min. backen, bis die Ränder goldbraun sind.',
      'Vollständig abkühlen lassen und in Riegel schneiden. Gekühlt 4 Tage haltbar.',
    ],
    tm: { fit: 1, note: 'Für 8 Riegel. Backen im Ofen.', steps: [
      ['Mandeln hacken.', '3 Sek.', '', 'Stufe 5', ''],
      ['Haferflocken, Whey, Zimt, Apfelmus, Eiklar und Quark zugeben und vermengen.', '30 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ['In die Form streichen.', '', '', '', ''],
      ['Bei 180 °C 20–22 Min. backen und schneiden.', '', '', '', ''],
    ] },
    kid: 'Kinder-Riegel ohne Whey (mehr Haferflocken und eine zerdrückte Banane), Mandeln gemahlen. Baby (ab 8 Mon.): weiche Streifen als Fingerfood.',
    baby: 1,
  },
  {
    id: 'erdnuss-schoko-protein-bites',
    n: 'Erdnuss-Schoko-Protein-Bites mit Chunky Flavour',
    ck: 'Energy Balls Erdnuss',
    img: { q: 'peanut chocolate protein balls' },
    cu: 'international', m: ['snack'], t: 15, d: 1, st: ['dessert', 'mealprep'],
    i: [['haferflocken', 15], ['erdnussbutter', 10], ['esn_designer_whey', 15], ['datteln', 10], ['kakao', 3], ['more_chunky', 3], ['milch', 10]],
    s: [
      'Haferflocken (glutenfrei: zertifizierte) und Datteln fein zerkleinern. Eine Portion = 3 Bites.',
      'Erdnussmus, Whey (Schoko), Chunky Flavour (z. B. Peanut Butter) und Milch zugeben und verkneten.',
      'Mit feuchten Händen walnussgroße Kugeln formen.',
      'In Kakao wälzen und mind. 30 Min. kühlen. Hält im Kühlschrank 1 Woche.',
    ],
    tm: { fit: 2, note: 'Für 12 Bites (4 Portionen).', steps: [
      ['Haferflocken und Datteln in den Mixtopf geben und zerkleinern.', '10 Sek.', '', 'Stufe 8', ''],
      ['Erdnussmus, Whey, Chunky und Milch zugeben und verkneten.', '1 Min.', '', '', 'Teigkneten'],
      ['Kugeln formen.', '', '', '', ''],
      ['In Kakao wälzen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Nicht für Babys (Pulver, Kugelform). Kleinkinder (ab 2 J.): Bites ohne Whey und Chunky aus Hafer, Dattel und Erdnussmus, flach gedrückt als Taler statt Kugeln.',
    baby: 0,
  },
  {
    id: 'frozen-cheesecake-bites',
    n: 'Frozen Cheesecake Bites mit Schokoboden',
    ck: 'Cheesecake Pralinen',
    img: { q: 'frozen cheesecake bites raspberry' },
    cu: 'amerikanisch', m: ['snack'], t: 20, d: 1, st: ['dessert', 'mealprep'],
    i: [['frischkaese_light', 30], ['magerquark', 80], ['esn_designer_whey', 10], ['erythrit', 8], ['zitronensaft', 3], ['himbeeren', 40], ['zartbitter', 6]],
    s: [
      'Schokolade schmelzen und je 1 TL in Mini-Muffin-Silikonförmchen streichen, 10 Min. einfrieren. Eine Portion = 4 Bites.',
      'Frischkäse, Quark, Whey (Vanille/Cheesecake), Erythrit und Zitronensaft glatt rühren.',
      'Creme auf die Schokoböden geben, je 1 Himbeere hineindrücken.',
      'Mind. 3 Std. einfrieren. Vor dem Essen 5–10 Min. antauen lassen.',
    ],
    tm: { fit: 2, note: 'Für 16 Bites (4 Portionen).', steps: [
      ['Schokolade zerkleinern und schmelzen.', '3 Min.', '50°C', 'Stufe 2', ''],
      ['In Förmchen streichen und anfrieren. Mixtopf säubern.', '', '', '', ''],
      ['Frischkäse, Quark, Whey, Erythrit und Zitronensaft verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Auf die Böden geben, Himbeeren hineindrücken und einfrieren.', '', '', '', ''],
    ] },
    kid: 'Kinder-Variante: Quark mit Himbeerpüree in Förmchen frieren – ohne Whey, Erythrit und Schokoboden. Baby (ab 8 Mon.): angetaut in kleinen Mengen.',
    baby: 0,
  },
  /* ---------- Gebackenes & Schoko-Desserts ---------- */
  {
    id: 'protein-schoko-lava-cake',
    n: 'Protein-Schoko-Lava-Cake',
    ck: 'Lava Cake',
    img: { wiki: 'Molten chocolate cake', q: 'chocolate lava cake' },
    cu: 'international', m: ['snack'], t: 20, d: 2, st: ['dessert', 'comfort'],
    i: [['ei', 50], ['magerquark', 50], ['kakao', 8], ['esn_designer_whey', 12], ['zartbitter', 10], ['erythrit', 10], ['speisestaerke', 3], ['backpulver', 1]],
    s: [
      'Ofen auf 200 °C vorheizen, zwei Förmchen (Ramequins) dünn einfetten. Mengen pro Portion = 1 Förmchen.',
      'Ei, Quark und Erythrit verrühren, Kakao, Whey (Schoko), Stärke und Backpulver unterrühren.',
      'Die Hälfte des Teigs in die Förmchen geben, je ein Stück Schokolade in die Mitte legen, mit restlichem Teig bedecken.',
      '9–11 Min. backen: Rand fest, Mitte noch weich.',
      '2 Min. ruhen lassen, auf einen Teller stürzen und sofort servieren.',
    ],
    tm: { fit: 1, note: 'Teig für 4 Förmchen im Thermomix, Backen im Ofen.', steps: [
      ['Ei, Quark, Erythrit, Kakao, Whey, Stärke und Backpulver in den Mixtopf geben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Halbe Teigmenge in die Förmchen füllen.', '', '', '', ''],
      ['Schokostück hineinsetzen und mit restlichem Teig bedecken.', '', '', '', ''],
      ['Bei 200 °C 9–11 Min. backen und stürzen.', '', '', '', ''],
    ] },
    kid: 'Nicht für Babys (flüssiger Kern mit nicht durchgegartem Ei, Schokolade). Kleinkinder: Teig ohne Whey/Erythrit mit Banane 15 Min. durchbacken (ohne Schokokern).',
    baby: 0,
  },
  {
    id: 'protein-cookies-schokostueckchen',
    n: 'Protein-Cookies mit Schokostückchen',
    ck: 'Cookies',
    img: { wiki: 'Chocolate chip cookie', q: 'chocolate chip cookies' },
    cu: 'amerikanisch', m: ['snack'], t: 25, d: 1, st: ['dessert', 'mealprep', 'kinderliebling'],
    i: [['mandelmehl', 15], ['haferflocken', 10], ['esn_designer_whey', 12], ['erdnussbutter', 8], ['eiklar', 15], ['erythrit', 8], ['zartbitter', 6], ['backpulver', 1]],
    s: [
      'Ofen auf 175 °C vorheizen, Blech mit Backpapier auslegen. Eine Portion = 2 Cookies.',
      'Mandelmehl, Haferflocken (glutenfrei: zertifizierte), Whey (Cookie/Vanille), Erythrit und Backpulver mischen.',
      'Erdnussmus und Eiklar unterkneten, gehackte Schokolade unterheben.',
      'Mit feuchten Händen Kugeln formen, aufs Blech setzen und flach drücken.',
      '9–11 Min. backen – sie sind warm noch weich und werden beim Abkühlen fester.',
    ],
    tm: { fit: 1, note: 'Für 8 Cookies (4 Portionen).', steps: [
      ['Schokolade hacken, umfüllen.', '4 Sek.', '', 'Stufe 7', ''],
      ['Mandelmehl, Haferflocken, Whey, Erythrit, Backpulver, Erdnussmus und Eiklar zugeben und verkneten.', '40 Sek.', '', '', 'Teigkneten'],
      ['Schokolade unterheben.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Cookies formen und bei 175 °C 9–11 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Kinder-Cookies ohne Whey und Erythrit, mit zerdrückter Banane gebunden und ohne Schokostücke. Baby (ab 8 Mon.): weiche Bananen-Hafer-Taler als Fingerfood.',
    baby: 0,
  },
  {
    id: 'apfel-crumble-protein-streusel',
    n: 'Apfel-Crumble mit Protein-Streuseln',
    ck: 'Apfel Crumble',
    img: { wiki: 'Crumble', q: 'apple crumble' },
    cu: 'international', m: ['snack'], t: 40, d: 1, st: ['dessert', 'comfort', 'kinderliebling'],
    i: [['apfel', 120], ['zimt', 1], ['zitronensaft', 5], ['haferflocken', 15], ['mandelmehl', 10], ['esn_designer_whey', 8], ['butter', 4], ['erythrit', 6], ['skyr', 80]],
    s: [
      'Ofen auf 190 °C vorheizen. Äpfel würfeln, mit Zitronensaft, Zimt und der Hälfte des Erythrits mischen und in eine Auflaufform geben.',
      'Haferflocken (glutenfrei: zertifizierte), Mandelmehl, Whey (Vanille), restliches Erythrit und kalte Butterflöckchen zu Streuseln verreiben (bei Bedarf 1 EL Wasser).',
      'Streusel über die Äpfel geben.',
      '25 Min. backen, bis die Streusel goldbraun sind und die Äpfel weich.',
      'Lauwarm mit einem Klecks Skyr servieren.',
    ],
    tm: { fit: 1, note: 'Für 4 Portionen. Backen im Ofen.', steps: [
      ['Haferflocken, Mandelmehl, Whey, Erythrit und Butter in den Mixtopf geben und zu Streuseln verarbeiten.', '10 Sek.', '', 'Stufe 4', ''],
      ['Streusel umfüllen. Äpfel in Stücken zugeben und zerkleinern.', '3 Sek.', '', 'Stufe 4', ''],
      ['Äpfel mit Zitronensaft und Zimt in der Form mischen, Streusel darauf verteilen.', '', '', '', ''],
      ['Bei 190 °C 25 Min. backen und mit Skyr servieren.', '', '', '', ''],
    ] },
    kid: 'Kinderportion: Apfelstücke am Rand ohne Erythrit, Streusel ohne Whey (nur Hafer, Mandel, Butter). Baby (ab 6 Mon.): gebackene weiche Apfelstücke als Fingerfood oder zerdrückt mit Joghurt.',
    baby: 1,
  },
  {
    id: 'bratapfel-quarkfuellung-protein',
    n: 'Bratapfel mit Protein-Quarkfüllung',
    ck: 'Bratapfel',
    img: { wiki: 'Baked apple', q: 'baked apple filled' },
    cu: 'deutsch', m: ['snack'], t: 40, d: 1, st: ['dessert', 'comfort', 'kinderliebling'],
    i: [['apfel', 180], ['magerquark', 100], ['more_pudding', 10], ['haferflocken', 10], ['mandeln', 5], ['zimt', 1], ['erythrit', 5]],
    s: [
      'Ofen auf 180 °C vorheizen. Äpfel waschen, einen Deckel abschneiden und das Kerngehäuse großzügig ausstechen.',
      'Mandeln hacken und mit den Haferflocken (glutenfrei: zertifizierte) in einer Pfanne ohne Fett 2 Min. rösten.',
      'Quark mit Pudding-Pulver (Vanille), Zimt, Erythrit und der Hälfte der Hafer-Mandel-Mischung verrühren.',
      'Äpfel in eine Form setzen, mit der Quarkmasse füllen, Deckel auflegen und 25–30 Min. backen.',
      'Mit der restlichen Hafer-Mandel-Mischung bestreut servieren.',
    ],
    tm: { fit: 1, note: 'Füllung im Thermomix, Backen im Ofen. Für 4 Äpfel.', steps: [
      ['Mandeln und Haferflocken in den Mixtopf geben und hacken.', '3 Sek.', '', 'Stufe 5', ''],
      ['Rösten, die Hälfte umfüllen.', '4 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
      ['Quark, Pudding-Pulver, Zimt und Erythrit zugeben und verrühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Äpfel füllen und bei 180 °C 25–30 Min. backen, mit Rest-Mischung bestreuen.', '', '', '', ''],
    ] },
    kid: 'Kinder-Bratapfel: Füllung nur aus Quark, Zimt und gemahlenen Mandeln (ohne Pulver und Erythrit). Baby (ab 6 Mon.): weich gebackenes Apfelfleisch auslöffeln und zerdrücken – ein toller erster Brei.',
    baby: 1,
  },
  /* ---------- Weitere Kuchen & Pfannkuchen-Desserts ---------- */
  {
    id: 'erdbeer-pfannkuchen-torte',
    n: 'Erdbeer-Pfannkuchen-Torte mit Skyr',
    ck: 'Pfannkuchentorte',
    img: { wiki: 'Crêpe', q: 'crepe cake strawberries' },
    cu: 'international', m: ['snack'], t: 40, d: 2, st: ['dessert', 'kinderliebling'],
    i: [['ei', 40], ['eiklar', 30], ['milch', 50], ['mehl', 15], ['rapsoel', 2], ['skyr', 120], ['erdbeeren', 80], ['erythrit', 8], ['vanille', 1]],
    s: [
      'Ei, Eiklar, Milch und Mehl (glutenfrei: glutenfreie Mehlmischung) zu einem dünnen Teig verrühren und 10 Min. quellen lassen. Ergibt 4 Tortenstücke.',
      'In einer beschichteten Pfanne mit wenig Öl 8 dünne Pfannkuchen backen und auskühlen lassen.',
      'Skyr mit Erythrit und Vanille cremig rühren. Die Hälfte der Erdbeeren in dünne Scheiben schneiden, den Rest fein würfeln.',
      'Pfannkuchen abwechselnd mit Skyrcreme und Erdbeerscheiben zu einer Torte stapeln.',
      'Mit Erdbeerwürfeln belegen, 1 Std. kühlen und in Stücke schneiden.',
    ],
    tm: { fit: 1, note: 'Teig und Creme im Thermomix, Pfannkuchen in der Pfanne. Für 4 Stücke.', steps: [
      ['Ei, Eiklar, Milch und Mehl in den Mixtopf geben und verrühren, umfüllen.', '20 Sek.', '', 'Stufe 5', ''],
      ['Pfannkuchen in der Pfanne dünn ausbacken und abkühlen lassen.', '', '', '', ''],
      ['Mixtopf spülen. Skyr, Erythrit und Vanille cremig rühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Pfannkuchen mit Creme und Erdbeeren schichten und kühlen.', '', '', '', ''],
    ] },
    kid: 'Kinderstück ohne Erythrit – mit zerdrückten Erdbeeren in der Creme süßen. Baby (ab 8 Mon.): Pfannkuchen-Streifen mit etwas Skyr-Erdbeer-Creme, Ei durchgebacken.',
    baby: 2,
  },
  {
    id: 'birnen-clafoutis-protein',
    n: 'Birnen-Clafoutis mit Mandel',
    ck: 'Clafoutis',
    img: { wiki: 'Clafoutis', q: 'pear clafoutis' },
    cu: 'international', m: ['snack'], t: 45, d: 1, st: ['dessert', 'comfort'],
    i: [['birne', 100], ['ei', 50], ['milch', 80], ['mandelmehl', 10], ['esn_designer_whey', 8], ['erythrit', 8], ['vanille', 1], ['butter', 2]],
    s: [
      'Ofen auf 180 °C vorheizen, eine Auflaufform (oder 4 Portionsförmchen) mit der Butter fetten.',
      'Birnen schälen, entkernen und in Spalten schneiden, fächerartig in die Form legen.',
      'Eier, Milch, Mandelmehl, Whey (Vanille), Erythrit und Vanille zu einem flüssigen Teig verquirlen.',
      'Teig über die Birnen gießen.',
      '30–35 Min. backen, bis der Clafoutis gestockt und goldbraun ist. Lauwarm servieren.',
    ],
    tm: { fit: 1, note: 'Für 4 Portionen. Backen im Ofen.', steps: [
      ['Birnenspalten in die gefettete Form legen.', '', '', '', ''],
      ['Eier, Milch, Mandelmehl, Whey, Erythrit und Vanille in den Mixtopf geben und verrühren.', '20 Sek.', '', 'Stufe 5', ''],
      ['Teig über die Birnen gießen.', '', '', '', ''],
      ['Bei 180 °C 30–35 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Kinderförmchen ohne Whey und Erythrit backen – reife Birnen süßen genug. Baby (ab 8 Mon.): weiche gebackene Birnenspalten mit etwas Eierteig als Fingerfood, vollständig gestockt.',
    baby: 1,
  },
  {
    id: 'ananas-upside-down-cake-light',
    n: 'Ananas-Upside-Down-Cake (light)',
    ck: 'Ananaskuchen gestürzt',
    img: { wiki: 'Upside-down cake', q: 'pineapple upside down cake' },
    cu: 'amerikanisch', m: ['snack'], t: 45, d: 1, st: ['dessert', 'kinderliebling'],
    i: [['ananas', 50], ['mandelmehl', 15], ['ei', 25], ['skyr', 40], ['esn_designer_whey', 10], ['erythrit', 10], ['kokosoel', 3], ['backpulver', 2]],
    s: [
      'Ofen auf 180 °C vorheizen, eine 20-cm-Form mit Backpapier auslegen. Ergibt 8 Stücke.',
      'Ananas in Scheiben oder Stücke schneiden und dicht auf den Boden der Form legen, mit einem Drittel des Erythrits bestreuen.',
      'Eier, Skyr, geschmolzenes Kokosöl und restliches Erythrit verrühren, Mandelmehl, Whey (Vanille) und Backpulver unterrühren.',
      'Teig über die Ananas streichen und 25–30 Min. backen.',
      '10 Min. abkühlen lassen und auf eine Platte stürzen.',
    ],
    tm: { fit: 1, note: 'Für 8 Stücke. Backen im Ofen.', steps: [
      ['Ananas in die Form legen und mit etwas Erythrit bestreuen.', '', '', '', ''],
      ['Kokosöl in den Mixtopf geben und schmelzen.', '2 Min.', '50°C', 'Stufe 1', ''],
      ['Eier, Skyr, Erythrit, Mandelmehl, Whey und Backpulver zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Teig über die Ananas streichen, bei 180 °C 25–30 Min. backen und stürzen.', '', '', '', ''],
    ] },
    kid: 'Kinder-Stück: Teig-Portion ohne Whey und Erythrit in einer kleinen Form backen. Baby (ab 8 Mon.): weiche gebackene Ananasstücke und Kuchenstreifen als Fingerfood.',
    baby: 1,
  },
]);
