// Familien-Klassiker: Tex-Mex, deutsche Hausmannskost, Suppen & proteinreiche Snacks
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  {
    id: 'chili-con-carne',
    n: 'Chili con carne',
    img: { wiki: 'Chili con carne', q: 'chili con carne beef beans rice' },
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['rinderhack', 150], ['kidneybohnen', 80], ['tomaten_dose', 200], ['paprika', 100], ['zwiebel', 50], ['knoblauch', 4], ['mais', 30], ['tomatenmark', 15], ['gewuerze', 4], ['olivenoel', 8], ['salz', 1], ['reis', 50], ['kraeuter', 3]],
    s: [
      'Zwiebel und Knoblauch fein würfeln, Paprika in 1 cm große Stücke schneiden.',
      'Öl in einem Topf stark erhitzen, Hackfleisch darin 5–6 Min. krümelig braun anbraten. Zwiebel und Knoblauch 2 Min. mitdünsten, Tomatenmark 1 Min. anrösten.',
      'Paprika, gehackte Tomaten, Kidneybohnen und Mais zugeben und alles 25 Min. bei kleiner Hitze offen köcheln lassen. Parallel den Reis nach Packungsangabe garen.',
      'Die Baby-/Kleinkind-Portion jetzt ungesalzen und ungewürzt entnehmen.',
      'Restliches Chili mit Paprikapulver, Kreuzkümmel, Oregano, Chili und Salz abschmecken, mit Reis und frischem Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Der Reis wird vorab im Garkörbchen gegart und im Thermoserver warmgehalten.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen. Reis warmstellen, Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hackfleisch zugeben und krümelig anbraten, dabei mit dem Spatel auflockern.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomatenmark zugeben und anrösten.', '1 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Paprikastücke, gehackte Tomaten, Kidneybohnen und Mais zugeben, Garkörbchen statt Messbecher auf den Deckel setzen und köcheln.', '25 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ungesalzen und ungewürzt entnehmen.', '', '', '', ''],
        ['Paprikapulver, Kreuzkümmel, Oregano, Chili und Salz zugeben und unterrühren.', '1 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Mit Reis und frischem Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Portion mit etwas Reis grob pürieren oder für BLW mit Reis zu kleinen Bällchen formen; Bohnenhaut ggf. abziehen bzw. Bohnen zerdrücken. Kleinkind (1–3 J.): mild mit nur Paprika edelsüß würzen, Bohnen und Mais leicht zerdrücken, ein Klecks Joghurt macht es cremig.',
    baby: 1,
  },
  {
    id: 'chili-sin-carne',
    n: 'Chili sin carne',
    img: { wiki: 'Chili con carne', q: 'vegetarian chili sin carne lentils beans' },
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['rote_linsen', 40], ['kidneybohnen', 80], ['schwarze_bohnen', 60], ['tomaten_dose', 200], ['paprika', 100], ['zwiebel', 50], ['knoblauch', 4], ['mais', 30], ['tomatenmark', 15], ['gewuerze', 4], ['olivenoel', 6], ['salz', 1], ['reis', 40], ['skyr', 100], ['kraeuter', 3]],
    s: [
      'Zwiebel und Knoblauch fein würfeln, Paprika klein schneiden. Rote Linsen in einem Sieb abspülen.',
      'Öl im Topf erhitzen, Zwiebel und Knoblauch 3 Min. glasig dünsten, Tomatenmark 1 Min. anrösten.',
      'Linsen, Paprika, gehackte Tomaten und 150 ml Wasser zugeben, 15 Min. köcheln. Dann Kidneybohnen, schwarze Bohnen und Mais weitere 10 Min. mitgaren. Reis parallel nach Packungsangabe kochen.',
      'Baby-/Kleinkind-Portion vor dem Würzen entnehmen.',
      'Rest mit Paprikapulver, Kreuzkümmel, Chili und Salz abschmecken. Mit Reis, einem Klecks Skyr und Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Der Reis wird vorab im Garkörbchen gegart und im Thermoserver warmgehalten.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen. Reis warmstellen, Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten, dann Tomatenmark zugeben.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Abgespülte Linsen, Paprikastücke, gehackte Tomaten und 150 g Wasser zugeben und köcheln.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Kidneybohnen, schwarze Bohnen und Mais zugeben und weitergaren.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Würzen entnehmen.', '', '', '', ''],
        ['Paprikapulver, Kreuzkümmel, Chili und Salz zugeben und unterrühren.', '1 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Mit Reis, einem Klecks Skyr und Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürztes Chili mit Reis fein pürieren oder dick einkochen und als Mus auf dem Löffel anbieten; Bohnen immer zerdrücken. Kleinkind (1–3 J.): mild würzen, Bohnen leicht anquetschen, Skyr unterrühren.',
    baby: 1,
  },
  {
    id: 'rindfleisch-tacos',
    n: 'Rindfleisch-Tacos',
    img: { wiki: 'Taco', q: 'ground beef tacos corn tortilla' },
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling'],
    i: [['rinderhack', 140], ['tortilla_mais', 90], ['tomate', 60], ['salat', 30], ['rote_zwiebel', 20], ['cheddar', 15], ['griech_joghurt', 50], ['avocado', 30], ['limette', 15], ['cajun', 4], ['olivenoel', 5], ['kraeuter', 3]],
    s: [
      'Tomate und rote Zwiebel fein würfeln, Salat in Streifen schneiden, Avocado mit Limettensaft zerdrücken.',
      'Öl in einer Pfanne erhitzen, Hackfleisch 6–7 Min. krümelig braten. Baby-/Kleinkind-Portion jetzt ungewürzt herausnehmen.',
      'Restliches Hack mit Taco-Gewürz und 3 EL Wasser 2 Min. schmoren lassen.',
      'Maistortillas in einer trockenen Pfanne je 30 Sek. pro Seite erwärmen.',
      'Tortillas mit Hack, Salat, Tomate, Zwiebel, Avocado, Cheddar und Joghurt füllen, mit Koriander bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Thermomix für Salsa, Avocado-Creme und Hackfüllung; Tortillas in der Pfanne erwärmen.',
      steps: [
        ['Tomate und rote Zwiebel in Stücken in den Mixtopf geben und grob zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 4', ''],
        ['Avocado mit Limettensaft in den Mixtopf geben und zerdrücken, umfüllen.', '8 Sek.', '', 'Stufe 4', ''],
        ['Öl und Hackfleisch in den Mixtopf geben und krümelig garen, dabei mit dem Spatel auflockern.', '7 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ungewürzt entnehmen.', '', '', '', ''],
        ['Taco-Gewürz und 3 EL Wasser zugeben und schmoren.', '2 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Maistortillas in einer trockenen Pfanne je 30 Sek. pro Seite erwärmen.', '', '', '', ''],
        ['Tortillas mit Hack, Salat, Salsa, Avocado-Creme, Cheddar und Joghurt füllen, mit Koriander bestreuen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürztes Hack mit zerdrückter Avocado und Joghurt mischen und löffeln, oder weiche Tortilla-Streifen mit Avocado bestrichen als Fingerfood. Kleinkind (1–3 J.): Taco offen auf dem Teller servieren, Tomaten klein würfeln, nur mildes Paprikapulver.',
    baby: 1,
  },
  {
    id: 'garnelen-tacos',
    n: 'Garnelen-Tacos',
    img: { wiki: 'Taco', q: 'shrimp tacos slaw lime' },
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['garnelen', 180], ['tortilla_mais', 90], ['weisskohl', 60], ['griech_joghurt', 60], ['avocado', 30], ['mango', 40], ['limette', 20], ['knoblauch', 4], ['gewuerze', 3], ['olivenoel', 8], ['kraeuter', 3], ['salz', 0.5]],
    s: [
      'Garnelen auftauen und trocken tupfen. Kohl sehr fein hobeln und mit Joghurt, der Hälfte des Limettensafts und einer Prise Salz zum Krautsalat mischen.',
      'Mango und Avocado würfeln, Koriander hacken.',
      'Öl in einer Pfanne stark erhitzen, Knoblauch kurz anbraten, Garnelen 2–3 Min. braten, bis sie rosa und durchgegart sind. Baby-/Kleinkind-Portion herausnehmen.',
      'Restliche Garnelen mit Paprikapulver, Kreuzkümmel und etwas Chili würzen.',
      'Maistortillas trocken in der Pfanne erwärmen und mit Krautsalat, Garnelen, Mango, Avocado und Limettensaft füllen.',
    ],
    tm: {
      fit: 0,
      note: 'Thermomix nur für Krautsalat und Koriander; die Garnelen werden in der Pfanne gebraten.',
      steps: [
        ['Koriander in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Weißkohl in Stücken in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Joghurt, die Hälfte des Limettensafts und eine Prise Salz zugeben und zum Krautsalat vermischen, umfüllen.', '10 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Mango und Avocado würfeln.', '', '', '', ''],
        ['Garnelen mit Knoblauch in einer heißen Pfanne 2–3 Min. durchbraten, Baby-/Kleinkind-Portion herausnehmen, Rest mit Paprikapulver, Kreuzkümmel und Chili würzen.', '', '', '', ''],
        ['Maistortillas trocken in der Pfanne erwärmen und mit Krautsalat, Garnelen, Mango, Avocado, Koriander und Limettensaft füllen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Garnelen nur vollständig durchgegart, sehr fein gehackt in zerdrückte Avocado gemischt anbieten (Krebstiere als neues Allergen einzeln einführen). Kleinkind (1–3 J.): Garnelen klein schneiden, Kohl weglassen oder sehr fein, Mango in Streifen.',
    baby: 1,
  },
  {
    id: 'burrito-bowl-haehnchen',
    n: 'Burrito-Bowl mit Hähnchen',
    img: { wiki: 'Burrito', q: 'chicken burrito bowl rice beans' },
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['mealprep', 'kinderliebling'],
    i: [['haehnchenbrust', 160], ['reis', 60], ['schwarze_bohnen', 60], ['mais', 30], ['paprika', 80], ['tomate', 60], ['salat', 30], ['avocado', 30], ['griech_joghurt', 40], ['limette', 15], ['cajun', 4], ['olivenoel', 6], ['kraeuter', 3]],
    s: [
      'Reis nach Packungsangabe garen und mit etwas Limettensaft und gehacktem Koriander mischen.',
      'Hähnchen in Streifen schneiden, Baby-/Kleinkind-Portion ungewürzt beiseitelegen. Rest mit Taco-Gewürz und der Hälfte des Öls marinieren.',
      'Paprika in Streifen in restlichem Öl 4 Min. braten, herausnehmen. Hähnchen in derselben Pfanne 6–7 Min. durchbraten (ungewürzte Kinderportion separat mitgaren).',
      'Bohnen und Mais abspülen und kurz erwärmen, Tomate würfeln, Salat schneiden, Avocado in Scheiben schneiden.',
      'Alles nebeneinander auf Reis anrichten und mit Joghurt und Limette servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Das Hähnchen wird im Varoma gedämpft statt gebraten; Reis gart gleichzeitig im Garkörbchen.',
      steps: [
        ['Koriander in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Hähnchen in Streifen schneiden, Baby-/Kleinkind-Portion ungewürzt beiseitelegen, Rest mit Taco-Gewürz und Öl marinieren.', '', '', '', ''],
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen.', '', '', '', ''],
        ['Hähnchen (Kinderportion auf einer Seite) und Paprikastreifen in den Varoma-Behälter legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Bohnen und Mais auf den Varoma-Einlegeboden geben, einsetzen und weitergaren.', '5 Min.', 'Varoma', 'Stufe 4', ''],
        ['Reis mit Limettensaft und Koriander mischen.', '', '', '', ''],
        ['Tomate, Salat und Avocado schneiden und alles auf dem Reis anrichten, mit Joghurt und Limette servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürztes Hähnchen in fingerdicken Streifen oder fein gezupft, dazu Reis mit zerdrückter Avocado und zerquetschten Bohnen. Kleinkind (1–3 J.): alles als „Buffet“ auf dem Teller zum selbst Zugreifen, Mais leicht zerdrücken.',
    baby: 2,
  },
  {
    id: 'haehnchen-fajitas',
    n: 'Hähnchen-Fajitas',
    img: { file: 'Chicken fajitas - La Hacienda - Sarah Stierch.jpg', wiki: 'Fajita', q: 'chicken fajitas peppers onions skillet' },
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling'],
    i: [['haehnchenbrust', 160], ['tortilla', 90], ['paprika', 150], ['rote_zwiebel', 60], ['cajun', 4], ['olivenoel', 8], ['griech_joghurt', 50], ['salsa', 40], ['limette', 15], ['salat', 20]],
    s: [
      'Hähnchen, Paprika und Zwiebel in dünne Streifen schneiden.',
      'Baby-/Kleinkind-Portion Hähnchen ungewürzt abnehmen. Restliches Hähnchen mit Fajita-/Taco-Gewürz, Limettensaft und der Hälfte des Öls mischen.',
      'Restliches Öl in einer großen Pfanne sehr heiß werden lassen, Hähnchen 5–6 Min. scharf anbraten, dann Paprika und Zwiebel 4 Min. mitbraten, bis sie leicht gebräunt, aber noch bissfest sind.',
      'Tortillas in einer trockenen Pfanne oder im Ofen bei 160 °C 3 Min. erwärmen.',
      'Mit Salat, Salsa und Joghurt in die Tortillas füllen und aufrollen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen; das Hähnchen in 2 Durchgängen anbraten (Modus Anbraten, TM6/TM7). Tortillas in Pfanne oder Ofen erwärmen.',
      steps: [
        ['Hähnchen, Paprika und Zwiebel in Streifen schneiden. Baby-/Kleinkind-Portion Hähnchen ungewürzt abnehmen, Rest mit Gewürz, Limettensaft und der Hälfte des Öls mischen.', '', '', '', ''],
        ['Restliches Öl und die ungewürzte Kinderportion in den Mixtopf geben und anbraten, herausnehmen.', '5 Min.', '160°C', '', 'Anbraten'],
        ['Gewürztes Hähnchen portionsweise zugeben und anbraten.', '6 Min.', '160°C', '', 'Anbraten'],
        ['Paprika- und Zwiebelstreifen zugeben und bissfest mitgaren.', '4 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tortillas in einer trockenen Pfanne oder im Ofen bei 160 °C 3 Min. erwärmen.', '', '', '', ''],
        ['Mit Salat, Salsa und Joghurt in die Tortillas füllen und aufrollen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürztes Hähnchen und weich gegarte Paprikastreifen (ohne Haut) als Fingerfood, Tortilla in Streifen mit Joghurt-Dip. Kleinkind (1–3 J.): mild würzen, Fajita klein gerollt und halbiert servieren.',
    baby: 1,
  },
  {
    id: 'haehnchen-quesadillas',
    n: 'Hähnchen-Quesadillas',
    img: { file: 'Quesadilla 2.jpg', wiki: 'Quesadilla', q: 'chicken quesadilla cheese cut wedges' },
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling'],
    i: [['haehnchenbrust', 140], ['tortilla', 90], ['cheddar', 20], ['schwarze_bohnen', 40], ['mais', 30], ['paprika', 80], ['cajun', 3], ['salsa', 40], ['griech_joghurt', 40]],
    s: [
      'Hähnchen in kleine Würfel, Paprika in feine Würfel schneiden. Bohnen abspülen und grob zerdrücken.',
      'Hähnchen in einer beschichteten Pfanne ohne Fett 6–7 Min. durchbraten, Paprika 2 Min. mitgaren. Kinderportion abnehmen, Rest mit Taco-Gewürz würzen.',
      'Je eine Tortillahälfte mit zerdrückten Bohnen bestreichen, Hähnchen, Paprika, Mais und Cheddar darauf verteilen, zuklappen.',
      'In der trockenen Pfanne bei mittlerer Hitze pro Seite 2–3 Min. goldbraun backen, bis der Käse schmilzt.',
      'In Dreiecke schneiden und mit Salsa und Joghurt servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Füllung im Thermomix, Quesadillas in der Pfanne ausbacken.',
      steps: [
        ['Paprika in Stücken in den Mixtopf geben und zerkleinern, umfüllen.', '4 Sek.', '', 'Stufe 5', ''],
        ['Abgespülte Bohnen in den Mixtopf geben und grob zerdrücken, umfüllen.', '4 Sek.', '', 'Stufe 4', ''],
        ['Hähnchenwürfel mit 50 g Wasser in den Mixtopf geben und garen.', '7 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Paprika zugeben und mitgaren.', '2 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen, restliche Füllung mit Taco-Gewürz vermischen.', '10 Sek.', '', 'Stufe 1', 'Linkslauf'],
        ['Tortillahälften mit Bohnen bestreichen, mit Hähnchen, Paprika, Mais und Cheddar belegen und zuklappen.', '', '', '', ''],
        ['In der trockenen Pfanne pro Seite 2–3 Min. goldbraun backen, in Dreiecke schneiden und mit Salsa und Joghurt servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Quesadilla mit ungewürzter Füllung in fingerbreite Streifen schneiden (perfektes BLW-Fingerfood), Käse sparsam wegen Salz. Kleinkind (1–3 J.): Dreiecke zum Dippen in Joghurt, Mais leicht zerdrücken.',
    baby: 1,
  },
  {
    id: 'protein-burger',
    n: 'Protein-Burger',
    img: { wiki: 'Hamburger', q: 'homemade lean beef burger wholegrain bun' },
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['kinderliebling'],
    i: [['rinderhack', 150], ['burgerbroetchen', 70], ['cheddar', 15], ['tomate', 50], ['salat', 20], ['rote_zwiebel', 15], ['gurke', 30], ['griech_joghurt', 30], ['ketchup', 15], ['senf', 5], ['suesskartoffel', 150], ['olivenoel', 5], ['gewuerze', 2], ['salz', 0.5]],
    s: [
      'Ofen auf 220 °C Umluft vorheizen. Süßkartoffel in Spalten schneiden, mit Öl und Paprikapulver mischen und 25 Min. auf dem Blech backen, nach der Hälfte wenden.',
      'Hack zu einem flachen, etwas größeren Patty als das Brötchen formen (in der Mitte eine kleine Mulde drücken). Für die Kinder kleine Mini-Patties formen.',
      'Patties in einer heißen Grillpfanne pro Seite 3–4 Min. braten, erst danach die Erwachsenen-Patties salzen und pfeffern. In der letzten Minute Cheddar darauflegen.',
      'Joghurt mit Ketchup und Senf zur Burgersauce verrühren. Brötchen aufgeschnitten kurz anrösten.',
      'Brötchen mit Sauce, Salat, Tomate, Gurke, Zwiebel und Patty belegen und mit den Süßkartoffel-Wedges servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Thermomix nur für die Burgersauce; Wedges im Ofen, Patties in der Grillpfanne.',
      steps: [
        ['Süßkartoffelspalten mit Öl und Paprikapulver mischen und bei 220 °C Umluft 25 Min. backen.', '', '', '', ''],
        ['Joghurt, Ketchup und Senf in den Mixtopf geben und zur Burgersauce verrühren, umfüllen.', '10 Sek.', '', 'Stufe 3', ''],
        ['Patties (Kinder: Mini-Patties) formen und in der Grillpfanne pro Seite 3–4 Min. braten, erst danach die Erwachsenen-Patties salzen; zuletzt Cheddar auflegen.', '', '', '', ''],
        ['Brötchen anrösten und mit Sauce, Salat, Tomate, Gurke, Zwiebel und Patty belegen, mit den Wedges servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes Mini-Patty in Streifen schneiden, Süßkartoffel-Wedges weich gebacken als Fingerfood, Brötchen weglassen oder ein Stück ohne Sauce. Kleinkind (1–3 J.): Mini-Burger mit wenig Sauce, ohne Zwiebel, in Viertel geschnitten.',
    baby: 1,
  },
  {
    id: 'ofen-haehnchen-nuggets-suesskartoffel-pommes',
    n: 'Ofen-Hähnchen-Nuggets mit Süßkartoffel-Pommes',
    img: { wiki: 'Chicken nugget', q: 'baked chicken nuggets sweet potato fries' },
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['kinderliebling', 'comfort'],
    i: [['haehnchenbrust', 170], ['paniermehl', 25], ['ei', 20], ['gewuerze', 3], ['suesskartoffel', 220], ['olivenoel', 10], ['griech_joghurt', 50], ['ketchup', 15], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Ofen auf 220 °C Umluft vorheizen. Süßkartoffeln in 1 cm dicke Stifte schneiden, mit 2/3 des Öls mischen und auf einem Backblech verteilen.',
      'Hähnchen in mundgerechte Stücke schneiden. Ei verquirlen, Paniermehl mit Paprikapulver und restlichem Öl mischen.',
      'Hähnchenstücke erst durch das Ei, dann durch das Paniermehl ziehen und auf ein zweites Blech mit Backpapier legen.',
      'Beide Bleche 18–22 Min. backen, Pommes nach 10 Min. wenden, bis Nuggets innen durchgegart und außen knusprig sind.',
      'Baby-/Kleinkind-Portion entnehmen, dann die Pommes der Erwachsenen salzen. Joghurt mit Kräutern als Dip verrühren und mit Ketchup servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Thermomix nur für Dip und Panade; Nuggets und Pommes backen im Ofen.',
      steps: [
        ['Ofen auf 220 °C Umluft vorheizen, Süßkartoffelstifte mit 2/3 des Öls mischen und auf ein Blech geben.', '', '', '', ''],
        ['Kräuter in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Joghurt zugeben und zum Dip verrühren, umfüllen. Mixtopf ausspülen und trocknen.', '10 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Paniermehl, Paprikapulver und restliches Öl in den Mixtopf geben und vermischen, umfüllen.', '5 Sek.', '', 'Stufe 3', ''],
        ['Hähnchenstücke durch verquirltes Ei und die Panade ziehen und auf ein zweites Blech legen.', '', '', '', ''],
        ['Beide Bleche 18–22 Min. backen, Pommes nach 10 Min. wenden.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion entnehmen, dann die Erwachsenen-Pommes salzen. Mit Dip und Ketchup servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Nuggets in längliche Stücke schneiden, die gut in die Faust passen, Pommes etwas länger weich backen, Dip aus Joghurt ohne Ketchup. Kleinkind (1–3 J.): ungesalzen mit Kräuter-Joghurt-Dip, Ketchup sparsam.',
    baby: 2,
  },
  {
    id: 'fischstaebchen-kartoffelpueree',
    n: 'Selbstgemachte Fischstäbchen mit Kartoffelpüree',
    img: { wiki: 'Fish finger', q: 'homemade fish fingers mashed potatoes' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['kinderliebling', 'comfort'],
    i: [['kabeljau', 180], ['mehl', 10], ['ei', 25], ['paniermehl', 25], ['rapsoel', 8], ['kartoffel', 250], ['milch', 60], ['butter', 6], ['karotte', 100], ['zitrone', 15], ['gewuerze', 1], ['salz', 1]],
    s: [
      'Kartoffeln schälen, in Stücke schneiden und in Wasser 20 Min. weich kochen. Karotten in Stifte schneiden und die letzten 8 Min. in einem Dämpfeinsatz darüber garen.',
      'Kabeljau trocken tupfen und in fingerdicke Stäbchen schneiden. Nacheinander in Mehl, verquirltem Ei und Paniermehl wenden.',
      'Öl in einer beschichteten Pfanne erhitzen, Fischstäbchen bei mittlerer Hitze pro Seite 3 Min. goldbraun braten, bis der Fisch innen gar ist.',
      'Kartoffeln abgießen, mit warmer Milch und Butter zu Püree stampfen, mit Muskat würzen. Baby-/Kleinkind-Portion jetzt ungesalzen abnehmen, dann den Rest salzen.',
      'Fischstäbchen mit Püree, Karotten und Zitronenspalten servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Kartoffeln und Karotten im Thermomix, Fischstäbchen in der Pfanne braten.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Kartoffelstücke ins Garkörbchen geben und einhängen.', '', '', '', ''],
        ['Karottenstifte in den Varoma-Behälter legen, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
        ['Währenddessen Kabeljau-Stäbchen in Mehl, Ei und Paniermehl wenden und in der Pfanne pro Seite 3 Min. goldbraun braten.', '', '', '', ''],
        ['Wasser abgießen. Kartoffeln mit warmer Milch, Butter und Muskat in den Mixtopf geben, Rühraufsatz einsetzen und pürieren.', '30 Sek.', '', 'Stufe 3', ''],
        ['Baby-/Kleinkind-Portion ungesalzen entnehmen.', '', '', '', ''],
        ['Restliches Püree salzen und unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Fischstäbchen mit Püree, Karotten und Zitronenspalten servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fischstäbchen sind ideales BLW-Fingerfood – auf Gräten prüfen, ungesalzenes Püree zum Löffeln oder Dippen, Karottenstifte weich gedämpft. Kleinkind (1–3 J.): Fischstäbchen halbieren, Püree ungesalzen, Zitrone weglassen.',
    baby: 2,
  },
  {
    id: 'frikadellen-kartoffel-moehren-stampf',
    n: 'Frikadellen mit Kartoffel-Möhren-Stampf',
    img: { wiki: 'Frikadeller', q: 'german frikadellen meat patties mashed potatoes carrots' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['kinderliebling', 'comfort', 'mealprep'],
    i: [['rinderhack', 120], ['gemischtes_hack', 30], ['ei', 20], ['paniermehl', 15], ['zwiebel', 30], ['senf', 5], ['rapsoel', 8], ['kartoffel', 220], ['karotte', 120], ['milch', 50], ['butter', 5], ['kraeuter', 3], ['gewuerze', 2], ['salz', 1]],
    s: [
      'Kartoffeln und Möhren schälen, in Stücke schneiden und in Wasser 20 Min. weich kochen.',
      'Zwiebel sehr fein würfeln. Hack mit Ei, Paniermehl, Zwiebel, Senf und Petersilie verkneten. Kinder-Frikadellen ohne Salz formen, dann den Rest mit Salz, Pfeffer und Paprika würzen.',
      'Zu flachen Frikadellen formen (Kinder: kleine Taler) und im Öl bei mittlerer Hitze pro Seite 5–6 Min. braten, bis sie durchgegart sind (Kerntemperatur 72 °C).',
      'Kartoffeln und Möhren abgießen, mit warmer Milch und Butter grob stampfen, mit Muskat würzen. Kinderportion abnehmen, Rest salzen.',
      'Frikadellen mit Stampf und frischer Petersilie servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Hackmasse und Stampf im Thermomix, Frikadellen in der Pfanne braten.',
      steps: [
        ['Petersilie in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Zwiebel in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hack, Ei, Paniermehl, Senf und die Hälfte der Petersilie zugeben und vermengen.', '20 Sek.', '', 'Stufe 4', 'Linkslauf'],
        ['Kinder-Frikadellen ungesalzen abnehmen. Rest mit Salz, Pfeffer und Paprika würzen und vermengen.', '10 Sek.', '', 'Stufe 4', 'Linkslauf'],
        ['Frikadellen formen und in der Pfanne pro Seite 5–6 Min. durchbraten.', '', '', '', ''],
        ['Mixtopf ausspülen, 1000 g Wasser einfüllen, Kartoffel- und Möhrenstücke im Garkörbchen einhängen und garen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
        ['Wasser abgießen, Kartoffeln, Möhren, warme Milch, Butter und Muskat in den Mixtopf geben und grob stampfen.', '10 Sek.', '', 'Stufe 3', ''],
        ['Kinderportion abnehmen, Rest salzen und unterrühren.', '5 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Mini-Frikadellen in Streifen als Fingerfood (weich, zerfallen gut im Mund), Stampf zum Löffeln. Kleinkind (1–3 J.): kleine Taler ohne Salz, Senf nur ganz wenig, Stampf mit Butterflöckchen.',
    baby: 2,
  },
  {
    id: 'pellkartoffeln-kraeuterquark-leinsamen',
    n: 'Pellkartoffeln mit Kräuterquark & Leinsamen',
    img: { file: 'Kartoffeln-quark.jpg', wiki: 'Quark (dairy product)', q: 'boiled potatoes herb quark linseed oil' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['comfort'],
    i: [['kartoffel', 350], ['magerquark', 250], ['milch', 30], ['kraeuter', 10], ['leinsamen', 10], ['rapsoel', 8], ['gurke', 80], ['salz', 1]],
    s: [
      'Kartoffeln gründlich waschen und mit Schale in Salzwasser 20–25 Min. garen, bis sie weich sind.',
      'Quark mit Milch glatt rühren. Schnittlauch, Petersilie und Dill fein hacken, Gurke in kleine Würfel schneiden und beides unterheben.',
      'Baby-/Kleinkind-Portion Quark abnehmen, Rest mit Salz und Pfeffer abschmecken.',
      'Kartoffeln abgießen, kurz ausdampfen lassen und pellen.',
      'Kräuterquark auf die Kartoffeln geben, mit geschroteten Leinsamen bestreuen und mit Rapsöl (oder Leinöl) beträufeln.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Kartoffeln im Garkörbchen und im Varoma-Behälter verteilen.',
      steps: [
        ['Leinsamen in den Mixtopf geben und schroten, umfüllen.', '10 Sek.', '', 'Stufe 8', ''],
        ['Schnittlauch, Petersilie und Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Gurke in Stücken zugeben und zerkleinern.', '3 Sek.', '', 'Stufe 4', ''],
        ['Quark und Milch zugeben und glatt rühren. Baby-/Kleinkind-Portion abnehmen.', '20 Sek.', '', 'Stufe 3', ''],
        ['Rest mit Salz und Pfeffer abschmecken und verrühren, umfüllen. Mixtopf ausspülen.', '5 Sek.', '', 'Stufe 3', ''],
        ['1000 g Wasser einfüllen, Kartoffeln ins Garkörbchen und in den Varoma-Behälter geben, aufsetzen und garen.', '35 Min.', 'Varoma', 'Stufe 1', ''],
        ['Kartoffeln pellen, mit Kräuterquark, Leinsamen und Rapsöl servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): gepellte Kartoffeln mit ungesalzenem Quark zerdrücken und löffeln oder Kartoffelspalten zum Dippen; Leinsamen fein gemahlen untermischen. Kleinkind (1–3 J.): Kartoffeln in Stücke, Quark mild mit Kräutern, Gurke in Stiften dazu.',
    baby: 2,
  },
  {
    id: 'huehnerfrikassee-reis',
    n: 'Hühnerfrikassee mit Reis',
    img: { wiki: 'Fricassee', q: 'chicken fricassee rice german' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort', 'kinderliebling'],
    i: [['haehnchenbrust', 160], ['reis', 65], ['champignons', 60], ['spargel', 60], ['karotte', 60], ['huehnerbruehe', 200], ['sahne', 40], ['mehl', 10], ['butter', 6], ['zitrone', 10], ['kraeuter', 3], ['salz', 0.5]],
    s: [
      'Reis nach Packungsangabe garen. Hähnchen in 2 cm große Würfel, Karotten in Scheiben, Champignons in Viertel und Spargel in 3 cm lange Stücke schneiden.',
      'Brühe aufkochen, Hähnchen und Karotten darin 10 Min. sanft gar ziehen lassen, Spargel und Pilze die letzten 4 Min. mitgaren. Alles mit einer Schaumkelle herausnehmen, Brühe auffangen.',
      'Butter im Topf schmelzen, Mehl darin 1 Min. anschwitzen, nach und nach mit der Brühe ablöschen und glatt rühren, 3 Min. köcheln. Sahne einrühren.',
      'Fleisch und Gemüse zurück in die Sauce geben. Baby-/Kleinkind-Portion jetzt abnehmen (mit salzfreier Brühe bzw. Wasser zubereiten).',
      'Rest mit Zitronensaft, Salz und Pfeffer abschmecken und mit Petersilie und Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Salzarme Brühe verwenden, damit die Kinderportion passt.',
      steps: [
        ['Petersilie in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['800 g Brühe in den Mixtopf füllen, Reis im Garkörbchen einhängen. Hähnchenwürfel und Karotten in den Varoma-Behälter, Spargel und Champignons auf den Einlegeboden geben, aufsetzen und garen.', '22 Min.', 'Varoma', 'Stufe 4', ''],
        ['Reis und Varoma-Inhalt warmstellen. Brühe auffangen und 500 g davon zurück in den Mixtopf geben.', '', '', '', ''],
        ['Butter und Mehl zugeben und zur Sauce aufkochen.', '5 Min.', '95°C', 'Stufe 4', ''],
        ['Sahne zugeben und einrühren.', '1 Min.', '90°C', 'Stufe 3', ''],
        ['Fleisch und Gemüse zugeben und erwärmen.', '2 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen.', '', '', '', ''],
        ['Zitronensaft, Salz und Pfeffer zugeben und unterrühren. Mit Petersilie und Reis servieren.', '30 Sek.', '', 'Sanftrührstufe', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen und Gemüse mit Reis und etwas Sauce pürieren oder Hähnchen gezupft und Karottenscheiben als Fingerfood; Brühe salzfrei. Kleinkind (1–3 J.): Hähnchen klein würfeln, ohne Zitrone, Reis mit Sauce gemischt.',
    baby: 2,
  },
  {
    id: 'paprika-rindergulasch-kartoffeln',
    n: 'Paprika-Rindergulasch mit Kartoffeln',
    img: { wiki: 'Goulash', q: 'beef goulash paprika potatoes' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 120, d: 2,
    st: ['comfort', 'mealprep'],
    i: [['rindergulasch', 170], ['kartoffel', 250], ['paprika', 150], ['zwiebel', 80], ['knoblauch', 4], ['tomatenmark', 20], ['gewuerze', 4], ['rapsoel', 10], ['gemuesebruehe', 200], ['schmand_light', 20], ['salz', 1]],
    s: [
      'Rindfleisch trocken tupfen. Zwiebeln in Streifen, Paprika in 2 cm große Stücke, Knoblauch fein schneiden.',
      'Öl in einem Bräter stark erhitzen und das Fleisch portionsweise 4–5 Min. rundum scharf anbraten. Zwiebeln zugeben und 5 Min. goldbraun rösten, Knoblauch und Tomatenmark 1 Min. mitrösten.',
      'Mit edelsüßem Paprika und Kümmel bestäuben, mit Brühe ablöschen und zugedeckt bei kleiner Hitze 75 Min. schmoren.',
      'Paprika zugeben und weitere 20 Min. schmoren, bis das Fleisch zart ist. Kartoffeln parallel schälen und 20 Min. in Wasser kochen.',
      'Baby-/Kleinkind-Portion vor dem Salzen und vor Rosenpaprika/Chili entnehmen. Rest abschmecken und mit Kartoffeln und einem Klecks Schmand servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen (Mixtopf voll); Fleisch in 2 Durchgängen anbraten, Brühe auf 400 g reduzieren. Modus Anbraten ab TM6.',
      steps: [
        ['Zwiebeln und Knoblauch in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
        ['Öl und die Hälfte des Fleisches in den Mixtopf geben und anbraten, umfüllen. Mit dem restlichen Fleisch wiederholen.', '6 Min.', '160°C', '', 'Anbraten'],
        ['Fleisch, Zwiebeln, Knoblauch und Tomatenmark in den Mixtopf geben und anrösten.', '3 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Paprikapulver, Kümmel und 400 g Brühe zugeben, Garkörbchen statt Messbecher auf den Deckel setzen und schmoren.', '75 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Paprikastücke zugeben, Kartoffeln in den Varoma-Behälter legen, aufsetzen und weitergaren.', '25 Min.', 'Varoma', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Salzen und vor Rosenpaprika/Chili entnehmen.', '', '', '', ''],
        ['Rest mit Salz und Rosenpaprika abschmecken und unterrühren. Mit Kartoffeln und Schmand servieren.', '1 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): zartes Fleisch mit Kartoffel und Paprika (ohne Haut) und etwas Sauce pürieren, oder sehr weiche Fleischfasern zerzupfen. Kleinkind (1–3 J.): Fleisch klein schneiden und mit Kartoffeln in der Sauce zerdrücken, nur edelsüßes Paprika.',
    baby: 1,
  },
  {
    id: 'linseneintopf',
    n: 'Linseneintopf',
    img: { wiki: 'Lentil soup', q: 'german lentil stew carrots potatoes' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['linsen_dose', 250], ['rote_linsen', 40], ['kartoffel', 150], ['karotte', 80], ['sellerie', 30], ['lauch', 50], ['gemuesebruehe', 300], ['olivenoel', 8], ['essig', 5], ['gewuerze', 2], ['kraeuter', 3], ['salz', 0.5]],
    s: [
      'Kartoffeln, Karotten und Sellerie in kleine Würfel, Lauch in Ringe schneiden.',
      'Öl in einem großen Topf erhitzen, Lauch, Karotten und Sellerie 5 Min. andünsten.',
      'Kartoffeln, rote Linsen und Brühe zugeben, mit Majoran und Lorbeer würzen und 20 Min. köcheln, bis die roten Linsen zerfallen und den Eintopf binden.',
      'Abgetropfte Linsen zugeben und 5 Min. erhitzen. Baby-/Kleinkind-Portion vor dem Salzen und vor dem Essig entnehmen.',
      'Rest mit Essig, Salz und Pfeffer abschmecken und mit Petersilie servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen; Mixtopf ist gut gefüllt, daher Brühe auf ca. 800 g begrenzen.',
      steps: [
        ['Karotten und Sellerie in Stücken in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 4', ''],
        ['Lauchringe und Öl zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Kartoffelwürfel, rote Linsen, Brühe, Majoran und Lorbeer zugeben und köcheln.', '20 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Abgetropfte Linsen zugeben und erhitzen.', '5 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Salzen und vor dem Essig entnehmen.', '', '', '', ''],
        ['Essig, Salz und Pfeffer zugeben und unterrühren. Mit Petersilie servieren.', '1 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): mit salzfreier Brühe gekocht ist der Eintopf ein perfekter Brei – fein pürieren oder grob zerdrücken. Kleinkind (1–3 J.): Gemüse und Linsen leicht anquetschen, ohne Essig, dazu ein Stück Brot zum Tunken.',
    baby: 2,
  },
  {
    id: 'huehnersuppe-nudeln-gemuese',
    n: 'Hühnersuppe mit Nudeln & Gemüse',
    img: { wiki: 'Chicken soup', q: 'chicken noodle soup carrots celery' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    st: ['comfort', 'kinderliebling'],
    i: [['haehnchenschenkel', 180], ['nudeln', 60], ['karotte', 100], ['sellerie', 40], ['lauch', 40], ['huehnerbruehe', 450], ['kraeuter', 4], ['gewuerze', 1], ['salz', 0.5]],
    s: [
      'Hähnchenschenkel in der Brühe aufkochen und bei kleiner Hitze 25 Min. gar ziehen lassen. Schaum abschöpfen.',
      'Karotten in Scheiben, Sellerie in Stücke und Lauch in Ringe schneiden.',
      'Fleisch herausnehmen, Gemüse in die Brühe geben und 8 Min. garen. Nudeln zugeben und nach Packungsangabe (ca. 8 Min.) mitkochen.',
      'Fleisch in kleine Stücke zupfen und zurück in die Suppe geben. Baby-/Kleinkind-Portion jetzt entnehmen (mit salzfreier Brühe bzw. Wasser kochen).',
      'Rest mit Salz, Pfeffer und Muskat abschmecken und mit reichlich Petersilie servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 3–4 Portionen (max. 2,2 l); für größere Mengen in zwei Durchgängen kochen. Salzfreie Brühe für die Kinderportion.',
      steps: [
        ['Petersilie in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Hähnchenschenkel und 1200 g Brühe in den Mixtopf geben und gar ziehen lassen.', '25 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Fleisch herausnehmen. Karottenscheiben, Sellerie und Lauch zugeben und garen.', '8 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Nudeln zugeben und garen.', '8 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Fleisch klein zupfen, zurück in die Suppe geben und erwärmen.', '1 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen.', '', '', '', ''],
        ['Rest mit Salz, Pfeffer und Muskat abschmecken und mit Petersilie servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fleisch, Gemüse und Nudeln aus der salzfreien Suppe fischen und als weiches Fingerfood anbieten oder mit etwas Brühe pürieren. Kleinkind (1–3 J.): kurze Nudeln (z. B. Sternchen) verwenden, Fleisch klein zupfen, Suppe lauwarm.',
    baby: 2,
  },
  {
    id: 'kuerbissuppe-rote-linsen',
    n: 'Kürbissuppe mit roten Linsen',
    img: { wiki: 'Pumpkin soup', q: 'pumpkin red lentil soup' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['kuerbis', 300], ['rote_linsen', 60], ['kokosmilch_light', 100], ['gemuesebruehe', 300], ['zwiebel', 40], ['knoblauch', 4], ['ingwer', 5], ['olivenoel', 6], ['currypulver', 2], ['griech_joghurt', 80], ['kuerbiskerne', 10], ['salz', 0.5]],
    s: [
      'Hokkaido waschen, entkernen und mit Schale in Würfel schneiden. Zwiebel, Knoblauch und Ingwer fein hacken. Linsen abspülen.',
      'Öl im Topf erhitzen, Zwiebel, Knoblauch und Ingwer 3 Min. andünsten, Currypulver kurz mitrösten.',
      'Kürbis, Linsen und Brühe zugeben und zugedeckt 20 Min. köcheln, bis Kürbis und Linsen weich sind.',
      'Kokosmilch zugeben und alles fein pürieren. Baby-/Kleinkind-Portion vor dem Salzen entnehmen.',
      'Rest mit Salz und Limette abschmecken. Mit einem Klecks Joghurt und gerösteten Kürbiskernen servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Kürbiskerne separat in der Pfanne rösten.',
      steps: [
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten, Currypulver zugeben und kurz mitdünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Kürbisstücke, abgespülte Linsen und 900 g Brühe zugeben und garen.', '20 Min.', '100°C', 'Stufe 1', ''],
        ['Kokosmilch zugeben und schrittweise auf Stufe 10 ansteigend pürieren.', '1 Min.', '', 'Stufe 10', ''],
        ['Baby-/Kleinkind-Portion vor dem Salzen entnehmen.', '', '', '', ''],
        ['Salz und Limettensaft zugeben und unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Mit Joghurt und gerösteten Kürbiskernen servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): mit salzfreier Brühe gekocht ideal als Brei, etwas dicker einkochen; Kürbiskerne nur fein gemahlen darüber. Kleinkind (1–3 J.): Joghurt unterrühren, Brotstreifen zum Dippen, Kerne gemahlen statt ganz.',
    baby: 2,
  },
  {
    id: 'zucchini-puffer-joghurt-dip',
    n: 'Zucchini-Puffer mit Joghurt-Dip',
    img: { file: 'Zucchini & feta fritters (7804257920).jpg', wiki: 'Kolokithokeftedes', q: 'zucchini fritters yogurt dip' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    st: ['kinderliebling'],
    i: [['zucchini', 300], ['ei', 120], ['mehl', 30], ['parmesan', 20], ['kraeuter', 4], ['rapsoel', 12], ['griech_joghurt', 150], ['gurke', 50], ['knoblauch', 4], ['zitrone', 10], ['salz', 1]],
    s: [
      'Zucchini grob raspeln, mit einer Prise Salz mischen, 10 Min. ziehen lassen und dann in einem Tuch kräftig ausdrücken.',
      'Zucchini mit Eiern, Mehl, Parmesan und gehackten Kräutern zu einem dicken Teig verrühren. Kinderpuffer aus diesem ungewürzten Teig backen, Rest mit Pfeffer würzen.',
      'Öl in einer beschichteten Pfanne erhitzen und je 2 EL Teig als flache Puffer bei mittlerer Hitze pro Seite 3–4 Min. goldbraun braten.',
      'Für den Dip Joghurt mit geriebener Gurke, Knoblauch, Zitronensaft und etwas Salz verrühren (Kinderportion vorher ohne Knoblauch und Salz abnehmen).',
      'Puffer warm mit dem Dip servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Teig und Dip im Thermomix, Puffer in der Pfanne ausbacken.',
      steps: [
        ['Parmesan in Stücken in den Mixtopf geben und zerkleinern, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Kräuter in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Zucchini in Stücken in den Mixtopf geben und raspeln. Mit einer Prise Salz 10 Min. ziehen lassen und in einem Tuch kräftig ausdrücken.', '5 Sek.', '', 'Stufe 5', ''],
        ['Zucchini, Eier, Mehl, Parmesan und Kräuter in den Mixtopf geben und zum Teig verrühren. Kinderpuffer aus diesem Teig backen, Rest pfeffern.', '20 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Je 2 EL Teig in der Pfanne pro Seite 3–4 Min. goldbraun ausbacken. Mixtopf ausspülen.', '', '', '', ''],
        ['Gurke in Stücken in den Mixtopf geben und zerkleinern, Joghurt und Zitronensaft zugeben und verrühren.', '10 Sek.', '', 'Stufe 4', ''],
        ['Kinderportion Dip abnehmen, dann Knoblauch und Salz zugeben und verrühren.', '10 Sek.', '', 'Stufe 4', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Puffer ohne Salz backen und in Streifen schneiden – ideales BLW-Fingerfood, Parmesan sparsam; Joghurt pur als Dip. Kleinkind (1–3 J.): kleine Puffer zum Dippen, Dip ohne Knoblauch.',
    baby: 2,
  },
  {
    id: 'gefuellte-suesskartoffel-huettenkaese-bohnen',
    n: 'Gefüllte Süßkartoffel mit Hüttenkäse & Bohnen',
    img: { wiki: 'Sweet potato', q: 'stuffed baked sweet potato cottage cheese black beans' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 50, d: 1,
    st: ['mealprep'],
    i: [['suesskartoffel', 300], ['huettenkaese', 180], ['schwarze_bohnen', 80], ['mais', 30], ['fruehlingszwiebel', 15], ['salsa', 30], ['olivenoel', 5], ['gewuerze', 2], ['kraeuter', 3], ['limette', 10]],
    s: [
      'Ofen auf 200 °C Ober-/Unterhitze vorheizen. Süßkartoffeln waschen, mehrmals mit einer Gabel einstechen, mit Öl einreiben und 40–45 Min. backen, bis sie ganz weich sind.',
      'Bohnen und Mais abspülen und in einem Topf mit Kreuzkümmel und Paprika 3 Min. erwärmen. Kinderportion vor dem Würzen abnehmen.',
      'Frühlingszwiebel in Ringe schneiden, Koriander hacken.',
      'Süßkartoffeln längs aufschneiden, das Fruchtfleisch mit einer Gabel etwas auflockern.',
      'Mit Bohnen-Mais-Mischung und Hüttenkäse füllen, mit Salsa, Frühlingszwiebel, Koriander und Limettensaft toppen.',
    ],
    tm: {
      fit: 1,
      note: 'Süßkartoffeln im Ofen backen (alternativ in Hälften ca. 40 Min. im Varoma garen); die Füllung im Thermomix.',
      steps: [
        ['Süßkartoffeln einstechen, mit Öl einreiben und bei 200 °C Ober-/Unterhitze 40–45 Min. backen.', '', '', '', ''],
        ['Koriander in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Abgespülte Bohnen und Mais in den Mixtopf geben und erwärmen.', '3 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Würzen abnehmen.', '', '', '', ''],
        ['Kreuzkümmel und Paprikapulver zugeben und unterrühren.', '30 Sek.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Süßkartoffeln aufschneiden, mit Bohnen-Mais-Mischung und Hüttenkäse füllen, mit Salsa, Frühlingszwiebel, Koriander und Limettensaft toppen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Süßkartoffel-Fruchtfleisch mit zerdrückten Bohnen und etwas Hüttenkäse vermischen (Hüttenkäse enthält Salz, daher kleine Menge) oder Süßkartoffel-Spalten mit Schale als Griffhilfe. Kleinkind (1–3 J.): halbe Süßkartoffel ohne Salsa, Bohnen leicht zerdrückt.',
    baby: 2,
  },
  {
    id: 'rinder-stroganoff',
    n: 'Rinder-Stroganoff',
    img: { wiki: 'Beef Stroganoff', q: 'beef stroganoff mushrooms noodles' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 30, d: 2,
    st: ['comfort'],
    i: [['rindersteak', 160], ['champignons', 120], ['zwiebel', 60], ['tomatenmark', 10], ['gemuesebruehe', 100], ['schmand_light', 50], ['senf', 5], ['gewuerze', 3], ['rapsoel', 8], ['nudeln', 70], ['kraeuter', 3], ['salz', 0.5]],
    s: [
      'Bandnudeln nach Packungsangabe kochen. Steak quer zur Faser in dünne Streifen, Zwiebel in Würfel und Champignons in Scheiben schneiden.',
      'Die Hälfte des Öls in einer Pfanne sehr heiß werden lassen, Fleischstreifen 1–2 Min. scharf anbraten und herausnehmen.',
      'Restliches Öl zugeben, Zwiebel und Champignons 5 Min. braten, Tomatenmark und Paprikapulver 1 Min. mitrösten und mit Brühe ablöschen. 3 Min. einkochen.',
      'Schmand und Senf einrühren, Fleisch zurück in die Sauce geben und nur noch 1 Min. erwärmen. Baby-/Kleinkind-Portion jetzt abnehmen.',
      'Rest mit Salz und Pfeffer abschmecken, mit Petersilie bestreuen und über den Nudeln servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Fleisch in der Pfanne scharf anbraten und die Nudeln parallel im Topf kochen; die Sauce im Thermomix.',
      steps: [
        ['Petersilie in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Fleischstreifen in einer sehr heißen Pfanne 1–2 Min. scharf anbraten und beiseitestellen. Bandnudeln im Topf kochen.', '', '', '', ''],
        ['Zwiebel in den Mixtopf geben und zerkleinern, Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Champignonscheiben, Tomatenmark und Paprikapulver zugeben und dünsten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe zugeben und einkochen, Garkörbchen statt Messbecher aufsetzen.', '3 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Schmand, Senf und Fleisch zugeben und erwärmen.', '1 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen.', '', '', '', ''],
        ['Rest mit Salz und Pfeffer abschmecken und mit Petersilie über den Nudeln servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fleischstreifen sehr fein schneiden oder mit Nudeln und Sauce pürieren, Pilze klein hacken; Brühe salzfrei verwenden. Kleinkind (1–3 J.): Fleisch in kleine Stücke, Nudeln mit milder Sauce, Senf nur wenig.',
    baby: 1,
  },
  {
    id: 'shepherds-pie-linsen-hack',
    n: "Shepherd's Pie mit Linsen & Hack",
    img: { wiki: "Shepherd's pie", q: 'shepherds pie lentils beef mashed potato' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 60, d: 2,
    st: ['comfort', 'mealprep', 'kinderliebling'],
    i: [['rinderhack', 110], ['linsen_dose', 100], ['kartoffel', 250], ['karotte', 60], ['erbsen', 30], ['zwiebel', 40], ['tomatenmark', 15], ['gemuesebruehe', 100], ['milch', 50], ['butter', 6], ['cheddar', 10], ['rapsoel', 5], ['gewuerze', 2], ['salz', 0.5]],
    s: [
      'Kartoffeln schälen und in Wasser 20 Min. weich kochen. Ofen auf 200 °C Ober-/Unterhitze vorheizen.',
      'Zwiebel und Karotte fein würfeln. Öl erhitzen, Hack 5 Min. krümelig braten, Zwiebel und Karotte 4 Min. mitbraten, Tomatenmark 1 Min. anrösten.',
      'Brühe, Linsen, Erbsen, Thymian und Rosmarin zugeben und 10 Min. sämig einkochen.',
      'Kartoffeln mit warmer Milch und Butter zu Püree stampfen. Kinderportion von Füllung und Püree vor dem Salzen abnehmen und in eine kleine Form geben.',
      'Füllung in eine Auflaufform geben, Püree darauf verstreichen, mit einer Gabel Rillen ziehen und mit Cheddar bestreuen. 20 Min. backen, bis die Oberfläche goldbraun ist.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Püree und Füllung im Thermomix, anschließend im Ofen überbacken.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Kartoffelstücke im Garkörbchen einhängen und garen. Ofen auf 200 °C vorheizen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
        ['Wasser abgießen, Kartoffeln mit warmer Milch und Butter in den Mixtopf geben, Rühraufsatz einsetzen und pürieren, umfüllen.', '20 Sek.', '', 'Stufe 3', ''],
        ['Zwiebel und Karotte in Stücken in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hack zugeben und krümelig garen, dabei mit dem Spatel auflockern.', '7 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomatenmark, Brühe, Linsen, Erbsen, Thymian und Rosmarin zugeben, Garkörbchen statt Messbecher aufsetzen und sämig einkochen.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Kinderportion von Füllung und Püree vor dem Salzen abnehmen und in eine kleine Form geben.', '', '', '', ''],
        ['Rest salzen, Füllung in die Auflaufform geben, Püree darauf verstreichen, mit Cheddar bestreuen und 20 Min. goldbraun backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Kinderform mit Brühe ohne Salz zubereiten, Erbsen zerdrücken, alles zu einem groben Brei mischen. Kleinkind (1–3 J.): ein Stück Pie lauwarm servieren, Erbsen leicht angedrückt, wenig Käse.',
    baby: 2,
  },
  {
    id: 'beeren-bananen-protein-smoothie',
    n: 'Beeren-Bananen-Protein-Smoothie',
    img: { wiki: 'Smoothie', q: 'berry banana protein smoothie' },
    cu: 'international',
    m: ['snack'],
    t: 5, d: 1,
    st: ['kinderliebling'],
    i: [['banane', 60], ['beeren_tk', 100], ['skyr', 150], ['milch', 150], ['haferflocken', 10]],
    s: [
      'Banane schälen und in Stücke brechen.',
      'Banane, gefrorene Beeren, Skyr, Milch und Haferflocken in den Mixer geben.',
      'Auf höchster Stufe 45–60 Sek. cremig mixen, bei Bedarf mit etwas mehr Milch verdünnen.',
      'Sofort in Gläser füllen und servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Gläser.',
      steps: [
        ['Banane in Stücken, gefrorene Beeren, Skyr, Milch und Haferflocken in den Mixtopf geben.', '', '', '', ''],
        ['Cremig mixen.', '1 Min.', '', 'Stufe 10', ''],
        ['Bei Bedarf etwas Milch zugeben und nochmals mixen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Sofort in Gläser füllen und servieren (Baby-Portion mit mehr Skyr/Haferflocken dicker lassen).', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Smoothie dicker lassen (mehr Skyr/Haferflocken) und vom Löffel als Beerenbrei geben – Milch als Getränk erst ab 1 Jahr, im Brei in kleinen Mengen in Ordnung. Kleinkind (1–3 J.): im offenen Becher oder mit Strohhalm, kleine Portion.',
    baby: 2,
  },
  {
    id: 'frozen-joghurt-bark-beeren',
    n: 'Frozen-Joghurt-Bark mit Beeren',
    img: { wiki: 'Frozen yogurt', q: 'frozen yogurt bark berries chocolate' },
    cu: 'amerikanisch',
    m: ['snack'],
    t: 10, d: 1,
    st: ['kinderliebling', 'mealprep'],
    i: [['griech_joghurt', 200], ['heidelbeeren', 40], ['erdbeeren', 40], ['ahornsirup', 8], ['zartbitter', 10]],
    s: [
      'Ein kleines Blech oder eine Form mit Backpapier auslegen.',
      'Joghurt mit Ahornsirup glatt rühren (Baby-Anteil vorher ohne Sirup abnehmen) und etwa 1 cm dick auf dem Papier verstreichen.',
      'Erdbeeren klein schneiden, mit den Heidelbeeren auf dem Joghurt verteilen und leicht andrücken. Zartbitterschokolade hacken und darüberstreuen.',
      'Mindestens 3 Std. einfrieren, dann in Stücke brechen und 5 Min. antauen lassen, bevor sie serviert werden.',
    ],
    tm: {
      fit: 0,
      note: 'Thermomix nur zum Hacken der Schokolade und Verrühren des Joghurts.',
      steps: [
        ['Ein Blech mit Backpapier auslegen.', '', '', '', ''],
        ['Zartbitterschokolade in Stücken in den Mixtopf geben und hacken, umfüllen.', '4 Sek.', '', 'Stufe 7', ''],
        ['Baby-Anteil Joghurt ohne Sirup abnehmen. Restlichen Joghurt mit Ahornsirup in den Mixtopf geben und glatt rühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Joghurt 1 cm dick auf dem Papier verstreichen, Beeren und Schokolade darauf verteilen.', '', '', '', ''],
        ['Mindestens 3 Std. einfrieren, in Stücke brechen und 5 Min. antauen lassen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ohne Sirup und Schokolade, Heidelbeeren zerdrückt – angetaut als kühlender Snack beim Zahnen, gefrorene Stücke nur unter Aufsicht. Kleinkind (1–3 J.): Heidelbeeren halbieren, kleine angetaute Stücke, Schokolade sparsam.',
    baby: 1,
  },
  {
    id: 'reiswaffeln-huettenkaese-gurke',
    n: 'Reiswaffeln mit Hüttenkäse & Gurke',
    img: { wiki: 'Rice cake', q: 'rice cakes cottage cheese cucumber' },
    cu: 'international',
    m: ['snack'],
    t: 5, d: 1,
    i: [['reiswaffeln', 24], ['huettenkaese', 150], ['gurke', 80], ['kraeuter', 3], ['gewuerze', 1]],
    s: [
      'Gurke in dünne Scheiben schneiden, Schnittlauch oder Dill fein hacken.',
      'Hüttenkäse auf den Reiswaffeln verteilen.',
      'Mit Gurkenscheiben belegen, mit Kräutern und etwas Pfeffer bestreuen.',
      'Sofort servieren, damit die Waffeln knusprig bleiben.',
    ],
    tm: {
      fit: 0,
      note: 'Thermomix nur für den Kräuter-Hüttenkäse.',
      steps: [
        ['Schnittlauch oder Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Hüttenkäse zugeben und vermischen.', '5 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Gurke in dünne Scheiben schneiden.', '', '', '', ''],
        ['Kräuter-Hüttenkäse auf den Reiswaffeln verteilen, mit Gurke belegen, pfeffern und sofort servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Baby-Reiswaffel dünn mit wenig Hüttenkäse bestreichen (salzhaltig, daher kleine Menge), Gurke als geschälter Stick dazu. Kleinkind (1–3 J.): Waffel in Stücke brechen, Gurke in Stiften, ohne Pfeffer.',
    baby: 1,
  },
  {
    id: 'gemuese-kaese-muffins',
    n: 'Gemüse-Käse-Muffins',
    img: { file: 'Vegetable Muffin (1).jpg', wiki: 'Muffin', q: 'savory vegetable cheese egg muffins' },
    cu: 'international',
    m: ['snack'],
    t: 30, d: 1,
    st: ['mealprep', 'kinderliebling'],
    i: [['ei', 90], ['huettenkaese', 40], ['gouda_light', 25], ['paprika', 40], ['zucchini', 40], ['spinat', 20], ['mehl', 15], ['kraeuter', 2]],
    s: [
      'Ofen auf 180 °C Umluft vorheizen und ein Muffinblech einfetten oder mit Papierförmchen auslegen.',
      'Paprika und Zucchini sehr fein würfeln, Spinat und Kräuter hacken.',
      'Eier mit Hüttenkäse und Mehl verquirlen, Gemüse und den Großteil des Käses unterheben (kein zusätzliches Salz nötig).',
      'Masse zu 2/3 in die Mulden füllen, restlichen Käse darüberstreuen.',
      '18–20 Min. backen, bis die Muffins aufgegangen und in der Mitte fest sind. 5 Min. abkühlen lassen und aus der Form lösen.',
    ],
    tm: {
      fit: 1,
      note: 'Für 12 Muffins. Teig im Thermomix, Backen im Ofen.',
      steps: [
        ['Ofen auf 180 °C Umluft vorheizen, Muffinblech vorbereiten.', '', '', '', ''],
        ['Gouda in Stücken in den Mixtopf geben und reiben, umfüllen.', '8 Sek.', '', 'Stufe 8', ''],
        ['Paprika, Zucchini, Spinat und Kräuter in den Mixtopf geben und fein zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Eier, Hüttenkäse, Mehl und den Großteil des Käses zugeben und verrühren.', '15 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Masse zu 2/3 in die Mulden füllen, restlichen Käse darüberstreuen und 18–20 Min. backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Muffins ohne Salz sind ideales BLW-Fingerfood – halbieren, Ei muss vollständig durchgegart sein. Kleinkind (1–3 J.): ganzer Mini-Muffin als Snack, gut für unterwegs und zum Einfrieren.',
    baby: 2,
  },
]);
