// Fisch & Meeresfrüchte: Lachs, Kabeljau, Seelachs, Forelle, Zander, Dorade, Thunfisch und Garnelen
Object.assign(ING, {
  fisch_thunfisch: { n: 'Thunfischsteak (frisch/TK)', k: 110, p: 24, c: 0, f: 1, fi: 0, su: 0, sa: 0.1, pr: 35, cat: 'fleisch', fl: 'XAF', b: 'm' },
});
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  /* ---------- Kabeljau ---------- */
  {
    id: 'kabeljau-senfsauce-kartoffeln',
    n: 'Kabeljau in Senfsauce mit Salzkartoffeln',
    ck: 'Fisch in Senfsauce',
    img: { q: 'cod fillet mustard sauce potatoes dill' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['comfort'],
    i: [['kabeljau', 180], ['kartoffel', 250], ['erbsen', 60], ['senf', 15], ['milch', 100], ['gemuesebruehe', 80], ['speisestaerke', 8], ['butter', 5], ['kraeuter', 5], ['salz', 1]],
    s: [
      'Kartoffeln schälen, vierteln und in Salzwasser 20 Min. garen. Die Erbsen in den letzten 4 Min. zugeben.',
      'Kabeljau trocken tupfen und in 4 cm große Stücke schneiden.',
      'Milch und Brühe in einer Pfanne aufkochen, Speisestärke mit wenig Wasser glatt rühren, einrühren und 1 Min. köcheln. Fisch einlegen und zugedeckt bei kleiner Hitze 7–8 Min. gar ziehen lassen.',
      'Baby-/Kleinkind-Portion Fisch und Kartoffeln vor dem Senf entnehmen.',
      'Senf und Butter in die Sauce rühren, mit Salz abschmecken und mit gehacktem Dill und Kartoffeln servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Kartoffeln im Garkörbchen, Fisch und Erbsen im Varoma.',
      steps: [
        ['400 g Milch, 320 g Brühe und Speisestärke in den Mixtopf geben, Garkörbchen mit Kartoffelstücken einhängen.', '', '', '', ''],
        ['Kabeljaustücke und Erbsen in den Varoma legen, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
        ['Varoma und Garkörbchen abnehmen. Baby-/Kleinkind-Portion von Fisch, Kartoffeln und etwas Sauce entnehmen.', '', '', '', ''],
        ['Senf und Butter in die Sauce geben und andicken.', '3 Min.', '90°C', 'Stufe 3', ''],
        ['Dill zugeben, mit Salz abschmecken und mit Fisch, Erbsen und Kartoffeln servieren.', '10 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Kabeljau gründlich auf Gräten prüfen, in großen Flocken als Fingerfood oder mit Kartoffeln und Erbsen und etwas ungesalzener Milchsauce zerdrücken. Kleinkind (1–3 J.): Sauce mit nur wenig Senf, Kartoffeln klein schneiden, Erbsen leicht andrücken.',
    baby: 2,
  },
  {
    id: 'fish-tacos-kabeljau',
    n: 'Fish Tacos mit Kabeljau & Limetten-Krautsalat',
    ck: 'Fisch Tacos',
    img: { wiki: 'Fish taco', q: 'fish tacos cod cabbage slaw lime' },
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling'],
    i: [['kabeljau', 170], ['tortilla_mais', 90], ['weisskohl', 60], ['rote_zwiebel', 20], ['griech_joghurt', 60], ['avocado', 30], ['limette', 15], ['cajun', 3], ['rapsoel', 6], ['kraeuter', 4]],
    s: [
      'Weißkohl und rote Zwiebel sehr fein schneiden, mit der Hälfte des Limettensafts und einer Prise Salz kurz verkneten.',
      'Joghurt mit restlichem Limettensaft und gehacktem Koriander verrühren, Avocado in Scheiben schneiden.',
      'Kabeljau in Streifen schneiden. Eine Baby-Portion ungewürzt beiseitelegen, den Rest mit Cajun-Gewürz bestreuen.',
      'Fisch im Öl bei mittlerer Hitze 2–3 Min. pro Seite braten. Tortillas in einer trockenen Pfanne kurz erwärmen.',
      'Tortillas mit Krautsalat, Fisch, Avocado und Limetten-Joghurt füllen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Thermomix für Krautsalat und gedämpften Fisch, Tortillas in der Pfanne erwärmen.',
      steps: [
        ['Weißkohl und rote Zwiebel in den Mixtopf geben und zerkleinern, mit Limettensaft mischen und umfüllen.', '4 Sek.', '', 'Stufe 4', ''],
        ['Joghurt, restlichen Limettensaft und Koriander in den Mixtopf geben und verrühren, umfüllen.', '10 Sek.', '', 'Stufe 3', ''],
        ['500 g Wasser in den Mixtopf füllen. Kabeljaustreifen auf Backpapier in den Varoma legen (Baby-Portion ungewürzt, Rest mit Cajun bestreut) und garen.', '12 Min.', 'Varoma', 'Stufe 1', ''],
        ['Tortillas in einer trockenen Pfanne kurz erwärmen und mit allen Komponenten füllen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzten Fisch in Flocken, Avocado-Spalten und weiche Tortilla-Streifen als Fingerfood, Joghurt als Dip. Kleinkind (1–3 J.): Taco offen servieren, Kohl sehr fein und mild, Fisch ohne Cajun.',
    baby: 2,
  },
  {
    id: 'gedaempfter-kabeljau-ingwer',
    n: 'Gedämpfter Kabeljau mit Ingwer & Frühlingszwiebeln',
    ck: 'Fisch gedämpft Ingwer',
    img: { q: 'steamed fish ginger scallion cantonese' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['kabeljau', 200], ['reis', 65], ['pak_choi', 150], ['ingwer', 8], ['fruehlingszwiebel', 30], ['sojasauce', 12], ['sesamoel', 4], ['kraeuter', 3]],
    s: [
      'Reis nach Packungsangabe garen. Ingwer in feine Streifen, Frühlingszwiebeln in feine Ringe schneiden, Pak Choi längs halbieren.',
      'Kabeljau auf einen Teller legen, mit der Hälfte des Ingwers belegen und im Dämpfeinsatz über kochendem Wasser 8–10 Min. dämpfen. Pak Choi die letzten 4 Min. mitdämpfen.',
      'Baby-/Kleinkind-Portion Fisch und Pak Choi vor der Sauce entnehmen.',
      'Sesamöl in einem kleinen Topf erhitzen, restlichen Ingwer und Frühlingszwiebeln 30 Sek. darin anschwitzen, Sojasauce zugeben.',
      'Heiße Sauce über den Fisch gießen und mit Koriander und Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Reis im Garkörbchen, Fisch und Pak Choi im Varoma.',
      steps: [
        ['1200 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen.', '', '', '', ''],
        ['Kabeljau mit Ingwerstreifen in den Varoma-Einlegeboden, Pak Choi in den Varoma-Behälter legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Varoma und Garkörbchen abnehmen, Baby-/Kleinkind-Portion ohne Sauce entnehmen. Mixtopf leeren.', '', '', '', ''],
        ['Sesamöl, restlichen Ingwer und Frühlingszwiebeln in den Mixtopf geben und dünsten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Sojasauce zugeben, erwärmen und über den Fisch gießen.', '30 Sek.', '100°C', 'Stufe 1', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesaucten, gedämpften Kabeljau grätenfrei in Flocken mit weichem Reis und Pak-Choi-Stielen anbieten, ideal für BLW. Kleinkind (1–3 J.): nur einen Hauch Sauce, Pak Choi klein schneiden.',
    baby: 2,
  },
  {
    id: 'kabeljau-curry-blumenkohl',
    n: 'Indisches Fischcurry mit Kabeljau & Blumenkohl',
    ck: 'Fischcurry',
    img: { wiki: 'Fish curry', q: 'indian fish curry cod cauliflower rice' },
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['mealprep'],
    i: [['kabeljau', 180], ['blumenkohl', 150], ['tomaten_dose', 150], ['joghurt', 60], ['zwiebel', 40], ['knoblauch', 5], ['ingwer', 6], ['currypulver', 5], ['rapsoel', 7], ['reis', 55], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Reis nach Packungsangabe garen. Zwiebel, Knoblauch und Ingwer fein hacken, Blumenkohl in kleine Röschen teilen.',
      'Zwiebel im Öl 4 Min. goldgelb braten, Knoblauch, Ingwer und Currypulver 1 Min. mitrösten.',
      'Tomaten und Blumenkohl zugeben und zugedeckt 10 Min. köcheln. Kabeljau in Stücken einlegen und 6–7 Min. gar ziehen lassen.',
      'Vom Herd nehmen, Joghurt unterrühren. Baby-Portion vor dem Salzen entnehmen.',
      'Mit Salz abschmecken und mit Koriander und Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Fisch und Blumenkohl im Varoma, Reis im Garkörbchen.',
      steps: [
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Currypulver zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten und 300 g Wasser zugeben, Reis im Garkörbchen einhängen. Blumenkohl und Kabeljau in den Varoma legen, aufsetzen und garen.', '22 Min.', 'Varoma', 'Stufe 1', ''],
        ['Varoma und Garkörbchen abnehmen, Joghurt zur Sauce geben und verrühren.', '20 Sek.', '', 'Stufe 3', ''],
        ['Baby-Portion entnehmen, Rest salzen, Fisch und Blumenkohl in der Sauce mit Reis und Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fisch, weichen Blumenkohl und Reis mit der milden, ungesalzenen Joghurtsauce zerdrücken oder Röschen als Fingerfood. Kleinkind (1–3 J.): Currypulver ist mild, nur nicht nachschärfen; Fisch klein zupfen.',
    baby: 2,
  },
  /* ---------- Seelachs ---------- */
  {
    id: 'norddeutsche-fischsuppe-seelachs',
    n: 'Norddeutsche Fischsuppe mit Seelachs',
    ck: 'Fischsuppe',
    img: { wiki: 'Fish soup', q: 'creamy fish soup potatoes leek dill' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['comfort'],
    i: [['seelachs', 180], ['kartoffel', 180], ['karotte', 60], ['lauch', 60], ['sellerie', 40], ['gemuesebruehe', 350], ['sahne', 40], ['butter', 5], ['zitronensaft', 5], ['kraeuter', 5], ['salz', 1]],
    s: [
      'Kartoffeln und Karotten schälen und würfeln, Lauch in Ringe und Sellerie in Scheiben schneiden.',
      'Gemüse in der Butter 3 Min. andünsten, Brühe angießen und 15 Min. köcheln.',
      'Seelachs in 3 cm große Würfel schneiden, in die Suppe geben und 6 Min. gar ziehen lassen (nicht mehr kochen).',
      'Baby-Portion entnehmen (mit ungesalzenem Wasser statt Brühe gekocht ist ideal). Sahne einrühren.',
      'Mit Zitronensaft und Salz abschmecken und mit reichlich Dill bestreuen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen (Mixtopf gut gefüllt, Fisch im Varoma).',
      steps: [
        ['Butter, Karotten, Lauch und Sellerie in den Mixtopf geben und andünsten.', '3 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Kartoffelwürfel und Brühe zugeben, Seelachswürfel in den Varoma legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Varoma abnehmen, Baby-Portion Gemüse und Fisch entnehmen.', '', '', '', ''],
        ['Sahne, Zitronensaft und Salz zugeben und erwärmen.', '2 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Fisch in Teller verteilen, Suppe darübergeben und mit Dill bestreuen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fisch, Kartoffeln und Karotten aus der Suppe nehmen, grätenfrei zerdrücken oder als weiches Fingerfood; Brühe für Babys salzarm. Kleinkind (1–3 J.): lauwarm mit Löffel, Fisch in Flocken.',
    baby: 1,
  },
  {
    id: 'fischpfanne-seelachs-gemuese-reis',
    n: 'Fischpfanne mit Seelachs, Gemüse & Reis',
    ck: 'Fischpfanne mit Reis',
    img: { q: 'fish rice vegetable skillet pollock' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['kinderliebling'],
    i: [['seelachs', 180], ['reis', 60], ['zucchini', 100], ['mais', 40], ['erbsen', 50], ['zwiebel', 40], ['tomatenmark', 15], ['currypulver', 3], ['rapsoel', 8], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Reis nach Packungsangabe garen. Zwiebel würfeln, Zucchini in kleine Würfel schneiden.',
      'Seelachs in mundgerechte Stücke schneiden und in der Hälfte des Öls 2 Min. pro Seite anbraten, herausnehmen.',
      'Restliches Öl in die Pfanne geben, Zwiebel und Zucchini 4 Min. braten, Tomatenmark und Currypulver 1 Min. mitrösten.',
      'Reis, Mais und Erbsen unterheben, Fisch wieder zugeben und 2 Min. erhitzen. Baby-Portion entnehmen.',
      'Mit Salz abschmecken und mit Petersilie servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Reis und Fisch im Thermomix, Gemüse zum Schluss in der Pfanne mischen.',
      steps: [
        ['1200 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen.', '', '', '', ''],
        ['Seelachs in den Varoma-Einlegeboden, Zucchini, Mais und Erbsen in den Varoma-Behälter legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Zwiebel im Öl in einer großen Pfanne anbraten, Tomatenmark und Curry kurz mitrösten.', '', '', '', ''],
        ['Reis, Gemüse und Fisch zugeben und vorsichtig mischen. Baby-Portion entnehmen, Rest salzen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fischstücke, Reis und weiche Zucchini ungesalzen zerdrücken oder Fisch als Fingerfood; Mais und Erbsen andrücken. Kleinkind (1–3 J.): wie die Großen, nur wenig Salz.',
    baby: 2,
  },
  {
    id: 'fischfrikadellen-kartoffel-gurkensalat',
    n: 'Fischfrikadellen mit Kartoffel-Gurken-Salat',
    ck: 'Fischfrikadellen',
    img: { wiki: 'Fishcake', q: 'fish cakes potato cucumber salad' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['kinderliebling', 'mealprep'],
    i: [['seelachs', 170], ['ei', 30], ['paniermehl', 15], ['zwiebel', 25], ['senf', 5], ['kraeuter', 5], ['rapsoel', 8], ['kartoffel', 220], ['gurke', 100], ['joghurt', 40], ['essig', 10], ['salz', 1.5]],
    s: [
      'Kartoffeln in der Schale 20 Min. kochen, pellen, in Scheiben schneiden und mit Essig, Joghurt und dünnen Gurkenscheiben mischen.',
      'Seelachs (aufgetaut, gut trocken getupft) fein hacken, mit Ei, Paniermehl, fein gewürfelter Zwiebel und Dill mischen.',
      'Für Baby/Kleinkind 2 kleine Frikadellen ohne Senf und Salz abnehmen, restliche Masse mit Senf und Salz würzen.',
      'Mit nassen Händen kleine Frikadellen formen und im Öl bei mittlerer Hitze 4 Min. pro Seite goldbraun braten.',
      'Salat salzen und mit den Frikadellen servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Masse im Thermomix, Braten in der Pfanne.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Kartoffeln in den Varoma legen, aufsetzen und garen.', '30 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren. Zwiebel und Dill in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 6', ''],
        ['Seelachs in Stücken, Ei und Paniermehl zugeben und zu einer Masse verarbeiten.', '10 Sek.', '', 'Stufe 4', ''],
        ['Baby-Portion abnehmen, Senf und Salz zur restlichen Masse geben und unterrühren.', '5 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Frikadellen formen und in der Pfanne braten. Kartoffeln pellen und mit Gurke, Joghurt und Essig anmachen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Mini-Frikadellen als weiches Fingerfood, Kartoffel- und geschälte Gurkenstücke dazu. Kleinkind (1–3 J.): Frikadellen halbieren, Salat mit wenig Essig.',
    baby: 2,
  },
  {
    id: 'schlemmerfilet-seelachs-selbstgemacht',
    n: 'Schlemmerfilet selbstgemacht mit Reis & Salat',
    ck: 'Schlemmerfilet',
    img: { q: 'baked fish fillet cheese herb crust tomato' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['kinderliebling'],
    i: [['seelachs', 180], ['tomate', 80], ['frischkaese_light', 20], ['gouda_light', 20], ['paniermehl', 12], ['kraeuter', 4], ['reis', 55], ['salat', 60], ['olivenoel', 5], ['essig', 5], ['salz', 1]],
    s: [
      'Backofen auf 200 °C vorheizen, Reis nach Packungsangabe garen.',
      'Seelachs in eine Auflaufform legen, mit Tomatenscheiben belegen. Baby-Portion ungesalzen, Rest leicht salzen.',
      'Frischkäse, Gouda, Paniermehl und gehackte Kräuter verkneten und als Kruste auf dem Fisch verteilen.',
      'Im Ofen 20–25 Min. backen, bis die Kruste goldbraun ist.',
      'Salat mit Öl und Essig anmachen und mit Reis und Fisch servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Kruste und Reis im Thermomix, Backen im Ofen.',
      steps: [
        ['Kräuter in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Frischkäse, Gouda und Paniermehl zugeben und zur Kruste vermischen, umfüllen.', '10 Sek.', '', 'Stufe 4', ''],
        ['Fisch mit Tomaten und Kruste belegen und bei 200 °C 20–25 Min. im Ofen backen.', '', '', '', ''],
        ['1200 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen.', '20 Min.', '100°C', 'Stufe 4', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fisch mit wenig Kruste in Flocken, Reis als Bällchen geformt, Tomate geschält. Kleinkind (1–3 J.): wie die Großen, Salat in kleinen Stücken.',
    baby: 2,
  },
  {
    id: 'moqueca-seelachs-kokos',
    n: 'Moqueca – brasilianischer Fischtopf mit Kokos',
    ck: 'Fischeintopf Kokosmilch',
    img: { wiki: 'Moqueca', q: 'moqueca brazilian fish stew coconut' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    i: [['seelachs', 180], ['kokosmilch_light', 100], ['paprika', 100], ['tomate', 100], ['zwiebel', 40], ['knoblauch', 4], ['limette', 15], ['gewuerze', 2], ['rapsoel', 5], ['reis', 55], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Seelachs in große Stücke schneiden und mit Limettensaft beträufeln. Reis nach Packungsangabe garen.',
      'Zwiebel, Paprika und Tomaten in Streifen bzw. Scheiben schneiden, Knoblauch hacken.',
      'Öl in einem breiten Topf erhitzen, Zwiebel, Knoblauch und Paprika 4 Min. andünsten, Paprikapulver zugeben.',
      'Tomaten und Fisch einschichten, Kokosmilch angießen und zugedeckt 12 Min. leise köcheln. Baby-Portion entnehmen.',
      'Mit Salz abschmecken, mit Koriander bestreuen und mit Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Fisch im Varoma, Reis im Garkörbchen.',
      steps: [
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Paprikastreifen zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomaten, Kokosmilch, Gewürze und 300 g Wasser zugeben, Reis im Garkörbchen einhängen, Fisch in den Varoma legen, aufsetzen und garen.', '22 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen, Sauce salzen, Fisch einlegen und mit Koriander und Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fisch, Paprika und Reis in der milden Kokossauce ungesalzen zerdrücken oder Fischflocken als Fingerfood. Kleinkind (1–3 J.): Paprikahaut ggf. entfernen, Fisch zerteilen.',
    baby: 2,
  },
  {
    id: 'fischgulasch-seelachs-paprika',
    n: 'Fischgulasch mit Seelachs & Paprika',
    ck: 'Fischgulasch',
    img: { q: 'fish goulash paprika stew potatoes' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['seelachs', 180], ['paprika', 150], ['zwiebel', 50], ['tomatenmark', 15], ['passierte_tomaten', 150], ['gewuerze', 3], ['rapsoel', 7], ['kartoffel', 200], ['schmand_light', 30], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Kartoffeln schälen, würfeln und in Salzwasser 15 Min. garen. Zwiebel und Paprika würfeln.',
      'Zwiebel im Öl 4 Min. anbraten, Paprika 3 Min. mitbraten, Tomatenmark und Paprikapulver 1 Min. anrösten.',
      'Passierte Tomaten und 100 ml Wasser zugeben und 10 Min. köcheln.',
      'Seelachs in Würfeln einlegen und zugedeckt 6–8 Min. gar ziehen lassen. Baby-Portion entnehmen.',
      'Mit Salz abschmecken, mit einem Klecks Schmand und Petersilie zu den Kartoffeln servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Fisch im Varoma, Kartoffeln im Garkörbchen.',
      steps: [
        ['Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl, Paprikawürfel, Tomatenmark und Paprikapulver zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Passierte Tomaten und 300 g Wasser zugeben, Kartoffeln im Garkörbchen einhängen, Fisch in den Varoma legen, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen, Sauce salzen, Fisch unterheben und mit Schmand und Petersilie servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fisch, Kartoffeln und weiche Paprika ungesalzen zerdrücken. Kleinkind (1–3 J.): mit edelsüßem Paprika mild würzen, Schmand macht es cremig.',
    baby: 2,
  },
  /* ---------- Lachs ---------- */
  {
    id: 'lachs-kraeuterkruste-ofengemuese',
    n: 'Lachs mit Kräuterkruste & Ofengemüse',
    ck: 'Lachs mit Kräuterkruste',
    img: { q: 'salmon herb crust roasted vegetables' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    i: [['lachs', 130], ['paniermehl', 15], ['kraeuter', 6], ['senf', 10], ['zucchini', 150], ['paprika', 150], ['rote_zwiebel', 50], ['olivenoel', 7], ['quinoa', 35], ['zitronensaft', 8], ['salz', 1]],
    s: [
      'Backofen auf 200 °C vorheizen. Zucchini, Paprika und rote Zwiebel grob würfeln, mit der Hälfte des Öls mischen und 15 Min. backen.',
      'Quinoa gründlich waschen und in der doppelten Menge Wasser 15 Min. garen.',
      'Kräuter fein hacken und mit Paniermehl, restlichem Öl und Zitronensaft mischen. Lachs mit Senf bestreichen (Baby-Stück ohne Senf), Kruste andrücken.',
      'Lachs auf das Gemüse legen und alles weitere 12–15 Min. backen.',
      'Gemüse salzen und mit Quinoa und Lachs servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Kruste und Quinoa im Thermomix, Lachs und Gemüse im Ofen.',
      steps: [
        ['Kräuter in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Paniermehl, Öl und Zitronensaft zugeben und mischen, umfüllen.', '5 Sek.', '', 'Stufe 4', ''],
        ['1000 g Wasser in den Mixtopf füllen, gewaschene Quinoa im Garkörbchen einhängen und garen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Lachs mit Senf und Kruste belegen und mit dem Gemüse im Ofen bei 200 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Lachs ohne Senf und Kruste grätenfrei zerpflücken, weiches Ofengemüse als Fingerfood, Quinoa zum Löffeln. Kleinkind (1–3 J.): Kruste ist knusprig und beliebt, Gemüse klein schneiden.',
    baby: 2,
  },
  {
    id: 'lachs-quinoa-salat-avocado',
    n: 'Lachs-Quinoa-Salat mit Avocado & Rucola',
    ck: 'Quinoasalat mit Lachs',
    img: { q: 'salmon quinoa salad avocado arugula' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['mealprep'],
    i: [['lachs', 130], ['quinoa', 45], ['gurke', 100], ['kirschtomaten', 80], ['rucola', 30], ['avocado', 30], ['zitronensaft', 10], ['olivenoel', 5], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Quinoa waschen und in der doppelten Menge Wasser 15 Min. garen, abkühlen lassen.',
      'Lachs ohne Fett in einer beschichteten Pfanne 4 Min. auf der Hautseite und 2 Min. auf der anderen Seite braten, in Stücke zupfen.',
      'Gurke würfeln, Kirschtomaten halbieren, Avocado würfeln.',
      'Zitronensaft, Öl, Kräuter und Salz verrühren (Baby-Portion vorher ohne Dressing beiseitestellen) und mit Quinoa und Gemüse mischen.',
      'Rucola unterheben und Lachs darauf verteilen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Quinoa und Lachs im Thermomix, Salat von Hand.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, gewaschene Quinoa im Garkörbchen einhängen. Lachs in den Varoma legen, aufsetzen und garen.', '18 Min.', 'Varoma', 'Stufe 4', ''],
        ['Quinoa abkühlen lassen, Lachs zerpflücken. Mixtopf leeren.', '', '', '', ''],
        ['Kräuter, Zitronensaft, Öl und Salz in den Mixtopf geben und zum Dressing mixen.', '10 Sek.', '', 'Stufe 7', ''],
        ['Gemüse schneiden, mit Quinoa, Dressing und Rucola mischen und Lachs darauf verteilen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Lachsflocken, Quinoa, Avocado-Spalten und geschälte Gurkensticks ohne Dressing; Kirschtomaten nur geviertelt. Kleinkind (1–3 J.): Rucola weglassen oder fein schneiden.',
    baby: 2,
  },
  {
    id: 'lachsfrikadellen-skyr-dip',
    n: 'Lachsfrikadellen mit Gurken-Skyr-Dip & Kartoffeln',
    ck: 'Lachsfrikadellen',
    img: { wiki: 'Fishcake', q: 'salmon patties cucumber dip potatoes' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    st: ['kinderliebling'],
    i: [['lachs', 120], ['ei', 30], ['haferflocken', 15], ['kraeuter', 5], ['senf', 5], ['rapsoel', 7], ['kartoffel', 150], ['skyr', 100], ['gurke', 150], ['zitronensaft', 5], ['salz', 1]],
    s: [
      'Kartoffeln in Spalten schneiden und in Salzwasser 15 Min. garen (Baby-Portion vorher ungesalzen garen).',
      'Lachs ohne Haut fein hacken, mit Ei, Haferflocken und der Hälfte des Dills mischen, 10 Min. quellen lassen.',
      'Baby-Frikadellen ohne Senf und Salz abnehmen, Rest mit Senf und Salz würzen und kleine Frikadellen formen.',
      'Im Öl bei mittlerer Hitze 3–4 Min. pro Seite braten.',
      'Gurke raspeln, gut ausdrücken und mit Skyr, restlichem Dill und Zitronensaft verrühren. Zu Frikadellen und Kartoffeln servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Masse und Dip im Thermomix, Braten in der Pfanne.',
      steps: [
        ['Dill in den Mixtopf geben und zerkleinern, die Hälfte entnehmen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Lachs in Stücken, Ei und Haferflocken zugeben und zu einer Masse verarbeiten.', '8 Sek.', '', 'Stufe 4', ''],
        ['Baby-Portion abnehmen, Senf und Salz zugeben und unterrühren, umfüllen.', '5 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Frikadellen formen und in der Pfanne braten. Kartoffeln im Varoma oder Topf garen.', '', '', '', ''],
        ['Geraspelte Gurke, Skyr, restlichen Dill und Zitronensaft im Mixtopf verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Mini-Frikadellen und Kartoffelspalten als BLW-Fingerfood, Skyr-Dip ohne Salz. Kleinkind (1–3 J.): Frikadellen halbieren und dippen lassen.',
    baby: 2,
  },
  /* ---------- Forelle ---------- */
  {
    id: 'forelle-muellerin-glutenfrei',
    n: 'Forelle Müllerin (glutenfrei)',
    ck: 'Forelle Müllerin',
    img: { q: 'trout meuniere butter lemon parsley potatoes' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 30, d: 2,
    i: [['forelle', 200], ['mehl_gf', 10], ['butter', 10], ['zitronensaft', 10], ['kraeuter', 5], ['kartoffel', 250], ['salat', 60], ['essig', 5], ['salz', 1]],
    s: [
      'Kartoffeln schälen und in Salzwasser 20 Min. garen (Baby-Portion separat ohne Salz).',
      'Forellenfilets trocken tupfen und in glutenfreiem Mehl wenden, überschüssiges Mehl abklopfen.',
      'Die Hälfte der Butter in einer Pfanne aufschäumen, Filets auf der Hautseite 3 Min., dann 1–2 Min. auf der Fleischseite braten. Baby-Stück entnehmen, Rest salzen.',
      'Restliche Butter in die Pfanne geben, leicht bräunen, Zitronensaft und gehackte Petersilie zugeben und über die Forelle löffeln.',
      'Mit Petersilienkartoffeln und mit Essig angemachtem Blattsalat servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Kartoffeln im Thermomix, die Forelle wird klassisch in der Pfanne gebraten.',
      steps: [
        ['Petersilie in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['1000 g Wasser in den Mixtopf füllen, Kartoffeln im Garkörbchen einhängen und garen.', '25 Min.', 'Varoma', 'Stufe 4', ''],
        ['Forelle mehlieren und in der Pfanne in Butter braten, Baby-Stück ungesalzen entnehmen.', '', '', '', ''],
        ['Nussbutter mit Zitronensaft und Petersilie in der Pfanne herstellen und über Fisch und Kartoffeln geben.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Forelle sehr gründlich auf Gräten prüfen, ungesalzen in Flocken mit zerdrückten Kartoffeln. Kleinkind (1–3 J.): Fisch zerteilen, Kartoffeln mit etwas Petersilienbutter.',
    baby: 2,
  },
  {
    id: 'forelle-mandeln-gruene-bohnen',
    n: 'Forelle mit Mandeln & grünen Bohnen',
    ck: 'Forelle mit Mandeln',
    img: { q: 'trout amandine almonds green beans' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['forelle', 180], ['mandeln', 10], ['gruene_bohnen', 150], ['kartoffel', 200], ['butter', 6], ['zitronensaft', 8], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Kartoffeln schälen, halbieren und 20 Min. garen. Grüne Bohnen in den letzten 8 Min. mitgaren.',
      'Mandeln grob hacken und in einer trockenen Pfanne goldbraun rösten, herausnehmen.',
      'Butter in der Pfanne schmelzen, Forelle auf der Hautseite 3 Min. und auf der Fleischseite 1–2 Min. braten. Baby-Stück entnehmen.',
      'Mandeln, Zitronensaft und Petersilie zugeben und kurz schwenken, salzen.',
      'Forelle mit Mandelbutter, Bohnen und Kartoffeln servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Forelle im Varoma gedämpft, Mandeln im Mixtopf geröstet.',
      steps: [
        ['Mandeln in den Mixtopf geben und grob hacken, dann rösten und umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
        ['Mandeln ohne Messbecher rösten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['1000 g Wasser einfüllen, Kartoffeln im Garkörbchen einhängen, Bohnen in den Varoma-Behälter, Forelle in den Einlegeboden legen, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 4', ''],
        ['Baby-Portion entnehmen. Mixtopf leeren, Butter, Zitronensaft und Petersilie schmelzen.', '2 Min.', '80°C', 'Stufe 1', ''],
        ['Mandeln unterrühren, salzen und über Fisch und Gemüse geben.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Mandeln nur fein gemahlen (keine Stücke!), Forelle grätenfrei, Bohnen weich als Fingerfood. Kleinkind (1–3 J.): Mandeln gemahlen oder weglassen, Bohnen halbieren.',
    baby: 1,
  },
  {
    id: 'forelle-lauwarmer-kartoffelsalat-radieschen',
    n: 'Gebratene Forelle auf lauwarmem Kartoffelsalat mit Radieschen',
    ck: 'Kartoffelsalat mit Forelle',
    img: { q: 'trout fillet warm potato salad radish' },
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    i: [['forelle', 170], ['kartoffel', 220], ['radieschen', 80], ['gurke', 80], ['skyr', 60], ['senf', 8], ['essig', 8], ['rapsoel', 5], ['kraeuter', 5], ['salz', 1]],
    s: [
      'Kartoffeln in der Schale 20 Min. garen, pellen und noch warm in Scheiben schneiden.',
      'Skyr, Senf, Essig und Schnittlauch verrühren. Baby-Kartoffeln ohne Dressing beiseitelegen.',
      'Radieschen und Gurke in dünne Scheiben schneiden und mit Kartoffeln und Dressing mischen, salzen.',
      'Forelle im Öl auf der Hautseite 3 Min. knusprig braten, wenden und 1 Min. fertig garen.',
      'Forelle auf dem lauwarmen Salat anrichten.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Kartoffeln und Forelle im Varoma, Dressing im Mixtopf.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Kartoffeln in den Varoma-Behälter, Forelle in den Einlegeboden legen, aufsetzen und garen.', '30 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren. Schnittlauch zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Skyr, Senf, Essig und Salz zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Baby-Portion entnehmen, Kartoffeln pellen und mit Radieschen, Gurke und Dressing mischen, Forelle darauf anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Kartoffelstücke und Forelle ohne Dressing als Fingerfood, Radieschen weglassen. Kleinkind (1–3 J.): Radieschen in feine Stifte, Dressing mild.',
    baby: 2,
  },
  {
    id: 'forelle-rote-bete-quinoa-bowl',
    n: 'Forellen-Bowl mit Rote Bete, Quinoa & Feta',
    ck: 'Quinoa Bowl Rote Bete',
    img: { wiki: 'Buddha bowl', q: 'trout beetroot quinoa bowl feta walnuts' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['mealprep'],
    i: [['forelle', 170], ['quinoa', 45], ['rote_bete', 80], ['rucola', 30], ['feta', 20], ['walnuesse', 8], ['zitronensaft', 10], ['olivenoel', 5], ['salz', 0.5]],
    s: [
      'Quinoa waschen und in der doppelten Menge Wasser 15 Min. garen.',
      'Forelle auf der Hautseite in einer beschichteten Pfanne 3–4 Min. braten, wenden und 1 Min. fertig garen, in Stücke teilen.',
      'Rote Bete in Würfel schneiden, Walnüsse grob hacken, Feta zerbröseln.',
      'Zitronensaft, Öl und Salz verrühren. Baby-Portion vor Dressing und Feta abnehmen.',
      'Quinoa, Rucola, Rote Bete und Forelle in Schalen anrichten, mit Feta, Walnüssen und Dressing toppen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Quinoa und Forelle im Thermomix, Bowl von Hand anrichten.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Quinoa im Garkörbchen einhängen, Forelle in den Varoma legen, aufsetzen und garen.', '18 Min.', 'Varoma', 'Stufe 4', ''],
        ['Mixtopf leeren. Walnüsse grob hacken, umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
        ['Zitronensaft, Öl und Salz im Mixtopf verrühren.', '5 Sek.', '', 'Stufe 3', ''],
        ['Baby-Portion entnehmen und alle Komponenten in Bowls anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Forelle grätenfrei, Quinoa und weiche Rote-Bete-Würfel ohne Feta und Nussstücke (Walnüsse höchstens gemahlen). Kleinkind (1–3 J.): wenig Feta, Nüsse gemahlen.',
    baby: 1,
  },
  /* ---------- Zander ---------- */
  {
    id: 'zander-kuerbisrisotto',
    n: 'Gebratener Zander mit Kürbisrisotto',
    ck: 'Kürbisrisotto',
    img: { wiki: 'Risotto', q: 'pumpkin risotto fish fillet' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    i: [['zander', 160], ['risottoreis', 60], ['kuerbis', 150], ['zwiebel', 30], ['gemuesebruehe', 250], ['parmesan', 12], ['olivenoel', 8], ['kraeuter', 3], ['salz', 0.5]],
    s: [
      'Kürbis entkernen und in kleine Würfel schneiden (Hokkaido mit Schale), Zwiebel fein würfeln.',
      'Zwiebel in der Hälfte des Öls glasig dünsten, Reis 1 Min. mitrösten, Kürbis zugeben.',
      'Nach und nach heiße Brühe angießen und unter Rühren 18–20 Min. cremig garen. Baby-Portion vor dem Parmesan entnehmen.',
      'Parmesan unterrühren. Zander im restlichen Öl auf der Hautseite 4 Min. braten, wenden, 1 Min. fertig garen und salzen.',
      'Risotto mit Zander und Salbei oder Petersilie anrichten.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Zander im Varoma oder kurz in der Pfanne.',
      steps: [
        ['Parmesan in den Mixtopf geben und zerkleinern, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Zwiebel zerkleinern, 15 g Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Risottoreis und Kürbiswürfel zugeben und ohne Messbecher dünsten.', '2 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe zugeben, Zander in den Varoma legen, aufsetzen und garen.', '18 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen, Parmesan unterrühren und 2 Min. ruhen lassen.', '20 Sek.', '', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Kürbisrisotto (mit salzarmer Brühe) ohne Parmesan, Zanderflocken untergemischt – perfekt zum Löffeln. Kleinkind (1–3 J.): wenig Parmesan, Fisch klein zupfen.',
    baby: 1,
  },
  {
    id: 'zander-blumenkohlpueree-spinat',
    n: 'Zander mit Blumenkohlpüree & Rahmspinat',
    ck: 'Blumenkohlpüree',
    img: { q: 'fish fillet cauliflower puree spinach' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['zander', 200], ['blumenkohl', 300], ['milch', 50], ['butter', 10], ['parmesan', 10], ['spinat', 100], ['knoblauch', 4], ['gewuerze', 1], ['salz', 1]],
    s: [
      'Blumenkohl in Röschen teilen und in wenig Wasser 12 Min. weich garen, abgießen.',
      'Mit Milch, der Hälfte der Butter und Parmesan fein pürieren. Baby-Portion entnehmen, Rest mit Salz und Muskat abschmecken.',
      'Knoblauch in Scheiben in restlicher Butter andünsten, Spinat zugeben und zusammenfallen lassen.',
      'Zander in einer beschichteten Pfanne auf der Hautseite 4 Min. braten, wenden und 1 Min. fertig garen.',
      'Zander auf Püree und Spinat anrichten.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Blumenkohl und Zander im Varoma.',
      steps: [
        ['Parmesan in den Mixtopf geben und zerkleinern, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['500 g Wasser in den Mixtopf füllen, Blumenkohl in den Varoma-Behälter, Zander in den Einlegeboden legen, aufsetzen und garen.', '22 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren. Blumenkohl, Milch, 20 g Butter und Parmesan in den Mixtopf geben und pürieren.', '30 Sek.', '', 'Stufe 6', ''],
        ['Baby-Portion entnehmen, Rest mit Salz und Muskat würzen und umfüllen.', '', '', '', ''],
        ['Knoblauch und restliche Butter andünsten, Spinat zugeben und garen.', '4 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Blumenkohlpüree ungesalzen mit Zanderflocken und fein gehacktem Spinat. Kleinkind (1–3 J.): wie die Großen, wenig Salz.',
    baby: 2,
  },
  /* ---------- Dorade ---------- */
  {
    id: 'dorade-ofen-fenchel-tomaten',
    n: 'Dorade aus dem Ofen mit Fenchel & Tomaten',
    ck: 'Dorade aus dem Ofen',
    img: { q: 'baked sea bream fennel tomatoes potatoes' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    i: [['dorade', 200], ['fenchel', 150], ['kirschtomaten', 100], ['oliven', 15], ['kartoffel', 200], ['olivenoel', 10], ['zitronensaft', 10], ['knoblauch', 4], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Backofen auf 200 °C vorheizen. Kartoffeln in Spalten, Fenchel in dünne Spalten schneiden, Knoblauch andrücken.',
      'Kartoffeln, Fenchel und Knoblauch mit dem Öl auf einem Blech mischen und 20 Min. backen.',
      'Kirschtomaten, Oliven und Doradenfilets dazulegen, mit Zitronensaft beträufeln. Baby-Stück ohne Salz, Rest salzen.',
      'Weitere 12–15 Min. backen, bis der Fisch gar ist.',
      'Mit Fenchelgrün und Petersilie bestreut servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Kartoffeln und Fenchel im Varoma vorgaren, Fertiggaren im Ofen.',
      steps: [
        ['800 g Wasser in den Mixtopf füllen, Kartoffeln und Fenchel in den Varoma legen, aufsetzen und vorgaren.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Gemüse mit Öl und Knoblauch aufs Blech geben und bei 200 °C 10 Min. rösten.', '', '', '', ''],
        ['Tomaten, Oliven und Dorade dazulegen, Baby-Stück ungesalzen, und 12–15 Min. fertig backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Dorade sehr sorgfältig auf Gräten prüfen, weiche Kartoffel- und Fenchelspalten als Fingerfood, keine Oliven. Kleinkind (1–3 J.): Tomaten vierteln, Oliven klein schneiden.',
    baby: 2,
  },
  {
    id: 'dorade-zitronen-couscous',
    n: 'Dorade mit Zitronen-Couscous & Gemüse',
    ck: 'Couscous mit Fisch',
    img: { q: 'sea bream fillet lemon couscous vegetables' },
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['dorade', 180], ['couscous', 55], ['zucchini', 120], ['paprika', 100], ['zitronensaft', 10], ['olivenoel', 8], ['kraeuter', 5], ['gewuerze', 2], ['salz', 1]],
    s: [
      'Couscous mit der gleichen Menge kochendem Wasser übergießen und 5 Min. quellen lassen (glutenfrei: Quinoa 15 Min. garen).',
      'Zucchini und Paprika würfeln und in der Hälfte des Öls 5 Min. braten, mit Kreuzkümmel würzen.',
      'Couscous auflockern, Gemüse, Zitronensaft, Minze und Petersilie unterheben. Baby-Portion entnehmen, Rest salzen.',
      'Dorade im restlichen Öl auf der Hautseite 3 Min. kross braten, wenden und 1 Min. fertig garen.',
      'Dorade auf dem Zitronen-Couscous anrichten.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Gemüse und Dorade im Varoma, Couscous quillt anschließend in der Garflüssigkeit.',
      steps: [
        ['Kräuter in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['500 g Wasser in den Mixtopf füllen, Gemüse in den Varoma-Behälter, Dorade in den Einlegeboden legen, aufsetzen und garen.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Garflüssigkeit bis auf 220 g abgießen, Couscous, Öl und Gewürze zugeben und quellen lassen.', '5 Min.', '', '', ''],
        ['Gemüse, Zitronensaft und Kräuter zugeben und mischen. Baby-Portion entnehmen, Rest salzen.', '10 Sek.', '', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Couscous mit weichem Gemüse und Doradenflocken ungesalzen, gut zum Löffeln. Kleinkind (1–3 J.): Fisch zerteilen, Gemüse klein schneiden.',
    baby: 2,
  },
  {
    id: 'dorade-mango-salsa-kokosreis',
    n: 'Dorade mit Mango-Salsa & Kokosreis',
    ck: 'Mango Salsa',
    img: { q: 'sea bream mango salsa coconut rice' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['dorade', 180], ['reis', 55], ['kokosmilch_light', 50], ['mango', 60], ['rote_zwiebel', 20], ['chili_frisch', 2], ['limette', 15], ['kraeuter', 4], ['rapsoel', 5], ['salz', 1]],
    s: [
      'Reis mit Kokosmilch und der gleichen Menge Wasser aufkochen und zugedeckt 15 Min. bei kleiner Hitze quellen lassen.',
      'Mango, rote Zwiebel und Koriander fein würfeln und mit Limettensaft mischen. Baby-Portion Mango abnehmen, dann Chili zugeben.',
      'Dorade trocken tupfen und im Öl auf der Hautseite 3 Min. braten, wenden und 1 Min. fertig garen. Baby-Stück entnehmen, Rest salzen.',
      'Dorade auf dem Kokosreis anrichten und mit Mango-Salsa toppen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Kokosreis im Mixtopf, Dorade im Varoma.',
      steps: [
        ['Rote Zwiebel und Koriander in den Mixtopf geben und zerkleinern, mit Mangowürfeln und Limettensaft mischen, umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
        ['Baby-Portion Mango abnehmen, gehackte Chili unter die Salsa rühren.', '', '', '', ''],
        ['Reis, Kokosmilch und 400 g Wasser in den Mixtopf geben, Dorade in den Varoma legen, aufsetzen und garen.', '18 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Baby-Stück entnehmen, Rest salzen und mit Reis und Salsa anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Kokosreis zu Bällchen formen, Doradenflocken und weiche Mangostreifen ohne Chili als Fingerfood. Kleinkind (1–3 J.): Salsa ohne Chili und Zwiebel.',
    baby: 2,
  },
  {
    id: 'ceviche-dorade-suesskartoffel',
    n: 'Ceviche von der Dorade mit Süßkartoffel & Mais',
    ck: 'Ceviche',
    img: { wiki: 'Ceviche', q: 'ceviche sea bream sweet potato corn lime' },
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    i: [['dorade', 200], ['limette', 60], ['rote_zwiebel', 30], ['chili_frisch', 3], ['kraeuter', 6], ['suesskartoffel', 200], ['mais', 50], ['avocado', 30], ['olivenoel', 5], ['salz', 1]],
    s: [
      'Süßkartoffel in dicke Scheiben schneiden und 15 Min. in Wasser garen, abkühlen lassen.',
      'Dorade (unbedingt in Sushi-Qualität, ohne Haut und Gräten) in 1,5 cm große Würfel schneiden und kalt stellen.',
      'Rote Zwiebel in hauchdünne Ringe schneiden, Chili fein hacken, Koriander zupfen.',
      'Fisch mit Limettensaft, Salz, Zwiebel und Chili mischen und 10–15 Min. im Kühlschrank marinieren, bis er außen weiß ist.',
      'Mit Öl, Koriander, Mais, Avocado und Süßkartoffelscheiben sofort servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen. Ceviche ist ein Rohfisch-Gericht – Thermomix nur für Süßkartoffel und Marinade.',
      steps: [
        ['500 g Wasser in den Mixtopf füllen, Süßkartoffelscheiben in den Varoma legen, aufsetzen und garen.', '18 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren, Koriander und Chili zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Limettensaft und Salz zugeben und verrühren.', '5 Sek.', '', 'Stufe 3', ''],
        ['Fischwürfel und Zwiebelringe von Hand mit der Marinade mischen und 10–15 Min. kühl ziehen lassen, dann mit Beilagen anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): kein roher Fisch! Ein Stück Dorade 10 Min. dämpfen und zerpflücken, dazu Süßkartoffel und Avocado als Fingerfood, Mais zerdrückt. Kleinkind (1–3 J.): ebenfalls gegarten Fisch statt Ceviche, ohne Chili.',
    baby: 0,
  },
  {
    id: 'bouillabaisse-light',
    n: 'Bouillabaisse light',
    ck: 'Bouillabaisse',
    img: { wiki: 'Bouillabaisse', q: 'bouillabaisse fish stew saffron fennel' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['comfort'],
    i: [['dorade', 100], ['kabeljau', 80], ['garnelen', 60], ['fenchel', 80], ['tomaten_dose', 150], ['zwiebel', 40], ['knoblauch', 5], ['kartoffel', 120], ['gemuesebruehe', 250], ['olivenoel', 10], ['gewuerze', 2], ['kraeuter', 3], ['sauerteigbrot', 40], ['salz', 1]],
    s: [
      'Zwiebel, Knoblauch und Fenchel fein schneiden, Kartoffeln in 1,5 cm große Würfel schneiden.',
      'Gemüse im Öl 5 Min. andünsten, Safran und Fenchelsamen zugeben, Tomaten, Kartoffeln und Brühe zugießen und 15 Min. köcheln.',
      'Dorade und Kabeljau in große Stücke schneiden, mit den Garnelen in die Suppe geben und 5–6 Min. gar ziehen lassen.',
      'Baby-Portion entnehmen, Rest mit Salz abschmecken.',
      'Mit Petersilie bestreuen und mit geröstetem Brot (glutenfrei möglich) servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Fisch und Garnelen im Varoma, damit sie nicht zerfallen.',
      steps: [
        ['Zwiebel, Knoblauch und Fenchel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Gewürze zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten, Kartoffelwürfel und Brühe zugeben, Fisch und Garnelen in den Varoma legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen, Suppe salzen.', '', '', '', ''],
        ['Fisch und Garnelen in Teller verteilen, Suppe darübergeben, mit Petersilie und Brot servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fisch grätenfrei mit Kartoffeln und Fenchel aus der (salzarm gekochten) Suppe zerdrücken; Garnelen nur gut durchgegart und fein gehackt einführen. Kleinkind (1–3 J.): lauwarm, Brot zum Tunken.',
    baby: 1,
  },
  /* ---------- Thunfisch ---------- */
  {
    id: 'thunfischsteak-weisse-bohnen-rucola',
    n: 'Thunfischsteak mit weißen Bohnen & Rucola',
    ck: 'Thunfischsteak',
    img: { q: 'seared tuna steak white beans arugula' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 20, d: 2,
    i: [['fisch_thunfisch', 170], ['weisse_bohnen', 120], ['kirschtomaten', 100], ['rucola', 30], ['rote_zwiebel', 20], ['olivenoel', 10], ['zitronensaft', 10], ['knoblauch', 4], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Bohnen abspülen. Kirschtomaten halbieren, rote Zwiebel in feine Ringe schneiden, Knoblauch fein hacken.',
      'Bohnen, Tomaten, Zwiebel, Knoblauch, Petersilie, Zitronensaft und die Hälfte des Öls mischen und salzen.',
      'Thunfischsteak trocken tupfen und mit restlichem Öl bestreichen. Grillpfanne sehr heiß werden lassen.',
      'Steak 1–2 Min. pro Seite anbraten (innen rosa). Baby-/Kleinkind-Stück vollständig durchbraten.',
      'Thunfisch in Scheiben schneiden und auf Bohnensalat und Rucola anrichten.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen. Thunfisch wird kurz in der Pfanne gebraten, Thermomix nur fürs Dressing.',
      steps: [
        ['Knoblauch und Petersilie in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Zitronensaft, Öl und Salz zugeben und verrühren.', '5 Sek.', '', 'Stufe 3', ''],
        ['Bohnen, Tomaten und Zwiebel in einer Schüssel mit dem Dressing mischen.', '', '', '', ''],
        ['Thunfisch in einer sehr heißen Pfanne 1–2 Min. pro Seite braten, Baby-Stück durchgaren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Thunfisch nur selten (Quecksilber) und vollständig durchgegart in kleinen Flocken, weiße Bohnen zerdrückt. Kleinkind (1–3 J.): kleine durchgegarte Portion, Tomaten vierteln, Zwiebel weglassen.',
    baby: 1,
  },
  {
    id: 'thunfisch-tataki-gurken-sesam',
    n: 'Thunfisch-Tataki mit Gurken-Sesam-Salat & Reis',
    ck: 'Gurkensalat asiatisch',
    img: { wiki: 'Tataki', q: 'tuna tataki sesame cucumber salad' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 2,
    i: [['fisch_thunfisch', 160], ['sesam', 10], ['sojasauce', 12], ['reis', 60], ['gurke', 150], ['ingwer', 5], ['limette', 15], ['sesamoel', 3], ['fruehlingszwiebel', 15]],
    s: [
      'Reis nach Packungsangabe garen. Gurke in dünne Scheiben schneiden, Ingwer reiben.',
      'Gurke mit Limettensaft, Sesamöl, Ingwer und der Hälfte der Sojasauce mischen.',
      'Thunfisch in Sesam wälzen und in einer sehr heißen Pfanne rundum je 30–45 Sek. anbraten, sodass er innen roh bleibt. Baby-/Kleinkind-Stück komplett durchgaren.',
      'Thunfisch in dünne Scheiben schneiden, mit restlicher Sojasauce beträufeln.',
      'Mit Reis, Gurkensalat und Frühlingszwiebeln servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Reis und Dressing im Thermomix, Thunfisch scharf in der Pfanne anbraten.',
      steps: [
        ['Ingwer in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 8', ''],
        ['Limettensaft, Sesamöl und Sojasauce zugeben und verrühren, umfüllen und mit Gurkenscheiben mischen.', '5 Sek.', '', 'Stufe 3', ''],
        ['1200 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Thunfisch in Sesam wälzen und in der Pfanne kurz rundum anbraten, Baby-Stück durchgaren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): kein rosa Thunfisch – Stück vollständig durchgaren, ohne Sojasauce in kleinen Flocken, selten anbieten; Reisbällchen und geschälte Gurke dazu. Kleinkind (1–3 J.): durchgegart, Sesam fein gemahlen.',
    baby: 1,
  },
  {
    id: 'salade-nicoise-thunfisch',
    n: 'Salade Niçoise mit Thunfisch & Ei',
    ck: 'Salat Nizza',
    img: { wiki: 'Salade niçoise', q: 'salade nicoise tuna egg green beans' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['thunfisch_dose', 120], ['ei', 60], ['kartoffel', 150], ['gruene_bohnen', 100], ['kirschtomaten', 80], ['oliven', 15], ['salat', 60], ['olivenoel', 8], ['essig', 8], ['senf', 5], ['salz', 0.5]],
    s: [
      'Kartoffeln in der Schale 20 Min. garen, pellen und vierteln. Eier 9 Min. hart kochen, abschrecken und vierteln.',
      'Grüne Bohnen 6 Min. in Wasser garen und kalt abschrecken.',
      'Öl, Essig, Senf und Salz zu einer Vinaigrette verrühren.',
      'Salat, Kartoffeln, Bohnen, halbierte Tomaten und Oliven anrichten, Thunfisch und Eier darauf verteilen.',
      'Mit Vinaigrette beträufeln (Kinderportion vorher ohne Dressing abnehmen).',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Kartoffeln, Eier und Bohnen im Varoma, Dressing im Mixtopf.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Kartoffeln und Eier in den Varoma-Behälter, Bohnen in den Einlegeboden legen, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
        ['Eier abschrecken, Kartoffeln pellen. Mixtopf leeren.', '', '', '', ''],
        ['Öl, Essig, Senf und Salz in den Mixtopf geben und emulgieren.', '10 Sek.', '', 'Stufe 4', ''],
        ['Salat mit allen Zutaten anrichten und mit Dressing beträufeln.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Kartoffeln, Bohnen und Eiviertel als Fingerfood, Thunfisch nur selten in kleiner Menge, keine Oliven. Kleinkind (1–3 J.): Tomaten vierteln, Oliven klein schneiden.',
    baby: 1,
  },
  /* ---------- Garnelen ---------- */
  {
    id: 'gambas-al-ajillo-ofenkartoffeln',
    n: 'Gambas al Ajillo mit Ofenkartoffeln & Salat',
    ck: 'Garnelen in Knoblauchöl',
    img: { q: 'gambas al ajillo garlic shrimp potatoes' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    i: [['garnelen', 200], ['olivenoel', 12], ['knoblauch', 7], ['chili_frisch', 2], ['kraeuter', 4], ['kartoffel', 250], ['salat', 60], ['zitronensaft', 8], ['gewuerze', 1], ['salz', 1]],
    s: [
      'Backofen auf 220 °C vorheizen. Kartoffeln in Spalten schneiden, mit 1 TL Öl und Paprikapulver mischen und 30 Min. backen.',
      'Knoblauch in dünne Scheiben schneiden, Chili in Ringe.',
      'Restliches Öl in einer Pfanne erhitzen, Knoblauch bei mittlerer Hitze 1 Min. goldgelb werden lassen. Garnelen zugeben und 3–4 Min. durchgaren.',
      'Baby-Portion entnehmen, dann Chili, Zitronensaft, Petersilie und Salz zugeben.',
      'Gambas mit Ofenkartoffeln und Blattsalat servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen. Klassisch aus der Pfanne, Thermomix nur zum Vorgaren der Kartoffeln.',
      steps: [
        ['800 g Wasser in den Mixtopf füllen, Kartoffelspalten in den Varoma legen und vorgaren.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Kartoffeln mit Öl und Paprikapulver im Ofen bei 220 °C 15 Min. knusprig backen.', '', '', '', ''],
        ['Gambas in der Pfanne in Knoblauchöl garen, Baby-Portion entnehmen, dann würzen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Garnelen nur vollständig durchgegart und fein gehackt, Kartoffelspalten als Fingerfood. Kleinkind (1–3 J.): ohne Chili, Garnelen in Stücken.',
    baby: 1,
  },
  {
    id: 'garnelen-brokkoli-reisnudeln',
    n: 'Garnelen-Brokkoli-Pfanne mit Reisnudeln',
    ck: 'Garnelen Wok',
    img: { q: 'shrimp broccoli stir fry rice noodles' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['garnelen', 180], ['brokkoli', 150], ['paprika', 80], ['reisnudeln', 60], ['sojasauce', 15], ['ingwer', 5], ['knoblauch', 4], ['sesamoel', 4], ['rapsoel', 5], ['limette', 10], ['chili_frisch', 2]],
    s: [
      'Reisnudeln nach Packungsangabe einweichen oder garen. Brokkoli in kleine Röschen, Paprika in Streifen schneiden, Ingwer und Knoblauch hacken.',
      'Rapsöl im Wok stark erhitzen, Brokkoli und Paprika 4 Min. pfannenrühren.',
      'Ingwer, Knoblauch und Garnelen zugeben und 3 Min. braten, bis die Garnelen durchgegart sind.',
      'Nudeln untermischen. Baby-Portion entnehmen, dann Sojasauce, Sesamöl, Limettensaft und Chili zugeben.',
      'Kurz durchschwenken und sofort servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Garnelen und Gemüse im Varoma, Fertigstellen im Wok für Röstaromen.',
      steps: [
        ['Ingwer und Knoblauch in den Mixtopf geben und zerkleinern, umfüllen.', '5 Sek.', '', 'Stufe 8', ''],
        ['1000 g Wasser in den Mixtopf füllen, Brokkoli und Paprika in den Varoma-Behälter, Garnelen in den Einlegeboden legen, aufsetzen und garen.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Reisnudeln im heißen Garwasser 5 Min. ziehen lassen und abgießen.', '', '', '', ''],
        ['Alles im Wok mit Ingwer und Knoblauch kurz anbraten, Baby-Portion entnehmen, dann würzen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): durchgegarte, fein gehackte Garnelen mit weichen Brokkoli-Röschen und kurzen Nudeln ohne Sojasauce. Kleinkind (1–3 J.): ohne Chili, Nudeln kurz schneiden.',
    baby: 1,
  },
  {
    id: 'cajun-garnelen-bowl',
    n: 'Cajun-Garnelen-Bowl mit Bohnen, Mais & Avocado',
    ck: 'Bowl mit Garnelen',
    img: { q: 'cajun shrimp bowl rice black beans corn avocado' },
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['mealprep'],
    i: [['garnelen', 170], ['cajun', 3], ['reis', 50], ['schwarze_bohnen', 60], ['mais', 40], ['paprika', 80], ['avocado', 30], ['griech_joghurt', 40], ['limette', 10], ['rapsoel', 5], ['kraeuter', 3]],
    s: [
      'Reis nach Packungsangabe garen. Bohnen abspülen, Paprika würfeln, Avocado in Scheiben schneiden.',
      'Baby-Portion Garnelen ungewürzt beiseitelegen, Rest mit Cajun-Gewürz mischen.',
      'Garnelen im Öl 2 Min. pro Seite braten, bis sie durchgegart sind. Bohnen und Mais kurz in der Pfanne erwärmen.',
      'Joghurt mit Limettensaft verrühren.',
      'Reis, Bohnen, Mais, Paprika, Avocado und Garnelen in Bowls anrichten, mit Limetten-Joghurt und Koriander toppen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Reis und Garnelen im Thermomix, Bowl von Hand anrichten.',
      steps: [
        ['1200 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen. Garnelen (Baby-Portion ungewürzt, Rest mit Cajun) in den Varoma legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Mixtopf leeren, Joghurt und Limettensaft verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Bohnen und Mais kurz erwärmen und alle Komponenten in Bowls anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Garnelen fein gehackt, Reis, zerdrückte Bohnen und Avocado als Fingerfood. Kleinkind (1–3 J.): ohne Cajun, Mais und Bohnen leicht andrücken.',
    baby: 1,
  },
  {
    id: 'tom-yum-garnelen-glasnudeln',
    n: 'Tom Yum mit Garnelen & Glasnudeln',
    ck: 'Tom Yam Suppe',
    img: { wiki: 'Tom yum', q: 'tom yum soup shrimp mushrooms' },
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['garnelen', 180], ['champignons', 100], ['kirschtomaten', 80], ['glasnudeln', 50], ['kokosmilch_light', 60], ['gemuesebruehe', 400], ['currypaste', 10], ['fischsauce', 6], ['limette', 20], ['ingwer', 6], ['chili_frisch', 3], ['kraeuter', 4]],
    s: [
      'Ingwer in dünne Scheiben schneiden, Champignons vierteln, Kirschtomaten halbieren. Glasnudeln in heißem Wasser 5 Min. einweichen.',
      'Brühe mit Ingwer aufkochen, Champignons und Tomaten 4 Min. köcheln.',
      'Garnelen zugeben und 3 Min. gar ziehen lassen. Baby-Portion vor Paste und Fischsauce entnehmen.',
      'Currypaste, Kokosmilch, Fischsauce, Limettensaft und Chili einrühren.',
      'Glasnudeln in Schalen verteilen, Suppe darübergeben und mit Koriander bestreuen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen (Mixtopf gut gefüllt).',
      steps: [
        ['Brühe und Ingwer in den Mixtopf geben und aufkochen.', '8 Min.', '100°C', 'Stufe 1', ''],
        ['Champignons und Tomaten zugeben und garen.', '4 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Garnelen zugeben und gar ziehen lassen.', '4 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion ohne Würzpaste entnehmen.', '', '', '', ''],
        ['Currypaste, Kokosmilch, Fischsauce, Limettensaft und Chili zugeben und erwärmen.', '2 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Über die eingeweichten Glasnudeln geben und mit Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Garnelen, Pilze und kurz geschnittene Glasnudeln aus der salzarmen Brühe ohne Paste, Garnelen fein gehackt. Kleinkind (1–3 J.): mildes Kokos-Süppchen ohne Chili und Paste, Nudeln kurz schneiden.',
    baby: 1,
  },
  {
    id: 'garnelen-spargel-risotto',
    n: 'Garnelen-Spargel-Risotto mit Zitrone',
    ck: 'Spargelrisotto',
    img: { wiki: 'Risotto', q: 'shrimp asparagus risotto lemon' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    i: [['garnelen', 170], ['risottoreis', 60], ['spargel', 120], ['zwiebel', 30], ['gemuesebruehe', 250], ['parmesan', 12], ['olivenoel', 7], ['zitronensaft', 8], ['kraeuter', 3], ['salz', 0.5]],
    s: [
      'Spargel unten schälen und in 3 cm lange Stücke schneiden, Zwiebel fein würfeln.',
      'Zwiebel im Öl glasig dünsten, Reis 1 Min. mitrösten.',
      'Nach und nach heiße Brühe angießen und unter Rühren 18 Min. garen, Spargel nach 10 Min. zugeben.',
      'Garnelen unterheben und 4 Min. mitgaren. Baby-Portion vor dem Parmesan entnehmen.',
      'Parmesan, Zitronensaft und Petersilie unterrühren und salzen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Garnelen und Spargel im Varoma.',
      steps: [
        ['Parmesan in den Mixtopf geben und zerkleinern, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Zwiebel zerkleinern, Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Risottoreis zugeben und ohne Messbecher dünsten.', '2 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe zugeben, Spargel und Garnelen in den Varoma legen, aufsetzen und garen.', '18 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen, Garnelen, Spargel, Parmesan und Zitronensaft unterheben.', '20 Sek.', '', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Risotto mit salzarmer Brühe, weichen Spargelspitzen und fein gehackten, durchgegarten Garnelen. Kleinkind (1–3 J.): wenig Parmesan, Spargel klein schneiden.',
    baby: 1,
  },
  {
    id: 'garnelen-saganaki-feta',
    n: 'Garnelen Saganaki mit Tomaten & Feta',
    ck: 'Garnelen Tomaten Feta',
    img: { q: 'shrimp saganaki tomato feta greek' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['garnelen', 180], ['tomaten_dose', 200], ['feta', 30], ['zwiebel', 30], ['knoblauch', 4], ['olivenoel', 8], ['kraeuter', 4], ['gewuerze', 1], ['reis', 55], ['salz', 0.5]],
    s: [
      'Reis nach Packungsangabe garen. Zwiebel und Knoblauch fein würfeln.',
      'Zwiebel und Knoblauch im Öl 3 Min. andünsten, Tomaten und Oregano zugeben und 10 Min. einköcheln.',
      'Garnelen einlegen und 3–4 Min. durchgaren. Baby-Portion vor dem Feta entnehmen.',
      'Feta darüberbröseln, Deckel auflegen und 2 Min. schmelzen lassen.',
      'Mit Petersilie bestreuen und mit Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Garnelen im Varoma, Reis im Garkörbchen.',
      steps: [
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten, Oregano und 300 g Wasser zugeben, Reis im Garkörbchen einhängen, Garnelen in den Varoma legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 1', ''],
        ['Baby-Portion entnehmen. Garnelen in eine Form geben, Sauce darüber, mit Feta bestreuen.', '', '', '', ''],
        ['Mit Petersilie und Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Reis mit ungesalzener Tomatensauce und fein gehackten Garnelen, kein Feta (salzig). Kleinkind (1–3 J.): wenig Feta, Garnelen klein schneiden.',
    baby: 1,
  },
]);
