// Fleisch-Hauptgerichte: Rind, Schwein, Lamm & Hack – mager und proteinreich
Object.assign(ING, {
  fleisch_lamm: { n: 'Lammlachse / Lammkeule (mager)', k: 145, p: 20.5, c: 0, f: 7, fi: 0, su: 0, sa: 0.2, pr: 28, cat: 'fleisch', fl: 'XA' },
});
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  {
    id: 'tafelspitz-rinderhuefte-wurzelgemuese',
    n: 'Tafelspitz-Art von der Rinderhüfte mit Wurzelgemüse & Schnittlauchsauce',
    img: { wiki: 'Tafelspitz', q: 'tafelspitz boiled beef vegetables chive sauce' },
    ck: 'Tafelspitz',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 90, d: 2,
    st: ['comfort'],
    i: [['rinderfilet', 170], ['karotte', 80], ['lauch', 40], ['sellerie', 30], ['zwiebel', 30], ['kartoffel', 200], ['skyr', 80], ['senf', 5], ['kraeuter', 6], ['gemuesebruehe', 300], ['salz', 1], ['gewuerze', 1]],
    s: [
      'Brühe mit halbierter Zwiebel (mit Schale, in der Pfanne dunkel angeröstet) und Gewürzen (Lorbeer, Pfefferkörner) aufkochen.',
      'Rinderhüfte am Stück einlegen und bei 80–85 °C (nur siedend, nicht kochend) 45–60 Min. ziehen lassen, bis die Kerntemperatur 58–60 °C beträgt.',
      'Karotten, Sellerie und Lauch in Stücke schneiden und die letzten 15 Min. in der Brühe mitgaren. Kartoffeln separat 20 Min. kochen.',
      'Für die Sauce Skyr mit Senf, fein geschnittenem Schnittlauch und 2 EL Brühe glatt rühren.',
      'Baby-/Kleinkind-Portion vor dem Salzen entnehmen. Fleisch quer zur Faser in dünne Scheiben schneiden, mit Gemüse, Kartoffeln, etwas Brühe und Sauce servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Fleisch am Stück (ca. 700 g) im Varoma, Brühe im Mixtopf.',
      steps: [
        ['Zwiebel halbieren und in der Pfanne ohne Fett dunkel anrösten.', '', '', '', ''],
        ['1200 g Brühe, Zwiebel und Gewürze in den Mixtopf geben. Kartoffeln im Garkörbchen einhängen.', '', '', '', ''],
        ['Rinderhüfte in den Varoma-Behälter, Wurzelgemüse auf den Einlegeboden legen, Varoma aufsetzen und garen (Kerntemperatur 58–60 °C prüfen).', '55 Min.', 'Varoma', 'Stufe 1', ''],
        ['Varoma abnehmen, Fleisch 5 Min. ruhen lassen. Baby-Portion ungesalzen entnehmen.', '', '', '', ''],
        ['Mixtopf leeren und spülen. Schnittlauch hacken.', '3 Sek.', '', 'Stufe 7', ''],
        ['Skyr, Senf und 30 g Brühe zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fleisch mit Karotte, Kartoffel und ungesalzener Brühe fein pürieren; für BLW weiche Karottensticks und dünne, mürbe Fleischstreifen. Kleinkind (1–3 J.): Fleisch sehr klein schneiden, Gemüse zerdrücken, Sauce ohne Senf.',
    baby: 2,
  },
  {
    id: 'schnitzel-glutenfrei-kartoffelsalat',
    n: 'Schnitzel glutenfrei paniert mit Gurken-Kartoffelsalat',
    img: { wiki: 'Schnitzel', q: 'schnitzel potato salad lemon' },
    ck: 'Schnitzel Kartoffelsalat',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['kinderliebling'],
    i: [['schweineschnitzel', 150], ['ei', 25], ['speisestaerke', 8], ['paniermehl_gf', 25], ['rapsoel', 10], ['kartoffel', 200], ['gurke', 80], ['joghurt', 50], ['senf', 4], ['essig', 5], ['kraeuter', 4], ['zitrone', 20], ['salz', 1], ['gewuerze', 1]],
    s: [
      'Kartoffeln mit Schale 20 Min. kochen, pellen, etwas abkühlen lassen und in Scheiben schneiden.',
      'Gurke fein hobeln. Joghurt, Senf, Essig, 2 EL warmes Kartoffelwasser und Dill verrühren, mit Kartoffeln und Gurke mischen.',
      'Schnitzel zwischen Folie auf 5 mm dünn klopfen. Nacheinander in Stärke, verquirltem Ei und glutenfreiem Paniermehl wenden.',
      'Öl in einer beschichteten Pfanne erhitzen, Schnitzel bei mittlerer Hitze pro Seite 3 Min. goldbraun braten, dabei die Pfanne schwenken.',
      'Baby-/Kleinkind-Portion ungesalzen beiseitelegen. Rest leicht salzen und mit Zitronenspalten und Kartoffelsalat servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Schnitzel werden in der Pfanne gebraten.',
      steps: [
        ['500 g Wasser in den Mixtopf füllen, Kartoffeln in den Varoma-Behälter geben, aufsetzen und garen.', '30 Min.', 'Varoma', 'Stufe 1', ''],
        ['Kartoffeln pellen und in Scheiben schneiden, Mixtopf leeren.', '', '', '', ''],
        ['Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Joghurt, Senf, Essig und 30 g Kartoffelwasser zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Dressing mit Kartoffeln und gehobelter Gurke in einer Schüssel mischen.', '', '', '', ''],
        ['Schnitzel klopfen, panieren und in der Pfanne pro Seite 3 Min. ausbacken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Schnitzel ungesalzen in fingerlange Streifen schneiden (BLW) oder mit Kartoffel und etwas Wasser pürieren; Ei muss durchgegart sein. Kleinkind (1–3 J.): kleine Schnitzelstücke mit Kartoffeln, Gurke geschält und dünn.',
    baby: 2,
  },
  {
    id: 'schweinefilet-medaillons-pfeffersauce',
    n: 'Schweinefilet-Medaillons mit Pfeffersauce, Bohnen & Kartoffeln',
    img: { wiki: 'Pork tenderloin', q: 'pork tenderloin medallions pepper sauce green beans' },
    ck: 'Schweinefilet Medaillons',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    i: [['schweinefilet', 170], ['gruene_bohnen', 150], ['kartoffel', 200], ['zwiebel', 20], ['sahne', 30], ['gemuesebruehe', 80], ['senf', 4], ['speisestaerke', 3], ['rapsoel', 7], ['gewuerze', 2], ['salz', 1]],
    s: [
      'Kartoffeln schälen, halbieren und 20 Min. garen. Bohnen die letzten 8 Min. in Salzwasser bzw. im Dampf garen.',
      'Schweinefilet in 3 cm dicke Medaillons schneiden und leicht flach drücken.',
      'Öl in einer Pfanne erhitzen, Medaillons pro Seite 3 Min. braten, herausnehmen und bei 80 °C im Ofen 5 Min. ruhen lassen.',
      'Zwiebel fein würfeln, im Bratensatz 2 Min. dünsten. Mit Brühe ablöschen, Sahne und Senf zugeben, mit angerührter Stärke binden.',
      'Baby-/Kleinkind-Portion vor dem Pfeffern abnehmen. Sauce mit grob zerstoßenem Pfeffer und Salz würzen und zu Medaillons, Bohnen und Kartoffeln servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Medaillons in der Pfanne braten.',
      steps: [
        ['500 g Wasser in den Mixtopf füllen, Kartoffeln im Garkörbchen einhängen, Bohnen in den Varoma geben, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
        ['Kartoffeln und Bohnen warmstellen, Mixtopf leeren. Medaillons in der Pfanne pro Seite 3 Min. braten.', '', '', '', ''],
        ['Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Brühe, Sahne, Senf und Speisestärke zugeben und andicken.', '4 Min.', '100°C', 'Stufe 2', ''],
        ['Baby-Portion entnehmen, dann Pfeffer und Salz zugeben und kurz verrühren.', '10 Sek.', '', 'Stufe 2', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fleisch mit Kartoffel, Bohnen und ungewürzter Sauce pürieren; für BLW weiche Bohnen und dünne Filetstreifen. Kleinkind (1–3 J.): Medaillon klein schneiden, Sauce ohne Pfeffer.',
    baby: 2,
  },
  {
    id: 'koettbullar-kartoffelpueree',
    n: 'Köttbullar light mit Rahmsauce, Kartoffelpüree & Beerenkompott',
    img: { wiki: 'Swedish meatballs', q: 'swedish meatballs cream sauce mashed potatoes lingonberry' },
    ck: 'Köttbullar',
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['kinderliebling', 'comfort'],
    i: [['rinderhack', 150], ['ei', 15], ['haferflocken', 12], ['zwiebel', 30], ['kartoffel', 200], ['milch', 60], ['gemuesebruehe', 100], ['sahne', 25], ['speisestaerke', 4], ['sojasauce', 4], ['heidelbeeren', 40], ['gurke', 60], ['rapsoel', 6], ['gewuerze', 2], ['salz', 1]],
    s: [
      'Zwiebel sehr fein reiben. Hack mit Ei, Haferflocken, Zwiebel und Piment/Pfeffer verkneten und zu 3 cm großen Bällchen formen.',
      'Kartoffeln schälen und 20 Min. garen, abgießen und mit warmer Milch zu Püree stampfen.',
      'Öl in einer Pfanne erhitzen, Köttbullar rundum 8–10 Min. braun und durchbraten, herausnehmen.',
      'Bratensatz mit Brühe ablöschen, Sahne und Sojasauce zugeben, mit angerührter Stärke binden und Bällchen darin 2 Min. ziehen lassen.',
      'Heidelbeeren mit 1 EL Wasser 3 Min. zu Kompott einkochen. Baby-/Kleinkind-Portion vor dem Salzen entnehmen.',
      'Mit Püree, Kompott und Gurkenscheiben servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Köttbullar werden in der Pfanne gebraten.',
      steps: [
        ['Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hack, Ei, Haferflocken und Gewürze zugeben und vermengen. Bällchen formen und in der Pfanne braten.', '30 Sek.', '', 'Teigknetstufe', 'Teigkneten'],
        ['Mixtopf spülen. Rühraufsatz einsetzen, Kartoffeln in Stücken, Milch und 50 g Wasser zugeben und garen.', '22 Min.', '98°C', 'Stufe 1', ''],
        ['Rühraufsatz drin lassen und Kartoffeln zu Püree rühren, umfüllen.', '20 Sek.', '', 'Stufe 3', ''],
        ['Brühe, Sahne, Sojasauce und Speisestärke in den Mixtopf geben und andicken.', '5 Min.', '100°C', 'Stufe 2', ''],
        ['Baby-Portion entnehmen, Sauce über die Köttbullar geben.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Köttbullar ohne Salz und Sojasauce formen, zerdrückt mit Püree reichen oder als weiche Bällchen für BLW; Ei durchgaren. Kleinkind (1–3 J.): Bällchen halbieren, Püree mit wenig Sauce, Kompott als Dip.',
    baby: 2,
  },
  {
    id: 'cevapcici-ajvar-reis',
    n: 'Cevapcici mit Ajvar-Paprika, Reis & Joghurt-Dip',
    img: { wiki: 'Ćevapi', q: 'cevapcici ajvar rice yogurt' },
    ck: 'Cevapcici',
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['kinderliebling'],
    i: [['rinderhack', 140], ['lammhack', 20], ['zwiebel', 40], ['knoblauch', 4], ['paprika', 120], ['tomatenmark', 10], ['reis', 55], ['joghurt', 60], ['gurke', 50], ['rapsoel', 6], ['gewuerze', 3], ['salz', 1]],
    s: [
      'Hälfte der Zwiebel und Knoblauch fein reiben, mit Hackfleisch, Paprikapulver und Pfeffer gut verkneten und 10 Min. kühlen. Zu fingerdicken, 8 cm langen Röllchen formen.',
      'Reis nach Packungsangabe garen.',
      'Für das schnelle Ajvar Paprika würfeln und mit restlicher Zwiebel in 3 g Öl 8 Min. weich dünsten, Tomatenmark zugeben und grob pürieren.',
      'Cevapcici in einer Grillpfanne mit dem restlichen Öl rundum 8–10 Min. braten (oder 10 Min. grillen).',
      'Joghurt mit geriebener Gurke verrühren. Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest salzen und mit Reis, Ajvar und Dip servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Cevapcici werden in der Pfanne oder auf dem Grill gebraten.',
      steps: [
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hack und Gewürze zugeben und vermengen, umfüllen und Röllchen formen.', '30 Sek.', '', 'Teigknetstufe', 'Teigkneten'],
        ['Mixtopf spülen. Paprika in Stücken, restliche Zwiebel und Öl in den Mixtopf geben und weich dünsten.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Tomatenmark zugeben und zu Ajvar pürieren, umfüllen.', '10 Sek.', '', 'Stufe 6', ''],
        ['1000 g Wasser einfüllen, Reis im Garkörbchen garen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Cevapcici in der Pfanne 8–10 Min. braten, Joghurt mit geriebener Gurke verrühren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Cevapcici sind ideales BLW-Fingerfood (gut durchgebraten); alternativ mit Reis und Ajvar pürieren. Kleinkind (1–3 J.): Röllchen halbieren, Ajvar mild ohne Chili, Joghurt-Dip zum Tunken.',
    baby: 2,
  },
  {
    id: 'kofta-joghurt-quinoa',
    n: 'Lamm-Rind-Kofta mit Minz-Joghurt & Tomaten-Quinoa',
    img: { wiki: 'Kofta', q: 'kofta kebab yogurt mint quinoa' },
    ck: 'Kofta',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    i: [['rinderhack', 100], ['lammhack', 50], ['zwiebel', 30], ['knoblauch', 4], ['kraeuter', 6], ['quinoa', 50], ['tomate', 100], ['gurke', 60], ['griech_joghurt', 80], ['zitronensaft', 8], ['olivenoel', 5], ['gewuerze', 3], ['salz', 1]],
    s: [
      'Quinoa gründlich waschen und in der doppelten Menge Wasser 15 Min. garen, 5 Min. quellen lassen.',
      'Zwiebel, Knoblauch und die Hälfte der Kräuter fein hacken, mit Hack, Kreuzkümmel, Koriander und Zimt verkneten. Zu 8 länglichen Kofta formen, ggf. auf Spieße stecken.',
      'Kofta in einer Grillpfanne mit Öl rundum 8–10 Min. braten oder im Ofen bei 220 °C 12 Min. grillen.',
      'Tomate und Gurke würfeln, mit Quinoa, Zitronensaft und restlichen Kräutern mischen. Joghurt mit gehackter Minze verrühren.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest salzen und Kofta mit Quinoa und Minz-Joghurt servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Kofta in der Pfanne oder im Ofen garen.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Quinoa im Garkörbchen einhängen und garen, umfüllen.', '18 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel, Knoblauch und Kräuter in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hack und Gewürze zugeben und vermengen. Kofta formen und braten.', '30 Sek.', '', 'Teigknetstufe', 'Teigkneten'],
        ['Mixtopf spülen, Minze zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Joghurt zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Quinoa mit Tomate, Gurke und Zitronensaft mischen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene, gut durchgegarte Kofta ohne Spieß als Fingerfood oder mit Quinoa und Joghurt pürieren. Kleinkind (1–3 J.): Kofta in Scheiben, Quinoa-Salat mit kleinen Tomatenstücken, Joghurt als Dip.',
    baby: 2,
  },
  {
    id: 'bulgogi-rind-reis',
    n: 'Bulgogi (koreanisches Rindfleisch) mit Reis & Gurkensalat',
    img: { wiki: 'Bulgogi', q: 'bulgogi beef rice korean' },
    ck: 'Bulgogi',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['rindersteak', 160], ['sojasauce', 15], ['birne', 30], ['knoblauch', 5], ['ingwer', 5], ['sesamoel', 4], ['rapsoel', 4], ['fruehlingszwiebel', 20], ['reis', 65], ['gurke', 80], ['essig', 5], ['sesam', 4], ['karotte', 40]],
    s: [
      'Rindfleisch leicht anfrieren und quer zur Faser in hauchdünne Scheiben schneiden.',
      'Birne, Knoblauch und Ingwer fein reiben, mit Sojasauce und Sesamöl verrühren und das Fleisch darin mind. 15 Min. marinieren. Baby-/Kleinkind-Fleisch vorher ohne Sojasauce beiseitelegen.',
      'Reis nach Packungsangabe garen. Gurke in dünne Scheiben schneiden und mit Essig mischen.',
      'Rapsöl in einer Pfanne sehr heiß werden lassen, Fleisch mit Karottenstreifen portionsweise 2–3 Min. scharf anbraten.',
      'Mit Frühlingszwiebelringen und Sesam bestreuen und mit Reis und Gurkensalat servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Fleisch wird in der Pfanne scharf angebraten.',
      steps: [
        ['Birne, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 7', ''],
        ['Sojasauce und Sesamöl zugeben und verrühren, über das Fleisch geben und marinieren.', '5 Sek.', '', 'Stufe 3', ''],
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Baby-Fleisch ohne Marinade separat kurz braten.', '', '', '', ''],
        ['Mariniertes Fleisch mit Karotte in der heißen Pfanne 2–3 Min. scharf anbraten.', '', '', '', ''],
        ['Gurke mit Essig mischen, mit Sesam und Frühlingszwiebel servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürztes, dünn geschnittenes Rindfleisch weich braten und mit Reis und gedünsteter Karotte pürieren oder Reis-Bällchen formen. Kleinkind (1–3 J.): Fleisch in sehr kleine Stücke schneiden, Sojasauce stark verdünnt oder weglassen, Sesam gemahlen.',
    baby: 1,
  },
  {
    id: 'beef-stir-fry-reisnudeln',
    n: 'Beef Stir-Fry mit Paprika, Zuckerschoten & Reisnudeln',
    img: { wiki: 'Stir frying', q: 'beef stir fry snow peas peppers rice noodles' },
    ck: 'Rindfleisch Wok',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['rindersteak', 150], ['paprika', 100], ['zuckerschoten', 80], ['fruehlingszwiebel', 20], ['reisnudeln', 55], ['sojasauce', 15], ['austernsauce', 8], ['ingwer', 6], ['knoblauch', 4], ['speisestaerke', 4], ['rapsoel', 8], ['limette', 10]],
    s: [
      'Rindfleisch quer zur Faser in dünne Streifen schneiden und mit 1 TL Speisestärke und 1 TL Sojasauce vermengen.',
      'Reisnudeln nach Packungsangabe in heißem Wasser einweichen, abgießen und kalt abspülen.',
      'Paprika in Streifen schneiden, Zuckerschoten halbieren, Ingwer und Knoblauch fein hacken.',
      'Öl im Wok sehr stark erhitzen, Fleisch 2 Min. scharf anbraten und herausnehmen. Gemüse mit Ingwer und Knoblauch 3 Min. pfannenrühren. Baby-Portion vor der Sauce entnehmen.',
      'Fleisch, Nudeln, restliche Sojasauce, Austernsauce und 3 EL Wasser mit restlicher Stärke zugeben, 1 Min. schwenken, mit Frühlingszwiebel und Limette servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Stir-Fry gelingt am besten im heißen Wok; der Thermomix bereitet Sauce und Gemüse vor.',
      steps: [
        ['Ingwer und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 7', ''],
        ['Sojasauce, Austernsauce, Speisestärke und 50 g Wasser zugeben und andicken, umfüllen.', '3 Min.', '100°C', 'Stufe 2', ''],
        ['Rindfleischstreifen im Wok 2 Min. scharf anbraten.', '', '', '', ''],
        ['Paprika und Zuckerschoten im Wok 3 Min. pfannenrühren, Baby-Portion entnehmen.', '', '', '', ''],
        ['Eingeweichte Reisnudeln, Fleisch und Sauce zugeben und 1 Min. schwenken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Gemüse länger weich garen, mit ungewürzten Fleischstreifen und klein geschnittenen Nudeln als Fingerfood oder püriert anbieten. Kleinkind (1–3 J.): Nudeln kurz schneiden, wenig verdünnte Sauce, Zuckerschoten halbiert.',
    baby: 1,
  },
  {
    id: 'picadillo-reis',
    n: 'Picadillo (kubanische Hackpfanne) mit Reis',
    img: { wiki: 'Picadillo', q: 'picadillo cuban ground beef rice' },
    ck: 'Picadillo',
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['mealprep'],
    i: [['rinderhack', 150], ['zwiebel', 40], ['knoblauch', 4], ['paprika', 80], ['kartoffel', 80], ['tomaten_dose', 150], ['oliven', 12], ['rosinen', 8], ['reis', 50], ['olivenoel', 6], ['gewuerze', 3], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Reis nach Packungsangabe garen. Kartoffel in 1 cm kleine Würfel, Paprika, Zwiebel und Knoblauch fein würfeln.',
      'Öl in einer Pfanne erhitzen, Hack 5 Min. krümelig anbraten, Zwiebel, Knoblauch und Paprika 3 Min. mitbraten.',
      'Kartoffelwürfel, Tomaten und 100 ml Wasser zugeben, mit Kreuzkümmel und Oregano würzen und 15 Min. zugedeckt köcheln, bis die Kartoffeln weich sind.',
      'Baby-/Kleinkind-Portion vor Oliven und Salz entnehmen.',
      'Halbierte Oliven und Rosinen unterrühren, 3 Min. ziehen lassen, salzen und mit Reis und Petersilie servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen, warmstellen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hack zugeben und anbraten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Paprika- und Kartoffelwürfel, Tomaten, 100 g Wasser und Gewürze zugeben und garen.', '18 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen.', '', '', '', ''],
        ['Oliven, Rosinen und Salz zugeben und ziehen lassen.', '3 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes Picadillo ohne Oliven und Rosinen mit Reis pürieren oder zu weichen Reisbällchen formen. Kleinkind (1–3 J.): Rosinen gehackt, Oliven weglassen oder fein hacken, mild würzen.',
    baby: 2,
  },
  {
    id: 'carne-asada-bowl',
    n: 'Carne Asada Bowl mit Reis, Bohnen & Pico de Gallo',
    img: { wiki: 'Carne asada', q: 'carne asada bowl rice beans pico de gallo' },
    ck: 'Carne Asada',
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    i: [['rindersteak', 150], ['limette', 20], ['knoblauch', 4], ['cajun', 3], ['reis', 50], ['schwarze_bohnen', 60], ['mais', 30], ['tomate', 80], ['rote_zwiebel', 20], ['kraeuter', 5], ['avocado', 30], ['griech_joghurt', 40], ['olivenoel', 6], ['salz', 1]],
    s: [
      'Steak mit Limettensaft, gepresstem Knoblauch, Gewürz und 3 g Öl mind. 15 Min. marinieren. Baby-Stück vorher ohne Gewürz abschneiden.',
      'Reis nach Packungsangabe garen. Bohnen und Mais abspülen und erwärmen.',
      'Für Pico de Gallo Tomate und rote Zwiebel fein würfeln, mit Koriander, etwas Limettensaft und Salz mischen.',
      'Steak in einer Grillpfanne mit restlichem Öl pro Seite 3–4 Min. braten, 5 Min. ruhen lassen und quer zur Faser in Streifen schneiden.',
      'Reis, Bohnen, Mais, Steak, Pico de Gallo, Avocadoscheiben und Joghurt in Schalen anrichten.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Das Steak wird in der Grillpfanne gebraten.',
      steps: [
        ['Knoblauch in den Mixtopf geben und zerkleinern, mit Limettensaft, Gewürz und Öl verrühren und über das Steak geben.', '5 Sek.', '', 'Stufe 7', ''],
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen, Bohnen und Mais in den Varoma geben, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Mixtopf leeren. Zwiebel und Koriander zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Tomaten in Stücken und Limettensaft zugeben und grob hacken (Pico de Gallo).', '3 Sek.', '', 'Stufe 4', ''],
        ['Steak in der Grillpfanne pro Seite 3–4 Min. braten, ruhen lassen und aufschneiden.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürztes Steak gut durchgaren und in lange, dünne Streifen schneiden (BLW) oder mit Reis, Bohnen und Avocado pürieren. Kleinkind (1–3 J.): Fleisch klein schneiden, Bohnen zerdrücken, Pico de Gallo ohne Zwiebel.',
    baby: 1,
  },
  {
    id: 'hackbraten-ofengemuese',
    n: 'Saftiger Hackbraten mit Ofengemüse & Kartoffeln',
    img: { wiki: 'Meatloaf', q: 'meatloaf roasted vegetables potatoes' },
    ck: 'Hackbraten',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 75, d: 1,
    st: ['comfort', 'mealprep', 'kinderliebling'],
    i: [['rinderhack', 150], ['ei', 15], ['haferflocken', 12], ['zwiebel', 30], ['karotte', 60], ['senf', 4], ['ketchup', 10], ['kartoffel', 180], ['zucchini', 80], ['paprika', 80], ['olivenoel', 7], ['gewuerze', 3], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Ofen auf 200 °C Ober-/Unterhitze vorheizen. Zwiebel und die Hälfte der Karotte fein reiben.',
      'Hack mit Ei, Haferflocken, Zwiebel, geriebener Karotte, Senf, Paprikapulver und Pfeffer verkneten und zu einem Laib formen. In eine Auflaufform setzen und mit Ketchup bestreichen.',
      'Kartoffeln, restliche Karotte, Zucchini und Paprika in Spalten bzw. Stücke schneiden, mit Öl, Rosmarin und Thymian mischen und um den Hackbraten verteilen.',
      'Alles 45–50 Min. backen, bis der Hackbraten eine Kerntemperatur von 72 °C erreicht hat.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest leicht salzen, Hackbraten in Scheiben schneiden und mit dem Gemüse servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Gebacken wird im Ofen.',
      steps: [
        ['Zwiebel und Karotte in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hack, Ei, Haferflocken, Senf und Gewürze zugeben und vermengen.', '40 Sek.', '', 'Teigknetstufe', 'Teigkneten'],
        ['Masse zu einem Laib formen, mit Ketchup bestreichen und in die Form setzen.', '', '', '', ''],
        ['Gemüse und Kartoffeln mit Öl und Kräutern drumherum verteilen und bei 200 °C 45–50 Min. backen.', '', '', '', ''],
        ['Baby-Portion vor dem Salzen entnehmen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hackbraten ohne Salz ist weich und gut als Fingerfood in Sticks; Gemüse weich gebacken mitgeben oder alles zerdrücken. Kleinkind (1–3 J.): Scheiben in Würfel schneiden, Ketchup sparsam.',
    baby: 2,
  },
  {
    id: 'kohlrouladen-hack-reis',
    n: 'Kohlrouladen mit Rinderhack, Reis & Tomatensauce',
    img: { wiki: 'Cabbage roll', q: 'cabbage rolls ground beef rice tomato sauce' },
    ck: 'Kohlrouladen',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 80, d: 2,
    st: ['comfort', 'mealprep'],
    i: [['rinderhack', 150], ['reis', 35], ['weisskohl', 200], ['zwiebel', 40], ['ei', 15], ['passierte_tomaten', 150], ['tomatenmark', 10], ['gemuesebruehe', 100], ['schmand_light', 30], ['rapsoel', 6], ['gewuerze', 3], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Strunk aus dem Kohl schneiden, Kohlkopf 5 Min. in kochendes Wasser legen und große Blätter ablösen. Dicke Blattrippen flach schneiden.',
      'Reis 10 Min. vorgaren. Mit Hack, Ei, der Hälfte der fein gewürfelten Zwiebel, Paprikapulver und Majoran verkneten.',
      'Füllung auf die Kohlblätter verteilen, Seiten einschlagen, aufrollen und mit Küchengarn oder Zahnstochern fixieren.',
      'Öl in einem Schmortopf erhitzen, Rouladen rundum 5 Min. anbraten. Restliche Zwiebel und Tomatenmark kurz mitrösten, mit Tomaten und Brühe ablöschen.',
      'Zugedeckt 40 Min. bei kleiner Hitze schmoren. Baby-/Kleinkind-Portion ungesalzen entnehmen, Sauce mit Schmand verfeinern, salzen und mit Petersilie servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Die Rouladen garen im Varoma über der Tomatensauce.',
      steps: [
        ['1000 g Wasser aufkochen, Kohlblätter im Varoma blanchieren.', '10 Min.', 'Varoma', 'Stufe 1', ''],
        ['Wasser abgießen. Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hälfte der Zwiebel mit Hack, vorgegartem Reis, Ei und Gewürzen vermengen und in die Kohlblätter rollen.', '30 Sek.', '', 'Teigknetstufe', 'Teigkneten'],
        ['Öl zur restlichen Zwiebel geben und andünsten, Tomatenmark zugeben.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Passierte Tomaten und Brühe zugeben, Rouladen in Varoma und Einlegeboden legen, aufsetzen und garen.', '35 Min.', 'Varoma', 'Stufe 1', ''],
        ['Baby-Portion entnehmen, Schmand und Salz in die Sauce rühren.', '20 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Füllung ohne Salz mit weichem Kohl und Sauce pürieren oder die Füllung als Bällchen anbieten. Kleinkind (1–3 J.): Roulade in kleine Stücke schneiden, Kohl gut weich, Sauce mild.',
    baby: 2,
  },
  {
    id: 'gefuellte-zucchini-hack-feta',
    n: 'Gefüllte Zucchini mit Rinderhack, Tomate & Feta',
    img: { wiki: 'Stuffed zucchini', q: 'stuffed zucchini ground beef feta oven' },
    ck: 'Gefüllte Zucchini',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 50, d: 1,
    i: [['rinderhack', 140], ['zucchini', 250], ['zwiebel', 30], ['knoblauch', 4], ['tomaten_dose', 120], ['feta', 25], ['quinoa', 40], ['olivenoel', 6], ['gewuerze', 3], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Ofen auf 200 °C vorheizen. Quinoa waschen und 15 Min. in Wasser garen. Zucchini längs halbieren und das Fruchtfleisch mit einem Löffel herauslösen, fein hacken.',
      'Öl in einer Pfanne erhitzen, Hack 5 Min. krümelig anbraten, Zwiebel, Knoblauch und Zucchinifruchtfleisch 3 Min. mitbraten.',
      'Tomaten und Oregano zugeben und 5 Min. einkochen, Quinoa unterheben. Baby-/Kleinkind-Portion der Füllung vor dem Salzen entnehmen.',
      'Zucchinihälften in eine Form legen, mit der Hackmasse füllen und mit zerbröseltem Feta bestreuen.',
      '25 Min. backen, bis die Zucchini weich sind. Mit Basilikum bestreut servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Überbacken wird im Ofen.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Quinoa im Garkörbchen einhängen und garen, umfüllen.', '18 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hack zugeben und anbraten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Zucchinifruchtfleisch, Tomaten und Oregano zugeben und einkochen, dabei Messbecher weglassen.', '8 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Quinoa unterrühren, Baby-Portion entnehmen.', '15 Sek.', '', 'Stufe 1', 'Linkslauf'],
        ['Zucchini füllen, mit Feta bestreuen und bei 200 °C 25 Min. backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Füllung ohne Feta und Salz mit dem weichen Zucchinifleisch pürieren oder Zucchinistücke als Fingerfood. Kleinkind (1–3 J.): Zucchini klein schneiden, Feta in kleiner Menge (salzig).',
    baby: 2,
  },
  {
    id: 'steak-salat-ofenkartoffeln',
    n: 'Steak-Salat mit Rucola, Ofenkartoffeln & Balsamico',
    img: { wiki: 'Tagliata', q: 'steak salad rucola parmesan potatoes' },
    ck: 'Steak Salat',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    i: [['rindersteak', 160], ['kartoffel', 220], ['rucola', 50], ['kirschtomaten', 100], ['parmesan', 10], ['rote_zwiebel', 15], ['olivenoel', 10], ['essig', 8], ['senf', 3], ['kraeuter', 3], ['salz', 1], ['gewuerze', 1]],
    s: [
      'Ofen auf 220 °C vorheizen. Kartoffeln in Spalten schneiden, mit 4 g Öl und Rosmarin mischen und 30 Min. knusprig backen.',
      'Steak 20 Min. vor dem Braten aus dem Kühlschrank nehmen. In einer Grillpfanne mit 2 g Öl pro Seite 3 Min. braten, 5 Min. in Alufolie ruhen lassen.',
      'Restliches Öl mit Balsamico und Senf zu einem Dressing verrühren.',
      'Rucola, halbierte Kirschtomaten und rote Zwiebelringe mit dem Dressing mischen.',
      'Baby-/Kleinkind-Fleisch ungewürzt abschneiden. Steak in dünne Streifen schneiden, salzen, pfeffern und mit Parmesanspänen und Kartoffeln auf dem Salat anrichten.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix übernimmt nur das Dressing.',
      steps: [
        ['Kartoffelspalten mit Öl und Rosmarin bei 220 °C 30 Min. backen.', '', '', '', ''],
        ['Parmesan in den Mixtopf geben und zerkleinern, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Rote Zwiebel zerkleinern.', '3 Sek.', '', 'Stufe 5', ''],
        ['Öl, Balsamico, Senf, Salz und Pfeffer zugeben und emulgieren.', '15 Sek.', '', 'Stufe 4', ''],
        ['Steak in der Grillpfanne braten, ruhen lassen, aufschneiden und mit Salat und Kartoffeln anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Steak durchbraten und in lange, dünne Streifen schneiden, weiche Kartoffelspalten ohne Kruste dazu; Rucola eher weglassen. Kleinkind (1–3 J.): Fleisch klein schneiden, Kirschtomaten vierteln, wenig Dressing.',
    baby: 1,
  },
  {
    id: 'gulaschsuppe-rind',
    n: 'Ungarische Gulaschsuppe mit Rindfleisch & Kartoffeln',
    img: { wiki: 'Goulash', q: 'goulash soup beef potatoes paprika' },
    ck: 'Gulaschsuppe',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 100, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['rindergulasch', 170], ['zwiebel', 80], ['knoblauch', 4], ['paprika', 100], ['kartoffel', 150], ['tomatenmark', 15], ['tomaten_dose', 100], ['gemuesebruehe', 350], ['rapsoel', 6], ['gewuerze', 4], ['salz', 1], ['schmand_light', 20], ['vollkornbrot', 30]],
    s: [
      'Rindfleisch in 1,5 cm kleine Würfel schneiden, Zwiebeln grob würfeln, Paprika und Kartoffeln in 1 cm große Würfel schneiden.',
      'Öl in einem Topf stark erhitzen, Fleisch portionsweise 5 Min. kräftig anbraten. Zwiebeln zugeben und 5 Min. bräunen, Tomatenmark und edelsüßes Paprikapulver 1 Min. anrösten.',
      'Mit Brühe und Tomaten ablöschen, Kümmel und Majoran zugeben und zugedeckt 60 Min. leise köcheln.',
      'Kartoffeln und Paprika zugeben und weitere 20 Min. garen, bis Fleisch und Kartoffeln weich sind.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen. Rest mit Salz, Pfeffer und etwas Rosenpaprika abschmecken, mit einem Klecks Schmand und Brot servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Bei mehr als 4 Portionen in zwei Durchgängen kochen (max. 2,2 l).',
      steps: [
        ['Zwiebeln und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Rindfleischwürfel zugeben und anbraten, Messbecher nicht einsetzen.', '6 Min.', '160°C', 'Stufe 1', 'Anbraten'],
        ['Tomatenmark und Paprikapulver zugeben und anrösten.', '2 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe, Tomaten, Kümmel und Majoran zugeben und garen.', '60 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Kartoffel- und Paprikawürfel zugeben und weitergaren.', '20 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen, dann mit Salz und Pfeffer abschmecken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Suppe ohne Schärfe mit Fleisch und Kartoffeln fein pürieren; für BLW weiche Kartoffel- und Fleischstücke abtropfen lassen. Kleinkind (1–3 J.): Fleisch sehr klein zupfen, nur edelsüßes Paprika, Brot zum Tunken.',
    baby: 2,
  },
  {
    id: 'zuercher-geschnetzeltes-roesti',
    n: 'Zürcher Geschnetzeltes light mit Rösti',
    img: { wiki: 'Zürcher Geschnetzeltes', q: 'zuercher geschnetzeltes rosti mushrooms cream' },
    ck: 'Zürcher Geschnetzeltes',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort'],
    i: [['schweineschnitzel', 160], ['champignons', 120], ['zwiebel', 30], ['sahne', 40], ['gemuesebruehe', 80], ['speisestaerke', 4], ['zitronensaft', 5], ['kartoffel', 220], ['rapsoel', 10], ['kraeuter', 4], ['salz', 1], ['gewuerze', 1]],
    s: [
      'Kartoffeln schälen, grob raspeln und gut ausdrücken, mit etwas Salz und Pfeffer mischen.',
      'In einer beschichteten Pfanne 5 g Öl erhitzen, Kartoffelmasse flach andrücken und pro Seite 8–10 Min. goldbraun braten (Rösti mit Hilfe eines Tellers wenden).',
      'Fleisch in feine Streifen schneiden. Restliches Öl in einer zweiten Pfanne sehr heiß werden lassen, Fleisch 2 Min. scharf anbraten und herausnehmen.',
      'Zwiebel und geschnittene Champignons im Bratensatz 4 Min. braten, mit Brühe ablöschen, Sahne zugeben und mit angerührter Stärke binden.',
      'Fleisch zurück in die Sauce geben und 1 Min. ziehen lassen. Baby-Portion entnehmen, Rest mit Zitronensaft, Salz und Pfeffer abschmecken und mit Petersilie und Rösti servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Fleisch und Rösti werden in der Pfanne gebraten.',
      steps: [
        ['Kartoffeln in Stücken in den Mixtopf geben und raspeln, gut ausdrücken.', '4 Sek.', '', 'Stufe 4', ''],
        ['Rösti in der Pfanne pro Seite 8–10 Min. braten; Fleischstreifen separat scharf anbraten.', '', '', '', ''],
        ['Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Champignonscheiben zugeben und dünsten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe, Sahne und Speisestärke zugeben und andicken.', '4 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Fleisch zugeben und erwärmen, Baby-Portion entnehmen, dann würzen.', '2 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Geschnetzeltes ohne Salz mit Sauce und gekochter Kartoffel pürieren; Pilze fein hacken. Kleinkind (1–3 J.): Fleisch in kleine Stücke schneiden, Rösti in Streifen als Fingerfood.',
    baby: 2,
  },
  {
    id: 'schweinefilet-suess-sauer',
    n: 'Schweinefilet süß-sauer mit Ananas & Reis',
    img: { wiki: 'Sweet and sour pork', q: 'sweet and sour pork pineapple peppers rice' },
    ck: 'Schweinefleisch süß-sauer',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['kinderliebling'],
    i: [['schweinefilet', 160], ['ananas', 80], ['paprika', 120], ['zwiebel', 30], ['karotte', 40], ['tomatenmark', 10], ['essig', 10], ['sojasauce', 10], ['speisestaerke', 8], ['ahornsirup', 6], ['reis', 60], ['rapsoel', 8]],
    s: [
      'Reis nach Packungsangabe garen. Schweinefilet in 2 cm große Würfel schneiden und in der Hälfte der Speisestärke wenden.',
      'Paprika und Zwiebel in Stücke, Karotte in dünne Scheiben, Ananas in Würfel schneiden.',
      'Für die Sauce Tomatenmark, Essig, Sojasauce, Ahornsirup, restliche Stärke und 80 ml Wasser verrühren.',
      'Öl im Wok erhitzen, Fleisch 4 Min. rundum goldbraun braten und herausnehmen. Gemüse 3 Min. pfannenrühren. Baby-Portion Fleisch und Gemüse vor der Sauce entnehmen.',
      'Ananas, Fleisch und Sauce zugeben, 1–2 Min. aufkochen, bis die Sauce glänzt, und mit Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Fleisch wird im Wok gebraten.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen, Paprika, Zwiebel und Karotte in den Varoma geben, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Reis und Gemüse warmstellen, Mixtopf leeren. Baby-Portion Gemüse entnehmen.', '', '', '', ''],
        ['Tomatenmark, Essig, Sojasauce, Ahornsirup, Speisestärke und 80 g Wasser in den Mixtopf geben und andicken.', '4 Min.', '100°C', 'Stufe 2', ''],
        ['Fleischwürfel im Wok 4 Min. goldbraun braten.', '', '', '', ''],
        ['Gemüse, Ananas und Sauce zugeben und 1–2 Min. durchschwenken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesoßtes Fleisch und weiches Gemüse mit Reis pürieren oder als Fingerfood; Ananas fein würfeln. Kleinkind (1–3 J.): wenig Sauce, Fleisch klein schneiden – die fruchtige Note kommt gut an.',
    baby: 1,
  },
  {
    id: 'schweine-gyros-pfanne-tzatziki',
    n: 'Gyros-Pfanne vom Schweineschnitzel mit Tzatziki & Reis',
    img: { wiki: 'Gyros', q: 'pork gyros pan tzatziki rice' },
    ck: 'Gyros Pfanne',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['kinderliebling'],
    i: [['schweineschnitzel', 160], ['zwiebel', 40], ['paprika', 80], ['gewuerze', 4], ['olivenoel', 8], ['reis', 55], ['griech_joghurt', 80], ['gurke', 70], ['knoblauch', 3], ['tomate', 60], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Reis nach Packungsangabe garen.',
      'Fleisch in feine Streifen schneiden und mit Gyros-Gewürz (Paprika, Oregano, Thymian, Kreuzkümmel) und 4 g Öl mischen. Baby-Portion vorher ohne Gewürz abnehmen.',
      'Für das Tzatziki Gurke raspeln, gut ausdrücken und mit Joghurt, gepresstem Knoblauch und Dill verrühren.',
      'Restliches Öl in einer Pfanne sehr heiß werden lassen, Fleisch 4–5 Min. kräftig braten. Zwiebel- und Paprikastreifen zugeben und 3 Min. mitbraten, salzen.',
      'Mit Reis, Tzatziki und Tomatenspalten servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Gyros wird in der Pfanne gebraten.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen, warmstellen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Mixtopf leeren. Gurke und Knoblauch zerkleinern und gut ausdrücken.', '4 Sek.', '', 'Stufe 5', ''],
        ['Joghurt und Dill zugeben und verrühren, umfüllen.', '10 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Baby-Fleisch ungewürzt beiseitelegen, Rest würzen und in der heißen Pfanne 4–5 Min. braten.', '', '', '', ''],
        ['Zwiebel und Paprika zugeben und 3 Min. mitbraten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Fleischstreifen durchbraten und als Fingerfood oder mit Reis und Joghurt pürieren. Kleinkind (1–3 J.): Fleisch klein schneiden, Tzatziki ohne Knoblauch als Dip.',
    baby: 2,
  },
  {
    id: 'hack-gnocchi-pfanne-spinat',
    n: 'Hack-Gnocchi-Pfanne mit Spinat & Tomaten',
    img: { wiki: 'Gnocchi', q: 'gnocchi ground beef spinach tomato skillet' },
    ck: 'Gnocchi Hackfleisch Pfanne',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling'],
    i: [['rinderhack', 140], ['gnocchi', 160], ['spinat', 80], ['kirschtomaten', 100], ['zwiebel', 30], ['knoblauch', 4], ['passierte_tomaten', 80], ['mozzarella', 25], ['olivenoel', 5], ['gewuerze', 2], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Zwiebel und Knoblauch fein würfeln, Kirschtomaten halbieren.',
      'Öl in einer großen Pfanne erhitzen, Gnocchi 5 Min. goldbraun braten und herausnehmen.',
      'Hack im Bratfett 5 Min. krümelig anbraten, Zwiebel und Knoblauch 2 Min. mitbraten.',
      'Passierte Tomaten und Kirschtomaten zugeben, 5 Min. köcheln, Spinat unterheben und zusammenfallen lassen. Baby-Portion entnehmen.',
      'Gnocchi untermischen, mit Oregano, Salz und Pfeffer würzen, Mozzarella darüberzupfen, zugedeckt 2 Min. schmelzen lassen und mit Basilikum servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Gnocchi werden in der Pfanne knusprig gebraten.',
      steps: [
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hack zugeben und anbraten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Passierte Tomaten und Kirschtomaten zugeben und köcheln.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Spinat zugeben und garen.', '2 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen, Rest würzen.', '', '', '', ''],
        ['Gnocchi in der Pfanne goldbraun braten, Hacksauce untermischen, mit Mozzarella überbacken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Gnocchi kochen statt braten und halbieren (BLW), Hack-Spinat-Sauce ungesalzen dazu oder alles pürieren. Kleinkind (1–3 J.): Gnocchi vierteln, Kirschtomaten klein schneiden.',
    baby: 2,
  },
  {
    id: 'steak-suesskartoffel-wedges',
    n: 'Hüftsteak mit Süßkartoffel-Wedges & Kräuterquark-Dip',
    img: { wiki: 'Steak', q: 'sirloin steak sweet potato wedges herb dip' },
    ck: 'Steak Süßkartoffel',
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    i: [['rindersteak', 170], ['suesskartoffel', 180], ['brokkoli', 120], ['magerquark', 60], ['kraeuter', 5], ['olivenoel', 9], ['gewuerze', 2], ['salz', 1], ['zitronensaft', 5]],
    s: [
      'Ofen auf 220 °C Umluft vorheizen. Süßkartoffeln in Spalten schneiden, mit 6 g Öl und Paprikapulver mischen und 25 Min. backen, nach der Hälfte wenden.',
      'Brokkoli in Röschen teilen und 6 Min. dämpfen.',
      'Quark mit gehackten Kräutern, Zitronensaft und 1 EL Wasser verrühren.',
      'Steak trocken tupfen, in einer Grillpfanne mit restlichem Öl pro Seite 3–4 Min. braten und 5 Min. ruhen lassen.',
      'Baby-/Kleinkind-Fleisch ungewürzt abschneiden. Steak salzen, pfeffern, aufschneiden und mit Wedges, Brokkoli und Dip servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Wedges backen im Ofen, das Steak brät in der Pfanne.',
      steps: [
        ['Süßkartoffel-Wedges mit Öl und Paprika bei 220 °C 25 Min. backen.', '', '', '', ''],
        ['500 g Wasser in den Mixtopf füllen, Brokkoli in den Varoma legen, aufsetzen und dämpfen.', '12 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren, Kräuter zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Quark, Zitronensaft und 15 g Wasser zugeben und verrühren.', '15 Sek.', '', 'Stufe 3', ''],
        ['Steak in der Grillpfanne pro Seite 3–4 Min. braten, ruhen lassen und aufschneiden.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Steak gut durchbraten und in dünne Streifen schneiden, weiche Süßkartoffel-Wedges ohne Kruste und Brokkoliröschen sind perfektes BLW-Fingerfood. Kleinkind (1–3 J.): Fleisch klein schneiden, Wedges in Quark dippen.',
    baby: 2,
  },
  {
    id: 'larb-rinderhack',
    n: 'Larb (thailändischer Hacksalat) mit Rinderhack & Klebreis',
    img: { wiki: 'Larb', q: 'larb thai minced beef salad lettuce' },
    ck: 'Larb',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['rinderhack', 160], ['sushireis', 60], ['limette', 25], ['fischsauce', 8], ['rote_zwiebel', 25], ['fruehlingszwiebel', 15], ['kraeuter', 8], ['chili_frisch', 3], ['salat', 60], ['gurke', 80], ['rapsoel', 4], ['reis', 8]],
    s: [
      'Sushireis nach Packungsangabe garen. 8 g rohen Reis in einer trockenen Pfanne goldbraun rösten und im Mörser fein mahlen.',
      'Öl in einer Pfanne erhitzen, Hack 5–6 Min. krümelig und durchgaren, mit 2 EL Wasser lösen. Baby-Portion jetzt entnehmen.',
      'Pfanne vom Herd nehmen, Hack mit Limettensaft, Fischsauce und Chili mischen.',
      'Fein geschnittene rote Zwiebel, Frühlingszwiebel, Minze und Koriander sowie das Reispulver unterheben.',
      'In Salatblättern mit Gurkenscheiben und Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Reispulver wird in der Pfanne geröstet.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen, warmstellen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Mixtopf leeren. Gerösteten Reis in den trockenen Mixtopf geben und mahlen, umfüllen.', '20 Sek.', '', 'Stufe 10', ''],
        ['Öl und Hack in den Mixtopf geben und garen.', '7 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen.', '', '', '', ''],
        ['Limettensaft, Fischsauce, Chili, Zwiebeln, Kräuter und Reispulver zugeben und vermischen.', '15 Sek.', '', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hack ohne Fischsauce und Chili mit Reis zu kleinen Bällchen formen. Kleinkind (1–3 J.): Hack ungewürzt mit etwas Limette, Reis und Gurkensticks; Kräuter fein gehackt.',
    baby: 1,
  },
  {
    id: 'mapo-tofu-rinderhack',
    n: 'Mapo Tofu mit Rinderhack & Reis',
    img: { wiki: 'Mapo doufu', q: 'mapo tofu minced beef rice' },
    ck: 'Mapo Tofu',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 2,
    i: [['tofu', 150], ['rinderhack', 90], ['knoblauch', 5], ['ingwer', 6], ['fruehlingszwiebel', 20], ['sojasauce', 12], ['sriracha', 6], ['speisestaerke', 5], ['gemuesebruehe', 120], ['reis', 55], ['pak_choi', 100], ['rapsoel', 6], ['sesamoel', 2]],
    s: [
      'Reis nach Packungsangabe garen. Tofu in 2 cm große Würfel schneiden und 2 Min. in leicht gesalzenem Wasser ziehen lassen, abtropfen.',
      'Öl im Wok erhitzen, Hack 4 Min. krümelig braten, fein gehackten Knoblauch, Ingwer und Frühlingszwiebel-Weiß 1 Min. mitbraten.',
      'Mit Brühe und Sojasauce ablöschen, Tofu vorsichtig einlegen und 4 Min. köcheln. Pak Choi in Streifen zugeben. Baby-Portion vor Chili entnehmen.',
      'Chilisauce zugeben, mit angerührter Stärke binden und mit Sesamöl beträufeln.',
      'Mit Frühlingszwiebelgrün bestreuen und mit Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen, Pak Choi in den Varoma legen, aufsetzen und garen. Warmstellen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Mixtopf leeren. Knoblauch, Ingwer und Frühlingszwiebel-Weiß zerkleinern.', '5 Sek.', '', 'Stufe 7', ''],
        ['Öl und Hack zugeben und anbraten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe, Sojasauce und Tofuwürfel zugeben und garen.', '5 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen.', '', '', '', ''],
        ['Chilisauce und angerührte Speisestärke zugeben und andicken.', '2 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Tofuwürfel und Hack ohne Sojasauce und Chili sind weich und ideal als Fingerfood, oder mit Reis pürieren. Kleinkind (1–3 J.): ohne Chili, Sojasauce sparsam, Tofu mit der Gabel zerdrücken.',
    baby: 1,
  },
  {
    id: 'gyudon-rind-reis',
    n: 'Gyudon (japanische Rindfleisch-Reisschale) mit Ei',
    img: { wiki: 'Gyūdon', q: 'gyudon beef bowl onion rice egg' },
    ck: 'Gyudon',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['rindersteak', 140], ['zwiebel', 80], ['sojasauce', 15], ['ahornsirup', 5], ['ingwer', 5], ['gemuesebruehe', 100], ['reis', 65], ['ei', 50], ['fruehlingszwiebel', 15], ['spinat', 60], ['rapsoel', 3]],
    s: [
      'Reis nach Packungsangabe garen. Rindfleisch leicht angefroren hauchdünn aufschneiden, Zwiebel in Streifen schneiden.',
      'Ei 7 Min. wachsweich kochen (für Baby/Kleinkind 10 Min. hart), abschrecken und pellen.',
      'Öl in einer Pfanne erhitzen, Zwiebel 3 Min. glasig dünsten. Brühe, Sojasauce, Ahornsirup und geriebenen Ingwer zugeben und aufkochen. Baby-Fleisch vorher separat in Wasser garen.',
      'Rindfleisch in den Sud geben und 2–3 Min. sanft garen, Spinat kurz mit zusammenfallen lassen.',
      'Reis in Schalen füllen, Fleisch und Zwiebeln mit etwas Sud darauf verteilen, mit halbiertem Ei und Frühlingszwiebel servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen, Eier in den Varoma legen, aufsetzen und garen (Eier nach 12 Min. herausnehmen).', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Reis warmstellen, Mixtopf leeren. Zwiebelstreifen und Öl zugeben und dünsten.', '3 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe, Sojasauce, Ahornsirup und Ingwer zugeben und aufkochen.', '4 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Rindfleischscheiben und Spinat zugeben und garen.', '3 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Auf dem Reis anrichten, mit Ei und Frühlingszwiebel servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): in ungesalzenem Wasser gegartes Rindfleisch mit Reis, Spinat und hartem Eigelb pürieren oder als Reisbällchen anbieten. Kleinkind (1–3 J.): Fleisch klein schneiden, Sud stark verdünnt, Ei hart gekocht.',
    baby: 1,
  },
  {
    id: 'keema-matar',
    n: 'Keema Matar (indisches Hack-Erbsen-Curry) mit Reis',
    img: { wiki: 'Keema', q: 'keema matar minced meat peas curry rice' },
    ck: 'Keema',
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['mealprep'],
    i: [['rinderhack', 150], ['erbsen', 80], ['zwiebel', 50], ['knoblauch', 5], ['ingwer', 6], ['tomaten_dose', 150], ['currypulver', 5], ['joghurt', 50], ['reis', 55], ['rapsoel', 6], ['salz', 1], ['kraeuter', 4]],
    s: [
      'Reis nach Packungsangabe garen. Zwiebel, Knoblauch und Ingwer fein hacken.',
      'Öl in einer Pfanne erhitzen, Zwiebel 5 Min. goldbraun braten, Knoblauch und Ingwer 1 Min. mitbraten.',
      'Hack zugeben und 5 Min. krümelig anbraten, Garam Masala, Kurkuma und Kreuzkümmel 1 Min. mitrösten.',
      'Tomaten zugeben und 10 Min. köcheln, Erbsen 5 Min. mitgaren. Baby-/Kleinkind-Portion ohne Salz entnehmen.',
      'Rest salzen, mit Joghurt und Koriander servieren und mit Reis anrichten.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen, warmstellen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Mixtopf leeren. Zwiebel, Knoblauch und Ingwer zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Hack und Gewürze zugeben und anbraten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomaten zugeben und köcheln, nach 10 Min. Erbsen zugeben.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen, Rest salzen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes, mild gewürztes Keema mit Reis und Joghurt pürieren oder als Reisbällchen; Erbsen zerdrücken. Kleinkind (1–3 J.): Curry mild halten, Erbsen leicht anquetschen.',
    baby: 2,
  },
  {
    id: 'rinder-madras-curry',
    n: 'Leichtes Rinder-Madras-Curry mit Spinat & Basmatireis',
    img: { wiki: 'Madras curry sauce', q: 'beef madras curry rice' },
    ck: 'Rindfleisch Curry',
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 100, d: 2,
    st: ['mealprep', 'comfort'],
    i: [['rindergulasch', 160], ['zwiebel', 60], ['knoblauch', 5], ['ingwer', 6], ['tomaten_dose', 150], ['currypulver', 6], ['chili_frisch', 3], ['spinat', 60], ['kokosmilch_light', 60], ['reis', 55], ['rapsoel', 6], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Rindfleisch in 2 cm Würfel schneiden. Zwiebel, Knoblauch und Ingwer fein hacken.',
      'Öl im Schmortopf erhitzen, Fleisch portionsweise 5 Min. anbraten. Zwiebel 4 Min. mitbraten, Knoblauch, Ingwer und Currypulver 1 Min. anrösten.',
      'Tomaten, Kokosmilch und 150 ml Wasser zugeben und zugedeckt 70 Min. sanft schmoren, bis das Fleisch zart ist.',
      'Reis nach Packungsangabe garen. Spinat die letzten 2 Min. unterheben. Baby-/Kleinkind-Portion vor Chili und Salz entnehmen.',
      'Rest mit gehackter Chili und Salz abschmecken, mit Koriander und Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Rindfleisch zugeben und anbraten, ohne Messbecher.', '6 Min.', '160°C', 'Stufe 1', 'Anbraten'],
        ['Currypulver zugeben und anrösten.', '1 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomaten, Kokosmilch und 150 g Wasser zugeben, Garkörbchen als Spritzschutz aufsetzen und schmoren.', '70 Min.', '98°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Spinat zugeben und garen.', '2 Min.', '98°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen, dann Chili und Salz zugeben. Reis separat im Topf garen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): mürbe geschmortes Fleisch ohne Chili und Salz mit Spinat und Reis pürieren. Kleinkind (1–3 J.): Fleisch zerzupfen, mild mit etwas mehr Kokosmilch, Reis dazu.',
    baby: 1,
  },
  {
    id: 'lamm-rogan-josh',
    n: 'Lamm-Rogan-Josh light mit Basmatireis & Raita',
    img: { wiki: 'Rogan josh', q: 'lamb rogan josh rice raita' },
    ck: 'Rogan Josh',
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 100, d: 2,
    st: ['comfort'],
    i: [['fleisch_lamm', 160], ['zwiebel', 60], ['knoblauch', 5], ['ingwer', 6], ['tomaten_dose', 120], ['tomatenmark', 10], ['currypulver', 6], ['joghurt', 80], ['gurke', 50], ['reis', 55], ['rapsoel', 6], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Lammfleisch in 2–3 cm Würfel schneiden, mit 30 g Joghurt und der Hälfte des Currypulvers 30 Min. marinieren.',
      'Öl im Schmortopf erhitzen, fein gehackte Zwiebel 6 Min. bräunen, Knoblauch, Ingwer, Tomatenmark und restliche Gewürze (Paprika, Kardamom, Zimt) 1 Min. anrösten.',
      'Fleisch mit Marinade zugeben und 5 Min. anbraten, Tomaten und 150 ml Wasser zugeben und zugedeckt 60–70 Min. schmoren.',
      'Reis garen. Für die Raita restlichen Joghurt mit geriebener Gurke und Minze verrühren.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest salzen und mit Reis und Raita servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten, dann Tomatenmark und Gewürze zugeben.', '6 Min.', '120°C', 'Stufe 1', ''],
        ['Mariniertes Lamm zugeben und anbraten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomaten und 150 g Wasser zugeben, Garkörbchen als Spritzschutz aufsetzen und schmoren.', '65 Min.', '98°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen, Rest salzen. Reis separat garen.', '', '', '', ''],
        ['Für die Raita Mixtopf spülen, Gurke und Minze zerkleinern, Joghurt zugeben und verrühren.', '5 Sek.', '', 'Stufe 5', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): zart geschmortes Lamm ohne Salz mit Reis und Joghurt pürieren oder zerzupft als Fingerfood. Kleinkind (1–3 J.): mild würzen, Fleisch fein zerzupfen, Raita als Dip.',
    baby: 2,
  },
  {
    id: 'lamm-tajine-kichererbsen',
    n: 'Lamm-Tajine mit Kichererbsen, Datteln & Couscous',
    img: { wiki: 'Tajine', q: 'lamb tagine chickpeas dates couscous' },
    ck: 'Lamm Tajine',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 100, d: 2,
    st: ['comfort', 'mealprep'],
    i: [['fleisch_lamm', 150], ['kichererbsen', 40], ['zwiebel', 50], ['knoblauch', 4], ['ingwer', 4], ['karotte', 80], ['zucchini', 80], ['tomaten_dose', 120], ['datteln', 10], ['gewuerze', 4], ['zimt', 1], ['couscous', 45], ['olivenoel', 6], ['salz', 1], ['kraeuter', 4]],
    s: [
      'Lamm in 3 cm Würfel schneiden. Zwiebel und Knoblauch fein hacken, Karotten in dicke Scheiben, Zucchini in Stücke schneiden.',
      'Öl in Tajine oder Schmortopf erhitzen, Fleisch rundum 5 Min. anbraten. Zwiebel 4 Min. mitdünsten, Knoblauch, Ingwer, Kreuzkümmel, Koriander, Paprika und Zimt 1 Min. anrösten.',
      'Tomaten, Karotten und 200 ml Wasser zugeben und zugedeckt 60 Min. sanft schmoren.',
      'Zucchini, abgespülte Kichererbsen und gehackte Datteln zugeben und weitere 15 Min. garen. Couscous mit der 1,2-fachen Menge kochendem Wasser übergießen und 5 Min. quellen lassen.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen. Rest salzen und mit Couscous, Koriander und Petersilie servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Couscous wird nur mit heißem Wasser übergossen.',
      steps: [
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Lammwürfel zugeben und anbraten, ohne Messbecher.', '6 Min.', '160°C', 'Stufe 1', 'Anbraten'],
        ['Gewürze zugeben und anrösten.', '1 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomaten, Karotten und 200 g Wasser zugeben, Garkörbchen als Spritzschutz aufsetzen und schmoren.', '60 Min.', '98°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Zucchini, Kichererbsen und Datteln zugeben und weitergaren.', '15 Min.', '98°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen, Rest salzen. Couscous mit heißem Wasser quellen lassen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): mürbes Lamm mit Karotte, Zucchini und Kichererbsen ohne Salz pürieren; für BLW weiche Karottenscheiben und zerzupftes Fleisch. Kleinkind (1–3 J.): Kichererbsen zerdrücken, Datteln fein gehackt.',
    baby: 2,
  },
  {
    id: 'kaese-lauch-suppe-hack',
    n: 'Käse-Lauch-Suppe light mit Rinderhack',
    img: { wiki: 'Leek soup', q: 'cheese leek soup minced meat' },
    ck: 'Käse-Lauch-Suppe',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['comfort', 'mealprep', 'kinderliebling'],
    i: [['rinderhack', 150], ['lauch', 150], ['zwiebel', 30], ['champignons', 60], ['kartoffel', 100], ['frischkaese_light', 40], ['gemuesebruehe', 350], ['rapsoel', 5], ['gewuerze', 2], ['salz', 0.5], ['vollkornbrot', 40]],
    s: [
      'Lauch längs halbieren, gründlich waschen und in Ringe schneiden. Zwiebel würfeln, Champignons in Scheiben, Kartoffel in kleine Würfel schneiden.',
      'Öl in einem Topf erhitzen, Hack 5 Min. krümelig anbraten, Zwiebel 2 Min. mitbraten.',
      'Lauch, Champignons und Kartoffel zugeben, mit Brühe ablöschen und 15 Min. köcheln.',
      'Frischkäse einrühren und schmelzen lassen, nicht mehr kochen. Baby-/Kleinkind-Portion entnehmen.',
      'Rest mit Muskat, Pfeffer und wenig Salz abschmecken und mit Brot servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Bei Bedarf in zwei Durchgängen (max. 2,2 l).',
      steps: [
        ['Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hack zugeben und anbraten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Lauchringe, Champignons, Kartoffelwürfel und Brühe zugeben und garen.', '18 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Frischkäse zugeben und unterrühren.', '2 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen, dann mit Muskat, Pfeffer und Salz abschmecken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Suppe mit ungesalzener Brühe kochen bzw. vor dem Würzen entnehmen und fein pürieren. Kleinkind (1–3 J.): stückig servieren, Brot zum Tunken; Brühe salzarm wählen.',
    baby: 2,
  },
  {
    id: 'kartoffel-hack-auflauf-brokkoli',
    n: 'Kartoffel-Hack-Auflauf mit Brokkoli',
    img: { wiki: 'Casserole', q: 'potato ground beef broccoli casserole cheese' },
    ck: 'Kartoffel Hackfleisch Auflauf',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 60, d: 1,
    st: ['comfort', 'kinderliebling', 'mealprep'],
    i: [['rinderhack', 140], ['kartoffel', 200], ['brokkoli', 120], ['zwiebel', 30], ['tomatenmark', 10], ['milch', 80], ['ei', 25], ['gouda_light', 20], ['rapsoel', 5], ['gewuerze', 3], ['salz', 1]],
    s: [
      'Ofen auf 200 °C vorheizen. Kartoffeln schälen, in 3 mm Scheiben schneiden und 8 Min. vorgaren. Brokkoli in Röschen teilen und die letzten 3 Min. mitgaren.',
      'Öl in einer Pfanne erhitzen, Hack mit Zwiebel 6 Min. krümelig braten, Tomatenmark 1 Min. mitrösten und mit Paprika und Majoran würzen.',
      'Kartoffeln, Hack und Brokkoli schichtweise in eine Auflaufform geben.',
      'Milch mit Ei und Muskat verquirlen, darübergießen und mit Käse bestreuen.',
      '25 Min. goldbraun backen, bis der Guss gestockt ist. Baby-Portion ohne Salz aus einer Ecke entnehmen (Salz nur auf die Erwachsenenhälfte).',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Gebacken wird im Ofen.',
      steps: [
        ['500 g Wasser in den Mixtopf füllen, Kartoffelscheiben und Brokkoli in den Varoma legen, aufsetzen und vorgaren.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren, Zwiebel zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hack zugeben und anbraten, Tomatenmark und Gewürze zugeben.', '7 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Alles in die Form schichten. Mixtopf spülen, Milch, Eier und Muskat verrühren und darübergießen.', '10 Sek.', '', 'Stufe 4', ''],
        ['Mit Käse bestreuen und bei 200 °C 25 Min. backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Auflauf ohne Salz ist weich; zerdrücken oder Brokkoliröschen und Kartoffelscheiben als Fingerfood, Ei vollständig gestockt. Kleinkind (1–3 J.): in kleinen Würfeln servieren.',
    baby: 2,
  },
  {
    id: 'koenigsberger-klopse',
    n: 'Königsberger Klopse light mit Kartoffeln & Rote-Bete-Salat',
    img: { wiki: 'Königsberger Klopse', q: 'koenigsberger klopse meatballs white sauce potatoes beetroot' },
    ck: 'Königsberger Klopse',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 50, d: 2,
    st: ['comfort'],
    i: [['rinderhack', 150], ['ei', 15], ['paniermehl', 12], ['zwiebel', 30], ['gemuesebruehe', 300], ['milch', 50], ['speisestaerke', 6], ['senf', 3], ['zitronensaft', 6], ['kartoffel', 200], ['rote_bete', 60], ['essig', 3], ['kraeuter', 3], ['salz', 1], ['gewuerze', 1]],
    s: [
      'Zwiebel fein reiben, mit Hack, Ei, Paniermehl und Pfeffer verkneten und mit nassen Händen zu 4 cm großen Klopsen formen.',
      'Brühe mit Lorbeer aufkochen, Klopse einlegen und bei schwacher Hitze 15 Min. gar ziehen lassen. Herausheben und warmhalten.',
      'Kartoffeln 20 Min. kochen. Rote Bete würfeln und mit Essig und Petersilie mischen.',
      '300 ml Brühe abmessen, Milch zugeben, mit angerührter Stärke binden und Senf einrühren. Baby-Portion Sauce und Klopse entnehmen.',
      'Rest mit Zitronensaft und Salz abschmecken (klassisch mit Kapern), Klopse in der Sauce erwärmen und mit Kartoffeln und Rote-Bete-Salat servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Klopse garen im Varoma.',
      steps: [
        ['Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hack, Ei, Paniermehl und Pfeffer zugeben und vermengen, Klopse formen.', '30 Sek.', '', 'Teigknetstufe', 'Teigkneten'],
        ['1200 g Brühe in den Mixtopf geben, Kartoffeln im Garkörbchen einhängen, Klopse in Varoma und Einlegeboden legen, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
        ['Klopse und Kartoffeln warmstellen, Brühe bis auf 300 g abgießen.', '', '', '', ''],
        ['Milch, Speisestärke und Senf zugeben und andicken.', '4 Min.', '100°C', 'Stufe 3', ''],
        ['Baby-Portion entnehmen, dann Zitronensaft und Salz zugeben und unterrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Klopse in ungesalzenem Wasser garen, sie sind weich und ideal als Fingerfood oder zerdrückt mit Kartoffel und Sauce; Ei durchgaren. Kleinkind (1–3 J.): ohne Kapern, Klopse vierteln, Rote Bete nur wenig (färbt).',
    baby: 2,
  },
  {
    id: 'rinderhuefte-rosenkohl-stampf',
    n: 'Rinderhüfte mit Rosenkohl & Kartoffel-Sellerie-Stampf',
    img: { wiki: 'Brussels sprout', q: 'beef sirloin brussels sprouts mashed potatoes' },
    ck: 'Rinderhüfte',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    i: [['rinderfilet', 160], ['rosenkohl', 150], ['kartoffel', 180], ['sellerie', 40], ['milch', 60], ['butter', 4], ['rapsoel', 6], ['senf', 3], ['gemuesebruehe', 60], ['salz', 1], ['gewuerze', 1]],
    s: [
      'Kartoffeln und Sellerie schälen, würfeln und 20 Min. garen. Abgießen und mit warmer Milch, Butter und Muskat zu Stampf zerdrücken.',
      'Rosenkohl putzen, halbieren und 6 Min. dämpfen.',
      'Rinderhüfte in einer Pfanne mit 4 g Öl rundum 6 Min. scharf anbraten und im Ofen bei 140 °C 12–15 Min. auf 56 °C Kerntemperatur garen, 5 Min. ruhen lassen.',
      'Rosenkohl im Bratensatz mit restlichem Öl 3 Min. anrösten, mit Brühe und Senf ablöschen.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen. Fleisch aufschneiden, salzen, pfeffern und mit Rosenkohl und Stampf servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Fleisch wird in der Pfanne und im Ofen gegart.',
      steps: [
        ['Kartoffel- und Selleriewürfel mit Milch und 200 g Wasser in den Mixtopf geben, Rosenkohl in den Varoma legen, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Varoma abnehmen. Butter und Muskat zugeben, Flüssigkeit ggf. vorher teils abgießen und stampfen.', '15 Sek.', '', 'Stufe 4', ''],
        ['Rinderhüfte anbraten und bei 140 °C 12–15 Min. im Ofen garen.', '', '', '', ''],
        ['Rosenkohl in der Pfanne mit Senf und Brühe kurz anrösten.', '', '', '', ''],
        ['Baby-Portion ungesalzen entnehmen, Rest würzen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fleisch gut durchgaren und mit Stampf pürieren; Rosenkohl weich gegart und geviertelt als Fingerfood (kann blähen). Kleinkind (1–3 J.): Fleisch in kleine Stücke, Rosenkohl klein schneiden.',
    baby: 2,
  },
  {
    id: 'schweinefilet-fenchel-orange-quinoa',
    n: 'Schweinefilet mit Fenchel-Orangen-Gemüse & Quinoa',
    img: { wiki: 'Fennel', q: 'pork tenderloin fennel orange quinoa' },
    ck: 'Schweinefilet Fenchel',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    i: [['schweinefilet', 170], ['fenchel', 150], ['orange', 80], ['rote_zwiebel', 25], ['quinoa', 55], ['olivenoel', 8], ['gemuesebruehe', 80], ['kraeuter', 4], ['salz', 1], ['gewuerze', 1]],
    s: [
      'Quinoa waschen und in doppelter Menge Wasser 15 Min. garen.',
      'Fenchel in dünne Spalten, Zwiebel in Streifen schneiden. Orange filetieren, den Saft auffangen.',
      'Schweinefilet mit 4 g Öl rundum 4 Min. anbraten, dann bei 160 °C im Ofen 12–15 Min. bis 63 °C Kerntemperatur garen.',
      'Restliches Öl in der Pfanne erhitzen, Fenchel und Zwiebel 5 Min. anbraten, mit Brühe und Orangensaft ablöschen und 5 Min. bissfest schmoren. Orangenfilets unterheben.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen. Filet in Scheiben schneiden, salzen und mit Fenchelgemüse, Quinoa und Fenchelgrün servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Das Filet wird angebraten und im Ofen fertig gegart.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Quinoa im Garkörbchen einhängen und garen, warmstellen.', '18 Min.', '100°C', 'Stufe 4', ''],
        ['Mixtopf leeren. Zwiebelstreifen und Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Fenchelspalten, Brühe und Orangensaft zugeben und garen.', '10 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Orangenfilets unterheben.', '10 Sek.', '', 'Sanftrührstufe', 'Linkslauf'],
        ['Filet anbraten und im Ofen bei 160 °C 12–15 Min. garen, Baby-Portion ungesalzen abnehmen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): weich geschmorter Fenchel und dünne Filetstreifen als Fingerfood oder mit Quinoa pürieren; Orangenfilets ohne Haut. Kleinkind (1–3 J.): Fleisch und Fenchel klein schneiden.',
    baby: 2,
  },
  {
    id: 'saltimbocca-zitronenspinat-gnocchi',
    n: 'Schweine-Saltimbocca mit Zitronenspinat & Gnocchi',
    img: { wiki: 'Saltimbocca', q: 'saltimbocca sage ham pork spinach gnocchi' },
    ck: 'Saltimbocca',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 30, d: 2,
    i: [['schweineschnitzel', 150], ['schinken_gekocht', 25], ['kraeuter', 3], ['speisestaerke', 3], ['olivenoel', 8], ['gemuesebruehe', 80], ['zitronensaft', 8], ['spinat', 150], ['knoblauch', 3], ['gnocchi', 150], ['parmesan', 6], ['salz', 0.5], ['gewuerze', 1]],
    s: [
      'Schnitzel in 2 Stücke teilen und dünn klopfen. Mit je einer Scheibe magerem Schinken und einem Salbeiblatt belegen, mit Zahnstocher fixieren und die Unterseite leicht mit Stärke bestäuben.',
      'Gnocchi nach Packungsangabe in kochendem Wasser garen, bis sie oben schwimmen.',
      'Die Hälfte des Öls in einer Pfanne erhitzen, Saltimbocca zuerst auf der Schinkenseite 2 Min., dann auf der anderen Seite 2 Min. braten und warmstellen.',
      'Bratensatz mit Brühe und der Hälfte des Zitronensafts ablöschen und 2 Min. einkochen. Baby-Fleisch ohne Schinken separat braten.',
      'Restliches Öl mit Knoblauch erhitzen, Spinat zusammenfallen lassen und mit restlichem Zitronensaft würzen. Mit Gnocchi, Sauce und Parmesan servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Saltimbocca werden in der Pfanne gebraten.',
      steps: [
        ['1200 g Wasser in den Mixtopf füllen und aufkochen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Gnocchi zugeben und garen, abgießen.', '3 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Knoblauch zerkleinern, Öl zugeben und andünsten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Spinat und Zitronensaft zugeben und garen.', '3 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Saltimbocca in der Pfanne pro Seite 2 Min. braten, mit Brühe und Zitronensaft ablöschen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Schnitzelstück ohne Schinken (salzig) braten und in Streifen schneiden, Gnocchi halbieren, Spinat fein gehackt oder püriert. Kleinkind (1–3 J.): Schinken nur wenig, Fleisch klein schneiden.',
    baby: 1,
  },
  {
    id: 'sloppy-joes-coleslaw',
    n: 'Sloppy Joes light mit Coleslaw',
    img: { wiki: 'Sloppy joe', q: 'sloppy joe sandwich coleslaw' },
    ck: 'Sloppy Joes',
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['kinderliebling'],
    i: [['rinderhack', 150], ['zwiebel', 30], ['paprika', 60], ['passierte_tomaten', 80], ['tomatenmark', 10], ['ketchup', 10], ['senf', 4], ['essig', 3], ['burgerbroetchen', 70], ['weisskohl', 80], ['karotte', 40], ['joghurt', 40], ['rapsoel', 5], ['gewuerze', 2], ['salz', 1]],
    s: [
      'Für den Coleslaw Weißkohl fein hobeln und mit einer Prise Salz kurz durchkneten. Karotte raspeln, mit Joghurt, Senf (1 g) und Essig mischen.',
      'Öl in einer Pfanne erhitzen, Hack 5 Min. krümelig anbraten, Zwiebel und fein gewürfelte Paprika 3 Min. mitbraten.',
      'Passierte Tomaten, Tomatenmark, Ketchup, restlichen Senf und Paprikapulver zugeben und 8 Min. dicklich einkochen. Baby-Portion vor dem Salzen entnehmen.',
      'Brötchen aufschneiden und kurz toasten.',
      'Hackmasse salzen, auf die Brötchen häufen und mit Coleslaw servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Brötchen werden getoastet.',
      steps: [
        ['Weißkohl und Karotte in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Joghurt, etwas Senf und Essig zugeben und vermischen, umfüllen.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Zwiebel und Paprika zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hack zugeben und anbraten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Passierte Tomaten, Tomatenmark, Ketchup, Senf und Gewürze zugeben und einkochen, ohne Messbecher.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen, Rest salzen und in getoastete Brötchen füllen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Hacksauce mit weichem Brötchen-Innenteil oder Kartoffel anbieten; als Mus füttern. Kleinkind (1–3 J.): Brötchen in Streifen schneiden, Coleslaw fein und ohne Senf.',
    baby: 1,
  },
  {
    id: 'enchiladas-rinderhack',
    n: 'Enchiladas mit Rinderhack & schwarzen Bohnen',
    img: { wiki: 'Enchilada', q: 'beef enchiladas corn tortillas oven' },
    ck: 'Enchiladas',
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['kinderliebling', 'mealprep'],
    i: [['rinderhack', 130], ['schwarze_bohnen', 40], ['paprika', 60], ['zwiebel', 30], ['tortilla_mais', 80], ['passierte_tomaten', 120], ['cajun', 4], ['gouda_light', 20], ['griech_joghurt', 40], ['kraeuter', 3], ['rapsoel', 4], ['salz', 1]],
    s: [
      'Ofen auf 200 °C vorheizen. Zwiebel und Paprika fein würfeln.',
      'Öl in einer Pfanne erhitzen, Hack 5 Min. krümelig anbraten, Zwiebel und Paprika 3 Min. mitbraten, abgespülte Bohnen zugeben. Baby-Portion der Füllung ungewürzt entnehmen.',
      'Rest mit der Hälfte des Gewürzes würzen. Passierte Tomaten mit restlichem Gewürz und Salz verrühren.',
      'Tortillas kurz erwärmen, mit Hackmasse füllen, aufrollen und mit der Naht nach unten in eine Form legen.',
      'Tomatensauce darübergießen, mit Käse bestreuen und 15–20 Min. backen. Mit Joghurt und Koriander servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Gebacken wird im Ofen.',
      steps: [
        ['Zwiebel und Paprika in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hack zugeben und anbraten.', '7 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Bohnen zugeben und erwärmen, Baby-Portion ungewürzt entnehmen.', '2 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Hälfte des Gewürzes zugeben und unterrühren, umfüllen.', '10 Sek.', '', 'Stufe 1', 'Linkslauf'],
        ['Passierte Tomaten, restliches Gewürz und Salz im Mixtopf verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Tortillas füllen, aufrollen, mit Sauce und Käse bedecken und bei 200 °C 15–20 Min. backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Füllung mit zerdrückten Bohnen und weicher Tortilla in Streifen anbieten. Kleinkind (1–3 J.): eine Enchilada aus der ungewürzten Füllung mit wenig Käse backen und in Stücke schneiden.',
    baby: 1,
  },
  {
    id: 'pad-kra-pao-rind',
    n: 'Pad Kra Pao mit Rinderhack, Bohnen & Spiegelei',
    img: { wiki: 'Phat kaphrao', q: 'pad kra pao minced beef basil fried egg rice' },
    ck: 'Pad Kra Pao',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['rinderhack', 140], ['gruene_bohnen', 80], ['paprika', 50], ['knoblauch', 5], ['chili_frisch', 3], ['sojasauce', 10], ['austernsauce', 8], ['fischsauce', 4], ['kraeuter', 6], ['reis', 55], ['ei', 50], ['rapsoel', 7]],
    s: [
      'Reis nach Packungsangabe garen. Bohnen in 2 cm Stücke schneiden, Paprika würfeln, Knoblauch und Chili im Mörser grob zerstoßen.',
      'Bohnen 4 Min. vorblanchieren. 5 g Öl im Wok stark erhitzen, Hack 4 Min. krümelig braten.',
      'Bohnen und Paprika zugeben und 2 Min. pfannenrühren. Baby-Portion vor Würzpaste und Saucen entnehmen.',
      'Knoblauch-Chili-Paste, Sojasauce, Austernsauce, Fischsauce und 2 EL Wasser zugeben, 1 Min. braten und Thai-Basilikum unterheben.',
      'Ei im restlichen Öl als Spiegelei braten (für Kinder durchgegart) und mit Reis und Hackpfanne servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Hackpfanne gelingt am besten im heißen Wok.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen, Bohnen in den Varoma legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Mixtopf leeren. Knoblauch und Chili zerkleinern.', '4 Sek.', '', 'Stufe 7', ''],
        ['Hack im Wok krümelig braten, Bohnen und Paprika zugeben. Baby-Portion entnehmen.', '', '', '', ''],
        ['Knoblauch-Chili, Saucen und Basilikum zugeben und 1 Min. braten.', '', '', '', ''],
        ['Spiegeleier in der Pfanne braten und alles mit Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürztes Hack mit weichen Bohnen und Reis zu Bällchen formen, Ei nur durchgegart. Kleinkind (1–3 J.): ohne Chili, Saucen verdünnt, Ei gut durchgebraten.',
    baby: 1,
  },
  {
    id: 'rindergulasch-ossobuco-art-polenta',
    n: 'Rinderschmorgulasch Ossobuco-Art mit Gremolata & Polenta',
    img: { wiki: 'Ossobuco', q: 'ossobuco braised beef gremolata polenta' },
    ck: 'Ossobuco',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 120, d: 2,
    st: ['comfort'],
    i: [['rindergulasch', 170], ['karotte', 60], ['sellerie', 30], ['zwiebel', 40], ['tomaten_dose', 150], ['tomatenmark', 10], ['gemuesebruehe', 150], ['polenta', 50], ['parmesan', 6], ['zitrone', 10], ['knoblauch', 3], ['kraeuter', 5], ['olivenoel', 7], ['salz', 1], ['gewuerze', 1]],
    s: [
      'Rindfleisch in große Würfel schneiden, Karotte, Sellerie und Zwiebel fein würfeln.',
      'Öl im Schmortopf erhitzen, Fleisch rundum 6 Min. kräftig anbraten. Gemüse 4 Min. mitrösten, Tomatenmark 1 Min. anrösten.',
      'Tomaten und Brühe zugeben und zugedeckt bei kleiner Hitze 90 Min. schmoren, bis das Fleisch zerfällt.',
      'Polenta in 200 ml kochende Brühe/Wasser einrühren und 5–10 Min. unter Rühren quellen lassen, Parmesan unterziehen.',
      'Für die Gremolata Petersilie, Zitronenabrieb und Knoblauch fein hacken. Baby-Portion ungesalzen entnehmen, Rest salzen und mit Polenta und Gremolata servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Die Polenta wird nach dem Schmoren im Mixtopf gekocht.',
      steps: [
        ['Petersilie, Zitronenschale und Knoblauch in den Mixtopf geben, zerkleinern und umfüllen (Gremolata).', '4 Sek.', '', 'Stufe 7', ''],
        ['Zwiebel, Karotte und Sellerie zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Fleisch zugeben und anbraten, ohne Messbecher.', '6 Min.', '160°C', 'Stufe 1', 'Anbraten'],
        ['Tomatenmark, Tomaten und Brühe zugeben, Garkörbchen als Spritzschutz aufsetzen und schmoren.', '90 Min.', '98°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Ragout umfüllen und warmhalten, Baby-Portion ungesalzen entnehmen. Mixtopf spülen.', '', '', '', ''],
        ['800 g Wasser und Salz aufkochen.', '8 Min.', '100°C', 'Stufe 1', ''],
        ['Polenta durch die Deckelöffnung einrieseln lassen und garen, Parmesan unterrühren.', '8 Min.', '90°C', 'Stufe 3', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): zartes Schmorfleisch mit Gemüse ungesalzen pürieren, Polenta ohne Parmesan als weichen Brei oder abgekühlt in Sticks geschnitten. Kleinkind (1–3 J.): Fleisch zerzupfen, Gremolata weglassen.',
    baby: 2,
  },
  {
    id: 'char-siu-schweinefilet-pak-choi',
    n: 'Char Siu Schweinefilet mit Pak Choi & Reis',
    img: { wiki: 'Char siu', q: 'char siu pork tenderloin bok choy rice' },
    ck: 'Char Siu',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 50, d: 2,
    i: [['schweinefilet', 170], ['sojasauce', 12], ['honig', 8], ['tomatenmark', 8], ['knoblauch', 4], ['ingwer', 4], ['gewuerze', 1], ['pak_choi', 150], ['reis', 60], ['sesamoel', 3], ['rapsoel', 3], ['sesam', 3], ['fruehlingszwiebel', 15]],
    s: [
      'Sojasauce, Honig, Tomatenmark, geriebenen Knoblauch und Ingwer sowie Fünf-Gewürze-Pulver verrühren. Filet darin mind. 30 Min. marinieren (Baby-Stück vorher ohne Marinade abschneiden).',
      'Ofen auf 200 °C vorheizen. Filet auf ein Gitter über einer Fettpfanne legen und 20–25 Min. bis 63 °C Kerntemperatur braten, nach 10 Min. mit restlicher Marinade bestreichen.',
      'Reis nach Packungsangabe garen.',
      'Pak Choi längs vierteln und mit Rapsöl im Wok 3 Min. braten, mit Sesamöl beträufeln.',
      'Filet 5 Min. ruhen lassen, in dünne Scheiben schneiden und mit Reis, Pak Choi, Sesam und Frühlingszwiebeln servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Das Filet wird im Ofen gebraten.',
      steps: [
        ['Knoblauch und Ingwer in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 7', ''],
        ['Sojasauce, Honig, Tomatenmark und Gewürz zugeben, verrühren und das Filet darin marinieren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Filet bei 200 °C 20–25 Min. im Ofen braten.', '', '', '', ''],
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen, Pak Choi in den Varoma legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Pak Choi mit Sesamöl beträufeln, Filet aufschneiden und alles anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (unter 12 Mon.): KEIN Honig – Baby-Stück ohne Marinade separat braten, in dünne Streifen schneiden und mit weichem Pak Choi und Reis anbieten. Kleinkind (1–3 J.): Filet mit wenig Marinade, klein geschnitten.',
    baby: 1,
  },
  {
    id: 'beef-rendang-light',
    n: 'Beef Rendang light mit Reis & Gurke',
    img: { wiki: 'Rendang', q: 'beef rendang rice cucumber' },
    ck: 'Rendang',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 150, d: 3,
    st: ['comfort', 'mealprep'],
    i: [['rindergulasch', 170], ['kokosmilch_light', 100], ['zwiebel', 40], ['knoblauch', 5], ['ingwer', 8], ['chili_frisch', 3], ['currypulver', 5], ['limette', 10], ['kokosraspeln', 5], ['reis', 55], ['gurke', 80], ['rapsoel', 5], ['salz', 1]],
    s: [
      'Zwiebel, Knoblauch, Ingwer und Chili (Baby-Anteil ohne Chili beachten) mit 2 EL Wasser zu einer feinen Paste pürieren.',
      'Öl im Schmortopf erhitzen, Gewürzpaste und Currypulver (Kurkuma, Koriander, Zimt) 4 Min. unter Rühren anbraten.',
      'Fleisch in 3 cm Würfeln zugeben und 5 Min. rundum anbraten. Kokosmilch und 200 ml Wasser zugeben, Limettenschale zugeben und offen 2 Std. bei kleiner Hitze schmoren, bis die Sauce fast vollständig eingekocht ist.',
      'Kokosraspeln in einer trockenen Pfanne goldbraun rösten und unterrühren. Reis garen.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest salzen und mit Reis, Gurkenscheiben und Limette servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Für Babys die Chili erst nach dem Entnehmen zugeben.',
      steps: [
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zu Paste zerkleinern.', '10 Sek.', '', 'Stufe 8', ''],
        ['Öl und Currypulver zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Fleisch zugeben und anbraten, ohne Messbecher.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Kokosmilch, 200 g Wasser und Limettenschale zugeben, Garkörbchen statt Messbecher aufsetzen und schmoren.', '100 Min.', '98°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Ohne Garkörbchen einkochen lassen.', '20 Min.', 'Varoma', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen, dann gehackte Chili, geröstete Kokosraspeln und Salz unterrühren. Reis separat garen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): sehr zartes, ungeschärftes Fleisch zerzupfen und mit Reis und Sauce pürieren. Kleinkind (1–3 J.): ohne Chili, Fleisch in Fasern zupfen, Gurkensticks dazu.',
    baby: 1,
  },
  {
    id: 'hambagu-japanisches-hacksteak',
    n: 'Hambagu (japanisches Hacksteak) mit Pilzsauce & Reis',
    img: { wiki: 'Hamburg steak', q: 'hambagu japanese hamburg steak mushroom sauce rice' },
    ck: 'Hacksteak',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    st: ['kinderliebling'],
    i: [['rinderhack', 150], ['zwiebel', 40], ['ei', 15], ['paniermehl', 10], ['milch', 15], ['champignons', 80], ['ketchup', 10], ['sojasauce', 8], ['gemuesebruehe', 60], ['reis', 55], ['brokkoli', 100], ['rapsoel', 6], ['gewuerze', 1]],
    s: [
      'Zwiebel fein würfeln, die Hälfte in 2 g Öl 3 Min. glasig dünsten und abkühlen lassen. Paniermehl in Milch einweichen.',
      'Hack mit gedünsteter Zwiebel, Ei, eingeweichtem Paniermehl und Muskat verkneten, zu 2 ovalen, 2 cm dicken Laibchen formen, mittig leicht eindrücken.',
      'Reis garen, Brokkoli 6 Min. dämpfen.',
      'Restliches Öl erhitzen, Hacksteaks pro Seite 3 Min. braun braten, 2 EL Wasser zugeben und zugedeckt 6 Min. durchgaren. Baby-Portion entnehmen.',
      'Restliche Zwiebel und Champignons im Bratfett 3 Min. braten, Ketchup, Sojasauce und Brühe zugeben, 2 Min. einkochen und über die Hacksteaks geben. Mit Reis und Brokkoli servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Hacksteaks werden in der Pfanne gebraten.',
      steps: [
        ['Zwiebel in den Mixtopf geben und zerkleinern, Hälfte mit 2 g Öl andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hack, Ei, eingeweichtes Paniermehl und Muskat zugeben und vermengen, Laibchen formen.', '30 Sek.', '', 'Teigknetstufe', 'Teigkneten'],
        ['Mixtopf spülen, 1000 g Wasser einfüllen, Reis im Garkörbchen einhängen, Brokkoli in den Varoma legen, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Hacksteaks in der Pfanne pro Seite 3 Min. braten, mit 2 EL Wasser zugedeckt 6 Min. garen.', '', '', '', ''],
        ['Pilze im Bratfett braten, Ketchup, Sojasauce und Brühe zugeben und einkochen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hacksteak ohne Sauce ist weich und durchgegart ideales BLW-Fingerfood in Streifen, Brokkoliröschen dazu. Kleinkind (1–3 J.): Hacksteak in Würfeln mit wenig Sauce und Reis.',
    baby: 2,
  },
]);
