// Frühstück & Snacks
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  {
    id: 'protein-porridge-beeren',
    n: 'Protein-Porridge mit Beeren',
    img: { wiki: 'Porridge', q: 'protein porridge oatmeal berries' },
    cu: 'international',
    m: ['fruehstueck'],
    t: 10, d: 1,
    st: ['comfort', 'kinderliebling'],
    i: [['haferflocken', 50], ['milch', 220], ['whey', 25], ['beeren_tk', 100], ['chiasamen', 10], ['vanille', 1]],
    s: [
      'Haferflocken mit Milch und Chiasamen in einem kleinen Topf aufkochen.',
      'Bei schwacher Hitze unter Rühren 4–5 Min. quellen lassen, bis der Brei cremig ist.',
      'Für Baby/Kleinkind eine Portion ohne Proteinpulver abnehmen und etwas abkühlen lassen.',
      'Topf vom Herd nehmen, Whey mit 2–3 EL kaltem Wasser glatt rühren und unter den restlichen Porridge ziehen (nicht mehr kochen, sonst flockt es).',
      'Beeren in der Mikrowelle oder im Topf 2 Min. antauen und mit Zimt/Vanille über den Porridge geben.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Haferflocken, Chiasamen und Milch in den Mixtopf geben und aufkochen.', '8 Min.', '90°C', 'Stufe 2', 'Linkslauf'],
        ['Weitergaren, bis der Brei cremig ist.', '4 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Für Baby/Kleinkind eine Portion ohne Proteinpulver entnehmen und etwas abkühlen lassen.', '', '', '', ''],
        ['Whey mit 2–3 EL kaltem Wasser glatt rühren, zugeben und ohne Hitze unterrühren (nicht mehr kochen, sonst flockt es).', '20 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Porridge umfüllen. TK-Beeren in den Mixtopf geben und antauen.', '3 Min.', '60°C', 'Stufe 1', 'Linkslauf'],
        ['Beeren mit Zimt/Vanille über den Porridge geben.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Porridge ohne Whey etwas dünner kochen, Beeren zerdrücken und unterrühren – als Brei vom Löffel oder dick gekocht als Porridge-Finger. Kleinkind (1–3 J.): normale Konsistenz ohne Proteinpulver, Beeren halbiert obendrauf.',
    baby: 2,
  },
  {
    id: 'overnight-oats-skyr',
    n: 'Overnight Oats mit Skyr',
    img: { file: 'Muesli with Berries.jpg', wiki: 'Overnight oats', q: 'overnight oats skyr blueberries jar' },
    cu: 'international',
    m: ['fruehstueck'],
    t: 5, d: 1,
    st: ['mealprep'],
    i: [['haferflocken', 50], ['skyr', 150], ['milch', 100], ['chiasamen', 10], ['heidelbeeren', 80], ['ahornsirup', 8], ['vanille', 1]],
    s: [
      'Haferflocken, Chiasamen, Milch und Skyr in einem Schraubglas gründlich verrühren.',
      'Mit Vanille/Zimt abschmecken, Glas verschließen und mindestens 6 Std. oder über Nacht im Kühlschrank quellen lassen.',
      'Am Morgen kräftig umrühren, bei Bedarf 1–2 EL Milch zugeben.',
      'Mit Heidelbeeren toppen und mit Ahornsirup beträufeln. Hält sich 2 Tage im Kühlschrank.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Gequollen wird im Kühlschrank.',
      steps: [
        ['Für Baby/Kleinkind 2 EL Haferflocken im trockenen Mixtopf fein mahlen und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Haferflocken, Chiasamen, Milch, Skyr und Vanille in den Mixtopf geben und verrühren.', '20 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['In Schraubgläser füllen, verschließen und mindestens 6 Std. oder über Nacht im Kühlschrank quellen lassen.', '', '', '', ''],
        ['Morgens kräftig umrühren, bei Bedarf 1–2 EL Milch zugeben, mit Heidelbeeren toppen und mit Ahornsirup beträufeln.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Haferflocken vorher fein mahlen, ohne Ahornsirup ansetzen, Heidelbeeren zerdrücken (ganze Beeren nur gequetscht). Kleinkind (1–3 J.): Heidelbeeren halbieren, mit Banane statt Sirup süßen.',
    baby: 2,
  },
  {
    id: 'shakshuka',
    n: 'Shakshuka',
    img: { wiki: 'Shakshouka', q: 'shakshuka eggs tomato pan' },
    cu: 'orientalisch',
    m: ['fruehstueck', 'mittag'],
    t: 25, d: 1,
    st: ['comfort'],
    i: [['ei', 120], ['tomaten_dose', 250], ['paprika', 100], ['zwiebel', 40], ['knoblauch', 4], ['olivenoel', 8], ['gewuerze', 3], ['salz', 0.8], ['feta', 25], ['kraeuter', 3], ['sauerteigbrot', 40]],
    s: [
      'Zwiebel und Paprika fein würfeln und im Olivenöl bei mittlerer Hitze 5 Min. weich dünsten, Knoblauch 1 Min. mitbraten.',
      'Kreuzkümmel und Paprikapulver kurz anrösten, Tomaten zugeben und 8–10 Min. einköcheln lassen.',
      'Für Baby/Kleinkind 2–3 EL Sauce ungesalzen entnehmen, dann den Rest salzen.',
      'Mit einem Löffel Mulden formen, Eier hineinschlagen und zugedeckt bei schwacher Hitze 6–8 Min. stocken lassen.',
      'Mit zerbröseltem Feta und Kräutern bestreuen und mit geröstetem Brot servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Sauce entsteht im Thermomix, die Eier stocken in der Pfanne.',
      steps: [
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Paprika in Stücken zugeben und zerkleinern.', '4 Sek.', '', 'Stufe 4', ''],
        ['Olivenöl zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Kreuzkümmel und Paprikapulver zugeben und mitdünsten.', '1 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten zugeben und einköcheln, statt Messbecher das Garkörbchen als Spritzschutz aufsetzen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Für Baby/Kleinkind 2–3 EL Sauce ungesalzen entnehmen, Rest salzen.', '', '', '', ''],
        ['Sauce in eine Pfanne geben, Mulden formen, Eier hineinschlagen und zugedeckt bei schwacher Hitze 6–8 Min. stocken lassen.', '', '', '', ''],
        ['Mit Feta und Kräutern bestreuen und mit geröstetem Brot servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Ei in der ungesalzenen Sauce komplett durchgaren (kein flüssiges Eigelb), zerdrücken oder in Streifen geben, Brot als Fingerfood zum Dippen; Feta weglassen. Kleinkind (1–3 J.): Ei durchgegart, nur wenig Feta, Brot in Streifen.',
    baby: 2,
  },
  {
    id: 'ruehrei-spinat-toast',
    n: 'Rührei mit Spinat auf Vollkorntoast',
    img: { file: "Scrambled eggs on toast - Joe's Cafe 2024-04-14.jpg", wiki: 'Scrambled eggs', q: 'scrambled eggs spinach toast' },
    cu: 'international',
    m: ['fruehstueck'],
    t: 10, d: 1,
    st: ['kinderliebling'],
    i: [['ei', 150], ['milch', 20], ['spinat', 60], ['toast_vollkorn', 56], ['butter', 5], ['salz', 0.5], ['gewuerze', 1]],
    s: [
      'Eier mit Milch verquirlen.',
      'Butter in einer beschichteten Pfanne bei mittlerer Hitze schmelzen, Spinat darin 1 Min. zusammenfallen lassen.',
      'Eimasse zugeben und mit einem Pfannenwender langsam vom Rand zur Mitte schieben, 2–3 Min. cremig stocken lassen.',
      'Portion für Baby/Kleinkind ungesalzen entnehmen, den Rest mit Salz und Pfeffer würzen.',
      'Toast rösten und das Rührei darauf anrichten.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Nur der Toast kommt in den Toaster.',
      steps: [
        ['Spinat und Butter in den Mixtopf geben und zusammenfallen lassen.', '3 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Eier und Milch zugeben und verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
        ['Eimasse cremig stocken lassen, nach 5 Min. den Garzustand prüfen.', '6 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Portion für Baby/Kleinkind ungesalzen entnehmen.', '', '', '', ''],
        ['Rest mit Salz und Pfeffer würzen und kurz unterrühren.', '5 Sek.', '', 'Stufe 1', 'Linkslauf'],
        ['Toast rösten und das Rührei darauf anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Rührei vollständig durchgaren, ungesalzen, Spinat fein hacken; Toast in fingerdicke Streifen schneiden und dünn mit Rührei belegen. Kleinkind (1–3 J.): Toast in Dreiecke, Rührei mit wenig Salz.',
    baby: 2,
  },
  {
    id: 'skyr-beeren-bowl-granola',
    n: 'Skyr-Beeren-Bowl mit Granola',
    img: { wiki: 'Skyr', q: 'skyr bowl berries granola' },
    cu: 'international',
    m: ['fruehstueck', 'snack'],
    t: 5, d: 1,
    i: [['skyr', 250], ['beeren_tk', 100], ['granola', 40], ['ahornsirup', 8], ['vanille', 0.5]],
    s: [
      'Beeren am Vorabend im Kühlschrank auftauen lassen (oder 2 Min. in der Mikrowelle antauen).',
      'Skyr mit Vanille cremig rühren und in eine Schale geben.',
      'Beeren mitsamt Saft darauf verteilen.',
      'Kurz vor dem Essen mit Granola bestreuen, damit es knusprig bleibt, und mit Ahornsirup beträufeln.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix taut die Beeren an und rührt den Skyr cremig, der Rest ist Anrichten.',
      steps: [
        ['TK-Beeren in den Mixtopf geben und antauen.', '4 Min.', '50°C', 'Stufe 1', 'Linkslauf'],
        ['Beeren mitsamt Saft umfüllen. Skyr und Vanille in den Mixtopf geben und cremig rühren.', '20 Sek.', '', 'Stufe 3', ''],
        ['Skyr in Schalen geben und die Beeren darauf verteilen.', '', '', '', ''],
        ['Kurz vor dem Essen mit Granola bestreuen und mit Ahornsirup beträufeln.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Skyr mit zerdrückten Beeren verrühren, ohne Granola und Sirup, als Brei füttern. Kleinkind (1–3 J.): Granola grob zerbröseln (keine ganzen Nüsse), Beeren halbiert.',
    baby: 2,
  },
  {
    id: 'protein-pancakes',
    n: 'Protein-Pancakes',
    img: { wiki: 'Pancake', q: 'protein pancakes stack berries' },
    cu: 'amerikanisch',
    m: ['fruehstueck'],
    t: 20, d: 1,
    st: ['kinderliebling'],
    i: [['haferflocken', 50], ['ei', 60], ['magerquark', 100], ['whey', 15], ['milch', 50], ['backpulver', 3], ['rapsoel', 4], ['beeren_tk', 80], ['ahornsirup', 8]],
    s: [
      'Haferflocken im Mixer fein mahlen.',
      'Ei, Quark, Milch, Whey und Backpulver zugeben und zu einem dickflüssigen Teig mixen, 5 Min. quellen lassen.',
      'Eine beschichtete Pfanne mit wenig Öl auf mittlere Hitze bringen und je 2 EL Teig als kleine Pancakes hineingeben.',
      'Pro Seite 1,5–2 Min. backen, bis sich Bläschen bilden, dann wenden.',
      'Beeren erwärmen und mit Ahornsirup über die Pancakes geben.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Ausgebacken wird in der Pfanne.',
      steps: [
        ['Haferflocken in den Mixtopf geben und fein mahlen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Ei, Quark, Milch und Backpulver zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
        ['Für Baby/Kleinkind 2–3 EL Teig ohne Whey abnehmen.', '', '', '', ''],
        ['Whey zugeben, zu einem dickflüssigen Teig verrühren und 5 Min. quellen lassen.', '10 Sek.', '', 'Stufe 4', ''],
        ['In einer beschichteten Pfanne mit wenig Öl je 2 EL Teig pro Seite 1,5–2 Min. ausbacken.', '', '', '', ''],
        ['Mixtopf ausspülen, TK-Beeren darin erwärmen.', '4 Min.', '70°C', 'Stufe 1', 'Linkslauf'],
        ['Beeren mit Ahornsirup über die Pancakes geben.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): kleine, dünne Pancakes ohne Sirup in Streifen als Fingerfood, Beeren zerdrückt als Dip; für das Baby gern einen Teil ohne Whey backen. Kleinkind (1–3 J.): Mini-Pancakes mit halbierten Beeren, Sirup nur ein Tropfen.',
    baby: 2,
  },
  {
    id: 'bananen-hafer-pancakes',
    n: 'Bananen-Hafer-Pancakes (3 Zutaten)',
    img: { wiki: 'Pancake', q: 'banana oat pancakes baby' },
    cu: 'international',
    m: ['fruehstueck', 'snack'],
    t: 15, d: 1,
    st: ['kinderliebling'],
    i: [['banane', 100], ['ei', 120], ['haferflocken', 40], ['rapsoel', 3]],
    s: [
      'Banane mit einer Gabel sehr fein zerdrücken.',
      'Eier und Haferflocken unterrühren und den Teig 5 Min. quellen lassen.',
      'Pfanne mit wenig Öl auf mittlere Hitze bringen, je 1 EL Teig als kleine Taler hineingeben.',
      'Pro Seite ca. 2 Min. goldbraun backen, vorsichtig wenden, da der Teig weich ist.',
      'Warm servieren – ganz ohne Zucker und Salz, ideal für die ganze Familie.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix macht den Teig, ausgebacken wird in der Pfanne.',
      steps: [
        ['Haferflocken in den Mixtopf geben und fein mahlen (ideal fürs Baby).', '10 Sek.', '', 'Stufe 10', ''],
        ['Banane in Stücken und Eier zugeben und zu einem glatten Teig mixen.', '15 Sek.', '', 'Stufe 5', ''],
        ['Teig 5 Min. quellen lassen.', '', '', '', ''],
        ['In einer Pfanne mit wenig Öl je 1 EL Teig als Taler pro Seite ca. 2 Min. goldbraun backen und warm servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): perfektes BLW-Fingerfood – Taler gut durchbacken, in Streifen schneiden, Haferflocken vorher fein mahlen. Kleinkind (1–3 J.): ganze Mini-Pancakes, dazu Joghurt zum Dippen.',
    baby: 2,
  },
  {
    id: 'avocado-toast-pochiertes-ei',
    n: 'Avocado-Toast mit pochiertem Ei',
    img: { wiki: 'Avocado toast', q: 'avocado toast poached egg' },
    cu: 'international',
    m: ['fruehstueck'],
    t: 15, d: 2,
    i: [['sauerteigbrot', 60], ['avocado', 30], ['huettenkaese', 80], ['ei', 120], ['zitrone', 5], ['salz', 0.5], ['gewuerze', 1], ['kraeuter', 3], ['essig', 5]],
    s: [
      'Wasser in einem Topf aufkochen, Essig zugeben und die Hitze reduzieren, sodass es nur noch siedet.',
      'Eier einzeln in eine Tasse schlagen, einen Strudel rühren und die Eier hineingleiten lassen; 3–4 Min. pochieren, mit der Schaumkelle herausheben.',
      'Brot rösten. Avocado mit Zitronensaft zerdrücken und mit dem Hüttenkäse verrühren.',
      'Für Baby/Kleinkind einen Teil der Creme ungesalzen abnehmen, Rest mit Salz und Chiliflocken würzen.',
      'Brot mit der Creme bestreichen, Ei darauflegen und mit Kräutern bestreuen.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix macht nur die Avocado-Creme, die Eier werden im Topf pochiert.',
      steps: [
        ['Kräuter in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Avocado-Fruchtfleisch, Zitronensaft und Hüttenkäse in den Mixtopf geben und verrühren.', '10 Sek.', '', 'Stufe 4', ''],
        ['Für Baby/Kleinkind einen Teil der Creme ungesalzen abnehmen.', '', '', '', ''],
        ['Restliche Creme mit Salz und Chiliflocken würzen und kurz verrühren.', '5 Sek.', '', 'Stufe 3', ''],
        ['Eier in siedendem Essigwasser im Topf 3–4 Min. pochieren (fürs Baby 10 Min. hart kochen).', '', '', '', ''],
        ['Brot rösten, mit der Creme bestreichen, Ei darauflegen und mit Kräutern bestreuen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Ei 10 Min. hart kochen statt pochieren, zerdrücken und mit ungesalzener Avocado-Creme auf Toaststreifen streichen. Kleinkind (1–3 J.): Ei durchgegart, Brot in Streifen, ohne Chili.',
    baby: 2,
  },
  {
    id: 'gemuese-frittata',
    n: 'Gemüse-Frittata',
    img: { wiki: 'Frittata', q: 'vegetable frittata pan' },
    cu: 'italienisch',
    m: ['fruehstueck', 'mittag'],
    t: 30, d: 1,
    st: ['mealprep', 'kinderliebling'],
    i: [['ei', 180], ['kartoffel', 100], ['paprika', 80], ['zucchini', 60], ['spinat', 30], ['fruehlingszwiebel', 15], ['feta', 20], ['olivenoel', 6], ['salz', 0.5], ['gewuerze', 2], ['kraeuter', 3]],
    s: [
      'Ofen auf 180 °C Ober-/Unterhitze vorheizen. Kartoffeln in dünne Scheiben, Paprika und Zucchini in Würfel schneiden.',
      'Kartoffeln in einer ofenfesten Pfanne im Öl 8 Min. braten, Paprika, Zucchini und Frühlingszwiebel 3 Min. mitbraten, Spinat zufallen lassen.',
      'Eier mit Kräutern und Gewürzen verquirlen; für Baby/Kleinkind erst danach salzen bzw. die Kinder-Ecke ohne Feta lassen.',
      'Eimasse über das Gemüse gießen, Feta darüberbröseln und 2 Min. auf dem Herd anstocken lassen.',
      'Im Ofen 12–15 Min. backen, bis die Mitte fest ist. Kurz ruhen lassen und in Stücke schneiden.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Kartoffeln und Gemüse werden im Varoma vorgegart statt angebraten, gebacken wird im Ofen.',
      steps: [
        ['Ofen auf 180 °C Ober-/Unterhitze vorheizen. Kartoffeln in dünne Scheiben, Paprika und Zucchini in Würfel schneiden.', '', '', '', ''],
        ['500 g Wasser in den Mixtopf geben. Kartoffeln in den Varoma-Behälter, Paprika und Zucchini auf den Einlegeboden legen, aufsetzen und dampfgaren.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren. Eier, Kräuter und Gewürze hineingeben und verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
        ['Für Baby/Kleinkind etwas Eimasse ungesalzen abnehmen und später in eine Ecke der Form ohne Feta gießen.', '', '', '', ''],
        ['Restliche Eimasse salzen und kurz verrühren.', '5 Sek.', '', 'Stufe 3', ''],
        ['Gemüse, Frühlingszwiebel und Spinat in einer geölten ofenfesten Pfanne verteilen, Eimasse darübergießen und Feta darüberbröseln.', '', '', '', ''],
        ['Im Ofen 15–20 Min. backen, bis die Mitte fest ist. Kurz ruhen lassen und in Stücke schneiden.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Ecke ohne Feta in fingerlange Streifen schneiden – ideales BLW-Fingerfood, vollständig durchgegart. Kleinkind (1–3 J.): kleine Würfel, wenig Feta; kalt auch super für die Brotdose.',
    baby: 2,
  },
  {
    id: 'chia-pudding-mango',
    n: 'Chia-Pudding mit Mango',
    img: { file: 'Chia Seed Pudding in a cup.jpg', q: 'chia pudding mango layered glass' },
    cu: 'international',
    m: ['fruehstueck', 'snack'],
    t: 10, d: 1,
    st: ['mealprep'],
    i: [['chiasamen', 24], ['milch', 200], ['skyr', 150], ['mango', 40], ['ahornsirup', 6], ['vanille', 1], ['kokosraspeln', 5]],
    s: [
      'Chiasamen mit Milch, Vanille und Ahornsirup verrühren, nach 10 Min. nochmals umrühren, damit nichts klumpt.',
      'Abgedeckt mindestens 4 Std. oder über Nacht im Kühlschrank quellen lassen.',
      'Mango schälen und die Hälfte fein pürieren, den Rest würfeln.',
      'Im Glas schichten: Chia-Pudding, Skyr, Mangopüree; mit Mangowürfeln und Kokosraspeln toppen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Gequollen wird im Kühlschrank.',
      steps: [
        ['Für Baby/Kleinkind einen Teil der Chiasamen im trockenen Mixtopf fein mahlen und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Die Hälfte der Mango in Stücken in den Mixtopf geben, fein pürieren und umfüllen. Restliche Mango würfeln.', '20 Sek.', '', 'Stufe 8', ''],
        ['Chiasamen, Milch und Vanille in den Mixtopf geben und verrühren.', '15 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Für Baby/Kleinkind eine Portion ungesüßt abnehmen, Rest mit Ahornsirup süßen.', '', '', '', ''],
        ['In Gläser füllen, nach 10 Min. umrühren und mindestens 4 Std. oder über Nacht kühlen.', '', '', '', ''],
        ['Mit Skyr und Mangopüree schichten, mit Mangowürfeln und Kokosraspeln toppen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Chiasamen vorher mahlen oder sehr gut quellen lassen, ohne Sirup, mit viel Mangopüree als Brei. Kleinkind (1–3 J.): Pudding mit Mangowürfeln (klein, weich), Sirup weglassen.',
    baby: 1,
  },
  {
    id: 'huettenkaese-bowl-obst-nuesse',
    n: 'Hüttenkäse-Bowl mit Obst & Nüssen',
    img: { wiki: 'Cottage cheese', q: 'cottage cheese bowl fruit nuts' },
    cu: 'international',
    m: ['fruehstueck', 'snack'],
    t: 5, d: 1,
    i: [['huettenkaese', 250], ['erdbeeren', 100], ['heidelbeeren', 40], ['walnuesse', 15], ['ahornsirup', 5], ['vanille', 0.5]],
    s: [
      'Hüttenkäse in eine Schale geben und mit Zimt verrühren.',
      'Erdbeeren waschen, putzen und vierteln.',
      'Walnüsse grob hacken und in einer trockenen Pfanne 2–3 Min. rösten, bis sie duften.',
      'Beeren auf dem Hüttenkäse verteilen, mit Nüssen bestreuen und mit Ahornsirup beträufeln.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix röstet und hackt nur die Nüsse.',
      steps: [
        ['Walnüsse in den Mixtopf geben und ohne Fett rösten, bis sie duften.', '4 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Grob hacken und umfüllen (für Baby/Kleinkind einen Teil anschließend 10 Sek./Stufe 10 fein mahlen).', '3 Sek.', '', 'Stufe 5', ''],
        ['Hüttenkäse mit Zimt in Schalen verrühren, Erdbeeren putzen und vierteln.', '', '', '', ''],
        ['Beeren auf dem Hüttenkäse verteilen, mit Nüssen bestreuen und mit Ahornsirup beträufeln.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hüttenkäse ist salzig – nur 1–2 EL mit zerdrückten Beeren und fein gemahlenen Walnüssen mischen, ohne Sirup. Kleinkind (1–3 J.): Beeren klein schneiden, Nüsse nur gemahlen (Verschluckungsgefahr).',
    baby: 1,
  },
  {
    id: 'ei-muffins-gemuese',
    n: 'Ei-Muffins mit Gemüse',
    img: { file: 'Frittata 03.jpg', q: 'egg muffins vegetables muffin tin' },
    cu: 'amerikanisch',
    m: ['fruehstueck', 'snack'],
    t: 30, d: 1,
    st: ['mealprep', 'kinderliebling'],
    i: [['ei', 180], ['paprika', 60], ['spinat', 30], ['fruehlingszwiebel', 10], ['gouda_light', 20], ['kraeuter', 3], ['salz', 0.5], ['gewuerze', 2], ['rapsoel', 2], ['vollkornbrot', 50]],
    s: [
      'Ofen auf 180 °C Umluft vorheizen, 6 Mulden eines Muffinblechs dünn einölen.',
      'Paprika fein würfeln, Spinat hacken, Frühlingszwiebel in Ringe schneiden und auf die Mulden verteilen.',
      'Eier mit Kräutern und Gewürzen verquirlen; Kinder-Mulden zuerst füllen, dann den Rest der Eimasse salzen.',
      'Eimasse in die Mulden gießen und mit Käse bestreuen.',
      '18–20 Min. backen, bis die Muffins aufgegangen und fest sind. Mit Vollkornbrot servieren; halten 3 Tage im Kühlschrank.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen (12 Muffins) ausgelegt. Gebacken wird im Ofen.',
      steps: [
        ['Ofen auf 180 °C Umluft vorheizen, 12 Mulden eines Muffinblechs dünn einölen.', '', '', '', ''],
        ['Paprika in Stücken, Frühlingszwiebel und Spinat in den Mixtopf geben, zerkleinern und auf die Mulden verteilen.', '4 Sek.', '', 'Stufe 4', ''],
        ['Eier, Kräuter und Gewürze in den Mixtopf geben und verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
        ['Kinder-Mulden zuerst mit ungesalzener Eimasse füllen.', '', '', '', ''],
        ['Restliche Eimasse salzen und kurz verrühren.', '5 Sek.', '', 'Stufe 3', ''],
        ['Eimasse in die übrigen Mulden gießen, alle mit Käse bestreuen und 18–20 Min. backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Muffins halbieren oder in Streifen schneiden – weich und gut greifbar für BLW. Kleinkind (1–3 J.): ganze Mini-Muffins, auch kalt als Snack für unterwegs.',
    baby: 2,
  },
  {
    id: 'protein-smoothie-bowl',
    n: 'Protein-Smoothie-Bowl',
    img: { file: 'Chocolate Green Smoothie Bowl.jpg', q: 'smoothie bowl berries banana toppings' },
    cu: 'international',
    m: ['fruehstueck'],
    t: 10, d: 1,
    i: [['banane', 100], ['beeren_tk', 100], ['skyr', 150], ['whey', 20], ['milch', 80], ['granola', 25], ['chiasamen', 5], ['kiwi', 40]],
    s: [
      'Banane in Scheiben schneiden und am besten über Nacht einfrieren.',
      'Gefrorene Banane, TK-Beeren, Skyr, Whey und Milch im Mixer 1 Min. zu einer dicken, cremigen Masse mixen; nur bei Bedarf schluckweise mehr Milch zugeben.',
      'In eine Schale streichen.',
      'Mit Kiwischeiben, Granola und Chiasamen toppen und sofort essen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Banane am Vortag in Scheiben einfrieren.',
      steps: [
        ['Für Baby/Kleinkind zuerst etwas nicht gefrorene Banane mit Skyr ohne Whey pürieren und umfüllen.', '20 Sek.', '', 'Stufe 8', ''],
        ['Gefrorene Banane, TK-Beeren, Skyr, Whey und Milch in den Mixtopf geben und zu einer dicken, cremigen Masse mixen, zwischendurch mit dem Spatel nach unten schieben.', '1 Min.', '', 'Stufe 10', ''],
        ['Nur bei Bedarf schluckweise Milch zugeben und nochmals mixen.', '20 Sek.', '', 'Stufe 8', ''],
        ['In Schalen streichen, mit Kiwi, Granola und Chiasamen toppen und sofort essen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Smoothie-Masse ohne Whey aus nicht gefrorenem Obst mixen und als Brei vom Löffel geben, ohne Granola. Kleinkind (1–3 J.): ohne Whey, Toppings klein geschnitten, Granola zerbröselt.',
    baby: 1,
  },
  {
    id: 'breakfast-burrito',
    n: 'Breakfast Burrito',
    img: { wiki: 'Breakfast burrito', q: 'breakfast burrito eggs cheese' },
    cu: 'mexikanisch',
    m: ['fruehstueck', 'mittag'],
    t: 15, d: 1,
    st: ['comfort'],
    i: [['tortilla', 60], ['ei', 120], ['paprika', 50], ['cheddar', 15], ['avocado', 30], ['salsa', 30], ['rapsoel', 4], ['salz', 0.5], ['gewuerze', 1], ['kraeuter', 3]],
    s: [
      'Paprika fein würfeln und im Öl 3 Min. anbraten.',
      'Eier verquirlen, zur Paprika geben und 2–3 Min. zu Rührei stocken lassen; Kinder-Portion entnehmen, Rest mit Salz und Kreuzkümmel würzen.',
      'Tortilla in einer trockenen Pfanne 30 Sek. pro Seite erwärmen.',
      'Rührei, Käse, Avocadoscheiben, Salsa und Koriander mittig auf die Tortilla geben.',
      'Seiten einschlagen, fest aufrollen und in der Pfanne mit der Naht nach unten 1 Min. anrösten. Halbieren und servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Tortillas werden in der Pfanne erwärmt und angeröstet.',
      steps: [
        ['Paprika in Stücken in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 4', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Verquirlte Eier zugeben und zu Rührei stocken lassen.', '6 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Portion für Baby/Kleinkind ungesalzen entnehmen.', '', '', '', ''],
        ['Rest mit Salz und Kreuzkümmel würzen und kurz unterrühren.', '5 Sek.', '', 'Stufe 1', 'Linkslauf'],
        ['Tortillas in einer trockenen Pfanne 30 Sek. pro Seite erwärmen.', '', '', '', ''],
        ['Mit Rührei, Käse, Avocado, Salsa und Koriander füllen, aufrollen und mit der Naht nach unten 1 Min. in der Pfanne anrösten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes Rührei und Avocado-Streifen pur als Fingerfood, Tortilla in Streifen dazu, ohne Salsa und Käse. Kleinkind (1–3 J.): kleine Burrito-Rolle ohne Salsa, in Scheiben geschnitten.',
    baby: 2,
  },
  {
    id: 'protein-french-toast',
    n: 'Protein-French-Toast',
    img: { wiki: 'French toast', q: 'french toast berries' },
    cu: 'amerikanisch',
    m: ['fruehstueck'],
    t: 15, d: 1,
    st: ['comfort', 'kinderliebling'],
    i: [['toast_vollkorn', 84], ['ei', 60], ['eiklar', 60], ['milch', 50], ['whey', 10], ['vanille', 1], ['butter', 5], ['beeren_tk', 80], ['skyr', 50]],
    s: [
      'Ei, Eiklar, Milch, Whey und Zimt in einer flachen Schale glatt verquirlen.',
      'Toastscheiben von beiden Seiten je 20 Sek. einweichen lassen.',
      'Butter in einer Pfanne bei mittlerer Hitze schmelzen und den Toast pro Seite 2–3 Min. goldbraun braten.',
      'Beeren kurz erwärmen.',
      'French Toast mit einem Klecks Skyr und den Beeren servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Gebraten wird in der Pfanne.',
      steps: [
        ['Ei, Eiklar, Milch und Zimt in den Mixtopf geben und verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
        ['Für Baby/Kleinkind etwas Eimasse ohne Whey abnehmen.', '', '', '', ''],
        ['Whey zugeben, glatt verrühren und in eine flache Schale umfüllen.', '10 Sek.', '', 'Stufe 4', ''],
        ['Toast beidseitig je 20 Sek. einweichen und in der Pfanne mit Butter pro Seite 2–3 Min. goldbraun braten.', '', '', '', ''],
        ['TK-Beeren im Mixtopf erwärmen.', '4 Min.', '70°C', 'Stufe 1', 'Linkslauf'],
        ['French Toast mit Skyr und Beeren servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Toast nur in Ei und Milch (ohne Whey) tränken, vollständig durchbraten und in Streifen schneiden; Beeren zerdrückt als Dip. Kleinkind (1–3 J.): in kleine Quadrate schneiden, Skyr zum Dippen.',
    baby: 2,
  },
  {
    id: 'bircher-muesli',
    n: 'Bircher Müsli',
    img: { wiki: 'Muesli', q: 'bircher muesli apple' },
    cu: 'deutsch',
    m: ['fruehstueck'],
    t: 10, d: 1,
    st: ['mealprep'],
    i: [['haferflocken', 50], ['milch', 100], ['skyr', 100], ['apfel', 80], ['zitrone', 5], ['mandeln', 10], ['ahornsirup', 5], ['vanille', 0.5]],
    s: [
      'Haferflocken mit Milch verrühren und abgedeckt über Nacht (mind. 2 Std.) im Kühlschrank quellen lassen.',
      'Morgens den Apfel mit Schale grob raspeln und sofort mit Zitronensaft mischen.',
      'Apfel und Skyr unter die Flocken rühren, mit Zimt und Ahornsirup abschmecken.',
      'Mandeln grob hacken und darüberstreuen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Mandeln in den Mixtopf geben, grob hacken und umfüllen (für Baby/Kleinkind einen Teil fein mahlen).', '3 Sek.', '', 'Stufe 6', ''],
        ['Haferflocken und Milch in den Mixtopf geben, verrühren, umfüllen und abgedeckt über Nacht (mind. 2 Std.) kühlen.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Morgens Apfel in Stücken mit Zitronensaft in den Mixtopf geben und raspeln.', '4 Sek.', '', 'Stufe 5', ''],
        ['Eingeweichte Flocken, Skyr, Zimt und Ahornsirup zugeben und verrühren.', '15 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Mit den Mandeln bestreut servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Flocken vorher fein mahlen, Apfel sehr fein reiben, ohne Sirup; Mandeln nur als feines Mehl. Kleinkind (1–3 J.): normale Konsistenz, Mandeln gemahlen statt gehackt.',
    baby: 2,
  },
  {
    id: 'omelett-tomate-feta',
    n: 'Omelett mit Tomate & Feta',
    img: { wiki: 'Omelette', q: 'omelette tomato feta' },
    cu: 'mediterran',
    m: ['fruehstueck', 'mittag'],
    t: 10, d: 1,
    i: [['ei', 180], ['tomate', 100], ['feta', 30], ['kraeuter', 3], ['olivenoel', 5], ['gewuerze', 1], ['sauerteigbrot', 40]],
    s: [
      'Tomate entkernen und würfeln, Feta zerbröseln.',
      'Eier mit Oregano und Pfeffer verquirlen (Feta bringt genug Salz mit).',
      'Öl in einer beschichteten Pfanne bei mittlerer Hitze erhitzen, Eimasse hineingießen und 2 Min. stocken lassen.',
      'Tomaten und Feta auf eine Hälfte geben, Omelett zuklappen und weitere 1–2 Min. garen.',
      'Mit Kräutern bestreuen und mit geröstetem Brot servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix übernimmt nur die Vorbereitung, das Omelett gelingt in der Pfanne.',
      steps: [
        ['Kräuter in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Entkernte Tomaten in Stücken in den Mixtopf geben, grob zerkleinern und umfüllen.', '2 Sek.', '', 'Stufe 4', ''],
        ['Eier, Oregano und Pfeffer in den Mixtopf geben und verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
        ['Für Baby/Kleinkind vorab ein kleines Omelett ohne Feta komplett durchbraten.', '', '', '', ''],
        ['Eimasse portionsweise in einer beschichteten Pfanne mit Öl 2 Min. stocken lassen, Tomaten und Feta auf eine Hälfte geben, zuklappen und 1–2 Min. garen.', '', '', '', ''],
        ['Mit Kräutern bestreuen und mit geröstetem Brot servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Kinder-Omelett vorab ohne Feta komplett durchbraten, mit weichen Tomatenwürfeln in Streifen schneiden. Kleinkind (1–3 J.): wenig Feta, in Streifen oder Würfel.',
    baby: 2,
  },
  {
    id: 'hirsebrei-apfel-zimt',
    n: 'Hirsebrei mit Apfel & Zimt',
    img: { file: 'Porridge.jpg', q: 'millet porridge apple cinnamon' },
    cu: 'deutsch',
    m: ['fruehstueck'],
    t: 25, d: 1,
    st: ['comfort', 'kinderliebling'],
    i: [['hirse', 60], ['milch', 250], ['magerquark', 100], ['apfel', 100], ['vanille', 2], ['mandelmus', 10]],
    s: [
      'Hirse in einem Sieb heiß abspülen, damit sie nicht bitter schmeckt.',
      'Mit Milch aufkochen und zugedeckt bei schwacher Hitze 15–20 Min. quellen lassen, gelegentlich umrühren.',
      'Apfel klein würfeln und die letzten 5 Min. mitgaren, Zimt einrühren.',
      'Vom Herd nehmen und den Quark unterrühren.',
      'Mit einem Klecks Mandelmus servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Hirse und 1 l Milch passen gut in den Mixtopf.',
      steps: [
        ['Hirse im Garkörbchen heiß abspülen.', '', '', '', ''],
        ['Apfel in Stücken in den Mixtopf geben, zerkleinern und umfüllen.', '4 Sek.', '', 'Stufe 4', ''],
        ['Hirse und Milch in den Mixtopf geben und garen.', '15 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Apfel und Zimt zugeben und weitergaren.', '5 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Für Baby eine Portion entnehmen, mit etwas Milch verdünnen und fein zerdrücken.', '', '', '', ''],
        ['Quark zugeben und unterrühren.', '20 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Mit einem Klecks Mandelmus servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): klassischer Beikost-Brei – Hirse etwas länger und mit mehr Milch weich kochen, Apfel fein pürieren; Mandelmus nur dünn einrühren. Kleinkind (1–3 J.): wie für Erwachsene, Apfelstücke weich gegart.',
    baby: 2,
  },
  {
    id: 'quinoa-fruehstuecksbowl',
    n: 'Quinoa-Frühstücksbowl',
    img: { file: 'Vegan Quinoa Bowl (44040185371).jpg', wiki: 'Quinoa', q: 'quinoa breakfast bowl berries yogurt' },
    cu: 'international',
    m: ['fruehstueck'],
    t: 20, d: 1,
    st: ['mealprep'],
    i: [['quinoa', 50], ['milch', 150], ['skyr', 150], ['heidelbeeren', 60], ['kuerbiskerne', 10], ['ahornsirup', 5], ['vanille', 1]],
    s: [
      'Quinoa in einem Sieb gründlich heiß abspülen.',
      'Mit Milch und Zimt aufkochen und zugedeckt bei schwacher Hitze 15 Min. garen, bis die Milch aufgesogen ist.',
      'Kurz abkühlen lassen und in eine Schale geben.',
      'Skyr daraufgeben, mit Heidelbeeren und Kürbiskernen toppen und mit Ahornsirup beträufeln.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Für Baby/Kleinkind Kürbiskerne im trockenen Mixtopf fein mahlen und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Quinoa im Garkörbchen gründlich heiß abspülen.', '', '', '', ''],
        ['Quinoa, Milch und Zimt in den Mixtopf geben und garen, bis die Milch aufgesogen ist.', '20 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Kurz abkühlen lassen und in Schalen geben.', '', '', '', ''],
        ['Skyr daraufgeben, mit Heidelbeeren und Kürbiskernen toppen und mit Ahornsirup beträufeln.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Quinoa sehr weich kochen und mit Skyr und zerdrückten Heidelbeeren mischen, ohne Sirup, Kürbiskerne gemahlen. Kleinkind (1–3 J.): Heidelbeeren gequetscht oder halbiert, Kerne gemahlen.',
    baby: 2,
  },
  {
    id: 'raeucherlachs-bagel-frischkaese',
    n: 'Räucherlachs-Bagel mit Frischkäse',
    img: { wiki: 'Lox', q: 'smoked salmon bagel cream cheese' },
    cu: 'amerikanisch',
    m: ['fruehstueck', 'mittag'],
    t: 10, d: 1,
    i: [['bagel', 85], ['frischkaese_light', 30], ['raeucherlachs', 60], ['gurke', 30], ['rote_zwiebel', 10], ['zitrone', 5], ['kraeuter', 2]],
    s: [
      'Bagel aufschneiden und kurz toasten.',
      'Frischkäse mit etwas Zitronensaft und gehacktem Dill verrühren.',
      'Gurke in dünne Scheiben, rote Zwiebel in feine Ringe schneiden.',
      'Beide Bagelhälften mit Frischkäse bestreichen, mit Räucherlachs, Gurke und Zwiebel belegen und mit Pfeffer servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix rührt nur den Dill-Frischkäse.',
      steps: [
        ['Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Frischkäse und Zitronensaft zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Bagels aufschneiden und toasten, Gurke in Scheiben und rote Zwiebel in Ringe schneiden.', '', '', '', ''],
        ['Bagelhälften mit Frischkäse bestreichen, mit Räucherlachs, Gurke und Zwiebel belegen und pfeffern (Baby/Kleinkind: gegarter Lachs oder Ei statt Räucherlachs).', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): kein Räucherlachs (roh/salzig) – stattdessen Bagel-Streifen mit Frischkäse und hart gekochtem Ei oder durchgegartem Lachs, Gurke in Sticks. Kleinkind (1–3 J.): ebenfalls ohne Räucherlachs, mit gegartem Lachs oder Ei, ohne Zwiebel.',
    baby: 1,
  },
  {
    id: 'hummus-gemuesesticks',
    n: 'Hummus mit Gemüsesticks',
    img: { wiki: 'Hummus', q: 'hummus vegetable sticks' },
    cu: 'orientalisch',
    m: ['snack'],
    t: 10, d: 1,
    st: ['mealprep'],
    i: [['kichererbsen', 42], ['tahini', 10], ['zitrone', 10], ['knoblauch', 2], ['olivenoel', 5], ['gewuerze', 1], ['salz', 0.5], ['karotte', 80], ['gurke', 80], ['paprika', 80]],
    s: [
      'Kichererbsen abspülen (einige EL Kochwasser auffangen).',
      'Mit Tahini, Zitronensaft, Knoblauch und Kreuzkümmel im Mixer 2 Min. fein pürieren, dabei 2–3 EL eiskaltes Wasser zugeben, bis der Hummus cremig ist.',
      'Für Baby/Kleinkind eine Portion ungesalzen entnehmen, Rest salzen.',
      'In eine Schale streichen, mit Olivenöl beträufeln und mit Paprikapulver bestäuben.',
      'Karotte, Gurke und Paprika in Sticks schneiden und zum Dippen servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Abgetropfte Kichererbsen, Tahini, Zitronensaft und Kreuzkümmel zugeben und pürieren, dabei 2–3 EL eiskaltes Wasser durch die Deckelöffnung zugeben; zwischendurch mit dem Spatel nach unten schieben.', '2 Min.', '', 'Stufe 8', ''],
        ['Für Baby/Kleinkind eine Portion ungesalzen entnehmen.', '', '', '', ''],
        ['Rest salzen und kurz verrühren.', '10 Sek.', '', 'Stufe 4', ''],
        ['In eine Schale streichen, mit Olivenöl beträufeln und mit Paprikapulver bestäuben.', '', '', '', ''],
        ['Gemüse in Sticks schneiden (Karotten fürs Baby weich dämpfen) und zum Dippen servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenen Hummus auf Toaststreifen streichen oder weich gedämpfte Karottensticks hineindippen (rohe Karotte ist zu hart). Kleinkind (1–3 J.): Gurken- und Paprikasticks, Karotte kurz blanchiert.',
    baby: 2,
  },
  {
    id: 'energy-balls',
    n: 'Energy Balls',
    img: { file: 'Energy Balls (Unsplash).jpg', q: 'energy balls dates oats cocoa' },
    cu: 'international',
    m: ['snack'],
    t: 15, d: 1,
    st: ['mealprep', 'kinderliebling'],
    i: [['haferflocken', 20], ['datteln', 25], ['erdnussbutter', 15], ['whey', 10], ['kakao', 3], ['kokosraspeln', 5]],
    s: [
      'Datteln 10 Min. in heißem Wasser einweichen und abtropfen lassen.',
      'Mit Haferflocken, Erdnussmus, Whey und Kakao im Mixer zu einer klebrigen Masse pürieren; ist sie zu trocken, 1 EL Wasser zugeben.',
      'Mit feuchten Händen walnussgroße Kugeln formen (ca. 3 Stück pro Portion).',
      'In Kokosraspeln wälzen und mindestens 30 Min. kühlen. Halten 5 Tage im Kühlschrank.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Ergibt ca. 12 Kugeln.',
      steps: [
        ['Datteln 10 Min. in heißem Wasser einweichen und abtropfen lassen.', '', '', '', ''],
        ['Datteln, Haferflocken, Erdnussmus und Kakao in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '20 Sek.', '', 'Stufe 7', ''],
        ['Für Baby/Kleinkind einen Teil der Masse ohne Whey entnehmen.', '', '', '', ''],
        ['Whey zugeben und zu einer klebrigen Masse verarbeiten; ist sie zu trocken, 1 EL Wasser zugeben.', '15 Sek.', '', 'Stufe 5', ''],
        ['Mit feuchten Händen Kugeln formen, in Kokosraspeln wälzen und mindestens 30 Min. kühlen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ohne Whey zubereiten, Masse zu flachen weichen Talern drücken statt fester Kugeln; Erdnuss früh und in kleinen Mengen einführen. Kleinkind (1–3 J.): ohne Whey, Kugeln halbieren.',
    baby: 1,
  },
  {
    id: 'protein-mug-cake',
    n: 'Protein Mug Cake',
    img: { wiki: 'Mug cake', q: 'chocolate protein mug cake' },
    cu: 'amerikanisch',
    m: ['snack'],
    t: 5, d: 1,
    st: ['comfort'],
    i: [['whey', 25], ['ei', 60], ['haferflocken', 15], ['kakao', 5], ['milch', 30], ['backpulver', 2], ['zartbitter', 5]],
    s: [
      'Haferflocken fein mahlen.',
      'Mit Whey, Kakao und Backpulver in einer großen Tasse mischen.',
      'Ei und Milch zugeben und mit einer Gabel glatt rühren, Schokolade grob hacken und unterheben.',
      'In der Mikrowelle bei 800 W 60–75 Sek. garen, bis der Kuchen aufgegangen, aber innen noch saftig ist.',
      '1 Min. ruhen lassen und warm genießen.',
    ],
    tm: {
      fit: 1,
      note: 'Für 4 Tassen ausgelegt. Gegart wird in der Mikrowelle.',
      steps: [
        ['Schokolade in den Mixtopf geben, grob hacken und umfüllen.', '3 Sek.', '', 'Stufe 6', ''],
        ['Haferflocken in den Mixtopf geben und fein mahlen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Whey, Kakao, Backpulver, Eier und Milch zugeben und glatt verrühren.', '15 Sek.', '', 'Stufe 4', ''],
        ['Schokolade zugeben und unterheben.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Teig auf 4 große Tassen verteilen und nacheinander in der Mikrowelle bei 800 W je 60–75 Sek. garen.', '', '', '', ''],
        ['1 Min. ruhen lassen und warm genießen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): eher nicht geeignet (Proteinpulver, Schokolade); stattdessen ein Bananen-Ei-Hafer-Tassenkuchen ohne Whey und Schokolade, durchgegart, in Streifen. Kleinkind (1–3 J.): kleine Portion ohne Whey und Schokolade, mit zerdrückter Banane.',
    baby: 1,
  },
  {
    id: 'protein-bananenbrot',
    n: 'Protein-Bananenbrot',
    img: { wiki: 'Banana bread', q: 'protein banana bread slice' },
    cu: 'amerikanisch',
    m: ['snack', 'fruehstueck'],
    t: 60, d: 1,
    st: ['mealprep', 'kinderliebling'],
    i: [['banane', 30], ['ei', 18], ['haferflocken', 20], ['magerquark', 25], ['whey', 9], ['walnuesse', 5], ['backpulver', 1.5], ['ahornsirup', 3], ['vanille', 0.5]],
    s: [
      'Ofen auf 175 °C Ober-/Unterhitze vorheizen, eine Kastenform (25 cm) mit Backpapier auslegen. 1 Portion = 1 dicke Scheibe, das Rezept ergibt 10 Scheiben.',
      '300 g sehr reife Bananen zerdrücken, mit 3 Eiern, 250 g Quark und 30 g Ahornsirup glatt rühren.',
      '200 g Haferflocken fein mahlen, mit 90 g Whey, 1 Päckchen Backpulver und Zimt mischen und unter die Bananenmasse rühren.',
      '50 g Walnüsse hacken und unterheben (für Kinder-Ende nur gemahlen bzw. weglassen).',
      'Teig in die Form füllen und 45–50 Min. backen (Stäbchenprobe). In der Form 10 Min., dann auf dem Gitter vollständig abkühlen lassen.',
    ],
    tm: {
      fit: 1,
      note: 'Ergibt eine Kastenform (10 Scheiben), der Teig passt in einem Durchgang in den Mixtopf. Gebacken wird im Ofen.',
      steps: [
        ['Ofen auf 175 °C Ober-/Unterhitze vorheizen, Kastenform mit Backpapier auslegen.', '', '', '', ''],
        ['Walnüsse in den Mixtopf geben, grob hacken und umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
        ['Haferflocken in den Mixtopf geben und fein mahlen.', '15 Sek.', '', 'Stufe 10', ''],
        ['Bananen in Stücken, Eier, Quark und Ahornsirup zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
        ['Whey, Backpulver und Zimt zugeben und zu einem glatten Teig verrühren.', '15 Sek.', '', 'Stufe 4', ''],
        ['Für das Kinder-Ende ein Drittel des Teigs ohne Nüsse an ein Ende der Form füllen.', '', '', '', ''],
        ['Walnüsse zum restlichen Teig geben und unterheben.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Restlichen Teig in die Form füllen, 45–50 Min. backen (Stäbchenprobe) und auf dem Gitter abkühlen lassen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): für die Kleinen gern eine Mini-Form ohne Whey, Nüsse und Sirup backen – Scheibe in Streifen als weiches Fingerfood. Kleinkind (1–3 J.): Scheibe ohne Nussstücke (Nüsse gemahlen), in Würfel geschnitten.',
    baby: 1,
  },
  {
    id: 'edamame-meersalz-sesam',
    n: 'Edamame mit Meersalz & Sesam',
    img: { wiki: 'Edamame', q: 'edamame sea salt sesame' },
    cu: 'asiatisch',
    m: ['snack'],
    t: 10, d: 1,
    i: [['edamame', 90], ['sesam', 6], ['sesamoel', 3], ['salz', 0.8]],
    s: [
      'Wasser in einem Topf aufkochen und die TK-Edamame darin 4–5 Min. garen.',
      'Sesam in einer trockenen Pfanne 2 Min. goldbraun rösten.',
      'Edamame abgießen und gut abtropfen lassen; Portion für Baby/Kleinkind vor dem Würzen abnehmen.',
      'Restliche Edamame mit Sesamöl, geröstetem Sesam und grobem Meersalz mischen und warm servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Sesam in den Mixtopf geben, ohne Fett goldbraun rösten und umfüllen.', '4 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['500 g Wasser in den Mixtopf geben, TK-Edamame in den Varoma-Behälter geben, aufsetzen und dampfgaren.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Portion für Baby/Kleinkind ungewürzt abnehmen (fürs Baby etwas länger garen und zerdrücken).', '', '', '', ''],
        ['Restliche Edamame mit Sesamöl, geröstetem Sesam und Meersalz mischen und warm servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Edamame etwas länger weich garen und mit der Gabel zerdrücken oder zu Mus pürieren (ganze Bohnen = Verschluckungsgefahr). Kleinkind (1–3 J.): ungesalzen, Bohnen leicht zerdrückt, Sesam gemahlen.',
    baby: 1,
  },
]);
