// Frühstück international (Erweiterung 2): herzhaft & süß
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  {
    id: 'eggs-benedict-glutenfrei',
    n: 'Eggs Benedict (glutenfrei) mit leichter Hollandaise',
    img: { wiki: 'Eggs Benedict', q: 'eggs benedict poached egg ham hollandaise' },
    cu: 'amerikanisch', m: ['fruehstueck'], t: 25, d: 2, st: ['comfort'],
    ck: 'Eggs Benedict',
    i: [['broetchen_gf', 70], ['schinken_gekocht', 50], ['ei', 120], ['skyr', 40], ['butter', 5], ['senf', 3], ['zitronensaft', 6], ['spinat', 40], ['salz', 0.4]],
    s: [
      'Für die leichte Hollandaise Skyr, Senf, Zitronensaft und geschmolzene Butter glatt rühren und im Wasserbad bei kleiner Hitze 3 Min. lauwarm erwärmen (nicht kochen).',
      'Wasser in einem Topf aufkochen, Hitze reduzieren, bis es nur noch siedet (ca. 90 °C), einen Strudel rühren und die Eier einzeln 3–4 Min. pochieren.',
      'Glutenfreie Brötchen halbieren und toasten, Spinat in einer Pfanne 1 Min. zusammenfallen lassen.',
      'Brötchenhälften mit Spinat und Kochschinken belegen, je ein pochiertes Ei daraufsetzen.',
      'Für Baby/Kleinkind ein Ei hart kochen statt pochieren und ohne Schinken und Salz abnehmen.',
      'Restliche Portionen mit Hollandaise überziehen, leicht salzen und sofort servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Die Eier werden im Topf pochiert.', steps: [
      ['Butter in den Mixtopf geben und schmelzen.', '2 Min.', '50°C', 'Stufe 1', ''],
      ['Skyr, Senf und Zitronensaft zugeben und zu einer leichten Hollandaise verrühren.', '3 Min.', '50°C', 'Stufe 3', ''],
      ['Sauce umfüllen und warm halten.', '', '', '', ''],
      ['Eier im siedenden Wasser im Topf 3–4 Min. pochieren, Brötchen toasten und Spinat in der Pfanne kurz zusammenfallen lassen.', '', '', '', ''],
      ['Für Baby/Kleinkind ein Ei hart kochen, ohne Schinken und Salz abnehmen.', '', '', '', ''],
      ['Brötchen mit Spinat, Schinken und Ei belegen und mit Hollandaise überziehen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Ei hart kochen (kein flüssiges Eigelb), in Streifen schneiden und mit weichem, getoastetem Brötchenstreifen und gehacktem Spinat als Fingerfood anbieten, ohne Schinken. Kleinkind (1–3 J.): Brötchenhälfte mit hart gekochtem Ei und wenig Hollandaise, Schinken nur in kleinen Mengen.',
    baby: 1,
  },
  {
    id: 'huevos-rancheros',
    n: 'Huevos Rancheros',
    img: { wiki: 'Huevos rancheros', q: 'huevos rancheros fried eggs tortilla salsa beans' },
    cu: 'mexikanisch', m: ['fruehstueck', 'mittag'], t: 20, d: 1, st: ['comfort'],
    ck: 'Huevos Rancheros',
    i: [['tortilla_mais', 60], ['ei', 120], ['schwarze_bohnen', 50], ['salsa', 60], ['avocado', 25], ['feta', 10], ['rapsoel', 3], ['gewuerze', 1.5], ['kraeuter', 3], ['limette', 10]],
    s: [
      'Schwarze Bohnen abspülen, mit Kreuzkümmel und 2 EL Wasser in einem kleinen Topf 4 Min. erhitzen und grob zerdrücken.',
      'Maistortillas in einer trockenen Pfanne je Seite 30 Sek. erwärmen und warm halten.',
      'Öl in der Pfanne erhitzen und die Eier bei mittlerer Hitze 4–5 Min. als Spiegeleier braten.',
      'Salsa in einem kleinen Topf 2 Min. erwärmen.',
      'Tortillas mit Bohnenmus bestreichen, Spiegelei daraufsetzen, mit Salsa, Avocado, zerbröseltem Feta, Koriander und Limettensaft garnieren.',
      'Für Baby/Kleinkind Bohnenmus ungewürzt abnehmen und das Ei durchbraten.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Bohnenmus und Salsa im Thermomix, Eier in der Pfanne.', steps: [
      ['Bohnen, Kreuzkümmel und 30 g Wasser in den Mixtopf geben und erhitzen.', '4 Min.', '100°C', 'Stufe 1', ''],
      ['Für Baby/Kleinkind 2 EL Bohnen ungewürzt entnehmen.', '', '', '', ''],
      ['Bohnen grob zerkleinern und umfüllen.', '5 Sek.', '', 'Stufe 4', ''],
      ['Salsa in den Mixtopf geben und erwärmen.', '3 Min.', '90°C', 'Stufe 1', ''],
      ['Tortillas in der Pfanne erwärmen, Spiegeleier braten.', '', '', '', ''],
      ['Tortillas mit Bohnenmus, Ei, Salsa, Avocado, Feta, Koriander und Limette anrichten.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungewürztes Bohnenmus mit zerdrückter Avocado auf weichem Tortillastreifen, Ei vollständig durchgebraten in Streifen. Kleinkind (1–3 J.): Tortilla in Dreiecke schneiden, milde Salsa, Ei durchgebraten, wenig Feta.',
    baby: 2,
  },
  {
    id: 'menemen',
    n: 'Menemen (türkisches Rührei mit Tomate & Paprika)',
    img: { wiki: 'Menemen (food)', q: 'menemen turkish scrambled eggs tomato pepper' },
    cu: 'orientalisch', m: ['fruehstueck'], t: 20, d: 1, st: ['comfort'],
    ck: 'Menemen',
    i: [['ei', 180], ['tomate', 150], ['paprika', 80], ['zwiebel', 30], ['olivenoel', 6], ['chili_frisch', 2], ['gewuerze', 1.5], ['salz', 0.6], ['kraeuter', 3], ['sauerteigbrot', 40]],
    s: [
      'Zwiebel fein würfeln, Paprika (traditionell Spitzpaprika) in Streifen schneiden, Tomaten würfeln.',
      'Öl in einer Pfanne erhitzen, Zwiebel und Paprika bei mittlerer Hitze 5 Min. weich dünsten.',
      'Tomaten zugeben und 5–6 Min. einköcheln, bis eine dicke Sauce entsteht.',
      'Eier verquirlen, zugeben und bei schwacher Hitze unter langsamem Rühren 2–3 Min. cremig stocken lassen.',
      'Für Baby/Kleinkind eine Portion ohne Salz und Chili entnehmen und vollständig durchgaren.',
      'Rest mit Salz, Pul Biber (Paprikaflocken) und frischer Chili würzen, mit Petersilie bestreuen und mit Brot servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Die Eier stocken in der Pfanne.', steps: [
      ['Zwiebel in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
      ['Olivenöl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
      ['Paprikastreifen und Tomatenwürfel zugeben und einköcheln, Garkörbchen als Spritzschutz aufsetzen.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Gemüse in eine Pfanne geben, verquirlte Eier zugeben und bei schwacher Hitze cremig stocken lassen.', '', '', '', ''],
      ['Für Baby/Kleinkind eine Portion ungewürzt entnehmen und durchgaren.', '', '', '', ''],
      ['Rest mit Salz, Pul Biber und Chili würzen, mit Petersilie und Brot servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzenes, gut durchgegartes Menemen mit weichem Brotstreifen zum Dippen oder als Löffelkost. Kleinkind (1–3 J.): ohne Chili, Tomatenhaut bei Bedarf entfernen, Brotwürfel dazu.',
    baby: 2,
  },
  {
    id: 'tamagoyaki-reis',
    n: 'Tamagoyaki mit Reis & Gurke',
    img: { wiki: 'Tamagoyaki', q: 'tamagoyaki japanese rolled omelette' },
    cu: 'asiatisch', m: ['fruehstueck'], t: 30, d: 2, st: ['kinderliebling'],
    ck: 'Tamagoyaki',
    i: [['ei', 180], ['sojasauce', 6], ['zucker', 3], ['rapsoel', 4], ['reis', 40], ['spinat', 50], ['gurke', 50], ['sesam', 3], ['salz', 0.2]],
    s: [
      'Reis waschen und mit der doppelten Menge Wasser 12 Min. zugedeckt garen, 5 Min. ziehen lassen.',
      'Eier mit Sojasauce, Zucker und 2 EL Wasser verquirlen. Für Baby/Kleinkind vorher ein Ei ohne Sojasauce und Zucker separat verquirlen.',
      'Eine (eckige) Pfanne leicht einölen, ein Drittel der Eimasse dünn einfüllen, bei mittlerer Hitze fast stocken lassen und von einer Seite aufrollen.',
      'Rolle zur Seite schieben, Pfanne erneut einfetten, die nächste Schicht einfüllen, unter die Rolle laufen lassen und wieder aufrollen. Insgesamt 3–4 Schichten.',
      'Omelettrolle kurz ruhen lassen und in 2 cm dicke Scheiben schneiden.',
      'Spinat in der Pfanne 1 Min. zusammenfallen lassen, mit Sesam bestreuen. Mit Reis und Gurkenscheiben servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Reis im Thermomix, die Omelettrolle in der Pfanne.', steps: [
      ['1000 g Wasser in den Mixtopf geben, Garkörbchen einhängen, Reis einwiegen und garen.', '20 Min.', '100°C', 'Stufe 4', ''],
      ['Garkörbchen entnehmen, Reis warm halten, Mixtopf leeren.', '', '', '', ''],
      ['Für Baby/Kleinkind ein Ei separat ohne Sojasauce und Zucker verquirlen.', '', '', '', ''],
      ['Eier, Sojasauce, Zucker und 30 g Wasser in den Mixtopf geben und verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
      ['Eimasse in mehreren dünnen Schichten in der Pfanne stocken lassen und aufrollen, in Scheiben schneiden.', '', '', '', ''],
      ['Spinat kurz in der Pfanne garen, mit Sesam bestreuen und mit Reis und Gurke servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Tamagoyaki aus dem ungewürzten Ei vollständig durchgegart in fingerdicken Streifen, Reis weich gekocht und zu kleinen Bällchen gedrückt. Kleinkind (1–3 J.): Omelettscheiben ohne Sojasauce, Gurke in Stiften, Sesam gemahlen.',
    baby: 2,
  },
  {
    id: 'congee-haehnchen-ei',
    n: 'Congee (Reisbrei) mit Hähnchen & Ei',
    img: { wiki: 'Congee', q: 'congee rice porridge chicken egg' },
    cu: 'asiatisch', m: ['fruehstueck', 'abend'], t: 50, d: 1, st: ['comfort', 'mealprep'],
    ck: 'Congee',
    i: [['reis', 45], ['huehnerbruehe', 350], ['haehnchenbrust', 100], ['ei', 60], ['ingwer', 6], ['fruehlingszwiebel', 15], ['sojasauce', 8], ['sesamoel', 3], ['salz', 0.3]],
    s: [
      'Reis waschen und mit Brühe, 200 ml Wasser und Ingwerscheiben aufkochen.',
      'Bei schwacher Hitze halb zugedeckt 35–40 Min. köcheln, dabei regelmäßig rühren, bis ein sämiger Brei entsteht.',
      'Hähnchenbrust in feine Streifen schneiden, die letzten 8 Min. im Congee gar ziehen lassen.',
      'Eier 7 Min. wachsweich kochen, abschrecken, schälen und halbieren.',
      'Für Baby/Kleinkind eine Portion ohne Sojasauce entnehmen (mit ungesalzener Brühe ansetzen oder mit Wasser verdünnen).',
      'Rest mit Sojasauce, Sesamöl und Frühlingszwiebelringen würzen und mit dem Ei servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['Ingwer in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Reis, Brühe und 800 g Wasser zugeben und köcheln, Garkörbchen als Spritzschutz aufsetzen.', '40 Min.', '95°C', 'Stufe 1', 'Linkslauf'],
      ['Eier in den Varoma-Behälter legen. Hähnchenstreifen in den Mixtopf geben, Varoma aufsetzen und garen.', '12 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
      ['Eier abschrecken, schälen und halbieren.', '', '', '', ''],
      ['Für Baby/Kleinkind eine Portion ohne Sojasauce entnehmen.', '', '', '', ''],
      ['Rest mit Sojasauce und Sesamöl würzen, mit Frühlingszwiebeln und Ei servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Congee mit Wasser statt Brühe ansetzen, Hähnchen fein zerzupfen, hart gekochtes Ei zerdrücken – ideal als Brei vom Löffel. Kleinkind (1–3 J.): ohne Sojasauce, Hähnchen klein gezupft, Ei geviertelt, Ingwer entfernen.',
    baby: 2,
  },
  {
    id: 'gruene-shakshuka',
    n: 'Grüne Shakshuka mit Spinat & Zucchini',
    img: { wiki: 'Shakshouka', q: 'green shakshuka spinach eggs pan' },
    cu: 'orientalisch', m: ['fruehstueck', 'abend'], t: 25, d: 1, st: ['comfort'],
    ck: 'Grüne Shakshuka',
    i: [['spinat', 100], ['zucchini', 100], ['lauch', 60], ['olivenoel', 6], ['knoblauch', 4], ['gewuerze', 2], ['ei', 120], ['feta', 25], ['griech_joghurt', 50], ['kraeuter', 5], ['zitronensaft', 5], ['salz', 0.6], ['sauerteigbrot', 30]],
    s: [
      'Lauch in feine Ringe, Zucchini in kleine Würfel schneiden, Knoblauch hacken.',
      'Öl in einer Pfanne erhitzen, Lauch und Zucchini 6 Min. bei mittlerer Hitze dünsten, Knoblauch und Kreuzkümmel 1 Min. mitbraten.',
      'Spinat portionsweise zugeben und zusammenfallen lassen, mit Zitronensaft abschmecken.',
      'Für Baby/Kleinkind 2–3 EL Gemüse ungesalzen entnehmen, Rest salzen.',
      'Mulden formen, Eier hineinschlagen und zugedeckt bei schwacher Hitze 6–8 Min. stocken lassen.',
      'Mit Feta, Joghurt und Kräutern (Dill, Petersilie) toppen und mit geröstetem Brot servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Die Eier stocken in der Pfanne.', steps: [
      ['Knoblauch und Lauch in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
      ['Olivenöl und Kreuzkümmel zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
      ['Zucchiniwürfel und Spinat zugeben und garen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Für Baby/Kleinkind 2–3 EL Gemüse ungesalzen entnehmen, Rest mit Zitronensaft und Salz abschmecken.', '', '', '', ''],
      ['Gemüse in eine Pfanne geben, Mulden formen, Eier hineinschlagen und zugedeckt stocken lassen.', '', '', '', ''],
      ['Mit Feta, Joghurt und Kräutern servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzenes Gemüse fein pürieren, ein Ei vollständig durchgaren und zerdrücken, ohne Feta. Kleinkind (1–3 J.): Ei durchgegart, Gemüse mit Joghurt und Brotstreifen zum Dippen, Feta nur wenig.',
    baby: 2,
  },
  {
    id: 'feta-shakshuka-kichererbsen',
    n: 'Feta-Shakshuka mit Kichererbsen',
    img: { wiki: 'Shakshouka', q: 'shakshuka feta chickpeas eggs skillet' },
    cu: 'orientalisch', m: ['fruehstueck', 'abend'], t: 25, d: 1, st: ['comfort'],
    ck: 'Shakshuka mit Feta',
    i: [['tomaten_dose', 200], ['paprika', 80], ['zwiebel', 30], ['knoblauch', 4], ['olivenoel', 6], ['gewuerze', 2.5], ['kichererbsen', 40], ['ei', 120], ['feta', 30], ['kraeuter', 4], ['salz', 0.4]],
    s: [
      'Zwiebel, Paprika und Knoblauch würfeln und im Öl 5 Min. bei mittlerer Hitze dünsten.',
      'Paprikapulver, Kreuzkümmel und etwas Zimt 30 Sek. mitrösten, Tomaten und abgespülte Kichererbsen zugeben und 10 Min. einköcheln.',
      'Für Baby/Kleinkind 2–3 EL Sauce ungesalzen entnehmen, Rest leicht salzen (Feta ist salzig).',
      'Feta in groben Stücken in die Sauce setzen, Mulden formen und die Eier hineinschlagen.',
      'Zugedeckt bei schwacher Hitze 6–8 Min. stocken lassen, bis das Eiweiß fest ist.',
      'Mit Petersilie bestreuen und in der Pfanne servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Die Eier stocken in der Pfanne.', steps: [
      ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
      ['Paprika in Stücken zugeben und zerkleinern.', '4 Sek.', '', 'Stufe 4', ''],
      ['Olivenöl und Gewürze zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
      ['Tomaten und Kichererbsen zugeben und einköcheln, Garkörbchen als Spritzschutz aufsetzen.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Für Baby/Kleinkind 2–3 EL Sauce ungesalzen entnehmen, Rest leicht salzen.', '', '', '', ''],
      ['Sauce in eine Pfanne geben, Feta und Eier hineinsetzen und zugedeckt stocken lassen.', '', '', '', ''],
      ['Mit Petersilie bestreuen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzene Sauce mit zerdrückten Kichererbsen und vollständig gegartem Ei, ohne Feta. Kleinkind (1–3 J.): Kichererbsen zerdrücken (Verschluckungsgefahr), Ei durchgaren, wenig Feta.',
    baby: 2,
  },
  {
    id: 'apfelstrudel-protein-porridge',
    n: 'Apfelstrudel-Protein-Porridge',
    img: { wiki: 'Porridge', q: 'apple cinnamon oatmeal porridge raisins' },
    cu: 'deutsch', m: ['fruehstueck'], t: 12, d: 1, st: ['comfort'],
    ck: 'Apfel-Zimt-Porridge',
    i: [['haferflocken', 50], ['milch', 200], ['whey', 20], ['apfel', 80], ['zimt', 1.5], ['rosinen', 10], ['mandeln', 8]],
    s: [
      'Apfel entkernen und klein würfeln, mit Rosinen, Zimt und 2 EL Wasser in einem kleinen Topf 4 Min. weich dünsten.',
      'Haferflocken mit Milch aufkochen und bei schwacher Hitze 4–5 Min. cremig quellen lassen.',
      'Für Baby/Kleinkind eine Portion ohne Proteinpulver und ohne Rosinen abnehmen.',
      'Topf vom Herd nehmen, Whey mit 2 EL kaltem Wasser glatt rühren und unterziehen (nicht mehr kochen).',
      'Porridge mit den Zimtäpfeln und gehackten, gerösteten Mandeln toppen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['Mandeln in den Mixtopf geben, grob hacken und umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
      ['Apfelwürfel, Rosinen, Zimt und 30 g Wasser in den Mixtopf geben und dünsten.', '5 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Zimtäpfel umfüllen. Haferflocken und Milch in den Mixtopf geben und garen.', '10 Min.', '90°C', 'Stufe 2', 'Linkslauf'],
      ['Für Baby/Kleinkind eine Portion ohne Proteinpulver entnehmen.', '', '', '', ''],
      ['Whey mit wenig kaltem Wasser glatt rühren, zugeben und ohne Hitze unterrühren.', '20 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Porridge mit Zimtäpfeln und Mandeln servieren.', '', '', '', ''],
    ] },
    kid: 'Kinderportion ohne Whey. Baby (6–12 Mon.): Porridge etwas dünner, Apfel weich gedünstet und zerdrückt, ohne Rosinen und Mandeln (oder Mandeln fein gemahlen). Kleinkind (1–3 J.): Rosinen gehackt, Mandeln gemahlen.',
    baby: 1,
  },
  {
    id: 'schoko-bananen-protein-porridge',
    n: 'Schoko-Bananen-Protein-Porridge mit Erdnussmus',
    img: { wiki: 'Porridge', q: 'chocolate banana oatmeal peanut butter' },
    cu: 'international', m: ['fruehstueck'], t: 10, d: 1, st: ['kinderliebling'],
    ck: 'Schoko-Porridge',
    i: [['haferflocken', 45], ['milch', 200], ['esn_designer_whey', 20], ['kakao', 6], ['banane', 60], ['erdnussbutter', 8]],
    s: [
      'Haferflocken, Kakao und Milch in einem Topf aufkochen.',
      'Bei schwacher Hitze unter Rühren 4–5 Min. cremig quellen lassen.',
      'Für Baby/Kleinkind eine Portion ohne Proteinpulver abnehmen.',
      'Vom Herd nehmen, Whey mit 2 EL kaltem Wasser glatt rühren und unter den restlichen Porridge ziehen.',
      'Mit Bananenscheiben und einem Klecks Erdnussmus servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['Haferflocken, Kakao und Milch in den Mixtopf geben und garen.', '10 Min.', '90°C', 'Stufe 2', 'Linkslauf'],
      ['Für Baby/Kleinkind eine Portion ohne Proteinpulver entnehmen.', '', '', '', ''],
      ['Whey mit wenig kaltem Wasser glatt rühren, zugeben und ohne Hitze unterrühren.', '20 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Porridge mit Bananenscheiben und Erdnussmus anrichten.', '', '', '', ''],
    ] },
    kid: 'Kinderportion ohne Whey, Banane zerdrückt untergerührt. Baby (6–12 Mon.): wenig Kakao, Erdnussmus nur dünn eingerührt (nie als Klecks pur – klebt). Kleinkind (1–3 J.): Bananenscheiben geviertelt, Erdnussmus eingerührt.',
    baby: 1,
  },
  {
    id: 'carrot-cake-porridge-quark',
    n: 'Carrot-Cake-Porridge mit Quark',
    img: { wiki: 'Porridge', q: 'carrot cake oatmeal walnuts' },
    cu: 'amerikanisch', m: ['fruehstueck'], t: 12, d: 1, st: ['comfort', 'kinderliebling'],
    ck: 'Karotten-Porridge',
    i: [['haferflocken', 45], ['milch', 150], ['karotte', 50], ['magerquark', 100], ['walnuesse', 8], ['zimt', 1.5], ['rosinen', 10], ['vanille', 1]],
    s: [
      'Karotte fein raspeln.',
      'Haferflocken, Karotte, Rosinen, Zimt und Milch aufkochen und bei schwacher Hitze 5–6 Min. quellen lassen, bis die Karotte weich ist.',
      'Quark mit Vanille glatt rühren (das ist das „Frosting“).',
      'Porridge in eine Schale geben, Quark daraufsetzen und mit gehackten Walnüssen bestreuen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['Walnüsse in den Mixtopf geben, hacken und umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
      ['Karotten in Stücken in den Mixtopf geben und raspeln.', '4 Sek.', '', 'Stufe 5', ''],
      ['Haferflocken, Rosinen, Zimt und Milch zugeben und garen.', '10 Min.', '90°C', 'Stufe 2', 'Linkslauf'],
      ['Porridge umfüllen, Quark und Vanille kurz verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Porridge mit Quark-Frosting und Walnüssen servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Porridge mit fein geriebener Karotte, ohne Rosinen und Walnüsse (oder Nüsse fein gemahlen), Quark nur 1–2 EL. Kleinkind (1–3 J.): Rosinen gehackt, Walnüsse gemahlen.',
    baby: 2,
  },
  {
    id: 'herzhafte-quinoa-bowl-ei-avocado',
    n: 'Herzhafte Quinoa-Frühstücksbowl mit Ei & Avocado',
    img: { wiki: 'Buddha bowl', q: 'savory quinoa breakfast bowl egg avocado' },
    cu: 'international', m: ['fruehstueck', 'mittag'], t: 25, d: 1, st: ['mealprep'],
    ck: 'Quinoa Bowl Ei',
    i: [['quinoa', 45], ['ei', 120], ['avocado', 30], ['spinat', 40], ['kirschtomaten', 80], ['feta', 15], ['zitronensaft', 8], ['olivenoel', 3], ['salz', 0.5], ['gewuerze', 1]],
    s: [
      'Quinoa heiß abspülen und in der doppelten Menge Wasser 15 Min. garen, 5 Min. nachquellen lassen.',
      'Eier 7 Min. wachsweich kochen (für Baby/Kleinkind 10 Min. hart), abschrecken und schälen.',
      'Quinoa mit Zitronensaft, Öl und Salz würzen, Spinat unterheben.',
      'Kirschtomaten vierteln, Avocado in Scheiben schneiden.',
      'Alles in Schalen anrichten, halbierte Eier daraufsetzen, mit Feta und Chiliflocken bestreuen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['1000 g Wasser in den Mixtopf geben, Garkörbchen mit gewaschener Quinoa einhängen.', '', '', '', ''],
      ['Eier in den Varoma-Behälter legen, aufsetzen und alles garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
      ['Eier abschrecken und schälen, für Baby/Kleinkind ein hartes Ei beiseitelegen.', '', '', '', ''],
      ['Quinoa mit Zitronensaft, Öl und Salz würzen, Spinat unterheben.', '', '', '', ''],
      ['Mit Tomaten, Avocado, Ei und Feta anrichten.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzene Quinoa mit zerdrückter Avocado zu Bällchen formen, hart gekochtes Ei in Spalten, Tomaten nur gehäutet und klein. Kleinkind (1–3 J.): Kirschtomaten längs vierteln, Ei hart gekocht, wenig Feta.',
    baby: 2,
  },
  {
    id: 'spinat-champignon-omelett-huettenkaese',
    n: 'Spinat-Champignon-Omelett mit Hüttenkäse',
    img: { wiki: 'Omelette', q: 'spinach mushroom omelette cottage cheese' },
    cu: 'international', m: ['fruehstueck', 'abend'], t: 15, d: 1,
    ck: 'Omelett mit Spinat',
    i: [['ei', 180], ['huettenkaese', 80], ['spinat', 60], ['champignons', 80], ['rapsoel', 5], ['kraeuter', 3], ['salz', 0.5], ['toast_vollkorn', 28]],
    s: [
      'Champignons in Scheiben schneiden und in der Hälfte des Öls 4 Min. braten, Spinat zugeben und zusammenfallen lassen, herausnehmen.',
      'Eier mit Schnittlauch verquirlen. Für Baby/Kleinkind eine kleine Menge ungesalzen abnehmen, Rest salzen.',
      'Restliches Öl in der Pfanne erhitzen, Eier einfüllen und bei mittlerer Hitze 3–4 Min. stocken lassen.',
      'Pilz-Spinat-Mischung und Hüttenkäse auf eine Hälfte geben, Omelett zuklappen und 1 Min. ziehen lassen.',
      'Mit getoastetem Brot servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Das Omelett wird in der Pfanne gebraten.', steps: [
      ['Champignons in den Varoma-Behälter, Spinat auf den Einlegeboden geben. 500 g Wasser in den Mixtopf füllen, Varoma aufsetzen und dämpfen.', '10 Min.', 'Varoma', 'Stufe 1', ''],
      ['Mixtopf leeren und abtrocknen. Eier und Schnittlauch hineingeben und verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
      ['Für Baby/Kleinkind eine kleine Menge ungesalzen entnehmen, Rest salzen.', '', '', '', ''],
      ['Omeletts in der Pfanne stocken lassen, mit Gemüse und Hüttenkäse füllen und zuklappen.', '', '', '', ''],
      ['Mit Toast servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzenes Omelett komplett durchgaren und in Streifen schneiden, Spinat fein gehackt mit eingebacken. Kleinkind (1–3 J.): Omelett-Röllchen mit Hüttenkäse, Pilze klein geschnitten.',
    baby: 2,
  },
  {
    id: 'denver-omelett',
    n: 'Denver Omelett mit Schinken, Paprika & Cheddar',
    img: { wiki: 'Denver omelette', q: 'denver omelette ham pepper onion' },
    cu: 'amerikanisch', m: ['fruehstueck'], t: 15, d: 1, st: ['kinderliebling'],
    ck: 'Omelett mit Schinken und Paprika',
    i: [['ei', 180], ['schinken_gekocht', 40], ['paprika', 60], ['zwiebel', 25], ['cheddar', 15], ['rapsoel', 4], ['salz', 0.2], ['kraeuter', 2]],
    s: [
      'Paprika, Zwiebel und Schinken klein würfeln.',
      'Zwiebel und Paprika in der Hälfte des Öls 4 Min. anbraten, Schinken 1 Min. mitbraten und herausnehmen.',
      'Eier mit Pfeffer verquirlen (Schinken und Käse bringen genug Salz mit).',
      'Restliches Öl erhitzen, Eier einfüllen, die Füllung darauf verteilen und bei mittlerer Hitze 3–4 Min. stocken lassen.',
      'Cheddar daraufstreuen, Omelett zuklappen, 1 Min. ziehen lassen und mit Schnittlauch servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Das Omelett wird in der Pfanne gebraten.', steps: [
      ['Zwiebel und Paprika in Stücken in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 4', ''],
      ['Öl zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
      ['Für Baby/Kleinkind 2 EL Gemüse entnehmen.', '', '', '', ''],
      ['Schinkenwürfel zugeben und mitgaren, dann umfüllen.', '1 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Eier im sauberen Mixtopf verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
      ['Omeletts in der Pfanne mit Füllung und Cheddar stocken lassen und zuklappen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Omelett ohne Schinken (gepökelt) und Käse, nur mit weichem Paprikagemüse, vollständig durchgegart in Streifen. Kleinkind (1–3 J.): wenig Schinken, Cheddar mild, Omelett in Würfeln.',
    baby: 1,
  },
  {
    id: 'masala-omelett',
    n: 'Masala-Omelett mit Koriander & Joghurt',
    img: { wiki: 'Omelette', q: 'indian masala omelette coriander onion tomato' },
    cu: 'indisch', m: ['fruehstueck'], t: 15, d: 1,
    ck: 'Indisches Omelett',
    i: [['ei', 180], ['tomate', 60], ['rote_zwiebel', 25], ['chili_frisch', 2], ['kraeuter', 4], ['currypulver', 1.5], ['rapsoel', 5], ['salz', 0.5], ['griech_joghurt', 50]],
    s: [
      'Zwiebel, Tomate (ohne Kerne) und Koriander fein hacken, Chili in feine Ringe schneiden.',
      'Eier mit Kurkuma/Garam Masala, Zwiebel, Tomate und Koriander verquirlen.',
      'Für Baby/Kleinkind eine kleine Portion ohne Chili und Salz separat braten, Rest mit Chili und Salz würzen.',
      'Öl in einer Pfanne erhitzen, Eimasse einfüllen und bei mittlerer Hitze 3 Min. stocken lassen, wenden und 1 Min. weiterbraten.',
      'Mit einem Klecks Joghurt servieren.',
    ],
    tm: { fit: 0, note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix zerkleinert, gebraten wird in der Pfanne.', steps: [
      ['Zwiebel und Koriander in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
      ['Eier, Tomatenwürfel und Gewürze zugeben und verquirlen.', '8 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ['Für Baby/Kleinkind eine kleine Portion ohne Chili und Salz entnehmen.', '', '', '', ''],
      ['Rest mit Chili und Salz würzen und in der Pfanne als Omeletts braten, mit Joghurt servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): mildes, ungesalzenes Omelett vollständig durchbraten und in Streifen schneiden, Joghurt als Dip. Kleinkind (1–3 J.): ohne Chili, Omelett zu Röllchen mit Joghurt.',
    baby: 2,
  },
  {
    id: 'fruehstuecks-wrap-ruehrei-spinat-feta',
    n: 'Frühstücks-Wrap mit Rührei, Spinat & Feta',
    img: { wiki: 'Wrap (food)', q: 'breakfast wrap scrambled eggs spinach feta' },
    cu: 'mediterran', m: ['fruehstueck'], t: 12, d: 1, st: ['kinderliebling'],
    ck: 'Frühstückswrap',
    i: [['tortilla', 60], ['ei', 120], ['eiklar', 60], ['spinat', 50], ['feta', 20], ['kirschtomaten', 50], ['rapsoel', 3], ['gewuerze', 1]],
    s: [
      'Eier und Eiklar mit Oregano und Pfeffer verquirlen (Feta salzt genug).',
      'Öl in einer Pfanne erhitzen, Spinat 1 Min. zusammenfallen lassen, Eier zugeben und bei mittlerer Hitze cremig stocken lassen.',
      'Für Baby/Kleinkind eine Portion Rührei ohne Feta abnehmen und vollständig durchgaren.',
      'Tortilla in der trockenen Pfanne 20 Sek. je Seite erwärmen.',
      'Rührei, zerbröselten Feta und geviertelte Kirschtomaten daraufgeben, fest einrollen und halbieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Das Rührei gelingt im Thermomix, die Wraps werden in der Pfanne erwärmt.', steps: [
      ['Eier, Eiklar und Gewürze in den Mixtopf geben und verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
      ['Öl und Spinat zugeben und zum Rührei garen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Für Baby/Kleinkind eine Portion ohne Feta entnehmen.', '', '', '', ''],
      ['Tortillas in der Pfanne erwärmen, mit Rührei, Feta und Tomaten füllen und einrollen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Rührei mit Spinat ohne Feta, durchgegart, auf weichen Tortillastreifen. Kleinkind (1–3 J.): kleiner Wrap in Scheiben (Pinwheels), Kirschtomaten längs geviertelt, wenig Feta.',
    baby: 2,
  },
  {
    id: 'schwarzwaelder-bircher',
    n: 'Schwarzwälder Bircher Müsli mit Kirschen & Kakao',
    img: { wiki: 'Muesli', q: 'chocolate cherry overnight muesli jar' },
    cu: 'deutsch', m: ['fruehstueck'], t: 10, d: 1, st: ['mealprep', 'kinderliebling'],
    ck: 'Bircher Müsli Kirsch',
    i: [['haferflocken', 45], ['skyr', 150], ['milch', 80], ['kakao', 6], ['sauerkirschen', 80], ['zartbitter', 6], ['erythrit', 5], ['vanille', 1]],
    s: [
      'Haferflocken, Kakao, Vanille, Erythrit, Milch und Skyr gründlich verrühren.',
      'Abgedeckt über Nacht im Kühlschrank quellen lassen.',
      'Sauerkirschen gut abtropfen lassen, Zartbitterschokolade fein hacken.',
      'Bircher mit Kirschen schichten und mit Schokoraspeln bestreuen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['Schokolade in den Mixtopf geben, raspeln und umfüllen.', '5 Sek.', '', 'Stufe 8', ''],
      ['Haferflocken, Kakao, Vanille, Erythrit, Milch und Skyr in den Mixtopf geben und verrühren.', '20 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ['In Gläser abwechselnd mit Kirschen schichten und über Nacht kühlen.', '', '', '', ''],
      ['Vor dem Servieren mit Schokoraspeln bestreuen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Haferflocken fein gemahlen, ohne Erythrit und Schokolade, Kirschen zerdrückt (Kerne kontrollieren). Kleinkind (1–3 J.): ohne Erythrit, Kirschen halbiert, wenig Schokoraspel.',
    baby: 2,
  },
  {
    id: 'quarkbroetchen-glutenfrei',
    n: 'Quarkbrötchen (glutenfrei) mit körnigem Frischkäse & Schinken',
    img: { q: 'gluten free quark rolls bread breakfast' },
    cu: 'deutsch', m: ['fruehstueck'], t: 35, d: 2, st: ['mealprep', 'kinderliebling'],
    ck: 'Quarkbrötchen glutenfrei',
    i: [['magerquark', 80], ['mehl_gf', 60], ['ei', 25], ['backpulver', 4], ['leinsamen', 5], ['salz', 0.6], ['koerniger_frischkaese', 60], ['schinken_gekocht', 30], ['gurke', 40]],
    s: [
      'Ofen auf 180 °C Umluft vorheizen, ein Blech mit Backpapier belegen.',
      'Quark, Ei und Salz glatt rühren, glutenfreies Mehl, Backpulver und geschrotete Leinsamen zugeben und zügig zu einem weichen Teig verkneten.',
      'Mit bemehlten Händen 2 Brötchen pro Portion formen, oben kreuzweise einschneiden.',
      'Ca. 22–25 Min. goldbraun backen und kurz abkühlen lassen.',
      'Aufschneiden, mit körnigem Frischkäse, Schinken und Gurkenscheiben belegen. Brötchen lassen sich gut einfrieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 8 Brötchen (4 Portionen). Gebacken wird im Ofen.', steps: [
      ['Quark, Ei und Salz in den Mixtopf geben und verrühren.', '10 Sek.', '', 'Stufe 4', ''],
      ['Glutenfreies Mehl, Backpulver und Leinsamen zugeben und kneten.', '1 Min.', '', '', 'Teigkneten'],
      ['Mit bemehlten Händen 8 Brötchen formen und einschneiden.', '', '', '', ''],
      ['Im Ofen bei 180 °C Umluft 22–25 Min. backen.', '', '', '', ''],
      ['Mit körnigem Frischkäse, Schinken und Gurke belegen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Brötchen ohne Salz backen, in Streifen schneiden und mit Frischkäse und Gurkenstreifen anbieten, ohne Schinken. Kleinkind (1–3 J.): Brötchen mit Frischkäse und Gurke, Schinken nur wenig.',
    baby: 1,
  },
  {
    id: 'huettenkaese-pfannkuchen',
    n: 'Hüttenkäse-Pfannkuchen mit Heidelbeeren',
    img: { wiki: 'Pancake', q: 'cottage cheese pancakes blueberries' },
    cu: 'amerikanisch', m: ['fruehstueck'], t: 20, d: 1, st: ['kinderliebling'],
    ck: 'Hüttenkäse-Pfannkuchen',
    i: [['huettenkaese', 150], ['ei', 60], ['haferflocken', 40], ['backpulver', 3], ['vanille', 1], ['rapsoel', 4], ['heidelbeeren', 70], ['ahornsirup', 5]],
    s: [
      'Hüttenkäse, Ei, Haferflocken, Backpulver und Vanille fein pürieren und 5 Min. quellen lassen.',
      'Wenig Öl in einer beschichteten Pfanne bei mittlerer Hitze erhitzen.',
      'Je 2 EL Teig als kleine Pfannkuchen hineingeben, einige Heidelbeeren daraufdrücken.',
      'Ca. 2–3 Min. backen, bis sich Bläschen bilden, wenden und 1–2 Min. fertig backen.',
      'Mit restlichen Heidelbeeren und Ahornsirup servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Ausgebacken wird in der Pfanne.', steps: [
      ['Haferflocken in den Mixtopf geben und mahlen.', '10 Sek.', '', 'Stufe 10', ''],
      ['Hüttenkäse, Eier, Backpulver und Vanille zugeben und zu einem glatten Teig mixen.', '20 Sek.', '', 'Stufe 6', ''],
      ['Teig 5 Min. quellen lassen.', '', '', '', ''],
      ['In der Pfanne kleine Pfannkuchen mit Heidelbeeren ausbacken.', '', '', '', ''],
      ['Mit Heidelbeeren und Ahornsirup servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): kleine Pfannkuchen ohne Sirup, Heidelbeeren gequetscht eingebacken – perfektes Fingerfood. Kleinkind (1–3 J.): ohne Sirup, Heidelbeeren halbiert, mit Apfelmus zum Dippen.',
    baby: 2,
  },
  {
    id: 'syrniki-quarkpfannkuchen',
    n: 'Syrniki (russische Quarkpfannkuchen) mit Himbeeren',
    img: { wiki: 'Syrniki', q: 'syrniki quark pancakes sour cream' },
    cu: 'international', m: ['fruehstueck'], t: 25, d: 2, st: ['comfort', 'kinderliebling'],
    ck: 'Syrniki',
    i: [['magerquark', 200], ['ei', 30], ['mehl', 30], ['erythrit', 6], ['vanille', 1], ['rapsoel', 6], ['schmand_light', 20], ['himbeeren', 60]],
    s: [
      'Quark gut abtropfen lassen (eventuell in einem Tuch ausdrücken), mit Ei, Erythrit und Vanille verrühren.',
      'Mehl (glutenfrei: glutenfreie Mehlmischung) unterrühren, sodass ein formbarer, leicht klebriger Teig entsteht.',
      'Mit bemehlten Händen kleine, 1,5 cm dicke Taler formen und rundum leicht in Mehl wenden.',
      'Öl in einer Pfanne bei mittlerer Hitze erhitzen und die Syrniki je Seite 3–4 Min. goldbraun braten.',
      'Mit Schmand und Himbeeren servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Gebraten wird in der Pfanne.', steps: [
      ['Quark, Eier, Erythrit und Vanille in den Mixtopf geben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Mehl zugeben und unterrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['Teig 10 Min. ruhen lassen, dann kleine Taler formen.', '', '', '', ''],
      ['In der Pfanne goldbraun braten.', '', '', '', ''],
      ['Mit Schmand und Himbeeren servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Teig ohne Erythrit, Syrniki als kleine Stäbchen formen und gut durchbraten, mit zerdrückten Himbeeren. Kleinkind (1–3 J.): ohne Erythrit, mit Apfelmus oder Himbeeren.',
    baby: 2,
  },
  {
    id: 'suesskartoffel-hash-pute-spiegelei',
    n: 'Süßkartoffel-Hash mit Pute & Spiegelei',
    img: { wiki: 'Hash (food)', q: 'sweet potato breakfast hash fried egg' },
    cu: 'amerikanisch', m: ['fruehstueck', 'abend'], t: 30, d: 1, st: ['comfort', 'mealprep'],
    ck: 'Süßkartoffel-Hash',
    i: [['suesskartoffel', 150], ['paprika', 70], ['zwiebel', 30], ['putenbrust', 50], ['olivenoel', 7], ['ei', 120], ['gewuerze', 2], ['kraeuter', 3], ['salz', 0.6]],
    s: [
      'Süßkartoffel in 1 cm große Würfel schneiden, Paprika und Zwiebel würfeln, Putenbrust klein schneiden.',
      'Öl in einer großen Pfanne erhitzen, Süßkartoffel 10–12 Min. bei mittlerer Hitze braten, bis sie weich und gebräunt ist.',
      'Pute, Paprika und Zwiebel zugeben und 5 Min. mitbraten, mit Paprikapulver und Kreuzkümmel würzen.',
      'Für Baby/Kleinkind eine Portion ungesalzen entnehmen, Rest salzen.',
      'Mulden formen, Eier hineinschlagen und zugedeckt 5–6 Min. stocken lassen. Mit Petersilie bestreuen.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Die Süßkartoffeln werden im Varoma vorgegart und in der Pfanne knusprig gebraten.', steps: [
      ['500 g Wasser in den Mixtopf geben, Süßkartoffelwürfel in den Varoma-Behälter geben, aufsetzen und vorgaren.', '15 Min.', 'Varoma', 'Stufe 1', ''],
      ['Varoma abnehmen, Mixtopf leeren. Zwiebel und Paprika in Stücken zerkleinern.', '3 Sek.', '', 'Stufe 4', ''],
      ['Öl und Putenwürfel zugeben und garen.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
      ['Für Baby/Kleinkind eine Portion ungesalzen entnehmen.', '', '', '', ''],
      ['Süßkartoffeln in der Pfanne anbraten, Pute und Gemüse zugeben, würzen.', '', '', '', ''],
      ['Eier in Mulden stocken lassen und mit Petersilie servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): weiche Süßkartoffelstücke und fein gezupfte Pute ungesalzen als Fingerfood, Ei vollständig durchgebraten. Kleinkind (1–3 J.): ungesalzen, Würfel klein, Eigelb fest.',
    baby: 2,
  },
  {
    id: 'tofu-scramble-burrito',
    n: 'Tofu-Scramble-Burrito mit schwarzen Bohnen',
    img: { wiki: 'Breakfast burrito', q: 'tofu scramble breakfast burrito vegan' },
    cu: 'mexikanisch', m: ['fruehstueck', 'mittag'], t: 20, d: 1, st: ['mealprep'],
    ck: 'Veganer Frühstücksburrito',
    i: [['tortilla', 60], ['tofu', 120], ['schwarze_bohnen', 40], ['paprika', 50], ['spinat', 30], ['gewuerze', 2], ['rapsoel', 4], ['salsa', 40], ['salz', 0.4]],
    s: [
      'Tofu gut ausdrücken und mit einer Gabel grob zerkrümeln.',
      'Öl in einer Pfanne erhitzen, Paprikawürfel 3 Min. anbraten, Tofu zugeben und 5 Min. braten.',
      'Kurkuma, Kreuzkümmel und Paprikapulver zugeben, Bohnen und Spinat unterheben und 2 Min. erhitzen.',
      'Für Baby/Kleinkind eine Portion ungesalzen entnehmen, Rest salzen.',
      'Tortillas erwärmen, mit Tofu-Scramble und Salsa füllen, fest einrollen. Eingewickelt lassen sich die Burritos einfrieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['Paprika in Stücken in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 4', ''],
      ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
      ['Tofu zerbröckelt und Gewürze zugeben und garen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Bohnen und Spinat zugeben und erhitzen.', '2 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Für Baby/Kleinkind eine Portion ungesalzen entnehmen, Rest salzen.', '', '', '', ''],
      ['Tortillas in der Pfanne erwärmen, füllen und einrollen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Tofu-Scramble ungesalzen mit zerdrückten Bohnen, als Löffelkost oder auf weichem Tortillastreifen. Kleinkind (1–3 J.): kleiner Burrito in Scheiben, milde Salsa, Bohnen zerdrückt.',
    baby: 2,
  },
  {
    id: 'fruehstuecks-burrito-putenhack-ei',
    n: 'Frühstücks-Burrito mit würzigem Putenhack, Ei & Kartoffel',
    img: { wiki: 'Breakfast burrito', q: 'breakfast burrito sausage egg potato' },
    cu: 'mexikanisch', m: ['fruehstueck'], t: 25, d: 1, st: ['mealprep', 'comfort'],
    ck: 'Frühstücksburrito',
    i: [['tortilla', 60], ['putenhack', 60], ['ei', 60], ['eiklar', 40], ['kartoffel', 50], ['paprika', 40], ['cajun', 2], ['salsa', 30], ['rapsoel', 3]],
    s: [
      'Kartoffel klein würfeln und in Öl 8 Min. knusprig braten.',
      'Putenhack zugeben, krümelig braten und mit Taco-Gewürz würzen (für Baby/Kleinkind vorher eine Portion ungewürzt entnehmen).',
      'Paprikawürfel 2 Min. mitbraten.',
      'Eier und Eiklar verquirlen, zugeben und unter Rühren stocken lassen.',
      'Tortillas erwärmen, Füllung und Salsa daraufgeben, Seiten einschlagen und fest aufrollen. In der Pfanne kurz von allen Seiten anrösten.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['Paprika in Stücken in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 4', ''],
      ['Öl, Putenhack und Kartoffelwürfel zugeben und anbraten.', '8 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
      ['Für Baby/Kleinkind eine Portion ungewürzt entnehmen.', '', '', '', ''],
      ['Taco-Gewürz zugeben und weitergaren.', '2 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Verquirlte Eier und Eiklar zugeben und stocken lassen.', '4 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Tortillas füllen, aufrollen und in der Pfanne anrösten.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungewürztes Hack-Kartoffel-Ei-Gemisch, Ei durchgegart, als Löffelkost oder in weiche Tortillastreifen gerollt. Kleinkind (1–3 J.): ohne Taco-Gewürz, Burrito in Scheiben.',
    baby: 1,
  },
  {
    id: 'tofu-scramble-gemuese',
    n: 'Tofu-Scramble mit Gemüse auf Vollkornbrot',
    img: { q: 'tofu scramble vegetables turmeric toast' },
    cu: 'international', m: ['fruehstueck', 'abend'], t: 15, d: 1,
    ck: 'Tofu Rührei',
    i: [['tofu', 180], ['paprika', 60], ['spinat', 50], ['kirschtomaten', 60], ['fruehlingszwiebel', 15], ['rapsoel', 6], ['gewuerze', 2], ['salz', 0.6], ['vollkornbrot', 50]],
    s: [
      'Tofu abtropfen lassen, gut ausdrücken und mit den Fingern grob zerkrümeln.',
      'Öl in einer Pfanne erhitzen, Paprikawürfel und Frühlingszwiebel 3 Min. anbraten.',
      'Tofu zugeben und 5 Min. braten, mit Kurkuma, Paprikapulver und Pfeffer würzen.',
      'Spinat und halbierte Kirschtomaten unterheben und 2 Min. mitgaren.',
      'Für Baby/Kleinkind eine Portion ungesalzen entnehmen, Rest salzen. Mit Vollkornbrot servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['Frühlingszwiebel und Paprika in Stücken in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 4', ''],
      ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
      ['Zerkrümelten Tofu und Gewürze zugeben und garen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Spinat und Tomaten zugeben und mitgaren.', '2 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Für Baby/Kleinkind eine Portion ungesalzen entnehmen, Rest salzen.', '', '', '', ''],
      ['Mit Vollkornbrot servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzener Tofu-Scramble mit weichem Gemüse als Fingerfood oder zerdrückt, Brot ohne Rinde in Streifen. Kleinkind (1–3 J.): Kirschtomaten geviertelt, Brot mit Frischkäse.',
    baby: 2,
  },
  {
    id: 'cilbir-tuerkische-eier-joghurt',
    n: 'Çılbır (türkische Eier auf Knoblauch-Joghurt)',
    img: { wiki: 'Çılbır', q: 'cilbir turkish poached eggs yogurt chili butter' },
    cu: 'orientalisch', m: ['fruehstueck'], t: 15, d: 2,
    ck: 'Türkische Eier',
    i: [['ei', 120], ['griech_joghurt', 150], ['knoblauch', 3], ['butter', 6], ['gewuerze', 1], ['kraeuter', 3], ['zitronensaft', 5], ['salz', 0.4], ['sauerteigbrot', 50]],
    s: [
      'Joghurt mit fein geriebenem Knoblauch, Zitronensaft und Salz verrühren und Zimmertemperatur annehmen lassen. Für Baby/Kleinkind vorher Joghurt pur abnehmen.',
      'Wasser mit einem Schuss Essig zum Sieden bringen und die Eier nacheinander 3–4 Min. pochieren (für Baby/Kleinkind 6 Min., bis das Eigelb fest ist).',
      'Butter schmelzen und mit Pul Biber (Paprikaflocken) kurz aufschäumen lassen.',
      'Joghurt in tiefe Teller streichen, Eier daraufsetzen und mit der Chilibutter beträufeln.',
      'Mit Dill bestreuen und mit geröstetem Brot zum Tunken servieren.',
    ],
    tm: { fit: 0, note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix bereitet Joghurt und Chilibutter zu, pochiert wird im Topf.', steps: [
      ['Knoblauch und Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Für Baby/Kleinkind Joghurt pur beiseitestellen. Restlichen Joghurt, Zitronensaft und Salz zugeben und verrühren, umfüllen.', '10 Sek.', '', 'Stufe 3', ''],
      ['Butter und Pul Biber in den Mixtopf geben und schmelzen.', '2 Min.', '80°C', 'Stufe 1', ''],
      ['Eier im siedenden Wasser im Topf pochieren, auf dem Joghurt anrichten und mit Chilibutter beträufeln.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Joghurt pur ohne Knoblauch und Salz, Ei mit festem Eigelb zerdrückt untergerührt, Brotstreifen zum Dippen, ohne Chilibutter. Kleinkind (1–3 J.): Eigelb fest, nur wenig Knoblauch, Butter ohne Chili.',
    baby: 2,
  },
  {
    id: 'besan-chilla-huettenkaese',
    n: 'Besan Chilla (Kichererbsen-Pfannkuchen) mit Hüttenkäse',
    img: { q: 'besan chilla chickpea flour pancake indian' },
    cu: 'indisch', m: ['fruehstueck', 'abend'], t: 20, d: 1,
    ck: 'Kichererbsenpfannkuchen',
    i: [['kichererbsenmehl', 50], ['rote_zwiebel', 20], ['tomate', 40], ['kraeuter', 4], ['currypulver', 1], ['ingwer', 3], ['rapsoel', 5], ['huettenkaese', 100], ['spinat', 30], ['salz', 0.5]],
    s: [
      'Kichererbsenmehl mit ca. 90 ml Wasser, Kurkuma, Kreuzkümmel und geriebenem Ingwer zu einem glatten, dünnflüssigen Teig verrühren und 5 Min. ruhen lassen.',
      'Zwiebel, Tomate, Spinat und Koriander fein hacken und unterrühren. Für Baby/Kleinkind etwas Teig ungesalzen abnehmen, Rest salzen.',
      'Wenig Öl in einer Pfanne erhitzen, eine Kelle Teig dünn verstreichen und bei mittlerer Hitze 2–3 Min. backen.',
      'Wenden, 1–2 Min. fertig backen.',
      'Mit Hüttenkäse füllen oder belegen und zusammenklappen.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Ausgebacken wird in der Pfanne.', steps: [
      ['Zwiebel, Ingwer und Koriander in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
      ['Kichererbsenmehl, 360 g Wasser und Gewürze zugeben und zu einem glatten Teig verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Tomatenwürfel und gehackten Spinat zugeben und unterrühren.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Für Baby/Kleinkind etwas Teig ungesalzen entnehmen, Rest salzen.', '', '', '', ''],
      ['Teig in der Pfanne dünn ausbacken und mit Hüttenkäse füllen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): kleine, ungesalzene Chillas gut durchbacken und in Streifen schneiden, Hüttenkäse als Dip. Kleinkind (1–3 J.): mild ohne Salz, gefüllt und in Ecken geschnitten.',
    baby: 2,
  },
  {
    id: 'chilaquiles-ei',
    n: 'Chilaquiles mit Ei & schwarzen Bohnen',
    img: { wiki: 'Chilaquiles', q: 'chilaquiles fried egg salsa tortilla chips' },
    cu: 'mexikanisch', m: ['fruehstueck', 'mittag'], t: 25, d: 1, st: ['comfort'],
    ck: 'Chilaquiles',
    i: [['tortilla_mais', 60], ['salsa', 100], ['ei', 120], ['schwarze_bohnen', 40], ['feta', 15], ['griech_joghurt', 30], ['kraeuter', 3], ['rapsoel', 3], ['rote_zwiebel', 15]],
    s: [
      'Ofen auf 200 °C vorheizen. Maistortillas in Ecken schneiden, mit dem halben Öl mischen und 8–10 Min. knusprig backen.',
      'Salsa mit den abgespülten Bohnen in einer Pfanne 4 Min. köcheln. Für Baby/Kleinkind etwas Bohnen ohne Salsa abnehmen.',
      'Tortilla-Chips in die Salsa geben und 1 Min. durchschwenken, bis sie leicht weich werden.',
      'Im restlichen Öl Spiegeleier braten.',
      'Chilaquiles mit Ei, zerbröseltem Feta (statt Queso fresco), Joghurt, roten Zwiebelringen und Koriander servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Chips im Ofen, Eier in der Pfanne.', steps: [
      ['Tortilla-Ecken im Ofen bei 200 °C 8–10 Min. knusprig backen.', '', '', '', ''],
      ['Für Baby/Kleinkind etwas Bohnen pur entnehmen.', '', '', '', ''],
      ['Salsa und Bohnen in den Mixtopf geben und erhitzen.', '5 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ['Salsa in eine Pfanne geben, Chips darin kurz schwenken.', '', '', '', ''],
      ['Spiegeleier braten und mit Feta, Joghurt, Zwiebel und Koriander anrichten.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): zerdrückte Bohnen mit Joghurt und durchgebratenem Ei, weiche (nicht knusprige) Tortillastreifen. Kleinkind (1–3 J.): milde Salsa, Chips leicht eingeweicht, Ei durchgebraten.',
    baby: 2,
  },
  {
    id: 'fruehstueckssandwich-ei-schinken-kaese',
    n: 'Frühstückssandwich mit Ei, Schinken & Käse',
    img: { wiki: 'Breakfast sandwich', q: 'breakfast sandwich egg ham cheese muffin' },
    cu: 'amerikanisch', m: ['fruehstueck'], t: 12, d: 1, st: ['kinderliebling'],
    ck: 'Frühstückssandwich',
    i: [['burgerbroetchen', 70], ['ei', 60], ['schinken_gekocht', 40], ['gouda_light', 15], ['rapsoel', 2], ['salat', 15], ['tomate', 40]],
    s: [
      'Brötchen halbieren und im Toaster oder in der Pfanne rösten.',
      'Ein Ei in einem gefetteten Dessertring (oder Glasdeckel) in der Pfanne bei mittlerer Hitze 4 Min. braten, Eigelb dabei anstechen, damit es rund und flach wird.',
      'Schinken kurz in der Pfanne erwärmen, Käse auf das Ei legen und zugedeckt 1 Min. schmelzen lassen.',
      'Brötchen mit Salat, Tomate, Schinken und Käse-Ei belegen und zuklappen.',
    ],
    tm: { fit: 0, note: 'Für ca. 4 Portionen ausgelegt. Am besten in der Pfanne zubereiten – der Thermomix kann die Eier im Varoma garen.', steps: [
      ['500 g Wasser in den Mixtopf geben. Eier einzeln in gefettete Silikon-Muffinförmchen schlagen, in den Varoma stellen, aufsetzen und garen.', '14 Min.', 'Varoma', 'Stufe 1', ''],
      ['Brötchen rösten, Schinken in der Pfanne erwärmen.', '', '', '', ''],
      ['Käse auf die heißen Eier legen und schmelzen lassen.', '', '', '', ''],
      ['Brötchen mit Salat, Tomate, Schinken und Käse-Ei belegen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Brötchen ohne Schinken, nur mit durchgegartem Ei und Tomate (gehäutet) in Streifen. Kleinkind (1–3 J.): halbes Sandwich in Vierteln, Schinken nur wenig.',
    baby: 1,
  },
  {
    id: 'suesskartoffel-toast-huettenkaese-ei',
    n: 'Süßkartoffel-Toast mit Hüttenkäse, Avocado & Ei',
    img: { q: 'sweet potato toast cottage cheese egg avocado' },
    cu: 'amerikanisch', m: ['fruehstueck'], t: 25, d: 1,
    ck: 'Süßkartoffel-Toast',
    i: [['suesskartoffel', 150], ['huettenkaese', 100], ['ei', 120], ['avocado', 25], ['radieschen', 30], ['kraeuter', 3], ['gewuerze', 1], ['olivenoel', 3], ['salz', 0.4]],
    s: [
      'Süßkartoffel längs in 1 cm dicke Scheiben schneiden, dünn mit Öl bestreichen.',
      'Im Toaster (2–3 Durchgänge auf höchster Stufe) oder im Ofen bei 200 °C 15–18 Min. weich und leicht gebräunt rösten.',
      'Eier 7 Min. wachsweich kochen (für Baby/Kleinkind hart), schälen und in Scheiben schneiden.',
      'Süßkartoffelscheiben mit Hüttenkäse bestreichen, mit Avocado, Ei und Radieschenscheiben belegen.',
      'Mit Salz, Pfeffer, Chiliflocken und Schnittlauch würzen.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Die Scheiben werden im Varoma vorgegart und im Ofen geröstet.', steps: [
      ['500 g Wasser in den Mixtopf geben. Süßkartoffelscheiben in den Varoma-Behälter, Eier auf den Einlegeboden legen, aufsetzen und garen.', '14 Min.', 'Varoma', 'Stufe 1', ''],
      ['Eier abschrecken und schälen.', '', '', '', ''],
      ['Süßkartoffelscheiben mit Öl bestreichen und im Ofen bei 220 °C 6–8 Min. rösten.', '', '', '', ''],
      ['Mit Hüttenkäse, Avocado, Ei und Radieschen belegen und würzen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): weiche Süßkartoffelscheiben in Streifen mit zerdrückter Avocado und hart gekochtem Ei, ungesalzen. Kleinkind (1–3 J.): mit Hüttenkäse, ohne Chili, Radieschen fein gerieben.',
    baby: 2,
  },
  {
    id: 'smorrebrod-ei-radieschen',
    n: 'Smørrebrød mit Ei, körnigem Frischkäse & Radieschen',
    img: { wiki: 'Smørrebrød', q: 'smorrebrod egg radish rye bread' },
    cu: 'international', m: ['fruehstueck', 'abend'], t: 15, d: 1,
    ck: 'Smørrebrød',
    i: [['vollkornbrot', 70], ['koerniger_frischkaese', 100], ['ei', 90], ['radieschen', 40], ['gurke', 30], ['kraeuter', 4], ['senf', 3], ['salz', 0.3]],
    s: [
      'Eier 9 Min. hart kochen, abschrecken, schälen und in Scheiben schneiden.',
      'Körnigen Frischkäse mit Senf, gehacktem Dill und Pfeffer verrühren.',
      'Dunkles Vollkornbrot (dänisches Rugbrød) dick mit der Creme bestreichen.',
      'Mit Gurke, Ei und Radieschen in Scheiben dachziegelartig belegen, mit Schnittlauch und etwas Salz bestreuen.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['500 g Wasser in den Mixtopf geben, Eier in den Varoma legen, aufsetzen und hart garen.', '16 Min.', 'Varoma', 'Stufe 1', ''],
      ['Eier abschrecken. Mixtopf leeren, Dill hineingeben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Körnigen Frischkäse und Senf zugeben und verrühren.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Brot bestreichen und mit Gurke, Ei und Radieschen belegen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): weiches Brot ohne Rinde mit Frischkäse (ohne Senf), Ei in Spalten, Gurke als Stick. Kleinkind (1–3 J.): ohne Senf, Radieschen fein gerieben, Brot in Streifen.',
    baby: 2,
  },
  {
    id: 'strammer-max-leicht',
    n: 'Strammer Max (leicht) mit Schinken & Spiegelei',
    img: { wiki: 'Strammer Max', q: 'strammer max ham fried egg bread' },
    cu: 'deutsch', m: ['fruehstueck', 'abend'], t: 12, d: 1, st: ['comfort'],
    ck: 'Strammer Max',
    i: [['vollkornbrot', 70], ['schinken_gekocht', 50], ['ei', 120], ['rapsoel', 4], ['tomate', 60], ['gurke', 40], ['kraeuter', 2]],
    s: [
      'Brotscheiben im Toaster oder in der Pfanne ohne Fett leicht rösten.',
      'Öl in einer Pfanne erhitzen und die Eier bei mittlerer Hitze 4 Min. zu Spiegeleiern braten (fürs Kind durchbraten).',
      'Brot mit Kochschinken belegen, je ein Spiegelei daraufsetzen.',
      'Mit Pfeffer und Schnittlauch bestreuen, mit Tomate und Gurke servieren.',
    ],
    tm: { fit: 0, note: 'Für ca. 4 Portionen ausgelegt. Klassisch in der Pfanne – der Thermomix gart die Eier nur im Varoma.', steps: [
      ['500 g Wasser in den Mixtopf geben. Eier in gefettete Silikonförmchen schlagen, in den Varoma stellen, aufsetzen und garen.', '14 Min.', 'Varoma', 'Stufe 1', ''],
      ['Brot rösten und mit Schinken belegen.', '', '', '', ''],
      ['Eier daraufsetzen, mit Schnittlauch bestreuen und mit Tomate und Gurke servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Brotstreifen mit durchgebratenem Ei, ohne Schinken (gepökelt), Gurke als Stick. Kleinkind (1–3 J.): wenig Schinken, Brot in Würfeln, Eigelb fest.',
    baby: 1,
  },
  {
    id: 'quarkkeulchen-apfelmus',
    n: 'Sächsische Quarkkeulchen mit Apfelmus',
    img: { wiki: 'Quarkkeulchen', q: 'quarkkeulchen quark potato pancakes apple sauce' },
    cu: 'deutsch', m: ['fruehstueck', 'abend'], t: 40, d: 2, st: ['comfort', 'kinderliebling'],
    ck: 'Quarkkeulchen',
    i: [['kartoffel', 150], ['magerquark', 125], ['ei', 30], ['mehl', 20], ['erythrit', 5], ['zimt', 1], ['rosinen', 10], ['rapsoel', 6], ['apfelmus', 80]],
    s: [
      'Kartoffeln (am besten vom Vortag) als Pellkartoffeln 20 Min. kochen, pellen und fein zerdrücken.',
      'Quark, Ei, Mehl (glutenfrei: glutenfreie Mehlmischung), Erythrit, Zimt und Rosinen unterkneten.',
      'Mit feuchten Händen kleine, flache Keulchen formen.',
      'Öl in einer Pfanne erhitzen und die Keulchen je Seite 3–4 Min. goldbraun braten.',
      'Mit Apfelmus und etwas Zimt servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Gebraten wird in der Pfanne.', steps: [
      ['500 g Wasser in den Mixtopf geben, geschälte Kartoffelstücke in den Varoma geben, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
      ['Mixtopf leeren, Kartoffeln hineingeben und zerkleinern.', '10 Sek.', '', 'Stufe 4', ''],
      ['Quark, Eier, Mehl, Erythrit, Zimt und Rosinen zugeben und vermengen.', '30 Sek.', '', '', 'Teigkneten'],
      ['Keulchen formen und in der Pfanne goldbraun braten.', '', '', '', ''],
      ['Mit Apfelmus servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Keulchen ohne Erythrit und Rosinen, gut durchgebraten als Fingerfood mit Apfelmus zum Dippen. Kleinkind (1–3 J.): ohne Erythrit, Rosinen gehackt.',
    baby: 2,
  },
  {
    id: 'buchweizen-kascha-quark',
    n: 'Buchweizen-Kascha mit Quark & Zimtapfel',
    img: { wiki: 'Kasha', q: 'buckwheat kasha porridge milk' },
    cu: 'international', m: ['fruehstueck'], t: 20, d: 1, st: ['comfort', 'mealprep'],
    ck: 'Buchweizenbrei',
    i: [['buchweizen', 55], ['milch', 150], ['magerquark', 120], ['apfel', 80], ['zimt', 1], ['walnuesse', 6]],
    s: [
      'Buchweizen in einem Sieb abspülen und in einem Topf ohne Fett 2 Min. rösten.',
      'Mit Milch und 80 ml Wasser aufkochen und zugedeckt bei schwacher Hitze 12–15 Min. weich garen.',
      'Apfel würfeln und mit Zimt und 1 EL Wasser 3 Min. dünsten.',
      'Kascha etwas abkühlen lassen, Quark unterrühren und mit Zimtapfel und gehackten Walnüssen servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen ausgelegt.', steps: [
      ['Walnüsse in den Mixtopf geben, hacken und umfüllen.', '3 Sek.', '', 'Stufe 5', ''],
      ['Buchweizen in den Mixtopf geben und rösten.', '3 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
      ['Milch und 320 g Wasser zugeben und garen, Garkörbchen als Spritzschutz aufsetzen. Apfelwürfel mit Zimt im Varoma aufsetzen.', '18 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
      ['Etwas abkühlen lassen, Quark zugeben und unterrühren.', '20 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Mit Zimtapfel und Walnüssen servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Buchweizen sehr weich kochen und pürieren, Apfel zerdrückt, nur 1–2 EL Quark, ohne Walnüsse. Kleinkind (1–3 J.): Walnüsse fein gemahlen.',
    baby: 2,
  },
  {
    id: 'protein-crepes-quarkfuellung',
    n: 'Protein-Crêpes mit Vanillequark & Erdbeeren',
    img: { wiki: 'Crêpe', q: 'crepes quark filling strawberries' },
    cu: 'international', m: ['fruehstueck'], t: 25, d: 2, st: ['kinderliebling'],
    ck: 'Crêpes',
    i: [['mehl', 40], ['eiklar', 60], ['ei', 30], ['milch', 100], ['rapsoel', 3], ['magerquark', 120], ['erythrit', 6], ['vanille', 1], ['erdbeeren', 80]],
    s: [
      'Mehl (glutenfrei: glutenfreie Mehlmischung), Ei, Eiklar und Milch glatt verquirlen und 10 Min. ruhen lassen.',
      'Quark mit Vanille und Erythrit cremig rühren, Erdbeeren in Scheiben schneiden.',
      'Eine beschichtete Pfanne dünn mit Öl auspinseln, eine kleine Kelle Teig hineingeben und durch Schwenken dünn verteilen.',
      'Crêpe bei mittlerer Hitze 1 Min. backen, wenden und 30 Sek. fertig backen. Mit dem restlichen Teig ebenso verfahren.',
      'Crêpes mit Vanillequark und Erdbeeren füllen und zusammenklappen.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Ausgebacken wird in der Pfanne.', steps: [
      ['Mehl, Eier, Eiklar und Milch in den Mixtopf geben und zu einem glatten Teig verrühren.', '20 Sek.', '', 'Stufe 5', ''],
      ['Teig umfüllen und 10 Min. ruhen lassen.', '', '', '', ''],
      ['Quark, Vanille und Erythrit in den Mixtopf geben und cremig rühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Crêpes in der Pfanne dünn ausbacken.', '', '', '', ''],
      ['Mit Vanillequark und Erdbeeren füllen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Crêpe in Streifen mit etwas Quark (ohne Erythrit) und zerdrückten Erdbeeren. Kleinkind (1–3 J.): ohne Erythrit, mit Banane gesüßter Quark, als Röllchen.',
    baby: 2,
  },
  {
    id: 'baked-oats-heidelbeeren',
    n: 'Baked Oats mit Heidelbeeren',
    img: { q: 'baked oats blueberries ramekin' },
    cu: 'amerikanisch', m: ['fruehstueck'], t: 30, d: 1, st: ['mealprep', 'kinderliebling'],
    ck: 'Baked Oats',
    i: [['haferflocken', 50], ['ei', 60], ['skyr', 100], ['milch', 50], ['banane', 40], ['backpulver', 3], ['vanille', 1], ['heidelbeeren', 70]],
    s: [
      'Ofen auf 180 °C Ober-/Unterhitze vorheizen.',
      'Haferflocken, Ei, Skyr, Milch, Banane, Backpulver und Vanille fein pürieren.',
      'Teig in eine kleine ofenfeste Form (ca. 12 cm) füllen und die Heidelbeeren hineindrücken.',
      'Ca. 22–25 Min. backen, bis die Oberfläche goldgelb und die Mitte gerade fest ist.',
      'Warm oder kalt servieren. Hält 2 Tage im Kühlschrank.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Förmchen. Gebacken wird im Ofen.', steps: [
      ['Haferflocken in den Mixtopf geben und mahlen.', '10 Sek.', '', 'Stufe 10', ''],
      ['Eier, Skyr, Milch, Banane, Backpulver und Vanille zugeben und zu einem glatten Teig mixen.', '20 Sek.', '', 'Stufe 5', ''],
      ['Teig in Förmchen füllen und Heidelbeeren hineindrücken.', '', '', '', ''],
      ['Im Ofen bei 180 °C 22–25 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): in Streifen geschnitten als weiches Fingerfood, Heidelbeeren sind eingebacken und weich. Kleinkind (1–3 J.): als Portion im Förmchen, mit etwas Joghurt.',
    baby: 2,
  },
  {
    id: 'tortilla-espanola',
    n: 'Tortilla Española (spanisches Kartoffel-Omelett)',
    img: { wiki: 'Spanish omelette', q: 'tortilla espanola spanish potato omelette' },
    cu: 'mediterran', m: ['fruehstueck', 'abend'], t: 40, d: 2, st: ['mealprep', 'comfort'],
    ck: 'Tortilla Española',
    i: [['kartoffel', 180], ['zwiebel', 40], ['olivenoel', 10], ['ei', 150], ['salz', 0.8], ['kraeuter', 2], ['salat', 30]],
    s: [
      'Kartoffeln schälen, vierteln und in dünne Scheiben schneiden, Zwiebel in feine Streifen.',
      'Öl in einer beschichteten Pfanne (ca. 20 cm) erhitzen, Kartoffeln und Zwiebel bei mittlerer bis schwacher Hitze zugedeckt 15–18 Min. weich garen, gelegentlich wenden.',
      'Eier verquirlen, Kartoffeln untermischen und 5 Min. ziehen lassen. Für Baby/Kleinkind einen Teil ungesalzen abnehmen, Rest salzen.',
      'Masse zurück in die Pfanne geben und bei schwacher Hitze 6–8 Min. stocken lassen.',
      'Mit Hilfe eines Tellers wenden und weitere 3–4 Min. fertig garen (fürs Kind vollständig durch). Mit Salat servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen ausgelegt. Die Kartoffeln garen im Varoma, gestockt wird in der Pfanne.', steps: [
      ['500 g Wasser in den Mixtopf geben, Kartoffel- und Zwiebelscheiben in den Varoma geben, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 1', ''],
      ['Mixtopf leeren, Eier hineingeben und verquirlen.', '10 Sek.', '', 'Stufe 4', ''],
      ['Kartoffeln in eine Schüssel geben, Eier untermischen. Für Baby/Kleinkind einen Teil ungesalzen entnehmen, Rest salzen.', '', '', '', ''],
      ['In der Pfanne im Olivenöl stocken lassen, wenden und fertig garen.', '', '', '', ''],
      ['In Stücke schneiden und mit Salat servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzene, vollständig durchgegarte Tortilla in Stäbchen – ideales BLW-Fingerfood. Kleinkind (1–3 J.): in Würfeln, ungesalzen oder nur leicht gesalzen.',
    baby: 2,
  },
]);
