// Geflügel aus aller Welt: Hähnchen & Pute – Klassiker, Ofengerichte, Aufläufe, Salate & Suppen
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  {
    id: 'zuercher-haehnchen-geschnetzeltes-roesti',
    n: 'Hähnchen-Geschnetzeltes Zürcher Art mit Rösti',
    img: { wiki: 'Zürcher Geschnetzeltes', q: 'zurich style chicken geschnetzeltes mushroom cream rosti' },
    ck: 'Geschnetzeltes Zürcher Art',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort'],
    i: [['haehnchenbrust', 170], ['champignons', 120], ['zwiebel', 40], ['sahne', 50], ['huehnerbruehe', 100], ['speisestaerke', 5], ['kartoffel', 250], ['rapsoel', 10], ['kraeuter', 4], ['gewuerze', 1], ['salz', 1]],
    s: [
      'Kartoffeln schälen, grob raspeln und kräftig ausdrücken. Hähnchen in feine Streifen, Champignons in Scheiben schneiden, Zwiebel fein würfeln.',
      'Die Hälfte des Öls in einer beschichteten Pfanne erhitzen, Kartoffelraspel als flache Rösti hineindrücken und je Seite 8–10 Min. bei mittlerer Hitze goldbraun braten.',
      'Restliches Öl in einer zweiten Pfanne stark erhitzen, Hähnchenstreifen 3–4 Min. scharf anbraten und herausnehmen.',
      'Zwiebel und Champignons 5 Min. braten, mit Brühe ablöschen, Sahne zugeben und 3 Min. köcheln. Stärke in wenig Wasser anrühren und die Sauce damit binden.',
      'Hähnchen zurück in die Sauce geben und 2 Min. ziehen lassen. Baby-/Kleinkind-Portion jetzt ungesalzen entnehmen.',
      'Rest mit Salz, Pfeffer und Paprika abschmecken, mit Petersilie bestreuen und mit Rösti servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Rösti werden in der Pfanne gebraten.',
      steps: [
        ['Zwiebel in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hälfte des Öls zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hähnchenstreifen und Champignonscheiben zugeben und anbraten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe und Sahne zugeben und garen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Angerührte Stärke zugeben und binden.', '2 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest abschmecken.', '', '', '', ''],
        ['Rösti parallel in der Pfanne mit dem restlichen Öl je Seite 8–10 Min. goldbraun braten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes Hähnchen sehr fein zupfen, mit Sauce und weich gekochter Kartoffel zu Brei zerdrücken; für BLW weiche Kartoffelstäbchen statt knuspriger Rösti. Kleinkind (1–3 J.): Hähnchen klein schneiden, Pilze fein hacken, Rösti in Streifen.',
    baby: 2,
  },
  {
    id: 'putenschnitzel-gurken-kartoffelsalat',
    n: 'Putenschnitzel mit Gurken-Kartoffelsalat',
    img: { wiki: 'Schnitzel', q: 'breaded turkey schnitzel potato salad cucumber' },
    ck: 'Putenschnitzel paniert',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['kinderliebling'],
    i: [['putenbrust', 160], ['ei', 25], ['paniermehl', 25], ['rapsoel', 10], ['kartoffel', 220], ['gurke', 100], ['joghurt', 60], ['senf', 5], ['essig', 5], ['zwiebel', 20], ['kraeuter', 4], ['zitrone', 20], ['salz', 1.5]],
    s: [
      'Kartoffeln mit Schale 20 Min. kochen, pellen, etwas abkühlen lassen und in Scheiben schneiden.',
      'Gurke fein hobeln, Zwiebel fein würfeln. Joghurt mit Senf, Essig, Dill und etwas Salz verrühren und mit Kartoffeln und Gurke mischen, 15 Min. ziehen lassen.',
      'Putenbrust in 2 dünne Schnitzel schneiden und zwischen Folie flach klopfen. Durch verquirltes Ei ziehen und in Paniermehl wenden.',
      'Öl in einer Pfanne erhitzen und die Schnitzel je Seite 3–4 Min. goldbraun und durchgegart ausbraten.',
      'Baby-/Kleinkind-Portion vom Schnitzel und vom Salat vor dem Salzen abnehmen.',
      'Schnitzel leicht salzen und mit Zitronenspalten und Kartoffelsalat servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Schnitzel werden in der Pfanne ausgebacken.',
      steps: [
        ['500 g Wasser in den Mixtopf füllen, Kartoffeln im Varoma-Behälter dampfgaren.', '30 Min.', 'Varoma', 'Stufe 1', ''],
        ['Kartoffeln pellen und in Scheiben schneiden. Mixtopf leeren.', '', '', '', ''],
        ['Zwiebel und Dill in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Joghurt, Senf und Essig zugeben und zum Dressing verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Dressing mit Kartoffeln und gehobelter Gurke in einer Schüssel mischen.', '', '', '', ''],
        ['Schnitzel panieren und in der Pfanne je Seite 3–4 Min. ausbraten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes Schnitzel ohne harte Panadeecken in fingerdicke Streifen schneiden, Kartoffeln weich als Fingerfood, Gurke geschält in Sticks. Kleinkind (1–3 J.): Schnitzel in kleine Stücke, Salat mit wenig Senf.',
    baby: 2,
  },
  {
    id: 'haehnchen-piccata-tomatenspaghetti',
    n: 'Hähnchen-Piccata milanese mit Tomatenspaghetti',
    img: { wiki: 'Piccata', q: 'chicken piccata milanese egg parmesan crust spaghetti tomato' },
    ck: 'Piccata Milanese',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    st: ['kinderliebling'],
    i: [['haehnchenbrust', 160], ['ei', 50], ['parmesan', 10], ['mehl', 8], ['olivenoel', 8], ['nudeln', 55], ['passierte_tomaten', 150], ['knoblauch', 4], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Spaghetti nach Packungsangabe garen. Passierte Tomaten mit Knoblauch 10 Min. leise köcheln lassen.',
      'Hähnchenbrust waagerecht in dünne Schnitzel schneiden und leicht flach klopfen. Eier mit Parmesan verquirlen.',
      'Schnitzel dünn in Mehl wenden, durch die Ei-Parmesan-Masse ziehen.',
      'Öl in einer Pfanne erhitzen und die Piccata bei mittlerer Hitze je Seite 3 Min. goldgelb und gar braten.',
      'Baby-/Kleinkind-Portion von Sauce und Fleisch ungesalzen abnehmen.',
      'Sauce mit Salz und Basilikum abschmecken, mit Spaghetti mischen und die Piccata darauf servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Piccata wird in der Pfanne gebraten.',
      steps: [
        ['Knoblauch zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Passierte Tomaten zugeben und köcheln, Messbecher durch Garkörbchen ersetzen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Sauce umfüllen, Mixtopf spülen. 1200 g Wasser aufkochen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Spaghetti zugeben und garen, abgießen.', '9 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Eier mit Parmesan verquirlen, Schnitzel mehlieren, durchziehen und in der Pfanne je Seite 3 Min. braten.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion ungesalzen abnehmen, Rest mit Salz und Basilikum abschmecken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Ei muss vollständig gegart sein; Piccata in Streifen als Fingerfood, Spaghetti mit ungesalzener Tomatensauce kurz geschnitten. Kleinkind (1–3 J.): alles in Häppchen, Parmesan ist salzig, daher sparsam.',
    baby: 1,
  },
  {
    id: 'puten-saltimbocca-polenta',
    n: 'Puten-Saltimbocca mit cremiger Polenta',
    img: { wiki: 'Saltimbocca', q: 'turkey saltimbocca sage ham polenta' },
    ck: 'Saltimbocca',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 30, d: 2,
    i: [['putenbrust', 150], ['schinken_gekocht', 25], ['kraeuter', 3], ['olivenoel', 8], ['zitronensaft', 8], ['huehnerbruehe', 60], ['polenta', 55], ['milch', 100], ['parmesan', 8], ['zucchini', 150], ['salz', 0.5]],
    s: [
      'Milch mit 150 ml Wasser aufkochen, Polenta einrieseln lassen und unter Rühren 8–10 Min. bei kleiner Hitze quellen lassen, Parmesan einrühren.',
      'Putenbrust in 3 dünne Schnitzel schneiden und flach klopfen. Je ein Salbeiblatt und eine Scheibe Schinken auflegen und mit einem Zahnstocher feststecken.',
      'Öl erhitzen, Schnitzel zuerst auf der Schinkenseite 2 Min., dann auf der anderen Seite 2–3 Min. braten, herausnehmen.',
      'Zucchini in Scheiben im Bratfett 4 Min. braten. Mit Brühe und Zitronensaft ablöschen, kurz einkochen und Schnitzel darin wenden.',
      'Für Baby/Kleinkind eine Portion Pute ohne Schinken mitbraten und Polenta vor dem Parmesan abnehmen.',
      'Saltimbocca mit Zucchini und Sauce auf der Polenta anrichten, mit Pfeffer würzen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Saltimbocca wird in der Pfanne gebraten.',
      steps: [
        ['Parmesan reiben, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Milch und 600 g Wasser in den Mixtopf geben und aufkochen.', '8 Min.', '100°C', 'Stufe 1', ''],
        ['Polenta durch die Deckelöffnung einrieseln lassen und quellen lassen.', '10 Min.', '90°C', 'Stufe 2', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion Polenta abnehmen, Parmesan zum Rest geben und unterrühren.', '20 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Schnitzel mit Salbei und Schinken belegen und in der Pfanne braten, Zucchini im Bratfett garen und mit Brühe und Zitronensaft ablöschen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Pute ohne Schinken (salzig, gepökelt) braten, fein zerzupfen und mit Polenta und weicher Zucchini mischen; Polenta abgekühlt in Streifen als BLW-Fingerfood. Kleinkind (1–3 J.): Schinken nur in Spuren, Fleisch klein schneiden.',
    baby: 1,
  },
  {
    id: 'haehnchen-pizzaiola-gnocchi',
    n: 'Hähnchen alla Pizzaiola mit Gnocchi',
    img: { q: 'chicken pizzaiola tomato oregano mozzarella gnocchi' },
    ck: 'Hähnchen Pizzaiola',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['kinderliebling'],
    i: [['haehnchenbrust', 160], ['tomaten_dose', 150], ['oliven', 10], ['knoblauch', 4], ['mozzarella', 40], ['gnocchi', 150], ['olivenoel', 8], ['gewuerze', 1], ['kraeuter', 3], ['rucola', 30], ['salz', 1]],
    s: [
      'Hähnchenbrust waagerecht halbieren. Öl in einer ofenfesten Pfanne erhitzen und das Fleisch je Seite 2 Min. anbraten, herausnehmen.',
      'Knoblauch kurz andünsten, Tomaten, Oregano und Oliven zugeben und 5 Min. köcheln. Baby-/Kleinkind-Sauce ungesalzen und ohne Oliven abnehmen.',
      'Rest der Sauce salzen, Hähnchen hineinlegen und mit Mozzarellascheiben belegen.',
      'Im Ofen bei 200 °C Ober-/Unterhitze 12 Min. überbacken, bis der Käse schmilzt und das Fleisch gar ist.',
      'Gnocchi parallel in Salzwasser garen, bis sie oben schwimmen, abtropfen lassen.',
      'Mit Gnocchi, Rucola und Basilikum servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Überbacken im Ofen.',
      steps: [
        ['Knoblauch zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl zugeben und andünsten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten, Oregano und Oliven zugeben und köcheln.', '8 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ungesalzen abnehmen, Rest salzen.', '', '', '', ''],
        ['Hähnchen anbraten, mit Sauce und Mozzarella in einer Form 12 Min. bei 200 °C überbacken.', '', '', '', ''],
        ['Gnocchi in Salzwasser garen und dazu servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen fein zupfen, mit ungesalzener Tomatensauce und zerdrückten Gnocchi mischen; Gnocchi für BLW halbieren. Kleinkind (1–3 J.): Oliven weglassen oder fein hacken, Gnocchi vierteln (Verschluckungsgefahr).',
    baby: 2,
  },
  {
    id: 'pollo-al-ajillo-ofenkartoffeln',
    n: 'Pollo al ajillo (Knoblauchhähnchen) mit Ofenkartoffeln',
    img: { q: 'pollo al ajillo spanish garlic chicken potatoes' },
    ck: 'Knoblauchhähnchen',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 50, d: 1,
    i: [['haehnchenschenkel', 180], ['knoblauch', 8], ['olivenoel', 10], ['zitronensaft', 10], ['huehnerbruehe', 60], ['kartoffel', 220], ['paprika', 100], ['gewuerze', 2], ['kraeuter', 4], ['salz', 1.5]],
    s: [
      'Ofen auf 210 °C Umluft vorheizen. Kartoffeln in Spalten schneiden, mit der Hälfte des Öls, geräuchertem Paprikapulver und etwas Salz mischen und 30 Min. backen.',
      'Hähnchenschenkel in große Stücke schneiden. Knoblauch in Scheiben schneiden.',
      'Restliches Öl in einer Pfanne erhitzen, Hähnchen 6–7 Min. rundum goldbraun braten. Paprikastreifen und Knoblauch zugeben und 2 Min. mitbraten, ohne dass der Knoblauch dunkel wird.',
      'Mit Brühe und Zitronensaft ablöschen und 8 Min. offen schmoren, bis das Fleisch gar ist.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen. Rest salzen, mit Petersilie bestreuen und mit Ofenkartoffeln servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Kartoffeln im Ofen, Hähnchen im Mixtopf geschmort.',
      steps: [
        ['Kartoffelspalten würzen und im Ofen bei 210 °C 30 Min. backen.', '', '', '', ''],
        ['Knoblauch in Scheiben und Öl in den Mixtopf geben und anbraten.', '3 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Hähnchenstücke zugeben und anbraten.', '6 Min.', '150°C', 'Stufe 1', 'Anbraten'],
        ['Paprika, Brühe und Zitronensaft zugeben und schmoren.', '12 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest salzen und mit Petersilie bestreuen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Schenkelfleisch ist saftig und ideal: ungesalzen fein zupfen oder als weiche Streifen, Kartoffelspalten ohne Kruste. Kleinkind (1–3 J.): Knoblauchscheiben herausnehmen, Fleisch klein schneiden.',
    baby: 2,
  },
  {
    id: 'arroz-con-pollo',
    n: 'Arroz con pollo',
    img: { wiki: 'Arroz con pollo', q: 'arroz con pollo chicken rice peas peppers' },
    ck: 'Arroz con Pollo',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    st: ['mealprep'],
    i: [['haehnchenschenkel', 170], ['reis', 60], ['paprika', 80], ['erbsen', 50], ['zwiebel', 40], ['knoblauch', 4], ['tomaten_dose', 80], ['huehnerbruehe', 180], ['olivenoel', 8], ['gewuerze', 3], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Hähnchenschenkel in mundgerechte Stücke schneiden, mit Paprikapulver und Kreuzkümmel einreiben. Zwiebel, Knoblauch und Paprika würfeln.',
      'Öl in einem breiten Topf erhitzen, Hähnchen 5 Min. anbraten. Zwiebel, Knoblauch und Paprika 3 Min. mitbraten.',
      'Reis und Tomaten zugeben, mit Brühe auffüllen und zugedeckt 18 Min. bei kleiner Hitze garen.',
      'Erbsen unterheben und weitere 4 Min. ziehen lassen.',
      'Baby-/Kleinkind-Portion ungesalzen entnehmen. Rest salzen, mit Petersilie und Limettenspalten servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Zwiebel und Knoblauch zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hähnchenstücke, Paprika und Gewürze zugeben und anbraten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Reis, Tomaten und Brühe zugeben und garen.', '18 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Erbsen zugeben und ziehen lassen.', '4 Min.', '98°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest salzen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzen als weicher Reis-Brei mit zerdrückten Erbsen; mit Brühe ohne Salz kochen oder Wasser nehmen. Für BLW zu Reisbällchen formen. Kleinkind (1–3 J.): Erbsen leicht zerdrücken, Fleisch klein schneiden.',
    baby: 2,
  },
  {
    id: 'tavuk-sis-bulgur-pilav',
    n: 'Tavuk Şiş mit Bulgur-Pilav',
    img: { wiki: 'Shish kebab', q: 'tavuk sis chicken skewers bulgur pilaf' },
    ck: 'Hähnchenspieße Bulgur',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    i: [['haehnchenbrust', 170], ['joghurt', 40], ['tomatenmark', 10], ['gewuerze', 3], ['zitronensaft', 8], ['bulgur', 60], ['paprika', 80], ['tomate', 80], ['zwiebel', 30], ['olivenoel', 8], ['kraeuter', 4], ['salz', 1.5]],
    s: [
      'Joghurt mit Tomatenmark, Paprikapulver, Pul Biber, Kreuzkümmel, Zitronensaft und der Hälfte des Öls verrühren. Hähnchen würfeln und mindestens 20 Min. darin marinieren.',
      'Restliches Öl im Topf erhitzen, Zwiebel und Paprika 3 Min. dünsten, Bulgur kurz mitrösten, mit 130 ml Wasser auffüllen und 12 Min. quellen lassen.',
      'Hähnchen auf Spieße stecken und im Backofengrill oder in der Grillpfanne 10–12 Min. rundum grillen.',
      'Baby-/Kleinkind-Spieß nur mit Joghurt und mildem Paprika marinieren, ungesalzen garen.',
      'Bulgur salzen, Tomatenwürfel und Petersilie unterheben und mit den Spießen servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Spieße werden gegrillt.',
      steps: [
        ['Joghurt, Tomatenmark, Gewürze, Zitronensaft und Öl in den Mixtopf geben und zur Marinade verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Hähnchen in der Marinade ziehen lassen, Mixtopf spülen.', '', '', '', ''],
        ['Zwiebel zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Paprikawürfel zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Bulgur und 520 g Wasser zugeben und garen.', '12 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Spieße in der Grillpfanne 10–12 Min. grillen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fleisch vom Spieß nehmen, mild mariniertes Hähnchen in Streifen als Fingerfood, Bulgur (bzw. Quinoa) weich und ungesalzen. Kleinkind (1–3 J.): Spießchen ohne Spitze servieren, Tomate geviertelt.',
    baby: 2,
  },
  {
    id: 'puten-koefte-hirtensalat-joghurt',
    n: 'Puten-Köfte mit Hirtensalat & Joghurtdip',
    img: { wiki: 'Kofta', q: 'turkey kofte shepherd salad yogurt flatbread' },
    ck: 'Köfte',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['kinderliebling'],
    i: [['putenhack', 160], ['zwiebel', 30], ['knoblauch', 3], ['paniermehl', 10], ['gewuerze', 3], ['kraeuter', 5], ['tomate', 100], ['gurke', 80], ['paprika', 60], ['griech_joghurt', 60], ['pitabrot', 40], ['olivenoel', 8], ['zitronensaft', 6], ['salz', 1.5]],
    s: [
      'Zwiebel sehr fein reiben, mit Putenhack, Knoblauch, Paniermehl, Kreuzkümmel, Paprikapulver und Petersilie verkneten.',
      'Baby-/Kleinkind-Portion abnehmen, Rest mit Salz würzen. Zu länglichen Köfte formen.',
      'Köfte in einer Grillpfanne mit wenig Öl 8–10 Min. rundum braten, bis sie durchgegart sind.',
      'Tomaten, Gurke und Paprika fein würfeln, mit restlichem Öl, Zitronensaft und etwas Salz zum Hirtensalat mischen.',
      'Joghurt mit einer Prise Salz glatt rühren. Köfte mit Salat, Joghurt und warmem Fladenbrot servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Köfte in der Pfanne braten.',
      steps: [
        ['Zwiebel, Knoblauch und Petersilie zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Putenhack, Paniermehl und Gewürze zugeben und vermengen.', '30 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Baby-Portion abnehmen, Rest salzen und Köfte formen.', '', '', '', ''],
        ['Köfte in der Pfanne 8–10 Min. rundum braten.', '', '', '', ''],
        ['Gemüse fürs Hirtensalat in den Mixtopf geben und grob hacken.', '3 Sek.', '', 'Stufe 4', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Mini-Köfte in Stäbchenform sind tolles BLW-Fingerfood, Gurke geschält in Sticks, Joghurt als Dip. Kleinkind (1–3 J.): Köfte halbieren, Fladenbrot in Streifen.',
    baby: 2,
  },
  {
    id: 'tavuk-sote-reis',
    n: 'Tavuk Sote (türkische Hähnchenpfanne) mit Reis',
    img: { q: 'tavuk sote turkish chicken saute peppers tomatoes rice' },
    ck: 'Türkische Hähnchenpfanne',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['mealprep'],
    i: [['haehnchenbrust', 170], ['paprika', 120], ['tomate', 120], ['zwiebel', 40], ['knoblauch', 4], ['tomatenmark', 10], ['chili_frisch', 3], ['reis', 60], ['olivenoel', 8], ['gewuerze', 2], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Reis nach Packungsangabe garen. Hähnchen in kleine Würfel, Paprika und Tomaten in Stücke schneiden, Zwiebel und Knoblauch hacken.',
      'Öl in einer Pfanne erhitzen und Hähnchen 4 Min. scharf anbraten.',
      'Zwiebel, Knoblauch und Paprika 4 Min. mitbraten, Tomatenmark 1 Min. anrösten.',
      'Tomaten und 50 ml Wasser zugeben und 8 Min. schmoren lassen. Baby-/Kleinkind-Portion jetzt ohne Chili und Salz entnehmen.',
      'Rest mit Chili, Paprikapulver, Thymian und Salz würzen und mit Reis und Petersilie servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Reis im Garkörbchen mitgaren.',
      steps: [
        ['Zwiebel und Knoblauch zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Tomatenmark zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hähnchenwürfel, Paprika, Tomaten und 500 g Wasser zugeben. Garkörbchen mit Reis einhängen und garen.', '20 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Garkörbchen herausnehmen, Pfanne ggf. ohne Messbecher einkochen.', '5 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ohne Chili und Salz entnehmen.', '', '', '', ''],
        ['Chili, Gewürze und Salz zugeben und unterrühren.', '1 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Pfanne mit Reis grob pürieren oder Fleischstreifen und weiche Paprika als Fingerfood. Kleinkind (1–3 J.): ohne Chili, Tomatenhaut ggf. entfernen.',
    baby: 2,
  },
  {
    id: 'musakhan-haehnchen-fladenbrot',
    n: 'Musakhan (Sumach-Hähnchen mit Zwiebeln & Fladenbrot)',
    img: { wiki: 'Musakhan', q: 'musakhan chicken sumac onions flatbread' },
    ck: 'Sumach Hähnchen',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 50, d: 2,
    i: [['haehnchenschenkel', 180], ['rote_zwiebel', 80], ['gewuerze', 4], ['olivenoel', 10], ['pitabrot', 60], ['mandeln', 8], ['griech_joghurt', 60], ['salat', 60], ['zitronensaft', 6], ['kraeuter', 3], ['salz', 1.5]],
    s: [
      'Hähnchenschenkel mit der Hälfte von Sumach, Piment und Kreuzkümmel sowie etwas Öl einreiben. Ofen auf 200 °C vorheizen.',
      'Rote Zwiebeln in Ringe schneiden und im restlichen Öl bei kleiner Hitze 15 Min. weich schmoren, restliches Sumach zugeben.',
      'Hähnchen im Ofen 25 Min. backen, dann in Streifen schneiden.',
      'Fladenbrot mit Zwiebeln und Hähnchen belegen, mit gehackten Mandeln bestreuen und 5 Min. im Ofen knusprig backen.',
      'Baby-/Kleinkind-Portion ungesalzen abnehmen. Mit Joghurt, Blattsalat mit Zitronensaft und Petersilie servieren, leicht salzen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Zwiebeln im Mixtopf geschmort, Rest im Ofen.',
      steps: [
        ['Rote Zwiebeln halbiert in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 4', ''],
        ['Öl zugeben und schmoren, Messbecher durch Garkörbchen ersetzen.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Sumach zugeben und unterrühren.', '10 Sek.', '', 'Stufe 1', 'Linkslauf'],
        ['Hähnchen im Ofen 25 Min. bei 200 °C backen, mit Zwiebeln auf Fladenbrot verteilen und 5 Min. überbacken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes Hähnchen in Streifen, weiche Zwiebeln, Fladenbrot (bzw. glutenfrei) in Streifen ohne ganze Mandeln. Kleinkind (1–3 J.): Mandeln nur gemahlen, Brot in Stücke.',
    baby: 1,
  },
  {
    id: 'haehnchen-tajine-zitrone-oliven',
    n: 'Hähnchen-Tajine mit Zitrone & Oliven',
    img: { wiki: 'Tajine', q: 'chicken tagine preserved lemon olives couscous' },
    ck: 'Hähnchen Tajine',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 55, d: 2,
    st: ['comfort'],
    i: [['haehnchenschenkel', 170], ['zwiebel', 50], ['knoblauch', 4], ['ingwer', 4], ['karotte', 100], ['kichererbsen', 40], ['oliven', 15], ['zitronensaft', 10], ['huehnerbruehe', 150], ['couscous', 50], ['olivenoel', 8], ['gewuerze', 3], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Hähnchen in große Stücke schneiden und mit Kurkuma, Kreuzkümmel, Zimt und Paprika einreiben. Zwiebel, Knoblauch und Ingwer fein hacken, Karotten in dicke Scheiben schneiden.',
      'Öl in einem Schmortopf erhitzen, Hähnchen 5 Min. anbraten. Zwiebel, Knoblauch und Ingwer 3 Min. mitdünsten.',
      'Karotten, Kichererbsen und Brühe zugeben und zugedeckt 25 Min. leise schmoren.',
      'Baby-/Kleinkind-Portion ohne Oliven und ungesalzen entnehmen.',
      'Oliven und Zitronensaft zugeben und 5 Min. ziehen lassen. Couscous mit 75 ml kochendem Wasser übergießen, 5 Min. quellen lassen und auflockern.',
      'Tajine mit Koriander bestreuen und mit Couscous servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Zwiebel, Knoblauch und Ingwer zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Gewürze zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hähnchenstücke, Karotten, Kichererbsen und Brühe zugeben und schmoren.', '25 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ohne Oliven und Salz entnehmen.', '', '', '', ''],
        ['Oliven und Zitronensaft zugeben und ziehen lassen.', '5 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Couscous mit kochendem Wasser übergießen und quellen lassen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ohne Oliven und Salz; Hähnchen zupfen, Karotten und Kichererbsen zerdrücken (Haut abziehen) und mit Couscous mischen. Kleinkind (1–3 J.): Oliven nur fein gehackt, Kichererbsen halbieren.',
    baby: 2,
  },
  {
    id: 'fattoush-haehnchen',
    n: 'Fattoush-Salat mit gegrilltem Hähnchen',
    img: { wiki: 'Fattoush', q: 'fattoush salad grilled chicken pita chips sumac' },
    ck: 'Fattoush',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['haehnchenbrust', 170], ['salat', 80], ['tomate', 100], ['gurke', 100], ['radieschen', 50], ['paprika', 60], ['pitabrot', 40], ['olivenoel', 12], ['zitronensaft', 12], ['gewuerze', 3], ['kraeuter', 6], ['feta', 20], ['salz', 1.5]],
    s: [
      'Hähnchenbrust mit Sumach, Paprikapulver und etwas Öl einreiben und in der Grillpfanne je Seite 5–6 Min. braten, 5 Min. ruhen lassen und in Scheiben schneiden.',
      'Fladenbrot in Stücke reißen und im Ofen bei 200 °C 6–8 Min. knusprig rösten.',
      'Salat, Tomaten, Gurke, Radieschen und Paprika schneiden, Minze und Petersilie hacken.',
      'Restliches Öl mit Zitronensaft, Sumach und Salz verrühren und mit dem Salat mischen.',
      'Brotchips und Hähnchen darauf verteilen und mit zerbröseltem Feta bestreuen.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen ausgelegt. Thermomix nur für Dressing und Hähnchen im Varoma.',
      steps: [
        ['500 g Wasser in den Mixtopf, gewürzte Hähnchenbrust in Scheiben in den Varoma legen und dampfgaren.', '18 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren, Minze und Petersilie zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl, Zitronensaft, Sumach und Salz zugeben und emulgieren.', '10 Sek.', '', 'Stufe 4', ''],
        ['Salat schneiden, Brot im Ofen rösten und alles mischen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen ungesalzen in Streifen, Gurke und Paprika gedünstet als Sticks, Brot weich (nicht geröstet), keine Radieschen. Kleinkind (1–3 J.): Salat klein geschnitten ohne Dressing-Salz, Brotchips in kleinen Stücken.',
    baby: 1,
  },
  {
    id: 'yakitori-reis-gurkensalat',
    n: 'Yakitori mit Reis & Gurkensalat',
    img: { wiki: 'Yakitori', q: 'yakitori chicken skewers tare rice cucumber salad' },
    ck: 'Yakitori',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    i: [['haehnchenschenkel', 180], ['fruehlingszwiebel', 40], ['sojasauce', 20], ['honig', 8], ['ingwer', 4], ['reis', 60], ['gurke', 120], ['essig', 8], ['sesam', 4], ['rapsoel', 6]],
    s: [
      'Sojasauce, Honig, geriebenen Ingwer und 3 EL Wasser in einem kleinen Topf 4–5 Min. zu einer dicklichen Tare einkochen.',
      'Reis nach Packungsangabe garen. Gurke in dünne Scheiben schneiden und mit Essig und Sesam marinieren.',
      'Hähnchenschenkel in 3 cm große Stücke schneiden und abwechselnd mit Frühlingszwiebelstücken auf Spieße stecken.',
      'Spieße mit Öl bepinseln und in der Grillpfanne oder unter dem Backofengrill 10–12 Min. rundum grillen. Baby-/Kleinkind-Spieß ohne Tare zur Seite legen.',
      'Die übrigen Spieße in den letzten 3 Min. mehrfach mit Tare bestreichen und mit Reis und Gurkensalat servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Spieße werden gegrillt.',
      steps: [
        ['Ingwer zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Sojasauce, Honig und 50 g Wasser zugeben und zur Tare einkochen, Messbecher durch Garkörbchen ersetzen.', '6 Min.', '100°C', 'Stufe 2', ''],
        ['Tare umfüllen, Mixtopf spülen. 1000 g Wasser einfüllen, Reis im Garkörbchen garen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Spieße in der Grillpfanne 10–12 Min. grillen, Baby-Spieß ohne Tare beiseitelegen, Rest glasieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Honig ist unter 12 Monaten tabu – Babyspieß ohne Tare, Fleisch vom Spieß in Streifen, Reis als Bällchen, geschälte Gurkensticks. Kleinkind (1–3 J.): Tare sparsam (salzig), Fleisch vom Spieß nehmen.',
    baby: 1,
  },
  {
    id: 'orangenhaehnchen-reis-brokkoli',
    n: 'Orangenhähnchen mit Reis & Brokkoli',
    img: { wiki: 'Orange chicken', q: 'orange chicken rice broccoli' },
    ck: 'Orangenhähnchen',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    st: ['kinderliebling'],
    i: [['haehnchenbrust', 170], ['speisestaerke', 10], ['ei', 20], ['orange', 100], ['sojasauce', 15], ['ingwer', 4], ['knoblauch', 3], ['honig', 6], ['reis', 50], ['brokkoli', 150], ['rapsoel', 8], ['sesam', 3]],
    s: [
      'Reis nach Packungsangabe garen, Brokkoli in Röschen in den letzten 5 Min. darüber dämpfen.',
      'Hähnchen in mundgerechte Würfel schneiden, mit Ei und 2/3 der Stärke mischen.',
      'Öl in einer großen Pfanne erhitzen und das Hähnchen 6–7 Min. rundum knusprig braten. Baby-/Kleinkind-Portion vor dem Glasieren abnehmen.',
      'Orangen auspressen (Schale einer halben abreiben). Saft mit Sojasauce, Honig, Ingwer, Knoblauch und restlicher Stärke verrühren.',
      'Sauce in die Pfanne geben, 1–2 Min. aufkochen, bis sie glänzt und andickt, Hähnchen darin schwenken. Mit Sesam, Reis und Brokkoli servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Hähnchen in der Pfanne knusprig braten.',
      steps: [
        ['1000 g Wasser in den Mixtopf, Reis im Garkörbchen und Brokkoli im Varoma garen.', '22 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren. Ingwer und Knoblauch zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Orangensaft, Sojasauce, Honig und Stärke zugeben und zur Sauce andicken.', '4 Min.', '100°C', 'Stufe 3', 'Andicken'],
        ['Hähnchen in der Pfanne knusprig braten, Baby-Portion abnehmen, Rest in der Sauce schwenken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Honig erst ab 12 Monaten – Babyportion ohne Sauce, nur mit etwas frischem Orangensaft beträufeln; Hähnchen in Streifen, Brokkoli-Röschen weich. Kleinkind (1–3 J.): wenig Sauce (salzig/süß).',
    baby: 1,
  },
  {
    id: 'massaman-curry-haehnchen',
    n: 'Massaman-Curry mit Hähnchen & Kartoffeln',
    img: { wiki: 'Massaman curry', q: 'massaman curry chicken potatoes peanuts' },
    ck: 'Massaman Curry',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['comfort', 'mealprep'],
    i: [['haehnchenschenkel', 170], ['kartoffel', 180], ['zwiebel', 50], ['currypaste', 20], ['kokosmilch_light', 150], ['erdnuesse', 10], ['fischsauce', 6], ['limette', 15], ['gewuerze', 1], ['zimt', 0.5], ['rapsoel', 5], ['kraeuter', 3]],
    s: [
      'Kartoffeln schälen und in 2 cm große Würfel, Hähnchen in große Stücke, Zwiebel in Spalten schneiden.',
      'Öl im Topf erhitzen, Currypaste mit Zimt und Kardamom 1 Min. anrösten, Hähnchen 3 Min. darin anbraten.',
      'Kokosmilch, 100 ml Wasser, Kartoffeln und Zwiebeln zugeben und 20–25 Min. sanft köcheln, bis die Kartoffeln weich sind.',
      'Baby-/Kleinkind-Portion besser vorher separat ohne Currypaste in Kokosmilch garen.',
      'Mit Fischsauce und Limettensaft abschmecken, mit gehackten Erdnüssen und Koriander bestreuen. Nach Wunsch mit etwas Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Zwiebel in Spalten, Öl, Currypaste und Gewürze in den Mixtopf geben und andünsten.', '3 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Hähnchenstücke zugeben und anbraten.', '4 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Kokosmilch, 400 g Wasser und Kartoffelwürfel zugeben und garen.', '22 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Fischsauce und Limettensaft zugeben und unterrühren.', '30 Sek.', '', 'Sanftrührstufe', 'Linkslauf'],
        ['Mit gehackten Erdnüssen und Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): eigene Portion Hähnchen und Kartoffeln in Kokosmilch ohne Currypaste und Fischsauce garen und zerdrücken; Erdnüsse nur als feines Mus einführen. Kleinkind (1–3 J.): mild, Erdnüsse fein gemahlen statt gehackt.',
    baby: 1,
  },
  {
    id: 'pad-kra-pao-haehnchen-spiegelei',
    n: 'Pad Kra Pao (Thai-Basilikum-Hähnchen) mit Spiegelei',
    img: { q: 'pad kra pao thai basil chicken fried egg rice' },
    ck: 'Thai Basilikum Hähnchen',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['haehnchenbrust', 150], ['ei', 55], ['knoblauch', 5], ['chili_frisch', 3], ['gruene_bohnen', 100], ['paprika', 60], ['austernsauce', 10], ['sojasauce', 8], ['fischsauce', 5], ['kraeuter', 6], ['reis', 55], ['rapsoel', 8]],
    s: [
      'Reis nach Packungsangabe garen. Hähnchen sehr fein hacken oder in kleine Stücke schneiden. Knoblauch und Chili fein hacken, Bohnen in 2 cm Stücke schneiden.',
      'Die Hälfte des Öls im Wok stark erhitzen, Knoblauch 30 Sek. anbraten, Hähnchen 3–4 Min. krümelig braten.',
      'Bohnen, Paprika und 2 EL Wasser zugeben und 3 Min. pfannenrühren. Baby-/Kleinkind-Portion jetzt ohne Chili und Saucen entnehmen.',
      'Chili, Austern-, Soja- und Fischsauce zugeben, Thai-Basilikum unterheben und vom Herd nehmen.',
      'Im restlichen Öl ein Spiegelei mit knusprigem Rand braten und auf Reis und Hähnchen setzen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Spiegelei in der Pfanne braten.',
      steps: [
        ['Reis vorab nach Packungsangabe garen. Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl und Hähnchenstücke zugeben und anbraten.', '5 Min.', '150°C', 'Stufe 1', 'Anbraten'],
        ['Bohnen, Paprika und 50 g Wasser zugeben und garen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ohne Chili und Saucen entnehmen.', '', '', '', ''],
        ['Fein gehackte Chili und Saucen zugeben, Basilikum unterheben.', '1 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Spiegelei in der Pfanne braten und auf Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen ohne Saucen und Chili mit Reis mischen, Ei vollständig durchgaren (kein flüssiges Eigelb) und in Streifen schneiden. Kleinkind (1–3 J.): ohne Chili, Saucen nur wenig.',
    baby: 1,
  },
  {
    id: 'bun-zitronengras-haehnchen',
    n: 'Bún mit Zitronengras-Hähnchen',
    img: { q: 'bun ga nuong vietnamese lemongrass chicken vermicelli bowl' },
    ck: 'Vietnamesische Reisnudelbowl',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    i: [['haehnchenschenkel', 170], ['reisnudeln', 60], ['salat', 50], ['gurke', 80], ['karotte', 60], ['kraeuter', 8], ['erdnuesse', 10], ['fischsauce', 10], ['limette', 20], ['knoblauch', 3], ['chili_frisch', 2], ['honig', 5], ['ingwer', 4], ['rapsoel', 6]],
    s: [
      'Hähnchenschenkel mit gehacktem Zitronengras (oder Ingwer), Knoblauch, der Hälfte der Fischsauce und Öl 15 Min. marinieren.',
      'Reisnudeln nach Packungsangabe einweichen bzw. garen und kalt abspülen. Gurke und Karotte in feine Streifen schneiden.',
      'Hähnchen in der Grillpfanne je Seite 5–6 Min. braten und in Streifen schneiden.',
      'Dressing (Nuoc Cham) aus restlicher Fischsauce, Limettensaft, Honig, 3 EL Wasser und Chili verrühren. Baby-/Kleinkind-Portion ohne Dressing abnehmen.',
      'Nudeln mit Salat, Gemüse, Hähnchen, Minze und Koriander anrichten, mit gehackten Erdnüssen bestreuen und Dressing darüber geben.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen ausgelegt. Thermomix für Marinade und Dressing.',
      steps: [
        ['Ingwer/Zitronengras und Knoblauch zerkleinern.', '5 Sek.', '', 'Stufe 8', ''],
        ['Hälfte der Fischsauce und Öl zugeben, verrühren und Hähnchen darin marinieren.', '5 Sek.', '', 'Stufe 3', ''],
        ['Mixtopf spülen. Chili zerkleinern, Fischsauce, Limettensaft, Honig und Wasser zugeben und verrühren.', '10 Sek.', '', 'Stufe 4', ''],
        ['Hähnchen in der Grillpfanne braten, Nudeln garen und Bowls anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen ohne Fischsauce marinieren (nur Ingwer), weich in Streifen, Reisnudeln kurz geschnitten, Gemüse gedünstet; Honig erst ab 12 Monaten. Kleinkind (1–3 J.): ohne Chili, Erdnüsse fein gemahlen.',
    baby: 1,
  },
  {
    id: 'dakgalbi-haehnchen-kohl',
    n: 'Dakgalbi (koreanische scharfe Hähnchenpfanne)',
    img: { wiki: 'Dak-galbi', q: 'dakgalbi korean spicy chicken cabbage sweet potato' },
    ck: 'Koreanische Hähnchenpfanne',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 35, d: 2,
    i: [['haehnchenschenkel', 180], ['weisskohl', 150], ['suesskartoffel', 80], ['zwiebel', 40], ['fruehlingszwiebel', 20], ['sriracha', 10], ['sojasauce', 12], ['honig', 5], ['knoblauch', 4], ['ingwer', 4], ['reis', 40], ['sesamoel', 5], ['rapsoel', 5], ['sesam', 3]],
    s: [
      'Sriracha (oder Gochujang), Sojasauce, Honig, Knoblauch und Ingwer verrühren. Hähnchen in Streifen schneiden und 15 Min. darin marinieren – die Baby-/Kleinkind-Portion nur mit etwas Ingwer.',
      'Reis nach Packungsangabe garen. Kohl in breite Streifen, Süßkartoffel in dünne Scheiben, Zwiebel in Spalten schneiden.',
      'Rapsöl in einer großen Pfanne erhitzen, Süßkartoffel und Zwiebel 4 Min. braten.',
      'Hähnchen samt Marinade und Kohl zugeben und unter Wenden 8–10 Min. braten, bis das Fleisch gar und der Kohl weich ist.',
      'Mit Sesamöl, Frühlingszwiebeln und Sesam vollenden und mit Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Pfanne wird klassisch in der großen Pfanne gebraten.',
      steps: [
        ['Knoblauch und Ingwer zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Sriracha, Sojasauce und Honig zugeben und zur Marinade verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Baby-Portion Hähnchen vorher nur mit Ingwer beiseitestellen, Rest marinieren. Mixtopf spülen.', '', '', '', ''],
        ['1000 g Wasser in den Mixtopf, Reis im Garkörbchen garen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Gemüse und Hähnchen in der Pfanne 12–14 Min. braten, mit Sesamöl und Sesam vollenden.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): eigene Portion ohne scharfe Sauce und Honig braten, Süßkartoffelscheiben und weiches Hähnchen als Fingerfood, Kohl sehr weich. Kleinkind (1–3 J.): ohne Sriracha, nur mit Sojasauce mild.',
    baby: 1,
  },
  {
    id: 'haehnchen-cashew-wok',
    n: 'Hähnchen mit Cashewkernen aus dem Wok',
    img: { wiki: 'Cashew chicken', q: 'cashew chicken stir fry peppers rice' },
    ck: 'Hähnchen Cashew Wok',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['haehnchenbrust', 170], ['cashews', 15], ['paprika', 100], ['zuckerschoten', 80], ['fruehlingszwiebel', 30], ['knoblauch', 4], ['ingwer', 4], ['sojasauce', 15], ['austernsauce', 10], ['speisestaerke', 6], ['reis', 50], ['rapsoel', 8]],
    s: [
      'Reis nach Packungsangabe garen. Hähnchen in Würfel schneiden und mit der Hälfte der Stärke mischen.',
      'Cashews in einem trockenen Wok 2–3 Min. goldbraun rösten und herausnehmen.',
      'Öl im Wok stark erhitzen, Hähnchen 4–5 Min. braten. Knoblauch, Ingwer, Paprika und Zuckerschoten 3 Min. mitbraten.',
      'Baby-/Kleinkind-Portion vor den Saucen entnehmen.',
      'Soja- und Austernsauce mit restlicher Stärke und 60 ml Wasser verrühren, zugießen und kurz aufkochen. Cashews und Frühlingszwiebeln unterheben und mit Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Im Wok wird es knackiger; Reis und Sauce im Thermomix.',
      steps: [
        ['1000 g Wasser in den Mixtopf, Reis im Garkörbchen garen, warmhalten und Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Knoblauch und Ingwer zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Soja- und Austernsauce, Stärke und 200 g Wasser zugeben und andicken.', '4 Min.', '100°C', 'Stufe 3', 'Andicken'],
        ['Hähnchen und Gemüse im Wok braten, Baby-Portion entnehmen, Rest mit der Sauce, Cashews und Frühlingszwiebeln mischen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ohne Saucen; Hähnchenstreifen und weiche Paprika als Fingerfood, Cashews nur als feines Mus (keine ganzen Nüsse). Kleinkind (1–3 J.): Cashews gemahlen darüberstreuen, Zuckerschoten klein schneiden.',
    baby: 1,
  },
  {
    id: 'larb-gai-puten-salat',
    n: 'Larb Gai – Thai-Hackfleischsalat mit Pute',
    img: { wiki: 'Larb', q: 'larb gai thai minced chicken salad lettuce cups herbs' },
    ck: 'Larb Thai Salat',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['putenhack', 170], ['reis', 50], ['salat', 80], ['gurke', 100], ['rote_zwiebel', 30], ['kraeuter', 8], ['limette', 25], ['fischsauce', 10], ['chili_frisch', 2], ['rapsoel', 5], ['erdnuesse', 8]],
    s: [
      'Reis nach Packungsangabe garen (traditionell kommt geröstetes Reispulver in den Larb – dafür 1 EL Reis trocken rösten und mahlen).',
      'Öl in einer Pfanne erhitzen und Putenhack mit 2 EL Wasser 5–6 Min. krümelig gar braten.',
      'Baby-/Kleinkind-Portion abnehmen. Rest vom Herd nehmen und mit Limettensaft, Fischsauce, Chili und fein geschnittener roter Zwiebel mischen.',
      'Minze, Koriander und Reispulver unterheben.',
      'In Salatblättern mit Gurkenscheiben, Erdnüssen und Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['1000 g Wasser in den Mixtopf, Reis im Garkörbchen garen, warmhalten und Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Öl, Putenhack und 50 g Wasser in den Mixtopf geben und krümelig garen.', '8 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion abnehmen.', '', '', '', ''],
        ['Limettensaft, Fischsauce, Chili und Zwiebelstreifen zugeben und mischen.', '10 Sek.', '', 'Stufe 1', 'Linkslauf'],
        ['Kräuter unterheben und in Salatblättern servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hack ohne Fischsauce und Chili mit Reis zu Bällchen formen, Gurke geschält als Sticks. Kleinkind (1–3 J.): ohne Chili, wenig Fischsauce, Erdnüsse nur gemahlen; Salatschiffchen machen Spaß.',
    baby: 1,
  },
  {
    id: 'oyakodon',
    n: 'Oyakodon (japanische Hähnchen-Ei-Reisschüssel)',
    img: { wiki: 'Oyakodon', q: 'oyakodon chicken egg rice bowl' },
    ck: 'Oyakodon',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['comfort'],
    i: [['haehnchenschenkel', 150], ['ei', 80], ['zwiebel', 60], ['huehnerbruehe', 100], ['sojasauce', 15], ['honig', 5], ['reis', 60], ['fruehlingszwiebel', 15], ['spinat', 60]],
    s: [
      'Sushireis oder Basmati nach Packungsangabe garen. Hähnchen in kleine Stücke, Zwiebel in feine Streifen schneiden.',
      'Brühe mit Sojasauce und Honig in einer kleinen Pfanne aufkochen, Zwiebeln 3 Min. darin köcheln.',
      'Hähnchen zugeben und zugedeckt 5–6 Min. garen. Spinat in den letzten 30 Sek. zusammenfallen lassen. Baby-/Kleinkind-Hähnchen vorher aus der ungewürzten Brühe nehmen.',
      'Eier locker verquirlen, über das Hähnchen gießen und zugedeckt 1–2 Min. stocken lassen (für Kinder vollständig durchgaren).',
      'Alles auf Reis gleiten lassen und mit Frühlingszwiebeln bestreuen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Reis im Garkörbchen, Hähnchen und Zwiebeln im Varoma, Ei-Topping auf dem Einlegeboden.',
      steps: [
        ['Brühe und 700 g Wasser in den Mixtopf, Reis im Garkörbchen einhängen.', '', '', '', ''],
        ['Varoma mit Zwiebelstreifen und Hähnchenstücken aufsetzen und alles garen.', '20 Min.', 'Varoma', 'Stufe 4', ''],
        ['Baby-/Kleinkind-Portion Hähnchen entnehmen. Hähnchen und Zwiebeln in einer flachen Form mit Sojasauce und Honig mischen, verquirlte Eier und Spinat darauf geben.', '', '', '', ''],
        ['Form in den Varoma stellen und das Ei stocken lassen.', '8 Min.', 'Varoma', 'Stufe 1', ''],
        ['Auf Reis anrichten und mit Frühlingszwiebeln bestreuen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Ei komplett durchgaren, ohne Sojasauce und Honig; Hähnchen-Ei-Reis zerdrücken oder als Omelettstreifen. Kleinkind (1–3 J.): wenig Sojasauce, Ei fest stocken lassen.',
    baby: 1,
  },
  {
    id: 'haehnchen-jalfrezi',
    n: 'Hähnchen-Jalfrezi mit Basmatireis',
    img: { wiki: 'Jalfrezi', q: 'chicken jalfrezi peppers onions curry rice' },
    ck: 'Chicken Jalfrezi',
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['mealprep'],
    i: [['haehnchenbrust', 170], ['paprika', 150], ['zwiebel', 60], ['tomaten_dose', 120], ['knoblauch', 4], ['ingwer', 5], ['chili_frisch', 3], ['currypulver', 5], ['reis', 55], ['rapsoel', 8], ['kraeuter', 4], ['joghurt', 40], ['salz', 1]],
    s: [
      'Reis nach Packungsangabe garen. Hähnchen würfeln, Paprika und Zwiebel in grobe Stücke schneiden, Knoblauch und Ingwer reiben.',
      'Öl in einer Pfanne stark erhitzen, Hähnchen mit der Hälfte des Garam Masala 4 Min. anbraten und herausnehmen.',
      'Zwiebel und Paprika 4 Min. bissfest braten, Knoblauch, Ingwer und restliche Gewürze 1 Min. mitrösten.',
      'Tomaten zugeben, 6 Min. einköcheln und Hähnchen zurückgeben. Baby-/Kleinkind-Portion ohne Chili und Salz entnehmen.',
      'Chili und Salz zugeben, mit Koriander, einem Klecks Joghurt und Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Reis im Garkörbchen mitgaren.',
      steps: [
        ['Knoblauch und Ingwer zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Öl und Gewürze zugeben und anrösten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Hähnchenwürfel, Zwiebel- und Paprikastücke, Tomaten und 450 g Wasser zugeben, Garkörbchen mit Reis einhängen und garen.', '20 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Garkörbchen herausnehmen, Sauce ohne Messbecher einkochen.', '5 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ohne Chili und Salz entnehmen.', '', '', '', ''],
        ['Chili und Salz zugeben und unterrühren.', '30 Sek.', '', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): mild ohne Chili und Salz, mit Joghurt und Reis grob pürieren; weiche Hähnchenstücke als Fingerfood. Kleinkind (1–3 J.): ohne Chili, Paprika klein schneiden.',
    baby: 2,
  },
  {
    id: 'haehnchen-enchiladas',
    n: 'Hähnchen-Enchiladas mit Bohnen',
    img: { wiki: 'Enchilada', q: 'chicken enchiladas baked tomato sauce cheese' },
    ck: 'Enchiladas Hähnchen',
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['kinderliebling'],
    i: [['haehnchenbrust', 140], ['tortilla', 60], ['kidneybohnen', 40], ['paprika', 60], ['zwiebel', 30], ['passierte_tomaten', 120], ['cajun', 3], ['gouda_light', 20], ['skyr', 40], ['rapsoel', 5], ['kraeuter', 3], ['salz', 0.5]],
    s: [
      'Ofen auf 200 °C vorheizen. Hähnchen in einem Topf mit Wasser bedeckt 12 Min. pochieren, dann mit zwei Gabeln zerzupfen.',
      'Zwiebel und Paprika würfeln und im Öl 4 Min. dünsten. Bohnen und Hähnchen zugeben. Baby-/Kleinkind-Portion ungewürzt abnehmen.',
      'Passierte Tomaten mit Taco-Gewürz und Salz verrühren; die Hälfte unter die Füllung mischen.',
      'Füllung auf die Tortillas verteilen, aufrollen und mit der Naht nach unten in eine Form legen. Restliche Sauce darübergießen und mit Käse bestreuen.',
      '20 Min. backen, mit Skyr und Koriander servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Hähnchen im Varoma, Backen im Ofen.',
      steps: [
        ['500 g Wasser in den Mixtopf, Hähnchenbrust in Scheiben in den Varoma legen und garen.', '20 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren, Hähnchen in den Mixtopf geben und zerzupfen.', '4 Sek.', '', 'Stufe 4', 'Linkslauf'],
        ['Hähnchen umfüllen. Zwiebel zerkleinern, Öl und Paprika zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Bohnen und Hähnchen zugeben, Baby-Portion entnehmen.', '', '', '', ''],
        ['Tortillas füllen, mit gewürzter Tomatensauce und Käse 20 Min. bei 200 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Füllung mit zerdrückten Bohnen (Haut abziehen), Tortilla in Streifen; Käse nur wenig. Kleinkind (1–3 J.): mild würzen, Enchilada in Stücke schneiden.',
    baby: 1,
  },
  {
    id: 'chicken-tinga-tostadas',
    n: 'Chicken-Tinga-Tostadas mit Avocado',
    img: { q: 'chicken tinga tostadas chipotle tomato avocado' },
    ck: 'Tinga de Pollo',
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    i: [['haehnchenbrust', 160], ['tortilla_mais', 60], ['tomaten_dose', 150], ['zwiebel', 50], ['knoblauch', 4], ['gewuerze', 3], ['chili_frisch', 3], ['avocado', 30], ['salat', 50], ['schmand_light', 30], ['limette', 15], ['rapsoel', 8], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Hähnchenbrust 12 Min. in leicht siedendem Wasser pochieren und zerzupfen.',
      'Zwiebel in Streifen schneiden und in der Hälfte des Öls 5 Min. weich dünsten, Knoblauch zugeben.',
      'Tomaten, geräuchertes Paprikapulver, Oregano und Chili (oder Chipotle) zugeben, 8 Min. köcheln und fein pürieren. Hähnchen unterheben. Baby-/Kleinkind-Portion vor Chili und Salz entnehmen.',
      'Maistortillas dünn mit restlichem Öl bepinseln und bei 200 °C 6–8 Min. knusprig backen.',
      'Tostadas mit Salat, Tinga, Avocadoscheiben, Schmand, Koriander und Limette belegen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Tostadas im Ofen backen.',
      steps: [
        ['500 g Wasser in den Mixtopf, Hähnchen in Scheiben im Varoma garen.', '20 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren. Zwiebel und Knoblauch zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten und Gewürze zugeben und köcheln.', '8 Min.', '100°C', 'Stufe 1', ''],
        ['Baby-Portion Sauce abnehmen. Chili zugeben und pürieren.', '20 Sek.', '', 'Stufe 8', ''],
        ['Hähnchen zugeben und unterrühren.', '1 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Tortillas im Ofen knusprig backen und belegen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen mit ungewürzter Tomatensauce, Avocado als zerdrückter Brei oder Spalten, Maistortilla weich (nicht geröstet) in Streifen. Kleinkind (1–3 J.): ohne Chili, Tostada in Stücke brechen.',
    baby: 1,
  },
  {
    id: 'sopa-de-lima-haehnchen',
    n: 'Mexikanische Hähnchen-Limetten-Suppe (Sopa de lima)',
    img: { wiki: 'Tortilla soup', q: 'sopa de lima mexican chicken lime soup tortilla strips' },
    ck: 'Mexikanische Hühnersuppe',
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['comfort'],
    i: [['haehnchenbrust', 170], ['huehnerbruehe', 450], ['tomate', 100], ['paprika', 60], ['zwiebel', 40], ['knoblauch', 4], ['mais', 30], ['schwarze_bohnen', 40], ['tortilla_mais', 30], ['avocado', 30], ['limette', 25], ['gewuerze', 2], ['kraeuter', 4], ['rapsoel', 6]],
    s: [
      'Zwiebel, Knoblauch, Tomaten und Paprika würfeln. Öl im Topf erhitzen und das Gemüse 5 Min. dünsten.',
      'Brühe, Oregano und Kreuzkümmel zugeben, aufkochen und das ganze Hähnchenbrustfilet 15 Min. darin gar ziehen lassen. Herausnehmen und zerzupfen.',
      'Mais, Bohnen und Hähnchen in die Suppe geben und 3 Min. erhitzen. Baby-/Kleinkind-Portion entnehmen.',
      'Tortillas in Streifen schneiden und im Ofen bei 200 °C 6 Min. knusprig backen.',
      'Suppe mit Limettensaft abschmecken, mit Tortillastreifen, Avocadowürfeln und Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Tortillastreifen im Ofen rösten.',
      steps: [
        ['Zwiebel und Knoblauch zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl, Tomaten- und Paprikawürfel zugeben und dünsten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe, Gewürze und Hähnchenbrust zugeben und garen.', '18 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Hähnchen herausnehmen, zerzupfen und mit Mais und Bohnen zurückgeben.', '3 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen, Rest mit Limettensaft abschmecken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Brühe ohne Salz (selbst gekocht), Hähnchen und Gemüse abschöpfen und zerdrücken, Avocado als Fingerfood. Kleinkind (1–3 J.): Mais und Bohnen leicht zerdrücken, Tortillastreifen weich in der Suppe.',
    baby: 1,
  },
  {
    id: 'white-chicken-chili',
    n: 'White Chicken Chili (weißes Hähnchen-Chili)',
    img: { q: 'white chicken chili white beans green chiles' },
    ck: 'Weißes Chili Hähnchen',
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['haehnchenbrust', 160], ['weisse_bohnen', 100], ['mais', 35], ['zwiebel', 50], ['knoblauch', 4], ['paprika', 60], ['chili_frisch', 3], ['huehnerbruehe', 200], ['frischkaese_light', 30], ['gewuerze', 3], ['limette', 10], ['kraeuter', 4], ['rapsoel', 6], ['tortilla_mais', 25]],
    s: [
      'Zwiebel, Knoblauch und grüne Paprika würfeln und im Öl 4 Min. dünsten. Kreuzkümmel und Oregano 30 Sek. mitrösten.',
      'Brühe und ganze Hähnchenbrust zugeben und 15 Min. leise köcheln, dann herausnehmen und zerzupfen.',
      'Ein Drittel der Bohnen zerdrücken, mit den übrigen Bohnen, Mais und Hähnchen in den Topf geben, Frischkäse einrühren und 5 Min. sämig köcheln.',
      'Baby-/Kleinkind-Portion ohne Chili entnehmen.',
      'Rest mit Chili und Limettensaft abschmecken, mit Koriander und zerbröselten Tortillachips (Maistortilla im Ofen geröstet) servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Zwiebel und Knoblauch zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl, Paprikawürfel und Gewürze zugeben und dünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Brühe und Hähnchenbrust zugeben und garen.', '18 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Hähnchen herausnehmen und zerzupfen. Ein Drittel der Bohnen zugeben und pürieren.', '10 Sek.', '', 'Stufe 6', ''],
        ['Hähnchen, restliche Bohnen, Mais und Frischkäse zugeben und erhitzen.', '5 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen, Rest mit Chili und Limette abschmecken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ohne Chili, Bohnen gut zerdrücken (Bohnen langsam einführen) und mit gezupftem Hähnchen als cremiger Brei. Kleinkind (1–3 J.): mild, Tortillachips weich in der Suppe.',
    baby: 1,
  },
  {
    id: 'bbq-pulled-chicken-coleslaw',
    n: 'BBQ Pulled Chicken mit Coleslaw & Süßkartoffel',
    img: { q: 'bbq pulled chicken coleslaw sweet potato' },
    ck: 'Pulled Chicken',
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 50, d: 1,
    st: ['kinderliebling', 'mealprep'],
    i: [['haehnchenschenkel', 170], ['ketchup', 30], ['essig', 8], ['senf', 5], ['gewuerze', 3], ['honig', 6], ['zwiebel', 30], ['suesskartoffel', 200], ['weisskohl', 100], ['karotte', 40], ['joghurt', 50], ['mayo_light', 8], ['rapsoel', 5], ['salz', 1]],
    s: [
      'Ofen auf 200 °C vorheizen. Süßkartoffeln halbieren, mit Öl einpinseln und 35–40 Min. weich backen.',
      'Ketchup, Essig, Senf, Honig, geräuchertes Paprikapulver und fein gewürfelte Zwiebel mit 100 ml Wasser verrühren.',
      'Hähnchenschenkel in der Sauce zugedeckt 25 Min. schmoren, dann mit zwei Gabeln zerzupfen und offen 5 Min. einkochen. Baby-/Kleinkind-Fleisch vorher ohne Sauce in Wasser garen.',
      'Kohl und Karotte fein hobeln, mit Joghurt, Mayo, etwas Essig und Salz zum Coleslaw mischen.',
      'Süßkartoffel aufschneiden, mit Pulled Chicken füllen und mit Coleslaw servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Süßkartoffeln gegart im Varoma statt im Ofen möglich.',
      steps: [
        ['Kohl und Karotte in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Joghurt, Mayo, Essig und Salz zugeben und vermischen, umfüllen.', '10 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Zwiebel zerkleinern, Ketchup, Essig, Senf, Honig, Gewürze und 300 g Wasser zugeben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hähnchenschenkel zugeben, Süßkartoffelstücke in den Varoma legen und alles garen.', '30 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Varoma abnehmen, Hähnchen im Mixtopf zerzupfen.', '5 Sek.', '', 'Stufe 4', 'Linkslauf'],
        ['Ohne Messbecher einkochen.', '5 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): eigenes Hähnchen ohne BBQ-Sauce (Honig!) garen und zupfen, Süßkartoffel als weiches Fingerfood. Kleinkind (1–3 J.): wenig Sauce, Coleslaw sehr fein gehobelt.',
    baby: 1,
  },
  {
    id: 'buffalo-chicken-bowl',
    n: 'Buffalo-Chicken-Bowl mit Joghurt-Ranch',
    img: { wiki: 'Buffalo wing', q: 'buffalo chicken bowl celery ranch rice' },
    ck: 'Buffalo Chicken',
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    i: [['haehnchenbrust', 170], ['sriracha', 12], ['butter', 6], ['essig', 5], ['gewuerze', 2], ['reis', 50], ['sellerie', 40], ['karotte', 60], ['salat', 60], ['mais', 30], ['griech_joghurt', 60], ['kraeuter', 4], ['zitronensaft', 6], ['rapsoel', 5], ['salz', 1]],
    s: [
      'Reis nach Packungsangabe garen. Hähnchen mit Paprika und Knoblauchpulver würzen und im Öl je Seite 5–6 Min. braten, dann in Streifen schneiden.',
      'Baby-/Kleinkind-Portion ohne Buffalo-Sauce abnehmen.',
      'Butter schmelzen, mit Sriracha (bzw. Hot Sauce) und Essig verrühren und das restliche Hähnchen darin wenden.',
      'Joghurt mit Dill, Schnittlauch, Zitronensaft und Salz zu Ranch verrühren.',
      'Reis, Salat, Selleriesticks, Karottenstreifen und Mais in Bowls anrichten, Buffalo-Hähnchen darauf geben und mit Ranch beträufeln.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Hähnchen in der Pfanne braten.',
      steps: [
        ['1000 g Wasser in den Mixtopf, Reis im Garkörbchen garen, Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Kräuter zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Joghurt, Zitronensaft und Salz zugeben und verrühren, umfüllen.', '10 Sek.', '', 'Stufe 3', ''],
        ['Butter, Sriracha und Essig in den Mixtopf geben und schmelzen.', '2 Min.', '60°C', 'Stufe 2', ''],
        ['Hähnchen in der Pfanne braten, Baby-Portion abnehmen, Rest in der Sauce wenden.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen ohne scharfe Sauce in Streifen, Karotte gedünstet, Joghurt-Dip ohne Salz. Kleinkind (1–3 J.): ohne Buffalo-Sauce, Sellerie fein schneiden (faserig).',
    baby: 1,
  },
  {
    id: 'chicken-pot-pie-quarkteig',
    n: 'Chicken Pot Pie mit Quark-Öl-Teig',
    img: { wiki: 'Pot pie', q: 'chicken pot pie crust vegetables' },
    ck: 'Chicken Pot Pie',
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 60, d: 2,
    st: ['comfort', 'kinderliebling'],
    i: [['haehnchenbrust', 150], ['karotte', 70], ['erbsen', 50], ['champignons', 50], ['zwiebel', 30], ['huehnerbruehe', 150], ['milch', 60], ['speisestaerke', 8], ['mehl', 35], ['magerquark', 35], ['rapsoel', 10], ['ei', 10], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Ofen auf 200 °C vorheizen. Mehl, Quark, die Hälfte des Öls, eine Prise Salz und 1 EL Wasser zu einem glatten Teig kneten und 15 Min. kühlen.',
      'Hähnchen würfeln, Karotten und Pilze klein schneiden, Zwiebel würfeln. Restliches Öl erhitzen, Hähnchen 4 Min. anbraten, Gemüse 3 Min. mitdünsten.',
      'Brühe und Milch zugießen, aufkochen, mit angerührter Stärke binden. Erbsen und Thymian zugeben. Baby-/Kleinkind-Portion ungesalzen entnehmen, Rest leicht salzen.',
      'Füllung in eine Form geben, Teig ausrollen, darauflegen, mit verquirltem Ei bestreichen und einige Löcher einstechen.',
      '25 Min. backen, bis der Deckel goldbraun ist.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Teig und Füllung im Thermomix, Backen im Ofen.',
      steps: [
        ['Mehl, Quark, Öl, Salz und Wasser in den Mixtopf geben und kneten, Teig kühlen.', '1 Min.', '', '', 'Teigkneten'],
        ['Zwiebel zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl, Hähnchenwürfel, Karotten und Pilze zugeben und anbraten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe und Milch zugeben und garen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Angerührte Stärke und Erbsen zugeben und binden.', '3 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen. Füllung in die Form, Teigdeckel auflegen und 25 Min. bei 200 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Füllung zerdrücken oder Hähnchen, Karotten und Erbsen (zerdrückt) als Fingerfood, weiche Teigstücke. Kleinkind (1–3 J.): klein geschnitten mit etwas Teigkruste.',
    baby: 2,
  },
  {
    id: 'chicken-alfredo-brokkoli',
    n: 'Leichtes Chicken Alfredo mit Brokkoli',
    img: { wiki: 'Fettuccine Alfredo', q: 'chicken alfredo fettuccine broccoli' },
    ck: 'Chicken Alfredo',
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['kinderliebling'],
    i: [['haehnchenbrust', 150], ['nudeln', 60], ['brokkoli', 120], ['milch', 120], ['frischkaese_light', 25], ['parmesan', 12], ['knoblauch', 4], ['speisestaerke', 5], ['olivenoel', 6], ['salz', 0.5]],
    s: [
      'Fettuccine nach Packungsangabe garen, Brokkoliröschen in den letzten 4 Min. mitkochen.',
      'Hähnchen in Streifen schneiden und im Öl 5 Min. goldbraun braten, Knoblauch 30 Sek. mitbraten.',
      'Milch mit Stärke verrühren, zugießen und aufkochen. Frischkäse und Parmesan einrühren, bis eine cremige Sauce entsteht.',
      'Nudeln und Brokkoli in der Sauce schwenken. Baby-/Kleinkind-Portion vor dem Salzen entnehmen.',
      'Mit Pfeffer und wenig Salz abschmecken und servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Parmesan reiben, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['1200 g Wasser aufkochen, Brokkoli in den Varoma legen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Nudeln zugeben, Varoma aufsetzen und garen. Abgießen.', '10 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Knoblauch zerkleinern, Öl und Hähnchenstreifen zugeben und anbraten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Milch mit Stärke, Frischkäse und Parmesan zugeben und andicken.', '5 Min.', '95°C', 'Stufe 1', 'Linkslauf'],
        ['Nudeln und Brokkoli unterheben, Baby-Portion entnehmen, Rest abschmecken.', '30 Sek.', '', 'Sanftrührstufe', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Nudeln kurz schneiden, Brokkoli-Röschen weich als Fingerfood, Hähnchen fein zerzupft; Parmesan ist salzig, Babyportion vorher abnehmen. Kleinkind (1–3 J.): cremig und mild, ein Lieblingsessen.',
    baby: 2,
  },
  {
    id: 'puten-hackbraten-ofengemuese',
    n: 'Puten-Hackbraten mit Ofengemüse',
    img: { wiki: 'Meatloaf', q: 'turkey meatloaf roasted vegetables' },
    ck: 'Hackbraten Pute',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 70, d: 2,
    st: ['comfort', 'mealprep', 'kinderliebling'],
    i: [['putenhack', 160], ['ei', 20], ['haferflocken', 15], ['zwiebel', 30], ['karotte', 80], ['senf', 5], ['ketchup', 15], ['kartoffel', 180], ['zucchini', 100], ['paprika', 80], ['olivenoel', 8], ['gewuerze', 2], ['kraeuter', 4], ['salz', 1.5]],
    s: [
      'Ofen auf 190 °C vorheizen. Zwiebel und eine Karotte fein reiben, mit Putenhack, Ei, Haferflocken, Senf, Paprikapulver und Petersilie verkneten.',
      'Baby-/Kleinkind-Portion als kleine Rolle ungesalzen abnehmen. Rest salzen und zu einem Laib formen.',
      'Hackbraten in eine Form setzen, mit Ketchup bestreichen und 45 Min. backen (Kerntemperatur 75 °C).',
      'Kartoffeln, restliche Karotten, Zucchini und Paprika in Stücke schneiden, mit Öl und Rosmarin mischen und nach 10 Min. Backzeit mit aufs Blech geben.',
      'Hackbraten 5 Min. ruhen lassen, in Scheiben schneiden und mit Ofengemüse servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Backen im Ofen.',
      steps: [
        ['Zwiebel, Karotte und Petersilie in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Putenhack, Ei, Haferflocken, Senf und Gewürze zugeben und vermengen.', '40 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Baby-Portion abnehmen, Rest salzen und zu einem Laib formen.', '', '', '', ''],
        ['Mit Ketchup bestreichen und 45 Min. bei 190 °C backen, Gemüse nach 10 Min. dazugeben.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzener Mini-Hackbraten in Stäbchen geschnitten ist super BLW-Fingerfood, Gemüse weich gegart. Kleinkind (1–3 J.): Scheiben in Stücke, Ketchup sparsam.',
    baby: 2,
  },
  {
    id: 'haehnchen-brokkoli-auflauf',
    n: 'Hähnchen-Brokkoli-Auflauf mit Käsehaube',
    img: { q: 'chicken broccoli casserole cheese potatoes' },
    ck: 'Hähnchen Brokkoli Auflauf',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 55, d: 1,
    st: ['comfort', 'kinderliebling'],
    i: [['haehnchenbrust', 150], ['brokkoli', 180], ['kartoffel', 200], ['milch', 80], ['frischkaese_light', 25], ['ei', 25], ['gouda_light', 20], ['olivenoel', 5], ['gewuerze', 1], ['salz', 1]],
    s: [
      'Ofen auf 200 °C vorheizen. Kartoffeln schälen, in dünne Scheiben schneiden und 8 Min. vorkochen. Brokkoli in Röschen teilen und 3 Min. blanchieren.',
      'Hähnchen in Würfel schneiden und im Öl 4 Min. anbraten.',
      'Milch, Frischkäse und Ei verquirlen, mit Muskat und Pfeffer würzen. Baby-/Kleinkind-Portion in einer kleinen Form ungesalzen schichten, Rest salzen.',
      'Kartoffeln, Brokkoli und Hähnchen in eine gefettete Form schichten, Eiermilch darübergießen und mit Käse bestreuen.',
      '25 Min. backen, bis die Haube goldbraun und der Guss gestockt ist.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Vorgaren im Varoma, Überbacken im Ofen.',
      steps: [
        ['500 g Wasser in den Mixtopf, Kartoffelscheiben in den Varoma und Brokkoli auf den Einlegeboden legen und vorgaren.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren. Milch, Frischkäse, Ei und Gewürze verrühren.', '15 Sek.', '', 'Stufe 4', ''],
        ['Hähnchen in der Pfanne anbraten, mit Gemüse schichten, Guss und Käse darüber geben und 25 Min. bei 200 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Portion mit wenig Käse; Brokkoli, Kartoffeln und Hähnchen als Fingerfood oder zerdrückt, Ei durchgegart. Kleinkind (1–3 J.): klein geschnitten, ein Familien-Favorit.',
    baby: 2,
  },
  {
    id: 'haehnchenkeulen-blech-rosmarinkartoffeln',
    n: 'Hähnchenkeulen vom Blech mit Rosmarinkartoffeln & Möhren',
    img: { q: 'roast chicken legs sheet pan rosemary potatoes carrots' },
    ck: 'Hähnchenschenkel vom Blech',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 60, d: 1,
    st: ['kinderliebling'],
    i: [['haehnchenkeule', 200], ['kartoffel', 200], ['karotte', 120], ['rote_zwiebel', 40], ['olivenoel', 5], ['gewuerze', 3], ['kraeuter', 3], ['griech_joghurt', 40], ['salz', 1.5]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Hähnchenkeulen trocken tupfen, Haut entfernen und mit Paprikapulver, Thymian und der Hälfte des Öls einreiben.',
      'Kartoffeln vierteln, Karotten längs halbieren, Zwiebel in Spalten schneiden. Mit restlichem Öl und Rosmarin mischen.',
      'Gemüse aufs Blech geben, Keulen darauflegen und 45 Min. backen, bis der Fleischsaft klar ist (Kerntemperatur 80 °C).',
      'Baby-/Kleinkind-Portion ungesalzen nehmen. Rest nach dem Garen salzen.',
      'Mit Kräuterjoghurt servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen ausgelegt. Ein klassisches Blechgericht – Thermomix nur für Marinade und Dip.',
      steps: [
        ['Kräuter zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl und Gewürze zugeben und zur Marinade verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Keulen und Gemüse marinieren und 45 Min. bei 200 °C backen.', '', '', '', ''],
        ['Joghurt mit restlichen Kräutern im Mixtopf verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Fleisch vom Knochen lösen (auf kleine Knochen achten), ungesalzen in Streifen; Kartoffeln und Möhren weich als Fingerfood. Kleinkind (1–3 J.): Fleisch auslösen und klein schneiden.',
    baby: 2,
  },
  {
    id: 'puten-gnocchi-auflauf-spinat',
    n: 'Puten-Gnocchi-Auflauf mit Spinat & Tomaten',
    img: { q: 'gnocchi bake turkey spinach tomato mozzarella' },
    ck: 'Gnocchi Auflauf',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['comfort', 'kinderliebling'],
    i: [['putenbrust', 150], ['gnocchi', 150], ['spinat', 80], ['kirschtomaten', 100], ['passierte_tomaten', 100], ['knoblauch', 4], ['mozzarella', 40], ['olivenoel', 6], ['gewuerze', 1], ['salz', 1]],
    s: [
      'Ofen auf 200 °C vorheizen. Putenbrust in Würfel schneiden und im Öl 4 Min. anbraten, Knoblauch kurz mitbraten.',
      'Passierte Tomaten und Oregano zugeben, Spinat darin zusammenfallen lassen. Baby-/Kleinkind-Portion ungesalzen abnehmen.',
      'Rest salzen und mit den rohen Gnocchi und halbierten Kirschtomaten in einer Auflaufform mischen.',
      'Mit Mozzarellastücken belegen und 20 Min. backen, bis die Gnocchi weich und der Käse goldbraun ist.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Backen im Ofen.',
      steps: [
        ['Knoblauch zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl und Putenwürfel zugeben und anbraten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Passierte Tomaten, Oregano und Spinat zugeben und garen.', '4 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion abnehmen, Rest salzen.', '', '', '', ''],
        ['Mit Gnocchi und Kirschtomaten in die Form geben, mit Mozzarella belegen und 20 Min. bei 200 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Gnocchi halbieren oder zerdrücken, Pute fein zerkleinert, Kirschtomaten nur gehäutet und geviertelt. Kleinkind (1–3 J.): Gnocchi und Tomaten vierteln (Verschluckungsgefahr).',
    baby: 2,
  },
  {
    id: 'haehnchen-kartoffel-lauch-gratin',
    n: 'Hähnchen-Kartoffel-Gratin mit Lauch',
    img: { wiki: 'Gratin', q: 'chicken potato leek gratin' },
    ck: 'Kartoffelgratin Hähnchen',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 60, d: 1,
    st: ['comfort'],
    i: [['haehnchenbrust', 150], ['kartoffel', 230], ['lauch', 80], ['milch', 100], ['sahne', 25], ['speisestaerke', 4], ['gouda_light', 20], ['rapsoel', 5], ['gewuerze', 1], ['salz', 1]],
    s: [
      'Ofen auf 190 °C vorheizen. Kartoffeln in 3 mm dünne Scheiben hobeln, Lauch in Ringe schneiden, Hähnchen in dünne Streifen.',
      'Hähnchen im Öl 3 Min. anbraten, Lauch 2 Min. mitdünsten.',
      'Milch und Sahne mit Stärke, Muskat und Pfeffer aufkochen. Baby-/Kleinkind-Portion ungesalzen in eine kleine Form schichten, Rest salzen.',
      'Kartoffeln mit Hähnchen und Lauch abwechselnd in eine Form schichten, Sauce darübergießen und mit Käse bestreuen.',
      'Abgedeckt 25 Min. backen, dann ohne Abdeckung 15 Min. goldbraun gratinieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Kartoffeln im Mixtopf vorgaren verkürzt die Backzeit.',
      steps: [
        ['Milch, Sahne, Stärke und Gewürze in den Mixtopf geben und aufkochen.', '6 Min.', '90°C', 'Stufe 3', ''],
        ['Kartoffelscheiben zugeben und vorgaren.', '8 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion abnehmen, Rest salzen.', '', '', '', ''],
        ['Hähnchen und Lauch in der Pfanne anbraten, mit Kartoffeln schichten, mit Käse bestreuen und 25 Min. bei 190 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes Gratin mit wenig Käse zerdrücken; Kartoffelscheiben weich als Fingerfood. Kleinkind (1–3 J.): Lauch fein geschnitten, in Stücke serviert.',
    baby: 2,
  },
  {
    id: 'asiatischer-glasnudelsalat-haehnchen',
    n: 'Asiatischer Glasnudelsalat mit Hähnchen',
    img: { q: 'glass noodle salad chicken asian cucumber carrot herbs' },
    ck: 'Glasnudelsalat',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['mealprep'],
    i: [['haehnchenbrust', 170], ['glasnudeln', 50], ['karotte', 60], ['gurke', 100], ['paprika', 60], ['edamame', 40], ['kraeuter', 6], ['sojasauce', 15], ['limette', 20], ['sesamoel', 5], ['ingwer', 4], ['erdnuesse', 10], ['honig', 4]],
    s: [
      'Hähnchenbrust in leicht siedendem Wasser 12–14 Min. gar ziehen lassen, abkühlen und in feine Streifen zupfen.',
      'Glasnudeln mit kochendem Wasser übergießen, 5 Min. ziehen lassen, kalt abspülen und mit der Schere kürzen. Edamame 3 Min. blanchieren.',
      'Karotte, Gurke und Paprika in feine Streifen schneiden.',
      'Sojasauce, Limettensaft, Sesamöl, geriebenen Ingwer und Honig verrühren. Baby-/Kleinkind-Portion ohne Dressing abnehmen.',
      'Alles mit Dressing, Koriander und Minze mischen und mit gehackten Erdnüssen bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['500 g Wasser in den Mixtopf, Hähnchen in Scheiben und Edamame in den Varoma legen und garen.', '18 Min.', 'Varoma', 'Stufe 1', ''],
        ['Hähnchen in den leeren Mixtopf geben und zerzupfen.', '4 Sek.', '', 'Stufe 4', 'Linkslauf'],
        ['Hähnchen umfüllen. Ingwer zerkleinern, Sojasauce, Limettensaft, Sesamöl und Honig zugeben und verrühren.', '10 Sek.', '', 'Stufe 5', ''],
        ['Glasnudeln mit kochendem Wasser einweichen, Gemüse schneiden und alles mischen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Glasnudeln sehr kurz schneiden, Hähnchen und gedünstete Karotte ohne Dressing (Honig erst ab 12 Monaten), Edamame zerdrücken. Kleinkind (1–3 J.): wenig Dressing, Erdnüsse gemahlen.',
    baby: 1,
  },
  {
    id: 'cobb-salad-pute',
    n: 'Cobb Salad mit Pute',
    img: { wiki: 'Cobb salad', q: 'cobb salad turkey egg avocado tomato' },
    ck: 'Cobb Salad',
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['putenbrust', 150], ['ei', 55], ['salat', 120], ['kirschtomaten', 100], ['avocado', 30], ['mais', 30], ['feta', 20], ['schinken_gekocht', 20], ['joghurt', 40], ['senf', 5], ['essig', 8], ['olivenoel', 8], ['kartoffel', 120], ['salz', 1]],
    s: [
      'Kartoffeln in Würfel schneiden und in 15 Min. weich kochen, abkühlen lassen. Ei 10 Min. hart kochen, abschrecken und vierteln.',
      'Putenbrust mit etwas Öl einreiben und in der Pfanne je Seite 5–6 Min. braten, 5 Min. ruhen lassen und würfeln.',
      'Schinken in Streifen kurz knusprig anbraten.',
      'Joghurt mit Senf, Essig, restlichem Öl und Salz zu einem Dressing verrühren.',
      'Salat auf Tellern verteilen und Pute, Ei, Tomaten, Avocado, Mais, Kartoffeln, Schinken und Feta in Reihen darauf anrichten, mit Dressing beträufeln.',
    ],
    tm: {
      fit: 0,
      note: 'Für ca. 4 Portionen ausgelegt. Thermomix für Garen im Varoma und Dressing.',
      steps: [
        ['500 g Wasser in den Mixtopf, Kartoffelwürfel und Eier ins Garkörbchen, Putenbrust in Scheiben in den Varoma geben und garen.', '20 Min.', 'Varoma', 'Stufe 1', ''],
        ['Eier abschrecken, Mixtopf leeren.', '', '', '', ''],
        ['Joghurt, Senf, Essig, Öl und Salz verrühren.', '10 Sek.', '', 'Stufe 4', ''],
        ['Salat anrichten und alle Zutaten in Reihen darauflegen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Pute, Ei (hart gekocht), Kartoffel und Avocado als Fingerfood, ohne Schinken und Feta; Tomaten geviertelt. Kleinkind (1–3 J.): Bausteine-Teller ohne Dressing, Schinken nur wenig.',
    baby: 1,
  },
  {
    id: 'avgolemono-huehnersuppe',
    n: 'Avgolemono (griechische Hühner-Zitronen-Suppe)',
    img: { wiki: 'Avgolemono', q: 'avgolemono greek lemon chicken rice soup' },
    ck: 'Avgolemono',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort'],
    i: [['haehnchenbrust', 160], ['huehnerbruehe', 450], ['reis', 45], ['ei', 55], ['zitronensaft', 15], ['karotte', 60], ['zwiebel', 30], ['spinat', 40], ['kraeuter', 4], ['olivenoel', 5], ['salz', 0.5]],
    s: [
      'Zwiebel und Karotte fein würfeln und im Öl 3 Min. dünsten. Brühe zugeben und aufkochen.',
      'Hähnchenbrust und Reis zugeben und 15 Min. leise köcheln. Hähnchen herausnehmen und zerzupfen.',
      'Eier mit Zitronensaft schaumig schlagen. Nach und nach 200 ml heiße Brühe unter ständigem Rühren einlaufen lassen (temperieren).',
      'Eiermischung in die nicht mehr kochende Suppe rühren und bei kleiner Hitze 3–4 Min. rühren, bis sie leicht bindet und das Ei gar ist (nicht kochen).',
      'Hähnchen und Spinat zugeben, Baby-/Kleinkind-Portion entnehmen, mit Dill bestreuen und servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Der Thermomix legiert die Suppe sicher ohne Gerinnen.',
      steps: [
        ['Zwiebel und Karotte zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Brühe, Reis und Hähnchenbrust zugeben und garen.', '18 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Hähnchen herausnehmen und zerzupfen. Suppe abkühlen lassen.', '3 Min.', '', 'Stufe 1', 'Linkslauf'],
        ['Eier und Zitronensaft bei laufendem Messer zugeben und legieren.', '5 Min.', '80°C', 'Stufe 2', 'Linkslauf'],
        ['Hähnchen und Spinat zugeben und erwärmen.', '2 Min.', '80°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen und mit Dill servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): mit ungesalzener Brühe kochen, Ei vollständig gegart; Reis, Hähnchen und Karotte als dicker Brei abschöpfen. Kleinkind (1–3 J.): weniger Zitrone, Suppe dicklich mit dem Löffel.',
    baby: 2,
  },
  {
    id: 'tom-kha-gai',
    n: 'Tom Kha Gai (Thai-Kokos-Hühnersuppe)',
    img: { wiki: 'Tom kha kai', q: 'tom kha gai coconut chicken soup galangal mushrooms' },
    ck: 'Tom Kha Gai',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['comfort'],
    i: [['haehnchenbrust', 170], ['kokosmilch_light', 200], ['huehnerbruehe', 250], ['austernpilze', 80], ['kirschtomaten', 60], ['ingwer', 8], ['limette', 25], ['fischsauce', 8], ['chili_frisch', 2], ['reisnudeln', 40], ['kraeuter', 4], ['honig', 3]],
    s: [
      'Ingwer bzw. Galgant in Scheiben schneiden, mit Zitronengras und Brühe 5 Min. köcheln.',
      'Kokosmilch zugießen, Hähnchen in dünnen Scheiben und Pilze zugeben und 8 Min. sanft garen.',
      'Reisnudeln nach Packungsangabe einweichen und in Schalen verteilen.',
      'Tomaten zugeben. Baby-/Kleinkind-Portion vor Fischsauce und Chili entnehmen.',
      'Mit Fischsauce, Limettensaft, Honig und Chili abschmecken, Ingwerscheiben entfernen und über die Nudeln geben, mit Koriander bestreuen.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt.',
      steps: [
        ['Brühe, Ingwer-/Galgantscheiben und Zitronengras in den Mixtopf geben und aufkochen.', '7 Min.', '100°C', 'Stufe 1', ''],
        ['Kokosmilch, Hähnchenscheiben und Pilze zugeben und garen.', '10 Min.', '95°C', 'Stufe 1', 'Linkslauf'],
        ['Tomaten zugeben und erwärmen.', '2 Min.', '95°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen.', '', '', '', ''],
        ['Fischsauce, Limettensaft, Honig und Chili zugeben und unterrühren.', '20 Sek.', '', 'Sanftrührstufe', 'Linkslauf'],
        ['Reisnudeln einweichen und mit der Suppe servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ohne Fischsauce, Honig und Chili; Hähnchen und Pilze klein geschnitten, kurze Reisnudeln, mildes Kokos-Aroma. Kleinkind (1–3 J.): ohne Chili, Nudeln kürzen.',
    baby: 1,
  },
  {
    id: 'mulligatawny-haehnchen',
    n: 'Mulligatawny – Curry-Hühnersuppe mit Linsen & Apfel',
    img: { wiki: 'Mulligatawny', q: 'mulligatawny soup chicken lentils curry' },
    ck: 'Mulligatawny',
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['haehnchenbrust', 150], ['rote_linsen', 35], ['apfel', 60], ['karotte', 80], ['zwiebel', 40], ['knoblauch', 4], ['ingwer', 5], ['currypulver', 5], ['huehnerbruehe', 400], ['kokosmilch_light', 60], ['reis', 25], ['joghurt', 40], ['rapsoel', 6], ['kraeuter', 3]],
    s: [
      'Zwiebel, Knoblauch, Ingwer, Karotte und Apfel würfeln. Öl im Topf erhitzen und alles 4 Min. dünsten, Currypulver 1 Min. mitrösten.',
      'Linsen, Reis und Brühe zugeben und 20 Min. köcheln. Hähnchen in Würfeln nach 8 Min. zugeben.',
      'Die Hälfte der Suppe ohne Fleisch fein pürieren und zurückgeben, Kokosmilch einrühren.',
      'Baby-/Kleinkind-Portion entnehmen (bei Bedarf mit milderem Curry separat gekocht).',
      'Mit Koriander und einem Klecks Joghurt servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Bei 4 Portionen ist der Mixtopf gut gefüllt – Brühe ggf. reduzieren.',
      steps: [
        ['Zwiebel, Knoblauch, Ingwer, Karotte und Apfel zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Currypulver zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Linsen, Reis und Brühe zugeben und garen.', '12 Min.', '100°C', 'Stufe 1', ''],
        ['Teilweise pürieren.', '15 Sek.', '', 'Stufe 6', ''],
        ['Hähnchenwürfel und Kokosmilch zugeben und garen.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen und mit Joghurt und Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): mild mit wenig Curry und salzfreier Brühe, als dicker Linsen-Hähnchen-Brei – Apfel macht sie natürlich süß. Kleinkind (1–3 J.): Hähnchen klein schneiden, Joghurt einrühren.',
    baby: 2,
  },
  {
    id: 'haehnchen-giouvetsi-kritharaki',
    n: 'Hähnchen-Giouvetsi mit Kritharaki',
    img: { wiki: 'Giouvetsi', q: 'giouvetsi orzo chicken' },
    ck: 'Giouvetsi',
    cu: 'mediterran', m: ['mittag', 'abend'], t: 50, d: 1, st: ['comfort', 'kinderliebling'],
    i: [['haehnchenschenkel', 160], ['nudeln', 60], ['tomaten_dose', 150], ['huehnerbruehe', 200], ['zwiebel', 50], ['knoblauch', 4], ['paprika', 80], ['tomatenmark', 10], ['olivenoel', 8], ['gewuerze', 3], ['zimt', 0.5], ['feta', 15], ['kraeuter', 4]],
    s: [
      'Ofen auf 200 °C (Umluft 180 °C) vorheizen. Hähnchenschenkel in große Stücke schneiden.',
      'Zwiebel, Knoblauch und Paprika würfeln und im Olivenöl in einer ofenfesten Form oder einem Bräter 4 Min. andünsten. Hähnchen zugeben und 4 Min. rundum anbraten.',
      'Tomatenmark, Oregano/Paprikapulver und eine Prise Zimt einrühren, gehackte Tomaten und Brühe angießen, aufkochen. Baby-/Kleinkind-Portion vor dem Salzen entnehmen.',
      'Kritharaki (glutenfrei: glutenfreie Reisnudeln/Orzo-Ersatz) einrühren und alles im Ofen 25–30 Min. garen, bis die Nudeln weich sind und die Flüssigkeit aufgesogen ist. Zwischendurch einmal umrühren.',
      'Mit zerbröseltem Feta und frischen Kräutern bestreuen und servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Sauce im Thermomix, Überbacken im Ofen.',
      steps: [
        ['Zwiebel, Knoblauch und Paprika in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hähnchenstücke, Tomatenmark und Gewürze zugeben und anbraten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Gehackte Tomaten und Brühe zugeben und aufkochen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Salzen entnehmen.', '', '', '', ''],
        ['In eine Auflaufform umfüllen, Kritharaki einrühren und im Ofen bei 200 °C 25–30 Min. garen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Portion ohne Feta, Nudeln weich garen und Hähnchen fein zupfen oder pürieren. Kleinkind (1–3 J.): Hähnchen klein schneiden, Feta nur wenig (salzig).',
    baby: 2,
  },
]);
