// Italienische & mediterrane Hauptgerichte
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  {
    id: 'spaghetti-bolognese',
    n: 'Spaghetti Bolognese',
    img: { wiki: 'Bolognese sauce', q: 'spaghetti bolognese' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    st: ['comfort', 'kinderliebling', 'mealprep'],
    i: [['rinderhack', 150], ['nudeln', 80], ['passierte_tomaten', 150], ['tomatenmark', 15], ['karotte', 40], ['sellerie', 10], ['zwiebel', 40], ['knoblauch', 4], ['olivenoel', 7], ['gewuerze', 2], ['salz', 1], ['parmesan', 8], ['kraeuter', 3]],
    s: [
      'Zwiebel, Karotte und Sellerie sehr fein würfeln, Knoblauch hacken.',
      'Öl in einem Topf erhitzen, Hack bei starker Hitze 5–6 Min. krümelig anbraten, Gemüse zugeben und 4 Min. mitdünsten.',
      'Tomatenmark 1 Min. mitrösten, passierte Tomaten und Oregano zugeben und zugedeckt bei kleiner Hitze 25 Min. köcheln lassen.',
      'Spaghetti in reichlich Wasser nach Packungsangabe al dente kochen.',
      'Baby-/Kleinkind-Portion Sauce jetzt entnehmen, dann den Rest mit Salz und Pfeffer abschmecken.',
      'Spaghetti mit Sauce mischen und mit Parmesan und Basilikum servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Spaghetti halbieren, damit sie in den Mixtopf passen; Nudelwasser für die Baby-Portion nicht salzen.',
      steps: [
        ['Zwiebel, Karotte, Sellerie und Knoblauch in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hack zugeben und krümelig anbraten, dabei ohne Messbecher garen.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomatenmark, passierte Tomaten und Oregano zugeben und köcheln lassen, Garkörbchen als Spritzschutz auf den Deckel stellen.', '25 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Sauce in den Thermoserver umfüllen, Baby-/Kleinkind-Portion entnehmen, Rest mit Salz und Pfeffer abschmecken. Mixtopf ausspülen.', '', '', '', ''],
        ['1,2 l Wasser in den Mixtopf geben und aufkochen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Spaghetti durch die Deckelöffnung zugeben und nach Packungsangabe (ca. 10 Min.) al dente garen, dann abgießen.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Spaghetti mit Sauce mischen und mit Parmesan und Basilikum servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Sauce mit weich gekochten, klein geschnittenen Nudeln fein pürieren oder kurze Nudeln (Fusilli) als Fingerfood mit Sauce anbieten. Kleinkind: Spaghetti in kurze Stücke schneiden, Parmesan nur wenig.',
    baby: 2,
  },
  {
    id: 'protein-lasagne',
    n: 'Protein-Lasagne',
    img: { wiki: 'Lasagne', q: 'lasagna bolognese slice' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 75, d: 2,
    st: ['comfort', 'mealprep', 'kinderliebling'],
    i: [['rinderhack', 120], ['lasagneplatten', 60], ['passierte_tomaten', 150], ['tomatenmark', 10], ['zwiebel', 30], ['karotte', 30], ['knoblauch', 4], ['olivenoel', 5], ['magerquark', 100], ['milch', 50], ['mozzarella', 40], ['parmesan', 8], ['gewuerze', 2], ['salz', 1]],
    s: [
      'Zwiebel, Karotte und Knoblauch fein würfeln und im Öl 3 Min. andünsten. Hack zugeben und 5 Min. krümelig braten.',
      'Tomatenmark kurz anrösten, passierte Tomaten und Oregano zugeben und 15 Min. köcheln lassen. Baby-Portion vor dem Salzen abnehmen, dann würzen.',
      'Für die Protein-Béchamel Magerquark mit Milch, Parmesan und einer Prise Muskat glatt rühren.',
      'Ofen auf 180 °C Umluft vorheizen. In eine Form abwechselnd Sauce, Lasagneplatten und Quarkcreme schichten, mit Sauce abschließen.',
      'Mit Mozzarella belegen und 35–40 Min. backen, bis die Oberfläche goldbraun ist. 10 Min. ruhen lassen, dann schneiden.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Sauce und Protein-Béchamel im Thermomix, Backen im Ofen.',
      steps: [
        ['Parmesan in den Mixtopf geben, zerkleinern und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Zwiebel, Karotte und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hack zugeben und krümelig anbraten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomatenmark, passierte Tomaten und Oregano zugeben und köcheln lassen.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Sauce umfüllen, Baby-Portion vor dem Salzen abnehmen, Rest würzen. Mixtopf ausspülen.', '', '', '', ''],
        ['Magerquark, Milch, Parmesan und eine Prise Muskat in den Mixtopf geben und glatt rühren.', '20 Sek.', '', 'Stufe 4', ''],
        ['Im Ofen bei 180 °C Umluft abwechselnd Sauce, Lasagneplatten und Quarkcreme schichten, mit Mozzarella belegen und 35–40 Min. backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ein Stück aus der salzarmen Ecke nehmen, mit der Gabel zerdrücken oder in fingerdicke Streifen schneiden (BLW). Kleinkind: in kleine Würfel schneiden und gut abkühlen lassen.',
    baby: 2,
  },
  {
    id: 'penne-lachs-spinat',
    n: 'Penne mit Lachs & Spinat',
    img: { file: 'Pasta with cold-smoked salmon and peas in Loviisa.jpg', wiki: 'Penne', q: 'penne salmon spinach cream sauce' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling'],
    i: [['nudeln', 75], ['lachs', 130], ['spinat', 80], ['frischkaese_light', 30], ['milch', 60], ['knoblauch', 4], ['zitrone', 10], ['parmesan', 5], ['olivenoel', 4], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Penne nach Packungsangabe in Salzwasser al dente kochen (für das Baby einen Teil in ungesalzenem Wasser garen).',
      'Lachs in 2 cm große Würfel schneiden. Öl erhitzen, Lachs 3–4 Min. rundum braten und herausnehmen.',
      'Knoblauch in der Pfanne 30 Sek. anschwitzen, Milch und Frischkäse einrühren und 2 Min. leise köcheln lassen.',
      'Spinat zugeben und zusammenfallen lassen, Lachs wieder unterheben. Baby-Portion entnehmen.',
      'Rest mit Zitronensaft, Salz und Pfeffer abschmecken, mit den Penne mischen und mit Parmesan und Dill servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Für das Baby einen Teil der Penne vorab in ungesalzenem Wasser garen oder das Kochwasser gar nicht salzen.',
      steps: [
        ['Parmesan in den Mixtopf geben, zerkleinern und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['1,2 l Wasser in den Mixtopf geben und aufkochen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Penne zugeben und nach Packungsangabe al dente garen, abgießen und im Thermoserver warm halten.', '11 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl zugeben und andünsten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Milch und Frischkäse zugeben und erhitzen.', '3 Min.', '90°C', 'Stufe 2', ''],
        ['Lachswürfel und Spinat zugeben und gar ziehen lassen, bis der Lachs durchgegart ist.', '6 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen.', '', '', '', ''],
        ['Rest mit Zitronensaft, Salz und Pfeffer abschmecken, mit den Penne mischen und mit Parmesan und Dill servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Lachs auf Gräten prüfen, durchgaren und zerpflücken, mit weichen Penne und gehacktem Spinat in der Sauce anbieten oder pürieren. Kleinkind: Penne halbieren, Spinat fein hacken.',
    baby: 2,
  },
  {
    id: 'pesto-pasta-haehnchen',
    n: 'Pesto-Pasta mit Hähnchen',
    img: { file: 'Pasta al pesto fatto in casa.jpg', wiki: 'Pesto', q: 'pesto pasta chicken' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 20, d: 1,
    st: ['kinderliebling', 'mealprep'],
    i: [['nudeln', 85], ['haehnchenbrust', 150], ['pesto', 20], ['kirschtomaten', 80], ['rucola', 20], ['parmesan', 8], ['olivenoel', 3], ['salz', 0.5]],
    s: [
      'Nudeln nach Packungsangabe al dente kochen, 3 EL Kochwasser auffangen.',
      'Hähnchen in Streifen schneiden. Öl erhitzen und das Hähnchen 6–7 Min. goldbraun und durchgaren.',
      'Kirschtomaten halbieren und 1 Min. in der Pfanne mitschwenken. Baby-Portion (Nudeln, Hähnchen, Tomate) jetzt ohne Pesto entnehmen.',
      'Nudeln mit Pesto und etwas Kochwasser cremig mischen, Hähnchen unterheben und leicht salzen.',
      'Mit Rucola und Parmesan anrichten.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Das Hähnchen gart im Varoma, während die Nudeln kochen.',
      steps: [
        ['Parmesan in den Mixtopf geben, zerkleinern und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['1,5 l Wasser in den Mixtopf geben. Hähnchenstreifen im Varoma-Behälter verteilen, aufsetzen und vorgaren.', '10 Min.', 'Varoma', 'Stufe 1', ''],
        ['Varoma kurz abnehmen, Nudeln in den Mixtopf geben, Varoma wieder aufsetzen und nach Packungsangabe garen. Kirschtomaten in den letzten 2 Min. in den Varoma legen.', '10 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['3 EL Kochwasser auffangen, Nudeln abgießen. Baby-Portion (Nudeln, Hähnchen, Tomate) ohne Pesto entnehmen.', '', '', '', ''],
        ['Nudeln, Pesto, Kochwasser und Hähnchen in den Mixtopf geben, cremig vermischen und leicht salzen.', '30 Sek.', '', 'Sanftrührstufe', 'Linkslauf'],
        ['Mit Rucola und Parmesan anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Nudeln mit zerdrückten Tomaten und gezupftem Hähnchen ohne Pesto (salzig, Nüsse) anbieten; Hähnchen in langen Streifen als Fingerfood. Kleinkind: wenig Pesto, Kirschtomaten unbedingt vierteln.',
    baby: 2,
  },
  {
    id: 'gnocchi-tomate-mozzarella',
    n: 'Gnocchi mit Tomate & Mozzarella',
    img: { file: 'Gnocchi al pomodoro 2.jpg', wiki: 'Gnocchi', q: 'gnocchi alla sorrentina tomato mozzarella' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['comfort', 'kinderliebling'],
    i: [['gnocchi', 200], ['mozzarella', 125], ['passierte_tomaten', 200], ['spinat', 50], ['parmesan', 8], ['zwiebel', 30], ['knoblauch', 4], ['olivenoel', 5], ['kraeuter', 4], ['gewuerze', 1]],
    s: [
      'Ofen auf 220 °C Oberhitze/Grill vorheizen. Zwiebel und Knoblauch fein würfeln und im Öl 3 Min. andünsten.',
      'Passierte Tomaten und Oregano zugeben und 8 Min. köcheln lassen, Spinat unterrühren.',
      'Gnocchi direkt in der Sauce 3–4 Min. garen. Baby-Portion entnehmen, Rest mit Pfeffer abschmecken.',
      'In eine Auflaufform geben, mit zerzupftem Mozzarella und Parmesan belegen.',
      '8–10 Min. überbacken, bis der Käse blubbert. Mit Basilikum servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt, der Mixtopf ist dann gut gefüllt. Überbacken im Ofen.',
      steps: [
        ['Parmesan in den Mixtopf geben, zerkleinern und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Passierte Tomaten und Oregano zugeben und köcheln lassen.', '8 Min.', '100°C', 'Stufe 1', ''],
        ['Spinat und Gnocchi zugeben und in der Sauce garen.', '5 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen, Rest mit Pfeffer abschmecken.', '', '', '', ''],
        ['In eine Auflaufform füllen, mit zerzupftem Mozzarella und Parmesan belegen und bei 220 °C Oberhitze/Grill 8–10 Min. überbacken. Mit Basilikum servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Gnocchi längs halbieren oder zerdrücken, mit Tomatensauce und etwas weichem Mozzarella anbieten (Gnocchi enthalten Salz, daher kleine Menge). Kleinkind: Gnocchi halbieren, Käse gut abkühlen lassen.',
    baby: 1,
  },
  {
    id: 'spinat-ricotta-cannelloni',
    n: 'Spinat-Ricotta-Cannelloni',
    img: { wiki: 'Cannelloni', q: 'spinach ricotta cannelloni' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 60, d: 2,
    st: ['comfort', 'mealprep'],
    i: [['lasagneplatten', 60], ['ricotta', 40], ['magerquark', 120], ['spinat_tk', 150], ['ei', 30], ['parmesan', 10], ['mozzarella', 40], ['passierte_tomaten', 200], ['zwiebel', 30], ['knoblauch', 4], ['olivenoel', 3], ['gewuerze', 2], ['salz', 1]],
    s: [
      'Spinat auftauen, sehr gut ausdrücken und fein hacken. Mit Ricotta, Quark, Ei, der Hälfte Parmesan und Muskat verrühren.',
      'Zwiebel und Knoblauch im Öl 3 Min. andünsten, passierte Tomaten zugeben und 10 Min. köcheln. Baby-Portion abnehmen, dann salzen.',
      'Lasagneplatten 2 Min. in kochendem Wasser einweichen, mit der Füllung bestreichen und aufrollen.',
      'Ofen auf 180 °C Umluft vorheizen. Die Hälfte der Sauce in eine Form geben, Röllchen nebeneinander einlegen, restliche Sauce darüber.',
      'Mit Mozzarella und restlichem Parmesan bestreuen und 30–35 Min. backen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Füllung und Sauce im Thermomix, Backen im Ofen.',
      steps: [
        ['Parmesan in den Mixtopf geben, zerkleinern und die Hälfte umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Gut ausgedrückten Spinat, Ricotta, Quark, Ei und Muskat zugeben, zu einer Füllung verrühren und umfüllen.', '20 Sek.', '', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Passierte Tomaten zugeben und köcheln lassen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Baby-Portion Sauce abnehmen, Rest salzen.', '', '', '', ''],
        ['Lasagneplatten 2 Min. in kochendem Wasser einweichen, mit der Füllung bestreichen und aufrollen.', '', '', '', ''],
        ['Röllchen mit der Sauce in eine Form schichten, mit Mozzarella und restlichem Parmesan bestreuen und bei 180 °C Umluft 30–35 Min. backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ein Röllchen mit ungesalzener Sauce in Scheiben schneiden oder zerdrücken – die weiche Spinat-Ricotta-Füllung ist ideal für BLW. Kleinkind: in Stücke schneiden, Füllung abkühlen lassen.',
    baby: 2,
  },
  {
    id: 'haehnchen-erbsen-risotto',
    n: 'Hähnchen-Erbsen-Risotto',
    img: { wiki: 'Risotto', q: 'chicken pea risotto' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort', 'kinderliebling'],
    i: [['risottoreis', 75], ['haehnchenbrust', 150], ['erbsen', 80], ['zwiebel', 40], ['huehnerbruehe', 300], ['parmesan', 12], ['olivenoel', 7], ['butter', 5], ['zitrone', 10], ['kraeuter', 3], ['salz', 0.5]],
    s: [
      'Hähnchen würfeln und in der Hälfte des Öls 5–6 Min. durchbraten, herausnehmen.',
      'Zwiebel fein würfeln und im restlichen Öl glasig dünsten, Reis zugeben und 1 Min. glasig rühren.',
      'Heiße Brühe nach und nach angießen und unter Rühren 18–20 Min. garen, bis der Reis cremig, aber bissfest ist.',
      'Erbsen in den letzten 4 Min. zugeben, Hähnchen unterheben. Baby-Portion vor Parmesan und Salz entnehmen.',
      'Butter, Parmesan und Zitronenabrieb unterrühren, 2 Min. ruhen lassen und mit Petersilie servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt, der Mixtopf ist dann sehr voll – max. 1 l Brühe verwenden. Für das Baby salzfreie Brühe nehmen.',
      steps: [
        ['Parmesan in den Mixtopf geben, zerkleinern und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Zwiebel in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Risottoreis zugeben und ohne Messbecher glasig dünsten.', '2 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Hähnchenwürfel und heiße Brühe zugeben und garen, Garkörbchen als Spritzschutz auf den Deckel stellen.', '14 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Erbsen zugeben und fertig garen.', '4 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion vor Parmesan und Salz entnehmen.', '', '', '', ''],
        ['Butter, Parmesan und Zitronenabrieb zugeben und unterrühren, 2 Min. ruhen lassen und mit Petersilie servieren.', '30 Sek.', '', 'Sanftrührstufe', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): mit salzfreier Brühe zubereitete Portion grob pürieren oder als weiche Risotto-Bällchen formen; Erbsen zerdrücken. Kleinkind: Erbsen leicht andrücken, Hähnchen klein schneiden.',
    baby: 2,
  },
  {
    id: 'pasta-primavera-garnelen',
    n: 'Pasta Primavera mit Garnelen',
    img: { wiki: 'Pasta primavera', q: 'pasta primavera shrimp' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['nudeln', 85], ['garnelen', 150], ['zucchini', 65], ['spargel', 60], ['erbsen', 40], ['kirschtomaten', 60], ['knoblauch', 4], ['olivenoel', 10], ['parmesan', 10], ['zitrone', 10], ['kraeuter', 4], ['salz', 0.5]],
    s: [
      'Nudeln al dente kochen, Spargel in den letzten 3 Min. und Erbsen in der letzten Minute mitgaren. 50 ml Kochwasser auffangen.',
      'Zucchini in Halbmonde schneiden und in der Hälfte des Öls 4 Min. braten.',
      'Garnelen mit Knoblauch im restlichen Öl 2–3 Min. braten, bis sie rosa und durchgegart sind. Kirschtomaten halbiert zugeben.',
      'Nudeln und Gemüse mit Kochwasser untermischen. Baby-Portion entnehmen.',
      'Mit Zitronensaft, Salz, Pfeffer und Parmesan abschmecken und mit Basilikum servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Gemüse und Garnelen garen im Varoma, während die Nudeln kochen.',
      steps: [
        ['Parmesan in den Mixtopf geben, zerkleinern und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['1,5 l Wasser in den Mixtopf geben und aufkochen.', '10 Min.', 'Varoma', 'Stufe 1', ''],
        ['Nudeln zugeben. Zucchini und Spargelstücke in den Varoma-Behälter, Garnelen auf den Einlegeboden legen, Varoma aufsetzen und garen, bis die Garnelen rosa und durchgegart sind. Erbsen in der letzten Minute in den Mixtopf geben.', '11 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['50 ml Kochwasser auffangen, Nudeln abgießen.', '', '', '', ''],
        ['Knoblauch in den Mixtopf geben und zerkleinern, Öl zugeben und andünsten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Nudeln, Gemüse, Garnelen, halbierte Kirschtomaten und Kochwasser zugeben und vermischen.', '1 Min.', '90°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen.', '', '', '', ''],
        ['Mit Zitronensaft, Salz, Pfeffer und Parmesan abschmecken und mit Basilikum servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Garnelen vollständig durchgaren und fein hacken, mit weichen Nudeln und Zucchini anbieten (Krebstiere einzeln einführen). Kleinkind: Garnelen in Stücke schneiden, Tomaten vierteln.',
    baby: 1,
  },
  {
    id: 'minestrone-weisse-bohnen',
    n: 'Minestrone mit weißen Bohnen',
    img: { file: 'Liat Portal for Foodie Disorder - Homemade minestrone soup.jpg', wiki: 'Minestrone', q: 'minestrone soup white beans' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    st: ['mealprep', 'comfort'],
    i: [['weisse_bohnen', 160], ['linsennudeln', 50], ['zucchini', 65], ['karotte', 50], ['sellerie', 10], ['kartoffel', 80], ['tomaten_dose', 150], ['zwiebel', 40], ['knoblauch', 4], ['gemuesebruehe', 350], ['olivenoel', 8], ['parmesan', 20], ['kraeuter', 4], ['gewuerze', 1]],
    s: [
      'Zwiebel, Karotte, Sellerie und Kartoffel in kleine Würfel schneiden, Knoblauch hacken.',
      'Öl im Topf erhitzen, Zwiebel, Knoblauch, Karotte und Sellerie 5 Min. andünsten.',
      'Kartoffeln, Tomaten und Brühe zugeben, aufkochen und 15 Min. köcheln lassen.',
      'Zucchini, abgespülte Bohnen und Nudeln zugeben und weitere 8–10 Min. garen, bis die Nudeln weich sind.',
      'Baby-Portion (mit salzfreier Brühe gekocht) entnehmen. Rest mit Pfeffer abschmecken und mit Parmesan und Basilikum servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für 4 Portionen ist die Menge zu groß für einen Mixtopf (max. 2,2 l): in zwei Durchgängen kochen oder Menge halbieren. Für das Baby salzfreie Brühe verwenden.',
      steps: [
        ['Parmesan in den Mixtopf geben, zerkleinern und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Zwiebel, Karotte, Sellerie und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Kartoffelwürfel, Tomaten und Brühe zugeben und köcheln lassen.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Zucchiniwürfel, abgespülte Bohnen und Nudeln zugeben und garen, bis die Nudeln weich sind.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-Portion entnehmen.', '', '', '', ''],
        ['Rest mit Pfeffer abschmecken und mit Parmesan und Basilikum servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Suppe stückig pürieren oder Gemüse und Bohnen abgießen und zerdrückt bzw. als weiche Stücke anbieten. Kleinkind: Bohnen leicht andrücken, Suppe dicklich servieren.',
    baby: 2,
  },
  {
    id: 'protein-pizza-margherita-haehnchen',
    n: 'Protein-Pizza Margherita mit Hähnchen',
    img: { wiki: 'Pizza Margherita', q: 'pizza margherita chicken' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['kinderliebling', 'comfort'],
    i: [['pizzateig', 150], ['passierte_tomaten', 60], ['mozzarella', 80], ['haehnchenbrust', 100], ['olivenoel', 3], ['gewuerze', 1], ['kraeuter', 4]],
    s: [
      'Ofen mit Blech auf 250 °C Ober-/Unterhitze vorheizen.',
      'Hähnchen in dünne Streifen schneiden und in einer Pfanne mit dem Öl 4–5 Min. durchbraten.',
      'Pizzateig ausrollen, mit passierten Tomaten und Oregano bestreichen.',
      'Mit zerzupftem Mozzarella und Hähnchen belegen und 10–12 Min. knusprig backen.',
      'Mit frischem Basilikum belegen und in Stücke schneiden.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Hähnchen und Tomatensauce im Thermomix, die Pizza backt im Ofen.',
      steps: [
        ['Ofen mit Blech auf 250 °C Ober-/Unterhitze vorheizen.', '', '', '', ''],
        ['500 ml Wasser in den Mixtopf geben. Hähnchenstreifen in den Varoma-Behälter legen, aufsetzen und durchgaren.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Mixtopf leeren. Passierte Tomaten, Oregano und Öl in den Mixtopf geben und leicht einkochen lassen.', '5 Min.', '100°C', 'Stufe 2', ''],
        ['Pizzateig ausrollen und mit der Tomatensauce bestreichen.', '', '', '', ''],
        ['Mit zerzupftem Mozzarella und Hähnchen belegen und 10–12 Min. knusprig backen.', '', '', '', ''],
        ['Mit frischem Basilikum belegen und in Stücke schneiden.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Pizzarand ist salzig – kleine, weiche Streifen aus der Mitte ohne harten Rand anbieten, Hähnchen gezupft. Kleinkind: in schmale Streifen schneiden, Käse vorher abkühlen lassen.',
    baby: 1,
  },
  {
    id: 'haehnchen-cacciatore',
    n: 'Hähnchen Cacciatore',
    img: { wiki: 'Cacciatore', q: 'chicken cacciatore polenta' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 50, d: 2,
    st: ['comfort', 'mealprep'],
    i: [['haehnchenschenkel', 200], ['tomaten_dose', 200], ['paprika', 100], ['champignons', 80], ['zwiebel', 50], ['knoblauch', 8], ['oliven', 15], ['olivenoel', 8], ['gewuerze', 2], ['salz', 1], ['kraeuter', 4], ['polenta', 50]],
    s: [
      'Hähnchenschenkel salzfrei mit Rosmarin und Pfeffer einreiben und im Öl in einem Schmortopf 3 Min. pro Seite anbraten, herausnehmen.',
      'Zwiebel, Paprika und Champignons in Streifen schneiden und im Bratfett 5 Min. braten, Knoblauch 1 Min. mitbraten.',
      'Tomaten zugeben, Hähnchen hineinlegen und zugedeckt 25 Min. bei kleiner Hitze schmoren.',
      'Polenta in 200 ml kochendes Wasser einrieseln lassen und unter Rühren 5–8 Min. quellen lassen.',
      'Baby-Portion entnehmen, dann Oliven zugeben und mit Salz abschmecken. Auf der Polenta mit Petersilie servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Die Schenkel werden in der Pfanne angebraten und geschmort, Sauce und Polenta kommen aus dem Thermomix.',
      steps: [
        ['Hähnchenschenkel mit Rosmarin und Pfeffer einreiben und in einem Schmortopf in etwas Öl 3 Min. pro Seite anbraten.', '', '', '', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Restliches Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Paprika- und Champignonstreifen zugeben und dünsten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomaten zugeben und köcheln lassen.', '8 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Sauce über die Schenkel in den Schmortopf gießen und zugedeckt 25 Min. bei kleiner Hitze schmoren. Mixtopf ausspülen.', '', '', '', ''],
        ['800 ml Wasser in den Mixtopf geben und aufkochen.', '8 Min.', '100°C', 'Stufe 1', ''],
        ['Polenta durch die Deckelöffnung einrieseln lassen und quellen lassen.', '6 Min.', '100°C', 'Stufe 2', 'Linkslauf'],
        ['Baby-Portion entnehmen, dann Oliven zugeben und mit Salz abschmecken. Auf der Polenta mit Petersilie servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): zartes Schenkelfleisch zerzupfen, mit weicher Polenta und Tomatensauce mischen oder Polenta abgekühlt in Sticks schneiden. Kleinkind: Oliven weglassen oder fein hacken, Fleisch klein schneiden.',
    baby: 2,
  },
  {
    id: 'polpette-tomatensauce',
    n: 'Polpette (Hackbällchen in Tomatensauce)',
    img: { file: 'Spaghetti and meatballs 1.jpg', wiki: 'Meatball', q: 'italian polpette meatballs tomato sauce' },
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['kinderliebling', 'mealprep', 'comfort'],
    i: [['rinderhack', 150], ['paniermehl', 15], ['ei', 20], ['parmesan', 10], ['passierte_tomaten', 200], ['zwiebel', 30], ['knoblauch', 4], ['olivenoel', 7], ['kraeuter', 4], ['gewuerze', 1], ['salz', 1], ['nudeln', 60]],
    s: [
      'Hack mit Paniermehl, Ei, Parmesan, gehackter Petersilie und der Hälfte des Knoblauchs verkneten, walnussgroße Bällchen formen.',
      'Bällchen im Öl rundum 5 Min. anbraten und herausnehmen.',
      'Zwiebel und restlichen Knoblauch im Bratfett andünsten, passierte Tomaten und Oregano zugeben.',
      'Bällchen in die Sauce legen und zugedeckt 15 Min. sanft köcheln lassen. Baby-Portion entnehmen, Rest salzen.',
      'Nudeln al dente kochen und mit den Polpette und Basilikum servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Die Polpette werden im Varoma gedämpft statt angebraten; wer Röstaromen mag, brät sie vorher kurz in der Pfanne an.',
      steps: [
        ['Parmesan in den Mixtopf geben und zerkleinern.', '10 Sek.', '', 'Stufe 10', ''],
        ['Petersilie und die Hälfte des Knoblauchs zugeben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Hack, Paniermehl und Ei zugeben und vermengen. Walnussgroße Bällchen formen und in den gefetteten Varoma-Behälter legen.', '20 Sek.', '', 'Stufe 4', 'Linkslauf'],
        ['Zwiebel und restlichen Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Passierte Tomaten, 150 ml Wasser und Oregano zugeben, Varoma aufsetzen und Sauce und Bällchen garen.', '20 Min.', 'Varoma', 'Stufe 1', ''],
        ['Bällchen in die Sauce geben, alles in den Thermoserver umfüllen. Baby-Portion entnehmen, Rest salzen. Mixtopf ausspülen.', '', '', '', ''],
        ['1,2 l Wasser in den Mixtopf geben und aufkochen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Nudeln zugeben und nach Packungsangabe al dente garen, abgießen und mit Polpette und Basilikum servieren.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Bällchen ohne Salz etwas länglich formen (gut greifbar) und weich schmoren, alternativ zerdrücken. Kleinkind: Bällchen halbieren, mit Sauce zum Dippen.',
    baby: 2,
  },
  {
    id: 'ratatouille-haehnchen',
    n: 'Ratatouille mit Hähnchen',
    img: { wiki: 'Ratatouille', q: 'ratatouille chicken' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    st: ['mealprep'],
    i: [['haehnchenbrust', 160], ['aubergine', 120], ['zucchini', 65], ['paprika', 120], ['tomaten_dose', 150], ['zwiebel', 50], ['knoblauch', 8], ['olivenoel', 12], ['kraeuter', 4], ['gewuerze', 2], ['salz', 1], ['reis', 60]],
    s: [
      'Aubergine, Zucchini, Paprika und Zwiebel in 2 cm große Würfel schneiden, Knoblauch hacken.',
      'Hähnchen würfeln und in einem Drittel des Öls 5–6 Min. braten, herausnehmen.',
      'Aubergine im restlichen Öl 5 Min. anbraten, Zwiebel, Paprika und Zucchini zugeben und 5 Min. weiterbraten.',
      'Tomaten, Knoblauch und Kräuter der Provence zugeben, 20 Min. schmoren, Hähnchen in den letzten 5 Min. zugeben. Reis parallel garen.',
      'Baby-Portion entnehmen, Rest mit Salz und Pfeffer abschmecken und mit Basilikum servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für 4 Portionen ist die Gemüsemenge zu groß für einen Mixtopf: in zwei Durchgängen garen oder Menge halbieren. Reis vorab im Garkörbchen garen und im Thermoserver warm halten.',
      steps: [
        ['1 l Wasser in den Mixtopf geben, Reis im Garkörbchen einhängen und garen. Reis im Thermoserver warm halten, Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Aubergine, Paprika und Zucchini in 2 cm großen Würfeln zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomaten und Kräuter der Provence zugeben. Hähnchen in Scheiben im Varoma-Behälter verteilen, aufsetzen und alles garen.', '20 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Hähnchen unter das Gemüse heben. Baby-Portion entnehmen.', '', '', '', ''],
        ['Rest mit Salz und Pfeffer abschmecken und mit Reis und Basilikum servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): weich geschmortes Gemüse und Hähnchen grob pürieren oder als weiche Stücke mit Reis anbieten. Kleinkind: alles klein würfeln, Reis zum Mischen dazu.',
    baby: 2,
  },
  {
    id: 'paella-haehnchen-garnelen',
    n: 'Paella mit Hähnchen & Garnelen',
    img: { wiki: 'Paella', q: 'paella chicken shrimp' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['comfort'],
    i: [['risottoreis', 75], ['haehnchenbrust', 100], ['garnelen', 80], ['paprika', 80], ['erbsen', 40], ['tomate', 60], ['zwiebel', 40], ['knoblauch', 4], ['huehnerbruehe', 250], ['olivenoel', 10], ['gewuerze', 2], ['zitrone', 15], ['salz', 0.5]],
    s: [
      'Hähnchen würfeln und im Öl in einer großen Pfanne 4 Min. anbraten. Zwiebel, Paprika und Knoblauch zugeben und 3 Min. braten.',
      'Gewürfelte Tomate, Paprikapulver und Safran zugeben, Reis einstreuen und 1 Min. mitrösten.',
      'Heiße Brühe angießen, einmal umrühren und 18 Min. ohne Rühren bei mittlerer Hitze garen.',
      'Garnelen und Erbsen in den Reis drücken und zugedeckt 5–6 Min. garen, bis die Garnelen durch sind.',
      'Baby-Portion entnehmen, Rest leicht salzen, 5 Min. ruhen lassen und mit Zitronenspalten servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt, der Mixtopf ist dann randvoll – ggf. in zwei Durchgängen kochen. Im Thermomix wird die Paella cremiger, ohne Kruste am Boden. Für das Baby salzfreie Brühe verwenden.',
      steps: [
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Hähnchenwürfel zugeben und anbraten.', '4 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Paprikastreifen, gewürfelte Tomate, Paprikapulver, Safran und Reis zugeben und ohne Messbecher mitdünsten.', '2 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Heiße Brühe zugeben und garen, Garkörbchen als Spritzschutz auf den Deckel stellen.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Garnelen und Erbsen zugeben und garen, bis die Garnelen durch sind.', '5 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-Portion entnehmen.', '', '', '', ''],
        ['Rest leicht salzen, 5 Min. ruhen lassen und mit Zitronenspalten servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): mit salzfreier Brühe gekochten Reis mit fein gezupftem Hähnchen und zerdrückten Erbsen anbieten; Garnelen nur gut durchgegart und gehackt. Kleinkind: Garnelen klein schneiden.',
    baby: 1,
  },
  {
    id: 'griechischer-haehnchensalat',
    n: 'Griechischer Hähnchensalat',
    img: { wiki: 'Greek salad', q: 'greek salad grilled chicken' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 20, d: 1,
    st: ['mealprep'],
    i: [['haehnchenbrust', 170], ['salat', 80], ['gurke', 100], ['tomate', 100], ['paprika', 60], ['rote_zwiebel', 20], ['oliven', 20], ['feta', 40], ['olivenoel', 10], ['essig', 5], ['gewuerze', 1], ['zitrone', 10], ['pitabrot', 60]],
    s: [
      'Hähnchen mit Oregano und Zitronensaft marinieren und in 1 TL Öl 6–7 Min. pro Seite durchbraten, 3 Min. ruhen lassen und in Streifen schneiden.',
      'Salat, Gurke, Tomate und Paprika in mundgerechte Stücke schneiden, rote Zwiebel in feine Ringe.',
      'Restliches Öl mit Essig, Oregano und Pfeffer zu einem Dressing verrühren.',
      'Baby-Portion (Gurke, Tomate, Hähnchen) ohne Feta und Oliven abnehmen.',
      'Salat mit Dressing mischen, mit Feta, Oliven und Hähnchen belegen und mit Pita servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Der Thermomix übernimmt hier nur das Dressing; Hähnchen in der Pfanne braten, Gemüse von Hand schneiden.',
      steps: [
        ['Hähnchen mit Oregano und Zitronensaft marinieren, in 1 TL Öl in der Pfanne 6–7 Min. pro Seite durchbraten, 3 Min. ruhen lassen und in Streifen schneiden.', '', '', '', ''],
        ['Restliches Öl, Essig, Oregano und Pfeffer in den Mixtopf geben und zu einem Dressing verrühren.', '10 Sek.', '', 'Stufe 4', ''],
        ['Salat, Gurke, Tomate und Paprika in mundgerechte Stücke schneiden, rote Zwiebel in feine Ringe.', '', '', '', ''],
        ['Baby-Portion (Gurke, Tomate, Hähnchen) ohne Feta und Oliven abnehmen.', '', '', '', ''],
        ['Salat mit Dressing mischen, mit Feta, Oliven und Hähnchen belegen und mit Pita servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchenstreifen, geschälte Gurkensticks und weiche Tomatenspalten als Fingerfood, Pita in Streifen; Feta und Oliven weglassen (salzig). Kleinkind: wenig Feta, Oliven fein hacken.',
    baby: 1,
  },
  {
    id: 'haehnchen-souvlaki-tzatziki',
    n: 'Hähnchen-Souvlaki mit Tzatziki',
    img: { wiki: 'Souvlaki', q: 'chicken souvlaki tzatziki pita' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['kinderliebling', 'mealprep'],
    i: [['haehnchenbrust', 170], ['olivenoel', 8], ['zitrone', 15], ['gewuerze', 2], ['knoblauch', 4], ['griech_joghurt', 100], ['gurke', 60], ['pitabrot', 70], ['tomate', 60], ['rote_zwiebel', 15], ['salat', 30], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Hähnchen in 3 cm große Würfel schneiden, mit Öl, Zitronensaft, Oregano und der Hälfte des Knoblauchs 20 Min. marinieren.',
      'Für das Tzatziki Gurke raspeln und ausdrücken, mit Joghurt, restlichem Knoblauch und Dill verrühren.',
      'Hähnchen auf Spieße stecken und in der Grillpfanne 10–12 Min. rundum durchgaren. Baby-Portion vor dem Salzen abnehmen.',
      'Pita im Ofen oder in der Pfanne 1 Min. pro Seite erwärmen.',
      'Spieße mit Tzatziki, Tomate, Zwiebel und Salat in der Pita servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Der Thermomix übernimmt Marinade und Tzatziki; die Spieße werden in der Grillpfanne gegart.',
      steps: [
        ['Die Hälfte des Knoblauchs in den Mixtopf geben und zerkleinern, Öl, Zitronensaft und Oregano zugeben und verrühren.', '5 Sek.', '', 'Stufe 5', ''],
        ['Hähnchenwürfel mit der Marinade mischen und 20 Min. ziehen lassen. Mixtopf ausspülen.', '', '', '', ''],
        ['Restlichen Knoblauch und Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Gurke in Stücken zugeben, zerkleinern und anschließend gut ausdrücken.', '4 Sek.', '', 'Stufe 5', ''],
        ['Joghurt zugeben und zum Tzatziki verrühren.', '10 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Hähnchen auf Spieße stecken und in der Grillpfanne 10–12 Min. rundum durchgaren. Baby-Portion vor dem Salzen abnehmen.', '', '', '', ''],
        ['Pita kurz erwärmen und mit Spießen, Tzatziki, Tomate, Zwiebel und Salat servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen vom Spieß nehmen, in Streifen schneiden und in Joghurt (ohne Knoblauch) dippen; Pita in Streifen, Gurke als Stick. Kleinkind: Hähnchen in kleine Stücke, Tzatziki mild.',
    baby: 2,
  },
  {
    id: 'leichte-moussaka',
    n: 'Leichte Moussaka',
    img: { wiki: 'Moussaka', q: 'greek moussaka' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 80, d: 2,
    st: ['comfort', 'mealprep'],
    i: [['aubergine', 200], ['rinderhack', 140], ['kartoffel', 120], ['tomaten_dose', 150], ['zwiebel', 40], ['knoblauch', 4], ['olivenoel', 10], ['gewuerze', 2], ['vanille', 1], ['milch', 100], ['speisestaerke', 8], ['ei', 20], ['parmesan', 12], ['salz', 1]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Aubergine und Kartoffeln in 1 cm dicke Scheiben schneiden, mit der Hälfte des Öls bepinseln und 20 Min. auf dem Blech vorbacken.',
      'Zwiebel und Knoblauch im restlichen Öl andünsten, Hack 5 Min. krümelig braten. Tomaten, Oregano und Zimt zugeben und 15 Min. köcheln. Baby-Portion abnehmen, Rest salzen.',
      'Für die leichte Béchamel Milch mit Stärke aufkochen, vom Herd nehmen, Ei und die Hälfte Parmesan einrühren.',
      'In eine Form schichten: Kartoffeln, Aubergine, Hacksauce, nochmals Aubergine. Béchamel darübergießen und mit restlichem Parmesan bestreuen.',
      'Bei 180 °C 30–35 Min. goldbraun backen und 10 Min. ruhen lassen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Hacksauce und Béchamel im Thermomix, Gemüse vorbacken und Überbacken im Ofen.',
      steps: [
        ['Ofen auf 200 °C Umluft vorheizen. Auberginen- und Kartoffelscheiben mit der Hälfte des Öls bepinseln und 20 Min. auf dem Blech vorbacken.', '', '', '', ''],
        ['Parmesan in den Mixtopf geben, zerkleinern und umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben. Restliches Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hack zugeben und krümelig anbraten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomaten, Oregano und Zimt zugeben und köcheln lassen. Sauce umfüllen, Baby-Portion abnehmen, Rest salzen. Mixtopf ausspülen.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Milch und Stärke in den Mixtopf geben und zur Béchamel aufkochen.', '7 Min.', '90°C', 'Stufe 4', ''],
        ['Kurz abkühlen lassen, Ei und die Hälfte des Parmesans zugeben und unterrühren.', '10 Sek.', '', 'Stufe 4', ''],
        ['Kartoffeln, Aubergine, Hacksauce und Aubergine in eine Form schichten, Béchamel darübergießen, mit Parmesan bestreuen und bei 180 °C 30–35 Min. backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ein Stück aus der ungesalzenen Portion zerdrücken oder in Streifen anbieten – weiche Aubergine und Kartoffel eignen sich gut für BLW. Kleinkind: in kleine Würfel schneiden.',
    baby: 2,
  },
  {
    id: 'gefuellte-paprika-hack-reis',
    n: 'Gefüllte Paprika mit Hack & Reis',
    img: { wiki: 'Stuffed peppers', q: 'stuffed bell peppers ground beef rice' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 60, d: 2,
    st: ['comfort', 'kinderliebling', 'mealprep'],
    i: [['paprika', 320], ['rinderhack', 140], ['reis', 45], ['passierte_tomaten', 150], ['zwiebel', 40], ['knoblauch', 4], ['mozzarella', 30], ['olivenoel', 5], ['gewuerze', 2], ['salz', 1], ['kraeuter', 3]],
    s: [
      'Reis in Wasser 10 Min. vorgaren und abgießen. Ofen auf 180 °C Umluft vorheizen.',
      'Zwiebel und Knoblauch im Öl andünsten, Hack 5 Min. krümelig braten, Reis, Kräuter, Paprikapulver und die Hälfte der passierten Tomaten unterrühren.',
      'Paprika halbieren, entkernen und mit der Masse füllen. Baby-Portion vor dem Salzen abfüllen.',
      'Restliche Tomaten in eine Auflaufform geben, Paprika hineinsetzen, mit Mozzarella bestreuen.',
      'Zugedeckt 25 Min., dann offen 10 Min. backen, bis die Paprika weich ist.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Reis und Füllung im Thermomix, die Paprika garen im Ofen.',
      steps: [
        ['1 l Wasser in den Mixtopf geben, Reis im Garkörbchen einhängen und vorgaren. Reis umfüllen, Mixtopf leeren. Ofen auf 180 °C Umluft vorheizen.', '12 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Hack zugeben und krümelig anbraten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Reis, Kräuter, Paprikapulver und die Hälfte der passierten Tomaten zugeben und vermischen.', '30 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Paprika halbieren, entkernen und füllen. Baby-Portion vor dem Salzen abfüllen.', '', '', '', ''],
        ['Restliche Tomaten in eine Auflaufform geben, Paprika hineinsetzen, mit Mozzarella bestreuen und zugedeckt 25 Min., dann offen 10 Min. backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Füllung herauslöffeln und mit weicher, gehäuteter Paprika zerdrücken oder Paprika in Streifen anbieten. Kleinkind: Paprika klein schneiden, Füllung abkühlen lassen.',
    baby: 2,
  },
  {
    id: 'ofenlachs-zitronenkartoffeln-spargel',
    n: 'Ofenlachs mit Zitronenkartoffeln & Spargel',
    img: { file: 'Սաղմոն ու մակարոն.JPG', wiki: 'Salmon as food', q: 'baked salmon lemon potatoes asparagus' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['kinderliebling'],
    i: [['lachs', 150], ['kartoffel', 250], ['spargel', 150], ['olivenoel', 10], ['zitrone', 30], ['knoblauch', 4], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Kartoffeln in Spalten schneiden, mit 2/3 des Öls, Zitronenabrieb und Knoblauch mischen.',
      'Kartoffeln auf dem Blech 20 Min. backen.',
      'Spargel und Lachs dazulegen, mit restlichem Öl beträufeln und Zitronenscheiben belegen.',
      'Weitere 12–15 Min. backen, bis der Lachs innen glasig-zart und durchgegart ist. Baby-Portion entnehmen.',
      'Rest mit Salz, Pfeffer, Zitronensaft und Dill abschmecken.',
    ],
    tm: {
      fit: 2,
      note: 'Thermomix-Variante: Kartoffeln, Spargel und Lachs werden gedämpft statt gebacken, die Kartoffeln werden also nicht knusprig. Ins Garkörbchen passen ca. 800 g Kartoffeln, den Rest im Varoma mitgaren.',
      steps: [
        ['500 ml Wasser in den Mixtopf geben, Garkörbchen mit Kartoffelspalten einhängen und vorgaren.', '10 Min.', 'Varoma', 'Stufe 1', ''],
        ['Spargel in den Varoma-Behälter legen, Lachs mit Zitronenscheiben auf den Einlegeboden legen, Varoma aufsetzen und dampfgaren, bis der Lachs durchgegart ist.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Baby-Portion entnehmen. Garkörbchen herausnehmen, Mixtopf leeren.', '', '', '', ''],
        ['Knoblauch und Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl, Zitronenabrieb und Zitronensaft zugeben und verrühren.', '5 Sek.', '', 'Stufe 3', ''],
        ['Kartoffeln, Spargel und Lachs anrichten, mit dem Zitronen-Kräuter-Öl beträufeln und mit Salz und Pfeffer abschmecken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Lachs gründlich auf Gräten prüfen und zerpflücken, Kartoffelspalten und weiche Spargelspitzen als Fingerfood oder alles zerdrücken. Kleinkind: Spargel in Stücke, Lachs zerteilen.',
    baby: 2,
  },
  {
    id: 'ofenhaehnchen-feta-erbsen',
    n: 'Mediterranes Ofenhähnchen mit Feta & Erbsen',
    img: { wiki: 'Roast chicken', q: 'mediterranean sheet pan chicken feta' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    st: ['mealprep'],
    i: [['haehnchenbrust', 170], ['kartoffel', 200], ['erbsen', 80], ['kirschtomaten', 100], ['rote_zwiebel', 40], ['feta', 40], ['oliven', 15], ['olivenoel', 10], ['gewuerze', 2], ['zitrone', 10], ['knoblauch', 4]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Kartoffeln würfeln, Zwiebel in Spalten schneiden und mit der Hälfte des Öls und Oregano 15 Min. backen.',
      'Hähnchen mit restlichem Öl, Knoblauch, Paprikapulver und Zitronensaft einreiben und mit den Kirschtomaten aufs Blech geben.',
      '15 Min. backen, dann Erbsen zugeben und weitere 5 Min. garen.',
      'Baby-Portion entnehmen, dann Feta zerbröseln und mit Oliven darüberstreuen.',
      'Noch 3 Min. überbacken und mit frischen Kräutern servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Blechgericht aus dem Ofen; der Thermomix übernimmt nur Marinade und Kräuter.',
      steps: [
        ['Ofen auf 200 °C Umluft vorheizen. Kräuter in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Knoblauch in den Mixtopf geben und zerkleinern, Öl, Zitronensaft, Paprikapulver und Oregano zugeben und zur Marinade verrühren.', '5 Sek.', '', 'Stufe 5', ''],
        ['Kartoffelwürfel und Zwiebelspalten mit der Hälfte der Marinade mischen und 15 Min. backen.', '', '', '', ''],
        ['Hähnchen mit der restlichen Marinade einreiben, mit den Kirschtomaten aufs Blech geben und 15 Min. backen, dann Erbsen zugeben und 5 Min. weitergaren.', '', '', '', ''],
        ['Baby-Portion entnehmen.', '', '', '', ''],
        ['Feta darüberbröseln, Oliven verteilen, 3 Min. überbacken und mit den Kräutern servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchen in Streifen, Kartoffelwürfel und zerdrückte Erbsen ohne Feta/Oliven anbieten. Kleinkind: Kirschtomaten vierteln, wenig Feta.',
    baby: 2,
  },
  {
    id: 'thunfisch-nudelsalat',
    n: 'Thunfisch-Nudelsalat',
    img: { wiki: 'Pasta salad', q: 'tuna pasta salad' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 20, d: 1,
    st: ['mealprep'],
    i: [['nudeln', 75], ['thunfisch_dose', 120], ['kirschtomaten', 80], ['gurke', 80], ['paprika', 60], ['mais', 30], ['rote_zwiebel', 20], ['rucola', 20], ['griech_joghurt', 60], ['mayo_light', 10], ['zitrone', 10], ['olivenoel', 5], ['kraeuter', 4], ['salz', 1]],
    s: [
      'Nudeln nach Packungsangabe al dente kochen, kalt abschrecken und abtropfen lassen.',
      'Thunfisch abtropfen lassen und zerpflücken. Tomaten halbieren, Gurke und Paprika würfeln, Zwiebel fein hacken.',
      'Joghurt mit Mayo, Zitronensaft, Öl, Dill und Pfeffer zu einem Dressing verrühren.',
      'Baby-/Kleinkind-Portion (Nudeln, Gemüse, wenig Thunfisch) ungesalzen abnehmen.',
      'Alles mit Dressing mischen, leicht salzen, Rucola unterheben und 10 Min. durchziehen lassen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Nudeln und Dressing im Thermomix, Gemüse von Hand schneiden.',
      steps: [
        ['Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Joghurt, Mayo, Zitronensaft, Öl und Pfeffer zugeben, zum Dressing verrühren und umfüllen. Mixtopf ausspülen.', '10 Sek.', '', 'Stufe 3', ''],
        ['1,2 l Wasser in den Mixtopf geben und aufkochen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Nudeln zugeben und nach Packungsangabe al dente garen, abgießen, kalt abschrecken und abtropfen lassen.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Thunfisch zerpflücken, Tomaten halbieren, Gurke und Paprika würfeln, Zwiebel fein hacken.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion (Nudeln, Gemüse, wenig Thunfisch) ungesalzen abnehmen.', '', '', '', ''],
        ['Alles mit dem Dressing mischen, leicht salzen, Rucola unterheben und 10 Min. durchziehen lassen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Nudeln, Gurke und Paprika weich anbieten; Thunfisch nur selten und in kleiner Menge (Quecksilber). Kleinkind: Tomaten vierteln, Mais andrücken, Thunfisch max. 1×/Woche.',
    baby: 1,
  },
  {
    id: 'couscous-salat-haehnchen-feta',
    n: 'Couscous-Salat mit Hähnchen & Feta',
    img: { wiki: 'Couscous', q: 'couscous salad chicken feta' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['mealprep'],
    i: [['couscous', 70], ['gemuesebruehe', 100], ['haehnchenbrust', 150], ['feta', 35], ['gurke', 80], ['tomate', 80], ['paprika', 60], ['rote_zwiebel', 20], ['kraeuter', 8], ['zitrone', 20], ['olivenoel', 10], ['gewuerze', 1]],
    s: [
      'Couscous mit kochender Brühe übergießen, zugedeckt 5 Min. quellen lassen und mit einer Gabel auflockern.',
      'Hähnchen mit Paprikapulver würzen und in 1 TL Öl 6–7 Min. pro Seite durchbraten, abkühlen lassen und würfeln.',
      'Gurke, Tomate und Paprika fein würfeln, Zwiebel hacken, Petersilie und Minze grob zupfen.',
      'Baby-Portion (Couscous mit salzfreier Brühe, Gemüse, Hähnchen) ohne Feta abnehmen.',
      'Rest mit Zitronensaft, restlichem Öl und Kräutern mischen, Feta darüberbröseln.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Couscous, Kräuter und Zwiebel im Thermomix, Hähnchen in der Pfanne.',
      steps: [
        ['Petersilie und Minze in den Mixtopf geben, zerkleinern und umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
        ['Rote Zwiebel in den Mixtopf geben, zerkleinern und umfüllen.', '5 Sek.', '', 'Stufe 5', ''],
        ['Brühe in den Mixtopf geben und aufkochen.', '5 Min.', '100°C', 'Stufe 1', ''],
        ['Couscous zugeben, kurz verrühren und bei geschlossenem Deckel 5 Min. quellen lassen, dann umfüllen und mit einer Gabel auflockern.', '5 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Hähnchen mit Paprikapulver würzen, in 1 TL Öl in der Pfanne 6–7 Min. pro Seite durchbraten, abkühlen lassen und würfeln.', '', '', '', ''],
        ['Gurke, Tomate und Paprika fein würfeln. Baby-Portion (Couscous mit salzfreier Brühe, Gemüse, Hähnchen) ohne Feta abnehmen.', '', '', '', ''],
        ['Rest mit Zitronensaft, restlichem Öl, Zwiebel und Kräutern mischen und Feta darüberbröseln.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Couscous mit Joghurt oder Gemüsepüree zu Bällchen formen, Hähnchen zerzupft, Gurke geschält. Kleinkind: Feta nur wenig, Gemüse fein würfeln.',
    baby: 2,
  },
  {
    id: 'caesar-salad-haehnchen',
    n: 'Caesar Salad mit Hähnchen',
    img: { wiki: 'Caesar salad', q: 'chicken caesar salad' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['haehnchenbrust', 170], ['salat', 150], ['toast_vollkorn', 50], ['olivenoel', 8], ['parmesan', 15], ['griech_joghurt', 50], ['mayo_light', 10], ['senf', 5], ['zitrone', 10], ['knoblauch', 2], ['salz', 0.5]],
    s: [
      'Ofen auf 200 °C vorheizen. Toast würfeln, mit 1 TL Öl mischen und 8–10 Min. zu Croutons rösten.',
      'Hähnchen mit restlichem Öl in der Pfanne 6–7 Min. pro Seite durchbraten, 3 Min. ruhen lassen und in Streifen schneiden.',
      'Für das Dressing Joghurt, Mayo, Senf, Zitronensaft, geriebenen Knoblauch und die Hälfte des Parmesans verrühren.',
      'Baby-Portion (Hähnchen, Toast) vor dem Dressing abnehmen.',
      'Romanasalat zerzupfen, mit Dressing mischen, mit Hähnchen, Croutons und restlichem Parmesan anrichten.',
    ],
    tm: {
      fit: 0,
      note: 'Der Thermomix übernimmt nur das Dressing; Croutons im Ofen, Hähnchen in der Pfanne.',
      steps: [
        ['Ofen auf 200 °C vorheizen. Toast würfeln, mit 1 TL Öl mischen und 8–10 Min. zu Croutons rösten.', '', '', '', ''],
        ['Hähnchen mit restlichem Öl in der Pfanne 6–7 Min. pro Seite durchbraten, 3 Min. ruhen lassen und in Streifen schneiden.', '', '', '', ''],
        ['Parmesan und Knoblauch in den Mixtopf geben und zerkleinern, die Hälfte des Parmesans zum Bestreuen umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Joghurt, Mayo, Senf und Zitronensaft zugeben und zum Dressing verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Baby-Portion (Hähnchen, Toast) vor dem Dressing abnehmen.', '', '', '', ''],
        ['Romanasalat zerzupfen, mit Dressing mischen und mit Hähnchen, Croutons und restlichem Parmesan anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Hähnchenstreifen und weicher Toast (keine harten Croutons) mit etwas Joghurt zum Dippen; Blattsalat ist schwer zu kauen. Kleinkind: Salat fein schneiden, Croutons nur weich.',
    baby: 1,
  },
  {
    id: 'halloumi-gemuese-bowl',
    n: 'Halloumi-Gemüse-Bowl',
    img: { wiki: 'Buddha bowl', q: 'grilled halloumi vegetable quinoa bowl' },
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['mealprep'],
    i: [['halloumi', 80], ['quinoa', 60], ['kichererbsen', 42], ['zucchini', 65], ['paprika', 100], ['kirschtomaten', 60], ['rucola', 20], ['griech_joghurt', 60], ['zitrone', 10], ['olivenoel', 5], ['gewuerze', 1], ['kraeuter', 4]],
    s: [
      'Quinoa gründlich spülen und in der doppelten Menge Wasser 15 Min. garen, 5 Min. nachquellen lassen.',
      'Zucchini und Paprika in Streifen schneiden, mit Öl und Paprikapulver in der Grillpfanne 6–8 Min. braten. Kichererbsen 2 Min. mitbraten.',
      'Halloumi in Scheiben schneiden und ohne Fett 2 Min. pro Seite goldbraun grillen.',
      'Joghurt mit Zitronensaft und Minze verrühren.',
      'Quinoa, Gemüse, Kirschtomaten, Rucola und Halloumi in Schalen anrichten und mit Joghurtsauce servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen ausgelegt. Quinoa und Joghurtsauce im Thermomix, Gemüse und Halloumi in der Grillpfanne.',
      steps: [
        ['Minze in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Joghurt und Zitronensaft zugeben, verrühren und umfüllen. Mixtopf ausspülen.', '5 Sek.', '', 'Stufe 3', ''],
        ['1 l Wasser in den Mixtopf geben, gespülte Quinoa im Garkörbchen einhängen und garen, 5 Min. nachquellen lassen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zucchini und Paprika in Streifen mit Öl und Paprikapulver in der Grillpfanne 6–8 Min. braten, Kichererbsen 2 Min. mitbraten.', '', '', '', ''],
        ['Halloumi in Scheiben ohne Fett 2 Min. pro Seite goldbraun grillen.', '', '', '', ''],
        ['Quinoa, Gemüse, Kirschtomaten, Rucola und Halloumi in Schalen anrichten und mit der Joghurtsauce servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Halloumi ist sehr salzig – weglassen; stattdessen Quinoa mit Joghurt, zerdrückten Kichererbsen und weichem Gemüse. Kleinkind: ein kleines Stück Halloumi, Kirschtomaten vierteln.',
    baby: 1,
  },
  {
    id: 'protein-mac-and-cheese-brokkoli',
    n: 'Protein Mac and Cheese mit Brokkoli',
    img: { wiki: 'Macaroni and cheese', q: 'mac and cheese broccoli' },
    cu: 'amerikanisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['comfort', 'kinderliebling'],
    i: [['nudeln', 85], ['brokkoli', 120], ['milch', 120], ['speisestaerke', 6], ['huettenkaese', 100], ['cheddar', 30], ['gouda_light', 20], ['senf', 3], ['gewuerze', 1], ['salz', 0.5]],
    s: [
      'Makkaroni in Salzwasser al dente kochen, Brokkoliröschen in den letzten 4 Min. mitgaren und abgießen.',
      'Milch mit Stärke verrühren und unter Rühren aufkochen, bis sie leicht andickt.',
      'Hüttenkäse mit dem Stabmixer glatt pürieren und mit Cheddar, Gouda und Senf in die heiße Milch rühren, bis der Käse geschmolzen ist.',
      'Nudeln und Brokkoli unterheben. Baby-Portion entnehmen, Rest mit Paprikapulver und Pfeffer abschmecken.',
      'Optional in einer Form bei 220 °C Grill 5 Min. überbacken.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen ausgelegt. Brokkoli gart im Varoma mit; für das Baby das Nudelwasser nicht salzen.',
      steps: [
        ['Cheddar und Gouda in Stücken in den Mixtopf geben, reiben und umfüllen.', '8 Sek.', '', 'Stufe 8', ''],
        ['1,5 l Wasser in den Mixtopf geben und aufkochen.', '10 Min.', 'Varoma', 'Stufe 1', ''],
        ['Makkaroni zugeben, Brokkoliröschen in den Varoma-Behälter legen, aufsetzen und nach Packungsangabe garen. Abgießen und im Thermoserver warm halten.', '9 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
        ['Hüttenkäse, Milch und Stärke in den Mixtopf geben und glatt mixen.', '20 Sek.', '', 'Stufe 8', ''],
        ['Sauce aufkochen, bis sie leicht andickt.', '7 Min.', '90°C', 'Stufe 3', ''],
        ['Geriebenen Käse und Senf zugeben und schmelzen lassen.', '1 Min.', '90°C', 'Stufe 3', ''],
        ['Nudeln und Brokkoli zugeben und unterheben. Baby-Portion entnehmen, Rest mit Paprikapulver und Pfeffer abschmecken.', '30 Sek.', '', 'Sanftrührstufe', 'Linkslauf'],
        ['Optional in einer Form bei 220 °C Grill 5 Min. überbacken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Nudeln in ungesalzenem Wasser kochen, Brokkoliröschen als Fingerfood (gut greifbarer Stiel), wenig Käsesauce, da Käse salzig ist. Kleinkind: perfekt so, Brokkoli klein schneiden.',
    baby: 2,
  },
]);
