// Proteinreiche Rezepte mit Markenprodukten (More Nutrition, ESN) – alle glutenfrei umsetzbar.
// Proteinpulver ist nicht für Babys und Kleinkinder geeignet: Kinderportion immer ohne Pulver.
Object.assign(ING, {
  prot_gelatine: { n: 'Gelatine (gemahlen)', k: 340, p: 86, c: 0, f: 0.1, fi: 0, su: 0, sa: 0.6, pr: 40, cat: 'backen', fl: 'XA', u: [9, 'Päckchen'] },
});
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  {
    id: 'protein-milchreis-more-sahne',
    n: 'Protein-Milchreis mit More „Sahne“ & Beeren',
    img: { file: "Rice pudding cinnamon.jpg", wiki: 'Rice pudding', q: 'rice pudding berries' },
    cu: 'deutsch', m: ['fruehstueck', 'mittag', 'snack'], t: 35, d: 1, st: ['comfort', 'kinderliebling'],
    i: [['sushireis', 50], ['milch', 250], ['more_total_sahne', 30], ['heidelbeeren', 80], ['vanille', 1], ['ahornsirup', 5]],
    s: [
      'Milch mit Vanille/Zimt aufkochen, Milchreis einrühren und bei kleiner Hitze 25–30 Min. unter gelegentlichem Rühren quellen lassen.',
      'Kinderportion jetzt abnehmen (ohne Proteinpulver) und mit etwas Obstmus süßen.',
      'Den Rest etwas abkühlen lassen (unter 60 °C), dann More Total Protein „Sahne“ glatt einrühren – nicht mehr kochen, sonst flockt es.',
      'Mit Heidelbeeren und einem Hauch Ahornsirup servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen. Proteinpulver erst nach dem Abkühlen einrühren.', steps: [
      ['Milch, Milchreis und Vanille/Zimt in den Mixtopf geben, ohne Messbecher garen.', '30 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
      ['Kinderportion entnehmen (ohne Pulver).', '', '', '', ''],
      ['5 Min. abkühlen lassen, dann Proteinpulver zugeben und unterrühren.', '30 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Mit Beeren und Ahornsirup servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (ab ca. 8 Mon.) und Kleinkind: Milchreis OHNE Proteinpulver und ohne Sirup, mit zerdrückten Beeren oder Apfelmus süßen. Für Babys unter 12 Mon. nur wenig Kuhmilch im Brei – alternativ mit Wasser/Muttermilch kochen.',
    baby: 1,
  },
  {
    id: 'protein-kaiserschmarrn',
    n: 'Protein-Kaiserschmarrn (glutenfrei möglich)',
    img: { wiki: 'Kaiserschmarrn', q: 'kaiserschmarrn' },
    cu: 'deutsch', m: ['fruehstueck', 'mittag'], t: 25, d: 2, st: ['comfort', 'kinderliebling'],
    i: [['ei', 120], ['more_total_sahne', 30], ['mehl', 40], ['milch', 100], ['butter', 5], ['beeren_tk', 80], ['ahornsirup', 5]],
    s: [
      'Eier trennen. Eigelb mit Milch, Mehl (glutenfrei: z. B. Schär Mix It!) und Proteinpulver glatt rühren.',
      'Eiweiß steif schlagen und vorsichtig unterheben.',
      'Butter in einer beschichteten Pfanne erhitzen, Teig hineingeben und bei mittlerer Hitze 4–5 Min. stocken lassen.',
      'Wenden, mit zwei Gabeln in Stücke reißen und weitere 2–3 Min. goldbraun braten.',
      'Beeren kurz in einem Topf erwärmen und als Kompott dazu reichen, mit Ahornsirup beträufeln.',
    ],
    tm: { fit: 1, note: 'Teig im Thermomix, Ausbacken in der Pfanne.', steps: [
      ['Rühraufsatz einsetzen. Eiweiß in den Mixtopf geben und steif schlagen, umfüllen.', '3 Min.', '', 'Stufe 3,5', ''],
      ['Rühraufsatz entfernen. Eigelb, Milch, Mehl und Proteinpulver verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Eischnee zugeben und unterheben.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['In der Pfanne mit Butter ausbacken, zerreißen und fertig braten.', '', '', '', ''],
      ['Beeren im Mixtopf erwärmen.', '4 Min.', '90°C', 'Stufe 1', 'Linkslauf'],
    ] },
    kid: 'Kleinkind: Kinder-Schmarrn ohne Proteinpulver (stattdessen 1 EL mehr Mehl), ohne Sirup, mit Beerenkompott. Baby (ab 8 Mon.): weiche, durchgebackene Streifen als Fingerfood, Eier vollständig durchgaren.',
    baby: 1,
  },
  {
    id: 'protein-cheesecake-glas',
    n: 'Protein-Cheesecake im Glas mit ESN Designer Whey',
    img: { file: "Cheesecake in a jar.jpg", q: 'cheesecake in a jar raspberries' },
    cu: 'amerikanisch', m: ['snack', 'fruehstueck'], t: 10, d: 1, st: ['mealprep'],
    i: [['magerquark', 150], ['skyr', 100], ['esn_designer_whey', 20], ['frischkaese_light', 30], ['haferflocken', 20], ['himbeeren', 60], ['vanille', 1], ['ahornsirup', 5]],
    s: [
      'Haferflocken (glutenfrei: zertifizierte Haferflocken) in einer Pfanne ohne Fett 2 Min. rösten – das ist der „Keksboden“.',
      'Quark, Skyr, Frischkäse, Whey und Vanille cremig rühren.',
      'Geröstete Flocken ins Glas geben, Creme darauf schichten.',
      'Mit Himbeeren und Ahornsirup toppen, 30 Min. kühlen (hält 2 Tage im Kühlschrank).',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Haferflocken in den Mixtopf geben und rösten.', '4 Min.', 'Varoma', 'Stufe 1', 'Linkslauf'],
      ['Umfüllen. Quark, Skyr, Frischkäse, Whey und Vanille in den Mixtopf geben und cremig rühren.', '30 Sek.', '', 'Stufe 4', ''],
      ['In Gläser schichten, mit Himbeeren toppen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Kinderportion ohne Whey: Quark mit Skyr, zerdrückten Himbeeren und etwas Banane süßen. Für Babys unter 12 Mon. nur kleine Mengen Quark/Skyr (hoher Eiweißgehalt).',
    baby: 0,
  },
  {
    id: 'proffee-overnight-oats-flexpresso',
    n: 'Proffee Overnight Oats mit ESN Flexpresso',
    img: { file: "Protein overnight oats.jpg", q: 'overnight oats jar coffee' },
    cu: 'international', m: ['fruehstueck'], t: 5, d: 1, st: ['mealprep'],
    i: [['haferflocken', 50], ['skyr', 150], ['milch', 100], ['esn_flexpresso', 25], ['chiasamen', 10], ['banane', 60]],
    s: [
      'Haferflocken (glutenfrei: zertifizierte Haferflocken), Chiasamen, Milch und Flexpresso im Glas verrühren.',
      'Skyr unterrühren und über Nacht (mind. 4 Std.) im Kühlschrank quellen lassen.',
      'Morgens mit Bananenscheiben toppen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Gläser.', steps: [
      ['Milch und Flexpresso verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Haferflocken, Chiasamen und Skyr zugeben und vermischen.', '20 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['In Gläser füllen, über Nacht kühlen, mit Banane servieren.', '', '', '', ''],
    ] },
    kid: 'Enthält Kaffee/Koffein und Proteinpulver – nicht für Kinder. Kinderportion: Overnight Oats nur mit Milch, Joghurt und zerdrückter Banane.',
    baby: 0,
  },
  {
    id: 'isoclear-protein-wackelpudding',
    n: 'ESN Isoclear Protein-Wackelpudding mit Beeren',
    img: { file: "Götterspeise Hof (Saale) 20220923 182656.jpg", q: 'jelly dessert berries glass' },
    cu: 'international', m: ['snack'], t: 15, d: 1, st: ['mealprep'],
    i: [['esn_isoclear', 25], ['prot_gelatine', 6], ['beeren_tk', 80], ['skyr', 80]],
    s: [
      'Gelatine in 50 ml kaltem Wasser 5 Min. quellen lassen, dann bei kleiner Hitze auflösen (nicht kochen).',
      'Isoclear in 200 ml kaltem Wasser auflösen, die warme Gelatine zügig einrühren.',
      'Beeren in Gläser verteilen, Flüssigkeit darübergießen und mind. 3 Std. kühlen.',
      'Mit einem Klecks Skyr servieren.',
    ],
    tm: { fit: 1, note: 'Gelatine im Thermomix auflösen.', steps: [
      ['Gelatine mit 50 ml Wasser 5 Min. quellen lassen, dann auflösen.', '2 Min.', '60°C', 'Stufe 2', ''],
      ['200 ml kaltes Wasser und Isoclear zugeben und verrühren.', '20 Sek.', '', 'Stufe 3', ''],
      ['Über die Beeren gießen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Für Kinder: Fruchtgelee ohne Isoclear – Beeren mit etwas Apfelsaft und Gelatine (oder Agar-Agar) – und Naturjoghurt statt Skyr. Gelee für Babys nur in weichen, kleinen Stücken.',
    baby: 0,
  },
  {
    id: 'protein-waffeln-glutenfrei',
    n: 'Protein-Waffeln mit Quark (glutenfrei möglich)',
    img: { wiki: 'Waffle', q: 'waffles berries' },
    cu: 'international', m: ['fruehstueck', 'snack'], t: 20, d: 1, st: ['kinderliebling'],
    i: [['haferflocken', 50], ['ei', 60], ['esn_designer_whey', 20], ['magerquark', 80], ['milch', 50], ['backpulver', 3], ['beeren_tk', 80], ['ahornsirup', 5]],
    s: [
      'Haferflocken (glutenfrei: zertifiziert) fein mahlen.',
      'Mit Ei, Quark, Milch, Backpulver und Whey zu einem dickflüssigen Teig verrühren, 5 Min. quellen lassen.',
      'Waffeleisen leicht fetten und Waffeln goldbraun backen (ca. 3 Min. pro Waffel).',
      'Mit Beeren und Ahornsirup servieren.',
    ],
    tm: { fit: 1, note: 'Teig im Thermomix, Backen im Waffeleisen.', steps: [
      ['Haferflocken mahlen.', '10 Sek.', '', 'Stufe 10', ''],
      ['Ei, Quark, Milch, Backpulver und Whey zugeben und verrühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Teig 5 Min. quellen lassen und im Waffeleisen backen.', '', '', '', ''],
    ] },
    kid: 'Kinderwaffel: Teig ohne Whey (stattdessen 20 g mehr Haferflocken + 1 zerdrückte Banane). Baby (ab 8 Mon.): in Streifen als Fingerfood, ohne Sirup.',
    baby: 1,
  },
  {
    id: 'more-protein-pudding-himbeeren',
    n: 'More Protein Pudding mit Himbeeren & Mandeln',
    img: { q: 'vanilla pudding raspberries' },
    cu: 'international', m: ['snack'], t: 5, d: 1, st: [],
    i: [['more_pudding', 30], ['milch', 250], ['himbeeren', 80], ['mandeln', 10], ['more_chunky', 3]],
    s: [
      'Kalte Milch in ein hohes Gefäß geben, Puddingpulver und Chunky Flavour zugeben.',
      '1 Min. kräftig mit dem Schneebesen oder Milchaufschäumer aufschlagen.',
      '5 Min. andicken lassen, mit Himbeeren und gehackten Mandeln toppen.',
    ],
    tm: { fit: 2, note: 'Für 4 Portionen.', steps: [
      ['Milch, Puddingpulver und Chunky Flavour in den Mixtopf geben und aufschlagen.', '1 Min.', '', 'Stufe 4', ''],
      ['5 Min. andicken lassen, in Schalen füllen und toppen.', '', '', '', ''],
    ] },
    kid: 'Kinder: klassischer Vanillepudding mit wenig Zucker oder Grießbrei (glutenfrei: Hirse- oder Maisgrieß) mit Himbeeren. Mandeln für Kleinkinder nur gemahlen.',
    baby: 0,
  },
  {
    id: 'chunky-skyr-bowl',
    n: 'Skyr-Bowl mit More Chunky Flavour',
    img: { file: "Granola and yogurt - Bubbles + Brunch 2018 - Sarah Stierch 02.jpg", q: 'yogurt bowl berries granola' },
    cu: 'international', m: ['fruehstueck', 'snack'], t: 5, d: 1, st: [],
    i: [['skyr', 250], ['more_chunky', 5], ['beeren_tk', 100], ['granola', 25]],
    s: [
      'Skyr mit Chunky Flavour cremig rühren.',
      'Aufgetaute Beeren darauf verteilen.',
      'Mit Granola (glutenfrei: z. B. Schär oder Bauck) toppen.',
    ],
    tm: { fit: 0, note: 'Kein Thermomix nötig.', steps: [
      ['Skyr mit Chunky Flavour verrühren, mit Beeren und Granola toppen.', '', '', '', ''],
    ] },
    kid: 'Kinder: Naturjoghurt mit Beeren, ohne Geschmackspulver (Süßstoff). Granola für Kleinkinder fein zerbröseln oder weglassen.',
    baby: 0,
  },
  {
    id: 'protein-nicecream',
    n: 'Protein-Nicecream (Bananen-Eis) mit ESN Designer Whey',
    img: { q: 'banana nice cream' },
    cu: 'international', m: ['snack'], t: 5, d: 1, st: ['kinderliebling'],
    i: [['banane', 120], ['skyr', 100], ['esn_designer_whey', 20], ['kakao', 5], ['erdnussbutter', 10]],
    s: [
      'Bananen in Scheiben schneiden und mind. 4 Std. einfrieren.',
      'Gefrorene Bananen mit Skyr, Whey und Kakao im Mixer cremig pürieren.',
      'Sofort mit einem Klecks Erdnussmus servieren.',
    ],
    tm: { fit: 2, note: 'Bananen gut durchgefroren verwenden.', steps: [
      ['Gefrorene Bananen in den Mixtopf geben und zerkleinern.', '20 Sek.', '', 'Stufe 10', ''],
      ['Skyr, Whey und Kakao zugeben und cremig rühren, dabei mit dem Spatel nachschieben.', '30 Sek.', '', 'Stufe 4', ''],
    ] },
    kid: 'Kinder-Nicecream: nur gefrorene Banane mit etwas Joghurt pürieren – ohne Whey. Erdnussmus ist ein gutes, frühes Allergen für Babys (dünn verstrichen), aber nie als ganze Nüsse.',
    baby: 0,
  },
  {
    id: 'protein-tiramisu-glas',
    n: 'Protein-Tiramisu im Glas (glutenfrei)',
    img: { wiki: 'Tiramisu', q: 'tiramisu glass' },
    cu: 'italienisch', m: ['snack', 'fruehstueck'], t: 10, d: 1, st: ['mealprep'],
    i: [['magerquark', 150], ['skyr', 100], ['esn_flexpresso', 15], ['more_total_sahne', 15], ['kakao', 5], ['reiswaffeln', 16]],
    s: [
      'Quark, Skyr und More „Sahne“ cremig rühren.',
      'Flexpresso in 80 ml kaltem Wasser auflösen.',
      'Reiswaffeln grob zerbröseln, mit dem Kaffee-Protein-Mix tränken und ins Glas geben.',
      'Creme darauf schichten, mit Kakao bestäuben und 1 Std. kühlen.',
    ],
    tm: { fit: 2, note: 'Für 4 Gläser.', steps: [
      ['Flexpresso mit 320 ml kaltem Wasser verrühren, umfüllen.', '15 Sek.', '', 'Stufe 4', ''],
      ['Quark, Skyr und More „Sahne“ in den Mixtopf geben und cremig rühren.', '30 Sek.', '', 'Stufe 4', ''],
      ['Zerbröselte Reiswaffeln tränken, mit Creme schichten, mit Kakao bestäuben.', '', '', '', ''],
    ] },
    kid: 'Enthält Kaffee und Proteinpulver – nicht für Kinder. Kinder-Variante: Quark mit Banane und Kakao, mit Reiswaffel-Bröseln geschichtet.',
    baby: 0,
  },
]);
