// Proteinreiche Snacks: Dips mit Gemüsesticks, Eier-Snacks, Röllchen, Bites, Häppchen, Protein-Chips & süßes Fingerfood – alle glutenfrei umsetzbar.
// Proteinpulver ist nicht für Babys und Kleinkinder geeignet: Kinderportion immer ohne Pulver.
Object.assign(ING, {
  snacks_knaecke_gf: { n: 'Glutenfreies Knäckebrot (Reis/Mais/Saaten)', k: 400, p: 8, c: 66, f: 10, fi: 8, su: 1.5, sa: 1.2, pr: 14, cat: 'spezial', fl: '', u: [10, 'Scheibe'] },
});
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  /* ---------- Dips mit Gemüsesticks ---------- */
  {
    id: 'protein-tzatziki-gemuesesticks',
    n: 'Protein-Tzatziki mit Paprika- und Kohlrabisticks',
    ck: 'Tzatziki',
    img: { wiki: 'Tzatziki', q: 'tzatziki dip vegetable sticks' },
    cu: 'mediterran', m: ['snack'], t: 15, d: 1, st: ['mealprep'],
    i: [['skyr', 100], ['griech_joghurt', 100], ['gurke', 150], ['knoblauch', 4], ['kraeuter', 4], ['olivenoel', 5], ['zitronensaft', 5], ['salz', 1], ['paprika', 100], ['kohlrabi', 80]],
    s: [
      'Gurke grob raspeln, mit einer Prise Salz mischen und 5 Min. ziehen lassen, dann kräftig ausdrücken.',
      'Skyr und griechischen Joghurt glatt rühren, Knoblauch fein dazureiben.',
      'Gurke, gehackten Dill, Zitronensaft und Olivenöl unterrühren.',
      'Für das Baby eine Portion vor dem Nachsalzen entnehmen, Rest abschmecken.',
      'Paprika und Kohlrabi in Sticks schneiden und zum Tzatziki reichen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Gurke in Stücken in den Mixtopf geben und zerkleinern, in ein Sieb geben und ausdrücken.', '4 Sek.', '', 'Stufe 4', ''],
      ['Knoblauch und Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Skyr, Joghurt, Zitronensaft, Olivenöl und Gurke zugeben und verrühren.', '15 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ['Baby-Portion ungesalzen entnehmen.', '', '', '', ''],
      ['Salz zugeben und unterrühren.', '5 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ['Gemüse in Sticks schneiden und dazu servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzenes Tzatziki mit wenig Knoblauch zu weich gedämpften Kohlrabisticks. Kleinkind (1–3 J.): Paprikasticks und dünne Kohlrabistreifen zum Dippen, Knoblauch halbieren.',
    baby: 2,
  },
  {
    id: 'rote-bete-hummus-kohlrabi',
    n: 'Rote-Bete-Hummus mit Skyr und Kohlrabisticks',
    ck: 'Rote Bete Hummus',
    img: { wiki: 'Hummus', q: 'beetroot hummus' },
    cu: 'orientalisch', m: ['snack'], t: 10, d: 1, st: ['mealprep', 'kinderliebling'],
    i: [['kichererbsen', 42], ['rote_bete', 60], ['skyr', 80], ['tahini', 8], ['zitronensaft', 8], ['knoblauch', 3], ['gewuerze', 1], ['salz', 0.5], ['kohlrabi', 120], ['karotte', 60]],
    s: [
      'Kichererbsen abspülen und abtropfen lassen, Rote Bete grob würfeln.',
      'Kichererbsen, Rote Bete, Tahini, Zitronensaft, Knoblauch und Kreuzkümmel 2 Min. fein pürieren.',
      'Skyr unterrühren, bis ein cremiger, pinker Dip entsteht.',
      'Baby-Portion ungesalzen abnehmen, Rest mit Salz abschmecken.',
      'Kohlrabi und Karotte in Sticks schneiden und mit dem Hummus servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
      ['Kichererbsen, Rote Bete, Tahini, Zitronensaft und Kreuzkümmel zugeben und pürieren, zwischendurch nach unten schieben.', '1 Min.', '', 'Stufe 8', ''],
      ['Skyr zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['Baby-Portion ungesalzen entnehmen.', '', '', '', ''],
      ['Salz zugeben und kurz verrühren, mit Gemüsesticks servieren.', '5 Sek.', '', 'Stufe 4', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzenen Hummus auf weich gedämpfte Kohlrabi- oder Karottensticks streichen – die Farbe begeistert. Kleinkind (1–3 J.): als Dip zu dünnen Kohlrabistreifen, Lätzchen nicht vergessen (Rote Bete färbt).',
    baby: 2,
  },
  {
    id: 'edamame-hummus-gurke',
    n: 'Grüner Edamame-Hummus mit Gurken und Radieschen',
    ck: 'Edamame Hummus',
    img: { wiki: 'Edamame', q: 'edamame hummus dip' },
    cu: 'international', m: ['snack'], t: 15, d: 1, st: ['mealprep'],
    i: [['edamame', 100], ['skyr', 50], ['tahini', 8], ['zitronensaft', 10], ['knoblauch', 3], ['olivenoel', 5], ['kraeuter', 3], ['salz', 0.5], ['gewuerze', 1], ['gurke', 150], ['radieschen', 60]],
    s: [
      'Edamame in kochendem Wasser 4 Min. garen, kalt abschrecken und abtropfen lassen.',
      'Edamame mit Tahini, Zitronensaft, Knoblauch, Olivenöl und Koriander 2 Min. fein pürieren, dabei 2–3 EL kaltes Wasser zugeben.',
      'Skyr unterrühren. Baby-Portion ungesalzen entnehmen.',
      'Rest mit Salz und Kreuzkümmel abschmecken.',
      'Gurke in Sticks, Radieschen in Hälften schneiden und dazu servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['500 g Wasser in den Mixtopf füllen, Edamame ins Garkörbchen geben und garen. Abschrecken, Mixtopf leeren.', '12 Min.', '100°C', 'Stufe 1', ''],
      ['Knoblauch und Koriander in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Edamame, Tahini, Zitronensaft, Olivenöl und 2–3 EL Wasser zugeben und pürieren.', '1 Min.', '', 'Stufe 8', ''],
      ['Skyr zugeben und verrühren, dann Baby-Portion entnehmen.', '15 Sek.', '', 'Stufe 4', ''],
      ['Salz und Kreuzkümmel zugeben und unterrühren.', '5 Sek.', '', 'Stufe 4', ''],
      ['Mit Gurken- und Radieschenstücken servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzenen Edamame-Hummus auf weich gedämpfte Zucchinistreifen oder Toaststreifen (glutenfrei) streichen. Kleinkind (1–3 J.): Gurkensticks zum Dippen, Radieschen geviertelt (scharf, nicht jeder mag sie).',
    baby: 2,
  },
  {
    id: 'schwarze-bohnen-dip-paprika',
    n: 'Schwarze-Bohnen-Dip mit Limette und Paprikasticks',
    ck: 'Bohnendip mexikanisch',
    img: { wiki: 'Bean dip', q: 'black bean dip lime' },
    cu: 'mexikanisch', m: ['snack'], t: 10, d: 1, st: ['mealprep'],
    i: [['schwarze_bohnen', 100], ['skyr', 80], ['limette', 10], ['knoblauch', 3], ['gewuerze', 2], ['kraeuter', 4], ['chili_frisch', 2], ['salz', 0.5], ['paprika', 150]],
    s: [
      'Bohnen abspülen und abtropfen lassen, Limettensaft auspressen.',
      'Bohnen mit Knoblauch, Limettensaft und Kreuzkümmel fein pürieren.',
      'Skyr und gehackten Koriander unterrühren. Baby-/Kleinkind-Portion ohne Salz und Chili entnehmen.',
      'Rest mit Salz, geräuchertem Paprikapulver und fein gehackter Chili abschmecken.',
      'Paprika in Streifen schneiden und zum Dippen reichen.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Knoblauch und Koriander in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Bohnen, Limettensaft und Kreuzkümmel zugeben und pürieren.', '40 Sek.', '', 'Stufe 7', ''],
      ['Skyr zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['Baby-/Kleinkind-Portion ohne Salz und Chili entnehmen.', '', '', '', ''],
      ['Salz, Paprikapulver und Chili zugeben und unterrühren.', '10 Sek.', '', 'Stufe 4', ''],
      ['Mit Paprikastreifen servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Dip ohne Salz und Chili, sehr fein püriert auf weichen Süßkartoffelspalten. Kleinkind (1–3 J.): milde Variante mit Paprikastreifen; Bohnen können blähen, also kleine Menge.',
    baby: 2,
  },
  {
    id: 'htipiti-feta-paprika-dip',
    n: 'Htipiti – Feta-Paprika-Dip mit Quark',
    ck: 'Feta Paprika Dip',
    img: { wiki: 'Htipiti', q: 'htipiti feta pepper dip' },
    cu: 'mediterran', m: ['snack'], t: 25, d: 1, st: ['mealprep'],
    i: [['feta', 40], ['magerquark', 100], ['paprika', 80], ['chili_frisch', 2], ['olivenoel', 5], ['gewuerze', 1], ['gurke', 100], ['karotte', 60]],
    s: [
      'Paprika halbieren, mit der Hautseite nach oben bei 230 °C Grill 12–15 Min. rösten, bis die Haut Blasen wirft. Abkühlen lassen und häuten.',
      'Paprika mit Feta, Magerquark und Olivenöl grob pürieren – der Dip darf stückig bleiben.',
      'Baby-/Kleinkind-Portion ohne Chili entnehmen (Feta ist salzig, für Babys nur wenig).',
      'Rest mit fein gehackter Chili und Oregano würzen – Salz ist dank Feta nicht nötig.',
      'Mit Gurken- und Karottensticks servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen. Paprika im Ofen rösten.', steps: [
      ['Paprika im Ofen rösten und häuten.', '', '', '', ''],
      ['Paprika, Feta und Olivenöl in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
      ['Magerquark zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Kinderportion ohne Chili entnehmen.', '', '', '', ''],
      ['Chili und Oregano zugeben und unterrühren.', '5 Sek.', '', 'Stufe 3', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): wegen des Fetas nur einen kleinen Klecks, mit zusätzlichem Quark verdünnt auf weich gedämpftem Gemüse. Kleinkind (1–3 J.): ohne Chili als Dip zu Gurkensticks.',
    baby: 1,
  },
  {
    id: 'huettenkaese-guacamole-maischips',
    n: 'Hüttenkäse-Guacamole mit Ofen-Maischips',
    ck: 'Guacamole',
    img: { wiki: 'Guacamole', q: 'guacamole tortilla chips' },
    cu: 'mexikanisch', m: ['snack'], t: 15, d: 1, st: ['kinderliebling'],
    i: [['avocado', 30], ['huettenkaese', 150], ['limette', 10], ['tomate', 50], ['rote_zwiebel', 15], ['kraeuter', 4], ['chili_frisch', 2], ['salz', 0.5], ['tortilla_mais', 30], ['paprika', 80]],
    s: [
      'Maistortillas in Achtel schneiden, auf ein Blech legen und bei 200 °C 6–8 Min. knusprig backen.',
      'Avocado mit Limettensaft zerdrücken, Hüttenkäse unterrühren (für eine glatte Creme kurz pürieren).',
      'Tomate entkernen und fein würfeln, rote Zwiebel und Koriander fein hacken und unterheben.',
      'Baby-/Kleinkind-Portion ohne Salz, Zwiebel und Chili entnehmen, Rest abschmecken.',
      'Mit Maischips und Paprikastreifen servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen. Chips im Ofen backen.', steps: [
      ['Zwiebel, Koriander und Chili in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 7', ''],
      ['Avocado, Hüttenkäse und Limettensaft in den Mixtopf geben und cremig rühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['Kinderportion entnehmen.', '', '', '', ''],
      ['Zwiebelmischung, Tomatenwürfel und Salz zugeben und unterheben.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Maistortillas im Ofen zu Chips backen und dazu servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Avocado-Hüttenkäse-Creme ohne Salz, Zwiebel und Chili als Brei oder auf weichen Paprikastreifen; Chips sind zu hart. Kleinkind (1–3 J.): milde Guacamole mit weichen Tortillastreifen.',
    baby: 2,
  },
  {
    id: 'thunfischcreme-gurke',
    n: 'Thunfischcreme mit Gurken- und Paprikasticks',
    ck: 'Thunfischcreme',
    img: { q: 'tuna spread cucumber' },
    cu: 'international', m: ['snack'], t: 10, d: 1, st: ['mealprep'],
    i: [['thunfisch_dose', 70], ['magerquark', 60], ['frischkaese_light', 15], ['zitronensaft', 5], ['kraeuter', 4], ['senf', 3], ['salz', 0.3], ['gurke', 150], ['paprika', 80]],
    s: [
      'Thunfisch gut abtropfen lassen und mit einer Gabel zerpflücken.',
      'Magerquark, Frischkäse, Senf und Zitronensaft glatt rühren.',
      'Thunfisch und gehackte Petersilie unterrühren, mit Pfeffer und wenig Salz abschmecken.',
      'Gurke und Paprika in Sticks schneiden und mit der Creme servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Petersilie in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Magerquark, Frischkäse, Senf und Zitronensaft zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['Thunfisch, Pfeffer und Salz zugeben und unterrühren.', '10 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ['Mit Gemüsesticks servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 10 Mon.): Thunfisch höchstens 1× pro Woche, ohne Salz und Senf mit Quark vermischt auf weichem Gemüse. Kleinkind (1–3 J.): kleine Portion auf Reiswaffel oder mit Gurkensticks.',
    baby: 1,
  },
  {
    id: 'linsen-hummus-karotte',
    n: 'Rote-Linsen-Hummus mit Karotten- und Gurkensticks',
    ck: 'Linsen Hummus',
    img: { q: 'red lentil hummus' },
    cu: 'orientalisch', m: ['snack'], t: 25, d: 1, st: ['mealprep', 'kinderliebling'],
    i: [['rote_linsen', 30], ['skyr', 60], ['tahini', 8], ['zitronensaft', 8], ['knoblauch', 3], ['gewuerze', 2], ['olivenoel', 3], ['salz', 0.5], ['karotte', 100], ['gurke', 100]],
    s: [
      'Rote Linsen abspülen und in der doppelten Menge Wasser 12–15 Min. weich kochen, abgießen und abkühlen lassen.',
      'Linsen mit Tahini, Zitronensaft, Knoblauch und Kreuzkümmel fein pürieren.',
      'Skyr unterrühren. Baby-Portion ungesalzen entnehmen.',
      'Rest salzen, mit Olivenöl beträufeln und mit Paprikapulver bestäuben.',
      'Mit Karotten- und Gurkensticks servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Linsen und Wasser in den Mixtopf geben und garen.', '15 Min.', '100°C', 'Stufe 1', ''],
      ['Abgießen, 10 Min. abkühlen lassen. Mit Tahini, Zitronensaft, Knoblauch und Kreuzkümmel in den Mixtopf geben und pürieren.', '1 Min.', '', 'Stufe 8', ''],
      ['Skyr zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['Baby-Portion ungesalzen entnehmen.', '', '', '', ''],
      ['Salz zugeben und unterrühren, mit Öl und Paprikapulver anrichten.', '5 Sek.', '', 'Stufe 4', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzener Linsen-Hummus pur als Brei oder auf weich gedämpften Karottensticks – sehr eisenreich. Kleinkind (1–3 J.): Gurkensticks und blanchierte Karotte zum Dippen.',
    baby: 2,
  },
  /* ---------- Harzer Käse ---------- */
  {
    id: 'obatzda-light-radieschen',
    n: 'Obatzda light mit Harzer und Radieschen',
    ck: 'Obatzda',
    img: { wiki: 'Obatzda', q: 'obatzda radishes' },
    cu: 'deutsch', m: ['snack'], t: 15, d: 1, st: ['mealprep'],
    i: [['harzer', 50], ['magerquark', 80], ['frischkaese_light', 20], ['zwiebel', 15], ['gewuerze', 2], ['kraeuter', 3], ['radieschen', 100], ['gurke', 80]],
    s: [
      'Harzer Käse in kleine Würfel schneiden und mit einer Gabel zerdrücken.',
      'Magerquark und Frischkäse unterrühren, bis eine cremige, leicht stückige Masse entsteht.',
      'Zwiebel sehr fein würfeln und mit edelsüßem Paprikapulver und etwas Kümmel unterrühren – kein Salz nötig.',
      'Mit Schnittlauch bestreuen, 15 Min. durchziehen lassen.',
      'Mit Radieschen und Gurkenscheiben servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['Zwiebel in den Mixtopf geben und zerkleinern, nach unten schieben.', '4 Sek.', '', 'Stufe 5', ''],
      ['Harzer in Stücken zugeben und zerkleinern.', '5 Sek.', '', 'Stufe 4', ''],
      ['Magerquark, Frischkäse, Paprikapulver und Kümmel zugeben und verrühren.', '20 Sek.', '', 'Stufe 3', 'Linkslauf'],
      ['Mit Schnittlauch bestreuen und mit Radieschen und Gurke servieren.', '', '', '', ''],
    ] },
    kid: 'Harzer ist sehr salzig – nichts fürs Baby. Baby (6–12 Mon.): Quark mit Paprikapulver als Dip zu weicher Gurke. Kleinkind (1–3 J.): höchstens 1 TL Obatzda, mit extra Quark gestreckt, auf Gurkenscheiben.',
    baby: 0,
  },
  {
    id: 'harzer-mit-musik',
    n: 'Harzer mit Musik (Handkäs-Art) und Knäckebrot',
    ck: 'Handkäse mit Musik',
    img: { wiki: 'Handkäse', q: 'handkaese mit musik onions' },
    cu: 'deutsch', m: ['snack'], t: 10, d: 1,
    i: [['harzer', 100], ['zwiebel', 40], ['essig', 10], ['rapsoel', 5], ['gewuerze', 1], ['kraeuter', 3], ['snacks_knaecke_gf', 10]],
    s: [
      'Zwiebel fein würfeln und mit Apfelessig, 2 EL Wasser, Rapsöl, Kümmel und Pfeffer zur „Musik“ verrühren.',
      'Harzer Käse in dicke Scheiben schneiden und auf einen Teller legen.',
      'Die Marinade darübergießen und mindestens 30 Min. (gern über Nacht) im Kühlschrank ziehen lassen.',
      'Mit Schnittlauch bestreuen und mit glutenfreiem Knäckebrot servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen. Der Käse wird nur mariniert.', steps: [
      ['Zwiebel in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
      ['Essig, Wasser, Rapsöl, Kümmel und Pfeffer zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Marinade über die Käsescheiben gießen.', '', '', '', ''],
      ['Mindestens 30 Min. ziehen lassen und mit Knäckebrot servieren.', '', '', '', ''],
    ] },
    kid: 'Für Baby und Kleinkind ungeeignet (sehr salzig, rohe Zwiebel, Essig). Kinder-Snack stattdessen: Knäckebrot mit Frischkäse und Gurke.',
    baby: 0,
  },
  {
    id: 'harzer-kaese-chips',
    n: 'Knusprige Harzer-Käse-Chips mit Skyr-Dip',
    ck: 'Käsechips',
    img: { q: 'baked cheese crisps' },
    cu: 'deutsch', m: ['snack'], t: 45, d: 1, st: ['mealprep'],
    i: [['harzer', 100], ['gewuerze', 1], ['skyr', 60], ['kraeuter', 3], ['gurke', 100]],
    s: [
      'Ofen auf 120 °C Umluft vorheizen, Blech mit Backpapier belegen.',
      'Harzer in sehr dünne Scheiben (2 mm) schneiden, mit viel Abstand auf das Blech legen und mit Paprikapulver bestäuben.',
      'Ca. 35–40 Min. trocknen und backen, bis die Scheiben aufgegangen und kross sind. Auf dem Blech auskühlen lassen.',
      'Skyr mit gehackten Kräutern und Pfeffer verrühren.',
      'Chips mit Dip und Gurkenscheiben servieren (luftdicht 3 Tage haltbar).',
    ],
    tm: { fit: 0, note: 'Chips im Ofen, nur der Dip im Thermomix.', steps: [
      ['Harzer-Scheiben im Ofen zu Chips backen.', '', '', '', ''],
      ['Kräuter in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Skyr und Pfeffer zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Chips mit Dip und Gurke servieren.', '', '', '', ''],
    ] },
    kid: 'Für Baby und Kleinkind ungeeignet (sehr salzig, harte Chips). Kinder-Snack: Skyr-Kräuter-Dip mit Gurkensticks.',
    baby: 0,
  },
  /* ---------- Eier-Snacks ---------- */
  {
    id: 'devilled-eggs-skyr',
    n: 'Devilled Eggs mit Skyr-Senf-Füllung',
    ck: 'Gefüllte Eier',
    img: { wiki: 'Deviled egg', q: 'deviled eggs paprika' },
    cu: 'amerikanisch', m: ['snack'], t: 20, d: 1, st: ['kinderliebling'],
    i: [['ei', 120], ['skyr', 30], ['senf', 5], ['gewuerze', 1], ['salz', 0.3], ['kraeuter', 2], ['gurke', 80]],
    s: [
      'Eier 10 Min. hart kochen, kalt abschrecken und schälen.',
      'Längs halbieren, Eigelb herauslösen und mit Skyr und Senf glatt rühren.',
      'Baby-/Kleinkind-Portion ohne Senf und Salz abnehmen, Rest mit Salz und Pfeffer abschmecken.',
      'Creme mit einem Spritzbeutel oder Teelöffel in die Eiweißhälften füllen.',
      'Mit geräuchertem Paprikapulver und Schnittlauch bestreuen, mit Gurkenscheiben servieren.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen (8 Eier).', steps: [
      ['500 g Wasser in den Mixtopf füllen, Eier in den Varoma-Behälter legen und garen.', '16 Min.', 'Varoma', 'Stufe 1', ''],
      ['Eier abschrecken, schälen, halbieren. Eigelb, Skyr und Senf in den Mixtopf geben und cremig rühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Kinderportion entnehmen.', '', '', '', ''],
      ['Salz und Pfeffer zugeben und unterrühren.', '5 Sek.', '', 'Stufe 3', ''],
      ['Füllung in die Eiweißhälften spritzen und garnieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Eiweißhälfte in Streifen und Eigelb-Skyr-Creme (ohne Senf/Salz) zum Dippen; Ei vollständig durchgegart. Kleinkind (1–3 J.): gefülltes Ei geviertelt, mild ohne Senf.',
    baby: 2,
  },
  {
    id: 'pizza-eiermuffins',
    n: 'Pizza-Eiermuffins mit Schinken und Mozzarella',
    ck: 'Pizza Muffins',
    img: { q: 'egg muffins pizza ham mozzarella' },
    cu: 'italienisch', m: ['snack', 'fruehstueck'], t: 30, d: 1, st: ['mealprep', 'kinderliebling'],
    i: [['ei', 90], ['eiklar', 60], ['schinken_gekocht', 30], ['mozzarella', 30], ['paprika', 40], ['tomatenmark', 10], ['gewuerze', 1], ['rapsoel', 2]],
    s: [
      'Ofen auf 180 °C vorheizen, Muffinform leicht einfetten.',
      'Eier, Eiklar und Tomatenmark verquirlen, mit Oregano und Pfeffer würzen.',
      'Schinken, Paprika und Mozzarella klein würfeln und in die Mulden verteilen (Kinderportion ohne Schinken).',
      'Eimasse darübergießen und 18–20 Min. goldbraun backen.',
      'Leicht abkühlen lassen und warm oder kalt als Snack essen.',
    ],
    tm: { fit: 1, note: 'Für ca. 12 Muffins (4 Portionen). Backen im Ofen.', steps: [
      ['Paprika in Stücken in den Mixtopf geben und zerkleinern, umfüllen.', '3 Sek.', '', 'Stufe 4', ''],
      ['Eier, Eiklar, Tomatenmark, Oregano und Pfeffer in den Mixtopf geben und verquirlen.', '15 Sek.', '', 'Stufe 4', ''],
      ['Paprika, Schinken und Mozzarella in die Form verteilen, Eimasse darübergießen.', '', '', '', ''],
      ['Im Ofen bei 180 °C 18–20 Min. backen.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Muffins ohne Schinken (salzig/gepökelt), in Streifen geschnitten als Fingerfood, gut durchgebacken. Kleinkind (1–3 J.): ganze Mini-Muffins, wenig Schinken.',
    baby: 1,
  },
  {
    id: 'eiersalat-gurkenschiffchen',
    n: 'Eiersalat mit Skyr in Gurkenschiffchen',
    ck: 'Eiersalat',
    img: { wiki: 'Egg salad', q: 'egg salad cucumber boats' },
    cu: 'deutsch', m: ['snack'], t: 20, d: 1, st: ['mealprep'],
    i: [['ei', 120], ['skyr', 40], ['senf', 5], ['kraeuter', 3], ['salz', 0.5], ['gewuerze', 1], ['gurke', 200]],
    s: [
      'Eier 10 Min. hart kochen, abschrecken, schälen und fein würfeln.',
      'Skyr mit Senf, Schnittlauch und einer Prise Curry verrühren, Eier unterheben.',
      'Kinderportion ohne Salz und Senf abnehmen, Rest abschmecken.',
      'Gurke längs halbieren und die Kerne mit einem Teelöffel herauskratzen.',
      'Eiersalat in die Gurkenhälften füllen und in 4 cm breite Schiffchen schneiden.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen.', steps: [
      ['500 g Wasser in den Mixtopf füllen, Eier in den Varoma-Behälter legen und garen.', '16 Min.', 'Varoma', 'Stufe 1', ''],
      ['Eier abschrecken, schälen und in den leeren Mixtopf geben, grob zerkleinern.', '3 Sek.', '', 'Stufe 4', ''],
      ['Skyr, Senf, Schnittlauch und Curry zugeben und vermengen.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Kinderportion entnehmen, Rest salzen und kurz untermischen.', '5 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['In ausgehöhlte Gurkenhälften füllen und schneiden.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Eiersalat ohne Senf und Salz, mit Gabel fein zerdrückt, auf weichen geschälten Gurkenstücken. Kleinkind (1–3 J.): Gurkenschiffchen klein geschnitten, mild.',
    baby: 2,
  },
  {
    id: 'ofen-scotch-eggs-pute',
    n: 'Ofen-Scotch-Eggs mit Putenhack',
    ck: 'Scotch Eggs',
    img: { wiki: 'Scotch egg', q: 'scotch egg' },
    cu: 'international', m: ['snack'], t: 40, d: 2, st: ['mealprep'],
    i: [['ei', 60], ['putenhack', 70], ['eiklar', 15], ['paniermehl', 10], ['senf', 3], ['gewuerze', 2], ['salz', 0.5], ['skyr', 30], ['kraeuter', 2]],
    s: [
      'Eier 7 Min. wachsweich bis hart kochen, kalt abschrecken und schälen. Ofen auf 200 °C vorheizen.',
      'Putenhack mit Senf, Paprikapulver, Thymian, Salz und Pfeffer verkneten.',
      'Hack flach drücken, jedes Ei damit vollständig umhüllen.',
      'Erst durch verquirltes Eiklar, dann durch Paniermehl (glutenfrei: glutenfreies Paniermehl) rollen.',
      'Auf Backpapier 20–25 Min. goldbraun backen. Halbiert mit Skyr-Kräuter-Dip servieren.',
    ],
    tm: { fit: 1, note: 'Für 4 Scotch Eggs. Backen im Ofen.', steps: [
      ['500 g Wasser in den Mixtopf füllen, Eier in den Varoma-Behälter legen und garen, abschrecken.', '14 Min.', 'Varoma', 'Stufe 1', ''],
      ['Putenhack, Senf, Gewürze und Salz in den Mixtopf geben und vermengen.', '20 Sek.', '', 'Stufe 4', 'Linkslauf'],
      ['Eier mit Hack umhüllen, panieren und im Ofen bei 200 °C 20–25 Min. backen.', '', '', '', ''],
      ['Mixtopf spülen, Kräuter zerkleinern, Skyr zugeben und verrühren.', '10 Sek.', '', 'Stufe 4', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Hackmasse ohne Salz und Senf für das Kinder-Ei verwenden, Ei ganz durchgaren und in Spalten schneiden. Kleinkind (1–3 J.): Viertel mit Dip, mild gewürzt.',
    baby: 1,
  },
  /* ---------- Röllchen & Wraps ---------- */
  {
    id: 'zucchini-roellchen-ricotta-schinken',
    n: 'Gegrillte Zucchini-Röllchen mit Ricotta und Schinken',
    ck: 'Zucchini Röllchen',
    img: { q: 'zucchini rolls ricotta' },
    cu: 'italienisch', m: ['snack'], t: 25, d: 2,
    i: [['zucchini', 150], ['ricotta', 40], ['magerquark', 50], ['schinken_gekocht', 40], ['olivenoel', 5], ['kraeuter', 3], ['salz', 0.3], ['gewuerze', 1]],
    s: [
      'Zucchini längs in 3 mm dünne Scheiben hobeln, dünn mit Olivenöl bestreichen.',
      'In einer Grillpfanne 1–2 Min. pro Seite grillen, bis sie weich und gestreift sind. Abkühlen lassen.',
      'Ricotta mit Magerquark, gehacktem Basilikum, Zitronenabrieb, Salz und Pfeffer verrühren.',
      'Zucchinischeiben mit Creme bestreichen, eine halbe Scheibe Schinken auflegen.',
      'Aufrollen und mit Zahnstochern feststecken.',
    ],
    tm: { fit: 0, note: 'Zucchini in der Grillpfanne, nur die Füllung im Thermomix.', steps: [
      ['Zucchinischeiben in der Grillpfanne grillen.', '', '', '', ''],
      ['Basilikum in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Ricotta, Magerquark, Salz und Pfeffer zugeben und verrühren.', '15 Sek.', '', 'Stufe 3', ''],
      ['Zucchini bestreichen, mit Schinken belegen und aufrollen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): weiche gegrillte Zucchinistreifen mit ungesalzener Ricotta-Creme, ohne Schinken. Kleinkind (1–3 J.): Röllchen ohne Zahnstocher, in Stücke geschnitten.',
    baby: 2,
  },
  {
    id: 'salatwraps-haehnchen-erdnuss',
    n: 'Salat-Wraps mit Hähnchen und Erdnuss-Limetten-Sauce',
    ck: 'Salatwraps Hähnchen',
    img: { wiki: 'Lettuce wrap', q: 'chicken lettuce wraps' },
    cu: 'asiatisch', m: ['snack'], t: 20, d: 1,
    i: [['haehnchenbrust', 100], ['salat', 50], ['karotte', 40], ['gurke', 50], ['erdnussbutter', 10], ['sojasauce', 8], ['limette', 10], ['ingwer', 3], ['rapsoel', 4]],
    s: [
      'Hähnchenbrust in feine Streifen schneiden und in Rapsöl 5–6 Min. durchbraten.',
      'Erdnussmus mit Sojasauce (glutenfrei: Tamari), Limettensaft, geriebenem Ingwer und 2 EL warmem Wasser glatt rühren.',
      'Karotte und Gurke in feine Streifen schneiden.',
      'Romanasalatblätter mit Hähnchen und Gemüse füllen.',
      'Mit der Erdnusssauce beträufeln und wie einen Wrap einrollen.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen. Hähnchen im Varoma.', steps: [
      ['500 g Wasser in den Mixtopf füllen, Hähnchenstreifen in den Varoma-Behälter legen und garen.', '18 Min.', 'Varoma', 'Stufe 1', ''],
      ['Mixtopf leeren. Ingwer in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
      ['Erdnussmus, Sojasauce, Limettensaft und 2 EL Wasser zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
      ['Salatblätter füllen und mit Sauce beträufeln.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Hähnchen fein gezupft mit einem Klecks Erdnussmus (ohne Sojasauce) verrührt – früh eingeführt beugt Allergien vor. Kleinkind (1–3 J.): Hähnchenstreifen und Gurke zum Dippen in milde Erdnusssauce.',
    baby: 2,
  },
  /* ---------- Hähnchen-, Puten- & Tofu-Bites ---------- */
  {
    id: 'sesam-haehnchen-bites-tamari',
    n: 'Sesam-Hähnchen-Bites mit Tamari-Ingwer-Dip',
    ck: 'Sesam Hähnchen',
    img: { q: 'sesame chicken bites' },
    cu: 'asiatisch', m: ['snack'], t: 25, d: 1, st: ['kinderliebling'],
    i: [['haehnchenbrust', 120], ['sesam', 8], ['speisestaerke', 5], ['sojasauce', 10], ['rapsoel', 5], ['ingwer', 3], ['knoblauch', 3], ['limette', 5]],
    s: [
      'Hähnchenbrust in 2 cm große Würfel schneiden, mit der Hälfte der Sojasauce (glutenfrei: Tamari) und Knoblauch 10 Min. marinieren.',
      'Würfel in Speisestärke wenden und dann in Sesam drücken.',
      'Rapsöl in einer Pfanne erhitzen und die Bites rundum 6–7 Min. goldbraun und durchgaren (alternativ 15 Min. bei 200 °C im Ofen).',
      'Restliche Sojasauce mit geriebenem Ingwer und Limettensaft zum Dip verrühren.',
      'Bites auf Spießchen stecken und mit Dip servieren.',
    ],
    tm: { fit: 0, note: 'Bites in Pfanne oder Ofen, nur der Dip im Thermomix.', steps: [
      ['Ingwer und Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
      ['Sojasauce und Limettensaft zugeben und verrühren, die Hälfte als Marinade verwenden.', '5 Sek.', '', 'Stufe 3', ''],
      ['Hähnchen marinieren, panieren und in der Pfanne braten.', '', '', '', ''],
      ['Mit dem restlichen Dip servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Hähnchen ohne Sojasauce marinieren, Sesam fein gemahlen, Bites in Streifen schneiden. Kleinkind (1–3 J.): ganze Bites ohne Spieß, Dip mit Wasser verdünnt.',
    baby: 1,
  },
  {
    id: 'buffalo-haehnchen-bites-skyr-dip',
    n: 'Buffalo-Hähnchen-Bites mit Skyr-Kräuter-Dip und Selleriesticks',
    ck: 'Chicken Wings Ofen',
    img: { wiki: 'Buffalo wing', q: 'buffalo chicken bites celery dip' },
    cu: 'amerikanisch', m: ['snack'], t: 25, d: 1,
    i: [['haehnchenbrust', 120], ['sriracha', 10], ['butter', 3], ['gewuerze', 2], ['salz', 0.5], ['skyr', 60], ['kraeuter', 3], ['knoblauch', 3], ['sellerie', 40], ['karotte', 60]],
    s: [
      'Ofen auf 220 °C vorheizen. Hähnchen in 3 cm große Würfel schneiden, mit Paprikapulver, Knoblauchpulver und Salz würzen.',
      'Auf Backpapier 12–15 Min. backen, bis sie durchgegart sind. Kinderportion jetzt entnehmen.',
      'Butter schmelzen, mit Sriracha verrühren und die restlichen Bites darin schwenken.',
      'Skyr mit fein geriebenem Knoblauch, gehacktem Schnittlauch und Dill verrühren.',
      'Bites mit Dip, Sellerie- und Karottensticks servieren.',
    ],
    tm: { fit: 0, note: 'Bites im Ofen, nur der Dip im Thermomix.', steps: [
      ['Hähnchen im Ofen backen, Kinderportion entnehmen.', '', '', '', ''],
      ['Knoblauch und Kräuter in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Skyr zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ['Butter mit Sriracha schmelzen, Bites darin schwenken und mit Dip servieren.', '', '', '', ''],
    ] },
    kid: 'Scharfe Sauce nur für Erwachsene. Baby (6–12 Mon.): ungewürzte Hähnchenstreifen aus dem Ofen mit Skyr-Dip (ohne Knoblauch). Kleinkind (1–3 J.): Bites ohne Buffalo-Sauce, Karotte blanchiert.',
    baby: 1,
  },
  {
    id: 'puten-zucchini-baellchen',
    n: 'Puten-Zucchini-Bällchen mit Tomatendip',
    ck: 'Hackbällchen Pute',
    img: { wiki: 'Meatball', q: 'turkey zucchini meatballs' },
    cu: 'mediterran', m: ['snack'], t: 30, d: 1, st: ['mealprep', 'kinderliebling'],
    i: [['putenhack', 100], ['zucchini', 60], ['ei', 15], ['haferflocken', 10], ['gewuerze', 2], ['salz', 0.5], ['rapsoel', 3], ['passierte_tomaten', 60], ['kraeuter', 2]],
    s: [
      'Ofen auf 200 °C vorheizen. Zucchini fein raspeln und kräftig ausdrücken.',
      'Putenhack mit Zucchini, Ei, Haferflocken (glutenfrei: zertifizierte Haferflocken) und Oregano verkneten. Kinderportion ungesalzen formen, Rest salzen.',
      'Walnussgroße Bällchen formen, auf ein mit Öl bestrichenes Blech legen und 15–18 Min. backen.',
      'Passierte Tomaten mit Basilikum 5 Min. einköcheln lassen.',
      'Bällchen auf Spießchen mit Tomatendip servieren – warm oder kalt.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen. Bällchen alternativ im Varoma garen (25 Min.), dann ohne Kruste.', steps: [
      ['Zucchini in Stücken in den Mixtopf geben und zerkleinern, ausdrücken.', '4 Sek.', '', 'Stufe 5', ''],
      ['Putenhack, Ei, Haferflocken und Oregano zugeben und vermengen.', '20 Sek.', '', 'Stufe 4', 'Linkslauf'],
      ['Bällchen formen (Kinderportion ungesalzen) und im Ofen bei 200 °C 15–18 Min. backen.', '', '', '', ''],
      ['Passierte Tomaten und Basilikum in den Mixtopf geben und einköcheln.', '5 Min.', '100°C', 'Stufe 1', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzene Bällchen als weiches Fingerfood, in Hälften geteilt, mit Tomatensauce. Kleinkind (1–3 J.): ganze Bällchen, toll für die Brotdose.',
    baby: 2,
  },
  {
    id: 'caprese-haehnchen-spiesschen',
    n: 'Caprese-Hähnchen-Spießchen mit Balsamico',
    ck: 'Tomate Mozzarella Spieße',
    img: { wiki: 'Caprese salad', q: 'caprese skewers chicken' },
    cu: 'italienisch', m: ['snack'], t: 20, d: 1, st: ['kinderliebling'],
    i: [['haehnchenbrust', 80], ['mozzarella', 50], ['kirschtomaten', 80], ['kraeuter', 3], ['olivenoel', 5], ['essig', 5], ['salz', 0.3], ['gewuerze', 1]],
    s: [
      'Hähnchenbrust in 2 cm große Würfel schneiden, mit italienischen Kräutern würzen und in 2 g Olivenöl 6–7 Min. durchbraten. Abkühlen lassen.',
      'Mozzarella in Würfel schneiden, Kirschtomaten halbieren.',
      'Abwechselnd Hähnchen, Tomate, Basilikumblatt und Mozzarella auf Spießchen stecken.',
      'Restliches Olivenöl mit Balsamico, Salz und Pfeffer verrühren und über die Spieße träufeln.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen. Hähnchen im Varoma garen.', steps: [
      ['500 g Wasser in den Mixtopf füllen, gewürzte Hähnchenwürfel in den Varoma-Behälter legen und garen.', '18 Min.', 'Varoma', 'Stufe 1', ''],
      ['Abkühlen lassen.', '', '', '', ''],
      ['Mixtopf leeren. Öl, Balsamico, Salz und Pfeffer in den Mixtopf geben und emulgieren.', '10 Sek.', '', 'Stufe 4', ''],
      ['Spieße stecken und beträufeln.', '', '', '', ''],
    ] },
    kid: 'Kirschtomaten immer vierteln (Verschluckungsgefahr). Baby (6–12 Mon.): Hähnchen und Mozzarella in Streifen, Tomate geviertelt, ohne Dressing. Kleinkind (1–3 J.): ohne Spieß servieren.',
    baby: 2,
  },
  /* ---------- Fisch-Häppchen ---------- */
  {
    id: 'raeucherlachs-gurken-haeppchen',
    n: 'Räucherlachs-Gurken-Häppchen mit Dill-Skyr',
    ck: 'Gurkenhäppchen Lachs',
    img: { wiki: 'Smoked salmon', q: 'smoked salmon cucumber bites' },
    cu: 'international', m: ['snack'], t: 10, d: 1,
    i: [['gurke', 150], ['raeucherlachs', 50], ['frischkaese_light', 20], ['skyr', 40], ['kraeuter', 3], ['zitronensaft', 5]],
    s: [
      'Gurke in 1 cm dicke Scheiben schneiden und trocken tupfen.',
      'Frischkäse mit Skyr, gehacktem Dill, Zitronensaft und Pfeffer glatt rühren.',
      'Je einen Klecks Creme auf die Gurkenscheiben spritzen oder streichen.',
      'Räucherlachs in Streifen schneiden, zu Röschen drehen und auflegen.',
      'Mit Dillspitzen garnieren und gekühlt servieren.',
    ],
    tm: { fit: 0, note: 'Nur die Dillcreme im Thermomix.', steps: [
      ['Dill in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Frischkäse, Skyr, Zitronensaft und Pfeffer zugeben und verrühren.', '15 Sek.', '', 'Stufe 3', ''],
      ['Creme auf Gurkenscheiben geben.', '', '', '', ''],
      ['Mit Lachsröschen belegen und garnieren.', '', '', '', ''],
    ] },
    kid: 'Räucherlachs ist roh geräuchert und salzig – nicht für Baby und Kleinkind. Kinder-Häppchen: Gurkenscheiben mit Dill-Skyr und etwas gegartem, zerpflücktem Lachs (Baby: Gurke geschält, weich).',
    baby: 0,
  },
  {
    id: 'garnelen-spiesschen-limetten-dip',
    n: 'Knoblauch-Garnelen-Spießchen mit Limetten-Skyr-Dip',
    ck: 'Garnelenspieße',
    img: { q: 'shrimp skewers lime dip' },
    cu: 'mediterran', m: ['snack'], t: 20, d: 1,
    i: [['garnelen', 120], ['olivenoel', 5], ['knoblauch', 3], ['chili_frisch', 2], ['limette', 10], ['skyr', 60], ['kraeuter', 3], ['salz', 0.3], ['zucchini', 80]],
    s: [
      'Garnelen auftauen lassen und trocken tupfen. Zucchini in 1 cm dicke Halbmonde schneiden.',
      'Garnelen mit Olivenöl, Knoblauch und Limettenabrieb mischen und abwechselnd mit Zucchini auf Spießchen stecken.',
      'In einer Grillpfanne 2–3 Min. pro Seite braten, bis die Garnelen rosa und durchgegart sind. Mit Salz und Chili würzen.',
      'Skyr mit Limettensaft und gehacktem Koriander verrühren.',
      'Spießchen mit Dip servieren.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen. Garnelen alternativ im Varoma (8–10 Min.).', steps: [
      ['Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
      ['Olivenöl und Limettenabrieb zugeben, verrühren und über die Garnelen geben.', '5 Sek.', '', 'Stufe 3', ''],
      ['Spieße stecken und in der Grillpfanne braten.', '', '', '', ''],
      ['Mixtopf ausspülen. Koriander zerkleinern, Skyr und Limettensaft zugeben und verrühren.', '10 Sek.', '', 'Stufe 4', ''],
    ] },
    kid: 'Baby (ab 8 Mon.): Garnelen ohne Chili und Salz komplett durchgaren und klein schneiden, Zucchini weich. Kleinkind (1–3 J.): ohne Spieß und Chili, mit Skyr-Dip.',
    baby: 1,
  },
  /* ---------- Hüttenkäse ---------- */
  /* ---------- Edamame & Kichererbsen ---------- */
  {
    id: 'geroestete-kichererbsen-edamame',
    n: 'Geröstete Kichererbsen und Edamame mit Paprika',
    ck: 'Geröstete Kichererbsen',
    img: { wiki: 'Chickpea', q: 'roasted chickpeas snack' },
    cu: 'orientalisch', m: ['snack'], t: 40, d: 1, st: ['mealprep'],
    i: [['kichererbsen', 42], ['edamame', 80], ['olivenoel', 5], ['gewuerze', 2], ['salz', 0.5], ['kuerbiskerne', 8]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Kichererbsen abspülen und mit Küchenpapier sehr gründlich trocken tupfen, lose Häutchen entfernen.',
      'Edamame auftauen und ebenfalls trocken tupfen.',
      'Mit Olivenöl, geräuchertem Paprikapulver und Kreuzkümmel mischen und auf einem Blech verteilen.',
      'Ca. 30 Min. rösten, alle 10 Min. rütteln; in den letzten 5 Min. Kürbiskerne zugeben.',
      'Noch warm salzen und auskühlen lassen – erst dann werden sie richtig knusprig.',
    ],
    tm: { fit: 0, note: 'Rösten im Ofen, im Thermomix nur das Würzöl.', steps: [
      ['Olivenöl, Paprikapulver und Kreuzkümmel in den Mixtopf geben und verrühren.', '5 Sek.', '', 'Stufe 3', ''],
      ['Mit Kichererbsen und Edamame mischen.', '', '', '', ''],
      ['Im Ofen bei 200 °C ca. 30 Min. rösten, Kürbiskerne zum Schluss zugeben.', '', '', '', ''],
      ['Salzen und auskühlen lassen.', '', '', '', ''],
    ] },
    kid: 'Geröstete Hülsenfrüchte und Kerne sind hart – Verschluckungsgefahr bis 4 J. Baby/Kleinkind: Kichererbsen und Edamame weich gegart und zerdrückt, ungesalzen, mit etwas Öl und mildem Paprika.',
    baby: 1,
  },
  /* ---------- Reiswaffel- & Knäcke-Toppings ---------- */
  {
    id: 'knaecke-ei-schnittlauchquark',
    n: 'Knäckebrot mit Schnittlauchquark, Ei und Tomate',
    ck: 'Schnittlauchquark',
    img: { wiki: 'Crispbread', q: 'crispbread egg chives quark' },
    cu: 'deutsch', m: ['snack'], t: 15, d: 1,
    i: [['snacks_knaecke_gf', 20], ['magerquark', 80], ['ei', 60], ['kraeuter', 4], ['salz', 0.3], ['tomate', 50]],
    s: [
      'Ei 9 Min. hart kochen, abschrecken, schälen und in Scheiben schneiden.',
      'Magerquark mit reichlich Schnittlauch, Salz und Pfeffer verrühren.',
      'Glutenfreies Knäckebrot dick mit dem Quark bestreichen.',
      'Mit Ei- und Tomatenscheiben belegen und mit Schnittlauch bestreuen.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen. Eier im Varoma.', steps: [
      ['500 g Wasser in den Mixtopf füllen, Eier in den Varoma-Behälter legen und garen, abschrecken.', '16 Min.', 'Varoma', 'Stufe 1', ''],
      ['Mixtopf leeren. Schnittlauch zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
      ['Magerquark, Salz und Pfeffer zugeben und verrühren (Kinderportion vorher ungesalzen entnehmen).', '10 Sek.', '', 'Stufe 3', ''],
      ['Knäckebrot bestreichen und belegen.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): ungesalzener Schnittlauchquark auf weichem Brotstreifen, Ei durchgegart und zerdrückt, Tomate geschält. Kleinkind (1–3 J.): Knäcke in Stücken, Ei in Scheiben.',
    baby: 2,
  },
  /* ---------- Protein-Chips ---------- */
  /* ---------- Gemüse-Pizzabällchen ---------- */
  {
    id: 'gemuese-pizzabaellchen',
    n: 'Gemüse-Pizzabällchen mit Mozzarella und Tomatendip',
    ck: 'Pizzabällchen',
    img: { q: 'vegetable pizza bites balls' },
    cu: 'italienisch', m: ['snack'], t: 35, d: 1, st: ['mealprep', 'kinderliebling'],
    i: [['zucchini', 80], ['magerquark', 40], ['ei', 30], ['mozzarella', 40], ['kichererbsenmehl', 20], ['tomatenmark', 10], ['gewuerze', 2], ['salz', 0.5], ['parmesan', 5], ['passierte_tomaten', 50]],
    s: [
      'Ofen auf 200 °C vorheizen. Zucchini fein raspeln, salzen, 5 Min. ziehen lassen und kräftig ausdrücken.',
      'Mozzarella klein würfeln.',
      'Zucchini, Quark, Ei, Kichererbsenmehl, Tomatenmark, Mozzarella, Parmesan und Oregano zu einem formbaren Teig mischen.',
      'Mit feuchten Händen walnussgroße Bällchen formen, auf Backpapier setzen und 18–20 Min. goldbraun backen.',
      'Passierte Tomaten mit Oregano erwärmen und als Dip dazu reichen.',
    ],
    tm: { fit: 1, note: 'Für ca. 16 Bällchen (4 Portionen). Backen im Ofen.', steps: [
      ['Zucchini in Stücken in den Mixtopf geben und zerkleinern, ausdrücken.', '4 Sek.', '', 'Stufe 5', ''],
      ['Zucchini, Quark, Ei, Kichererbsenmehl, Tomatenmark, Parmesan und Oregano in den Mixtopf geben und vermengen.', '20 Sek.', '', 'Stufe 4', 'Linkslauf'],
      ['Mozzarellawürfel zugeben und unterheben.', '10 Sek.', '', 'Stufe 2', 'Linkslauf'],
      ['Bällchen formen und im Ofen bei 200 °C 18–20 Min. backen.', '', '', '', ''],
      ['Mixtopf spülen, passierte Tomaten und Oregano erwärmen.', '4 Min.', '90°C', 'Stufe 1', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Zucchini nicht salzen, Bällchen etwas flacher als weiche Taler backen – ideales BLW-Fingerfood. Kleinkind (1–3 J.): ganze Bällchen mit Tomatendip, toll für die Kita-Dose.',
    baby: 2,
  },
  /* ---------- Süßes Fingerfood ---------- */
  {
    id: 'schoko-protein-crispies',
    n: 'Schoko-Protein-Crispies mit Erdnuss',
    ck: 'Schoko Crossies',
    img: { q: 'chocolate rice crispy clusters' },
    cu: 'international', m: ['snack'], t: 20, d: 1, st: ['mealprep'],
    i: [['puffreis', 15], ['esn_designer_whey', 20], ['zartbitter', 12], ['erdnussbutter', 8], ['milch', 15]],
    s: [
      'Zartbitterschokolade über dem Wasserbad schmelzen und mit Erdnussmus verrühren.',
      'Whey mit Milch zu einer dicken Paste glatt rühren und unter die Schokolade mischen.',
      'Puffreis unterheben, bis alles gleichmäßig überzogen ist.',
      'Mit zwei Teelöffeln kleine Häufchen auf Backpapier setzen.',
      'Ca. 30 Min. im Kühlschrank fest werden lassen; gekühlt eine Woche haltbar.',
    ],
    tm: { fit: 2, note: 'Für ca. 4 Portionen (ca. 16 Crispies).', steps: [
      ['Schokolade in Stücken in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 8', ''],
      ['Erdnussmus zugeben und schmelzen.', '3 Min.', '50°C', 'Stufe 2', ''],
      ['Milch und Whey zugeben und verrühren.', '15 Sek.', '', 'Stufe 3', ''],
      ['Puffreis zugeben und unterheben.', '20 Sek.', '', 'Stufe 1', 'Linkslauf'],
      ['Häufchen auf Backpapier setzen und kühlen.', '', '', '', ''],
    ] },
    kid: 'Enthält Proteinpulver und Schokolade – nicht für Baby und Kleinkind. Kinder-Variante: Puffreis mit Erdnussmus und zerdrückter Banane zu weichen Talern formen.',
    baby: 0,
  },
  {
    id: 'erdbeeren-vanillequark-dip',
    n: 'Erdbeeren mit Vanillequark-Dip und Schoko-Mandel-Crunch',
    ck: 'Quark Dip süß',
    img: { wiki: 'Strawberry', q: 'strawberries yogurt dip' },
    cu: 'deutsch', m: ['snack'], t: 10, d: 1, st: ['kinderliebling'],
    i: [['erdbeeren', 150], ['magerquark', 150], ['vanille', 1], ['erythrit', 8], ['milch', 20], ['zartbitter', 5], ['mandeln', 5]],
    s: [
      'Erdbeeren waschen, trocken tupfen und das Grün dranlassen (zum Anfassen).',
      'Magerquark mit Milch, Vanille und Erythrit cremig rühren.',
      'Mandeln und Zartbitterschokolade grob hacken.',
      'Dip in ein Schälchen füllen, Schoko-Mandel-Crunch darüberstreuen.',
      'Erdbeeren in den Dip tunken und genießen.',
    ],
    tm: { fit: 1, note: 'Für ca. 4 Portionen.', steps: [
      ['Mandeln und Schokolade in den Mixtopf geben und grob hacken, umfüllen.', '3 Sek.', '', 'Stufe 6', ''],
      ['Erythrit in den Mixtopf geben und pulverisieren.', '10 Sek.', '', 'Stufe 10', ''],
      ['Quark, Milch und Vanille zugeben und cremig rühren.', '20 Sek.', '', 'Stufe 4', ''],
      ['Dip anrichten, mit Crunch bestreuen und mit Erdbeeren servieren.', '', '', '', ''],
    ] },
    kid: 'Baby (6–12 Mon.): Quark ohne Erythrit und Schokolade, Erdbeeren längs geviertelt, Mandeln nur fein gemahlen. Kleinkind (1–3 J.): Erdbeeren halbiert, Crunch aus gemahlenen Mandeln.',
    baby: 2,
  },
]);
