// Vegetarische Hauptgerichte: proteinreich mit Eiern, Quark, Käse, Tofu, Tempeh, Soja und Hülsenfrüchten
(typeof window !== 'undefined' ? window : globalThis).RECIPES = ((typeof window !== 'undefined' ? window : globalThis).RECIPES || []).concat([
  {
    id: 'linsen-bolognese',
    n: 'Linsen-Bolognese mit Vollkornspaghetti',
    img: { wiki: 'Bolognese sauce', q: 'lentil bolognese spaghetti vegetarian' },
    ck: 'Linsenbolognese',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['mealprep', 'kinderliebling'],
    i: [['rote_linsen', 45], ['sojaschnetzel', 15], ['vollkornnudeln', 65], ['passierte_tomaten', 180], ['karotte', 60], ['sellerie', 30], ['zwiebel', 50], ['knoblauch', 4], ['tomatenmark', 15], ['olivenoel', 6], ['gewuerze', 2], ['salz', 1], ['parmesan', 8], ['kraeuter', 3]],
    s: [
      'Zwiebel, Knoblauch, Karotte und Sellerie sehr fein würfeln. Rote Linsen in einem Sieb abspülen, Sojaschnetzel 10 Min. in heißem Wasser einweichen und gut ausdrücken.',
      'Öl in einem Topf erhitzen, Gemüsewürfel 5 Min. andünsten, Sojaschnetzel 3 Min. mitbraten und Tomatenmark 1 Min. anrösten.',
      'Linsen, passierte Tomaten und 200 ml Wasser zugeben und 15–18 Min. bei kleiner Hitze köcheln, bis die Linsen zerfallen. Parallel die Spaghetti nach Packungsangabe kochen.',
      'Baby-/Kleinkind-Portion vor dem Salzen entnehmen.',
      'Sauce mit Oregano, Pfeffer und Salz abschmecken, mit Spaghetti, Parmesan und Basilikum servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Die Nudeln separat im Topf kochen.',
      steps: [
        ['Zwiebel, Knoblauch, Karotte und Sellerie in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Eingeweichte Sojaschnetzel und Tomatenmark zugeben und mitdünsten.', '3 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Linsen, passierte Tomaten und 200 g Wasser zugeben, Garkörbchen als Spritzschutz auf den Deckel setzen und köcheln.', '18 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Salzen entnehmen.', '', '', '', ''],
        ['Oregano, Pfeffer und Salz zugeben und unterrühren.', '30 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Mit Spaghetti, Parmesan und Basilikum servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzene Linsensauce mit weich gekochten Nudeln fein pürieren oder kurze Nudeln für BLW in der dicken Sauce wälzen. Kleinkind (1–3 J.): kleine Nudeln wie Fusilli nehmen, Sauce mild lassen und etwas Parmesan darüberstreuen.',
    baby: 2,
  },
  {
    id: 'thai-tofu-kuerbis-curry',
    n: 'Rotes Thai-Curry mit Tofu & Kürbis',
    img: { wiki: 'Red curry', q: 'thai red curry tofu pumpkin' },
    ck: 'Thai Curry Tofu',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['comfort'],
    i: [['tofu', 190], ['kuerbis', 150], ['kokosmilch_light', 100], ['currypaste', 12], ['paprika', 80], ['spinat', 40], ['reis', 45], ['ingwer', 5], ['knoblauch', 4], ['rapsoel', 5], ['sojasauce', 8], ['limette', 10], ['kraeuter', 3]],
    s: [
      'Tofu trocken tupfen und in 2 cm große Würfel schneiden. Kürbis entkernen und in 2 cm Stücke, Paprika in Streifen schneiden. Ingwer und Knoblauch fein hacken. Reis nach Packungsangabe garen.',
      'Tofu in 2 TL Öl in einer Pfanne rundum 6–8 Min. goldbraun braten und herausnehmen.',
      'Restliches Öl in einem Topf erhitzen, Ingwer und Knoblauch 1 Min. anschwitzen, Kürbis, Paprika, Kokosmilch und 100 ml Wasser zugeben und 12 Min. köcheln.',
      'Baby-/Kleinkind-Portion (Kürbis, Tofu, etwas Sauce) jetzt ohne Currypaste und Sojasauce entnehmen.',
      'Currypaste und Sojasauce einrühren, Tofu und Spinat 2 Min. mitziehen lassen. Mit Limettensaft, Koriander und Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Tofu für die Röstaromen in der Pfanne braten.',
      steps: [
        ['Ingwer und Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl zugeben und andünsten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['Kokosmilch und 400 g Wasser zugeben, Reis im Garkörbchen einhängen, Kürbis und Paprika in den Varoma-Behälter geben, aufsetzen und garen.', '22 Min.', 'Varoma', 'Stufe 1', ''],
        ['Parallel den Tofu in der Pfanne 6–8 Min. goldbraun braten.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion Kürbis und Tofu ohne Currypaste entnehmen.', '', '', '', ''],
        ['Garkörbchen herausnehmen. Currypaste, Sojasauce, Gemüse aus dem Varoma und Spinat in die Sauce geben und erhitzen.', '3 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Tofu unterheben, mit Limette, Koriander und Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Kürbis und Tofu ohne Currypaste in Fingerstreifen anbieten oder mit etwas Kokosmilch und Reis zu Brei pürieren. Kleinkind (1–3 J.): ungewürzte Portion mit Kokossauce und Reis, Tofuwürfel halbieren, Schärfe ganz weglassen.',
    baby: 1,
  },
  {
    id: 'halloumi-kichererbsen-pfanne',
    n: 'Halloumi-Kichererbsen-Pfanne mit Zucchini',
    img: { wiki: 'Halloumi', q: 'fried halloumi chickpeas zucchini pan' },
    ck: 'Halloumi Pfanne',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['halloumi', 70], ['kichererbsen', 80], ['zucchini', 150], ['paprika', 100], ['kirschtomaten', 80], ['rote_zwiebel', 40], ['knoblauch', 4], ['olivenoel', 6], ['gewuerze', 2], ['skyr', 120], ['kraeuter', 4], ['zitronensaft', 8]],
    s: [
      'Halloumi in 1 cm dicke Scheiben, Zucchini in Halbmonde, Paprika in Streifen und Zwiebel in Spalten schneiden. Kichererbsen abspülen, Kirschtomaten halbieren.',
      'Halloumi in einer beschichteten Pfanne ohne Fett von jeder Seite 2 Min. goldbraun braten und herausnehmen.',
      'Öl in die Pfanne geben, Zwiebel, Zucchini und Paprika 6 Min. bei starker Hitze braten. Knoblauch, Kichererbsen und Tomaten 3 Min. mitbraten.',
      'Baby-/Kleinkind-Portion Gemüse und Kichererbsen ohne Gewürz entnehmen.',
      'Rest mit Paprikapulver, Kreuzkümmel und Zitronensaft würzen. Skyr mit Kräutern verrühren und alles mit dem Halloumi anrichten.',
    ],
    tm: {
      fit: 0,
      note: 'Gebraten wird in der Pfanne. Der Thermomix bereitet den Kräuter-Skyr zu.',
      steps: [
        ['Kräuter in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Skyr und die Hälfte des Zitronensafts zugeben und verrühren, umfüllen.', '10 Sek.', '', 'Stufe 3', ''],
        ['Halloumi ohne Fett in der Pfanne goldbraun braten, herausnehmen.', '', '', '', ''],
        ['Gemüse und Kichererbsen in Öl in der Pfanne braten, Baby-Portion ungewürzt entnehmen, Rest würzen.', '', '', '', ''],
        ['Mit Halloumi und Kräuter-Skyr servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Halloumi ist sehr salzig, deshalb weglassen. Weiche Zucchini- und Paprikastreifen als Fingerfood, Kichererbsen zerdrückt mit etwas Skyr. Kleinkind (1–3 J.): ein kleines Stück Halloumi, Kirschtomaten vierteln, Kichererbsen leicht anquetschen.',
    baby: 1,
  },
  {
    id: 'spinat-feta-kartoffelauflauf',
    n: 'Spinat-Feta-Auflauf mit Kartoffeln & Ei',
    img: { wiki: 'Spanakopita', q: 'spinach feta potato casserole egg' },
    ck: 'Kartoffel-Spinat-Auflauf',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 55, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['kartoffel', 200], ['spinat_tk', 150], ['feta', 40], ['ei', 120], ['huettenkaese', 100], ['milch', 50], ['zwiebel', 40], ['knoblauch', 4], ['olivenoel', 4], ['gewuerze', 1], ['salz', 0.5]],
    s: [
      'Ofen auf 190 °C Ober-/Unterhitze vorheizen. Kartoffeln schälen, in 3 mm dünne Scheiben schneiden und 8 Min. in Salzwasser vorgaren.',
      'Zwiebel und Knoblauch würfeln und im Öl 3 Min. andünsten. Aufgetauten Spinat gut ausdrücken und 2 Min. mitdünsten.',
      'Eier mit Hüttenkäse, Milch und Muskat verquirlen. Die Hälfte des Fetas zerbröseln und mit dem Spinat mischen.',
      'Kartoffeln und Spinat abwechselnd in eine gefettete Form schichten, Eiermasse darübergießen und restlichen Feta darüberbröseln.',
      '30 Min. backen, bis die Eimasse gestockt und die Oberfläche goldbraun ist. 5 Min. ruhen lassen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Kartoffeln im Varoma vorgaren, Backen im Ofen.',
      steps: [
        ['500 g Wasser in den Mixtopf füllen, Kartoffelscheiben in den Varoma-Behälter legen, aufsetzen und vorgaren. Wasser abgießen.', '15 Min.', 'Varoma', 'Stufe 1', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Ausgedrückten Spinat zugeben und mitdünsten.', '3 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Eier, Hüttenkäse, Milch, Muskat und die Hälfte des Fetas zugeben und verrühren.', '15 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Kartoffeln in eine Form schichten, Spinat-Eier-Masse darübergießen, restlichen Feta darüberbröseln und 30 Min. bei 190 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): eine kleine Form ohne Feta und Salz vorbereiten. Gut durchgebackene Auflaufstreifen sind prima BLW-Fingerfood, für Brei mit etwas Milch zerdrücken. Kleinkind (1–3 J.): normale Portion in Würfeln, Feta in kleinen Mengen ist in Ordnung.',
    baby: 2,
  },
  {
    id: 'kichererbsen-shakshuka',
    n: 'Kichererbsen-Shakshuka mit Feta',
    img: { wiki: 'Shakshouka', q: 'shakshuka chickpeas feta skillet' },
    ck: 'Shakshuka',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['comfort'],
    i: [['ei', 120], ['kichererbsen', 80], ['tomaten_dose', 250], ['paprika', 100], ['zwiebel', 50], ['knoblauch', 4], ['olivenoel', 6], ['gewuerze', 3], ['feta', 30], ['kraeuter', 4], ['vollkornbrot', 50], ['salz', 0.5]],
    s: [
      'Zwiebel, Knoblauch und Paprika würfeln, Kichererbsen abspülen.',
      'Öl in einer tiefen Pfanne erhitzen, Zwiebel und Paprika 5 Min. weich dünsten, Knoblauch, Kreuzkümmel und Paprikapulver 1 Min. mitrösten.',
      'Tomaten und Kichererbsen zugeben und 10 Min. offen einköcheln lassen. Baby-/Kleinkind-Portion der Sauce jetzt ungesalzen entnehmen.',
      'Restliche Sauce leicht salzen, 2 Mulden formen, die Eier hineinschlagen und zugedeckt 6–8 Min. stocken lassen.',
      'Feta darüberbröseln, mit Petersilie bestreuen und mit Vollkornbrot servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Die Sauce entsteht im Thermomix, die Eier stocken in der Pfanne.',
      steps: [
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Paprikawürfel zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Gewürze, Tomaten und Kichererbsen zugeben und einköcheln, Garkörbchen als Spritzschutz aufsetzen.', '12 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion ungesalzen entnehmen.', '', '', '', ''],
        ['Sauce in eine Pfanne umfüllen, Eier hineinschlagen und zugedeckt 6–8 Min. stocken lassen.', '', '', '', ''],
        ['Mit Feta, Petersilie und Brot servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Ei vollständig durchgaren (Eigelb fest), mit ungesalzener Sauce und zerdrückten Kichererbsen mischen oder Brotstreifen zum Dippen geben. Kleinkind (1–3 J.): Ei durchgegart, Kichererbsen leicht zerdrücken, wenig Feta.',
    baby: 1,
  },
  {
    id: 'tempeh-erdnuss-bowl',
    n: 'Tempeh-Bowl mit Erdnusssauce',
    img: { wiki: 'Tempeh', q: 'tempeh bowl peanut sauce rice vegetables' },
    ck: 'Tempeh Bowl',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['mealprep'],
    i: [['tempeh', 120], ['vollkornreis', 45], ['edamame', 50], ['karotte', 60], ['gurke', 80], ['rotkohl', 50], ['erdnussbutter', 12], ['sojasauce', 10], ['limette', 10], ['ingwer', 4], ['rapsoel', 3], ['sesam', 3]],
    s: [
      'Vollkornreis nach Packungsangabe garen, Edamame die letzten 4 Min. mitgaren.',
      'Tempeh in 1 cm dicke Scheiben schneiden und in Öl 3–4 Min. pro Seite knusprig braten. Mit 1 TL Sojasauce ablöschen.',
      'Karotte und Rotkohl fein raspeln bzw. hobeln, Gurke in Scheiben schneiden.',
      'Für die Sauce Erdnussmus, restliche Sojasauce, Limettensaft, geriebenen Ingwer und 2–3 EL warmes Wasser glatt rühren.',
      'Reis in Schalen geben, Tempeh, Gemüse und Edamame darauf verteilen, mit Sauce beträufeln und mit Sesam bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Tempeh in der Pfanne braten.',
      steps: [
        ['1000 g Wasser in den Mixtopf füllen, Reis im Garkörbchen einhängen und garen, Edamame die letzten 5 Min. im Varoma-Behälter mitgaren.', '30 Min.', 'Varoma', 'Stufe 4', ''],
        ['Reis und Edamame umfüllen, Mixtopf leeren und abtrocknen.', '', '', '', ''],
        ['Karotte und Rotkohl in Stücken in den Mixtopf geben und raspeln, umfüllen.', '4 Sek.', '', 'Stufe 5', ''],
        ['Ingwer zerkleinern, dann Erdnussmus, Sojasauce, Limettensaft und 40 g warmes Wasser zugeben und verrühren.', '15 Sek.', '', 'Stufe 4', ''],
        ['Tempeh in der Pfanne knusprig braten und alles in Bowls anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Tempeh-Streifen ungesalzen braten, Karotte gedünstet statt roh, Edamame zerdrücken. Erdnussmus dünn mit Wasser verrührt (ohne Sojasauce) ist ein guter früher Allergenkontakt. Kleinkind (1–3 J.): Tempeh klein schneiden, Sauce mit wenig Sojasauce.',
    baby: 1,
  },
  {
    id: 'weisses-bohnen-chili',
    n: 'Weißes Bohnen-Chili mit Mais & Skyr',
    img: { wiki: 'Chili con carne', q: 'white bean chili vegetarian corn' },
    ck: 'Weißes Chili',
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['mealprep', 'comfort'],
    i: [['weisse_bohnen', 150], ['sojaschnetzel', 25], ['mais', 50], ['paprika', 100], ['zwiebel', 50], ['knoblauch', 4], ['gemuesebruehe', 200], ['gewuerze', 3], ['chili_frisch', 3], ['olivenoel', 6], ['reis', 40], ['skyr', 100], ['limette', 10], ['kraeuter', 4]],
    s: [
      'Sojaschnetzel 10 Min. in heißem Wasser einweichen und ausdrücken. Zwiebel, Knoblauch und gelbe Paprika würfeln. Reis nach Packungsangabe garen.',
      'Öl im Topf erhitzen, Sojaschnetzel 4 Min. anbraten, Zwiebel, Knoblauch und Paprika 3 Min. mitdünsten.',
      'Bohnen, Mais und Brühe zugeben und 15 Min. köcheln. Ein Drittel der Bohnen mit dem Kochlöffel am Topfrand zerdrücken, damit das Chili sämig wird.',
      'Baby-/Kleinkind-Portion vor dem Würzen entnehmen.',
      'Rest mit Kreuzkümmel, Oregano und Chili abschmecken. Mit Reis, Skyr, Limette und Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Reis vorab im Garkörbchen garen und warmhalten.',
      steps: [
        ['1000 g Wasser einfüllen, Reis im Garkörbchen einhängen und garen, warmstellen und Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch zerkleinern, mit dem Spatel nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl, eingeweichte Sojaschnetzel und Paprikawürfel zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Bohnen, Mais und Brühe zugeben und köcheln.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Würzen entnehmen.', '', '', '', ''],
        ['Gewürze und Chili zugeben und kurz andicken.', '1 Min.', '100°C', 'Stufe 2', 'Linkslauf'],
        ['Mit Reis, Skyr, Limette und Koriander servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Portion mit Reis pürieren (Brühe salzarm wählen) oder dick eingekocht als Löffelmus. Bohnen immer zerdrücken. Kleinkind (1–3 J.): ohne Chili, mit einem Klecks Skyr, Bohnen leicht anquetschen.',
    baby: 1,
  },
  {
    id: 'ofengemuese-feta-kichererbsen',
    n: 'Ofengemüse mit Feta & Kichererbsen',
    img: { wiki: 'Feta', q: 'roasted vegetables feta chickpeas sheet pan' },
    ck: 'Ofengemüse mit Feta',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['mealprep'],
    i: [['feta', 60], ['kichererbsen', 80], ['suesskartoffel', 120], ['zucchini', 120], ['paprika', 100], ['rote_zwiebel', 50], ['knoblauch', 4], ['olivenoel', 8], ['gewuerze', 2], ['skyr', 150], ['kraeuter', 4], ['zitronensaft', 5]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Süßkartoffel in 2 cm Würfel, Zucchini und Paprika in grobe Stücke, Zwiebel in Spalten schneiden. Kichererbsen abspülen und trocken tupfen.',
      'Gemüse und Kichererbsen mit Öl und Knoblauch auf einem Blech mischen. Baby-Ecke ungewürzt lassen, Rest mit Paprikapulver und Thymian würzen.',
      '20 Min. rösten, dann den Feta in Würfeln darauf verteilen und weitere 10 Min. backen.',
      'Skyr mit gehackten Kräutern und Zitronensaft verrühren und als Dip dazu servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Das Gemüse röstet im Ofen. Der Thermomix macht den Kräuter-Skyr.',
      steps: [
        ['Ofen auf 200 °C Umluft vorheizen, Gemüse schneiden und mit Öl, Knoblauch und Gewürzen aufs Blech geben (Baby-Ecke ungewürzt).', '', '', '', ''],
        ['20 Min. rösten, Feta darauf verteilen und weitere 10 Min. backen.', '', '', '', ''],
        ['Kräuter in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Skyr und Zitronensaft zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Süßkartoffel, Zucchini und Paprika aus der ungewürzten Ecke in Fingerform, Kichererbsen zerdrücken, Feta weglassen. Kleinkind (1–3 J.): Gemüse in Stücken, Kichererbsen angequetscht, etwas Feta und Skyr-Dip.',
    baby: 2,
  },
  {
    id: 'falafel-bowl-glutenfrei',
    n: 'Ofen-Falafel-Bowl mit Tahini-Joghurt (glutenfrei)',
    img: { wiki: 'Falafel', q: 'falafel bowl quinoa tahini yogurt salad' },
    ck: 'Falafel',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['mealprep'],
    i: [['kichererbsen', 120], ['kichererbsenmehl', 20], ['quinoa', 40], ['griech_joghurt', 150], ['tahini', 8], ['gurke', 80], ['tomate', 80], ['salat', 30], ['zwiebel', 20], ['knoblauch', 4], ['kraeuter', 6], ['gewuerze', 3], ['olivenoel', 6], ['zitronensaft', 8], ['salz', 1]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Quinoa heiß abspülen und nach Packungsangabe garen.',
      'Kichererbsen gut abtropfen lassen und mit Zwiebel, Knoblauch, Petersilie, Kreuzkümmel, Koriander und Salz im Mixer grob pürieren. Kichererbsenmehl unterkneten.',
      'Aus der Masse walnussgroße Bällchen formen, leicht flachdrücken, mit Öl bepinseln und 20–22 Min. backen, nach der Hälfte wenden.',
      'Joghurt mit Tahini, Zitronensaft und 1 EL Wasser glatt rühren. Gurke und Tomate würfeln.',
      'Quinoa, Salat, Gemüse und Falafel in Schalen anrichten und mit Tahini-Joghurt beträufeln.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen (ca. 20 Falafel). Backen im Ofen.',
      steps: [
        ['Quinoa im Garkörbchen mit 1000 g Wasser garen, umfüllen, Mixtopf leeren.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel, Knoblauch und Kräuter in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 6', ''],
        ['Kichererbsen, Gewürze und Salz (Baby-Teil vorher ohne Salz abnehmen) zugeben und grob zerkleinern.', '8 Sek.', '', 'Stufe 5', ''],
        ['Kichererbsenmehl zugeben und unterkneten.', '1 Min.', '', '', 'Teigkneten'],
        ['Bällchen formen und im Ofen 20–22 Min. bei 200 °C backen.', '', '', '', ''],
        ['Joghurt, Tahini, Zitronensaft und 15 g Wasser in den gespülten Mixtopf geben und verrühren.', '10 Sek.', '', 'Stufe 3', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): einige Falafel ohne Salz formen und etwas länger backen, damit sie innen weich und außen nicht hart sind, als Fingerfood mit Joghurt zum Dippen. Kleinkind (1–3 J.): Falafel halbieren, Quinoa mit Joghurt mischen, Gurke in Sticks.',
    baby: 2,
  },
  {
    id: 'quinoa-edamame-feta-salat',
    n: 'Quinoa-Salat mit Edamame & Feta',
    img: { wiki: 'Quinoa', q: 'quinoa salad edamame feta cucumber' },
    ck: 'Quinoasalat',
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['mealprep'],
    i: [['quinoa', 55], ['edamame', 100], ['feta', 40], ['gurke', 100], ['paprika', 80], ['kirschtomaten', 60], ['fruehlingszwiebel', 15], ['kuerbiskerne', 10], ['olivenoel', 7], ['zitronensaft', 10], ['senf', 3], ['kraeuter', 5]],
    s: [
      'Quinoa in einem Sieb heiß abspülen und in doppelter Menge Wasser 15 Min. garen, Edamame die letzten 4 Min. mitgaren. Abgießen und abkühlen lassen.',
      'Gurke, Paprika und Frühlingszwiebel würfeln, Kirschtomaten vierteln, Kräuter hacken.',
      'Kürbiskerne in einer Pfanne ohne Fett 2–3 Min. rösten.',
      'Öl, Zitronensaft, Senf und Pfeffer zu einem Dressing verrühren, mit Quinoa, Edamame und Gemüse mischen.',
      'Feta darüberbröseln und mit Kürbiskernen bestreuen. Hält im Kühlschrank 2–3 Tage.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Quinoa und Edamame garen im Thermomix, der Rest ist Schnippelarbeit.',
      steps: [
        ['1000 g Wasser einfüllen, Quinoa im Garkörbchen einhängen, Edamame in den Varoma-Behälter geben, aufsetzen und garen.', '18 Min.', 'Varoma', 'Stufe 4', ''],
        ['Quinoa und Edamame abkühlen lassen, Mixtopf leeren.', '', '', '', ''],
        ['Kräuter und Frühlingszwiebel zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl, Zitronensaft, Senf und Pfeffer zugeben und zum Dressing verrühren.', '10 Sek.', '', 'Stufe 3', ''],
        ['Mit Quinoa, Edamame, Gemüse, Feta und gerösteten Kürbiskernen mischen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Quinoa mit zerdrückten Edamame und weicher Gurke ohne Dressing und Feta. Kürbiskerne nur gemahlen. Kleinkind (1–3 J.): Kirschtomaten vierteln, Kerne gemahlen darüberstreuen, Edamame halbieren.',
    baby: 1,
  },
  {
    id: 'mercimek-linsensuppe-joghurt',
    n: 'Türkische Linsensuppe (Mercimek) mit Joghurt',
    img: { wiki: 'Lentil soup', q: 'turkish red lentil soup mercimek corbasi' },
    ck: 'Türkische Linsensuppe',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['rote_linsen', 75], ['zwiebel', 60], ['karotte', 80], ['kartoffel', 60], ['tomatenmark', 15], ['gemuesebruehe', 350], ['olivenoel', 6], ['gewuerze', 3], ['zitrone', 20], ['skyr', 150], ['kraeuter', 3], ['salz', 0.5]],
    s: [
      'Zwiebel, Karotte und Kartoffel würfeln, Linsen abspülen.',
      'Öl im Topf erhitzen, Zwiebel 3 Min. andünsten, Tomatenmark und Kreuzkümmel 1 Min. mitrösten.',
      'Linsen, Karotte, Kartoffel und Brühe zugeben und 20 Min. köcheln, bis alles weich ist. Fein pürieren.',
      'Baby-/Kleinkind-Portion vor dem Salzen entnehmen.',
      'Suppe mit Pul Biber, Salz und Zitronensaft abschmecken. Mit einem großen Klecks Skyr und Minze servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen.',
      steps: [
        ['Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl, Tomatenmark und Kreuzkümmel zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Karotte und Kartoffel in Stücken zugeben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Linsen und Brühe zugeben und garen.', '20 Min.', '100°C', 'Stufe 1', ''],
        ['Suppe pürieren, dabei langsam auf Stufe 8 steigern.', '1 Min.', '', 'Stufe 8', ''],
        ['Baby-/Kleinkind-Portion vor dem Salzen entnehmen.', '', '', '', ''],
        ['Mit Salz, Pul Biber und Zitronensaft abschmecken, mit Skyr und Minze servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): die ungesalzene Suppe ist ein idealer Brei, für BLW dicker einkochen und mit Brotstreifen zum Dippen. Salzarme Brühe nehmen. Kleinkind (1–3 J.): mild ohne Pul Biber, mit Joghurt verrührt.',
    baby: 2,
  },
  {
    id: 'ribollita-pochiertes-ei',
    n: 'Ribollita mit pochiertem Ei',
    img: { wiki: 'Ribollita', q: 'ribollita tuscan bean soup kale egg' },
    ck: 'Ribollita',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['comfort'],
    i: [['weisse_bohnen', 130], ['gruenkohl', 100], ['tomaten_dose', 150], ['karotte', 60], ['sellerie', 40], ['zwiebel', 50], ['knoblauch', 4], ['gemuesebruehe', 300], ['vollkornbrot', 40], ['ei', 120], ['parmesan', 10], ['olivenoel', 6]],
    s: [
      'Zwiebel, Karotte, Sellerie und Knoblauch fein würfeln, Grünkohl von den Stielen zupfen und grob hacken.',
      'Öl im Topf erhitzen und das Gemüse 6 Min. andünsten. Tomaten, Bohnen und Brühe zugeben und 15 Min. köcheln.',
      'Grünkohl und das gewürfelte Brot zugeben und weitere 10 Min. köcheln, bis die Suppe dicklich ist. Ein Teil der Bohnen kann zerdrückt werden.',
      'Baby-/Kleinkind-Portion entnehmen, Rest mit Pfeffer und Rosmarin abschmecken.',
      'Eier in siedendem Essigwasser 4 Min. pochieren. Suppe mit je einem Ei und Parmesan servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Eier im Topf pochieren.',
      steps: [
        ['Zwiebel, Karotte, Sellerie und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten, Bohnen und Brühe zugeben und garen.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Grünkohl und Brotwürfel zugeben und weitergaren.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen.', '', '', '', ''],
        ['Eier parallel im Topf pochieren, Suppe mit Ei und Parmesan servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Suppe ohne Parmesan und mit salzarmer Brühe fein pürieren, Ei hart gekocht statt pochiert und zerdrückt unterrühren. Kleinkind (1–3 J.): Grünkohl fein hacken, Ei vollständig durchgegart.',
    baby: 1,
  },
  {
    id: 'kartoffel-lauch-suppe-raeuchertofu',
    n: 'Kartoffel-Lauch-Suppe mit Räuchertofu',
    img: { wiki: 'Leek soup', q: 'potato leek soup smoked tofu' },
    ck: 'Kartoffel-Lauch-Suppe',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['kartoffel', 220], ['lauch', 150], ['raeuchertofu', 110], ['gemuesebruehe', 350], ['milch', 100], ['skyr', 80], ['olivenoel', 5], ['gewuerze', 1], ['kraeuter', 4], ['salz', 0.5]],
    s: [
      'Kartoffeln schälen und würfeln, Lauch längs halbieren, waschen und in Ringe schneiden. Räuchertofu in kleine Würfel schneiden.',
      'Räuchertofu in einer Pfanne in 1 TL Öl 5 Min. knusprig braten und beiseitestellen.',
      'Restliches Öl im Topf erhitzen, Lauch 4 Min. andünsten, Kartoffeln und Brühe zugeben und 18 Min. köcheln.',
      'Milch zugeben und fein pürieren. Baby-/Kleinkind-Portion entnehmen.',
      'Mit Muskat, Pfeffer und etwas Salz abschmecken, Skyr einrühren und mit Tofu-Croutons und Schnittlauch servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Tofu-Croutons in der Pfanne braten.',
      steps: [
        ['Lauch in Stücken in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Kartoffeln und Brühe zugeben und garen.', '18 Min.', '100°C', 'Stufe 1', ''],
        ['Milch zugeben und pürieren, langsam auf Stufe 8 steigern.', '1 Min.', '', 'Stufe 8', ''],
        ['Baby-/Kleinkind-Portion entnehmen.', '', '', '', ''],
        ['Muskat, Pfeffer, Salz und Skyr zugeben und unterrühren.', '20 Sek.', '', 'Stufe 3', ''],
        ['Tofu-Croutons in der Pfanne braten und auf der Suppe servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): pürierte Suppe mit salzarmer Brühe ist ein idealer Brei, statt Räuchertofu (salzig) gedämpften Naturtofu fein zerdrückt unterrühren. Kleinkind (1–3 J.): wenig Räuchertofu in sehr kleinen Würfeln, Suppe dick lassen.',
    baby: 1,
  },
  {
    id: 'vegetarische-gulaschsuppe-soja',
    n: 'Vegetarische Gulaschsuppe mit Sojaschnetzeln',
    img: { wiki: 'Goulash', q: 'vegetarian goulash soup soy chunks paprika' },
    ck: 'Gulaschsuppe vegetarisch',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 50, d: 1,
    st: ['comfort', 'mealprep'],
    i: [['sojaschnetzel', 45], ['kartoffel', 180], ['paprika', 150], ['zwiebel', 80], ['knoblauch', 4], ['tomatenmark', 20], ['tomaten_dose', 150], ['gemuesebruehe', 400], ['rapsoel', 8], ['gewuerze', 4], ['schmand_light', 40], ['kraeuter', 3]],
    s: [
      'Sojaschnetzel 15 Min. in heißer Brühe (von der Gesamtmenge) einweichen und gut ausdrücken. Zwiebeln, Paprika und Kartoffeln würfeln.',
      'Öl im Topf stark erhitzen, Sojaschnetzel 5 Min. kräftig anbraten. Zwiebeln und Knoblauch 4 Min. mitbraten, Tomatenmark und edelsüßes Paprikapulver 1 Min. anrösten.',
      'Mit Tomaten und restlicher Brühe ablöschen, Kartoffeln und Paprika zugeben und 25 Min. köcheln.',
      'Baby-/Kleinkind-Portion vor dem Nachwürzen entnehmen.',
      'Mit Kümmel, Majoran und Pfeffer abschmecken und mit Schmand und Petersilie servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Für Röstaromen die Sojaschnetzel in der Pfanne anbraten.',
      steps: [
        ['Sojaschnetzel in der Pfanne mit der Hälfte des Öls kräftig anbraten.', '', '', '', ''],
        ['Zwiebeln und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Restliches Öl, Tomatenmark und Paprikapulver zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Sojaschnetzel, Tomaten, Brühe, Kartoffel- und Paprikawürfel zugeben und garen.', '25 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen.', '', '', '', ''],
        ['Mit Kümmel, Majoran und Pfeffer abschmecken, mit Schmand servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Kartoffeln, Paprika und Sojaschnetzel aus der ungewürzten Portion fein pürieren, salzarme Brühe verwenden. Kleinkind (1–3 J.): Schnetzel klein schneiden, Kartoffeln leicht zerdrücken, ohne Kümmelschärfe.',
    baby: 1,
  },
  {
    id: 'tofu-ruehrei-bowl',
    n: 'Tofu-Rührei-Bowl mit Süßkartoffel & Avocado',
    img: { wiki: 'Scrambled tofu', q: 'tofu scramble bowl sweet potato avocado' },
    ck: 'Tofu Rührei',
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    i: [['tofu', 220], ['suesskartoffel', 150], ['spinat', 60], ['kirschtomaten', 80], ['avocado', 30], ['kuerbiskerne', 10], ['fruehlingszwiebel', 15], ['olivenoel', 6], ['gewuerze', 2], ['sojasauce', 5], ['salz', 0.5]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Süßkartoffel in 2 cm Würfel schneiden, mit 1 TL Öl mischen und 20–25 Min. rösten.',
      'Tofu mit einer Gabel grob zerbröseln. Restliches Öl in einer Pfanne erhitzen und den Tofu 5 Min. braten.',
      'Kurkuma, Paprikapulver und Pfeffer zugeben, Baby-/Kleinkind-Portion ohne Sojasauce entnehmen. Rest mit Sojasauce und Salz würzen.',
      'Spinat und halbierte Kirschtomaten unterheben und 1 Min. zusammenfallen lassen.',
      'Süßkartoffel, Tofu-Rührei und Avocadoscheiben in Schalen anrichten, mit Frühlingszwiebeln und gerösteten Kürbiskernen bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Süßkartoffel im Varoma, Tofu-Rührei in der Pfanne.',
      steps: [
        ['500 g Wasser einfüllen, Süßkartoffelwürfel in den Varoma-Behälter geben, aufsetzen und garen.', '20 Min.', 'Varoma', 'Stufe 1', ''],
        ['Tofu in der Pfanne mit Öl zerbröselt anbraten, Gewürze zugeben.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion ohne Sojasauce entnehmen.', '', '', '', ''],
        ['Sojasauce, Spinat und Kirschtomaten zugeben und kurz zusammenfallen lassen.', '', '', '', ''],
        ['Mit Süßkartoffel, Avocado, Frühlingszwiebeln und Kürbiskernen anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): weicher Tofu-Rührei-Krümel ohne Sojasauce, Süßkartoffel als Sticks, Avocado in Spalten. Kürbiskerne nur gemahlen. Kleinkind (1–3 J.): Tomaten vierteln, wenig Sojasauce, Kerne gemahlen.',
    baby: 2,
  },
  {
    id: 'protein-kaesespaetzle-glutenfrei',
    n: 'Protein-Käsespätzle mit Röstzwiebeln (glutenfrei möglich)',
    img: { wiki: 'Käsespätzle', q: 'kaesespaetzle cheese spaetzle fried onions' },
    ck: 'Käsespätzle',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort', 'kinderliebling'],
    i: [['mehl', 65], ['ei', 110], ['huettenkaese', 60], ['gouda_light', 35], ['milch', 30], ['zwiebel', 80], ['rapsoel', 5], ['gewuerze', 1], ['salz', 1], ['salat', 50]],
    s: [
      'Mehl (für glutenfrei eine glutenfreie Mehlmischung), Eier, Milch, Muskat und eine Prise Salz zu einem zähen Teig schlagen, bis er Blasen wirft. 10 Min. quellen lassen.',
      'Zwiebeln in feine Ringe schneiden und im Öl bei mittlerer Hitze 10–12 Min. goldbraun rösten.',
      'Teig portionsweise mit Spätzlehobel oder -presse in siedendes Wasser drücken. Sobald die Spätzle oben schwimmen, abschöpfen.',
      'Spätzle lagenweise mit Hüttenkäse und Gouda in eine Form schichten und 10 Min. bei 180 °C überbacken, bis der Käse schmilzt.',
      'Mit Röstzwiebeln und einem grünen Salat servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Teig im Thermomix, Spätzle im Topf kochen.',
      steps: [
        ['Gouda in Stücken in den Mixtopf geben und reiben, umfüllen.', '8 Sek.', '', 'Stufe 8', ''],
        ['Mehl, Eier, Milch, Muskat und Salz in den Mixtopf geben und zu einem zähen Teig verarbeiten.', '2 Min.', '', '', 'Teigkneten'],
        ['Teig 10 Min. quellen lassen, parallel Zwiebelringe in der Pfanne goldbraun rösten.', '', '', '', ''],
        ['Teig portionsweise in siedendes Wasser schaben oder pressen und abschöpfen, sobald die Spätzle oben schwimmen.', '', '', '', ''],
        ['Spätzle mit Hüttenkäse und Käse schichten, 10 Min. bei 180 °C überbacken und mit Röstzwiebeln servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Spätzle ohne Salz kochen, mit etwas Hüttenkäse vermischt als weiches Fingerfood. Wenig Gouda, Röstzwiebeln weglassen. Kleinkind (1–3 J.): wie Erwachsene, Spätzle kurz schneiden, ein paar weiche Zwiebeln.',
    baby: 2,
  },
  {
    id: 'gnocchi-pfanne-edamame-feta',
    n: 'Gnocchi-Pfanne mit Edamame, Spinat & Feta',
    img: { wiki: 'Gnocchi', q: 'pan fried gnocchi spinach feta edamame' },
    ck: 'Gnocchipfanne',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 20, d: 1,
    st: ['kinderliebling'],
    i: [['gnocchi', 150], ['edamame', 100], ['erbsen', 50], ['feta', 40], ['parmesan', 8], ['spinat', 60], ['kirschtomaten', 80], ['knoblauch', 4], ['olivenoel', 6], ['zitronensaft', 5]],
    s: [
      'Öl in einer großen beschichteten Pfanne erhitzen und die Gnocchi darin 6–8 Min. goldbraun und knusprig braten.',
      'Edamame und Erbsen in kochendem Wasser 3 Min. blanchieren und abgießen.',
      'Knoblauch, Edamame, Erbsen und halbierte Kirschtomaten zu den Gnocchi geben und 2 Min. mitbraten. Spinat unterschwenken, bis er zusammenfällt.',
      'Baby-/Kleinkind-Portion ohne Feta entnehmen.',
      'Mit Zitronensaft und Pfeffer abschmecken, Feta darüberbröseln und mit Parmesan bestreuen.',
    ],
    tm: {
      fit: 0,
      note: 'Gnocchi werden in der Pfanne knusprig. Der Thermomix gart das Gemüse.',
      steps: [
        ['500 g Wasser einfüllen, Edamame und Erbsen in den Varoma-Behälter geben, aufsetzen und dämpfen.', '10 Min.', 'Varoma', 'Stufe 1', ''],
        ['Parallel Gnocchi in der Pfanne mit Öl knusprig braten.', '', '', '', ''],
        ['Knoblauch, Gemüse, Kirschtomaten und Spinat zugeben und kurz mitbraten.', '', '', '', ''],
        ['Baby-Portion ohne Feta entnehmen, Rest mit Feta, Parmesan und Zitrone servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Gnocchi sind gesalzen, daher für das Baby nur 1–2 Stück. Besser gedämpfte Erbsen und Edamame zerdrückt mit Spinat, dazu ein paar halbierte Gnocchi. Kleinkind (1–3 J.): Gnocchi halbieren, Tomaten vierteln, Edamame anquetschen.',
    baby: 1,
  },
  {
    id: 'soja-geschnetzeltes-champignons',
    n: 'Geschnetzeltes Zürcher Art mit Sojaschnetzeln & Reis',
    img: { wiki: 'Zürcher Geschnetzeltes', q: 'zurich style geschnetzeltes mushroom cream sauce rice' },
    ck: 'Zürcher Geschnetzeltes',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['comfort'],
    i: [['sojaschnetzel', 45], ['champignons', 200], ['zwiebel', 50], ['sahne', 50], ['gemuesebruehe', 150], ['senf', 5], ['reis', 55], ['rapsoel', 7], ['gewuerze', 1], ['kraeuter', 4], ['salz', 0.5]],
    s: [
      'Sojaschnetzel 15 Min. in heißer Brühe einweichen, gut ausdrücken und die Brühe auffangen. Reis nach Packungsangabe garen.',
      'Champignons in Scheiben schneiden, Zwiebel fein würfeln.',
      'Öl in einer Pfanne stark erhitzen, Sojaschnetzel 5 Min. kräftig anbraten und herausnehmen. Champignons und Zwiebel 6 Min. braten.',
      'Mit der Einweichbrühe ablöschen, Sahne und Senf einrühren, Schnetzel zurückgeben und 5 Min. sämig köcheln. Baby-/Kleinkind-Portion entnehmen.',
      'Rest mit Paprikapulver, Pfeffer und Salz abschmecken und mit Petersilie und Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Sojaschnetzel für die Röstaromen in der Pfanne anbraten.',
      steps: [
        ['Sojaschnetzel in der Pfanne mit der Hälfte des Öls kräftig anbraten.', '', '', '', ''],
        ['Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Restliches Öl und Champignons zugeben und andünsten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Brühe zugeben, Reis im Garkörbchen mit 500 g zusätzlichem Wasser im Mixtopf einhängen und garen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Garkörbchen herausnehmen, Sahne, Senf und Sojaschnetzel zugeben und sämig köcheln.', '5 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen, Rest abschmecken und mit Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Schnetzel und Pilze aus der ungewürzten Portion klein hacken und mit Reis und Sauce pürieren, salzarme Brühe verwenden. Kleinkind (1–3 J.): Schnetzel klein schneiden, Pilze fein, Sauce mild.',
    baby: 1,
  },
  {
    id: 'matar-tofu-curry',
    n: 'Matar Tofu (Erbsen-Tofu-Curry)',
    img: { wiki: 'Mattar paneer', q: 'matar tofu peas curry indian' },
    ck: 'Erbsencurry',
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['mealprep'],
    i: [['tofu', 180], ['erbsen', 80], ['tomaten_dose', 150], ['zwiebel', 60], ['ingwer', 6], ['knoblauch', 4], ['currypulver', 5], ['griech_joghurt', 50], ['rapsoel', 6], ['reis', 50], ['chili_frisch', 2], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Tofu in 2 cm Würfel schneiden und in der Hälfte des Öls 6–8 Min. rundum goldbraun braten. Reis nach Packungsangabe garen.',
      'Zwiebel, Ingwer und Knoblauch fein hacken und im restlichen Öl 5 Min. goldgelb dünsten. Garam Masala, Kurkuma und Kreuzkümmel 1 Min. mitrösten.',
      'Tomaten und 100 ml Wasser zugeben, 10 Min. köcheln und bei Bedarf glatt pürieren. Erbsen und Tofu zugeben und 5 Min. ziehen lassen.',
      'Baby-/Kleinkind-Portion vor Chili und Salz entnehmen.',
      'Joghurt einrühren (nicht mehr kochen), mit Chili und Salz abschmecken und mit Koriander und Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Tofu in der Pfanne braten.',
      steps: [
        ['Zwiebel, Ingwer und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Gewürze zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten und 100 g Wasser zugeben, köcheln und anschließend pürieren.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Sauce glatt pürieren.', '20 Sek.', '', 'Stufe 7', ''],
        ['Erbsen und gebratenen Tofu zugeben und garen.', '5 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor Chili und Salz entnehmen.', '', '', '', ''],
        ['Joghurt, Chili und Salz unterrühren und mit Reis servieren.', '20 Sek.', '', 'Sanftrührstufe', 'Linkslauf'],
      ],
    },
    kid: 'Baby (6–12 Mon.): Tofuwürfel weich und ohne Chili als Fingerfood, Erbsen zerdrückt in der Tomatensauce mit Reis. Kleinkind (1–3 J.): mild ohne Chili, Erbsen leicht zerdrücken, ein Löffel Joghurt dazu.',
    baby: 2,
  },
  {
    id: 'mapo-tofu-vegetarisch',
    n: 'Mapo Tofu (vegetarisch) mit Pak Choi',
    img: { wiki: 'Mapo tofu', q: 'mapo tofu vegetarian rice' },
    ck: 'Mapo Tofu',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 2,
    i: [['tofu', 200], ['sojaschnetzel', 15], ['reis', 50], ['pak_choi', 100], ['sojasauce', 12], ['knoblauch', 5], ['ingwer', 6], ['fruehlingszwiebel', 20], ['chili_frisch', 3], ['speisestaerke', 5], ['gemuesebruehe', 100], ['sesamoel', 3], ['rapsoel', 5]],
    s: [
      'Reis nach Packungsangabe garen. Sojaschnetzel (feine Variante oder im Mixer zerkleinert) 10 Min. in heißem Wasser einweichen und ausdrücken.',
      'Tofu in 2 cm Würfel schneiden und in leicht gesalzenem Wasser 3 Min. sieden lassen, damit er fester wird. Abgießen.',
      'Öl im Wok erhitzen, Sojahack 4 Min. krümelig braten, Knoblauch, Ingwer und weiße Frühlingszwiebelteile 1 Min. mitbraten.',
      'Brühe und Pak Choi zugeben, Tofu vorsichtig unterheben und 3 Min. köcheln. Baby-/Kleinkind-Portion ohne Sojasauce und Chili entnehmen.',
      'Sojasauce und Chili zugeben, mit angerührter Stärke binden, mit Sesamöl und Frühlingszwiebelgrün beträufeln und mit Reis servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Reis im Garkörbchen, Pak Choi und Tofu im Varoma, Sojahack in der Pfanne.',
      steps: [
        ['Knoblauch, Ingwer und weiße Frühlingszwiebelteile in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 7', ''],
        ['Öl zugeben und andünsten.', '2 Min.', '120°C', 'Stufe 1', ''],
        ['900 g Wasser zugeben, Reis im Garkörbchen einhängen, Tofu und Pak Choi in den Varoma-Behälter geben, aufsetzen und garen.', '22 Min.', 'Varoma', 'Stufe 4', ''],
        ['Parallel Sojahack in der Pfanne krümelig braten.', '', '', '', ''],
        ['Baby-/Kleinkind-Portion Tofu, Pak Choi und Reis ohne Würze entnehmen.', '', '', '', ''],
        ['Sojahack, Tofu und Pak Choi in der Pfanne mit Brühe, Sojasauce, Chili und Stärke binden, mit Sesamöl beträufeln.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): gedämpfter Tofu in Würfeln und weicher Pak Choi ohne Sojasauce und Chili, dazu Reis. Kleinkind (1–3 J.): ohne Chili und mit wenig Sojasauce, Tofu halbieren.',
    baby: 1,
  },
  {
    id: 'tempeh-gyros-tzatziki',
    n: 'Tempeh-Gyros mit Tzatziki im Pita',
    img: { wiki: 'Gyros', q: 'tempeh gyros pita tzatziki vegetarian' },
    ck: 'Gyros vegetarisch',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    st: ['kinderliebling'],
    i: [['tempeh', 120], ['pitabrot', 70], ['griech_joghurt', 100], ['gurke', 80], ['tomate', 60], ['rote_zwiebel', 30], ['salat', 30], ['knoblauch', 4], ['gewuerze', 3], ['olivenoel', 6], ['zitronensaft', 5], ['sojasauce', 5]],
    s: [
      'Tempeh in sehr dünne Streifen schneiden und mit Öl, Sojasauce, Paprikapulver, Oregano, Kreuzkümmel und Zitronensaft 10 Min. marinieren (Kinderportion nur mit Öl und Paprika).',
      'Für das Tzatziki die Hälfte der Gurke raspeln, gut ausdrücken und mit Joghurt und gepresstem Knoblauch verrühren.',
      'Tempeh in einer heißen Pfanne 6–8 Min. knusprig braten.',
      'Pita kurz im Ofen oder Toaster aufbacken (für glutenfrei glutenfreies Fladenbrot), restliche Gurke, Tomate und Zwiebel in Scheiben schneiden.',
      'Pita mit Salat, Gemüse, Gyros und Tzatziki füllen.',
    ],
    tm: {
      fit: 0,
      note: 'Gyros in der Pfanne, Tzatziki im Thermomix.',
      steps: [
        ['Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Gurkenstücke zugeben und zerkleinern, in einem Sieb gut ausdrücken.', '4 Sek.', '', 'Stufe 5', ''],
        ['Gurke zurück in den Mixtopf geben, Joghurt zugeben und verrühren.', '10 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Marinierten Tempeh in der Pfanne knusprig braten und mit Pita, Gemüse und Tzatziki servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Tempehstreifen nur mit Öl gebraten (nicht zu knusprig), Pita-Streifen zum Dippen in Joghurt ohne Knoblauch. Kleinkind (1–3 J.): Gyros klein geschnitten im halben Pita, mildes Tzatziki.',
    baby: 2,
  },
  {
    id: 'linsen-bratlinge-joghurtdip',
    n: 'Rote-Linsen-Bratlinge mit Joghurt-Dip',
    img: { wiki: 'Veggie burger', q: 'red lentil patties yogurt dip' },
    ck: 'Linsenbratlinge',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['kinderliebling', 'mealprep'],
    i: [['rote_linsen', 60], ['haferflocken', 20], ['ei', 50], ['karotte', 60], ['zwiebel', 30], ['knoblauch', 3], ['gewuerze', 3], ['rapsoel', 8], ['griech_joghurt', 150], ['gurke', 60], ['kraeuter', 4], ['salat', 50], ['salz', 1]],
    s: [
      'Linsen abspülen und in der doppelten Menge Wasser 10–12 Min. weich kochen, bis das Wasser aufgesogen ist. Abkühlen lassen.',
      'Karotte fein raspeln, Zwiebel und Knoblauch fein hacken. Mit Linsen, Haferflocken (für glutenfrei zertifizierte), Ei, Kreuzkümmel und Paprikapulver zu einer formbaren Masse verkneten. Für das Baby einen Teil ohne Salz abnehmen, Rest salzen.',
      'Aus der Masse kleine Bratlinge formen und im Öl bei mittlerer Hitze 4 Min. pro Seite goldbraun braten.',
      'Joghurt mit geraspelter Gurke und Kräutern verrühren.',
      'Bratlinge mit Dip und Salat servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen (12 Bratlinge). Braten in der Pfanne.',
      steps: [
        ['Linsen mit doppelter Menge Wasser in den Mixtopf geben und garen, umfüllen und abkühlen lassen.', '12 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Karotte, Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Linsen, Haferflocken, Ei und Gewürze zugeben und vermengen.', '20 Sek.', '', 'Stufe 4', 'Linkslauf'],
        ['Bratlinge formen und in der Pfanne 4 Min. pro Seite braten.', '', '', '', ''],
        ['Gurke und Kräuter im gespülten Mixtopf zerkleinern, Joghurt zugeben und verrühren.', '5 Sek.', '', 'Stufe 5', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Bratlinge ohne Salz in Fingerform, weich gebraten, mit Joghurt zum Dippen. Kleinkind (1–3 J.): kleine Taler, auch kalt gut als Mitnehm-Snack.',
    baby: 2,
  },
  {
    id: 'gefuellte-zucchini-linsen-feta',
    n: 'Gefüllte Zucchini mit Linsen, Quinoa & Feta',
    img: { wiki: 'Stuffed zucchini', q: 'stuffed zucchini lentils quinoa feta baked' },
    ck: 'Gefüllte Zucchini vegetarisch',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 50, d: 2,
    i: [['zucchini', 300], ['linsen_dose', 120], ['quinoa', 35], ['feta', 40], ['huettenkaese', 80], ['passierte_tomaten', 150], ['zwiebel', 40], ['knoblauch', 4], ['olivenoel', 6], ['gewuerze', 2], ['kraeuter', 3]],
    s: [
      'Ofen auf 190 °C Umluft vorheizen. Quinoa abspülen und 15 Min. in doppelter Menge Wasser garen.',
      'Zucchini längs halbieren und mit einem Löffel aushöhlen, das Fruchtfleisch fein hacken.',
      'Zwiebel und Knoblauch im Öl 3 Min. andünsten, Zucchinifleisch 3 Min. mitbraten. Linsen, Quinoa, Hüttenkäse und Oregano untermischen.',
      'Passierte Tomaten in eine Auflaufform gießen, Zucchinihälften hineinsetzen und füllen. Für Baby/Kleinkind eine Hälfte ohne Feta lassen, sonst Feta darüberbröseln.',
      '25 Min. backen, bis die Zucchini weich sind. Mit Basilikum servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Füllung im Thermomix, Backen im Ofen.',
      steps: [
        ['1000 g Wasser einfüllen, Quinoa im Garkörbchen garen, umfüllen und Mixtopf leeren.', '18 Min.', '100°C', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Zucchinifruchtfleisch zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Linsen, Quinoa, Hüttenkäse und Oregano zugeben und vermischen.', '20 Sek.', '', 'Stufe 2', 'Linkslauf'],
        ['Zucchinihälften auf Tomatensauce in der Form füllen, Feta darüberbröseln und 25 Min. bei 190 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Zucchinihälfte ohne Feta weich backen, in Streifen schneiden oder mit Füllung und Sauce zerdrücken. Kleinkind (1–3 J.): wenig Feta, in Stücke geschnitten mit Sauce.',
    baby: 2,
  },
  {
    id: 'gefuellte-aubergine-sojahack',
    n: 'Gefüllte Aubergine mit Sojahack (Karnıyarık-Art)',
    img: { wiki: 'Karnıyarık', q: 'stuffed eggplant karniyarik vegetarian' },
    ck: 'Gefüllte Aubergine',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 55, d: 2,
    st: ['comfort'],
    i: [['aubergine', 300], ['sojaschnetzel', 35], ['tomaten_dose', 150], ['zwiebel', 50], ['knoblauch', 4], ['paprika', 60], ['tomatenmark', 10], ['olivenoel', 8], ['gewuerze', 3], ['feta', 30], ['griech_joghurt', 100], ['bulgur', 30], ['kraeuter', 3]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Aubergine längs halbieren, die Schnittflächen rautenförmig einritzen, mit der Hälfte des Öls bepinseln und 20 Min. backen.',
      'Feine Sojaschnetzel 10 Min. in heißem Wasser einweichen und ausdrücken. Bulgur (für glutenfrei Quinoa) nach Packungsangabe garen.',
      'Restliches Öl erhitzen, Sojahack 4 Min. krümelig braten, Zwiebel, Knoblauch und Paprika 4 Min. mitbraten. Tomatenmark, Tomaten, Paprikapulver und Kreuzkümmel zugeben und 8 Min. einköcheln. Baby-Portion vor dem Würzen entnehmen.',
      'Das Fruchtfleisch der Auberginen mit einem Löffel eindrücken, Füllung daraufgeben und Feta darüberbröseln. 15 Min. backen.',
      'Mit Bulgur, Joghurt und Petersilie servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Auberginen im Ofen vorbacken, Füllung im Thermomix.',
      steps: [
        ['Auberginen im Ofen 20 Min. bei 200 °C vorbacken.', '', '', '', ''],
        ['Zwiebel, Knoblauch und Paprika in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Öl und eingeweichtes Sojahack zugeben und andünsten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Tomatenmark, Tomaten und Gewürze zugeben und einköcheln, Garkörbchen als Spritzschutz aufsetzen.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Nachwürzen entnehmen.', '', '', '', ''],
        ['Auberginen füllen, mit Feta bestreuen und 15 Min. überbacken. Mit Bulgur und Joghurt servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): weiches Auberginenfleisch mit ungewürzter Füllung und Joghurt zerdrücken, ohne Feta. Kleinkind (1–3 J.): Aubergine ohne Schale in Stücken mit Füllung und Bulgur.',
    baby: 1,
  },
  {
    id: 'blumenkohl-linsen-tahini',
    n: 'Gerösteter Blumenkohl mit Linsen & Tahini-Joghurt',
    img: { wiki: 'Cauliflower', q: 'roasted cauliflower lentils tahini yogurt' },
    ck: 'Ofenblumenkohl',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    i: [['blumenkohl', 300], ['linsen_dose', 150], ['griech_joghurt', 150], ['tahini', 10], ['olivenoel', 8], ['gewuerze', 3], ['kraeuter', 5], ['zitronensaft', 8], ['knoblauch', 3], ['rote_zwiebel', 30], ['kirschtomaten', 60], ['mandeln', 10]],
    s: [
      'Ofen auf 220 °C Umluft vorheizen. Blumenkohl in Röschen teilen, mit 2/3 des Öls mischen. Baby-Teil ungewürzt lassen, Rest mit Kreuzkümmel, Paprika und Kurkuma würzen.',
      'Blumenkohl 25 Min. rösten, bis die Ränder goldbraun sind. Mandeln die letzten 5 Min. mitrösten.',
      'Linsen abspülen und mit fein gewürfelter roter Zwiebel, halbierten Kirschtomaten, restlichem Öl, der Hälfte des Zitronensafts und Petersilie mischen.',
      'Joghurt mit Tahini, restlichem Zitronensaft, gepresstem Knoblauch und 1 EL Wasser glatt rühren.',
      'Tahini-Joghurt auf Teller streichen, Linsensalat und Blumenkohl darauf anrichten und mit gehackten Mandeln bestreuen.',
    ],
    tm: {
      fit: 0,
      note: 'Blumenkohl röstet im Ofen. Der Thermomix macht den Tahini-Joghurt.',
      steps: [
        ['Blumenkohl und Mandeln im Ofen bei 220 °C 25 Min. rösten.', '', '', '', ''],
        ['Knoblauch in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Joghurt, Tahini, Zitronensaft und 15 g Wasser zugeben und verrühren, umfüllen.', '10 Sek.', '', 'Stufe 3', ''],
        ['Linsen mit Zwiebel, Tomaten, Öl und Petersilie mischen und alles anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Blumenkohlröschen weich geröstet als Fingerfood, Linsen zerdrückt mit Joghurt. Mandeln nur gemahlen. Kleinkind (1–3 J.): Tomaten vierteln, Mandeln gehackt fein, Linsen ohne rohe Zwiebel.',
    baby: 2,
  },
  {
    id: 'brokkoli-quiche-ohne-boden',
    n: 'Brokkoli-Hüttenkäse-Quiche ohne Boden',
    img: { wiki: 'Quiche', q: 'crustless broccoli quiche cottage cheese' },
    ck: 'Quiche ohne Boden',
    cu: 'international',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    st: ['mealprep', 'kinderliebling'],
    i: [['ei', 150], ['huettenkaese', 150], ['brokkoli', 200], ['gouda_light', 20], ['fruehlingszwiebel', 20], ['kirschtomaten', 80], ['milch', 50], ['gewuerze', 1], ['salz', 0.3], ['salat', 60], ['olivenoel', 5], ['essig', 5]],
    s: [
      'Ofen auf 180 °C Ober-/Unterhitze vorheizen, eine Quiche- oder Auflaufform einfetten. Brokkoli in kleine Röschen teilen und 4 Min. dämpfen.',
      'Eier mit Hüttenkäse, Milch, Muskat, Pfeffer und wenig Salz verquirlen. Frühlingszwiebeln in Ringe schneiden.',
      'Brokkoli und Frühlingszwiebeln in der Form verteilen, Eiermasse darübergießen, halbierte Kirschtomaten darauflegen und mit Gouda bestreuen.',
      '30–35 Min. backen, bis die Quiche in der Mitte fest und goldbraun ist. 5 Min. ruhen lassen.',
      'Mit Blattsalat in Öl-Essig-Dressing servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Brokkoli im Varoma, Backen im Ofen.',
      steps: [
        ['500 g Wasser einfüllen, Brokkoliröschen in den Varoma-Behälter geben, aufsetzen und dämpfen. Mixtopf leeren.', '10 Min.', 'Varoma', 'Stufe 1', ''],
        ['Gouda in Stücken reiben, umfüllen.', '8 Sek.', '', 'Stufe 8', ''],
        ['Eier, Hüttenkäse, Milch, Muskat, Pfeffer und Salz in den Mixtopf geben und verrühren.', '15 Sek.', '', 'Stufe 3', ''],
        ['Brokkoli in der Form verteilen, Eiermasse darübergießen, Tomaten und Gouda daraufgeben und 30–35 Min. bei 180 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Quiche durchgebacken in Streifen als Fingerfood, eine Ecke ohne Salz zubereiten (Salz erst über die Erwachsenenhälfte streuen). Kleinkind (1–3 J.): in Würfeln, Kirschtomaten vierteln.',
    baby: 2,
  },
  {
    id: 'gemuese-linsen-lasagne',
    n: 'Gemüse-Linsen-Lasagne mit Hüttenkäse',
    img: { wiki: 'Lasagne', q: 'vegetable lentil lasagna cottage cheese' },
    ck: 'Gemüselasagne',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 70, d: 2,
    st: ['comfort', 'mealprep', 'kinderliebling'],
    i: [['lasagneplatten', 55], ['rote_linsen', 30], ['passierte_tomaten', 200], ['zucchini', 100], ['karotte', 50], ['zwiebel', 40], ['knoblauch', 4], ['spinat_tk', 80], ['huettenkaese', 100], ['mozzarella', 40], ['olivenoel', 5], ['gewuerze', 2]],
    s: [
      'Zwiebel, Knoblauch, Zucchini und Karotte fein würfeln und im Öl 5 Min. andünsten.',
      'Linsen, passierte Tomaten und 150 ml Wasser zugeben und 15 Min. köcheln. Baby-Portion entnehmen, Rest mit Oregano und Pfeffer würzen.',
      'Aufgetauten Spinat ausdrücken und mit dem Hüttenkäse verrühren. Ofen auf 180 °C Umluft vorheizen.',
      'In eine Form abwechselnd Sauce, Lasagneplatten (für glutenfrei glutenfreie Platten) und Spinat-Hüttenkäse schichten, mit Sauce abschließen.',
      'Mit Mozzarella belegen und 35–40 Min. backen. Vor dem Anschneiden 10 Min. ruhen lassen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Sauce im Thermomix, Backen im Ofen.',
      steps: [
        ['Zwiebel, Knoblauch, Karotte und Zucchini in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Linsen, passierte Tomaten und 150 g Wasser zugeben und garen.', '15 Min.', '100°C', 'Stufe 1', ''],
        ['Baby-/Kleinkind-Portion entnehmen, Rest mit Oregano und Pfeffer würzen.', '', '', '', ''],
        ['Lasagne mit Platten und Spinat-Hüttenkäse schichten, mit Mozzarella belegen und 35–40 Min. bei 180 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Sauce mit etwas Hüttenkäse und weich gebackenen Platten zerdrücken oder Lasagne in Fingerstreifen schneiden. Kleinkind (1–3 J.): in kleinen Würfeln, gut abgekühlt.',
    baby: 2,
  },
  {
    id: 'vegetarische-carbonara-raeuchertofu',
    n: 'Vegetarische Carbonara mit Räuchertofu & Erbsen',
    img: { wiki: 'Carbonara', q: 'vegetarian carbonara smoked tofu peas' },
    ck: 'Spaghetti Carbonara',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 20, d: 1,
    st: ['comfort', 'kinderliebling'],
    i: [['nudeln', 75], ['ei', 60], ['eiklar', 30], ['raeuchertofu', 80], ['parmesan', 15], ['erbsen', 50], ['olivenoel', 4], ['gewuerze', 1], ['salz', 0.5]],
    s: [
      'Spaghetti (für glutenfrei glutenfreie Spaghetti) in Salzwasser bissfest kochen, Erbsen die letzten 2 Min. mitkochen. 100 ml Nudelwasser auffangen.',
      'Räuchertofu in kleine Würfel schneiden und im Öl 5 Min. knusprig braten.',
      'Ei, Eiklar, Parmesan und viel schwarzen Pfeffer verquirlen.',
      'Pfanne vom Herd nehmen, Nudeln und Erbsen zum Tofu geben, Eimasse und etwas Nudelwasser zügig unterrühren, bis eine cremige Sauce entsteht.',
      'Baby-/Kleinkind-Portion bei kleiner Hitze kurz weitergaren, bis das Ei vollständig gestockt ist. Sofort servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Tofu in der Pfanne braten.',
      steps: [
        ['Parmesan in Stücken in den Mixtopf geben und reiben.', '10 Sek.', '', 'Stufe 10', ''],
        ['Eier, Eiklar und Pfeffer zugeben und verrühren, umfüllen.', '10 Sek.', '', 'Stufe 4', ''],
        ['1200 g Wasser und Salz in den Mixtopf füllen und aufkochen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Spaghetti zugeben und garen, Erbsen die letzten 2 Min. zugeben.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Abgießen, mit gebratenem Räuchertofu, Eimasse und etwas Nudelwasser in der Pfanne cremig rühren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Ei muss vollständig durchgegart sein; Nudeln ohne Salz, wenig Räuchertofu (salzig), Erbsen zerdrückt. Kleinkind (1–3 J.): Ei gestockt, Spaghetti kürzer schneiden.',
    baby: 1,
  },
  {
    id: 'kuerbisrisotto-feta-edamame',
    n: 'Kürbisrisotto mit Feta, Edamame & Kürbiskernen',
    img: { wiki: 'Risotto', q: 'pumpkin risotto feta pumpkin seeds' },
    ck: 'Kürbisrisotto',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 40, d: 2,
    st: ['comfort'],
    i: [['risottoreis', 55], ['kuerbis', 150], ['edamame', 80], ['feta', 40], ['parmesan', 15], ['kuerbiskerne', 10], ['zwiebel', 40], ['gemuesebruehe', 300], ['olivenoel', 4], ['kraeuter', 2]],
    s: [
      'Kürbis in 1 cm Würfel schneiden, Zwiebel fein würfeln. Brühe erhitzen.',
      'Öl im Topf erhitzen, Zwiebel 3 Min. glasig dünsten, Reis 1 Min. mitrösten, bis er glasig ist.',
      'Kürbis zugeben und nach und nach heiße Brühe angießen, dabei häufig rühren. Nach 18–20 Min. ist der Reis cremig und bissfest, Edamame die letzten 4 Min. mitgaren.',
      'Baby-/Kleinkind-Portion ohne Feta und Parmesan entnehmen.',
      'Parmesan einrühren, Risotto mit Feta, gerösteten Kürbiskernen und Salbei servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen.',
      steps: [
        ['Parmesan in Stücken in den Mixtopf geben und reiben, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Zwiebel in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Risottoreis zugeben und ohne Messbecher andünsten.', '2 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Kürbiswürfel und Brühe zugeben, Garkörbchen statt Messbecher aufsetzen und garen.', '16 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Edamame zugeben und fertig garen.', '4 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen, Rest mit Parmesan verrühren und mit Feta und Kürbiskernen servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Risotto mit salzarmer Brühe, ohne Käse, Edamame zerdrückt; ideal als Löffelbrei oder zu Bällchen geformt. Kürbiskerne nur gemahlen. Kleinkind (1–3 J.): mit etwas Parmesan, Kerne gemahlen.',
    baby: 2,
  },
  {
    id: 'polenta-pilzragout-ei',
    n: 'Cremige Polenta mit Pilzragout & Spiegelei',
    img: { wiki: 'Polenta', q: 'creamy polenta mushroom ragout fried egg' },
    ck: 'Polenta mit Pilzen',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['comfort'],
    i: [['polenta', 55], ['milch', 150], ['champignons', 200], ['zwiebel', 40], ['knoblauch', 4], ['ei', 120], ['parmesan', 10], ['olivenoel', 6], ['gemuesebruehe', 150], ['kraeuter', 4], ['gewuerze', 1], ['salz', 0.5]],
    s: [
      'Milch und Brühe aufkochen, Polenta unter Rühren einrieseln lassen und bei kleiner Hitze 5–10 Min. (je nach Sorte) quellen lassen, dabei öfter rühren. Parmesan unterrühren.',
      'Champignons in Scheiben schneiden, Zwiebel und Knoblauch fein würfeln.',
      'Zwei Drittel des Öls in einer Pfanne stark erhitzen, Pilze 5 Min. scharf anbraten, Zwiebel und Knoblauch 2 Min. mitbraten und mit Thymian, Pfeffer und Salz würzen.',
      'Im restlichen Öl die Eier zu Spiegeleiern braten (für Baby/Kleinkind von beiden Seiten durchbraten).',
      'Polenta auf Teller geben, Pilzragout und Spiegelei darauf anrichten und mit Petersilie bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Pilze und Eier in der Pfanne.',
      steps: [
        ['Parmesan in Stücken in den Mixtopf geben und reiben, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Milch und Brühe in den Mixtopf geben und aufkochen.', '8 Min.', '100°C', 'Stufe 1', ''],
        ['Polenta durch die Deckelöffnung einrieseln lassen und quellen lassen.', '8 Min.', '90°C', 'Stufe 3', ''],
        ['Parmesan zugeben und unterrühren.', '20 Sek.', '', 'Stufe 3', ''],
        ['Pilze und Spiegeleier parallel in der Pfanne braten und auf der Polenta anrichten.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Polenta ohne Parmesan und mit salzarmer Brühe als Brei oder fest geworden in Sticks, Ei vollständig durchgegart und zerdrückt, Pilze fein gehackt. Kleinkind (1–3 J.): Pilze klein geschnitten, Ei durchgebraten.',
    baby: 2,
  },
  {
    id: 'tofu-larb-salatwraps',
    n: 'Vegetarischer Larb mit Tofu in Salatblättern',
    img: { wiki: 'Larb', q: 'tofu larb lettuce wraps thai' },
    ck: 'Larb',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 25, d: 1,
    i: [['sojaschnetzel', 30], ['tofu', 120], ['reis', 50], ['salat', 80], ['gurke', 60], ['rote_zwiebel', 30], ['limette', 20], ['sojasauce', 10], ['kraeuter', 6], ['chili_frisch', 3], ['rapsoel', 6], ['erdnuesse', 8]],
    s: [
      'Reis nach Packungsangabe garen. Feine Sojaschnetzel 10 Min. in heißem Wasser einweichen und gut ausdrücken. Tofu mit der Gabel zerbröseln.',
      'Öl im Wok erhitzen, Sojahack und Tofu 6–8 Min. krümelig und leicht knusprig braten.',
      'Baby-/Kleinkind-Portion ohne Sojasauce, Chili und Zwiebel entnehmen.',
      'Rest vom Herd nehmen und mit Limettensaft, Sojasauce, Chili, feinen Zwiebelringen sowie reichlich Minze und Koriander mischen.',
      'In Salatblätter füllen, mit gehackten Erdnüssen bestreuen und mit Reis und Gurke servieren.',
    ],
    tm: {
      fit: 0,
      note: 'Das Braten erfolgt im Wok. Der Thermomix gart den Reis und hackt die Kräuter.',
      steps: [
        ['1000 g Wasser einfüllen, Reis im Garkörbchen einhängen und garen, umfüllen.', '20 Min.', '100°C', 'Stufe 4', ''],
        ['Kräuter und Erdnüsse in den trockenen Mixtopf geben und grob hacken.', '3 Sek.', '', 'Stufe 6', ''],
        ['Sojahack und Tofu im Wok knusprig braten, Baby-Portion entnehmen.', '', '', '', ''],
        ['Rest mit Limette, Sojasauce, Chili, Zwiebel und Kräutern mischen und in Salatblättern servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): gebratene Tofu-Krümel ohne Würze mit Reis vermischt oder zu Bällchen gedrückt, Erdnüsse nur als dünn verrührtes Mus. Kleinkind (1–3 J.): ohne Chili, Erdnüsse fein gemahlen, Salatblatt klein geschnitten.',
    baby: 1,
  },
  {
    id: 'rajma-kidneybohnen-curry',
    n: 'Rajma (Kidneybohnen-Curry) mit Reis & Gurken-Raita',
    img: { wiki: 'Rajma', q: 'rajma chawal kidney bean curry rice raita' },
    ck: 'Kidneybohnen Curry',
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 40, d: 1,
    st: ['mealprep', 'comfort'],
    i: [['kidneybohnen', 180], ['reis', 50], ['tomaten_dose', 150], ['zwiebel', 60], ['knoblauch', 4], ['ingwer', 5], ['currypulver', 5], ['rapsoel', 6], ['skyr', 150], ['gurke', 60], ['kraeuter', 3], ['salz', 1]],
    s: [
      'Reis nach Packungsangabe garen. Zwiebel, Knoblauch und Ingwer fein hacken.',
      'Öl im Topf erhitzen, Zwiebel 6 Min. goldbraun braten, Knoblauch, Ingwer, Garam Masala, Kurkuma und Kreuzkümmel 1 Min. mitrösten.',
      'Tomaten und 150 ml Wasser zugeben, 5 Min. köcheln, dann Kidneybohnen zugeben und 15 Min. sämig köcheln. Einige Bohnen am Topfrand zerdrücken.',
      'Baby-/Kleinkind-Portion vor dem Salzen entnehmen. Rest salzen.',
      'Für die Raita Gurke raspeln und mit Skyr und Minze verrühren. Rajma mit Reis, Raita und Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Reis gart im Garkörbchen mit.',
      steps: [
        ['Zwiebel, Knoblauch und Ingwer in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Gewürze zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten, Kidneybohnen und 500 g Wasser zugeben, Reis im Garkörbchen einhängen und garen.', '20 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Garkörbchen herausnehmen, Curry ohne Messbecher etwas einkochen.', '5 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Salzen entnehmen, Rest salzen.', '', '', '', ''],
        ['Gurke raspeln, mit Skyr und Minze zur Raita verrühren und alles servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenes Curry mit Reis pürieren, Bohnen immer zerdrücken (Haut ggf. entfernen), Raita ohne Minze. Kleinkind (1–3 J.): Bohnen leicht anquetschen, mild ohne Chili.',
    baby: 1,
  },
  {
    id: 'vegetarische-enchiladas',
    n: 'Vegetarische Enchiladas mit schwarzen Bohnen',
    img: { wiki: 'Enchilada', q: 'vegetarian black bean enchiladas cheese' },
    ck: 'Enchiladas vegetarisch',
    cu: 'mexikanisch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['kinderliebling', 'mealprep'],
    i: [['tortilla', 60], ['schwarze_bohnen', 80], ['sojaschnetzel', 25], ['passierte_tomaten', 150], ['paprika', 80], ['zwiebel', 40], ['mais', 30], ['cheddar', 15], ['skyr', 60], ['gewuerze', 3], ['olivenoel', 4], ['kraeuter', 3]],
    s: [
      'Sojaschnetzel 10 Min. in heißem Wasser einweichen und ausdrücken. Ofen auf 200 °C Umluft vorheizen.',
      'Zwiebel und Paprika würfeln und mit den Sojaschnetzeln im Öl 6 Min. braten. Bohnen und Mais zugeben, mit der Hälfte der passierten Tomaten 5 Min. köcheln. Baby-Portion entnehmen, Rest mit Kreuzkümmel, Paprika und Oregano würzen.',
      'Füllung auf die Tortillas (für glutenfrei Maistortillas) verteilen, aufrollen und mit der Naht nach unten in eine Form legen.',
      'Restliche passierte Tomaten darübergießen und mit Cheddar bestreuen. 15–20 Min. überbacken.',
      'Mit Skyr und Koriander servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen (8 Enchiladas). Füllung im Thermomix, Überbacken im Ofen.',
      steps: [
        ['Cheddar in Stücken reiben, umfüllen.', '8 Sek.', '', 'Stufe 8', ''],
        ['Zwiebel und Paprika in den Mixtopf geben und zerkleinern.', '4 Sek.', '', 'Stufe 5', ''],
        ['Öl und eingeweichte Sojaschnetzel zugeben und andünsten.', '6 Min.', '120°C', 'Stufe 1', 'Linkslauf'],
        ['Bohnen, Mais und die Hälfte der passierten Tomaten zugeben und garen.', '6 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen, Rest würzen.', '', '', '', ''],
        ['Tortillas füllen, aufrollen, mit restlicher Tomatensauce und Cheddar 15–20 Min. bei 200 °C überbacken.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungewürzte Füllung mit zerdrückten Bohnen pürieren oder in einer weichen Tortilla-Rolle in Streifen anbieten. Kleinkind (1–3 J.): eine Enchilada mild gewürzt, in Stücke geschnitten, mit Skyr.',
    baby: 1,
  },
  {
    id: 'rahmspinat-spiegelei-kartoffeln',
    n: 'Rahmspinat mit Spiegelei & Salzkartoffeln',
    img: { wiki: 'Creamed spinach', q: 'creamed spinach fried egg potatoes' },
    ck: 'Spinat mit Ei und Kartoffeln',
    cu: 'deutsch',
    m: ['mittag', 'abend'],
    t: 30, d: 1,
    st: ['kinderliebling', 'comfort'],
    i: [['kartoffel', 250], ['spinat_tk', 250], ['ei', 120], ['milch', 60], ['frischkaese_light', 30], ['huettenkaese', 50], ['zwiebel', 30], ['knoblauch', 3], ['butter', 5], ['gewuerze', 1], ['salz', 1]],
    s: [
      'Kartoffeln schälen, vierteln und in Salzwasser 20 Min. garen.',
      'Zwiebel und Knoblauch fein würfeln und in der Hälfte der Butter 3 Min. andünsten. Spinat und Milch zugeben und 8 Min. garen.',
      'Frischkäse einrühren und alles grob pürieren. Baby-/Kleinkind-Portion entnehmen, Rest mit Muskat, Pfeffer und Salz abschmecken.',
      'Eier in der restlichen Butter zu Spiegeleiern braten (für Kinder beidseitig durchbraten).',
      'Kartoffeln mit Rahmspinat, Spiegelei und einem Klecks Hüttenkäse servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Kartoffeln im Varoma, Spiegeleier in der Pfanne.',
      steps: [
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern.', '5 Sek.', '', 'Stufe 5', ''],
        ['Butter zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Gefrorenen Spinat und Milch zugeben, Kartoffeln in den Varoma-Behälter legen, aufsetzen und garen.', '25 Min.', 'Varoma', 'Stufe 1', ''],
        ['Varoma abnehmen, Frischkäse zugeben und grob pürieren.', '10 Sek.', '', 'Stufe 5', ''],
        ['Baby-/Kleinkind-Portion entnehmen, Rest mit Muskat, Pfeffer und Salz abschmecken.', '', '', '', ''],
        ['Spiegeleier in der Pfanne braten und mit Kartoffeln und Hüttenkäse servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): ungesalzenen Rahmspinat mit Kartoffeln zerdrücken, Ei vollständig durchgaren und klein schneiden. Kleinkind (1–3 J.): Kartoffeln mit Spinat zu Brei mischen, Ei durchgebraten in Streifen.',
    baby: 2,
  },
  {
    id: 'gigantes-bohnen-feta',
    n: 'Griechische Riesenbohnen (Gigantes) mit Feta',
    img: { wiki: 'Gigantes plaki', q: 'gigantes plaki baked beans tomato feta' },
    ck: 'Gigantes',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 50, d: 1,
    st: ['mealprep', 'comfort'],
    i: [['weisse_bohnen', 220], ['feta', 45], ['tomaten_dose', 200], ['zwiebel', 50], ['karotte', 50], ['knoblauch', 4], ['tomatenmark', 10], ['olivenoel', 7], ['gewuerze', 2], ['kraeuter', 4], ['vollkornbrot', 45]],
    s: [
      'Ofen auf 190 °C Umluft vorheizen. Zwiebel, Karotte und Knoblauch fein würfeln.',
      'Öl in einer ofenfesten Pfanne erhitzen, Gemüse 6 Min. andünsten, Tomatenmark 1 Min. anrösten.',
      'Tomaten, abgespülte große weiße Bohnen, Oregano, Zimt und 100 ml Wasser zugeben und 5 Min. köcheln. Baby-/Kleinkind-Portion entnehmen.',
      'Feta in Stücken darauf verteilen und alles 25 Min. im Ofen backen, bis die Sauce eingedickt ist.',
      'Mit Dill oder Petersilie bestreuen und mit Brot (für glutenfrei glutenfreies Brot) servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Fertig backen im Ofen.',
      steps: [
        ['Zwiebel, Karotte und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Tomatenmark zugeben und andünsten.', '5 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten, Bohnen, Gewürze und 100 g Wasser zugeben und garen.', '8 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion entnehmen.', '', '', '', ''],
        ['In eine Auflaufform umfüllen, Feta darauf verteilen und 25 Min. bei 190 °C backen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Bohnen ohne Feta zerdrücken und mit Tomatensauce als Brei oder auf Brotstreifen. Kleinkind (1–3 J.): Bohnen leicht anquetschen, wenig Feta.',
    baby: 1,
  },
  {
    id: 'baked-feta-pasta-bohnen',
    n: 'Ofen-Feta-Pasta mit weißen Bohnen & Spinat',
    img: { wiki: 'Baked feta pasta', q: 'baked feta pasta cherry tomatoes' },
    ck: 'Feta Pasta',
    cu: 'mediterran',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['kinderliebling'],
    i: [['vollkornnudeln', 70], ['feta', 60], ['kirschtomaten', 200], ['weisse_bohnen', 100], ['spinat', 50], ['knoblauch', 4], ['olivenoel', 6], ['gewuerze', 1], ['kraeuter', 4], ['chili_frisch', 2]],
    s: [
      'Ofen auf 200 °C Umluft vorheizen. Kirschtomaten und Knoblauchzehen in eine Auflaufform geben, den Feta-Block in die Mitte legen, mit Öl beträufeln und mit Oregano bestreuen.',
      '25 Min. backen, bis die Tomaten aufplatzen und der Feta weich ist.',
      'Nudeln (für glutenfrei glutenfreie Nudeln) nach Packungsangabe kochen, die abgespülten Bohnen die letzte Minute mitkochen. Etwas Nudelwasser auffangen.',
      'Feta, Tomaten und Knoblauch in der Form zu einer cremigen Sauce zerdrücken. Nudeln, Bohnen, Spinat und etwas Nudelwasser unterheben.',
      'Baby-/Kleinkind-Portion entnehmen, Rest mit Chili und Basilikum servieren.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Tomaten und Feta backen im Ofen.',
      steps: [
        ['Tomaten, Knoblauch und Feta mit Öl und Oregano 25 Min. bei 200 °C im Ofen backen.', '', '', '', ''],
        ['1200 g Wasser in den Mixtopf füllen und aufkochen.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Nudeln zugeben und garen, Bohnen die letzte Minute zugeben.', '10 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Abgießen und mit der zerdrückten Feta-Tomaten-Sauce, Spinat und etwas Nudelwasser mischen.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Nudeln ohne Salz, Feta nur sehr wenig, Bohnen zerdrückt mit gebackenen Tomaten. Kleinkind (1–3 J.): ohne Chili, kurze Nudeln, Bohnen leicht anquetschen.',
    baby: 1,
  },
  {
    id: 'gemuese-tajine-kichererbsen',
    n: 'Marokkanische Gemüse-Tajine mit Kichererbsen & Couscous',
    img: { wiki: 'Tajine', q: 'vegetable tagine chickpeas couscous' },
    ck: 'Gemüse Tajine',
    cu: 'orientalisch',
    m: ['mittag', 'abend'],
    t: 45, d: 1,
    st: ['mealprep', 'comfort'],
    i: [['kichererbsen', 110], ['couscous', 45], ['griech_joghurt', 150], ['mandeln', 10], ['karotte', 80], ['zucchini', 100], ['zwiebel', 50], ['tomaten_dose', 150], ['knoblauch', 4], ['gewuerze', 4], ['olivenoel', 6], ['kraeuter', 3]],
    s: [
      'Zwiebel und Knoblauch würfeln, Karotten und Zucchini in grobe Stücke schneiden.',
      'Öl im Topf erhitzen, Zwiebel 4 Min. dünsten, Knoblauch und Ras el Hanout (Kreuzkümmel, Zimt, Koriander) 1 Min. mitrösten.',
      'Karotten, Tomaten, Kichererbsen und 150 ml Wasser zugeben und zugedeckt 15 Min. schmoren, Zucchini zugeben und weitere 8 Min. garen. Baby-/Kleinkind-Portion vor dem Salzen entnehmen.',
      'Couscous (für glutenfrei Quinoa) mit der gleichen Menge kochendem Wasser übergießen und 5 Min. quellen lassen.',
      'Tajine mit Couscous, Joghurt, gerösteten Mandelblättchen und Koriander servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen.',
      steps: [
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Gewürze zugeben und andünsten.', '4 Min.', '120°C', 'Stufe 1', ''],
        ['Karotten, Tomaten, Kichererbsen und 150 g Wasser zugeben und garen.', '15 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Zucchini zugeben und weitergaren.', '8 Min.', '100°C', 'Stufe 1', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor dem Salzen entnehmen.', '', '', '', ''],
        ['Couscous mit kochendem Wasser übergießen und quellen lassen, alles mit Joghurt und Mandeln servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): weiches Gemüse und zerdrückte Kichererbsen mit Couscous und Joghurt mischen, Mandeln nur gemahlen. Kleinkind (1–3 J.): Gemüse in Stücken, Kichererbsen angequetscht.',
    baby: 2,
  },
  {
    id: 'spinat-quark-gnudi',
    n: 'Spinat-Quark-Gnudi in Tomatensauce',
    img: { wiki: 'Gnudi', q: 'spinach ricotta gnudi tomato sauce' },
    ck: 'Gnudi',
    cu: 'italienisch',
    m: ['mittag', 'abend'],
    t: 45, d: 2,
    st: ['kinderliebling'],
    i: [['magerquark', 150], ['spinat_tk', 150], ['parmesan', 20], ['ei', 30], ['mehl', 40], ['passierte_tomaten', 200], ['zwiebel', 30], ['knoblauch', 4], ['olivenoel', 6], ['kraeuter', 4], ['gewuerze', 1], ['salz', 1]],
    s: [
      'Quark in einem Sieb 15 Min. abtropfen lassen. Spinat auftauen, sehr gut ausdrücken und fein hacken.',
      'Quark, Spinat, die Hälfte des Parmesans, Ei, Mehl (für glutenfrei glutenfreie Mehlmischung), Muskat und eine Prise Salz zu einem weichen Teig verrühren. Mit bemehlten Händen walnussgroße Kugeln formen.',
      'Für die Sauce Zwiebel und Knoblauch im Öl 3 Min. dünsten, passierte Tomaten zugeben und 10 Min. köcheln. Mit Basilikum würzen.',
      'Gnudi in siedendem Salzwasser 4–5 Min. ziehen lassen, bis sie oben schwimmen, und mit einer Schaumkelle herausheben.',
      'Gnudi in der Sauce schwenken und mit restlichem Parmesan bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Gnudi im Topf garen.',
      steps: [
        ['Parmesan in Stücken in den Mixtopf geben und reiben, umfüllen.', '10 Sek.', '', 'Stufe 10', ''],
        ['Ausgedrückten Spinat, Quark, Ei, Mehl, die Hälfte des Parmesans und Muskat zugeben und vermischen, umfüllen.', '20 Sek.', '', 'Stufe 4', ''],
        ['Zwiebel und Knoblauch in den Mixtopf geben und zerkleinern, Öl zugeben und andünsten.', '3 Min.', '120°C', 'Stufe 1', ''],
        ['Passierte Tomaten zugeben und köcheln.', '10 Min.', '100°C', 'Stufe 1', ''],
        ['Gnudi formen, in siedendem Wasser im Topf garen und in der Sauce mit Parmesan servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): Gnudi ohne Salz in ungesalzenem Wasser garen, mit wenig Parmesan; die weichen Klößchen sind tolles BLW-Fingerfood. Kleinkind (1–3 J.): halbiert mit Tomatensauce.',
    baby: 2,
  },
  {
    id: 'anda-curry-eier',
    n: 'Anda Curry (Eier-Curry) mit Spinat & Reis',
    img: { wiki: 'Egg curry', q: 'egg curry indian anda masala rice' },
    ck: 'Eier Curry',
    cu: 'indisch',
    m: ['mittag', 'abend'],
    t: 35, d: 1,
    st: ['comfort'],
    i: [['ei', 180], ['reis', 45], ['tomaten_dose', 200], ['zwiebel', 80], ['ingwer', 5], ['knoblauch', 4], ['currypulver', 5], ['rapsoel', 6], ['griech_joghurt', 50], ['spinat', 50], ['kraeuter', 3], ['chili_frisch', 2], ['salz', 1]],
    s: [
      'Eier 9 Min. hart kochen, abschrecken und pellen. Reis nach Packungsangabe garen.',
      'Zwiebel, Ingwer und Knoblauch fein hacken und im Öl 6–8 Min. goldbraun braten. Garam Masala, Kurkuma und Kreuzkümmel 1 Min. mitrösten.',
      'Tomaten und 100 ml Wasser zugeben und 10 Min. sämig köcheln. Spinat unterrühren.',
      'Eier rundum leicht einritzen und 5 Min. in der Sauce ziehen lassen. Baby-/Kleinkind-Portion vor Chili und Salz entnehmen.',
      'Joghurt unterziehen, mit Chili und Salz abschmecken und mit Koriander und Reis servieren.',
    ],
    tm: {
      fit: 2,
      note: 'Für ca. 4 Portionen. Eier im Varoma garen, Reis im Garkörbchen.',
      steps: [
        ['Zwiebel, Ingwer und Knoblauch in den Mixtopf geben und zerkleinern, nach unten schieben.', '5 Sek.', '', 'Stufe 5', ''],
        ['Öl und Gewürze zugeben und andünsten.', '6 Min.', '120°C', 'Stufe 1', ''],
        ['Tomaten und 500 g Wasser zugeben, Reis im Garkörbchen einhängen, Eier in den Varoma-Behälter legen, aufsetzen und garen.', '22 Min.', 'Varoma', 'Stufe 1', ''],
        ['Eier abschrecken und pellen, Garkörbchen herausnehmen.', '', '', '', ''],
        ['Spinat und Eier zur Sauce geben und ziehen lassen.', '4 Min.', '100°C', 'Sanftrührstufe', 'Linkslauf'],
        ['Baby-/Kleinkind-Portion vor Chili und Salz entnehmen.', '', '', '', ''],
        ['Joghurt, Chili und Salz unterrühren und mit Reis servieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): hart gekochtes Ei in Spalten als Fingerfood, Sauce ohne Chili und Salz mit Reis vermischt. Kleinkind (1–3 J.): Ei klein geschnitten in milder Sauce mit Joghurt.',
    baby: 2,
  },
  {
    id: 'okonomiyaki-raeuchertofu',
    n: 'Okonomiyaki (japanischer Kohlpfannkuchen) mit Räuchertofu',
    img: { wiki: 'Okonomiyaki', q: 'okonomiyaki cabbage pancake' },
    ck: 'Okonomiyaki',
    cu: 'asiatisch',
    m: ['mittag', 'abend'],
    t: 30, d: 2,
    i: [['weisskohl', 200], ['mehl', 40], ['ei', 120], ['raeuchertofu', 70], ['fruehlingszwiebel', 20], ['gemuesebruehe', 40], ['ingwer', 3], ['sojasauce', 8], ['ketchup', 10], ['mayo_light', 10], ['rapsoel', 6], ['sesam', 3]],
    s: [
      'Weißkohl in sehr feine Streifen schneiden, Frühlingszwiebeln in Ringe, Räuchertofu in kleine Würfel. Ingwer reiben.',
      'Mehl (für glutenfrei glutenfreie Mehlmischung), Eier und Brühe zu einem dicken Teig verrühren. Kohl, Tofu, Ingwer und die Hälfte der Frühlingszwiebeln unterheben.',
      'Öl in einer beschichteten Pfanne erhitzen, Teig zu 2 dicken Pfannkuchen formen und bei mittlerer Hitze zugedeckt 5–6 Min. pro Seite goldbraun und durchgegart braten.',
      'Für die Okonomi-Sauce Ketchup und Sojasauce verrühren (Kinderportion ohne Sauce).',
      'Pfannkuchen mit Sauce und Mayo-Streifen garnieren, mit Sesam und restlichen Frühlingszwiebeln bestreuen.',
    ],
    tm: {
      fit: 1,
      note: 'Für ca. 4 Portionen. Ausbacken in der Pfanne.',
      steps: [
        ['Ingwer in den Mixtopf geben und zerkleinern.', '3 Sek.', '', 'Stufe 8', ''],
        ['Weißkohl in Stücken zugeben und zerkleinern.', '4 Sek.', '', 'Stufe 4', ''],
        ['Mehl, Eier, Brühe, Räuchertofu und die Hälfte der Frühlingszwiebeln zugeben und vermengen.', '20 Sek.', '', 'Stufe 3', 'Linkslauf'],
        ['Teig in der Pfanne zu Pfannkuchen formen und 5–6 Min. pro Seite braten.', '', '', '', ''],
        ['Mit Ketchup-Soja-Sauce, Mayo, Sesam und Frühlingszwiebeln garnieren.', '', '', '', ''],
      ],
    },
    kid: 'Baby (6–12 Mon.): einen kleinen Pfannkuchen ohne Räuchertofu und Sauce backen, Ei vollständig durchgaren und in Streifen schneiden. Kleinkind (1–3 J.): mit wenig Sauce, in kleine Stücke geschnitten.',
    baby: 1,
  },
]);
